In [1]:
import pandas as pd

In [2]:
faq_data = [

    # =========================
    # CHECK-IN / CHECK-OUT
    # =========================

    {
        "faq_id": "FAQ001",
        "category": "Check-in",
        "question": "What time is check-in?",
        "answer": "Check-in starts at 3:00 PM.",
        "language": "English"
    },
    {
        "faq_id": "FAQ002",
        "category": "Check-out",
        "question": "What time is check-out?",
        "answer": "Check-out is at 12:00 PM.",
        "language": "English"
    },
    {
        "faq_id": "FAQ003",
        "category": "Check-in",
        "question": "Can I check in early?",
        "answer": "Early check-in is subject to room availability and hotel approval.",
        "language": "English"
    },
    {
        "faq_id": "FAQ004",
        "category": "Check-out",
        "question": "Can I check out late?",
        "answer": "Late checkout is subject to availability and may have an additional fee.",
        "language": "English"
    },

    # =========================
    # BOOKING
    # =========================

    {
        "faq_id": "FAQ005",
        "category": "Booking",
        "question": "How can I make a reservation?",
        "answer": "Guests can make a reservation through the hotel website, phone, booking platforms, or customer service agent.",
        "language": "English"
    },
    {
        "faq_id": "FAQ006",
        "category": "Booking",
        "question": "Can I modify my reservation?",
        "answer": "Yes, reservation modifications may be requested through customer service and are subject to availability.",
        "language": "English"
    },
    {
        "faq_id": "FAQ007",
        "category": "Booking",
        "question": "Can I cancel my reservation?",
        "answer": "Standard reservations can be cancelled free of charge up to 48 hours before check-in.",
        "language": "English"
    },

    # =========================
    # PAYMENTS
    # =========================

    {
        "faq_id": "FAQ008",
        "category": "Payment",
        "question": "What payment methods do you accept?",
        "answer": "The hotel accepts credit cards, debit cards, cash, bank transfers, and digital wallets.",
        "language": "English"
    },
    {
        "faq_id": "FAQ009",
        "category": "Payment",
        "question": "How long does a refund take?",
        "answer": "Approved refunds are normally processed within 5 to 10 business days.",
        "language": "English"
    },
    {
        "faq_id": "FAQ010",
        "category": "Payment",
        "question": "What happens if my payment fails?",
        "answer": "Guests can retry the payment using another supported payment method.",
        "language": "English"
    },

    # =========================
    # SERVICES
    # =========================

    {
        "faq_id": "FAQ011",
        "category": "Services",
        "question": "Is room service available?",
        "answer": "Yes, room service is available 24 hours a day.",
        "language": "English"
    },
    {
        "faq_id": "FAQ012",
        "category": "Services",
        "question": "Do you provide airport transfer?",
        "answer": "Yes, airport transfer is available upon request for 800 EGP per trip.",
        "language": "English"
    },
    {
        "faq_id": "FAQ013",
        "category": "Services",
        "question": "Is laundry service available?",
        "answer": "Yes, laundry and dry-cleaning services are available daily.",
        "language": "English"
    },
    {
        "faq_id": "FAQ014",
        "category": "Services",
        "question": "Can I request an extra bed?",
        "answer": "Yes, an extra bed can be requested depending on room capacity and availability.",
        "language": "English"
    },

    # =========================
    # FACILITIES
    # =========================

    {
        "faq_id": "FAQ015",
        "category": "Facilities",
        "question": "Does the hotel have a swimming pool?",
        "answer": "Yes, the swimming pool is available from 7:00 AM to 9:00 PM.",
        "language": "English"
    },
    {
        "faq_id": "FAQ016",
        "category": "Facilities",
        "question": "Is the gym open 24 hours?",
        "answer": "Yes, the gym is open 24/7 for hotel guests.",
        "language": "English"
    },
    {
        "faq_id": "FAQ017",
        "category": "Facilities",
        "question": "Is Wi-Fi free?",
        "answer": "Yes, free Wi-Fi is available in all rooms and public areas.",
        "language": "English"
    },
    {
        "faq_id": "FAQ018",
        "category": "Facilities",
        "question": "Does the hotel have parking?",
        "answer": "Yes, parking is available for hotel guests.",
        "language": "English"
    },

    # =========================
    # POLICIES
    # =========================

    {
        "faq_id": "FAQ019",
        "category": "Policies",
        "question": "Are pets allowed?",
        "answer": "No, pets are not allowed inside the hotel.",
        "language": "English"
    },
    {
        "faq_id": "FAQ020",
        "category": "Policies",
        "question": "Is smoking allowed inside rooms?",
        "answer": "No, smoking is not permitted inside guest rooms or indoor public areas.",
        "language": "English"
    },

    # =========================
    # ROOMS
    # =========================

    {
        "faq_id": "FAQ021",
        "category": "Rooms",
        "question": "How many guests can stay in a suite?",
        "answer": "A suite can accommodate up to 4 guests.",
        "language": "English"
    },
    {
        "faq_id": "FAQ022",
        "category": "Rooms",
        "question": "What amenities are available in the rooms?",
        "answer": "Rooms include free Wi-Fi, air conditioning, a private bathroom, television, housekeeping, toiletries, and towels.",
        "language": "English"
    }
]

In [3]:
faq_df = pd.DataFrame(faq_data)

faq_df.head()

,faq_id,category,question,answer,language
0,FAQ001,Check-in,What time is check-in?,Check-in starts at 3:00 PM.,English
1,FAQ002,Check-out,What time is check-out?,Check-out is at 12:00 PM.,English
2,FAQ003,Check-in,Can I check in early?,Early check-in is subject to room availability...,English
3,FAQ004,Check-out,Can I check out late?,Late checkout is subject to availability and m...,English
4,FAQ005,Booking,How can I make a reservation?,Guests can make a reservation through the hote...,English

In [4]:
print("Number of FAQs:", len(faq_df))

Number of FAQs: 22

In [6]:
import os

print(os.getcwd())

c:\Users\User\OneDrive\سطح المكتب\HotelAI

In [7]:
import os

output_dir = "03_Structured_Data/CSV"

os.makedirs(output_dir, exist_ok=True)

faq_df.to_csv(
    os.path.join(output_dir, "hotel_faq.csv"),
    index=False,
    encoding="utf-8-sig"
)

print("Saved successfully!")

Saved successfully!

In [8]:
languages = [
    "English",
    "Arabic",
    "French",
    "Russian"
]

print(languages)

['English', 'Arabic', 'French', 'Russian']

In [9]:
categories = [
    "Hotel Information",
    "Rooms",
    "Booking",
    "Cancellation",
    "Check-in and Check-out",
    "Restaurant",
    "Breakfast",
    "Facilities",
    "Wi-Fi",
    "Parking",
    "Transportation",
    "Room Service",
    "Housekeeping",
    "Payment",
    "Policies",
    "Complaints"
]

print(categories)

['Hotel Information', 'Rooms', 'Booking', 'Cancellation', 'Check-in and Check-out', 'Restaurant', 'Breakfast', 'Facilities', 'Wi-Fi', 'Parking', 'Transportation', 'Room Service', 'Housekeeping', 'Payment', 'Policies', 'Complaints']

In [10]:
columns = [
    "language",
    "category",
    "question",
    "answer",
    "source"
]

print(columns)

['language', 'category', 'question', 'answer', 'source']

In [11]:
import pandas as pd

faq_df = pd.DataFrame(columns=columns)

print(faq_df.head())

Empty DataFrame
Columns: [language, category, question, answer, source]
Index: []

In [12]:
prompt_template = """
You are generating a multilingual FAQ dataset for a hotel AI assistant.

Hotel information:
{hotel_information}

Category:
{category}

Generate one high-quality FAQ pair.

Language:
{language}

Requirements:
- The question must be natural and realistic.
- The answer must be accurate and based ONLY on the provided hotel information.
- Do not invent hotel policies, prices, services, or facilities.
- Do not add information that is not present in the source.
- Keep the answer clear and concise.
- Return only the question and answer.

Format:

Question: ...
Answer: ...
"""

print(prompt_template)

You are generating a multilingual FAQ dataset for a hotel AI assistant.

Hotel information:
{hotel_information}

Category:
{category}

Generate one high-quality FAQ pair.

Language:
{language}

Requirements:
- The question must be natural and realistic.
- The answer must be accurate and based ONLY on the provided hotel information.
- Do not invent hotel policies, prices, services, or facilities.
- Do not add information that is not present in the source.
- Keep the answer clear and concise.
- Return only the question and answer.

Format:

Question: ...
Answer: ...

In [13]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\User\OneDrive\سطح المكتب\HotelAI
['02_Hotel_Knowledge', '03_Structured_Data', 'data', 'database', 'generate_hotel_faq.ipynb', 'README.md', 'scripts']

In [14]:
knowledge_path = "02_Hotel_Knowledge"

print(os.listdir(knowledge_path))

['DOCX', 'PDF', 'TXT']

In [15]:
import os

for folder in ["DOCX", "PDF", "TXT"]:
    folder_path = os.path.join("02_Hotel_Knowledge", folder)
    
    print(f"\n--- {folder} ---")
    
    files = os.listdir(folder_path)
    
    for file in files:
        print(file)

--- DOCX ---
hotel_services.docx
room_information.docx

--- PDF ---
cancellation_policy.pdf
hotel_policies.pdf
payment_refund_policy.pdf

--- TXT ---
faq.txt
hotel_information.txt

In [18]:
import os
from docx import Document
from pypdf import PdfReader

In [19]:
def read_txt(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        return file.read()


def read_docx(file_path):
    document = Document(file_path)
    return "\n".join(
        paragraph.text
        for paragraph in document.paragraphs
        if paragraph.text.strip()
    )


def read_pdf(file_path):
    reader = PdfReader(file_path)
    
    text = []
    
    for page in reader.pages:
        page_text = page.extract_text()
        
        if page_text:
            text.append(page_text)
    
    return "\n".join(text)

In [20]:
knowledge_path = "02_Hotel_Knowledge"

hotel_knowledge = []

for folder in ["TXT", "DOCX", "PDF"]:
    
    folder_path = os.path.join(knowledge_path, folder)
    
    for file_name in os.listdir(folder_path):
        
        file_path = os.path.join(folder_path, file_name)
        
        if folder == "TXT":
            content = read_txt(file_path)
            
        elif folder == "DOCX":
            content = read_docx(file_path)
            
        elif folder == "PDF":
            content = read_pdf(file_path)
        
        hotel_knowledge.append({
            "source": file_name,
            "content": content
        })

print(f"Loaded {len(hotel_knowledge)} documents")

PackageNotFoundError: Package not found at '02_Hotel_Knowledge\DOCX\hotel_services.docx'

In [21]:
import os

docx_path = "02_Hotel_Knowledge/DOCX"

for file_name in os.listdir(docx_path):
    file_path = os.path.join(docx_path, file_name)
    
    print(f"File: {file_name}")
    print(f"Exists: {os.path.exists(file_path)}")
    print(f"Size: {os.path.getsize(file_path)} bytes")
    print("-" * 40)

File: hotel_services.docx
Exists: True
Size: 1776 bytes
----------------------------------------
File: room_information.docx
Exists: True
Size: 2073 bytes
----------------------------------------

In [22]:
import zipfile

for file_name in ["hotel_services.docx", "room_information.docx"]:
    
    file_path = os.path.join(
        "02_Hotel_Knowledge",
        "DOCX",
        file_name
    )
    
    print(f"\n{file_name}")
    print("Is valid DOCX:", zipfile.is_zipfile(file_path))

hotel_services.docx
Is valid DOCX: False

room_information.docx
Is valid DOCX: False

In [23]:
for file_name in ["hotel_services.docx", "room_information.docx"]:
    
    file_path = os.path.join(
        "02_Hotel_Knowledge",
        "DOCX",
        file_name
    )
    
    print("\n" + "=" * 60)
    print(file_name)
    print("=" * 60)
    
    with open(file_path, "rb") as file:
        content = file.read()
    
    print(content[:1000])

============================================================
hotel_services.docx
============================================================
b'NILE PEARL HOTEL\r\nHOTEL SERVICES GUIDE\r\n\r\n1. Breakfast\r\n\r\nService: Daily Breakfast\r\nTime: 7:00 AM - 10:30 AM\r\nLocation: Main Restaurant\r\nPrice: 450 EGP per person\r\n\r\nBreakfast includes a variety of hot and cold food, beverages, pastries, and fresh fruit.\r\n\r\n2. Room Service\r\n\r\nService: 24/7 Room Service\r\nAvailability: Available 24 hours\r\nPrice: Depends on the selected order\r\n\r\nGuests can order food and beverages directly to their rooms.\r\n\r\n3. Airport Transfer\r\n\r\nService: Airport Transfer\r\nAvailability: Upon Request\r\nPrice: 800 EGP per trip\r\n\r\nPrivate airport pickup and drop-off are available. Guests should request the service in advance.\r\n\r\n4. Laundry\r\n\r\nService: Laundry and Dry Cleaning\r\nAvailability: Daily\r\nPrice: 200 EGP per kilogram\r\n\r\nGuests can request laundry service through the front desk or customer service.\r\n\r\n5. Spa\r\n\r\nService: Spa Treatment\r\nAvailability: 9:00 AM - 10:00 PM\r\nPrice: 1,200 EGP per session\r\n\r\nThe hotel spa provides relaxation and wellness treatments.\r\n\r\n6. Gym\r'

============================================================
room_information.docx
============================================================
b'NILE PEARL HOTEL\r\nROOM INFORMATION GUIDE\r\n\r\n1. Standard Room\r\n\r\nRoom Type: Standard Room\r\nCapacity: 2 Guests\r\nDescription:\r\nA comfortable room suitable for individuals or couples. The room includes a comfortable bed, private bathroom, Wi-Fi, air conditioning, television, and basic room amenities.\r\n\r\n2. Deluxe Room\r\n\r\nRoom Type: Deluxe Room\r\nCapacity: 2 Guests\r\nDescription:\r\nA spacious room with upgraded furnishings and additional comfort. It includes a private bathroom, Wi-Fi, air conditioning, television, and enhanced room amenities.\r\n\r\n3. Superior Room\r\n\r\nRoom Type: Superior Room\r\nCapacity: 3 Guests\r\nDescription:\r\nA larger room suitable for couples or small families. The room provides additional space and upgraded amenities.\r\n\r\n4. Family Room\r\n\r\nRoom Type: Family Room\r\nCapacity: 4 Guests\r\nDescription:\r\nA spacious room designed for families. It provides additional sleeping capacity and suitable facilities for families with children.\r\n\r\n5. Executive Room\r\n\r\nRoom Type: Executive Room\r\nC'

In [24]:
def read_docx(file_path):
    try:
        document = Document(file_path)
        
        return "\n".join(
            paragraph.text
            for paragraph in document.paragraphs
            if paragraph.text.strip()
        )
    
    except Exception:
        with open(file_path, "r", encoding="utf-8") as file:
            return file.read()

In [28]:
def read_pdf(file_path):
    try:
        reader = PdfReader(file_path)

        text = []

        for page in reader.pages:
            page_text = page.extract_text()

            if page_text:
                text.append(page_text)

        return "\n".join(text)

    except Exception:
        with open(file_path, "r", encoding="utf-8") as file:
            return file.read()

In [29]:
def read_docx(file_path):
    try:
        document = Document(file_path)

        return "\n".join(
            paragraph.text
            for paragraph in document.paragraphs
            if paragraph.text.strip()
        )

    except Exception:
        with open(file_path, "r", encoding="utf-8") as file:
            return file.read()

In [30]:
knowledge_path = "02_Hotel_Knowledge"

hotel_knowledge = []

for folder in ["TXT", "DOCX", "PDF"]:

    folder_path = os.path.join(knowledge_path, folder)

    for file_name in os.listdir(folder_path):

        file_path = os.path.join(folder_path, file_name)

        if folder == "TXT":
            content = read_txt(file_path)

        elif folder == "DOCX":
            content = read_docx(file_path)

        elif folder == "PDF":
            content = read_pdf(file_path)

        hotel_knowledge.append({
            "source": file_name,
            "content": content
        })

print(f"Loaded {len(hotel_knowledge)} documents")

invalid pdf header: b'NILE '
EOF marker not found
invalid pdf header: b'NILE '
EOF marker not found
invalid pdf header: b'NILE '
EOF marker not found

Loaded 7 documents

In [31]:
print("Files in Knowledge Base:")

for folder in ["TXT", "DOCX", "PDF"]:
    
    folder_path = os.path.join("02_Hotel_Knowledge", folder)
    
    print(f"\n--- {folder} ---")
    
    for file_name in os.listdir(folder_path):
        print(file_name)

Files in Knowledge Base:

--- TXT ---
faq.txt
hotel_information.txt

--- DOCX ---
hotel_services.docx
room_information.docx

--- PDF ---
cancellation_policy.pdf
hotel_policies.pdf
payment_refund_policy.pdf

In [32]:
for document in hotel_knowledge:
    print(
        f"{document['source']} → "
        f"{len(document['content'])} characters"
    )

faq.txt → 952 characters
hotel_information.txt → 525 characters
hotel_services.docx → 1700 characters
room_information.docx → 1999 characters
cancellation_policy.pdf → 1088 characters
hotel_policies.pdf → 1624 characters
payment_refund_policy.pdf → 1302 characters

In [33]:
knowledge_text = ""

for document in hotel_knowledge:
    knowledge_text += (
        f"\n\n===== SOURCE: {document['source']} =====\n\n"
        f"{document['content']}"
    )

print(knowledge_text[:3000])

===== SOURCE: faq.txt =====

HOTEL FAQ

Q: What time is check-in?
A: Check-in starts at 3:00 PM.

Q: What time is check-out?
A: Check-out is at 12:00 PM.

Q: Is the reception open 24 hours?
A: Yes, the hotel reception is available 24/7.

Q: Is breakfast available?
A: Yes, breakfast is available daily from 7:00 AM to 10:30 AM.

Q: Is Wi-Fi free?
A: Yes, free Wi-Fi is available in all rooms and public areas.

Q: Does the hotel have parking?
A: Yes, parking is available for hotel guests.

Q: Does the hotel have a swimming pool?
A: Yes, the swimming pool is available from 7:00 AM to 9:00 PM.

Q: Is the gym available 24 hours?
A: Yes, the gym is open 24/7.

Q: Does the hotel provide airport transfer?
A: Yes, airport transfer is available upon request.

Q: Is room service available?
A: Yes, room service is available 24/7.

Q: Are pets allowed?
A: No, pets are not allowed.

Q: What languages does the hotel support?
A: The hotel supports Arabic, English, French, and Russian.

===== SOURCE: hotel_information.txt =====

HOTEL INFORMATION

Hotel Name:
Nile Pearl Hotel

Location:
Cairo, Egypt

Hotel Category:
5-Star Hotel

Check-in:
3:00 PM

Check-out:
12:00 PM

Reception:
24/7

Breakfast:
7:00 AM - 10:30 AM

Free Wi-Fi:
Available in all rooms and public areas.

Parking:
Available for hotel guests.

Swimming Pool:
Available from 7:00 AM to 9:00 PM.

Gym:
Open 24/7 for hotel guests.

Airport Transfer:
Available upon request.

Room Service:
Available 24/7.

Pets:
Pets are not allowed.

Languages Supported:
Arabic, English, French, Russian.

===== SOURCE: hotel_services.docx =====

NILE PEARL HOTEL
HOTEL SERVICES GUIDE

1. Breakfast

Service: Daily Breakfast
Time: 7:00 AM - 10:30 AM
Location: Main Restaurant
Price: 450 EGP per person

Breakfast includes a variety of hot and cold food, beverages, pastries, and fresh fruit.

2. Room Service

Service: 24/7 Room Service
Availability: Available 24 hours
Price: Depends on the selected order

Guests can order food and beverages directly to their rooms.

3. Airport Transfer

Service: Airport Transfer
Availability: Upon Request
Price: 800 EGP per trip

Private airport pickup and drop-off are available. Guests should request the service in advance.

4. Laundry

Service: Laundry and Dry Cleaning
Availability: Daily
Price: 200 EGP per kilogram

Guests can request laundry service through the front desk or customer service.

5. Spa

Service: Spa Treatment
Availability: 9:00 AM - 10:00 PM
Price: 1,200 EGP per session

The hotel spa provides relaxation and wellness treatments.

6. Gym

Service: Fitness Center
Availability: 24/7
Price: 300 EGP per day

Hotel guests can access the fitness center throughout the day.

7. Extra Bed

Service: Extra Bed
Availability: Upon Request
Price: 600 EGP per night

An additional bed can be provided depending on room capacity and availability.

8. Late Checkout

Service: Late Checkout
Availability: Upon Request
Price: 500 EGP per request

Late checkout is subject to room availability and hote

In [34]:
print("Total characters:", len(knowledge_text))

Total characters: 9492

In [35]:
columns = [
    "faq_id",
    "category",
    "question",
    "answer",
    "language"
]

faq_df = pd.DataFrame(columns=columns)

print(faq_df)

Empty DataFrame
Columns: [faq_id, category, question, answer, language]
Index: []

In [36]:
faq_id = "FAQ001"
category = "Check-in"

print(faq_id)
print(category)

FAQ001
Check-in

In [37]:
checkin_knowledge = ""

for document in hotel_knowledge:
    if document["source"] in ["hotel_information.txt", "hotel_policies.pdf"]:
        checkin_knowledge += "\n" + document["content"]

print(checkin_knowledge)

HOTEL INFORMATION

Hotel Name:
Nile Pearl Hotel

Location:
Cairo, Egypt

Hotel Category:
5-Star Hotel

Check-in:
3:00 PM

Check-out:
12:00 PM

Reception:
24/7

Breakfast:
7:00 AM - 10:30 AM

Free Wi-Fi:
Available in all rooms and public areas.

Parking:
Available for hotel guests.

Swimming Pool:
Available from 7:00 AM to 9:00 PM.

Gym:
Open 24/7 for hotel guests.

Airport Transfer:
Available upon request.

Room Service:
Available 24/7.

Pets:
Pets are not allowed.

Languages Supported:
Arabic, English, French, Russian.
NILE PEARL HOTEL
GENERAL HOTEL POLICIES

1. Check-in Policy

Standard check-in time is 3:00 PM.

Guests must provide valid identification during check-in.

Early check-in is subject to room availability and hotel approval.

2. Check-out Policy

Standard check-out time is 12:00 PM.

Late checkout is subject to availability and may incur an additional fee.

3. Identification Policy

Guests are required to provide valid identification documents during check-in.

4. Smoking Policy

Smoking is not permitted inside guest rooms or indoor public areas.

Designated smoking areas are available.

5. Pet Policy

Pets are not allowed inside the hotel.

6. Guest Conduct

Guests are expected to respect hotel property, staff, and other guests.

Any damage caused to hotel property may result in additional charges.

7. Children Policy

Children are welcome at the hotel.

Extra beds or additional accommodation for children are subject to room capacity and availability.

8. Noise Policy

Guests should maintain reasonable noise levels, especially during nighttime hours.

9. Lost and Found

Items found on hotel property are handled by the hotel Lost and Found department.

Guests should contact the front desk if they lose an item.

10. Privacy

Guest information is handled according to hotel privacy and security procedures.

11. Emergency

In case of an emergency, guests should contact the hotel reception immediately.

The hotel reception operates 24/7.

12. Policy Updates

Hotel policies may be updated by hotel management when necessary.

Guests may contact customer service for clarification regarding any hotel policy.

In [38]:
faq_rows = [
    {
        "faq_id": "FAQ001",
        "category": "Check-in",
        "question": "What time is check-in?",
        "answer": "Standard check-in time is 3:00 PM.",
        "language": "English"
    },
    {
        "faq_id": "FAQ001",
        "category": "Check-in",
        "question": "متى يبدأ تسجيل الوصول؟",
        "answer": "يبدأ تسجيل الوصول في الساعة 3:00 مساءً.",
        "language": "Arabic"
    },
    {
        "faq_id": "FAQ001",
        "category": "Check-in",
        "question": "À quelle heure commence l'enregistrement ?",
        "answer": "L'enregistrement standard commence à 15h00.",
        "language": "French"
    },
    {
        "faq_id": "FAQ001",
        "category": "Check-in",
        "question": "Во сколько начинается регистрация?",
        "answer": "Стандартная регистрация начинается в 15:00.",
        "language": "Russian"
    }
]

faq_df = pd.DataFrame(faq_rows)

print(faq_df)

   faq_id  category                                    question  \
0  FAQ001  Check-in                      What time is check-in?
1  FAQ001  Check-in                      متى يبدأ تسجيل الوصول؟
2  FAQ001  Check-in  À quelle heure commence l'enregistrement ?
3  FAQ001  Check-in          Во сколько начинается регистрация?

                                        answer language
0           Standard check-in time is 3:00 PM.  English
1      يبدأ تسجيل الوصول في الساعة 3:00 مساءً.   Arabic
2  L'enregistrement standard commence à 15h00.   French
3  Стандартная регистрация начинается в 15:00.  Russian

In [39]:
faqs_per_category = 5

print("FAQs per category:", faqs_per_category)
print("Languages:", len(languages))
print("Categories:", len(categories))

total_rows = (
    faqs_per_category
    * len(categories)
    * len(languages)
)

print("Expected total rows:", total_rows)

FAQs per category: 5
Languages: 4
Categories: 16
Expected total rows: 320

In [40]:
category_sources = {
    "Hotel Information": [
        "hotel_information.txt"
    ],
    
    "Rooms": [
        "room_information.docx"
    ],
    
    "Booking": [
        "faq.txt"
    ],
    
    "Cancellation": [
        "cancellation_policy.pdf"
    ],
    
    "Check-in and Check-out": [
        "hotel_information.txt",
        "hotel_policies.pdf"
    ],
    
    "Breakfast": [
        "hotel_services.docx"
    ],
    
    "Restaurant": [
        "hotel_services.docx"
    ],
    
    "Facilities": [
        "hotel_information.txt",
        "hotel_services.docx"
    ],
    
    "Wi-Fi": [
        "hotel_information.txt"
    ],
    
    "Parking": [
        "hotel_information.txt"
    ],
    
    "Transportation": [
        "hotel_services.docx",
        "hotel_information.txt"
    ],
    
    "Room Service": [
        "hotel_services.docx"
    ],
    
    "Housekeeping": [
        "hotel_services.docx"
    ],
    
    "Payment": [
        "payment_refund_policy.pdf"
    ],
    
    "Hotel Policies": [
        "hotel_policies.pdf"
    ],
    
    "Complaints": [
        "faq.txt"
    ]
}

print(category_sources)

{'Hotel Information': ['hotel_information.txt'], 'Rooms': ['room_information.docx'], 'Booking': ['faq.txt'], 'Cancellation': ['cancellation_policy.pdf'], 'Check-in and Check-out': ['hotel_information.txt', 'hotel_policies.pdf'], 'Breakfast': ['hotel_services.docx'], 'Restaurant': ['hotel_services.docx'], 'Facilities': ['hotel_information.txt', 'hotel_services.docx'], 'Wi-Fi': ['hotel_information.txt'], 'Parking': ['hotel_information.txt'], 'Transportation': ['hotel_services.docx', 'hotel_information.txt'], 'Room Service': ['hotel_services.docx'], 'Housekeeping': ['hotel_services.docx'], 'Payment': ['payment_refund_policy.pdf'], 'Hotel Policies': ['hotel_policies.pdf'], 'Complaints': ['faq.txt']}

In [41]:
for category, sources in category_sources.items():
    print(f"{category}: {sources}")

Hotel Information: ['hotel_information.txt']
Rooms: ['room_information.docx']
Booking: ['faq.txt']
Cancellation: ['cancellation_policy.pdf']
Check-in and Check-out: ['hotel_information.txt', 'hotel_policies.pdf']
Breakfast: ['hotel_services.docx']
Restaurant: ['hotel_services.docx']
Facilities: ['hotel_information.txt', 'hotel_services.docx']
Wi-Fi: ['hotel_information.txt']
Parking: ['hotel_information.txt']
Transportation: ['hotel_services.docx', 'hotel_information.txt']
Room Service: ['hotel_services.docx']
Housekeeping: ['hotel_services.docx']
Payment: ['payment_refund_policy.pdf']
Hotel Policies: ['hotel_policies.pdf']
Complaints: ['faq.txt']

In [42]:
def get_category_knowledge(category):
    sources = category_sources[category]
    
    knowledge = []
    
    for document in hotel_knowledge:
        if document["source"] in sources:
            knowledge.append(
                f"Source: {document['source']}\n"
                f"{document['content']}"
            )
    
    return "\n\n".join(knowledge)


checkin_knowledge = get_category_knowledge(
    "Check-in and Check-out"
)

print(checkin_knowledge)

Source: hotel_information.txt
HOTEL INFORMATION

Hotel Name:
Nile Pearl Hotel

Location:
Cairo, Egypt

Hotel Category:
5-Star Hotel

Check-in:
3:00 PM

Check-out:
12:00 PM

Reception:
24/7

Breakfast:
7:00 AM - 10:30 AM

Free Wi-Fi:
Available in all rooms and public areas.

Parking:
Available for hotel guests.

Swimming Pool:
Available from 7:00 AM to 9:00 PM.

Gym:
Open 24/7 for hotel guests.

Airport Transfer:
Available upon request.

Room Service:
Available 24/7.

Pets:
Pets are not allowed.

Languages Supported:
Arabic, English, French, Russian.

Source: hotel_policies.pdf
NILE PEARL HOTEL
GENERAL HOTEL POLICIES

1. Check-in Policy

Standard check-in time is 3:00 PM.

Guests must provide valid identification during check-in.

Early check-in is subject to room availability and hotel approval.

2. Check-out Policy

Standard check-out time is 12:00 PM.

Late checkout is subject to availability and may incur an additional fee.

3. Identification Policy

Guests are required to provide valid identification documents during check-in.

4. Smoking Policy

Smoking is not permitted inside guest rooms or indoor public areas.

Designated smoking areas are available.

5. Pet Policy

Pets are not allowed inside the hotel.

6. Guest Conduct

Guests are expected to respect hotel property, staff, and other guests.

Any damage caused to hotel property may result in additional charges.

7. Children Policy

Children are welcome at the hotel.

Extra beds or additional accommodation for children are subject to room capacity and availability.

8. Noise Policy

Guests should maintain reasonable noise levels, especially during nighttime hours.

9. Lost and Found

Items found on hotel property are handled by the hotel Lost and Found department.

Guests should contact the front desk if they lose an item.

10. Privacy

Guest information is handled according to hotel privacy and security procedures.

11. Emergency

In case of an emergency, guests should contact the hotel reception immediately.

The hotel reception operates 24/7.

12. Policy Updates

Hotel policies may be updated by hotel management when necessary.

Guests may contact customer service for clarification regarding any hotel policy.

In [43]:
import os

ROOT = os.getcwd()

print("=" * 70)
print("HOTEL AI - PROJECT STRUCTURE")
print("=" * 70)

def print_tree(path, prefix=""):
    items = sorted(os.listdir(path))

    for i, item in enumerate(items):
        full_path = os.path.join(path, item)

        is_last = i == len(items) - 1
        connector = "└── " if is_last else "├── "

        print(prefix + connector + item)

        if os.path.isdir(full_path):
            extension = "    " if is_last else "│   "
            print_tree(full_path, prefix + extension)


print_tree(ROOT)

======================================================================
HOTEL AI - PROJECT STRUCTURE
======================================================================
├── 02_Hotel_Knowledge
│   ├── DOCX
│   │   ├── hotel_services.docx
│   │   └── room_information.docx
│   ├── PDF
│   │   ├── cancellation_policy.pdf
│   │   ├── hotel_policies.pdf
│   │   └── payment_refund_policy.pdf
│   └── TXT
│       ├── faq.txt
│       └── hotel_information.txt
├── 03_Structured_Data
│   ├── CSV
│   │   └── hotel_faq.csv
│   ├── Excel
│   └── JSON
│       └── 03_Structured_Data
│           └── JSON
│               └── hotel_config.json
├── README.md
├── data
│   ├── bookings.csv
│   ├── customer_requests.csv
│   ├── customers.csv
│   ├── payments.csv
│   ├── room_types.csv
│   ├── rooms.csv
│   └── services.csv
├── database
│   └── hotel_ai_final_backup.backup
├── generate_hotel_faq.ipynb
└── scripts
    ├── generate_bookings.ipynb
    ├── generate_customer_requests.ipynb
    ├── generate_customers.ipynb
    ├── generate_payments.ipynb
    ├── generate_room_types.ipynb
    ├── generate_rooms.ipynb
    ├── generate_services.ipynb
    └── validate_hotel_data.ipynb

In [44]:
import os

knowledge_path = "02_Hotel_Knowledge"

folders = [
    "Hotel_Information",
    "Rooms",
    "Booking",
    "Services",
    "Policies",
    "Payment",
    "Cancellation"
]

for folder in folders:
    folder_path = os.path.join(knowledge_path, folder)
    os.makedirs(folder_path, exist_ok=True)

print("Hotel Knowledge structure created successfully.")

for folder in folders:
    print(f"✓ {folder}")

Hotel Knowledge structure created successfully.
✓ Hotel_Information
✓ Rooms
✓ Booking
✓ Services
✓ Policies
✓ Payment
✓ Cancellation

In [46]:
import os

knowledge_path = "02_Hotel_Knowledge"

print("=" * 70)
print("HOTEL KNOWLEDGE BASE - STRUCTURE CHECK")
print("=" * 70)

expected_structure = {
    "Hotel_Information": [
        "hotel_information.txt",
        "contact_information.txt",
        "hotel_facilities.txt"
    ],
    
    "Rooms": [
        "room_types.txt",
        "room_amenities.txt",
        "room_policies.txt"
    ],
    
    "Booking": [
        "booking_policy.txt",
        "booking_process.txt",
        "booking_modification.txt",
        "booking_confirmation.txt"
    ],
    
    "Payment": [
        "payment_methods.txt",
        "payment_policy.txt",
        "refund_policy.txt"
    ],
    
    "Cancellation": [
        "cancellation_policy.txt",
        "cancellation_process.txt"
    ],
    
    "Services": [],
    "Policies": []
}


all_correct = True

for folder, files in expected_structure.items():

    folder_path = os.path.join(
        knowledge_path,
        folder
    )

    print(f"\n📁 {folder}")

    if not os.path.exists(folder_path):
        print("   ❌ Folder does not exist")
        all_correct = False
        continue

    print("   ✅ Folder exists")

    for file_name in files:

        file_path = os.path.join(
            folder_path,
            file_name
        )

        if os.path.exists(file_path):
            size = os.path.getsize(file_path)

            if size > 0:
                print(f"   ✅ {file_name} ({size} bytes)")
            else:
                print(f"   ⚠️ {file_name} is EMPTY")
                all_correct = False

        else:
            print(f"   ❌ Missing: {file_name}")
            all_correct = False


print("\n" + "=" * 70)

if all_correct:
    print("✅ STRUCTURE CHECK PASSED")
else:
    print("⚠️ STRUCTURE NEEDS ATTENTION")

======================================================================
HOTEL KNOWLEDGE BASE - STRUCTURE CHECK
======================================================================

📁 Hotel_Information
   ✅ Folder exists
   ✅ hotel_information.txt (588 bytes)
   ✅ contact_information.txt (776 bytes)
   ✅ hotel_facilities.txt (1240 bytes)

📁 Rooms
   ✅ Folder exists
   ✅ room_types.txt (1213 bytes)
   ✅ room_amenities.txt (964 bytes)
   ✅ room_policies.txt (1130 bytes)

📁 Booking
   ✅ Folder exists
   ✅ booking_policy.txt (1706 bytes)
   ✅ booking_process.txt (999 bytes)
   ✅ booking_modification.txt (1453 bytes)
   ✅ booking_confirmation.txt (1011 bytes)

📁 Payment
   ✅ Folder exists
   ✅ payment_methods.txt (894 bytes)
   ✅ payment_policy.txt (1024 bytes)
   ✅ refund_policy.txt (967 bytes)

📁 Cancellation
   ✅ Folder exists
   ✅ cancellation_policy.txt (1819 bytes)
   ✅ cancellation_process.txt (1129 bytes)

📁 Services
   ✅ Folder exists

📁 Policies
   ✅ Folder exists

======================================================================
✅ STRUCTURE CHECK PASSED

In [47]:
import os

knowledge_path = "02_Hotel_Knowledge"

expected_structure = {
    "Hotel_Information": [
        "hotel_information.txt",
        "contact_information.txt",
        "hotel_facilities.txt"
    ],
    "Rooms": [
        "room_types.txt",
        "room_amenities.txt",
        "room_policies.txt"
    ],
    "Booking": [
        "booking_policy.txt",
        "booking_process.txt",
        "booking_modification.txt",
        "booking_confirmation.txt"
    ],
    "Payment": [
        "payment_methods.txt",
        "payment_policy.txt",
        "refund_policy.txt"
    ],
    "Cancellation": [
        "cancellation_policy.txt",
        "cancellation_process.txt"
    ],
    "Services": [],
    "Policies": []
}

missing = []
empty = []

for folder, files in expected_structure.items():

    folder_path = os.path.join(knowledge_path, folder)

    if not os.path.isdir(folder_path):
        missing.append(f"Folder: {folder}")
        continue

    for file_name in files:

        file_path = os.path.join(folder_path, file_name)

        if not os.path.isfile(file_path):
            missing.append(f"{folder}/{file_name}")

        elif os.path.getsize(file_path) == 0:
            empty.append(f"{folder}/{file_name}")


print("=" * 70)
print("FINAL KNOWLEDGE BASE CHECK")
print("=" * 70)

if not missing and not empty:
    print("✅ ALL REQUIRED FILES EXIST")
    print("✅ ALL FILES CONTAIN DATA")
    print("✅ STRUCTURE PASSED")
else:

    if missing:
        print("\n❌ MISSING:")
        for item in missing:
            print("   -", item)

    if empty:
        print("\n⚠️ EMPTY:")
        for item in empty:
            print("   -", item)

print("=" * 70)

======================================================================
FINAL KNOWLEDGE BASE CHECK
======================================================================
✅ ALL REQUIRED FILES EXIST
✅ ALL FILES CONTAIN DATA
✅ STRUCTURE PASSED
======================================================================

In [48]:
import os

services_path = os.path.join(
    "02_Hotel_Knowledge",
    "Services"
)

print("=" * 60)
print("SERVICES CHECK")
print("=" * 60)

for file_name in sorted(os.listdir(services_path)):

    file_path = os.path.join(services_path, file_name)

    if os.path.isfile(file_path):
        size = os.path.getsize(file_path)

        print(f"✅ {file_name} ({size} bytes)")

print("=" * 60)

============================================================
SERVICES CHECK
============================================================
✅ airport_transfer.txt (445 bytes)
✅ breakfast.txt (517 bytes)
✅ gym.txt (334 bytes)
✅ laundry.txt (455 bytes)
✅ room_service.txt (442 bytes)
✅ spa.txt (437 bytes)
============================================================

In [49]:
import os

policies_path = os.path.join(
    "02_Hotel_Knowledge",
    "Policies"
)

print("=" * 60)
print("POLICIES CHECK")
print("=" * 60)

files = sorted(
    file_name
    for file_name in os.listdir(policies_path)
    if os.path.isfile(os.path.join(policies_path, file_name))
)

for file_name in files:
    file_path = os.path.join(policies_path, file_name)
    size = os.path.getsize(file_path)
    print(f"✅ {file_name} ({size} bytes)")

print("=" * 60)
print(f"Total policy files: {len(files)}")

============================================================
POLICIES CHECK
============================================================
✅ check_in_check_out.txt (550 bytes)
✅ children_policy.txt (335 bytes)
✅ emergency_policy.txt (309 bytes)
✅ guest_conduct.txt (321 bytes)
✅ identification_policy.txt (401 bytes)
✅ lost_and_found.txt (365 bytes)
✅ noise_policy.txt (258 bytes)
✅ pet_policy.txt (217 bytes)
✅ privacy_policy.txt (421 bytes)
✅ smoking_policy.txt (259 bytes)
============================================================
Total policy files: 10

In [50]:
import os

knowledge_path = "02_Hotel_Knowledge"

print("=" * 80)
print("HOTEL AI - FULL KNOWLEDGE BASE AUDIT")
print("=" * 80)

total_files = 0
total_characters = 0
total_words = 0

empty_files = []
small_files = []

for root, dirs, files in os.walk(knowledge_path):

    for file_name in sorted(files):

        file_path = os.path.join(root, file_name)

        # Only analyze text files
        if not file_name.lower().endswith(".txt"):
            continue

        total_files += 1

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()

        characters = len(content)
        words = len(content.split())

        total_characters += characters
        total_words += words

        relative_path = os.path.relpath(
            file_path,
            knowledge_path
        )

        print(f"\n📄 {relative_path}")
        print(f"   Characters: {characters}")
        print(f"   Words:      {words}")

        if characters == 0:
            empty_files.append(relative_path)

        elif characters < 200:
            small_files.append(relative_path)


print("\n" + "=" * 80)
print("SUMMARY")
print("=" * 80)

print(f"Total TXT files:       {total_files}")
print(f"Total characters:      {total_characters}")
print(f"Total words:           {total_words}")

print("\nEmpty files:")

if empty_files:
    for file in empty_files:
        print(f"❌ {file}")
else:
    print("✅ None")

print("\nVery small files (<200 characters):")

if small_files:
    for file in small_files:
        print(f"⚠️ {file}")
else:
    print("✅ None")

print("\n" + "=" * 80)

================================================================================
HOTEL AI - FULL KNOWLEDGE BASE AUDIT
================================================================================

📄 Booking\booking_confirmation.txt
   Characters: 974
   Words:      137

📄 Booking\booking_modification.txt
   Characters: 1398
   Words:      203

📄 Booking\booking_policy.txt
   Characters: 1625
   Words:      240

📄 Booking\booking_process.txt
   Characters: 953
   Words:      136

📄 Cancellation\cancellation_policy.txt
   Characters: 1758
   Words:      231

📄 Cancellation\cancellation_process.txt
   Characters: 1089
   Words:      145

📄 Hotel_Information\contact_information.txt
   Characters: 748
   Words:      104

📄 Hotel_Information\hotel_facilities.txt
   Characters: 1153
   Words:      165

📄 Hotel_Information\hotel_information.txt
   Characters: 542
   Words:      80

📄 Payment\payment_methods.txt
   Characters: 863
   Words:      122

📄 Payment\payment_policy.txt
   Characters: 986
   Words:      144

📄 Payment\refund_policy.txt
   Characters: 935
   Words:      138

📄 Policies\check_in_check_out.txt
   Characters: 523
   Words:      73

📄 Policies\children_policy.txt
   Characters: 323
   Words:      51

📄 Policies\emergency_policy.txt
   Characters: 300
   Words:      42

📄 Policies\guest_conduct.txt
   Characters: 308
   Words:      49

📄 Policies\identification_policy.txt
   Characters: 392
   Words:      51

📄 Policies\lost_and_found.txt
   Characters: 356
   Words:      58

📄 Policies\noise_policy.txt
   Characters: 251
   Words:      35

📄 Policies\pet_policy.txt
   Characters: 210
   Words:      34

📄 Policies\privacy_policy.txt
   Characters: 412
   Words:      58

📄 Policies\smoking_policy.txt
   Characters: 250
   Words:      37

📄 Rooms\room_amenities.txt
   Characters: 907
   Words:      129

📄 Rooms\room_policies.txt
   Characters: 1071
   Words:      157

📄 Rooms\room_types.txt
   Characters: 1138
   Words:      153

📄 Services\airport_transfer.txt
   Characters: 426
   Words:      57

📄 Services\breakfast.txt
   Characters: 489
   Words:      74

📄 Services\gym.txt
   Characters: 318
   Words:      47

📄 Services\laundry.txt
   Characters: 436
   Words:      62

📄 Services\room_service.txt
   Characters: 423
   Words:      62

📄 Services\spa.txt
   Characters: 418
   Words:      59

================================================================================
SUMMARY
================================================================================
Total TXT files:       31
Total characters:      21975
Total words:           3133

Empty files:
✅ None

Very small files (<200 characters):
✅ None

================================================================================

In [51]:
import os

services_path = os.path.join(
    "02_Hotel_Knowledge",
    "Services"
)

file_path = os.path.join(
    services_path,
    "restaurant.txt"
)

restaurant_content = """NILE PEARL HOTEL
RESTAURANT INFORMATION

Restaurant:
Main Restaurant

Known Service:
Daily Breakfast

Breakfast Hours:
7:00 AM - 10:30 AM

Breakfast Price:
450 EGP per person

Breakfast Includes:
- Hot food
- Cold food
- Beverages
- Pastries
- Fresh fruit

Important Information:

The current hotel knowledge base only provides confirmed information about breakfast at the main restaurant.

The current hotel knowledge base does not specify:

- Restaurant opening hours outside breakfast
- Lunch service
- Dinner service
- Restaurant menu
- Individual food prices
- Restaurant reservation requirements
- Restaurant dress code
"""

with open(file_path, "w", encoding="utf-8") as file:
    file.write(restaurant_content)

print("Created successfully:")
print(file_path)
print("Size:", os.path.getsize(file_path), "bytes")

Created successfully:
02_Hotel_Knowledge\Services\restaurant.txt
Size: 661 bytes

In [53]:
import os

knowledge_path = "02_Hotel_Knowledge"

total_files = 0
total_characters = 0
total_words = 0

print("=" * 70)
print("FINAL KNOWLEDGE BASE AUDIT")
print("=" * 70)

for root, dirs, files in os.walk(knowledge_path):

    for file_name in sorted(files):

        if not file_name.endswith(".txt"):
            continue

        file_path = os.path.join(root, file_name)

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()

        total_files += 1
        total_characters += len(content)
        total_words += len(content.split())

print(f"Total TXT files:  {total_files}")
print(f"Total characters: {total_characters}")
print(f"Total words:      {total_words}")

print("=" * 70)

if total_files == 32:
    print("✅ KNOWLEDGE BASE FILE COUNT PASSED")
else:
    print("⚠️ Check file count")

print("✅ No empty files expected")

======================================================================
FINAL KNOWLEDGE BASE AUDIT
======================================================================
Total TXT files:  32
Total characters: 22601
Total words:      3225
======================================================================
✅ KNOWLEDGE BASE FILE COUNT PASSED
✅ No empty files expected

In [52]:
print(os.listdir("02_Hotel_Knowledge/Services"))

['airport_transfer.txt', 'breakfast.txt', 'gym.txt', 'laundry.txt', 'restaurant.txt', 'room_service.txt', 'spa.txt']

In [54]:
import os

knowledge_path = "02_Hotel_Knowledge"

print("=" * 80)
print("HOTEL AI - CONTENT AUDIT")
print("=" * 80)

file_count = 0

for root, dirs, files in os.walk(knowledge_path):

    for file_name in sorted(files):

        if not file_name.lower().endswith(".txt"):
            continue

        file_path = os.path.join(root, file_name)

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read().strip()

        relative_path = os.path.relpath(
            file_path,
            knowledge_path
        )

        file_count += 1

        print("\n" + "=" * 80)
        print(f"FILE {file_count}: {relative_path}")
        print("=" * 80)

        print(content[:500])

        if len(content) > 500:
            print("\n... [content continues] ...")

print("\n" + "=" * 80)
print(f"TOTAL FILES AUDITED: {file_count}")
print("=" * 80)

================================================================================
HOTEL AI - CONTENT AUDIT
================================================================================

================================================================================
FILE 1: Booking\booking_confirmation.txt
================================================================================
NILE PEARL HOTEL
BOOKING CONFIRMATION

1. Reservation Confirmation

A reservation should be confirmed after the required booking information has been provided and the reservation process has been completed.

Guests should keep their booking confirmation details for future reference.


2. Confirmation Information

A booking confirmation should be associated with the reservation details provided during the booking process.

Relevant reservation information may include:

- Guest name
- Number of gu

... [content continues] ...

================================================================================
FILE 2: Booking\booking_modification.txt
================================================================================
NILE PEARL HOTEL
BOOKING MODIFICATION POLICY

1. Reservation Changes

Guests may contact customer service regarding changes to their reservations.

Reservation changes are subject to availability and hotel approval.


2. Changes to Check-in or Check-out Dates

Guests may request changes to their check-in or check-out dates.

The requested dates must be checked for room availability.

Any applicable cancellation or payment conditions depend on the hotel's relevant policies.


3. Changes to Room T

... [content continues] ...

================================================================================
FILE 3: Booking\booking_policy.txt
================================================================================
NILE PEARL HOTEL
BOOKING POLICY

1. Room Reservations

Guests can make reservations for available rooms at Nile Pearl Hotel.

Room availability depends on the selected dates and room type.

Guests should provide accurate booking information when making a reservation.


2. Required Booking Information

A reservation may require the following information:

- Guest full name
- Number of guests
- Check-in date
- Check-out date
- Selected room type
- Contact information
- Payment information when req

... [content continues] ...

================================================================================
FILE 4: Booking\booking_process.txt
================================================================================
NILE PEARL HOTEL
BOOKING PROCESS

1. Select Dates

The guest provides the desired check-in and check-out dates.


2. Select Room

The guest selects a suitable room type based on availability and guest capacity.


3. Provide Guest Information

The guest provides the required personal and contact information.


4. Review Reservation

The reservation details should be reviewed before confirmation.

The guest should verify:

- Guest name
- Number of guests
- Check-in date
- Check-out date
- Room typ

... [content continues] ...

================================================================================
FILE 5: Cancellation\cancellation_policy.txt
================================================================================
NILE PEARL HOTEL
CANCELLATION POLICY

1. Cancellation Requests

Guests may request cancellation of their hotel reservations.

Cancellation requests are subject to the applicable reservation and cancellation conditions.


2. Cancellation Eligibility

Cancellation eligibility depends on the conditions associated with the reservation.

Guests should review the cancellation conditions before requesting cancellation.


3. Cancellation Fees

Any applicable cancellation fees depend on the cancellation

... [content continues] ...

================================================================================
FILE 6: Cancellation\cancellation_process.txt
================================================================================
NILE PEARL HOTEL
CANCELLATION PROCESS

1. Identify the Reservation

The guest should provide the relevant reservation details when requesting cancellation.


2. Review Cancellation Conditions

The cancellation conditions associated with the reservation should be checked before processing the cancellation.


3. Submit Cancellation Request

The guest can contact customer service to request cancellation assistance.


4. Check Cancellation Eligibility

The reservation should be checked to determine

... [content continues] ...

================================================================================
FILE 7: Hotel_Information\contact_information.txt
================================================================================
NILE PEARL HOTEL
CONTACT INFORMATION

Hotel Name:
Nile Pearl Hotel

Location:
Cairo, Egypt

Reception:
Available 24/7.

Front Desk:
Guests can contact the front desk at any time for assistance.

Customer Service:
Customer service is available to assist guests with hotel services, reservations, requests, and general inquiries.

Emergency:
In case of an emergency, guests should contact the hotel reception immediately.

Lost and Found:
Guests should contact the front desk regarding lost or found it

... [content continues] ...

================================================================================
FILE 8: Hotel_Information\hotel_facilities.txt
================================================================================
NILE PEARL HOTEL
HOTEL FACILITIES

1. Swimming Pool

Availability:
7:00 AM - 9:00 PM

Access:
Available for hotel guests.

Description:
The hotel provides a swimming pool for guests.


2. Gym

Availability:
24/7

Access:
Available for hotel guests.

Description:
The hotel provides a gym that guests can use at any time.


3. Wi-Fi

Availability:
Available 24/7.

Access:
Available in all guest rooms and public areas.

Price:
Free of charge.


4. Parking

Availability:
Available for hotel guests.



... [content continues] ...

================================================================================
FILE 9: Hotel_Information\hotel_information.txt
================================================================================
NILE PEARL HOTEL
HOTEL INFORMATION

Hotel Name:
Nile Pearl Hotel

Location:
Cairo, Egypt

Hotel Category:
5-Star Hotel

Check-in:
3:00 PM

Check-out:
12:00 PM

Reception:
24/7

Breakfast:
7:00 AM - 10:30 AM

Free Wi-Fi:
Available in all rooms and public areas.

Parking:
Available for hotel guests.

Swimming Pool:
Available from 7:00 AM to 9:00 PM.

Gym:
Open 24/7 for hotel guests.

Airport Transfer:
Available upon request.

Room Service:
Available 24/7.

Pets:
Pets are not allowed.

Languages Su

... [content continues] ...

================================================================================
FILE 10: Payment\payment_methods.txt
================================================================================
NILE PEARL HOTEL
PAYMENT METHODS

1. Payment Information

Guests may be required to provide payment information when making or confirming a reservation.

2. Accepted Payment Methods

The current hotel knowledge base does not specify the exact payment methods accepted by the hotel.

Guests should contact customer service for information about currently accepted payment methods.

3. Payment Assistance

Guests can contact customer service regarding payment questions or payment-related issues.

4. P

... [content continues] ...

================================================================================
FILE 11: Payment\payment_policy.txt
================================================================================
NILE PEARL HOTEL
PAYMENT POLICY

1. Payment Requirements

Payment requirements depend on the selected reservation and applicable hotel policies.

2. Reservation Payment

Guests may be required to provide payment information when making or confirming a reservation.

3. Payment Verification

Payment information may need to be verified during the reservation process.

4. Additional Charges

Additional charges may apply for certain hotel services or damages to hotel property.

Examples of services w

... [content continues] ...

================================================================================
FILE 12: Payment\refund_policy.txt
================================================================================
NILE PEARL HOTEL
REFUND POLICY

1. Refund Eligibility

Refund eligibility depends on the conditions associated with the reservation.

2. Cancellation Refunds

If a cancelled reservation is eligible for a refund, the refund is processed according to the applicable payment and refund conditions.

3. Refund Amount

The refund amount depends on the reservation conditions and any applicable cancellation terms.

4. Refund Processing

The current hotel knowledge base does not specify a fixed refund pro

... [content continues] ...

================================================================================
FILE 13: Policies\check_in_check_out.txt
================================================================================
NILE PEARL HOTEL
CHECK-IN AND CHECK-OUT POLICY

1. Check-in

Standard check-in time:
3:00 PM

Guests must provide valid identification during check-in.

Early check-in:
Early check-in is subject to room availability and hotel approval.


2. Check-out

Standard check-out time:
12:00 PM

Late check-out:
Late check-out is subject to availability and may incur an additional fee.


3. Reception

Hotel reception operates 24/7.

Guests can contact reception for assistance with check-in, check-out, and

... [content continues] ...

================================================================================
FILE 14: Policies\children_policy.txt
================================================================================
NILE PEARL HOTEL
CHILDREN POLICY

Children are welcome at the hotel.

Extra beds or additional accommodation for children are subject to:

- Room capacity
- Availability

The selected room must have sufficient capacity for the number of guests.

The current hotel knowledge base does not specify a separate child age limit.

================================================================================
FILE 15: Policies\emergency_policy.txt
================================================================================
NILE PEARL HOTEL
EMERGENCY POLICY

In case of an emergency, guests should contact the hotel reception immediately.

Hotel reception operates 24/7.

Guests should follow the instructions provided by hotel staff during an emergency.

For immediate assistance, guests should contact the hotel reception.

================================================================================
FILE 16: Policies\guest_conduct.txt
================================================================================
NILE PEARL HOTEL
GUEST CONDUCT POLICY

Guests are expected to respect:

- Hotel property
- Hotel staff
- Other guests

Guests are responsible for any damage caused to hotel property.

Damage to hotel property may result in additional charges.

Guests should follow hotel rules and policies during their stay.

================================================================================
FILE 17: Policies\identification_policy.txt
================================================================================
NILE PEARL HOTEL
IDENTIFICATION POLICY

Guests are required to provide valid identification documents during check-in.

Valid identification is required to complete the check-in process.

Guests should contact hotel reception if they have questions regarding identification requirements.

The current hotel knowledge base does not specify the exact types of identification documents accepted.

================================================================================
FILE 18: Policies\lost_and_found.txt
================================================================================
NILE PEARL HOTEL
LOST AND FOUND POLICY

Items found on hotel property are handled by the hotel's Lost and Found department.

Guests who lose an item should contact the front desk.

Guests should provide relevant information about the lost item when contacting the hotel.

The current hotel knowledge base does not specify the storage period for lost items.

================================================================================
FILE 19: Policies\noise_policy.txt
================================================================================
NILE PEARL HOTEL
NOISE POLICY

Guests should maintain reasonable noise levels during their stay.

Guests are especially expected to maintain reasonable noise levels during nighttime hours.

Guests should respect other guests and avoid excessive noise.

================================================================================
FILE 20: Policies\pet_policy.txt
================================================================================
NILE PEARL HOTEL
PET POLICY

Pets are not allowed inside the hotel.

This policy applies to guest rooms and hotel facilities.

Guests should contact customer service if they have questions about the pet policy.

================================================================================
FILE 21: Policies\privacy_policy.txt
================================================================================
NILE PEARL HOTEL
PRIVACY POLICY

Guest information is handled according to the hotel's privacy and security procedures.

Guest information should be handled appropriately and securely.

Guests can contact customer service if they have questions regarding the handling of their information.

The current hotel knowledge base does not provide the hotel's complete privacy policy or specific data retention periods.

================================================================================
FILE 22: Policies\smoking_policy.txt
================================================================================
NILE PEARL HOTEL
SMOKING POLICY

Smoking is not permitted inside guest rooms.

Smoking is also not permitted inside indoor public areas.

Designated smoking areas are available for guests.

Guests should use the designated smoking areas when smoking.

================================================================================
FILE 23: Rooms\room_amenities.txt
================================================================================
NILE PEARL HOTEL
ROOM AMENITIES

1. Standard Room

Available Amenities:
- Comfortable bed
- Private bathroom
- Wi-Fi
- Air conditioning
- Television
- Basic room amenities


2. Deluxe Room

Available Amenities:
- Private bathroom
- Wi-Fi
- Air conditioning
- Television
- Enhanced room amenities
- Upgraded furnishings


3. Superior Room

Available Amenities:
- Additional space
- Upgraded amenities


4. Family Room

Available Amenities:
- Additional sleeping capacity
- Suitable facilities for fami

... [content continues] ...

================================================================================
FILE 24: Rooms\room_policies.txt
================================================================================
NILE PEARL HOTEL
ROOM POLICIES

1. Room Capacity

Standard Room:
Maximum capacity: 2 guests.

Deluxe Room:
Maximum capacity: 2 guests.

Superior Room:
Maximum capacity: 3 guests.

Family Room:
Maximum capacity: 4 guests.

Executive Room:
Capacity information is not specified in the current hotel knowledge base.


2. Extra Accommodation

Extra beds or additional accommodation for children are subject to room capacity and availability.


3. Children

Children are welcome at the hotel.

Additional

... [content continues] ...

================================================================================
FILE 25: Rooms\room_types.txt
================================================================================
NILE PEARL HOTEL
ROOM TYPES

1. Standard Room

Room Type:
Standard Room

Capacity:
2 Guests

Description:
A comfortable room suitable for individuals or couples.

Amenities:
Comfortable bed, private bathroom, Wi-Fi, air conditioning, television, and basic room amenities.


2. Deluxe Room

Room Type:
Deluxe Room

Capacity:
2 Guests

Description:
A spacious room with upgraded furnishings and additional comfort.

Amenities:
Private bathroom, Wi-Fi, air conditioning, television, and enhanced room am

... [content continues] ...

================================================================================
FILE 26: Services\airport_transfer.txt
================================================================================
NILE PEARL HOTEL
AIRPORT TRANSFER

Service:
Airport Transfer

Availability:
Upon Request

Price:
800 EGP per trip

Description:
Private airport pickup and drop-off services are available.

Booking:
Guests should request the airport transfer service in advance.

Important Information:
The current hotel knowledge base does not specify the airport transfer schedule, vehicle type, passenger capacity, or exact booking deadline.

================================================================================
FILE 27: Services\breakfast.txt
================================================================================
NILE PEARL HOTEL
BREAKFAST SERVICE

Service:
Daily Breakfast

Availability:
7:00 AM - 10:30 AM

Location:
Main Restaurant

Price:
450 EGP per person

Description:
The hotel provides daily breakfast at the main restaurant.

Breakfast includes:
- Hot food
- Cold food
- Beverages
- Pastries
- Fresh fruit

Important Information:
Guests can have breakfast during the specified breakfast hours.

The current hotel knowledge base does not specify whether breakfast is included in the room rate.

================================================================================
FILE 28: Services\gym.txt
================================================================================
NILE PEARL HOTEL
GYM

Service:
Hotel Gym

Availability:
24/7

Access:
Available for hotel guests.

Description:
The hotel provides a gym that guests can use at any time.

Important Information:
The current hotel knowledge base does not specify the gym equipment, age restrictions, or whether reservations are required.

================================================================================
FILE 29: Services\laundry.txt
================================================================================
NILE PEARL HOTEL
LAUNDRY AND DRY CLEANING

Service:
Laundry and Dry Cleaning

Availability:
Daily

Price:
200 EGP per kilogram

Request Method:
Guests can request laundry service through the front desk or customer service.

Description:
The hotel provides laundry and dry cleaning services for guests.

Important Information:
The current hotel knowledge base does not specify the exact turnaround time or individual dry-cleaning prices.

================================================================================
FILE 30: Services\restaurant.txt
================================================================================
NILE PEARL HOTEL
RESTAURANT INFORMATION

Restaurant:
Main Restaurant

Known Service:
Daily Breakfast

Breakfast Hours:
7:00 AM - 10:30 AM

Breakfast Price:
450 EGP per person

Breakfast Includes:
- Hot food
- Cold food
- Beverages
- Pastries
- Fresh fruit

Important Information:

The current hotel knowledge base only provides confirmed information about breakfast at the main restaurant.

The current hotel knowledge base does not specify:

- Restaurant opening hours outside breakfast
- Lunch serv

... [content continues] ...

================================================================================
FILE 31: Services\room_service.txt
================================================================================
NILE PEARL HOTEL
ROOM SERVICE

Service:
24/7 Room Service

Availability:
24 hours a day

Price:

In [55]:
import os
import pandas as pd

knowledge_path = "02_Hotel_Knowledge"

print("Knowledge path:", knowledge_path)
print("Exists:", os.path.exists(knowledge_path))

Knowledge path: 02_Hotel_Knowledge
Exists: True

In [56]:
import os
import pandas as pd

knowledge_path = "02_Hotel_Knowledge"

documents = []

for root, dirs, files in os.walk(knowledge_path):

    for file_name in sorted(files):

        if not file_name.lower().endswith(".txt"):
            continue

        file_path = os.path.join(root, file_name)

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read().strip()

        relative_path = os.path.relpath(
            file_path,
            knowledge_path
        )

        parts = relative_path.split(os.sep)

        domain = parts[0]
        source = parts[-1]

        documents.append({
            "source": source,
            "domain": domain,
            "content": content,
            "language": "English"
        })

knowledge_df = pd.DataFrame(documents)

print("Documents loaded:", len(knowledge_df))

knowledge_df.head()

Documents loaded: 32

,source,domain,content,language
0,booking_confirmation.txt,Booking,NILE PEARL HOTEL\nBOOKING CONFIRMATION\n\n1. R...,English
1,booking_modification.txt,Booking,NILE PEARL HOTEL\nBOOKING MODIFICATION POLICY\...,English
2,booking_policy.txt,Booking,NILE PEARL HOTEL\nBOOKING POLICY\n\n1. Room Re...,English
3,booking_process.txt,Booking,NILE PEARL HOTEL\nBOOKING PROCESS\n\n1. Select...,English
4,cancellation_policy.txt,Cancellation,NILE PEARL HOTEL\nCANCELLATION POLICY\n\n1. Ca...,English

In [57]:
# Add unique document IDs

knowledge_df.insert(
    0,
    "document_id",
    [f"DOC{i:03d}" for i in range(1, len(knowledge_df) + 1)]
)

# Map each source file to a specific category

category_map = {
    # Booking
    "booking_confirmation.txt": "Booking",
    "booking_modification.txt": "Booking",
    "booking_policy.txt": "Booking",
    "booking_process.txt": "Booking",

    # Cancellation
    "cancellation_policy.txt": "Cancellation",
    "cancellation_process.txt": "Cancellation",

    # Hotel Information
    "contact_information.txt": "Hotel Information",
    "hotel_facilities.txt": "Hotel Facilities",
    "hotel_information.txt": "Hotel Information",

    # Payment
    "payment_methods.txt": "Payment",
    "payment_policy.txt": "Payment",
    "refund_policy.txt": "Refund",

    # Policies
    "check_in_check_out.txt": "Check-in / Check-out",
    "children_policy.txt": "Children",
    "emergency_policy.txt": "Emergency",
    "guest_conduct.txt": "Guest Conduct",
    "identification_policy.txt": "Identification",
    "lost_and_found.txt": "Lost and Found",
    "noise_policy.txt": "Noise",
    "pet_policy.txt": "Pets",
    "privacy_policy.txt": "Privacy",
    "smoking_policy.txt": "Smoking",

    # Rooms
    "room_amenities.txt": "Room Amenities",
    "room_policies.txt": "Room Policies",
    "room_types.txt": "Room Types",

    # Services
    "airport_transfer.txt": "Airport Transfer",
    "breakfast.txt": "Breakfast",
    "gym.txt": "Gym",
    "laundry.txt": "Laundry",
    "restaurant.txt": "Restaurant",
    "room_service.txt": "Room Service",
    "spa.txt": "Spa"
}

knowledge_df["category"] = knowledge_df["source"].map(category_map)

print("Documents:", len(knowledge_df))
print("\nMissing categories:")

print(
    knowledge_df[
        knowledge_df["category"].isna()
    ][["source", "domain"]]
)

knowledge_df.head()

Documents: 32

Missing categories:
Empty DataFrame
Columns: [source, domain]
Index: []

,document_id,source,domain,content,language,category
0,DOC001,booking_confirmation.txt,Booking,NILE PEARL HOTEL\nBOOKING CONFIRMATION\n\n1. R...,English,Booking
1,DOC002,booking_modification.txt,Booking,NILE PEARL HOTEL\nBOOKING MODIFICATION POLICY\...,English,Booking
2,DOC003,booking_policy.txt,Booking,NILE PEARL HOTEL\nBOOKING POLICY\n\n1. Room Re...,English,Booking
3,DOC004,booking_process.txt,Booking,NILE PEARL HOTEL\nBOOKING PROCESS\n\n1. Select...,English,Booking
4,DOC005,cancellation_policy.txt,Cancellation,NILE PEARL HOTEL\nCANCELLATION POLICY\n\n1. Ca...,English,Cancellation

In [58]:
faq_columns = [
    "faq_id",
    "intent_id",
    "category",
    "language",
    "question",
    "answer",
    "source",
    "question_type",
    "difficulty"
]

faq_df = pd.DataFrame(columns=faq_columns)

print("FAQ Schema:")
print(faq_df.columns.tolist())

print("\nNumber of columns:", len(faq_df.columns))

FAQ Schema:
['faq_id', 'intent_id', 'category', 'language', 'question', 'answer', 'source', 'question_type', 'difficulty']

Number of columns: 9

In [59]:
intent_catalog = [
    # =========================
    # HOTEL INFORMATION
    # =========================

    {
        "intent_id": "INT001",
        "intent_name": "hotel_location",
        "category": "Hotel Information",
        "source": "hotel_information.txt"
    },

    {
        "intent_id": "INT002",
        "intent_name": "hotel_category",
        "category": "Hotel Information",
        "source": "hotel_information.txt"
    },

    {
        "intent_id": "INT003",
        "intent_name": "reception_availability",
        "category": "Hotel Information",
        "source": "hotel_information.txt"
    },

    # =========================
    # CHECK-IN / CHECK-OUT
    # =========================

    {
        "intent_id": "INT004",
        "intent_name": "check_in_time",
        "category": "Check-in / Check-out",
        "source": "check_in_check_out.txt"
    },

    {
        "intent_id": "INT005",
        "intent_name": "check_out_time",
        "category": "Check-in / Check-out",
        "source": "check_in_check_out.txt"
    },

    {
        "intent_id": "INT006",
        "intent_name": "early_check_in",
        "category": "Check-in / Check-out",
        "source": "check_in_check_out.txt"
    },

    {
        "intent_id": "INT007",
        "intent_name": "late_check_out",
        "category": "Check-in / Check-out",
        "source": "check_in_check_out.txt"
    },

    {
        "intent_id": "INT008",
        "intent_name": "identification_required",
        "category": "Identification",
        "source": "identification_policy.txt"
    },

    # =========================
    # ROOMS
    # =========================

    {
        "intent_id": "INT009",
        "intent_name": "available_room_types",
        "category": "Room Types",
        "source": "room_types.txt"
    },

    {
        "intent_id": "INT010",
        "intent_name": "room_capacity",
        "category": "Room Policies",
        "source": "room_policies.txt"
    },

    {
        "intent_id": "INT011",
        "intent_name": "room_amenities",
        "category": "Room Amenities",
        "source": "room_amenities.txt"
    },

    {
        "intent_id": "INT012",
        "intent_name": "children_room_accommodation",
        "category": "Room Policies",
        "source": "room_policies.txt"
    },

    # =========================
    # BOOKING
    # =========================

    {
        "intent_id": "INT013",
        "intent_name": "booking_process",
        "category": "Booking",
        "source": "booking_process.txt"
    },

    {
        "intent_id": "INT014",
        "intent_name": "booking_required_information",
        "category": "Booking",
        "source": "booking_policy.txt"
    },

    {
        "intent_id": "INT015",
        "intent_name": "booking_modification",
        "category": "Booking",
        "source": "booking_modification.txt"
    },

    {
        "intent_id": "INT016",
        "intent_name": "booking_confirmation",
        "category": "Booking",
        "source": "booking_confirmation.txt"
    },

    # =========================
    # CANCELLATION
    # =========================

    {
        "intent_id": "INT017",
        "intent_name": "cancellation_process",
        "category": "Cancellation",
        "source": "cancellation_process.txt"
    },

    {
        "intent_id": "INT018",
        "intent_name": "cancellation_policy",
        "category": "Cancellation",
        "source": "cancellation_policy.txt"
    },

    {
        "intent_id": "INT019",
        "intent_name": "cancellation_fees",
        "category": "Cancellation",
        "source": "cancellation_policy.txt"
    },

    # =========================
    # PAYMENT / REFUND
    # =========================

    {
        "intent_id": "INT020",
        "intent_name": "accepted_payment_methods",
        "category": "Payment",
        "source": "payment_methods.txt"
    },

    {
        "intent_id": "INT021",
        "intent_name": "payment_requirements",
        "category": "Payment",
        "source": "payment_policy.txt"
    },

    {
        "intent_id": "INT022",
        "intent_name": "additional_charges",
        "category": "Payment",
        "source": "payment_policy.txt"
    },

    {
        "intent_id": "INT023",
        "intent_name": "refund_eligibility",
        "category": "Refund",
        "source": "refund_policy.txt"
    },

    {
        "intent_id": "INT024",
        "intent_name": "refund_processing",
        "category": "Refund",
        "source": "refund_policy.txt"
    },

    # =========================
    # SERVICES
    # =========================

    {
        "intent_id": "INT025",
        "intent_name": "breakfast_hours",
        "category": "Breakfast",
        "source": "breakfast.txt"
    },

    {
        "intent_id": "INT026",
        "intent_name": "breakfast_price",
        "category": "Breakfast",
        "source": "breakfast.txt"
    },

    {
        "intent_id": "INT027",
        "intent_name": "room_service",
        "category": "Room Service",
        "source": "room_service.txt"
    },

    {
        "intent_id": "INT028",
        "intent_name": "airport_transfer",
        "category": "Airport Transfer",
        "source": "airport_transfer.txt"
    },

    {
        "intent_id": "INT029",
        "intent_name": "laundry_service",
        "category": "Laundry",
        "source": "laundry.txt"
    },

    {
        "intent_id": "INT030",
        "intent_name": "spa_service",
        "category": "Spa",
        "source": "spa.txt"
    },

    {
        "intent_id": "INT031",
        "intent_name": "gym_availability",
        "category": "Gym",
        "source": "gym.txt"
    },

    {
        "intent_id": "INT032",
        "intent_name": "restaurant_information",
        "category": "Restaurant",
        "source": "restaurant.txt"
    },

    # =========================
    # FACILITIES
    # =========================

    {
        "intent_id": "INT033",
        "intent_name": "wifi_availability",
        "category": "Hotel Facilities",
        "source": "hotel_facilities.txt"
    },

    {
        "intent_id": "INT034",
        "intent_name": "parking_availability",
        "category": "Hotel Facilities",
        "source": "hotel_facilities.txt"
    },

    {
        "intent_id": "INT035",
        "intent_name": "swimming_pool",
        "category": "Hotel Facilities",
        "source": "hotel_facilities.txt"
    },

    # =========================
    # POLICIES
    # =========================

    {
        "intent_id": "INT036",
        "intent_name": "pet_policy",
        "category": "Pets",
        "source": "pet_policy.txt"
    },

    {
        "intent_id": "INT037",
        "intent_name": "smoking_policy",
        "category": "Smoking",
        "source": "smoking_policy.txt"
    },

    {
        "intent_id": "INT038",
        "intent_name": "children_policy",
        "category": "Children",
        "source": "children_policy.txt"
    },

    {
        "intent_id": "INT039",
        "intent_name": "lost_and_found",
        "category": "Lost and Found",
        "source": "lost_and_found.txt"
    },

    {
        "intent_id": "INT040",
        "intent_name": "noise_policy",
        "category": "Noise",
        "source": "noise_policy.txt"
    },

    {
        "intent_id": "INT041",
        "intent_name": "guest_conduct",
        "category": "Guest Conduct",
        "source": "guest_conduct.txt"
    },

    {
        "intent_id": "INT042",
        "intent_name": "privacy_policy",
        "category": "Privacy",
        "source": "privacy_policy.txt"
    },

    {
        "intent_id": "INT043",
        "intent_name": "emergency_assistance",
        "category": "Emergency",
        "source": "emergency_policy.txt"
    }
]

In [60]:
intent_df = pd.DataFrame(intent_catalog)

print("Total intents:", len(intent_df))

intent_df.head(10)

Total intents: 43

,intent_id,intent_name,category,source
0,INT001,hotel_location,Hotel Information,hotel_information.txt
1,INT002,hotel_category,Hotel Information,hotel_information.txt
2,INT003,reception_availability,Hotel Information,hotel_information.txt
3,INT004,check_in_time,Check-in / Check-out,check_in_check_out.txt
4,INT005,check_out_time,Check-in / Check-out,check_in_check_out.txt
5,INT006,early_check_in,Check-in / Check-out,check_in_check_out.txt
6,INT007,late_check_out,Check-in / Check-out,check_in_check_out.txt
7,INT008,identification_required,Identification,identification_policy.txt
8,INT009,available_room_types,Room Types,room_types.txt
9,INT010,room_capacity,Room Policies,room_policies.txt

In [61]:
# Validate intent sources

available_sources = set(knowledge_df["source"])

intent_df["source_exists"] = intent_df["source"].isin(available_sources)

print("Total intents:", len(intent_df))
print("Valid sources:", intent_df["source_exists"].sum())
print("Missing sources:", (~intent_df["source_exists"]).sum())

print("\nMissing source files:")

print(
    intent_df[
        ~intent_df["source_exists"]
    ][
        ["intent_id", "intent_name", "source"]
    ]
)

Total intents: 43
Valid sources: 43
Missing sources: 0

Missing source files:
Empty DataFrame
Columns: [intent_id, intent_name, source]
Index: []

In [62]:
intent_distribution = (
    intent_df["category"]
    .value_counts()
    .sort_index()
)

print("=" * 60)
print("INTENT DISTRIBUTION")
print("=" * 60)

print(intent_distribution)

print("\nTotal categories:", intent_df["category"].nunique())
print("Total intents:", len(intent_df))

============================================================
INTENT DISTRIBUTION
============================================================
category
Airport Transfer        1
Booking                 4
Breakfast               2
Cancellation            3
Check-in / Check-out    4
Children                1
Emergency               1
Guest Conduct           1
Gym                     1
Hotel Facilities        3
Hotel Information       3
Identification          1
Laundry                 1
Lost and Found          1
Noise                   1
Payment                 3
Pets                    1
Privacy                 1
Refund                  2
Restaurant              1
Room Amenities          1
Room Policies           2
Room Service            1
Room Types              1
Smoking                 1
Spa                     1
Name: count, dtype: int64

Total categories: 26
Total intents: 43

In [63]:
print("=" * 70)
print("FINAL INTENT CATALOG VALIDATION")
print("=" * 70)

checks = {
    "Total intents": len(intent_df),
    "Unique intent IDs": intent_df["intent_id"].nunique(),
    "Unique intent names": intent_df["intent_name"].nunique(),
    "Unique categories": intent_df["category"].nunique(),
    "Missing intent IDs": intent_df["intent_id"].isna().sum(),
    "Missing intent names": intent_df["intent_name"].isna().sum(),
    "Missing categories": intent_df["category"].isna().sum(),
    "Missing sources": intent_df["source"].isna().sum(),
}

for name, value in checks.items():
    print(f"{name}: {value}")

print("=" * 70)

passed = (
    checks["Total intents"] == 43
    and checks["Unique intent IDs"] == 43
    and checks["Unique intent names"] == 43
    and checks["Missing intent IDs"] == 0
    and checks["Missing intent names"] == 0
    and checks["Missing categories"] == 0
    and checks["Missing sources"] == 0
)

if passed:
    print("✅ INTENT CATALOG PASSED")
    print("✅ Ready for FAQ generation design")
else:
    print("⚠️ INTENT CATALOG NEEDS REVIEW")

======================================================================
FINAL INTENT CATALOG VALIDATION
======================================================================
Total intents: 43
Unique intent IDs: 43
Unique intent names: 43
Unique categories: 26
Missing intent IDs: 0
Missing intent names: 0
Missing categories: 0
Missing sources: 0
======================================================================
✅ INTENT CATALOG PASSED
✅ Ready for FAQ generation design

In [64]:
question_matrix = {
    "Direct": 3,
    "Paraphrased": 3,
    "Scenario": 2
}

languages = [
    "English",
    "Arabic",
    "French",
    "Russian"
]

total_questions_per_intent = sum(question_matrix.values())

total_english_questions = (
    len(intent_df) * total_questions_per_intent
)

total_all_languages = (
    total_english_questions * len(languages)
)

print("=" * 70)
print("QUESTION GENERATION MATRIX")
print("=" * 70)

print("Question Types:")

for question_type, count in question_matrix.items():
    print(f"- {question_type}: {count}")

print("\nLanguages:")

for language in languages:
    print(f"- {language}")

print("\nTotal intents:", len(intent_df))
print("Questions per intent:", total_questions_per_intent)
print("English questions:", total_english_questions)
print("Total FAQ rows:", total_all_languages)

======================================================================
QUESTION GENERATION MATRIX
======================================================================
Question Types:
- Direct: 3
- Paraphrased: 3
- Scenario: 2

Languages:
- English
- Arabic
- French
- Russian

Total intents: 43
Questions per intent: 8
English questions: 344
Total FAQ rows: 1376

In [65]:
generation_columns = [
    "faq_id",
    "intent_id",
    "intent_name",
    "category",
    "language",
    "question_type",
    "difficulty",
    "question",
    "answer",
    "source"
]

generation_df = pd.DataFrame(columns=generation_columns)

print("=" * 70)
print("FAQ GENERATION DATASET")
print("=" * 70)

print("Columns:", len(generation_df.columns))
print("Target rows:", total_all_languages)

print("\nSchema:")
for column in generation_df.columns:
    print(f"- {column}")

======================================================================
FAQ GENERATION DATASET
======================================================================
Columns: 10
Target rows: 1376

Schema:
- faq_id
- intent_id
- intent_name
- category
- language
- question_type
- difficulty
- question
- answer
- source

In [66]:
generation_plan = []

faq_counter = 1

for _, intent in intent_df.iterrows():

    for language in languages:

        for question_type, count in question_matrix.items():

            for _ in range(count):

                generation_plan.append({
                    "faq_id": f"FAQ{faq_counter:04d}",
                    "intent_id": intent["intent_id"],
                    "intent_name": intent["intent_name"],
                    "category": intent["category"],
                    "language": language,
                    "question_type": question_type,
                    "difficulty": "Easy",
                    "question": "",
                    "answer": "",
                    "source": intent["source"]
                })

                faq_counter += 1

generation_plan_df = pd.DataFrame(generation_plan)

print("=" * 70)
print("FAQ GENERATION PLAN")
print("=" * 70)

print("Total planned rows:", len(generation_plan_df))
print("Expected rows:", total_all_languages)

print("\nLanguages:")
print(generation_plan_df["language"].value_counts())

print("\nQuestion Types:")
print(generation_plan_df["question_type"].value_counts())

print("\nFirst 10 rows:")
generation_plan_df.head(10)

======================================================================
FAQ GENERATION PLAN
======================================================================
Total planned rows: 1376
Expected rows: 1376

Languages:
language
English    344
Arabic     344
French     344
Russian    344
Name: count, dtype: int64

Question Types:
question_type
Direct         516
Paraphrased    516
Scenario       344
Name: count, dtype: int64

First 10 rows:

,faq_id,intent_id,intent_name,category,language,question_type,difficulty,question,answer,source
0,FAQ0001,INT001,hotel_location,Hotel Information,English,Direct,Easy,,,hotel_information.txt
1,FAQ0002,INT001,hotel_location,Hotel Information,English,Direct,Easy,,,hotel_information.txt
2,FAQ0003,INT001,hotel_location,Hotel Information,English,Direct,Easy,,,hotel_information.txt
3,FAQ0004,INT001,hotel_location,Hotel Information,English,Paraphrased,Easy,,,hotel_information.txt
4,FAQ0005,INT001,hotel_location,Hotel Information,English,Paraphrased,Easy,,,hotel_information.txt
5,FAQ0006,INT001,hotel_location,Hotel Information,English,Paraphrased,Easy,,,hotel_information.txt
6,FAQ0007,INT001,hotel_location,Hotel Information,English,Scenario,Easy,,,hotel_information.txt
7,FAQ0008,INT001,hotel_location,Hotel Information,English,Scenario,Easy,,,hotel_information.txt
8,FAQ0009,INT001,hotel_location,Hotel Information,Arabic,Direct,Easy,,,hotel_information.txt
9,FAQ0010,INT001,hotel_location,Hotel Information,Arabic,Direct,Easy,,,hotel_information.txt

In [67]:
# Build a lookup for knowledge documents

knowledge_lookup = {}

for _, row in knowledge_df.iterrows():
    knowledge_lookup[row["source"]] = row["content"]

print("Knowledge documents available:", len(knowledge_lookup))

# Check that every intent has its source available

missing_sources = []

for _, intent in intent_df.iterrows():

    if intent["source"] not in knowledge_lookup:
        missing_sources.append(intent["source"])

print("Missing intent sources:", len(missing_sources))

if missing_sources:
    print(missing_sources)
else:
    print("✅ All intent sources are available")

Knowledge documents available: 32
Missing intent sources: 0
✅ All intent sources are available

In [68]:
ground_truth_catalog = {
    "INT001": "Nile Pearl Hotel is located in Cairo, Egypt.",
    "INT002": "Nile Pearl Hotel is a 5-star hotel.",
    "INT003": "Hotel reception operates 24/7.",

    "INT004": "Standard check-in time is 3:00 PM.",
    "INT005": "Standard check-out time is 12:00 PM.",
    "INT006": "Early check-in is subject to room availability and hotel approval.",
    "INT007": "Late check-out is subject to availability and may incur an additional fee.",
    "INT008": "Guests are required to provide valid identification documents during check-in.",

    "INT009": "Nile Pearl Hotel offers Standard, Deluxe, Superior, Family, and Executive rooms.",
    "INT010": "Room capacity depends on the room type. Standard and Deluxe rooms accommodate up to 2 guests, Superior rooms up to 3 guests, and Family rooms up to 4 guests. Executive Room capacity is not specified.",
    "INT011": "Room amenities vary by room type and may include private bathrooms, Wi-Fi, air conditioning, televisions, comfortable beds, and upgraded amenities.",
    "INT012": "Children are welcome. Extra beds or additional accommodation are subject to room capacity and availability.",

    "INT013": "The booking process includes selecting dates, selecting a room, providing guest information, reviewing the reservation, and confirming the booking.",
    "INT014": "Booking information may include the guest's full name, number of guests, check-in date, check-out date, selected room type, contact information, and payment information when required.",
    "INT015": "Guests may contact customer service to request reservation changes. Changes are subject to availability and hotel approval.",
    "INT016": "A reservation should be confirmed after the required booking information has been provided and the reservation process has been completed.",

    "INT017": "Guests can contact customer service to request cancellation assistance and should provide the relevant reservation details.",
    "INT018": "Cancellation eligibility depends on the conditions associated with the reservation.",
    "INT019": "Any applicable cancellation fees depend on the cancellation conditions associated with the reservation.",

    "INT020": "The current hotel knowledge base does not specify the exact payment methods accepted by the hotel. Guests should contact customer service for current information.",
    "INT021": "Payment requirements depend on the selected reservation and applicable hotel policies.",
    "INT022": "Additional charges may apply for certain hotel services or damages to hotel property.",

    "INT023": "Refund eligibility depends on the conditions associated with the reservation.",
    "INT024": "Eligible refunds are processed according to the applicable payment and refund conditions. The current knowledge base does not specify a fixed refund processing time.",

    "INT025": "Daily breakfast is available from 7:00 AM to 10:30 AM at the main restaurant.",
    "INT026": "Breakfast costs 450 EGP per person.",
    "INT027": "Room service is available 24/7. Guests can order food and beverages directly to their rooms.",
    "INT028": "Airport transfer is available upon request and costs 800 EGP per trip.",
    "INT029": "Laundry and dry cleaning are available daily and laundry service costs 200 EGP per kilogram.",
    "INT030": "Spa treatments are available from 9:00 AM to 10:00 PM and cost 1,200 EGP per session.",
    "INT031": "The hotel gym is available 24/7 for hotel guests.",
    "INT032": "The main restaurant provides daily breakfast from 7:00 AM to 10:30 AM. The current knowledge base does not specify restaurant services outside breakfast.",

    "INT033": "Free Wi-Fi is available 24/7 in all guest rooms and public areas.",
    "INT034": "Parking is available for hotel guests.",
    "INT035": "The swimming pool is available for hotel guests from 7:00 AM to 9:00 PM.",

    "INT036": "Pets are not allowed inside the hotel, including guest rooms and hotel facilities.",
    "INT037": "Smoking is not permitted inside guest rooms or indoor public areas. Designated smoking areas are available.",
    "INT038": "Children are welcome. Extra beds or additional accommodation are subject to room capacity and availability.",
    "INT039": "Guests who lose an item should contact the front desk. Items found on hotel property are handled by the hotel's Lost and Found department.",
    "INT040": "Guests should maintain reasonable noise levels, especially during nighttime hours.",
    "INT041": "Guests are expected to respect hotel property, staff, and other guests. Damage to hotel property may result in additional charges.",
    "INT042": "Guest information is handled according to the hotel's privacy and security procedures. The current knowledge base does not provide the complete privacy policy or specific data retention periods.",
    "INT043": "In case of an emergency, guests should contact the hotel reception immediately. Reception operates 24/7."
}

print("Ground truth answers:", len(ground_truth_catalog))

Ground truth answers: 43

In [69]:
missing_ground_truth = []

for intent_id in intent_df["intent_id"]:

    if intent_id not in ground_truth_catalog:
        missing_ground_truth.append(intent_id)

print("Total intents:", len(intent_df))
print("Ground truth answers:", len(ground_truth_catalog))
print("Missing answers:", len(missing_ground_truth))

if missing_ground_truth:
    print("⚠️ Missing:", missing_ground_truth)
else:
    print("✅ ALL 43 INTENTS HAVE GROUND TRUTH ANSWERS")

Total intents: 43
Ground truth answers: 43
Missing answers: 0
✅ ALL 43 INTENTS HAVE GROUND TRUTH ANSWERS

In [70]:
print("=" * 70)
print("POTENTIAL DUPLICATE / OVERLAPPING INTENTS")
print("=" * 70)

for intent_id in ["INT012", "INT038"]:
    row = intent_df[intent_df["intent_id"] == intent_id]

    if not row.empty:
        print("\nIntent ID:", intent_id)
        print("Name:", row.iloc[0]["intent_name"])
        print("Category:", row.iloc[0]["category"])
        print("Source:", row.iloc[0]["source"])
        print("Answer:", ground_truth_catalog[intent_id])

======================================================================
POTENTIAL DUPLICATE / OVERLAPPING INTENTS
======================================================================

Intent ID: INT012
Name: children_room_accommodation
Category: Room Policies
Source: room_policies.txt
Answer: Children are welcome. Extra beds or additional accommodation are subject to room capacity and availability.

Intent ID: INT038
Name: children_policy
Category: Children
Source: children_policy.txt
Answer: Children are welcome. Extra beds or additional accommodation are subject to room capacity and availability.

In [71]:
intent_df_clean = intent_df[
    intent_df["intent_id"] != "INT012"
].copy()

intent_df_clean = intent_df_clean.reset_index(drop=True)

print("=" * 70)
print("CLEAN INTENT CATALOG")
print("=" * 70)

print("Original intents:", len(intent_df))
print("Clean intents:", len(intent_df_clean))
print("Removed intents:", len(intent_df) - len(intent_df_clean))

======================================================================
CLEAN INTENT CATALOG
======================================================================
Original intents: 43
Clean intents: 42
Removed intents: 1

In [72]:
ground_truth_catalog.pop("INT012", None)

print("Ground truth answers:", len(ground_truth_catalog))

Ground truth answers: 42

In [73]:
generation_plan = []

faq_counter = 1

for _, intent in intent_df_clean.iterrows():

    for language in languages:

        for question_type, count in question_matrix.items():

            for _ in range(count):

                generation_plan.append({
                    "faq_id": f"FAQ{faq_counter:04d}",
                    "intent_id": intent["intent_id"],
                    "intent_name": intent["intent_name"],
                    "category": intent["category"],
                    "language": language,
                    "question_type": question_type,
                    "difficulty": "Easy",
                    "question": "",
                    "answer": "",
                    "source": intent["source"]
                })

                faq_counter += 1

generation_plan_df = pd.DataFrame(generation_plan)

print("=" * 70)
print("UPDATED FAQ GENERATION PLAN")
print("=" * 70)

print("Total intents:", len(intent_df_clean))
print("Total planned rows:", len(generation_plan_df))

print("\nLanguages:")
print(generation_plan_df["language"].value_counts())

print("\nQuestion Types:")
print(generation_plan_df["question_type"].value_counts())

======================================================================
UPDATED FAQ GENERATION PLAN
======================================================================
Total intents: 42
Total planned rows: 1344

Languages:
language
English    336
Arabic     336
French     336
Russian    336
Name: count, dtype: int64

Question Types:
question_type
Direct         504
Paraphrased    504
Scenario       336
Name: count, dtype: int64

In [74]:
generation_plan_df["ground_truth"] = (
    generation_plan_df["intent_id"]
    .map(ground_truth_catalog)
)

print("=" * 70)
print("GROUND TRUTH MAPPING")
print("=" * 70)

print("Total rows:", len(generation_plan_df))
print(
    "Missing ground truth:",
    generation_plan_df["ground_truth"].isna().sum()
)

print("\nSample:")
print(
    generation_plan_df[
        [
            "faq_id",
            "intent_id",
            "intent_name",
            "language",
            "question_type",
            "ground_truth"
        ]
    ].head(10).to_string(index=False)
)

======================================================================
GROUND TRUTH MAPPING
======================================================================
Total rows: 1344
Missing ground truth: 0

Sample:
 faq_id intent_id    intent_name language question_type                                 ground_truth
FAQ0001    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0002    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0003    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0004    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0005    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0006    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0007    INT001 hotel_location  English      Scenario Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0008    INT001 hotel_location  English      Scenario Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0009    INT001 hotel_location   Arabic        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0010    INT001 hotel_location   Arabic        Direct Nile Pearl Hotel is located in Cairo, Egypt.

In [75]:
# ============================================================
# MULTILINGUAL GROUND TRUTH STRUCTURE
# ============================================================

languages = [
    "English",
    "Arabic",
    "French",
    "Russian"
]

multilingual_ground_truth = {}

for intent_id, english_answer in ground_truth_catalog.items():

    multilingual_ground_truth[intent_id] = {
        "English": english_answer,
        "Arabic": "",
        "French": "",
        "Russian": ""
    }

print("=" * 70)
print("MULTILINGUAL GROUND TRUTH")
print("=" * 70)

print("Total intents:", len(multilingual_ground_truth))
print("Languages per intent:", len(languages))

sample_intent = "INT001"

print("\nSample:")
print("Intent:", sample_intent)

for language in languages:
    print(
        f"{language}:",
        multilingual_ground_truth[sample_intent][language]
    )

======================================================================
MULTILINGUAL GROUND TRUTH
======================================================================
Total intents: 42
Languages per intent: 4

Sample:
Intent: INT001
English: Nile Pearl Hotel is located in Cairo, Egypt.
Arabic:
French:
Russian:

In [76]:
# ============================================================
# MULTILINGUAL ANSWER TRANSLATION PLAN
# ============================================================

translation_plan = []

for intent_id, answers in multilingual_ground_truth.items():

    intent_row = intent_df_clean[
        intent_df_clean["intent_id"] == intent_id
    ].iloc[0]

    for language in ["Arabic", "French", "Russian"]:

        translation_plan.append({
            "intent_id": intent_id,
            "intent_name": intent_row["intent_name"],
            "category": intent_row["category"],
            "source": intent_row["source"],
            "language": language,
            "english_answer": answers["English"],
            "translated_answer": ""
        })

translation_plan_df = pd.DataFrame(translation_plan)

print("=" * 70)
print("ANSWER TRANSLATION PLAN")
print("=" * 70)

print("Total translation rows:", len(translation_plan_df))
print("Expected:", 42 * 3)

print("\nLanguages:")
print(
    translation_plan_df["language"].value_counts()
)

print("\nSample:")
print(
    translation_plan_df.head(10).to_string(index=False)
)

======================================================================
ANSWER TRANSLATION PLAN
======================================================================
Total translation rows: 126
Expected: 126

Languages:
language
Arabic     42
French     42
Russian    42
Name: count, dtype: int64

Sample:
intent_id            intent_name             category                 source language                               english_answer translated_answer
   INT001         hotel_location    Hotel Information  hotel_information.txt   Arabic Nile Pearl Hotel is located in Cairo, Egypt.
   INT001         hotel_location    Hotel Information  hotel_information.txt   French Nile Pearl Hotel is located in Cairo, Egypt.
   INT001         hotel_location    Hotel Information  hotel_information.txt  Russian Nile Pearl Hotel is located in Cairo, Egypt.
   INT002         hotel_category    Hotel Information  hotel_information.txt   Arabic          Nile Pearl Hotel is a 5-star hotel.
   INT002         hotel_category    Hotel Information  hotel_information.txt   French          Nile Pearl Hotel is a 5-star hotel.
   INT002         hotel_category    Hotel Information  hotel_information.txt  Russian          Nile Pearl Hotel is a 5-star hotel.
   INT003 reception_availability    Hotel Information  hotel_information.txt   Arabic               Hotel reception operates 24/7.
   INT003 reception_availability    Hotel Information  hotel_information.txt   French               Hotel reception operates 24/7.
   INT003 reception_availability    Hotel Information  hotel_information.txt  Russian               Hotel reception operates 24/7.
   INT004          check_in_time Check-in / Check-out check_in_check_out.txt   Arabic           Standard check-in time is 3:00 PM.

In [77]:
# ============================================================
# MULTILINGUAL GROUND TRUTH ANSWERS
# ============================================================

localized_answers = {

    "INT001": {
        "Arabic": "يقع فندق نايل بيرل في القاهرة، مصر.",
        "French": "Le Nile Pearl Hotel est situé au Caire, en Égypte.",
        "Russian": "Отель Nile Pearl расположен в Каире, Египет."
    },

    "INT002": {
        "Arabic": "فندق نايل بيرل هو فندق خمس نجوم.",
        "French": "Le Nile Pearl Hotel est un hôtel 5 étoiles.",
        "Russian": "Nile Pearl Hotel — пятизвездочный отель."
    },

    "INT003": {
        "Arabic": "يعمل مكتب استقبال الفندق على مدار 24 ساعة طوال أيام الأسبوع.",
        "French": "La réception de l'hôtel est ouverte 24 heures sur 24, 7 jours sur 7.",
        "Russian": "Стойка регистрации отеля работает круглосуточно."
    },

    "INT004": {
        "Arabic": "وقت تسجيل الوصول القياسي هو الساعة 3:00 مساءً.",
        "French": "L'heure standard d'enregistrement est 15h00.",
        "Russian": "Стандартное время регистрации заезда — 15:00."
    },

    "INT005": {
        "Arabic": "وقت تسجيل المغادرة القياسي هو الساعة 12:00 ظهرًا.",
        "French": "L'heure standard de départ est 12h00.",
        "Russian": "Стандартное время выезда — 12:00."
    },

    "INT006": {
        "Arabic": "تسجيل الوصول المبكر يخضع لتوافر الغرفة وموافقة الفندق.",
        "French": "L'enregistrement anticipé dépend de la disponibilité de la chambre et de l'approbation de l'hôtel.",
        "Russian": "Ранний заезд зависит от наличия свободных номеров и одобрения отеля."
    },

    "INT007": {
        "Arabic": "تسجيل المغادرة المتأخر يخضع للتوافر وقد تترتب عليه رسوم إضافية.",
        "French": "Le départ tardif dépend des disponibilités et peut entraîner des frais supplémentaires.",
        "Russian": "Поздний выезд зависит от наличия возможности и может быть платным."
    },

    "INT008": {
        "Arabic": "يُطلب من الضيوف تقديم وثائق هوية سارية عند تسجيل الوصول.",
        "French": "Les clients doivent présenter une pièce d'identité valide lors de l'enregistrement.",
        "Russian": "При регистрации заезда гости должны предъявить действительный документ, удостоверяющий личность."
    },

    "INT009": {
        "Arabic": "يوفر فندق نايل بيرل غرفًا من الأنواع التالية: Standard وDeluxe وSuperior وFamily وExecutive.",
        "French": "Le Nile Pearl Hotel propose les types de chambres suivants : Standard, Deluxe, Superior, Family et Executive.",
        "Russian": "Nile Pearl Hotel предлагает следующие типы номеров: Standard, Deluxe, Superior, Family и Executive."
    },

    "INT010": {
        "Arabic": "تعتمد سعة الغرفة على نوعها. تستوعب غرفتا Standard وDeluxe ما يصل إلى ضيفين، وتستوعب Superior ما يصل إلى 3 ضيوف، وFamily ما يصل إلى 4 ضيوف. سعة غرفة Executive غير محددة في قاعدة المعرفة الحالية.",
        "French": "La capacité dépend du type de chambre. Les chambres Standard et Deluxe peuvent accueillir jusqu'à 2 personnes, la Superior jusqu'à 3 personnes et la Family jusqu'à 4 personnes. La capacité de la chambre Executive n'est pas précisée dans la base de connaissances actuelle.",
        "Russian": "Вместимость зависит от типа номера. Номера Standard и Deluxe рассчитаны максимум на 2 гостей, Superior — на 3 гостей, а Family — на 4 гостей. Вместимость номера Executive в текущей базе знаний не указана."
    },

    "INT011": {
        "Arabic": "تختلف وسائل الراحة حسب نوع الغرفة، وقد تشمل الحمام الخاص وخدمة الواي فاي وتكييف الهواء والتلفزيون والأسرة المريحة ووسائل الراحة المطورة.",
        "French": "Les équipements varient selon le type de chambre et peuvent inclure une salle de bains privative, le Wi-Fi, la climatisation, une télévision, des lits confortables et des équipements améliorés.",
        "Russian": "Удобства зависят от типа номера и могут включать отдельную ванную комнату, Wi-Fi, кондиционер, телевизор, удобную кровать и улучшенные удобства."
    },

    "INT012": {
        "Arabic": "الأطفال مرحب بهم. تخضع الأسرّة الإضافية أو أماكن الإقامة الإضافية لسعة الغرفة والتوافر.",
        "French": "Les enfants sont les bienvenus. Les lits supplémentaires ou les hébergements additionnels dépendent de la capacité de la chambre et des disponibilités.",
        "Russian": "Дети могут проживать в отеле. Дополнительные кровати или размещение зависят от вместимости номера и наличия свободных мест."
    },

    "INT013": {
        "Arabic": "تشمل عملية الحجز اختيار التواريخ، واختيار الغرفة، وتقديم معلومات الضيف، ومراجعة الحجز، ثم تأكيده.",
        "French": "Le processus de réservation comprend la sélection des dates, le choix de la chambre, la fourniture des informations du client, la vérification de la réservation et sa confirmation.",
        "Russian": "Процесс бронирования включает выбор дат, выбор номера, предоставление информации о госте, проверку данных бронирования и подтверждение."
    },

    "INT014": {
        "Arabic": "قد تتضمن معلومات الحجز الاسم الكامل للضيف، وعدد الضيوف، وتاريخ تسجيل الوصول، وتاريخ تسجيل المغادرة، ونوع الغرفة، ومعلومات الاتصال، ومعلومات الدفع عند الحاجة.",
        "French": "Les informations de réservation peuvent inclure le nom complet du client, le nombre de personnes, les dates d'arrivée et de départ, le type de chambre, les coordonnées et les informations de paiement lorsque cela est requis.",
        "Russian": "Информация для бронирования может включать полное имя гостя, количество гостей, даты заезда и выезда, тип номера, контактные данные и платежную информацию, если это требуется."
    },

    "INT015": {
        "Arabic": "يمكن للضيوف التواصل مع خدمة العملاء لطلب تعديل الحجوزات. تخضع التعديلات للتوافر وموافقة الفندق.",
        "French": "Les clients peuvent contacter le service client pour demander des modifications à leur réservation. Les modifications dépendent des disponibilités et de l'approbation de l'hôtel.",
        "Russian": "Гости могут обратиться в службу поддержки, чтобы изменить бронирование. Изменения зависят от наличия свободных номеров и одобрения отеля."
    },

    "INT016": {
        "Arabic": "يتم تأكيد الحجز بعد تقديم معلومات الحجز المطلوبة وإتمام عملية الحجز.",
        "French": "Une réservation est confirmée après la fourniture des informations requises et l'achèvement du processus de réservation.",
        "Russian": "Бронирование подтверждается после предоставления необходимой информации и завершения процесса бронирования."
    },

    "INT017": {
        "Arabic": "يمكن للضيوف التواصل مع خدمة العملاء لطلب المساعدة في إلغاء الحجز، ويجب عليهم تقديم تفاصيل الحجز ذات الصلة.",
        "French": "Les clients peuvent contacter le service client pour demander de l'aide concernant l'annulation et doivent fournir les informations pertinentes de la réservation.",
        "Russian": "Гости могут обратиться в службу поддержки для отмены бронирования и должны предоставить соответствующие данные бронирования."
    },

    "INT018": {
        "Arabic": "تعتمد أهلية إلغاء الحجز على الشروط المرتبطة بالحجز.",
        "French": "L'éligibilité à l'annulation dépend des conditions associées à la réservation.",
        "Russian": "Возможность отмены зависит от условий, связанных с бронированием."
    },

    "INT019": {
        "Arabic": "تعتمد أي رسوم إلغاء مطبقة على شروط الإلغاء المرتبطة بالحجز.",
        "French": "Les éventuels frais d'annulation dépendent des conditions d'annulation associées à la réservation.",
        "Russian": "Размер возможной платы за отмену зависит от условий отмены, связанных с бронированием."
    },

    "INT020": {
        "Arabic": "لا تحدد قاعدة المعرفة الحالية طرق الدفع المقبولة في الفندق. يجب على الضيوف التواصل مع خدمة العملاء لمعرفة طرق الدفع المتاحة حاليًا.",
        "French": "La base de connaissances actuelle ne précise pas les modes de paiement acceptés par l'hôtel. Les clients doivent contacter le service client pour connaître les modes de paiement actuellement disponibles.",
        "Russian": "В текущей базе знаний не указаны точные способы оплаты, принимаемые отелем. Гостям следует обратиться в службу поддержки для получения актуальной информации."
    },

    "INT021": {
        "Arabic": "تعتمد متطلبات الدفع على الحجز المحدد وسياسات الفندق المعمول بها.",
        "French": "Les exigences de paiement dépendent de la réservation sélectionnée et des politiques de l'hôtel applicables.",
        "Russian": "Требования к оплате зависят от выбранного бронирования и действующих правил отеля."
    },

    "INT022": {
        "Arabic": "قد يتم تطبيق رسوم إضافية على بعض خدمات الفندق أو الأضرار التي تلحق بممتلكات الفندق.",
        "French": "Des frais supplémentaires peuvent s'appliquer à certains services de l'hôtel ou aux dommages causés aux biens de l'hôtel.",
        "Russian": "За некоторые услуги отеля или повреждение имущества отеля может взиматься дополнительная плата."
    },

    "INT023": {
        "Arabic": "تعتمد أهلية استرداد المبلغ على الشروط المرتبطة بالحجز.",
        "French": "L'éligibilité au remboursement dépend des conditions associées à la réservation.",
        "Russian": "Возможность возврата средств зависит от условий, связанных с бронированием."
    },

    "INT024": {
        "Arabic": "تتم معالجة المبالغ المستردة المؤهلة وفقًا لشروط الدفع والاسترداد المعمول بها. لا تحدد قاعدة المعرفة الحالية مدة ثابتة لمعالجة الاسترداد.",
        "French": "Les remboursements admissibles sont traités conformément aux conditions de paiement et de remboursement applicables. La base de connaissances actuelle ne précise pas de délai fixe de traitement.",
        "Russian": "Подлежащие возврату средства обрабатываются в соответствии с действующими условиями оплаты и возврата. В текущей базе знаний не указан фиксированный срок обработки возврата."
    },

    "INT025": {
        "Arabic": "يتوفر الإفطار يوميًا من الساعة 7:00 صباحًا حتى 10:30 صباحًا في المطعم الرئيسي.",
        "French": "Le petit-déjeuner est servi tous les jours de 7h00 à 10h30 au restaurant principal.",
        "Russian": "Завтрак подается ежедневно с 7:00 до 10:30 в главном ресторане."
    },

    "INT026": {
        "Arabic": "سعر الإفطار هو 450 جنيهًا مصريًا للشخص الواحد.",
        "French": "Le petit-déjeuner coûte 450 EGP par personne.",
        "Russian": "Стоимость завтрака составляет 450 EGP с человека."
    },

    "INT027": {
        "Arabic": "خدمة الغرف متاحة على مدار 24 ساعة. يمكن للضيوف طلب الطعام والمشروبات مباشرة إلى غرفهم.",
        "French": "Le service d'étage est disponible 24 heures sur 24. Les clients peuvent commander de la nourriture et des boissons directement dans leur chambre.",
        "Russian": "Обслуживание номеров доступно круглосуточно. Гости могут заказывать еду и напитки прямо в номер."
    },

    "INT028": {
        "Arabic": "خدمة النقل من وإلى المطار متاحة عند الطلب وتكلف 800 جنيه مصري للرحلة الواحدة.",
        "French": "Le transfert aéroport est disponible sur demande et coûte 800 EGP par trajet.",
        "Russian": "Трансфер из аэропорта и в аэропорт предоставляется по запросу и стоит 800 EGP за поездку."
    },

    "INT029": {
        "Arabic": "خدمات غسيل الملابس والتنظيف الجاف متاحة يوميًا، وتبلغ تكلفة خدمة غسيل الملابس 200 جنيه مصري لكل كيلوغرام.",
        "French": "Le service de blanchisserie et de nettoyage à sec est disponible tous les jours. Le service de blanchisserie coûte 200 EGP par kilogramme.",
        "Russian": "Услуги прачечной и химчистки доступны ежедневно. Стоимость стирки составляет 200 EGP за килограмм."
    },

    "INT030": {
        "Arabic": "تتوفر علاجات السبا من الساعة 9:00 صباحًا حتى 10:00 مساءً، وتبلغ تكلفة الجلسة 1,200 جنيه مصري.",
        "French": "Les soins du spa sont disponibles de 9h00 à 22h00 et coûtent 1 200 EGP par séance.",
        "Russian": "Спа-процедуры доступны с 9:00 до 22:00 и стоят 1 200 EGP за сеанс."
    },

    "INT031": {
        "Arabic": "صالة الألعاب الرياضية في الفندق متاحة على مدار 24 ساعة لنزلاء الفندق.",
        "French": "La salle de sport de l'hôtel est disponible 24 heures sur 24 pour les clients de l'hôtel.",
        "Russian": "Тренажерный зал отеля доступен круглосуточно для гостей."
    },

    "INT032": {
        "Arabic": "يقدم المطعم الرئيسي الإفطار يوميًا من الساعة 7:00 صباحًا حتى 10:30 صباحًا. ولا تحدد قاعدة المعرفة الحالية خدمات المطعم خارج فترة الإفطار.",
        "French": "Le restaurant principal sert le petit-déjeuner tous les jours de 7h00 à 10h30. La base de connaissances actuelle ne précise pas les services du restaurant en dehors du petit-déjeuner.",
        "Russian": "Главный ресторан ежедневно подает завтрак с 7:00 до 10:30. В текущей базе знаний не указаны услуги ресторана вне времени завтрака."
    },

    "INT033": {
        "Arabic": "تتوفر خدمة الواي فاي المجانية على مدار 24 ساعة في جميع غرف الضيوف والمناطق العامة.",
        "French": "Le Wi-Fi gratuit est disponible 24 heures sur 24 dans toutes les chambres et les espaces publics.",
        "Russian": "Бесплатный Wi-Fi доступен круглосуточно во всех номерах и общественных зонах."
    },

    "INT034": {
        "Arabic": "موقف السيارات متاح لنزلاء الفندق.",
        "French": "Le parking est disponible pour les clients de l'hôtel.",
        "Russian": "Парковка доступна для гостей отеля."
    },

    "INT035": {
        "Arabic": "حمام السباحة متاح لنزلاء الفندق من الساعة 7:00 صباحًا حتى 9:00 مساءً.",
        "French": "La piscine est disponible pour les clients de l'hôtel de 7h00 à 21h00.",
        "Russian": "Бассейн доступен для гостей отеля с 7:00 до 21:00."
    },

    "INT036": {
        "Arabic": "لا يُسمح بالحيوانات الأليفة داخل الفندق، بما في ذلك غرف الضيوف ومرافق الفندق.",
        "French": "Les animaux domestiques ne sont pas autorisés dans l'hôtel, y compris dans les chambres et les installations.",
        "Russian": "Домашние животные не допускаются в отель, включая номера и гостиничные объекты."
    },

    "INT037": {
        "Arabic": "يُمنع التدخين داخل غرف الضيوف والمناطق العامة الداخلية. توجد مناطق مخصصة للتدخين.",
        "French": "Il est interdit de fumer dans les chambres et les espaces publics intérieurs. Des zones fumeurs désignées sont disponibles.",
        "Russian": "Курение запрещено в номерах и внутренних общественных зонах. Для курения предусмотрены специальные места."
    },

    "INT038": {
        "Arabic": "الأطفال مرحب بهم في الفندق. تخضع الأسرّة الإضافية أو أماكن الإقامة الإضافية لسعة الغرفة والتوافر.",
        "French": "Les enfants sont les bienvenus à l'hôtel. Les lits supplémentaires ou les hébergements additionnels dépendent de la capacité de la chambre et des disponibilités.",
        "Russian": "Дети могут проживать в отеле. Дополнительные кровати или размещение зависят от вместимости номера и наличия свободных мест."
    },

    "INT039": {
        "Arabic": "يجب على الضيوف الذين يفقدون أحد أغراضهم التواصل مع مكتب الاستقبال. تتم إدارة الأشياء التي يتم العثور عليها داخل الفندق من خلال قسم المفقودات.",
        "French": "Les clients qui perdent un objet doivent contacter la réception. Les objets trouvés dans l'hôtel sont pris en charge par le service des objets trouvés.",
        "Russian": "Гостям, потерявшим вещь, следует обратиться на стойку регистрации. Найденные в отеле вещи передаются в отдел находок."
    },

    "INT040": {
        "Arabic": "يجب على الضيوف الحفاظ على مستويات ضوضاء معقولة، خاصة خلال ساعات الليل.",
        "French": "Les clients doivent maintenir un niveau sonore raisonnable, en particulier pendant les heures nocturnes.",
        "Russian": "Гости должны соблюдать разумный уровень шума, особенно в ночное время."
    },

    "INT041": {
        "Arabic": "يُتوقع من الضيوف احترام ممتلكات الفندق وموظفيه والضيوف الآخرين. وقد تؤدي الأضرار التي تلحق بممتلكات الفندق إلى رسوم إضافية.",
        "French": "Les clients sont tenus de respecter les biens de l'hôtel, son personnel et les autres clients. Les dommages causés aux biens de l'hôtel peuvent entraîner des frais supplémentaires.",
        "Russian": "Гости должны уважать имущество отеля, персонал и других гостей. Повреждение имущества отеля может привести к дополнительным расходам."
    },

    "INT042": {
        "Arabic": "تتم معالجة معلومات الضيوف وفقًا لإجراءات الخصوصية والأمان الخاصة بالفندق. ولا توفر قاعدة المعرفة الحالية سياسة الخصوصية الكاملة أو فترات الاحتفاظ المحددة بالبيانات.",
        "French": "Les informations des clients sont traitées conformément aux procédures de confidentialité et de sécurité de l'hôtel. La base de connaissances actuelle ne fournit pas la politique de confidentialité complète ni les périodes précises de conservation des données.",
        "Russian": "Информация о гостях обрабатывается в соответствии с процедурами конфиденциальности и безопасности отеля. В текущей базе знаний не указана полная политика конфиденциальности или конкретные сроки хранения данных."
    },

    "INT043": {
        "Arabic": "في حالة الطوارئ، يجب على الضيوف التواصل مع مكتب استقبال الفندق فورًا. يعمل مكتب الاستقبال على مدار 24 ساعة.",
        "French": "En cas d'urgence, les clients doivent contacter immédiatement la réception de l'hôtel. La réception est ouverte 24 heures sur 24.",
        "Russian": "В случае чрезвычайной ситуации гости должны немедленно обратиться на стойку регистрации. Стойка регистрации работает круглосуточно."
    }
}

In [78]:
# Keep only active intents
localized_answers = {
    intent_id: answers
    for intent_id, answers in localized_answers.items()
    if intent_id in set(intent_df_clean["intent_id"])
}

print("=" * 70)
print("LOCALIZED ANSWERS VALIDATION")
print("=" * 70)

print("Active intents:", len(intent_df_clean))
print("Localized intents:", len(localized_answers))

expected_languages = {"Arabic", "French", "Russian"}

missing = []

for intent_id in intent_df_clean["intent_id"]:

    if intent_id not in localized_answers:
        missing.append((intent_id, "all"))

        continue

    for language in expected_languages:

        if not localized_answers[intent_id].get(language, "").strip():
            missing.append((intent_id, language))

print("Missing translations:", len(missing))

if missing:
    print("⚠️ Missing:")
    for item in missing:
        print(item)
else:
    print("✅ ALL ACTIVE INTENTS HAVE ARABIC, FRENCH AND RUSSIAN ANSWERS")

======================================================================
LOCALIZED ANSWERS VALIDATION
======================================================================
Active intents: 42
Localized intents: 42
Missing translations: 0
✅ ALL ACTIVE INTENTS HAVE ARABIC, FRENCH AND RUSSIAN ANSWERS

In [79]:
# ============================================================
# BUILD FINAL MULTILINGUAL GROUND TRUTH
# ============================================================

def get_ground_truth(row):

    intent_id = row["intent_id"]
    language = row["language"]

    # English answer
    if language == "English":
        return ground_truth_catalog[intent_id]

    # Arabic / French / Russian
    return localized_answers[intent_id][language]


generation_plan_df["ground_truth"] = generation_plan_df.apply(
    get_ground_truth,
    axis=1
)

print("=" * 70)
print("FINAL GROUND TRUTH MAPPING")
print("=" * 70)

print("Total rows:", len(generation_plan_df))

print(
    "Missing ground truth:",
    generation_plan_df["ground_truth"].isna().sum()
)

print(
    "Empty ground truth:",
    (
        generation_plan_df["ground_truth"]
        .astype(str)
        .str.strip()
        .eq("")
    ).sum()
)

print("\nGround truth by language:")

print(
    generation_plan_df
    .groupby("language")["ground_truth"]
    .count()
)

print("\nSample:")

print(
    generation_plan_df[
        [
            "faq_id",
            "intent_id",
            "intent_name",
            "language",
            "question_type",
            "ground_truth"
        ]
    ].head(12).to_string(index=False)
)

======================================================================
FINAL GROUND TRUTH MAPPING
======================================================================
Total rows: 1344
Missing ground truth: 0
Empty ground truth: 0

Ground truth by language:
language
Arabic     336
English    336
French     336
Russian    336
Name: ground_truth, dtype: int64

Sample:
 faq_id intent_id    intent_name language question_type                                 ground_truth
FAQ0001    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0002    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0003    INT001 hotel_location  English        Direct Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0004    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0005    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0006    INT001 hotel_location  English   Paraphrased Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0007    INT001 hotel_location  English      Scenario Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0008    INT001 hotel_location  English      Scenario Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0009    INT001 hotel_location   Arabic        Direct          يقع فندق نايل بيرل في القاهرة، مصر.
FAQ0010    INT001 hotel_location   Arabic        Direct          يقع فندق نايل بيرل في القاهرة، مصر.
FAQ0011    INT001 hotel_location   Arabic        Direct          يقع فندق نايل بيرل في القاهرة، مصر.
FAQ0012    INT001 hotel_location   Arabic   Paraphrased          يقع فندق نايل بيرل في القاهرة، مصر.

In [80]:
# ============================================================
# PREPARE FINAL FAQ DATASET
# ============================================================

faq_df = generation_plan_df.copy()

faq_df["question"] = ""
faq_df["answer"] = faq_df["ground_truth"]

faq_df = faq_df[
    [
        "faq_id",
        "intent_id",
        "intent_name",
        "category",
        "language",
        "question_type",
        "difficulty",
        "question",
        "answer",
        "ground_truth",
        "source"
    ]
]

print("=" * 70)
print("FINAL FAQ DATASET STRUCTURE")
print("=" * 70)

print("Rows:", len(faq_df))
print("Columns:", len(faq_df.columns))

print("\nColumns:")
print(faq_df.columns.tolist())

print("\nMissing values:")
print(faq_df.isna().sum())

======================================================================
FINAL FAQ DATASET STRUCTURE
======================================================================
Rows: 1344
Columns: 11

Columns:
['faq_id', 'intent_id', 'intent_name', 'category', 'language', 'question_type', 'difficulty', 'question', 'answer', 'ground_truth', 'source']

Missing values:
faq_id           0
intent_id        0
intent_name      0
category         0
language         0
question_type    0
difficulty       0
question         0
answer           0
ground_truth     0
source           0
dtype: int64

In [81]:
# ============================================================
# QUESTION GENERATION RULES
# ============================================================

question_rules = {
    "Direct": {
        "count": 3,
        "description": "Ask the intent directly and clearly.",
        "style": "Short, natural, factual question."
    },

    "Paraphrased": {
        "count": 3,
        "description": "Ask the same intent using different wording.",
        "style": "Natural variation without changing the meaning."
    },

    "Scenario": {
        "count": 2,
        "description": "Ask the intent through a realistic hotel guest situation.",
        "style": "Natural customer scenario followed by a question."
    }
}

print("=" * 70)
print("QUESTION GENERATION RULES")
print("=" * 70)

for q_type, rule in question_rules.items():
    print(f"\n{q_type}")
    print("Count:", rule["count"])
    print("Description:", rule["description"])
    print("Style:", rule["style"])

======================================================================
QUESTION GENERATION RULES
======================================================================

Direct
Count: 3
Description: Ask the intent directly and clearly.
Style: Short, natural, factual question.

Paraphrased
Count: 3
Description: Ask the same intent using different wording.
Style: Natural variation without changing the meaning.

Scenario
Count: 2
Description: Ask the intent through a realistic hotel guest situation.
Style: Natural customer scenario followed by a question.

In [82]:
def build_question_prompt(row):
    
    return f"""
You are generating training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
{row['intent_name']}

CATEGORY:
{row['category']}

LANGUAGE:
{row['language']}

QUESTION TYPE:
{row['question_type']}

GROUND TRUTH:
{row['ground_truth']}

SOURCE:
{row['source']}

TASK:
Generate ONE natural guest question that matches the specified intent.

RULES:
1. The question MUST be written in {row['language']}.
2. The question MUST match the intent exactly.
3. Do not introduce information that is not supported by the ground truth.
4. Do not change prices, times, policies, room capacities, or conditions.
5. Direct questions must be clear and straightforward.
6. Paraphrased questions must use different wording but preserve the exact meaning.
7. Scenario questions must describe a realistic guest situation.
8. Do not answer the question.
9. Do not mention the intent name.
10. Return ONLY the question.

Generate one question now.
"""

In [84]:
# ============================================================
# IMPROVED QUESTION GENERATION PROMPT
# ============================================================

def build_question_prompt(row, existing_questions=None):

    if existing_questions is None:
        existing_questions = []

    previous_questions = "\n".join(
        f"- {q}" for q in existing_questions
    )

    if not previous_questions:
        previous_questions = "None"

    return f"""
You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
{row['intent_name']}

CATEGORY:
{row['category']}

LANGUAGE:
{row['language']}

QUESTION TYPE:
{row['question_type']}

GROUND TRUTH:
{row['ground_truth']}

SOURCE:
{row['source']}

PREVIOUS QUESTIONS FOR THIS INTENT:
{previous_questions}

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in {row['language']}.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.
"""

In [85]:
# ============================================================
# PILOT TEST - INT001
# ============================================================

test_rows = faq_df[
    faq_df["intent_id"] == "INT001"
].copy()

existing_questions = []

for _, row in test_rows.iterrows():

    prompt = build_question_prompt(
        row,
        existing_questions
    )

    print("=" * 70)
    print("FAQ ID:", row["faq_id"])
    print("Language:", row["language"])
    print("Type:", row["question_type"])
    print("=" * 70)
    print(prompt)

    # بعد ما نستخدم الـLLM لإنتاج السؤال:
    # existing_questions.append(generated_question)

======================================================================
FAQ ID: FAQ0001
Language: English
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Direct

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0002
Language: English
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Direct

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0003
Language: English
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Direct

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0004
Language: English
Type: Paraphrased
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Paraphrased

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0005
Language: English
Type: Paraphrased
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Paraphrased

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0006
Language: English
Type: Paraphrased
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Paraphrased

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0007
Language: English
Type: Scenario
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Scenario

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0008
Language: English
Type: Scenario
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
English

QUESTION TYPE:
Scenario

GROUND TRUTH:
Nile Pearl Hotel is located in Cairo, Egypt.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in English.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0009
Language: Arabic
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
Arabic

QUESTION TYPE:
Direct

GROUND TRUTH:
يقع فندق نايل بيرل في القاهرة، مصر.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in Arabic.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0010
Language: Arabic
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
Arabic

QUESTION TYPE:
Direct

GROUND TRUTH:
يقع فندق نايل بيرل في القاهرة، مصر.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in Arabic.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0011
Language: Arabic
Type: Direct
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
Arabic

QUESTION TYPE:
Direct

GROUND TRUTH:
يقع فندق نايل بيرل في القاهرة، مصر.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in Arabic.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.
10. The new question must be meaningfully different from previous questions.

QUESTION TYPE RULES:

Direct:
Ask the intent clearly and directly.

Paraphrased:
Ask the same intent using substantially different wording while preserving the exact meaning.

Scenario:
Create a realistic hotel guest situation that naturally leads to the same intent.

QUALITY REQUIREMENTS:

- Natural human wording.
- Concise.
- Relevant to a hotel guest.
- No unnecessary details.
- No invented facts.
- No repetition.

Return ONLY ONE question.
Do not include quotation marks.
Do not include explanations.

Generate the question now.

======================================================================
FAQ ID: FAQ0012
Language: Arabic
Type: Paraphrased
======================================================================

You are generating high-quality training data for a multilingual hotel AI assistant.

HOTEL:
Nile Pearl Hotel

INTENT:
hotel_location

CATEGORY:
Hotel Information

LANGUAGE:
Arabic

QUESTION TYPE:
Paraphrased

GROUND TRUTH:
يقع فندق نايل بيرل في القاهرة، مصر.

SOURCE:
hotel_information.txt

PREVIOUS QUESTIONS FOR THIS INTENT:
None

TASK:
Generate ONE natural guest question that matches the specified intent.

STRICT RULES:

1. The question MUST be written entirely in Arabic.
2. The question MUST match the intent exactly.
3. The question MUST be answerable using the provided ground truth.
4. Do NOT introduce information that is not supported by the ground truth.
5. Do NOT change prices, times, policies, room capacities, or conditions.
6. Do NOT ask about multiple intents in the same question.
7. Do NOT answer the question.
8. Do NOT mention the intent name.
9. Do NOT copy any previous question.

In [86]:
!pip install openai -q

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
httpcore 0.9.1 requires h11<0.10,>=0.8, but you have h11 0.16.0 which is incompatible.
httpx 0.13.3 requires idna==2.*, but you have idna 3.18 which is incompatible.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
from openai import OpenAI
import getpass

api_key = getpass.getpass("Enter your OpenAI API key: ")

client = OpenAI(api_key=api_key)

print("✅ OpenAI client initialized successfully.")

✅ OpenAI client initialized successfully.

In [91]:
import os

# ============================================================
# HOTEL AI - FULL PROJECT STRUCTURE
# ============================================================

PROJECT_ROOT = "."

print("=" * 80)
print("HOTEL AI - CURRENT PROJECT STRUCTURE")
print("=" * 80)

def print_tree(path, prefix=""):
    
    try:
        items = sorted(
            os.listdir(path),
            key=lambda x: (not os.path.isdir(os.path.join(path, x)), x.lower())
        )
    except PermissionError:
        print(prefix + "⚠️ Permission denied")
        return

    for index, item in enumerate(items):

        full_path = os.path.join(path, item)
        is_last = index == len(items) - 1

        connector = "└── " if is_last else "├── "
        print(prefix + connector + item)

        if os.path.isdir(full_path):
            extension = "    " if is_last else "│   "
            print_tree(full_path, prefix + extension)


print_tree(PROJECT_ROOT)

print("\n" + "=" * 80)
print("IMPORTANT FILE CHECK")
print("=" * 80)

important_paths = [
    "02_Hotel_Knowledge",
    "03_Structured_Data",
    "data",
    "database",
    "scripts",
    "README.md",
    "generate_hotel_faq.ipynb"
]

for path in important_paths:

    if os.path.exists(path):
        if os.path.isdir(path):
            print(f"✅ {path}/")
        else:
            size = os.path.getsize(path)
            print(f"✅ {path} ({size:,} bytes)")
    else:
        print(f"❌ {path} - MISSING")

================================================================================
HOTEL AI - CURRENT PROJECT STRUCTURE
================================================================================
├── 02_Hotel_Knowledge
│   ├── Booking
│   │   ├── booking_confirmation.txt
│   │   ├── booking_modification.txt
│   │   ├── booking_policy.txt
│   │   └── booking_process.txt
│   ├── Cancellation
│   │   ├── cancellation_policy.txt
│   │   └── cancellation_process.txt
│   ├── Hotel_Information
│   │   ├── contact_information.txt
│   │   ├── hotel_facilities.txt
│   │   └── hotel_information.txt
│   ├── Payment
│   │   ├── payment_methods.txt
│   │   ├── payment_policy.txt
│   │   └── refund_policy.txt
│   ├── Policies
│   │   ├── check_in_check_out.txt
│   │   ├── children_policy.txt
│   │   ├── emergency_policy.txt
│   │   ├── guest_conduct.txt
│   │   ├── identification_policy.txt
│   │   ├── lost_and_found.txt
│   │   ├── noise_policy.txt
│   │   ├── pet_policy.txt
│   │   ├── privacy_policy.txt
│   │   └── smoking_policy.txt
│   ├── Rooms
│   │   ├── room_amenities.txt
│   │   ├── room_policies.txt
│   │   └── room_types.txt
│   └── Services
│       ├── airport_transfer.txt
│       ├── breakfast.txt
│       ├── gym.txt
│       ├── laundry.txt
│       ├── restaurant.txt
│       ├── room_service.txt
│       └── spa.txt
├── 03_Structured_Data
│   ├── CSV
│   │   └── hotel_faq.csv
│   ├── Excel
│   └── JSON
│       └── 03_Structured_Data
│           └── JSON
│               └── hotel_config.json
├── 04_Data_Preparation
├── data
│   ├── bookings.csv
│   ├── customer_requests.csv
│   ├── customers.csv
│   ├── payments.csv
│   ├── room_types.csv
│   ├── rooms.csv
│   └── services.csv
├── database
│   └── hotel_ai_final_backup.backup
├── scripts
│   ├── generate_bookings.ipynb
│   ├── generate_customer_requests.ipynb
│   ├── generate_customers.ipynb
│   ├── generate_payments.ipynb
│   ├── generate_room_types.ipynb
│   ├── generate_rooms.ipynb
│   ├── generate_services.ipynb
│   └── validate_hotel_data.ipynb
├── generate_hotel_faq.ipynb
└── README.md

================================================================================
IMPORTANT FILE CHECK
================================================================================
✅ 02_Hotel_Knowledge/
✅ 03_Structured_Data/
✅ data/
✅ database/
✅ scripts/
✅ README.md (0 bytes)
✅ generate_hotel_faq.ipynb (0 bytes)

In [2]:
# ============================================================
# INT005 - CLEAN START
# ============================================================

import os
import pandas as pd
import numpy as np
from difflib import SequenceMatcher
from IPython.display import display

print("=" * 80)
print("INT005 CLEAN START")
print("=" * 80)

# ------------------------------------------------------------
# Current working directory
# ------------------------------------------------------------

print("Current directory:")
print(os.getcwd())

# ------------------------------------------------------------
# Load generation plan
# ------------------------------------------------------------

generation_plan_path = (
    "03_Structured_Data/CSV/faq_generation_plan.csv"
)

if not os.path.exists(generation_plan_path):
    raise FileNotFoundError(
        f"Generation plan not found:\n"
        f"{generation_plan_path}\n\n"
        f"Current directory: {os.getcwd()}"
    )

generation_plan = pd.read_csv(
    generation_plan_path
)

print("\nGeneration plan loaded successfully.")
print("Shape:", generation_plan.shape)

# ------------------------------------------------------------
# Select INT005
# ------------------------------------------------------------

int005_rows = generation_plan[
    generation_plan["intent_id"] == "INT005"
].copy()

print("\nINT005 rows:", len(int005_rows))

# ------------------------------------------------------------
# Basic validation
# ------------------------------------------------------------

if len(int005_rows) == 0:
    raise ValueError(
        "❌ INT005 was not found in generation_plan."
    )

print("\nLanguages:")
print(int005_rows["language"].value_counts())

print("\nQuestion types:")
print(int005_rows["question_type"].value_counts())

print("\nFAQ IDs:")
print(int005_rows["faq_id"].tolist())

print("\n" + "=" * 80)
print("✅ INT005 CLEAN START READY")
print("=" * 80)

================================================================================
INT005 CLEAN START
================================================================================
Current directory:
c:\Users\User\OneDrive\سطح المكتب\HotelAI

Generation plan loaded successfully.
Shape: (1344, 11)

INT005 rows: 32

Languages:
language
English    8
Arabic     8
French     8
Russian    8
Name: count, dtype: int64

Question types:
question_type
Direct         12
Paraphrased    12
Scenario        8
Name: count, dtype: int64

FAQ IDs:
['FAQ0129', 'FAQ0130', 'FAQ0131', 'FAQ0132', 'FAQ0133', 'FAQ0134', 'FAQ0135', 'FAQ0136', 'FAQ0137', 'FAQ0138', 'FAQ0139', 'FAQ0140', 'FAQ0141', 'FAQ0142', 'FAQ0143', 'FAQ0144', 'FAQ0145', 'FAQ0146', 'FAQ0147', 'FAQ0148', 'FAQ0149', 'FAQ0150', 'FAQ0151', 'FAQ0152', 'FAQ0153', 'FAQ0154', 'FAQ0155', 'FAQ0156', 'FAQ0157', 'FAQ0158', 'FAQ0159', 'FAQ0160']

================================================================================
✅ INT005 CLEAN START READY
================================================================================

In [3]:
# ============================================================
# INT005 - PREPARATION & GROUND TRUTH CHECK
# ============================================================

print("=" * 80)
print("INT005 PREPARATION")
print("=" * 80)

# ------------------------------------------------------------
# Basic columns check
# ------------------------------------------------------------

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type"
]

missing_columns = [
    col for col in required_columns
    if col not in int005_rows.columns
]

if missing_columns:
    raise ValueError(
        f"❌ Missing columns: {missing_columns}"
    )

print("Required columns: OK")

# ------------------------------------------------------------
# Ground truth
# ------------------------------------------------------------

ground_truth_columns = [
    col for col in int005_rows.columns
    if "ground" in col.lower()
    or "truth" in col.lower()
    or "answer" in col.lower()
]

print("\nPossible ground-truth columns:")
print(ground_truth_columns)

if ground_truth_columns:
    for col in ground_truth_columns:
        print(f"\n{col}:")
        print(int005_rows[col].dropna().unique())

# ------------------------------------------------------------
# Question column check
# ------------------------------------------------------------

if "question" in int005_rows.columns:

    non_empty = (
        int005_rows["question"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print("\nQuestion column: FOUND")
    print("Non-empty questions:", non_empty)

else:
    print("\nQuestion column: NOT FOUND")

# ------------------------------------------------------------
# INTENT ID check
# ------------------------------------------------------------

print("\nIntent IDs:")
print(int005_rows["intent_id"].unique())

# ------------------------------------------------------------
# Final preparation summary
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INT005 PREPARATION SUMMARY")
print("=" * 80)

print("Rows:", len(int005_rows))
print("Unique FAQ IDs:", int005_rows["faq_id"].nunique())
print("Languages:", int005_rows["language"].nunique())
print("Question types:", int005_rows["question_type"].nunique())

print("\n" + "=" * 80)
print("✅ INT005 PREPARATION COMPLETE")
print("=" * 80)

================================================================================
INT005 PREPARATION
================================================================================
Required columns: OK

Possible ground-truth columns:
['answer', 'ground_truth']

answer:
[]

ground_truth:
['Standard check-out time is 12:00 PM.']

Question column: FOUND
Non-empty questions: 0

Intent IDs:
['INT005']

================================================================================
INT005 PREPARATION SUMMARY
================================================================================
Rows: 32
Unique FAQ IDs: 32
Languages: 4
Question types: 3

================================================================================
✅ INT005 PREPARATION COMPLETE
================================================================================

In [15]:
# ============================================================
# INT005 - SIMILARITY FUNCTION
# ============================================================

from difflib import SequenceMatcher
import re

def normalize_text(text):
    """
    Normalize text before similarity comparison.
    """

    text = str(text).lower().strip()

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    # Remove punctuation
    text = re.sub(r"[^\w\s\u0600-\u06FF\u0400-\u04FF]", "", text)

    return text


def similarity_score(text1, text2):
    """
    Calculate similarity between two texts.
    Returns value between 0 and 1.
    """

    text1 = normalize_text(text1)
    text2 = normalize_text(text2)

    if not text1 or not text2:
        return 0.0

    return SequenceMatcher(
        None,
        text1,
        text2
    ).ratio()


print("=" * 80)
print("INT005 SIMILARITY FUNCTION")
print("=" * 80)

# ------------------------------------------------------------
# Test
# ------------------------------------------------------------

test_1 = "What time is check-out?"
test_2 = "What is the standard check-out time?"

score = similarity_score(test_1, test_2)

print("Test similarity:", round(score, 3))

print("\n" + "=" * 80)
print("Status: READY")
print("=" * 80)

================================================================================
INT005 SIMILARITY FUNCTION
================================================================================
Test similarity: 0.655

================================================================================
Status: READY
================================================================================

In [5]:
# ============================================================
# INT005 - OLLAMA CONFIGURATION
# ============================================================

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:7b"

print("=" * 80)
print("OLLAMA CONFIGURATION")
print("=" * 80)

print("URL:", OLLAMA_URL)
print("Model:", OLLAMA_MODEL)

# ------------------------------------------------------------
# Check Ollama connection
# ------------------------------------------------------------

try:

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": OLLAMA_MODEL,
            "prompt": "Reply with exactly: READY",
            "stream": False
        },
        timeout=60
    )

    response.raise_for_status()

    result = response.json()

    ollama_test_response = result.get(
        "response",
        ""
    ).strip()

    print("\nOllama response:")
    print(repr(ollama_test_response))

    if ollama_test_response:
        print("\n" + "=" * 80)
        print("Status: READY")
        print("=" * 80)

    else:
        print("\n⚠️ Ollama returned an empty response.")

except Exception as e:

    print("\n❌ Ollama connection failed.")
    print("Error:", e)

================================================================================
OLLAMA CONFIGURATION
================================================================================
URL: http://localhost:11434/api/generate
Model: qwen2.5:7b

Ollama response:
'READY'

================================================================================
Status: READY
================================================================================

In [6]:
# ============================================================
# INT005 - PROMPT BUILDER
# ============================================================

def build_int005_prompt(row):

    language = str(row["language"]).strip()
    question_type = str(row["question_type"]).strip()
    faq_id = str(row["faq_id"]).strip()

    ground_truth = str(row["ground_truth"]).strip()

    language_rules = {
        "English": "Write the question entirely in English.",
        "Arabic": "Write the question entirely in Arabic.",
        "French": "Write the question entirely in French.",
        "Russian": "Write the question entirely in Russian."
    }

    type_rules = {
        "Direct": (
            "Ask the information directly and clearly."
        ),
        "Paraphrased": (
            "Express the same information using different "
            "natural wording. Do not copy a direct question."
        ),
        "Scenario": (
            "Create a realistic hotel guest situation that "
            "naturally leads to asking about the same information."
        )
    }

    language_rule = language_rules.get(
        language,
        f"Write the question in {language}."
    )

    type_rule = type_rules.get(
        question_type,
        "Create a natural guest question."
    )

    prompt = f"""
You are generating a high-quality FAQ question for a hotel AI dataset.

Hotel name:
Nile Pearl Hotel

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

Ground truth:
{ground_truth}

Instructions:

1. {language_rule}

2. {type_rule}

3. The question must be about the STANDARD CHECK-OUT TIME.

4. The correct information is:
   Standard check-out time is 12:00 PM.

5. Keep the meaning consistent with the ground truth.

6. Mention "Nile Pearl Hotel" naturally when appropriate.

7. Do not invent any hotel policy or time.

8. Do not answer the question.

9. Return ONLY the question.

10. Do not add:
   - explanations
   - labels
   - quotation marks
   - bullet points
   - prefixes such as "Question:"
   - translations into another language

11. For Russian, use Cyrillic only for the Russian language.
12. For Arabic, use Arabic only for the Arabic language.
13. Do not mix Arabic, Russian, French, or English sentences.

Return exactly ONE natural guest question.

Generate now.
"""

    return prompt.strip()


print("=" * 80)
print("INT005 PROMPT BUILDER")
print("=" * 80)

# ------------------------------------------------------------
# Test with first INT005 row
# ------------------------------------------------------------

test_prompt = build_int005_prompt(
    int005_rows.iloc[0]
)

print("FAQ ID:", int005_rows.iloc[0]["faq_id"])
print("Language:", int005_rows.iloc[0]["language"])
print("Type:", int005_rows.iloc[0]["question_type"])

print("\n" + "=" * 80)
print("PROMPT CREATED SUCCESSFULLY")
print("=" * 80)

print(test_prompt)

================================================================================
INT005 PROMPT BUILDER
================================================================================
FAQ ID: FAQ0129
Language: English
Type: Direct

================================================================================
PROMPT CREATED SUCCESSFULLY
================================================================================
You are generating a high-quality FAQ question for a hotel AI dataset.

Hotel name:
Nile Pearl Hotel

FAQ ID:
FAQ0129

Language:
English

Question type:
Direct

Ground truth:
Standard check-out time is 12:00 PM.

Instructions:

1. Write the question entirely in English.

2. Ask the information directly and clearly.

3. The question must be about the STANDARD CHECK-OUT TIME.

4. The correct information is:
   Standard check-out time is 12:00 PM.

5. Keep the meaning consistent with the ground truth.

6. Mention "Nile Pearl Hotel" naturally when appropriate.

7. Do not invent any hotel policy or time.

8. Do not answer the question.

9. Return ONLY the question.

10. Do not add:
   - explanations
   - labels
   - quotation marks
   - bullet points
   - prefixes such as "Question:"
   - translations into another language

11. For Russian, use Cyrillic only for the Russian language.
12. For Arabic, use Arabic only for the Arabic language.
13. Do not mix Arabic, Russian, French, or English sentences.

Return exactly ONE natural guest question.

Generate now.

In [8]:
# ============================================================
# INT005 - VALIDATOR
# ============================================================

# ------------------------------------------------------------
# Language detection helpers
# ------------------------------------------------------------

def has_arabic(text):
    return any(
        '\u0600' <= char <= '\u06FF'
        for char in str(text)
    )


def has_cyrillic(text):
    return any(
        '\u0400' <= char <= '\u04FF'
        for char in str(text)
    )


# ------------------------------------------------------------
# Validator
# ------------------------------------------------------------

def validate_int005_question(
    question,
    language,
    question_type,
    ground_truth
):

    if question is None:
        return False, "Empty question"

    question = str(question).strip()

    # --------------------------------------------------------
    # Empty check
    # --------------------------------------------------------

    if not question:
        return False, "Empty question"

    # --------------------------------------------------------
    # Length check
    # --------------------------------------------------------

    if len(question) < 10:
        return False, "Question too short"

    if len(question) > 300:
        return False, "Question too long"

    # --------------------------------------------------------
    # Question mark check
    # --------------------------------------------------------

    if "?" not in question and "؟" not in question:
        return False, "Not formatted as a question"

    # --------------------------------------------------------
    # Check-out terminology
    # --------------------------------------------------------

    check_out_terms = {

        "English": [
            "check-out",
            "checkout",
            "check out",
            "departure"
        ],

        "Arabic": [
            "تسجيل المغادرة",
            "المغادرة",
            "الخروج"
        ],

        "French": [
            "départ",
            "check-out",
            "checkout",
            "heure de départ"
        ],

        "Russian": [
            "высел",
            "выезд",
            "врем",
            "checkout",
            "check-out"
        ]
    }

    terms = check_out_terms.get(
        language,
        []
    )

    question_lower = question.lower()

    if not any(
        term.lower() in question_lower
        for term in terms
    ):
        return False, "Not related to check-out"

    # --------------------------------------------------------
    # Language mixing
    # --------------------------------------------------------

    if language == "Russian":

        if has_arabic(question):
            return False, (
                "Arabic characters found in Russian question"
            )

    elif language == "Arabic":

        if has_cyrillic(question):
            return False, (
                "Cyrillic characters found in Arabic question"
            )

    elif language == "English":

        if has_arabic(question):
            return False, (
                "Arabic characters found in English question"
            )

        if has_cyrillic(question):
            return False, (
                "Cyrillic characters found in English question"
            )

    elif language == "French":

        if has_arabic(question):
            return False, (
                "Arabic characters found in French question"
            )

        if has_cyrillic(question):
            return False, (
                "Cyrillic characters found in French question"
            )

    # --------------------------------------------------------
    # Final validation
    # --------------------------------------------------------

    return True, "VALID"


# ============================================================
# TEST
# ============================================================

print("=" * 80)
print("INT005 VALIDATOR")
print("=" * 80)

test_question = (
    "What is the standard check-out time at Nile Pearl Hotel?"
)

valid, reason = validate_int005_question(
    question=test_question,
    language="English",
    question_type="Direct",
    ground_truth="Standard check-out time is 12:00 PM."
)

print("Test question:")
print(test_question)

print("\nValidation result:")
print("Valid:", valid)
print("Status:", reason)

print("\n" + "=" * 80)

if valid:
    print("Status: READY")
else:
    print("Status: CHECK VALIDATOR")

print("=" * 80)

================================================================================
INT005 VALIDATOR
================================================================================
Test question:
What is the standard check-out time at Nile Pearl Hotel?

Validation result:
Valid: True
Status: VALID

================================================================================
Status: READY
================================================================================

In [9]:
# ============================================================
# INT005 - REGENERATION FUNCTION
# ============================================================

def regenerate_int005_question(
    row,
    validation_error="",
    previous_question=""
):
    """
    Regenerate one INT005 question using Ollama
    after a validation failure.
    """

    language = str(row["language"]).strip()
    question_type = str(row["question_type"]).strip()
    ground_truth = str(row["ground_truth"]).strip()
    faq_id = str(row["faq_id"]).strip()

    prompt = f"""
You are fixing a hotel FAQ question generation failure.

Hotel:
Nile Pearl Hotel

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

Ground truth:
{ground_truth}

Previous generated question:
{previous_question}

Validation error:
{validation_error}

Generate ONE completely new question.

STRICT RULES:

- Write ONLY in {language}.
- The question must be about the standard check-out time.
- The correct check-out time is 12:00 PM.
- Do not invent another time.
- Do not answer the question.
- Do not include explanations.
- Do not include labels.
- Do not use quotation marks.
- Do not copy the previous question.
- Keep the question natural for a hotel guest.
- Return exactly ONE question.
"""

    try:

        response = requests.post(
            OLLAMA_URL,
            json={
                "model": OLLAMA_MODEL,
                "prompt": prompt.strip(),
                "stream": False,
                "options": {
                    "temperature": 0.7
                }
            },
            timeout=120
        )

        response.raise_for_status()

        result = response.json()

        generated = result.get(
            "response",
            ""
        ).strip()

        return generated

    except Exception as e:

        print(
            f"❌ Regeneration error for {faq_id}: {e}"
        )

        return ""


print("=" * 80)
print("INT005 REGENERATION FUNCTION")
print("=" * 80)

print("Function:", regenerate_int005_question.__name__)
print("Status: READY")

print("=" * 80)

================================================================================
INT005 REGENERATION FUNCTION
================================================================================
Function: regenerate_int005_question
Status: READY
================================================================================

In [10]:
# ============================================================
# INT005 - FULL QUESTION GENERATION
# ============================================================

import time

int005_generated = []

print("=" * 80)
print("INT005 FULL QUESTION GENERATION")
print("=" * 80)

# ------------------------------------------------------------
# Generation loop
# ------------------------------------------------------------

for index, (_, row) in enumerate(
    int005_rows.iterrows(),
    start=1
):

    faq_id = str(row["faq_id"])
    language = str(row["language"])
    question_type = str(row["question_type"])
    ground_truth = str(row["ground_truth"])

    print("\n" + "=" * 80)
    print(
        f"{index}/32 | "
        f"{faq_id} | "
        f"{language} | "
        f"{question_type}"
    )
    print("=" * 80)

    generated_question = ""
    validation_status = "FAILED"
    validation_reason = ""
    attempts = 0

    # --------------------------------------------------------
    # Maximum attempts
    # --------------------------------------------------------

    max_attempts = 4

    for attempt in range(1, max_attempts + 1):

        attempts = attempt

        # ----------------------------------------------------
        # Build prompt
        # ----------------------------------------------------

        prompt = build_int005_prompt(row)

        # If previous attempt failed, add regeneration info
        if generated_question:

            prompt += f"""

Previous generated question:
{generated_question}

Previous validation error:
{validation_reason}

Generate a completely new question.
"""

        # ----------------------------------------------------
        # Call Ollama
        # ----------------------------------------------------

        try:

            response = requests.post(
                OLLAMA_URL,
                json={
                    "model": OLLAMA_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.7
                    }
                },
                timeout=120
            )

            response.raise_for_status()

            result = response.json()

            generated_question = (
                result.get("response", "")
                .strip()
            )

        except Exception as e:

            validation_reason = (
                f"Ollama error: {str(e)}"
            )

            generated_question = ""

            continue

        # ----------------------------------------------------
        # Clean response
        # ----------------------------------------------------

        generated_question = (
            generated_question
            .replace('"', "")
            .replace("“", "")
            .replace("”", "")
            .strip()
        )

        # ----------------------------------------------------
        # Validate
        # ----------------------------------------------------

        is_valid, reason = validate_int005_question(
            question=generated_question,
            language=language,
            question_type=question_type,
            ground_truth=ground_truth
        )

        if is_valid:

            validation_status = "VALID"
            validation_reason = "VALID"

            break

        else:

            validation_status = "FAILED"
            validation_reason = reason

    # --------------------------------------------------------
    # Store result
    # --------------------------------------------------------

    int005_generated.append({

        "faq_id": faq_id,

        "intent_id": "INT005",

        "language": language,

        "question_type": question_type,

        "question": generated_question,

        "ground_truth": ground_truth,

        "status": validation_status,

        "validation_reason": validation_reason,

        "attempts": attempts
    })

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------

    print(
        "GENERATED:",
        generated_question
    )

    print(
        "Status:",
        validation_status,
        "| Attempts:",
        attempts
    )

    if validation_status != "VALID":

        print(
            "Reason:",
            validation_reason
        )

    time.sleep(0.2)


# ============================================================
# SUMMARY
# ============================================================

int005_generated_df = pd.DataFrame(
    int005_generated
)

valid_count = (
    int005_generated_df["status"]
    .eq("VALID")
    .sum()
)

failed_count = (
    int005_generated_df["status"]
    .ne("VALID")
    .sum()
)

non_empty_count = (
    int005_generated_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print("\n" + "=" * 80)
print("INT005 GENERATION SUMMARY")
print("=" * 80)

print("Total:", len(int005_generated_df))
print("Valid:", valid_count)
print("Failed:", failed_count)
print("Non-empty:", non_empty_count)

print("=" * 80)

================================================================================
INT005 FULL QUESTION GENERATION
================================================================================

================================================================================
1/32 | FAQ0129 | English | Direct
================================================================================
GENERATED: What is the standard check-out time at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
2/32 | FAQ0130 | English | Direct
================================================================================
GENERATED: What is the standard check-out time at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
3/32 | FAQ0131 | English | Direct
================================================================================
GENERATED: What is the standard check-out time at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
4/32 | FAQ0132 | English | Paraphrased
================================================================================
GENERATED: At what time should I check out by at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
5/32 | FAQ0133 | English | Paraphrased
================================================================================
GENERATED: When is the usual time to check out at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
6/32 | FAQ0134 | English | Paraphrased
================================================================================
GENERATED: At what time should I check out by if I'm staying at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
7/32 | FAQ0135 | English | Scenario
================================================================================
GENERATED: At what time do I need to check out by if I'm leaving the hotel today?
Status: VALID | Attempts: 1

================================================================================
8/32 | FAQ0136 | English | Scenario
================================================================================
GENERATED: At what time do I need to check out by at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
9/32 | FAQ0137 | Arabic | Direct
================================================================================
GENERATED: متى هو وقت الخروج المعايير في فندق نيل pearl؟
Status: VALID | Attempts: 1

================================================================================
10/32 | FAQ0138 | Arabic | Direct
================================================================================
GENERATED: متى هو وقت الخروج المعياري من فندق النيل الأبيض؟
Status: VALID | Attempts: 1

================================================================================
11/32 | FAQ0139 | Arabic | Direct
================================================================================
GENERATED: متى هو وقت الخروج المعياري من فندق نيل بيرل؟
Status: VALID | Attempts: 1

================================================================================
12/32 | FAQ0140 | Arabic | Paraphrased
================================================================================
GENERATED: فيما يتعلق بفندق نيل بيرل، في أي الوقت يجب على الضيوف الخروج بشكل متوقع؟
Status: VALID | Attempts: 2

================================================================================
13/32 | FAQ0141 | Arabic | Paraphrased
================================================================================
GENERATED: في ماذا الوقت يكون الخروج المعتاد من فندق نيل الياقوت؟
Status: VALID | Attempts: 3

================================================================================
14/32 | FAQ0142 | Arabic | Paraphrased
================================================================================
GENERATED: ما هو وقت الخروج المعتاد من فندق نيل الياقوتة؟
Status: VALID | Attempts: 3

================================================================================
15/32 | FAQ0143 | Arabic | Scenario
================================================================================
GENERATED: أرغب في مغادرة فندق Nile Pearl Hotel في وقت مبكر، فهل يمكنني المغادرة قبل الساعة 12:00 ظهرًا؟
Status: VALID | Attempts: 4

================================================================================
16/32 | FAQ0144 | Arabic | Scenario
================================================================================
GENERATED: هل يمكنني معرفة الوقت المعتاد لفأغادرة الغرفة في نيل الياقة بعد ؟
Status: FAILED | Attempts: 4
Reason: Not related to check-out

================================================================================
17/32 | FAQ0145 | French | Direct
================================================================================
GENERATED: quelle est l'heure standard de départ à l'hôtel Nile Pearl Hotel ?
Status: VALID | Attempts: 1

================================================================================
18/32 | FAQ0146 | French | Direct
================================================================================
GENERATED: Enlightener que l'heure de départ standard est à 12:00 PM au Nile Pearl Hotel ?
Status: VALID | Attempts: 1

================================================================================
19/32 | FAQ0147 | French | Direct
================================================================================
GENERATED: À quelle heure devons-nous sortir avant le départ de l'hôtel Nile Pearl Hotel ?
Status: VALID | Attempts: 3

================================================================================
20/32 | FAQ0148 | French | Paraphrased
================================================================================
GENERATED: في أي الوقت أحتاج إلى مغادرة غرفتي فيôtel Nile Pearl Hotel بشكل准时退出尼罗珍珠酒店的房间？
Status: FAILED | Attempts: 4
Reason: Not formatted as a question

================================================================================
21/32 | FAQ0149 | French | Paraphrased
================================================================================
GENERATED: هل يمكنني معرفة وقت الخروج المعتاد من فندق نيل الياقة؟
Status: FAILED | Attempts: 4
Reason: Not related to check-out

================================================================================
22/32 | FAQ0150 | French | Paraphrased
================================================================================
GENERATED: ما هو وقت الخروج المعتاد من فندق نيل الياصمة؟
Status: FAILED | Attempts: 4
Reason: Not related to check-out

================================================================================
23/32 | FAQ0151 | French | Scenario
================================================================================
GENERATED: si je pars du Nile Pearl Hotel avant 12 heures du midi, dois-je informer l'hôtel ?
Status: FAILED | Attempts: 4
Reason: Not related to check-out

================================================================================
24/32 | FAQ0152 | French | Scenario
================================================================================
GENERATED: عند partir du Nile Pearl Hotel, à quelle heure devons-nous quitter notre chambre ?
Status: FAILED | Attempts: 4
Reason: Not related to check-out

================================================================================
25/32 | FAQ0153 | Russian | Direct
================================================================================
GENERATED: В какое время стандартно необходимо выселиться из отеля Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
26/32 | FAQ0154 | Russian | Direct
================================================================================
GENERATED: В какое время-standard check-out-выход из номера в Нильском Бриллиантовом отеле?
Status: VALID | Attempts: 3

================================================================================
27/32 | FAQ0155 | Russian | Direct
================================================================================
GENERATED: Когда нужно выселиться из отеля Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
28/32 | FAQ0156 | Russian | Paraphrased
================================================================================
GENERATED: Когда необходимо выселиться из отеля Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
29/32 | FAQ0157 | Russian | Paraphrased
================================================================================
GENERATED: В какое время требуется выселение из Нилаowej башни до полудня?
Status: VALID | Attempts: 1

================================================================================
30/32 | FAQ0158 | Russian | Paraphrased
================================================================================
GENERATED: в какое время следует выйти из отеля Ниловая жемчужина?
Status: VALID | Attempts: 1

================================================================================
31/32 | FAQ0159 | Russian | Scenario
================================================================================
GENERATED: В какое время обычно необходимо выселиться из отеля Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
32/32 | FAQ0160 | Russian | Scenario
================================================================================
GENERATED: В какое время стандартно происходит выезд из Нильского Бриллиантового отеля?
Status: VALID | Attempts: 1

================================================================================
INT005 GENERATION SUMMARY
================================================================================
Total: 32
Valid: 26
Failed: 6
Non-empty: 32
================================================================================

In [11]:
# ============================================================
# INT005 - FAILED QUESTION REGENERATION
# ============================================================

failed_rows = int005_generated_df[
    int005_generated_df["status"] != "VALID"
].copy()

print("=" * 80)
print("INT005 FAILED QUESTION REGENERATION")
print("=" * 80)

print("Failed questions:", len(failed_rows))
print("FAQ IDs:", failed_rows["faq_id"].tolist())

# ------------------------------------------------------------
# Regenerate failed questions
# ------------------------------------------------------------

for idx, row in failed_rows.iterrows():

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    print("\n" + "=" * 80)
    print("FAQ:", faq_id)
    print("Language:", language)
    print("Type:", question_type)
    print("Old question:", row["question"])

    regenerated_question = ""

    max_attempts = 5

    for attempt in range(1, max_attempts + 1):

        regenerated_question = regenerate_int005_question(
            row=row,
            validation_error=row["validation_reason"],
            previous_question=regenerated_question
        )

        regenerated_question = (
            regenerated_question
            .replace('"', "")
            .replace("“", "")
            .replace("”", "")
            .strip()
        )

        is_valid, reason = validate_int005_question(
            question=regenerated_question,
            language=language,
            question_type=question_type,
            ground_truth=row["ground_truth"]
        )

        if is_valid:

            print("FIXED:", regenerated_question)
            print("Status: VALID")
            print("Attempts:", attempt)

            int005_generated_df.loc[
                idx,
                "question"
            ] = regenerated_question

            int005_generated_df.loc[
                idx,
                "status"
            ] = "VALID"

            int005_generated_df.loc[
                idx,
                "validation_reason"
            ] = "VALID"

            int005_generated_df.loc[
                idx,
                "attempts"
            ] = row["attempts"] + attempt

            break

        else:

            print(
                f"Attempt {attempt} FAILED:",
                reason
            )

            if attempt == max_attempts:

                print(
                    "❌ FAILED TO REGENERATE"
                )

                int005_generated_df.loc[
                    idx,
                    "question"
                ] = regenerated_question

                int005_generated_df.loc[
                    idx,
                    "validation_reason"
                ] = reason

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

remaining_failed = int005_generated_df[
    int005_generated_df["status"] != "VALID"
]

print("\n" + "=" * 80)
print("INT005 REGENERATION SUMMARY")
print("=" * 80)

print(
    "Total:",
    len(int005_generated_df)
)

print(
    "Valid:",
    int005_generated_df["status"].eq("VALID").sum()
)

print(
    "Failed:",
    len(remaining_failed)
)

if len(remaining_failed) > 0:

    print(
        "\nRemaining failed FAQ IDs:",
        remaining_failed["faq_id"].tolist()
    )

else:

    print("\n✅ ALL INT005 QUESTIONS ARE VALID")

print("=" * 80)

================================================================================
INT005 FAILED QUESTION REGENERATION
================================================================================
Failed questions: 6
FAQ IDs: ['FAQ0144', 'FAQ0148', 'FAQ0149', 'FAQ0150', 'FAQ0151', 'FAQ0152']

================================================================================
FAQ: FAQ0144
Language: Arabic
Type: Scenario
Old question: هل يمكنني معرفة الوقت المعتاد لفأغادرة الغرفة في نيل الياقة بعد ؟
FIXED: متى يكون وقت الخروج المعتاد من الفندق؟
Status: VALID
Attempts: 1

================================================================================
FAQ: FAQ0148
Language: French
Type: Paraphrased
Old question: في أي الوقت أحتاج إلى مغادرة غرفتي فيôtel Nile Pearl Hotel بشكل准时退出尼罗珍珠酒店的房间？
Attempt 1 FAILED: Not related to check-out
Attempt 2 FAILED: Not related to check-out
Attempt 3 FAILED: Not related to check-out
Attempt 4 FAILED: Not related to check-out
Attempt 5 FAILED: Not related to check-out
❌ FAILED TO REGENERATE

================================================================================
FAQ: FAQ0149
Language: French
Type: Paraphrased
Old question: هل يمكنني معرفة وقت الخروج المعتاد من فندق نيل الياقة؟
FIXED: Quelle est l'heure de départ standard ?
Status: VALID
Attempts: 1

================================================================================
FAQ: FAQ0150
Language: French
Type: Paraphrased
Old question: ما هو وقت الخروج المعتاد من فندق نيل الياصمة؟
Attempt 1 FAILED: Not related to check-out
Attempt 2 FAILED: Not related to check-out
Attempt 3 FAILED: Not related to check-out
Attempt 4 FAILED: Not related to check-out
Attempt 5 FAILED: Not related to check-out
❌ FAILED TO REGENERATE

================================================================================
FAQ: FAQ0151
Language: French
Type: Scenario
Old question: si je pars du Nile Pearl Hotel avant 12 heures du midi, dois-je informer l'hôtel ?
FIXED: Quelle est l'heure de départ standard ?
Status: VALID
Attempts: 1

================================================================================
FAQ: FAQ0152
Language: French
Type: Scenario
Old question: عند partir du Nile Pearl Hotel, à quelle heure devons-nous quitter notre chambre ?
Attempt 1 FAILED: Not formatted as a question
Attempt 2 FAILED: Not related to check-out
Attempt 3 FAILED: Not related to check-out
Attempt 4 FAILED: Not related to check-out
FIXED: À quelle heure dois-je m'enregistrer pour le départ à 12:00 PM ?
Status: VALID
Attempts: 5

================================================================================
INT005 REGENERATION SUMMARY
================================================================================
Total: 32
Valid: 30
Failed: 2

Remaining failed FAQ IDs: ['FAQ0148', 'FAQ0150']
================================================================================

In [12]:
# ============================================================
# INT005 - MANUAL FIX FOR REMAINING FAILED QUESTIONS
# ============================================================

print("=" * 80)
print("INT005 MANUAL LANGUAGE FIX")
print("=" * 80)

# ------------------------------------------------------------
# FAQ0148
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0148",
    "question"
] = "À quelle heure est-il habituellement nécessaire de quitter la chambre au Nile Pearl Hotel ?"

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0148",
    "status"
] = "VALID"

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0148",
    "validation_reason"
] = "VALID"

# ------------------------------------------------------------
# FAQ0150
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0150",
    "question"
] = "À quelle heure faut-il généralement quitter le Nile Pearl Hotel ?"

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0150",
    "status"
] = "VALID"

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0150",
    "validation_reason"
] = "VALID"

# ------------------------------------------------------------
# Display fixed questions
# ------------------------------------------------------------

fixed_ids = [
    "FAQ0148",
    "FAQ0150"
]

print("\nFixed questions:")

display(
    int005_generated_df[
        int005_generated_df["faq_id"].isin(fixed_ids)
    ][
        [
            "faq_id",
            "language",
            "question_type",
            "question",
            "status"
        ]
    ]
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

remaining_failed = int005_generated_df[
    int005_generated_df["status"] != "VALID"
]

print("\n" + "=" * 80)
print("INT005 MANUAL FIX SUMMARY")
print("=" * 80)

print("Total:", len(int005_generated_df))
print(
    "Valid:",
    int005_generated_df["status"].eq("VALID").sum()
)
print("Failed:", len(remaining_failed))

if len(remaining_failed) == 0:
    print("\n✅ ALL 32 INT005 QUESTIONS ARE VALID")
else:
    print(
        "\n⚠️ Remaining failed:",
        remaining_failed["faq_id"].tolist()
    )

print("=" * 80)

================================================================================
INT005 MANUAL LANGUAGE FIX
================================================================================

Fixed questions:

,faq_id,language,question_type,question,status
19,FAQ0148,French,Paraphrased,À quelle heure est-il habituellement nécessair...,VALID
21,FAQ0150,French,Paraphrased,À quelle heure faut-il généralement quitter le...,VALID

================================================================================
INT005 MANUAL FIX SUMMARY
================================================================================
Total: 32
Valid: 32
Failed: 0

✅ ALL 32 INT005 QUESTIONS ARE VALID
================================================================================

In [13]:
# ============================================================
# INT005 - FINAL LANGUAGE QUALITY CHECK
# ============================================================

language_issues = []

for _, row in int005_generated_df.iterrows():

    question = str(row["question"])
    language = row["language"]

    # --------------------------------------------------------
    # Arabic
    # --------------------------------------------------------

    if language == "Arabic":

        if has_cyrillic(question):

            language_issues.append({
                "faq_id": row["faq_id"],
                "language": language,
                "issue": "Cyrillic characters found in Arabic question",
                "question": question
            })

    # --------------------------------------------------------
    # Russian
    # --------------------------------------------------------

    elif language == "Russian":

        if has_arabic(question):

            language_issues.append({
                "faq_id": row["faq_id"],
                "language": language,
                "issue": "Arabic characters found in Russian question",
                "question": question
            })

    # --------------------------------------------------------
    # English
    # --------------------------------------------------------

    elif language == "English":

        if has_arabic(question) or has_cyrillic(question):

            language_issues.append({
                "faq_id": row["faq_id"],
                "language": language,
                "issue": "Non-English characters found in English question",
                "question": question
            })

    # --------------------------------------------------------
    # French
    # --------------------------------------------------------

    elif language == "French":

        if has_arabic(question) or has_cyrillic(question):

            language_issues.append({
                "faq_id": row["faq_id"],
                "language": language,
                "issue": "Non-French characters found in French question",
                "question": question
            })


# ============================================================
# RESULTS
# ============================================================

print("=" * 80)
print("INT005 FINAL LANGUAGE QUALITY CHECK")
print("=" * 80)

print(
    "Total questions:",
    len(int005_generated_df)
)

print(
    "Language issues:",
    len(language_issues)
)

if language_issues:

    print("\n⚠️ LANGUAGE ISSUES FOUND")

    display(
        pd.DataFrame(language_issues)
    )

else:

    print("✅ NO LANGUAGE MIXING FOUND")

print("=" * 80)

================================================================================
INT005 FINAL LANGUAGE QUALITY CHECK
================================================================================
Total questions: 32
Language issues: 0
✅ NO LANGUAGE MIXING FOUND
================================================================================

In [17]:
# ============================================================
# INT005 - FINAL DUPLICATE CHECK
# ============================================================

from difflib import SequenceMatcher

def similarity(text1, text2):
    """
    Calculate similarity between two questions.
    Returns a value between 0 and 1.
    """
    return SequenceMatcher(
        None,
        str(text1).lower().strip(),
        str(text2).lower().strip()
    ).ratio()


duplicate_pairs = []

questions = (
    int005_generated_df["question"]
    .fillna("")
    .astype(str)
    .tolist()
)

faq_ids = (
    int005_generated_df["faq_id"]
    .tolist()
)

languages = (
    int005_generated_df["language"]
    .tolist()
)

question_types = (
    int005_generated_df["question_type"]
    .tolist()
)


# ------------------------------------------------------------
# Compare every pair
# ------------------------------------------------------------

for i in range(len(questions)):

    for j in range(i + 1, len(questions)):

        q1 = questions[i]
        q2 = questions[j]

        similarity_score = similarity(
            q1,
            q2
        )

        if similarity_score >= 0.85:

            duplicate_pairs.append({

                "faq_1": faq_ids[i],

                "faq_2": faq_ids[j],

                "language": languages[i],

                "question_type_1": question_types[i],

                "question_type_2": question_types[j],

                "similarity": round(
                    similarity_score,
                    3
                ),

                "question_1": q1,

                "question_2": q2
            })


# ============================================================
# RESULTS
# ============================================================

print("=" * 80)
print("INT005 FINAL DUPLICATE CHECK")
print("=" * 80)

print(
    "Total questions:",
    len(int005_generated_df)
)

print(
    "Potential duplicates:",
    len(duplicate_pairs)
)

if duplicate_pairs:

    print("\n⚠️ POTENTIAL DUPLICATES FOUND")

    duplicate_df = pd.DataFrame(
        duplicate_pairs
    )

    display(duplicate_df)

else:

    print(
        "✅ NO POTENTIAL DUPLICATES FOUND"
    )

print("=" * 80)

================================================================================
INT005 FINAL DUPLICATE CHECK
================================================================================
Total questions: 32
Potential duplicates: 9

⚠️ POTENTIAL DUPLICATES FOUND

,faq_1,faq_2,language,question_type_1,question_type_2,similarity,question_1,question_2
0,FAQ0129,FAQ0130,English,Direct,Direct,1.000,What is the standard check-out time at Nile Pe...,What is the standard check-out time at Nile Pe...
1,FAQ0129,FAQ0131,English,Direct,Direct,1.000,What is the standard check-out time at Nile Pe...,What is the standard check-out time at Nile Pe...
2,FAQ0130,FAQ0131,English,Direct,Direct,1.000,What is the standard check-out time at Nile Pe...,What is the standard check-out time at Nile Pe...
3,FAQ0132,FAQ0134,English,Paraphrased,Paraphrased,0.880,At what time should I check out by at Nile Pea...,At what time should I check out by if I'm stay...
4,FAQ0132,FAQ0136,English,Paraphrased,Scenario,0.877,At what time should I check out by at Nile Pea...,At what time do I need to check out by at Nile...
5,FAQ0138,FAQ0139,Arabic,Direct,Direct,0.913,متى هو وقت الخروج المعياري من فندق النيل الأبيض؟,متى هو وقت الخروج المعياري من فندق نيل بيرل؟
6,FAQ0149,FAQ0151,French,Paraphrased,Scenario,1.000,Quelle est l'heure de départ standard ?,Quelle est l'heure de départ standard ?
7,FAQ0153,FAQ0159,Russian,Direct,Scenario,0.915,В какое время стандартно необходимо выселиться...,В какое время обычно необходимо выселиться из ...
8,FAQ0155,FAQ0156,Russian,Direct,Paraphrased,0.893,Когда нужно выселиться из отеля Nile Pearl Hotel?,Когда необходимо выселиться из отеля Nile Pear...

================================================================================

In [18]:
# ============================================================
# INT005 - DUPLICATE FIX
# ============================================================

print("=" * 80)
print("INT005 DUPLICATE FIX")
print("=" * 80)

# ------------------------------------------------------------
# English Direct
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0130",
    "question"
] = "When does the standard check-out time begin at Nile Pearl Hotel?"

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0131",
    "question"
] = "What time are guests expected to check out of Nile Pearl Hotel?"

# ------------------------------------------------------------
# English Paraphrased
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0134",
    "question"
] = "When is the usual departure time for guests staying at Nile Pearl Hotel?"

# ------------------------------------------------------------
# English Scenario
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0136",
    "question"
] = "If I am leaving Nile Pearl Hotel today, when should I check out?"

# ------------------------------------------------------------
# Arabic Direct
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0138",
    "question"
] = "متى يجب على النزلاء مغادرة الغرف في فندق Nile Pearl Hotel؟"

# ------------------------------------------------------------
# French Scenario
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0151",
    "question"
] = "Si je prévois de quitter le Nile Pearl Hotel, à quelle heure dois-je libérer ma chambre ?"

# ------------------------------------------------------------
# Russian Scenario
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0159",
    "question"
] = "Если я планирую выехать из Nile Pearl Hotel, в какое время мне нужно освободить номер?"

# ------------------------------------------------------------
# Russian Paraphrased
# ------------------------------------------------------------

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0156",
    "question"
] = "В какое время обычно заканчивается проживание в Nile Pearl Hotel?"

# ============================================================
# DISPLAY UPDATED QUESTIONS
# ============================================================

fixed_ids = [
    "FAQ0130",
    "FAQ0131",
    "FAQ0134",
    "FAQ0136",
    "FAQ0138",
    "FAQ0151",
    "FAQ0156",
    "FAQ0159"
]

display(
    int005_generated_df[
        int005_generated_df["faq_id"].isin(fixed_ids)
    ][
        [
            "faq_id",
            "language",
            "question_type",
            "question"
        ]
    ]
)

print("\n" + "=" * 80)
print("INT005 DUPLICATE FIX COMPLETE")
print("=" * 80)

================================================================================
INT005 DUPLICATE FIX
================================================================================

,faq_id,language,question_type,question
1,FAQ0130,English,Direct,When does the standard check-out time begin at...
2,FAQ0131,English,Direct,What time are guests expected to check out of ...
5,FAQ0134,English,Paraphrased,When is the usual departure time for guests st...
7,FAQ0136,English,Scenario,"If I am leaving Nile Pearl Hotel today, when s..."
9,FAQ0138,Arabic,Direct,متى يجب على النزلاء مغادرة الغرف في فندق Nile ...
22,FAQ0151,French,Scenario,"Si je prévois de quitter le Nile Pearl Hotel, ..."
27,FAQ0156,Russian,Paraphrased,В какое время обычно заканчивается проживание ...
30,FAQ0159,Russian,Scenario,"Если я планирую выехать из Nile Pearl Hotel, в..."

================================================================================
INT005 DUPLICATE FIX COMPLETE
================================================================================

In [19]:
# ============================================================
# INT005 - FINAL DUPLICATE RECHECK
# ============================================================

duplicate_pairs = []

questions = (
    int005_generated_df["question"]
    .fillna("")
    .astype(str)
    .tolist()
)

faq_ids = (
    int005_generated_df["faq_id"]
    .tolist()
)

languages = (
    int005_generated_df["language"]
    .tolist()
)

question_types = (
    int005_generated_df["question_type"]
    .tolist()
)


# ------------------------------------------------------------
# Compare all question pairs
# ------------------------------------------------------------

for i in range(len(questions)):

    for j in range(i + 1, len(questions)):

        score = similarity(
            questions[i],
            questions[j]
        )

        if score >= 0.85:

            duplicate_pairs.append({

                "faq_1": faq_ids[i],

                "faq_2": faq_ids[j],

                "language": languages[i],

                "question_type_1": question_types[i],

                "question_type_2": question_types[j],

                "similarity": round(
                    score,
                    3
                ),

                "question_1": questions[i],

                "question_2": questions[j]
            })


# ============================================================
# RESULTS
# ============================================================

print("=" * 80)
print("INT005 FINAL DUPLICATE RECHECK")
print("=" * 80)

print(
    "Total questions:",
    len(int005_generated_df)
)

print(
    "Potential duplicates:",
    len(duplicate_pairs)
)

if duplicate_pairs:

    print(
        "\n⚠️ POTENTIAL DUPLICATES FOUND"
    )

    duplicate_df = pd.DataFrame(
        duplicate_pairs
    )

    display(duplicate_df)

else:

    print(
        "✅ NO POTENTIAL DUPLICATES FOUND"
    )

print("=" * 80)

================================================================================
INT005 FINAL DUPLICATE RECHECK
================================================================================
Total questions: 32
Potential duplicates: 1

⚠️ POTENTIAL DUPLICATES FOUND

,faq_1,faq_2,language,question_type_1,question_type_2,similarity,question_1,question_2
0,FAQ0129,FAQ0130,English,Direct,Direct,0.883,What is the standard check-out time at Nile Pe...,When does the standard check-out time begin at...

================================================================================

In [21]:
# ============================================================
# INT005 - FINAL DUPLICATE RECHECK
# ============================================================

duplicate_pairs = []

questions = (
    int005_generated_df["question"]
    .fillna("")
    .astype(str)
    .tolist()
)

faq_ids = (
    int005_generated_df["faq_id"]
    .tolist()
)

languages = (
    int005_generated_df["language"]
    .tolist()
)

question_types = (
    int005_generated_df["question_type"]
    .tolist()
)


# ------------------------------------------------------------
# Compare all question pairs
# ------------------------------------------------------------

for i in range(len(questions)):

    for j in range(i + 1, len(questions)):

        score = similarity(
            questions[i],
            questions[j]
        )

        if score >= 0.85:

            duplicate_pairs.append({

                "faq_1": faq_ids[i],

                "faq_2": faq_ids[j],

                "language": languages[i],

                "question_type_1": question_types[i],

                "question_type_2": question_types[j],

                "similarity": round(
                    score,
                    3
                ),

                "question_1": questions[i],

                "question_2": questions[j]
            })


# ============================================================
# RESULTS
# ============================================================

print("=" * 80)
print("INT005 FINAL DUPLICATE RECHECK")
print("=" * 80)

print(
    "Total questions:",
    len(int005_generated_df)
)

print(
    "Potential duplicates:",
    len(duplicate_pairs)
)

if duplicate_pairs:

    print(
        "\n⚠️ POTENTIAL DUPLICATES FOUND"
    )

    duplicate_df = pd.DataFrame(
        duplicate_pairs
    )

    display(duplicate_df)

else:

    print(
        "✅ NO POTENTIAL DUPLICATES FOUND"
    )

print("=" * 80)

================================================================================
INT005 FINAL DUPLICATE RECHECK
================================================================================
Total questions: 32
Potential duplicates: 0
✅ NO POTENTIAL DUPLICATES FOUND
================================================================================

In [20]:
# ============================================================
# INT005 - FINAL DUPLICATE FIX
# ============================================================

int005_generated_df.loc[
    int005_generated_df["faq_id"] == "FAQ0130",
    "question"
] = "By what time should guests vacate their rooms at Nile Pearl Hotel?"

print("=" * 80)
print("FAQ0130 FIXED")
print("=" * 80)

print(
    int005_generated_df.loc[
        int005_generated_df["faq_id"] == "FAQ0130",
        ["faq_id", "language", "question_type", "question"]
    ].to_string(index=False)
)

================================================================================
FAQ0130 FIXED
================================================================================
 faq_id language question_type                                                           question
FAQ0130  English        Direct By what time should guests vacate their rooms at Nile Pearl Hotel?

In [22]:
# ============================================================
# INT006 - CLEAN START
# ============================================================

INTENT_ID = "INT006"

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print("=" * 80)
print("INT006 CLEAN START")
print("=" * 80)

print("Current directory:")
print(os.getcwd())

print("\nShape:", int006_df.shape)

print("\nLanguages:")
print(int006_df["language"].value_counts())

print("\nQuestion types:")
print(int006_df["question_type"].value_counts())

print("\nFAQ IDs:")
print(int006_df["faq_id"].tolist())

print("\n" + "=" * 80)
print("✅ INT006 CLEAN START READY")
print("=" * 80)

NameError: name 'faq_generation_plan' is not defined

In [24]:
# ============================================================
# LOAD FAQ GENERATION PLAN
# ============================================================

import pandas as pd
import os

PLAN_PATH = os.path.join(
    "03_Structured_Data",
    "CSV",
    "faq_generation_plan.csv"
)

print("=" * 80)
print("LOADING FAQ GENERATION PLAN")
print("=" * 80)

print("Path:", PLAN_PATH)
print("Exists:", os.path.exists(PLAN_PATH))

if not os.path.exists(PLAN_PATH):
    raise FileNotFoundError(
        f"Generation plan not found: {PLAN_PATH}"
    )

faq_generation_plan = pd.read_csv(PLAN_PATH)

print("\nLoaded successfully!")
print("Shape:", faq_generation_plan.shape)

print("\nColumns:")
print(faq_generation_plan.columns.tolist())

print("\nIntent count:")
print(faq_generation_plan["intent_id"].nunique())

print("=" * 80)

================================================================================
LOADING FAQ GENERATION PLAN
================================================================================
Path: 03_Structured_Data\CSV\faq_generation_plan.csv
Exists: True

Loaded successfully!
Shape: (1344, 11)

Columns:
['faq_id', 'intent_id', 'intent_name', 'category', 'language', 'question_type', 'difficulty', 'question', 'answer', 'ground_truth', 'source']

Intent count:
42
================================================================================

In [25]:
# ============================================================
# INT006 - CLEAN START
# ============================================================

INTENT_ID = "INT006"

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print("=" * 80)
print("INT006 CLEAN START")
print("=" * 80)

print("Rows:", len(int006_df))
print("Intent IDs:", int006_df["intent_id"].unique())
print("\nLanguages:")
print(int006_df["language"].value_counts())

print("\nQuestion types:")
print(int006_df["question_type"].value_counts())

print("\nFAQ IDs:")
print(int006_df["faq_id"].tolist())

print("\n" + "=" * 80)
print("INT006 CLEAN START READY")
print("=" * 80)

================================================================================
INT006 CLEAN START
================================================================================
Rows: 32
Intent IDs: ['INT006']

Languages:
language
English    8
Arabic     8
French     8
Russian    8
Name: count, dtype: int64

Question types:
question_type
Direct         12
Paraphrased    12
Scenario        8
Name: count, dtype: int64

FAQ IDs:
['FAQ0161', 'FAQ0162', 'FAQ0163', 'FAQ0164', 'FAQ0165', 'FAQ0166', 'FAQ0167', 'FAQ0168', 'FAQ0169', 'FAQ0170', 'FAQ0171', 'FAQ0172', 'FAQ0173', 'FAQ0174', 'FAQ0175', 'FAQ0176', 'FAQ0177', 'FAQ0178', 'FAQ0179', 'FAQ0180', 'FAQ0181', 'FAQ0182', 'FAQ0183', 'FAQ0184', 'FAQ0185', 'FAQ0186', 'FAQ0187', 'FAQ0188', 'FAQ0189', 'FAQ0190', 'FAQ0191', 'FAQ0192']

================================================================================
INT006 CLEAN START READY
================================================================================

In [26]:
# ============================================================
# INT006 - PREPARATION
# ============================================================

INTENT_ID = "INT006"

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print("=" * 80)
print("INT006 PREPARATION")
print("=" * 80)

required_columns = [
    "faq_id",
    "intent_id",
    "intent_name",
    "category",
    "language",
    "question_type",
    "difficulty",
    "question",
    "answer",
    "ground_truth",
    "source"
]

missing_columns = [
    col for col in required_columns
    if col not in int006_df.columns
]

print("Required columns:", "OK" if not missing_columns else missing_columns)

print("\nPossible ground-truth columns:")

for col in ["answer", "ground_truth"]:
    if col in int006_df.columns:
        print(f"\n{col}:")
        print(
            int006_df[col]
            .dropna()
            .astype(str)
            .loc[lambda x: x.str.strip() != ""]
            .unique()
        )

print("\nQuestion column:")

if "question" in int006_df.columns:
    print("FOUND")
    print(
        "Non-empty questions:",
        int006_df["question"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )
else:
    print("NOT FOUND")

print("\nIntent IDs:")
print(int006_df["intent_id"].unique())

print("\nGround Truth:")
print(
    int006_df["ground_truth"]
    .dropna()
    .astype(str)
    .unique()
)

print("\n" + "=" * 80)
print("INT006 PREPARATION SUMMARY")
print("=" * 80)

print("Rows:", len(int006_df))
print("Unique FAQ IDs:", int006_df["faq_id"].nunique())
print("Languages:", int006_df["language"].nunique())
print("Question types:", int006_df["question_type"].nunique())

print("=" * 80)
print("✅ INT006 PREPARATION COMPLETE")
print("=" * 80)

================================================================================
INT006 PREPARATION
================================================================================
Required columns: OK

Possible ground-truth columns:

answer:
[]

ground_truth:
['Early check-in is subject to room availability and hotel approval.']

Question column:
FOUND
Non-empty questions: 0

Intent IDs:
['INT006']

Ground Truth:
['Early check-in is subject to room availability and hotel approval.']

================================================================================
INT006 PREPARATION SUMMARY
================================================================================
Rows: 32
Unique FAQ IDs: 32
Languages: 4
Question types: 3
================================================================================
✅ INT006 PREPARATION COMPLETE
================================================================================

In [27]:
# ============================================================
# INT006 - SIMILARITY FUNCTION
# ============================================================

from difflib import SequenceMatcher


def similarity(a, b):
    """
    Calculate similarity between two strings.
    Returns a value between 0 and 1.
    """
    a = str(a).lower().strip()
    b = str(b).lower().strip()

    return SequenceMatcher(None, a, b).ratio()


# ============================================================
# TEST
# ============================================================

test_a = "Can I check in early?"
test_b = "Is early check-in available?"

score = similarity(test_a, test_b)

print("=" * 80)
print("INT006 SIMILARITY FUNCTION")
print("=" * 80)

print("Test similarity:", round(score, 3))

print("\n================================================================================")
print("Status: READY")
print("================================================================================")

================================================================================
INT006 SIMILARITY FUNCTION
================================================================================
Test similarity: 0.49

================================================================================
Status: READY
================================================================================

In [28]:
# ============================================================
# INT006 - OLLAMA CONFIGURATION
# ============================================================

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:7b"


def test_ollama():
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": "Reply with exactly: READY",
        "stream": False
    }

    response = requests.post(
        OLLAMA_URL,
        json=payload,
        timeout=120
    )

    response.raise_for_status()

    data = response.json()

    return data.get("response", "").strip()


print("=" * 80)
print("INT006 OLLAMA CONFIGURATION")
print("=" * 80)

print("URL:", OLLAMA_URL)
print("Model:", OLLAMA_MODEL)

try:
    ollama_response = test_ollama()

    print("\nOllama response:")
    print(repr(ollama_response))

    print("\n" + "=" * 80)
    print("Status: READY")
    print("=" * 80)

except Exception as e:

    print("\n❌ Ollama connection failed")
    print("Error:", e)

================================================================================
INT006 OLLAMA CONFIGURATION
================================================================================
URL: http://localhost:11434/api/generate
Model: qwen2.5:7b

Ollama response:
'READY'

================================================================================
Status: READY
================================================================================

In [29]:
# ============================================================
# INT006 - PROMPT BUILDER
# ============================================================

def build_int006_prompt(
    faq_id,
    language,
    question_type,
    ground_truth
):
    
    language_rules = {
        "English": """
Write the question entirely in English.
Do not use Arabic, Russian, French, or other non-English sentences.
""",

        "Arabic": """
Write the question entirely in Arabic.
Use Arabic script for the question.
Do not write the question in English, French, or Russian.
The hotel name "Nile Pearl Hotel" may remain in English if needed.
""",

        "French": """
Write the question entirely in French.
Do not use Arabic, Russian, or English sentences.
The hotel name "Nile Pearl Hotel" may remain in English if needed.
""",

        "Russian": """
Write the question entirely in Russian.
Use Cyrillic script for the Russian sentence.
Do not use Arabic, French, or English sentences.
The hotel name "Nile Pearl Hotel" may remain in English if needed.
"""
    }

    question_type_rules = {
        "Direct": """
Ask directly and clearly about EARLY CHECK-IN.
The question should be short and factual.
""",

        "Paraphrased": """
Ask about EARLY CHECK-IN using different natural wording.
Do not simply copy a standard direct question.
Keep exactly the same meaning.
""",

        "Scenario": """
Create a realistic hotel guest situation involving EARLY CHECK-IN,
then ask a question about whether early check-in is possible.
Do not introduce any new hotel policy.
"""
    }

    prompt = f"""
You are generating a high-quality FAQ question for a multilingual hotel AI dataset.

Hotel name:
Nile Pearl Hotel

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

Ground truth:
{ground_truth}

CORE INTENT:
early_check_in

The question MUST be about EARLY CHECK-IN.

The hotel policy states:
Early check-in is subject to room availability and hotel approval.

IMPORTANT:
- Ask about early check-in only.
- Do not ask about standard check-in time.
- Do not ask about late check-out.
- Do not ask about room availability in general.
- Do not ask about hotel approval in general.
- Do not invent a specific early check-in time.
- Do not invent additional fees.
- Do not invent guaranteed availability.
- Do not answer the question.
- Return exactly ONE question.
- Do not include explanations.
- Do not include labels.
- Do not include quotation marks.
- Do not include bullet points.
- Do not include "Question:".
- Do not mix languages.

LANGUAGE RULE:
{language_rules[language]}

QUESTION TYPE RULE:
{question_type_rules[question_type]}

Return ONLY the question.

Generate now.
"""

    return prompt.strip()


# ============================================================
# TEST PROMPT
# ============================================================

test_row = int006_df.iloc[0]

test_prompt = build_int006_prompt(
    faq_id=test_row["faq_id"],
    language=test_row["language"],
    question_type=test_row["question_type"],
    ground_truth=test_row["ground_truth"]
)

print("=" * 80)
print("INT006 PROMPT BUILDER")
print("=" * 80)

print("FAQ ID:", test_row["faq_id"])
print("Language:", test_row["language"])
print("Type:", test_row["question_type"])

print("\n" + "=" * 80)
print("PROMPT CREATED SUCCESSFULLY")
print("=" * 80)

print(test_prompt)

================================================================================
INT006 PROMPT BUILDER
================================================================================
FAQ ID: FAQ0161
Language: English
Type: Direct

================================================================================
PROMPT CREATED SUCCESSFULLY
================================================================================
You are generating a high-quality FAQ question for a multilingual hotel AI dataset.

Hotel name:
Nile Pearl Hotel

FAQ ID:
FAQ0161

Language:
English

Question type:
Direct

Ground truth:
Early check-in is subject to room availability and hotel approval.

CORE INTENT:
early_check_in

The question MUST be about EARLY CHECK-IN.

The hotel policy states:
Early check-in is subject to room availability and hotel approval.

IMPORTANT:
- Ask about early check-in only.
- Do not ask about standard check-in time.
- Do not ask about late check-out.
- Do not ask about room availability in general.
- Do not ask about hotel approval in general.
- Do not invent a specific early check-in time.
- Do not invent additional fees.
- Do not invent guaranteed availability.
- Do not answer the question.
- Return exactly ONE question.
- Do not include explanations.
- Do not include labels.
- Do not include quotation marks.
- Do not include bullet points.
- Do not include "Question:".
- Do not mix languages.

LANGUAGE RULE:

Write the question entirely in English.
Do not use Arabic, Russian, French, or other non-English sentences.


QUESTION TYPE RULE:

Ask directly and clearly about EARLY CHECK-IN.
The question should be short and factual.


Return ONLY the question.

Generate now.

In [30]:
# ============================================================
# INT006 - VALIDATOR
# ============================================================

import re


# ============================================================
# LANGUAGE DETECTION HELPERS
# ============================================================

def has_arabic(text):
    return bool(re.search(r"[\u0600-\u06FF]", str(text)))


def has_cyrillic(text):
    return bool(re.search(r"[\u0400-\u04FF]", str(text)))


def has_latin(text):
    return bool(re.search(r"[A-Za-z]", str(text)))


# ============================================================
# INTENT KEYWORDS
# ============================================================

EARLY_CHECKIN_KEYWORDS = {
    "English": [
        "early check-in",
        "early check in",
        "check in early",
        "arrive early",
        "before check-in",
        "before check in"
    ],

    "Arabic": [
        "تسجيل الوصول المبكر",
        "الوصول المبكر",
        "تسجيل الدخول المبكر",
        "الوصول قبل موعد",
        "تسجيل الوصول قبل"
    ],

    "French": [
        "enregistrement anticipé",
        "arrivée anticipée",
        "arriver tôt",
        "enregistrement plus tôt",
        "avant l'heure d'arrivée"
    ],

    "Russian": [
        "ранний заезд",
        "раннего заезда",
        "заселиться раньше",
        "раннее заселение",
        "заехать раньше"
    ]
}


# ============================================================
# BASIC QUESTION CHECK
# ============================================================

def is_question(text):
    text = str(text).strip()

    if not text:
        return False

    return "?" in text


# ============================================================
# INT006 VALIDATOR
# ============================================================

def validate_int006_question(
    question,
    language,
    question_type,
    ground_truth
):

    question = str(question).strip()

    # --------------------------------------------------------
    # Empty check
    # --------------------------------------------------------

    if not question:
        return False, "Empty question"

    # --------------------------------------------------------
    # Must be a question
    # --------------------------------------------------------

    if not is_question(question):
        return False, "Not formatted as a question"

    # --------------------------------------------------------
    # No answer / explanation
    # --------------------------------------------------------

    if len(question.split()) > 35:
        return False, "Question is too long"

    # --------------------------------------------------------
    # Language validation
    # --------------------------------------------------------

    if language == "English":

        if has_arabic(question):
            return False, "Arabic characters found in English question"

        if has_cyrillic(question):
            return False, "Cyrillic characters found in English question"

    elif language == "Arabic":

        if has_cyrillic(question):
            return False, "Cyrillic characters found in Arabic question"

    elif language == "French":

        if has_arabic(question):
            return False, "Arabic characters found in French question"

        if has_cyrillic(question):
            return False, "Cyrillic characters found in French question"

    elif language == "Russian":

        if has_arabic(question):
            return False, "Arabic characters found in Russian question"

    else:
        return False, f"Unsupported language: {language}"

    # --------------------------------------------------------
    # Intent validation
    # --------------------------------------------------------

    question_lower = question.lower()

    keywords = EARLY_CHECKIN_KEYWORDS[language]

    intent_match = any(
        keyword.lower() in question_lower
        for keyword in keywords
    )

    if not intent_match:
        return False, "Not related to early check-in"

    # --------------------------------------------------------
    # Wrong intent protection
    # --------------------------------------------------------

    wrong_intents = {
        "English": [
            "late check-out",
            "late checkout",
            "standard check-in time",
            "check-out time",
            "checkout time"
        ],

        "Arabic": [
            "الخروج المتأخر",
            "وقت الخروج",
            "تسجيل الوصول العادي"
        ],

        "French": [
            "départ tardif",
            "heure de départ",
            "enregistrement standard"
        ],

        "Russian": [
            "поздний выезд",
            "время выезда",
            "стандартное время заезда"
        ]
    }

    for wrong in wrong_intents[language]:

        if wrong.lower() in question_lower:
            return False, f"Wrong intent detected: {wrong}"

    # --------------------------------------------------------
    # Direct / paraphrased / scenario basic checks
    # --------------------------------------------------------

    if question_type in ["Direct", "Paraphrased", "Scenario"]:

        if not question.endswith("?"):
            return False, "Question must end with '?'"

    # --------------------------------------------------------
    # Valid
    # --------------------------------------------------------

    return True, "Valid"


# ============================================================
# TEST VALIDATOR
# ============================================================

test_question = (
    "Can I check in early at Nile Pearl Hotel?"
)

valid, reason = validate_int006_question(
    question=test_question,
    language="English",
    question_type="Direct",
    ground_truth="Early check-in is subject to room availability and hotel approval."
)

print("=" * 80)
print("INT006 VALIDATOR")
print("=" * 80)

print("Test question:")
print(test_question)

print("\nValidation result:")
print("Valid:", valid)
print("Reason:", reason)

print("=" * 80)

if valid:
    print("Status: VALID")
else:
    print("Status: INVALID")

print("=" * 80)

================================================================================
INT006 VALIDATOR
================================================================================
Test question:
Can I check in early at Nile Pearl Hotel?

Validation result:
Valid: True
Reason: Valid
================================================================================
Status: VALID
================================================================================

In [31]:
# ============================================================
# INT006 - REGENERATION FUNCTION
# ============================================================

def regenerate_int006_question(
    row,
    max_attempts=5
):
    
    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]
    ground_truth = row["ground_truth"]

    last_question = ""
    last_reason = ""

    for attempt in range(1, max_attempts + 1):

        prompt = build_int006_prompt(
            faq_id=faq_id,
            language=language,
            question_type=question_type,
            ground_truth=ground_truth
        )

        try:

            payload = {
                "model": OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.7
                }
            }

            response = requests.post(
                OLLAMA_URL,
                json=payload,
                timeout=120
            )

            response.raise_for_status()

            data = response.json()

            question = data.get("response", "").strip()

            # ------------------------------------------------
            # Clean common unwanted prefixes
            # ------------------------------------------------

            question = re.sub(
                r"^(Question|Q)\s*:\s*",
                "",
                question,
                flags=re.IGNORECASE
            ).strip()

            # Remove surrounding quotes
            question = question.strip('"').strip("'").strip()

            last_question = question

            # ------------------------------------------------
            # Validate
            # ------------------------------------------------

            valid, reason = validate_int006_question(
                question=question,
                language=language,
                question_type=question_type,
                ground_truth=ground_truth
            )

            if valid:

                return {
                    "question": question,
                    "status": "VALID",
                    "attempts": attempt,
                    "reason": "Valid"
                }

            last_reason = reason

        except Exception as e:

            last_reason = f"Generation error: {str(e)}"

    return {
        "question": last_question,
        "status": "FAILED",
        "attempts": max_attempts,
        "reason": last_reason
    }


# ============================================================
# TEST REGENERATION
# ============================================================

test_row = int006_df.iloc[0]

print("=" * 80)
print("INT006 REGENERATION FUNCTION")
print("=" * 80)

print("FAQ ID:", test_row["faq_id"])
print("Language:", test_row["language"])
print("Type:", test_row["question_type"])

test_result = regenerate_int006_question(
    test_row,
    max_attempts=5
)

print("\nGenerated question:")
print(test_result["question"])

print("\nStatus:", test_result["status"])
print("Attempts:", test_result["attempts"])
print("Reason:", test_result["reason"])

print("=" * 80)

if test_result["status"] == "VALID":
    print("✅ REGENERATION FUNCTION READY")
else:
    print("⚠️ REGENERATION TEST FAILED")

print("=" * 80)

================================================================================
INT006 REGENERATION FUNCTION
================================================================================
FAQ ID: FAQ0161
Language: English
Type: Direct

Generated question:
Can I request early check-in at Nile Pearl Hotel?

Status: VALID
Attempts: 1
Reason: Valid
================================================================================
✅ REGENERATION FUNCTION READY
================================================================================

In [32]:
# ============================================================
# INT006 - FULL QUESTION GENERATION
# ============================================================

import pandas as pd
import time

print("=" * 80)
print("INT006 FULL QUESTION GENERATION")
print("=" * 80)

int006_results = []

for idx, (_, row) in enumerate(int006_df.iterrows(), start=1):

    print("\n" + "=" * 80)
    print(
        f"{idx}/{len(int006_df)} | "
        f"{row['faq_id']} | "
        f"{row['language']} | "
        f"{row['question_type']}"
    )
    print("=" * 80)

    result = regenerate_int006_question(
        row,
        max_attempts=5
    )

    int006_results.append({
        "faq_id": row["faq_id"],
        "intent_id": row["intent_id"],
        "intent_name": row["intent_name"],
        "category": row["category"],
        "language": row["language"],
        "question_type": row["question_type"],
        "difficulty": row["difficulty"],
        "question": result["question"],
        "ground_truth": row["ground_truth"],
        "source": row["source"],
        "status": result["status"],
        "attempts": result["attempts"],
        "reason": result["reason"]
    })

    print("GENERATED:", result["question"])
    print(
        f"Status: {result['status']} | "
        f"Attempts: {result['attempts']}"
    )

    if result["status"] == "FAILED":
        print("Reason:", result["reason"])

    # Small delay to avoid overloading Ollama
    time.sleep(0.2)


# ============================================================
# CREATE DATAFRAME
# ============================================================

int006_generated_df = pd.DataFrame(int006_results)


# ============================================================
# GENERATION SUMMARY
# ============================================================

total = len(int006_generated_df)

valid_count = (
    int006_generated_df["status"]
    .eq("VALID")
    .sum()
)

failed_count = (
    int006_generated_df["status"]
    .eq("FAILED")
    .sum()
)

non_empty_count = (
    int006_generated_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print("\n")
print("=" * 80)
print("INT006 GENERATION SUMMARY")
print("=" * 80)

print("Total:", total)
print("Valid:", valid_count)
print("Failed:", failed_count)
print("Non-empty:", non_empty_count)

print("=" * 80)

================================================================================
INT006 FULL QUESTION GENERATION
================================================================================

================================================================================
1/32 | FAQ0161 | English | Direct
================================================================================
GENERATED: Can I request early check-in at the Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
2/32 | FAQ0162 | English | Direct
================================================================================
GENERATED: Can I request early check-in at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
3/32 | FAQ0163 | English | Direct
================================================================================
GENERATED: Can I request early check-in at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
4/32 | FAQ0164 | English | Paraphrased
================================================================================
GENERATED: Can I request early check-in at the Nile Pearl Hotel, and if so, what should I be aware of?
Status: VALID | Attempts: 1

================================================================================
5/32 | FAQ0165 | English | Paraphrased
================================================================================
GENERATED: Can I request early check-in for my stay at Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
6/32 | FAQ0166 | English | Paraphrased
================================================================================
GENERATED: Can I request early check-in and when can I expect to be allowed to settle in early?
Status: VALID | Attempts: 1

================================================================================
7/32 | FAQ0167 | English | Scenario
================================================================================
GENERATED: If I arrive early, can I check in before my scheduled time?
Status: VALID | Attempts: 2

================================================================================
8/32 | FAQ0168 | English | Scenario
================================================================================
GENERATED: If I arrive early, can I check in before my scheduled time?
Status: VALID | Attempts: 1

================================================================================
9/32 | FAQ0169 | Arabic | Direct
================================================================================
GENERATED: هل يمكنني الوصول مبكرًا إلى الفندق قبل الوقت المحدد؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
10/32 | FAQ0170 | Arabic | Direct
================================================================================
GENERATED: هل يمكن الحصول على تسجيل إدخال مبكر في نيل اللؤلؤة_hotel_name_؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
11/32 | FAQ0171 | Arabic | Direct
================================================================================
GENERATED: هل يمكنني الوصول مبكرًا إلى الفندق قبل الوقت المحدد؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
12/32 | FAQ0172 | Arabic | Paraphrased
================================================================================
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel ومتى يمكن أن يحدث ذلك؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
13/32 | FAQ0173 | Arabic | Paraphrased
================================================================================
GENERATED: هل يمكنني دخول الفندق قبل وقت التفتيش المعتاد بناءً على التوفر وموافقة الفندق؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
14/32 | FAQ0174 | Arabic | Paraphrased
================================================================================
GENERATED: هل يمكنني الوصول مبكراً إلى غرفتي في Nile Pearl Hotel وفقاً للسياسة؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
15/32 | FAQ0175 | Arabic | Scenario
================================================================================
GENERATED: هل يمكنني الوصول مبكراً إلى الفندق قبل الوقت المحدد؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
16/32 | FAQ0176 | Arabic | Scenario
================================================================================
GENERATED: هل يمكنني الدخول مبكرًا إلى غرفة الفندق قبل وقت تسجيل الوصول المعتاد؟
Status: FAILED | Attempts: 5
Reason: Not formatted as a question

================================================================================
17/32 | FAQ0177 | French | Direct
================================================================================
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
Status: VALID | Attempts: 1

================================================================================
18/32 | FAQ0178 | French | Direct
================================================================================
GENERATED: Peut-on bénéficier d'un arrivée anticipée au Nile Pearl Hotel ?
Status: VALID | Attempts: 2

================================================================================
19/32 | FAQ0179 | French | Direct
================================================================================
GENERATED: Peut-on bénéficier d'un arrivée anticipée au Nile Pearl Hotel ?
Status: VALID | Attempts: 1

================================================================================
20/32 | FAQ0180 | French | Paraphrased
================================================================================
GENERATED: L'arrivée anticipée est-elle garantie si la chambre est disponible et avec l'accord de l'hôtel ?
Status: VALID | Attempts: 1

================================================================================
21/32 | FAQ0181 | French | Paraphrased
================================================================================
GENERATED: L'hôtel accepte-t-il une arrivée anticipée, et sous quels conditions ?
Status: VALID | Attempts: 1

================================================================================
22/32 | FAQ0182 | French | Paraphrased
================================================================================
GENERATED: L'hôtel peut-il accorder une arrivée anticipée?
Status: VALID | Attempts: 1

================================================================================
23/32 | FAQ0183 | French | Scenario
================================================================================
GENERATED: Peut-on bénéficier d'un arrivée anticipée au Nile Pearl Hotel ?
Status: VALID | Attempts: 1

================================================================================
24/32 | FAQ0184 | French | Scenario
================================================================================
GENERATED: Si je souhaite arriver tôt, est-ce que je peux bénéficier d'un arrivée anticipée au Nile Pearl Hotel ?
Status: VALID | Attempts: 2

================================================================================
25/32 | FAQ0185 | Russian | Direct
================================================================================
GENERATED: Есть ли возможность получить раннюю регистрацию заездом в Нил Перило Хôtel?
Status: FAILED | Attempts: 5
Reason: Not related to early check-in

================================================================================
26/32 | FAQ0186 | Russian | Direct
================================================================================
GENERATED: Как можно получить разрешение на раннюю регистрацию в Нил Пирл Хôtel?
Status: FAILED | Attempts: 5
Reason: Not related to early check-in

================================================================================
27/32 | FAQ0187 | Russian | Direct
================================================================================
GENERATED: Как можно забронировать номер на заезд раньше указанного времени в Нил Пирл Хôtel?
Status: FAILED | Attempts: 5
Reason: Not related to early check-in

================================================================================
28/32 | FAQ0188 | Russian | Paraphrased
================================================================================
GENERATED: Как можно получить разрешение на раннюю регистрацию в Нил Пирл Хôtel раньше установленного времени?
Status: FAILED | Attempts: 5
Reason: Not related to early check-in

================================================================================
29/32 | FAQ0189 | Russian | Paraphrased
================================================================================
GENERATED: Какие условия существуют для раннего заезда в Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
30/32 | FAQ0190 | Russian | Paraphrased
================================================================================
GENERATED: Как я могу узнать о возможности раннего заезда в Nile Pearl Hotel?
Status: VALID | Attempts: 1

================================================================================
31/32 | FAQ0191 | Russian | Scenario
================================================================================
GENERATED: Как можно забронировать комнату на раннюю регистрацию в Ниль Пирл Хôtel раньше назначенного времени?
Status: FAILED | Attempts: 5
Reason: Not related to early check-in

================================================================================
32/32 | FAQ0192 | Russian | Scenario
================================================================================
GENERATED: Как можно получить возможность раннего заезда в Нил Пирл Хôtel?
Status: VALID | Attempts: 5


================================================================================
INT006 GENERATION SUMMARY
================================================================================
Total: 32
Valid: 19
Failed: 13
Non-empty: 32
================================================================================

In [33]:
# ============================================================
# INT006 - IMPROVED QUESTION VALIDATION HELPERS
# ============================================================

import re

# ------------------------------------------------------------
# Question format
# ------------------------------------------------------------

def is_question(text):
    text = str(text).strip()

    if not text:
        return False

    # Support:
    # English/French/Russian -> ?
    # Arabic -> ؟
    return "?" in text or "؟" in text


# ------------------------------------------------------------
# Early check-in keywords
# ------------------------------------------------------------

EARLY_CHECKIN_KEYWORDS = {

    "English": [
        "early check-in",
        "early check in",
        "check in early",
        "arrive early",
        "before check-in",
        "before check in"
    ],

    "Arabic": [
        "تسجيل الوصول المبكر",
        "تسجيل الدخول المبكر",
        "الوصول المبكر",
        "الوصول مبكر",
        "تسجيل الوصول قبل",
        "الدخول مبكر",
        "أسجل الوصول مبكرًا",
        "أسجل الدخول مبكرًا"
    ],

    "French": [
        "arrivée anticipée",
        "arriver tôt",
        "enregistrement anticipé",
        "enregistrement plus tôt",
        "arrivée plus tôt"
    ],

    "Russian": [
        "ранний заезд",
        "раннего заезда",
        "раннее заселение",
        "ранней регистрации",
        "раннюю регистрацию",
        "заселиться раньше",
        "заехать раньше",
        "ранний приезд"
    ]
}


# ------------------------------------------------------------
# Forbidden concepts
# ------------------------------------------------------------

FORBIDDEN_INT006_TERMS = {

    "English": [
        "late check-out",
        "late check out",
        "standard check-in time",
        "regular check-in time"
    ],

    "Arabic": [
        "الخروج المتأخر",
        "تسجيل الخروج المتأخر",
        "وقت تسجيل الوصول المعتاد"
    ],

    "French": [
        "départ tardif",
        "check-out tardif",
        "heure d'arrivée standard"
    ],

    "Russian": [
        "поздний выезд",
        "позднего выезда",
        "стандартное время заезда"
    ]
}


print("=" * 80)
print("INT006 VALIDATION HELPERS")
print("=" * 80)

print("Question mark check: READY")
print("Language keywords: READY")
print("Forbidden terms: READY")
print("=" * 80)

================================================================================
INT006 VALIDATION HELPERS
================================================================================
Question mark check: READY
Language keywords: READY
Forbidden terms: READY
================================================================================

In [34]:
# ============================================================
# INT006 - IMPROVED PROMPT BUILDER
# ============================================================

def build_int006_prompt(
    faq_id,
    language,
    question_type,
    ground_truth
):

    prompt = f"""
You are generating ONE high-quality FAQ question
for a multilingual hotel AI assistant.

Hotel name:
Nile Pearl Hotel

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

CORE INTENT:
early_check_in

Ground truth:
{ground_truth}


IMPORTANT SEMANTIC RULE:

The question MUST be specifically about EARLY CHECK-IN.

The guest wants to know whether they can arrive,
check in, or access the room before the normal
check-in time.

The question must NOT be about:

- standard check-in time
- late check-out
- room availability in general
- hotel approval in general
- booking a room
- changing a reservation
- cancellation
- payment
- additional fees


DO NOT INVENT:

- a specific early check-in time
- an additional fee
- a guarantee
- a new hotel policy
- a new service


HOTEL NAME RULE:

If you mention the hotel name, write it EXACTLY as:

Nile Pearl Hotel

Never translate or modify the hotel name.

Never write:

Нил Пирл
Нил Перило
Нильский Бриллиант
Nile Перило
_hotel_name_
hôtel Nile Pearl


LANGUAGE RULE:

The question must be entirely in {language}.

Do not mix Arabic, English, French, or Russian sentences.

The hotel name "Nile Pearl Hotel" may remain exactly
as written even when the question is Arabic, French,
or Russian.


QUESTION TYPE:

Direct:
Ask directly whether early check-in is possible.

Paraphrased:
Ask the same thing using different natural wording.

Scenario:
Create a realistic guest situation involving arriving
early, then ask whether early check-in is possible.


QUALITY RULES:

- Return exactly ONE question.
- The output must be a question.
- English/French/Russian questions should end with "?".
- Arabic questions should end with "؟".
- Keep the question natural and concise.
- Do not answer the question.
- Do not include explanations.
- Do not include labels.
- Do not include quotation marks.
- Do not include bullet points.
- Do not include "Question:".


EXAMPLES OF GOOD QUESTIONS:

English:
Can I request early check-in at Nile Pearl Hotel?

Arabic:
هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

French:
L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

Russian:
Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?


FINAL SELF-CHECK:

Before returning the question, verify:

1. It is exactly ONE question.
2. It is about early check-in.
3. It is in the requested language.
4. It does not ask about standard check-in.
5. It does not ask about late check-out.
6. It does not invent a time.
7. It does not invent a fee.
8. It does not claim early check-in is guaranteed.
9. If the hotel name appears, it is exactly "Nile Pearl Hotel".
10. It ends with the correct question mark.

Return ONLY the question.

Generate now.
"""

    return prompt.strip()


print("=" * 80)
print("INT006 IMPROVED PROMPT BUILDER")
print("=" * 80)

test_prompt = build_int006_prompt(
    faq_id="FAQ0169",
    language="Arabic",
    question_type="Direct",
    ground_truth=(
        "Early check-in is subject to room availability "
        "and hotel approval."
    )
)

print(test_prompt)

print("=" * 80)
print("PROMPT BUILDER READY")
print("=" * 80)

================================================================================
INT006 IMPROVED PROMPT BUILDER
================================================================================
You are generating ONE high-quality FAQ question
for a multilingual hotel AI assistant.

Hotel name:
Nile Pearl Hotel

FAQ ID:
FAQ0169

Language:
Arabic

Question type:
Direct

CORE INTENT:
early_check_in

Ground truth:
Early check-in is subject to room availability and hotel approval.


IMPORTANT SEMANTIC RULE:

The question MUST be specifically about EARLY CHECK-IN.

The guest wants to know whether they can arrive,
check in, or access the room before the normal
check-in time.

The question must NOT be about:

- standard check-in time
- late check-out
- room availability in general
- hotel approval in general
- booking a room
- changing a reservation
- cancellation
- payment
- additional fees


DO NOT INVENT:

- a specific early check-in time
- an additional fee
- a guarantee
- a new hotel policy
- a new service


HOTEL NAME RULE:

If you mention the hotel name, write it EXACTLY as:

Nile Pearl Hotel

Never translate or modify the hotel name.

Never write:

Нил Пирл
Нил Перило
Нильский Бриллиант
Nile Перило
_hotel_name_
hôtel Nile Pearl


LANGUAGE RULE:

The question must be entirely in Arabic.

Do not mix Arabic, English, French, or Russian sentences.

The hotel name "Nile Pearl Hotel" may remain exactly
as written even when the question is Arabic, French,
or Russian.


QUESTION TYPE:

Direct:
Ask directly whether early check-in is possible.

Paraphrased:
Ask the same thing using different natural wording.

Scenario:
Create a realistic guest situation involving arriving
early, then ask whether early check-in is possible.


QUALITY RULES:

- Return exactly ONE question.
- The output must be a question.
- English/French/Russian questions should end with "?".
- Arabic questions should end with "؟".
- Keep the question natural and concise.
- Do not answer the question.
- Do not include explanations.
- Do not include labels.
- Do not include quotation marks.
- Do not include bullet points.
- Do not include "Question:".


EXAMPLES OF GOOD QUESTIONS:

English:
Can I request early check-in at Nile Pearl Hotel?

Arabic:
هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

French:
L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

Russian:
Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?


FINAL SELF-CHECK:

Before returning the question, verify:

1. It is exactly ONE question.
2. It is about early check-in.
3. It is in the requested language.
4. It does not ask about standard check-in.
5. It does not ask about late check-out.
6. It does not invent a time.
7. It does not invent a fee.
8. It does not claim early check-in is guaranteed.
9. If the hotel name appears, it is exactly "Nile Pearl Hotel".
10. It ends with the correct question mark.

Return ONLY the question.

Generate now.
================================================================================
PROMPT BUILDER READY
================================================================================

In [35]:
# ============================================================
# INT006 - IMPROVED QUESTION GENERATION
# ============================================================

import pandas as pd
import requests
import time
import re

INTENT_ID = "INT006"

# ------------------------------------------------------------
# 1. Get INT006 rows
# ------------------------------------------------------------

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print("=" * 80)
print("INT006 IMPROVED QUESTION GENERATION")
print("=" * 80)

print(f"Total rows: {len(int006_df)}")
print()

# ------------------------------------------------------------
# 2. Ollama configuration
# ------------------------------------------------------------

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:7b"

# ------------------------------------------------------------
# 3. Ground truth
# ------------------------------------------------------------

GROUND_TRUTH = (
    "Early check-in is subject to room availability and hotel approval."
)

# ------------------------------------------------------------
# 4. Language instructions
# ------------------------------------------------------------

LANGUAGE_RULES = {
    "English": """
Write the question entirely in English.
Use natural hotel guest language.
""",

    "Arabic": """
Write the question entirely in Arabic.
Arabic script must be used.
The hotel name may remain exactly:
Nile Pearl Hotel
The question must end with:
؟
""",

    "French": """
Write the question entirely in French.
The hotel name may remain exactly:
Nile Pearl Hotel
The question must end with:
?
""",

    "Russian": """
Write the question entirely in Russian.
Use Cyrillic.
The hotel name may remain exactly:
Nile Pearl Hotel
The question must end with:
?
"""
}

# ------------------------------------------------------------
# 5. Question type instructions
# ------------------------------------------------------------

QUESTION_TYPE_RULES = {
    "Direct": """
Ask directly whether early check-in is possible.
Keep the question short and factual.
""",

    "Paraphrased": """
Ask about the same early check-in intent using different
natural wording.
Do not simply copy a Direct question.
""",

    "Scenario": """
Create a realistic hotel guest situation involving arriving
early, then ask whether early check-in is possible.
Do not invent a specific arrival time.
"""
}

# ------------------------------------------------------------
# 6. Prompt builder
# ------------------------------------------------------------

def build_int006_prompt(row):

    language = row["language"]
    question_type = row["question_type"]
    faq_id = row["faq_id"]

    prompt = f"""
You are generating ONE high-quality FAQ question
for a multilingual hotel AI assistant.

Hotel name:
Nile Pearl Hotel

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

CORE INTENT:
early_check_in

Ground truth:
{GROUND_TRUTH}


SEMANTIC RULE:

The question MUST be specifically about EARLY CHECK-IN.

The guest wants to know whether they can arrive,
check in, or access the room before the normal
check-in time.

The question must NOT be about:

- standard check-in time
- late check-out
- room availability in general
- hotel approval in general
- booking a room
- changing a reservation
- cancellation
- payment
- additional fees


DO NOT INVENT:

- a specific early check-in time
- an additional fee
- a guarantee
- a new hotel policy
- a new service


HOTEL NAME RULE:

If you mention the hotel name, write it EXACTLY as:

Nile Pearl Hotel

Never translate or modify the hotel name.

Never write:

Нил Пирл
Нил Перило
Нильский Бриллиант
Nile Перило
_hotel_name_
hôtel Nile Pearl


LANGUAGE RULE:

{LANGUAGE_RULES[language]}


QUESTION TYPE RULE:

{QUESTION_TYPE_RULES[question_type]}


QUALITY RULES:

- Return exactly ONE question.
- The output must be a question.
- Do not answer the question.
- Do not include explanations.
- Do not include labels.
- Do not include quotation marks.
- Do not include bullet points.
- Do not include "Question:".
- Do not mix languages.
- Keep the question natural and concise.


GOOD EXAMPLES:

English:
Can I request early check-in at Nile Pearl Hotel?

Arabic:
هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

French:
L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

Russian:
Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?


FINAL SELF-CHECK:

Before returning the question, verify:

1. Exactly ONE question.
2. About early check-in.
3. Correct requested language.
4. Not about standard check-in.
5. Not about late check-out.
6. No invented time.
7. No invented fee.
8. No guarantee.
9. Hotel name, if used, is exactly Nile Pearl Hotel.
10. Correct question mark.

Return ONLY the question.

Generate now.
"""

    return prompt.strip()


# ------------------------------------------------------------
# 7. Ollama generation
# ------------------------------------------------------------

def generate_ollama_question(prompt):

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.7,
            "top_p": 0.9
        }
    }

    try:

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        question = data.get("response", "").strip()

        # Remove accidental labels
        question = re.sub(
            r"^(Question|question)\s*:\s*",
            "",
            question
        ).strip()

        # Remove surrounding quotes
        question = question.strip('"').strip("'").strip()

        # Remove accidental multiple lines
        question = question.split("\n")[0].strip()

        return question

    except Exception as e:

        print(f"Ollama Error: {e}")
        return ""


# ------------------------------------------------------------
# 8. Generate all questions
# ------------------------------------------------------------

generated_questions = []

print("=" * 80)
print("GENERATING INT006 QUESTIONS")
print("=" * 80)

for index, row in int006_df.iterrows():

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    print()
    print("-" * 80)
    print(
        f"{index + 1}/{len(int006_df)} | "
        f"{faq_id} | {language} | {question_type}"
    )

    prompt = build_int006_prompt(row)

    question = generate_ollama_question(prompt)

    generated_questions.append(question)

    print("GENERATED:", question)

    time.sleep(0.5)


# ------------------------------------------------------------
# 9. Save generated questions
# ------------------------------------------------------------

int006_df["question"] = generated_questions

print()
print("=" * 80)
print("INT006 GENERATION COMPLETE")
print("=" * 80)

print("Total:", len(int006_df))
print("Non-empty:", int006_df["question"].ne("").sum())
print("Empty:", int006_df["question"].eq("").sum())

================================================================================
INT006 IMPROVED QUESTION GENERATION
================================================================================
Total rows: 32

================================================================================
GENERATING INT006 QUESTIONS
================================================================================

--------------------------------------------------------------------------------
161/32 | FAQ0161 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
162/32 | FAQ0162 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
163/32 | FAQ0163 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
164/32 | FAQ0164 | English | Paraphrased
GENERATED: Can I arrange for an early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
165/32 | FAQ0165 | English | Paraphrased
GENERATED: Can I arrange for early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
166/32 | FAQ0166 | English | Paraphrased
GENERATED: Can I get an early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
167/32 | FAQ0167 | English | Scenario
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
168/32 | FAQ0168 | English | Scenario
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
169/32 | FAQ0169 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
170/32 | FAQ0170 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
171/32 | FAQ0171 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
172/32 | FAQ0172 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
173/32 | FAQ0173 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
174/32 | FAQ0174 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
175/32 | FAQ0175 | Arabic | Scenario
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
176/32 | FAQ0176 | Arabic | Scenario
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
177/32 | FAQ0177 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
178/32 | FAQ0178 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
179/32 | FAQ0179 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
180/32 | FAQ0180 | French | Paraphrased
GENERATED: L'arrivée précoce est-elle autorisée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
181/32 | FAQ0181 | French | Paraphrased
GENERATED: Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
182/32 | FAQ0182 | French | Paraphrased
GENERATED: L'hotel peut-il me permettre d'arriver plus tôt que la date prévue au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
183/32 | FAQ0183 | French | Scenario
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
184/32 | FAQ0184 | French | Scenario
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
185/32 | FAQ0185 | Russian | Direct
GENERATED: Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
186/32 | FAQ0186 | Russian | Direct
GENERATED: Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
187/32 | FAQ0187 | Russian | Direct
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

--------------------------------------------------------------------------------
188/32 | FAQ0188 | Russian | Paraphrased
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

--------------------------------------------------------------------------------
189/32 | FAQ0189 | Russian | Paraphrased
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

--------------------------------------------------------------------------------
190/32 | FAQ0190 | Russian | Paraphrased
GENERATED: Можно ли мне приехать раньше времени заезда в Nile Pearl Hotel?

--------------------------------------------------------------------------------
191/32 | FAQ0191 | Russian | Scenario
GENERATED: Можно ли мне воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
192/32 | FAQ0192 | Russian | Scenario
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

================================================================================
INT006 GENERATION COMPLETE
================================================================================
Total: 32
Non-empty: 32
Empty: 0

In [36]:
# ============================================================
# INT006 - DUPLICATE DETECTION
# ============================================================

import pandas as pd
from difflib import SequenceMatcher

print("=" * 80)
print("INT006 DUPLICATE CHECK")
print("=" * 80)

# Make sure INT006 exists
int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == "INT006"
].copy()

print(f"Total questions: {len(int006_df)}")

# ------------------------------------------------------------
# Similarity function
# ------------------------------------------------------------

def text_similarity(text1, text2):
    text1 = str(text1).strip().lower()
    text2 = str(text2).strip().lower()

    return SequenceMatcher(None, text1, text2).ratio()


# ------------------------------------------------------------
# Check duplicates
# ------------------------------------------------------------

duplicates = []

rows = int006_df.reset_index(drop=True)

for i in range(len(rows)):
    for j in range(i + 1, len(rows)):

        q1 = rows.loc[i, "question"]
        q2 = rows.loc[j, "question"]

        # Skip empty questions
        if not str(q1).strip() or not str(q2).strip():
            continue

        similarity = text_similarity(q1, q2)

        # Detect highly similar questions
        if similarity >= 0.85:

            duplicates.append({
                "faq_1": rows.loc[i, "faq_id"],
                "faq_2": rows.loc[j, "faq_id"],
                "language": rows.loc[i, "language"],
                "question_type_1": rows.loc[i, "question_type"],
                "question_type_2": rows.loc[j, "question_type"],
                "similarity": round(similarity, 3),
                "question_1": q1,
                "question_2": q2
            })


duplicates_df = pd.DataFrame(duplicates)

print("=" * 80)
print("INT006 DUPLICATE RESULTS")
print("=" * 80)

print(f"Potential duplicates: {len(duplicates_df)}")

if len(duplicates_df) > 0:

    print("\n⚠️ POTENTIAL DUPLICATES FOUND\n")

    display(
        duplicates_df.sort_values(
            "similarity",
            ascending=False
        ).reset_index(drop=True)
    )

else:

    print("✅ NO POTENTIAL DUPLICATES FOUND")

================================================================================
INT006 DUPLICATE CHECK
================================================================================
Total questions: 32
================================================================================
INT006 DUPLICATE RESULTS
================================================================================
Potential duplicates: 496

⚠️ POTENTIAL DUPLICATES FOUND

,faq_1,faq_2,language,question_type_1,question_type_2,similarity,question_1,question_2
0,FAQ0161,FAQ0162,English,Direct,Direct,1.0,NaN,NaN
1,FAQ0161,FAQ0163,English,Direct,Direct,1.0,NaN,NaN
2,FAQ0161,FAQ0164,English,Direct,Paraphrased,1.0,NaN,NaN
3,FAQ0161,FAQ0165,English,Direct,Paraphrased,1.0,NaN,NaN
4,FAQ0161,FAQ0166,English,Direct,Paraphrased,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
491,FAQ0189,FAQ0191,Russian,Paraphrased,Scenario,1.0,NaN,NaN
492,FAQ0189,FAQ0192,Russian,Paraphrased,Scenario,1.0,NaN,NaN
493,FAQ0190,FAQ0191,Russian,Paraphrased,Scenario,1.0,NaN,NaN
494,FAQ0190,FAQ0192,Russian,Paraphrased,Scenario,1.0,NaN,NaN
495,FAQ0191,FAQ0192,Russian,Scenario,Scenario,1.0,NaN,NaN

In [37]:
# ============================================================
# INT006 - CHECK GENERATED QUESTIONS STORAGE
# ============================================================

print("=" * 80)
print("INT006 QUESTION STORAGE CHECK")
print("=" * 80)

# INT006 rows from generation plan
int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == "INT006"
].copy()

print("Rows:", len(int006_df))

print("\nQuestion column:")
print(int006_df["question"].head(10))

print("\nNon-empty questions:",
      int006_df["question"].notna().sum())

print("Empty questions:",
      int006_df["question"].isna().sum())

================================================================================
INT006 QUESTION STORAGE CHECK
================================================================================
Rows: 32

Question column:
160   NaN
161   NaN
162   NaN
163   NaN
164   NaN
165   NaN
166   NaN
167   NaN
168   NaN
169   NaN
Name: question, dtype: float64

Non-empty questions: 0
Empty questions: 32

In [38]:
# ============================================================
# INT006 - QUESTION GENERATION + STORAGE FIX
# ============================================================

import pandas as pd
import time

print("=" * 80)
print("INT006 QUESTION GENERATION + STORAGE")
print("=" * 80)

INTENT_ID = "INT006"

# ------------------------------------------------------------
# 1. Load INT006 data
# ------------------------------------------------------------

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print(f"Total rows: {len(int006_df)}")

# ------------------------------------------------------------
# 2. Make sure question column exists
# ------------------------------------------------------------

if "question" not in int006_df.columns:
    int006_df["question"] = ""

# Clear old generated questions
int006_df["question"] = ""

# ------------------------------------------------------------
# 3. Generate each question
# ------------------------------------------------------------

generated_questions = []

for idx, row in int006_df.iterrows():

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    print("-" * 80)
    print(f"{idx + 1}/{len(int006_df)} | {faq_id} | {language} | {question_type}")

    try:
        # Build prompt
        prompt = build_improved_prompt(
            row=row
        )

        # Generate question
        question = generate_question_with_ollama(
            prompt=prompt
        )

        # Clean output
        if question is None:
            question = ""

        question = str(question).strip()

        # Remove accidental labels
        if question.lower().startswith("question:"):
            question = question.split(":", 1)[1].strip()

        generated_questions.append(question)

        print(f"GENERATED: {question}")

    except Exception as e:

        print(f"ERROR: {e}")

        generated_questions.append("")

# ------------------------------------------------------------
# 4. CRITICAL FIX
# ------------------------------------------------------------

# Assign generated questions by POSITION
int006_df["question"] = generated_questions

# ------------------------------------------------------------
# 5. Validation
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STORAGE VALIDATION")
print("=" * 80)

print("Rows:", len(int006_df))

print("\nQuestion column:")
print(int006_df["question"].head(10))

non_empty = int006_df["question"].fillna("").astype(str).str.strip().ne("").sum()

empty = len(int006_df) - non_empty

print("\nNon-empty questions:", non_empty)
print("Empty questions:", empty)

if non_empty == len(int006_df):
    print("\n✅ ALL QUESTIONS STORED SUCCESSFULLY")
else:
    print("\n⚠️ SOME QUESTIONS ARE EMPTY")

print("=" * 80)

================================================================================
INT006 QUESTION GENERATION + STORAGE
================================================================================
Total rows: 32
--------------------------------------------------------------------------------
161/32 | FAQ0161 | English | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
162/32 | FAQ0162 | English | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
163/32 | FAQ0163 | English | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
164/32 | FAQ0164 | English | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
165/32 | FAQ0165 | English | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
166/32 | FAQ0166 | English | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
167/32 | FAQ0167 | English | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
168/32 | FAQ0168 | English | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
169/32 | FAQ0169 | Arabic | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
170/32 | FAQ0170 | Arabic | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
171/32 | FAQ0171 | Arabic | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
172/32 | FAQ0172 | Arabic | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
173/32 | FAQ0173 | Arabic | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
174/32 | FAQ0174 | Arabic | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
175/32 | FAQ0175 | Arabic | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
176/32 | FAQ0176 | Arabic | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
177/32 | FAQ0177 | French | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
178/32 | FAQ0178 | French | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
179/32 | FAQ0179 | French | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
180/32 | FAQ0180 | French | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
181/32 | FAQ0181 | French | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
182/32 | FAQ0182 | French | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
183/32 | FAQ0183 | French | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
184/32 | FAQ0184 | French | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
185/32 | FAQ0185 | Russian | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
186/32 | FAQ0186 | Russian | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
187/32 | FAQ0187 | Russian | Direct
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
188/32 | FAQ0188 | Russian | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
189/32 | FAQ0189 | Russian | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
190/32 | FAQ0190 | Russian | Paraphrased
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
191/32 | FAQ0191 | Russian | Scenario
ERROR: name 'build_improved_prompt' is not defined
--------------------------------------------------------------------------------
192/32 | FAQ0192 | Russian | Scenario
ERROR: name 'build_improved_prompt' is not defined

================================================================================
STORAGE VALIDATION
================================================================================
Rows: 32

Question column:
160
161
162
163
164
165
166
167
168
169
Name: question, dtype: object

Non-empty questions: 0
Empty questions: 32

⚠️ SOME QUESTIONS ARE EMPTY
================================================================================

In [40]:
# ============================================================
# CHECK EXISTING FUNCTIONS - FIXED
# ============================================================

import inspect

print("=" * 80)
print("AVAILABLE FUNCTIONS")
print("=" * 80)

# IMPORTANT: copy globals first
global_items = list(globals().items())

found = []

for name, obj in global_items:

    if callable(obj) and not name.startswith("_"):

        try:
            source = inspect.getsource(obj)

            if (
                "ollama" in source.lower()
                or "prompt" in source.lower()
                or "question" in source.lower()
            ):
                found.append(name)

        except (OSError, TypeError, IOError):
            pass

for name in found:
    print(name)

print("\nTotal matching functions:", len(found))

print("=" * 80)

================================================================================
AVAILABLE FUNCTIONS
================================================================================
build_int005_prompt
validate_int005_question
regenerate_int005_question
test_ollama
build_int006_prompt
is_question
validate_int006_question
regenerate_int006_question
generate_ollama_question

Total matching functions: 9
================================================================================

In [41]:
# ============================================================
# INT006 - GENERATION + STORAGE FIX
# ============================================================

import pandas as pd
import time

INTENT_ID = "INT006"

print("=" * 80)
print("INT006 GENERATION + STORAGE FIX")
print("=" * 80)

# ------------------------------------------------------------
# 1. Load INT006
# ------------------------------------------------------------

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

print("Total rows:", len(int006_df))

# ------------------------------------------------------------
# 2. Generate questions
# ------------------------------------------------------------

generated_questions = []

print("\n")
print("=" * 80)
print("GENERATING QUESTIONS")
print("=" * 80)

for counter, (idx, row) in enumerate(
    int006_df.iterrows(),
    start=1
):

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    print("\n" + "-" * 80)
    print(
        f"{counter}/{len(int006_df)} | "
        f"{faq_id} | {language} | {question_type}"
    )

    try:

        # Build INT006 prompt using YOUR existing function
        prompt = build_int006_prompt(row)

        # Generate using YOUR existing Ollama function
        question = generate_ollama_question(prompt)

        # Clean result
        if question is None:
            question = ""

        question = str(question).strip()

        # Remove accidental "Question:"
        if question.lower().startswith("question:"):
            question = question.split(":", 1)[1].strip()

        generated_questions.append(question)

        print("GENERATED:", question)

    except Exception as e:

        print("ERROR:", e)

        generated_questions.append("")

# ------------------------------------------------------------
# 3. CRITICAL STORAGE FIX
# ------------------------------------------------------------

int006_df["question"] = generated_questions

# ------------------------------------------------------------
# 4. Storage validation
# ------------------------------------------------------------

print("\n")
print("=" * 80)
print("INT006 STORAGE VALIDATION")
print("=" * 80)

print("Rows:", len(int006_df))

non_empty = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

empty = len(int006_df) - non_empty

print("Non-empty questions:", non_empty)
print("Empty questions:", empty)

print("\nFirst 10 stored questions:")

print(
    int006_df[
        ["faq_id", "language", "question_type", "question"]
    ].head(10).to_string(index=False)
)

print("\nQuestion dtype:")
print(int006_df["question"].dtype)

print("\nNaN count:")
print(int006_df["question"].isna().sum())

if non_empty == len(int006_df):
    print("\n" + "=" * 80)
    print("✅ INT006 GENERATION + STORAGE SUCCESSFUL")
    print("=" * 80)
else:
    print("\n" + "=" * 80)
    print("⚠️ SOME QUESTIONS ARE EMPTY")
    print("=" * 80)

================================================================================
INT006 GENERATION + STORAGE FIX
================================================================================
Total rows: 32


================================================================================
GENERATING QUESTIONS
================================================================================

--------------------------------------------------------------------------------
1/32 | FAQ0161 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
2/32 | FAQ0162 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
3/32 | FAQ0163 | English | Direct
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
4/32 | FAQ0164 | English | Paraphrased
GENERATED: Can I get an early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
5/32 | FAQ0165 | English | Paraphrased
GENERATED: Can I arrange for an early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
6/32 | FAQ0166 | English | Paraphrased
GENERATED: Can I ask for an early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
7/32 | FAQ0167 | English | Scenario
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
8/32 | FAQ0168 | English | Scenario
GENERATED: Can I request early check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
9/32 | FAQ0169 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
10/32 | FAQ0170 | Arabic | Direct
GENERATED: هل يمكنني التسجيل المبكر في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
11/32 | FAQ0171 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
12/32 | FAQ0172 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
13/32 | FAQ0173 | Arabic | Paraphrased
GENERATED: هل يمكنني أن أدخل غرفتي مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
14/32 | FAQ0174 | Arabic | Paraphrased
GENERATED: هل يمكنني الدخول إلى غرفتي مبكرًا في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
15/32 | FAQ0175 | Arabic | Scenario
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
16/32 | FAQ0176 | Arabic | Scenario
GENERATED: هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

--------------------------------------------------------------------------------
17/32 | FAQ0177 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
18/32 | FAQ0178 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
19/32 | FAQ0179 | French | Direct
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
20/32 | FAQ0180 | French | Paraphrased
GENERATED: Peut-on réaliser un check-in précoce au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
21/32 | FAQ0181 | French | Paraphrased
GENERATED: Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
22/32 | FAQ0182 | French | Paraphrased
GENERATED: Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
23/32 | FAQ0183 | French | Scenario
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
24/32 | FAQ0184 | French | Scenario
GENERATED: L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
25/32 | FAQ0185 | Russian | Direct
GENERATED: Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
26/32 | FAQ0186 | Russian | Direct
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

--------------------------------------------------------------------------------
27/32 | FAQ0187 | Russian | Direct
GENERATED: Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
28/32 | FAQ0188 | Russian | Paraphrased
GENERATED: Можно ли договориться о раннем заезде в Nile Pearl Hotel?

--------------------------------------------------------------------------------
29/32 | FAQ0189 | Russian | Paraphrased
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?

--------------------------------------------------------------------------------
30/32 | FAQ0190 | Russian | Paraphrased
GENERATED: Можно ли мне заранее заселиться в Nile Pearl Hotel?

--------------------------------------------------------------------------------
31/32 | FAQ0191 | Russian | Scenario
GENERATED: Можно ли мне воспользоваться ранним заездом в Nile Pearl Hotel?

--------------------------------------------------------------------------------
32/32 | FAQ0192 | Russian | Scenario
GENERATED: Можно ли получить ранний заезд в Nile Pearl Hotel?


================================================================================
INT006 STORAGE VALIDATION
================================================================================
Rows: 32
Non-empty questions: 32
Empty questions: 0

First 10 stored questions:
 faq_id language question_type                                                 question
FAQ0161  English        Direct        Can I request early check-in at Nile Pearl Hotel?
FAQ0162  English        Direct        Can I request early check-in at Nile Pearl Hotel?
FAQ0163  English        Direct        Can I request early check-in at Nile Pearl Hotel?
FAQ0164  English   Paraphrased         Can I get an early check-in at Nile Pearl Hotel?
FAQ0165  English   Paraphrased Can I arrange for an early check-in at Nile Pearl Hotel?
FAQ0166  English   Paraphrased     Can I ask for an early check-in at Nile Pearl Hotel?
FAQ0167  English      Scenario        Can I request early check-in at Nile Pearl Hotel?
FAQ0168  English      Scenario        Can I request early check-in at Nile Pearl Hotel?
FAQ0169   Arabic        Direct       هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟
FAQ0170   Arabic        Direct            هل يمكنني التسجيل المبكر في Nile Pearl Hotel؟

Question dtype:
object

NaN count:
0

================================================================================
✅ INT006 GENERATION + STORAGE SUCCESSFUL
================================================================================

In [42]:
# ============================================================
# INT006 - REAL DUPLICATE CHECK
# ============================================================

import pandas as pd
from difflib import SequenceMatcher

print("=" * 80)
print("INT006 REAL DUPLICATE CHECK")
print("=" * 80)

df = int006_df.copy()

# ------------------------------------------------------------
# Clean questions
# ------------------------------------------------------------

df["question"] = (
    df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
)

# ------------------------------------------------------------
# Normalize text for exact duplicate detection
# ------------------------------------------------------------

def normalize_question(text):
    text = str(text).strip().lower()

    # Remove final question marks
    text = text.replace("؟", "")
    text = text.replace("?", "")

    # Normalize spaces
    text = " ".join(text.split())

    return text


df["normalized_question"] = df["question"].apply(
    normalize_question
)

# ------------------------------------------------------------
# Exact duplicates
# ------------------------------------------------------------

exact_duplicates = df[
    df.duplicated(
        subset=["language", "normalized_question"],
        keep=False
    )
].copy()

print("\nTotal questions:", len(df))
print("Exact duplicate rows:", len(exact_duplicates))

if len(exact_duplicates) == 0:

    print("✅ NO EXACT DUPLICATES")

else:

    print("⚠️ EXACT DUPLICATES FOUND\n")

    print(
        exact_duplicates[
            [
                "faq_id",
                "language",
                "question_type",
                "question"
            ]
        ].sort_values(
            ["language", "question"]
        ).to_string(index=False)
    )

# ------------------------------------------------------------
# Similarity check
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("SIMILARITY CHECK")
print("=" * 80)

similar_pairs = []

for i in range(len(df)):

    for j in range(i + 1, len(df)):

        # Only compare questions in same language
        if df.iloc[i]["language"] != df.iloc[j]["language"]:
            continue

        q1 = df.iloc[i]["normalized_question"]
        q2 = df.iloc[j]["normalized_question"]

        if not q1 or not q2:
            continue

        similarity = SequenceMatcher(
            None,
            q1,
            q2
        ).ratio()

        if similarity >= 0.85:

            similar_pairs.append({
                "faq_1": df.iloc[i]["faq_id"],
                "faq_2": df.iloc[j]["faq_id"],
                "language": df.iloc[i]["language"],
                "question_type_1": df.iloc[i]["question_type"],
                "question_type_2": df.iloc[j]["question_type"],
                "similarity": round(similarity, 3),
                "question_1": df.iloc[i]["question"],
                "question_2": df.iloc[j]["question"]
            })

similar_df = pd.DataFrame(similar_pairs)

print("Potential similar pairs:", len(similar_df))

if len(similar_df) > 0:

    print("\nTop similar pairs:")

    print(
        similar_df
        .sort_values("similarity", ascending=False)
        .head(50)
        .to_string(index=False)
    )

else:

    print("✅ NO HIGH-SIMILARITY PAIRS")

print("\n" + "=" * 80)
print("DUPLICATE CHECK COMPLETE")
print("=" * 80)

================================================================================
INT006 REAL DUPLICATE CHECK
================================================================================

Total questions: 32
Exact duplicate rows: 22
⚠️ EXACT DUPLICATES FOUND

 faq_id language question_type                                                    question
FAQ0172   Arabic   Paraphrased               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0175   Arabic      Scenario               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0176   Arabic      Scenario               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0169   Arabic        Direct          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟
FAQ0171   Arabic        Direct          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟
FAQ0161  English        Direct           Can I request early check-in at Nile Pearl Hotel?
FAQ0162  English        Direct           Can I request early check-in at Nile Pearl Hotel?
FAQ0163  English        Direct           Can I request early check-in at Nile Pearl Hotel?
FAQ0167  English      Scenario           Can I request early check-in at Nile Pearl Hotel?
FAQ0168  English      Scenario           Can I request early check-in at Nile Pearl Hotel?
FAQ0177   French        Direct L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0178   French        Direct L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0179   French        Direct L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0183   French      Scenario L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0184   French      Scenario L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0181   French   Paraphrased Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?
FAQ0182   French   Paraphrased Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?
FAQ0185  Russian        Direct Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?
FAQ0187  Russian        Direct Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?
FAQ0186  Russian        Direct          Можно ли получить ранний заезд в Nile Pearl Hotel?
FAQ0189  Russian   Paraphrased          Можно ли получить ранний заезд в Nile Pearl Hotel?
FAQ0192  Russian      Scenario          Можно ли получить ранний заезд в Nile Pearl Hotel?

================================================================================
SIMILARITY CHECK
================================================================================
Potential similar pairs: 48

Top similar pairs:
  faq_1   faq_2 language question_type_1 question_type_2  similarity                                                  question_1                                                      question_2
FAQ0161 FAQ0162  English          Direct          Direct       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0161 FAQ0163  English          Direct          Direct       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0161 FAQ0167  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0161 FAQ0168  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0162 FAQ0167  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0162 FAQ0163  English          Direct          Direct       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0163 FAQ0167  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0162 FAQ0168  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0163 FAQ0168  English          Direct        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0183 FAQ0184   French        Scenario        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0175 FAQ0176   Arabic        Scenario        Scenario       1.000               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0172 FAQ0176   Arabic     Paraphrased        Scenario       1.000               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0172 FAQ0175   Arabic     Paraphrased        Scenario       1.000               هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0177 FAQ0178   French          Direct          Direct       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0169 FAQ0171   Arabic          Direct          Direct       1.000          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟              هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟
FAQ0167 FAQ0168  English        Scenario        Scenario       1.000           Can I request early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0189 FAQ0192  Russian     Paraphrased        Scenario       1.000          Можно ли получить ранний заезд в Nile Pearl Hotel?              Можно ли получить ранний заезд в Nile Pearl Hotel?
FAQ0186 FAQ0192  Russian          Direct        Scenario       1.000          Можно ли получить ранний заезд в Nile Pearl Hotel?              Можно ли получить ранний заезд в Nile Pearl Hotel?
FAQ0185 FAQ0187  Russian          Direct          Direct       1.000 Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?     Можно ли воспользоваться ранним заездом в Nile Pearl Hotel?
FAQ0186 FAQ0189  Russian          Direct     Paraphrased       1.000          Можно ли получить ранний заезд в Nile Pearl Hotel?              Можно ли получить ранний заезд в Nile Pearl Hotel?
FAQ0178 FAQ0179   French          Direct          Direct       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0177 FAQ0184   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0177 FAQ0183   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0181 FAQ0182   French     Paraphrased     Paraphrased       1.000 Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?     Peut-on demander un arrivée anticipée au Nile Pearl Hotel ?
FAQ0179 FAQ0184   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0179 FAQ0183   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0178 FAQ0184   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0178 FAQ0183   French          Direct        Scenario       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0177 FAQ0179   French          Direct          Direct       1.000 L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?     L'arrivée anticipée est-elle possible au Nile Pearl Hotel ?
FAQ0185 FAQ0191  Russian          Direct        Scenario       0.967 Можно ли воспользоваться ранним заездом в Nile Pearl Hotel? Можно ли мне воспользоваться ранним заездом в Nile Pearl Hotel?
FAQ0187 FAQ0191  Russian          Direct        Scenario       0.967 Можно ли воспользоваться ранним заездом в Nile Pearl Hotel? Можно ли мне воспользоваться ранним заездом в Nile Pearl Hotel?
FAQ0165 FAQ0166  English     Paraphrased     Paraphrased       0.925    Can I arrange for an early check-in at Nile Pearl Hotel?            Can I ask for an early check-in at Nile Pearl Hotel?
FAQ0163 FAQ0164  English          Direct     Paraphrased       0.905           Can I request early check-in at Nile Pearl Hotel?                Can I get an early check-in at Nile Pearl Hotel?
FAQ0162 FAQ0164  English          Direct     Paraphrased       0.905           Can I request early check-in at Nile Pearl Hotel?                Can I get an early check-in at Nile Pearl Hotel?
FAQ0164 FAQ0167  English     Paraphrased        Scenario       0.905            Can I get an early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0164 FAQ0168  English     Paraphrased        Scenario       0.905            Can I get an early check-in at Nile Pearl Hotel?               Can I request early check-in at Nile Pearl Hotel?
FAQ0161 FAQ0164  English          Direct     Paraphrased       0.905           Can I request early check-in at Nile Pearl Hotel?                Can I get an early check-in at Nile Pearl Hotel?
FAQ0169 FAQ0170   Arabic          Direct          Direct       0.903          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني التسجيل المبكر في Nile Pearl Hotel؟
FAQ0170 FAQ0171   Arabic          Direct          Direct       0.903               هل يمكنني التسجيل المبكر في Nile Pearl Hotel؟              هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟
FAQ0164 FAQ0165  English     Paraphrased     Paraphrased       0.902            Can I get an early check-in at Nile Pearl Hotel?        Can I arrange for an early check-in at Nile Pearl Hotel?
FAQ0164 FAQ0166  English     Paraphrased     Paraphrased       0.898            Can I get an early check-in at Nile Pearl Hotel?            Can I ask for an early check-in at Nile Pearl Hotel?
FAQ0173 FAQ0174   Arabic     Paraphrased     Paraphrased       0.893         هل يمكنني أن أدخل غرفتي مبكرًا في Nile Pearl Hotel؟          هل يمكنني الدخول إلى غرفتي مبكرًا في Nile Pearl Hotel؟
FAQ0171 FAQ0175   Arabic          Direct        Scenario       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0171 FAQ0172   Arabic          Direct     Paraphrased       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0169 FAQ0175   Arabic          Direct        Scenario       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0169 FAQ0172   Arabic          Direct     Paraphrased       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0171 FAQ0176   Arabic          Direct        Scenario       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟
FAQ0169 FAQ0176   Arabic          Direct        Scenario       0.882          هل يمكنني تسجيل الوصول مبكرًا في Nile Pearl Hotel؟                   هل يمكنني الوصول مبكرًا إلى Nile Pearl Hotel؟

================================================================================
DUPLICATE CHECK COMPLETE
================================================================================

In [43]:
# ============================================================
# INT006 - STRONG DIVERSITY PROMPT BUILDER
# ============================================================

def build_int006_diverse_prompt(row):
    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    ground_truth = str(row["ground_truth"]).strip()

    # Different instructions for each question type
    if question_type == "Direct":
        type_instruction = {
            "English": """
Ask directly whether early check-in is possible.
Use natural wording.
Do NOT use the same wording as other direct questions.
""",
            "Arabic": """
اسأل بشكل مباشر عما إذا كان تسجيل الوصول المبكر ممكنًا.
استخدم صياغة طبيعية ومختلفة.
لا تكرر نفس صياغة الأسئلة المباشرة الأخرى.
""",
            "French": """
Demandez directement si l'arrivée anticipée est possible.
Utilisez une formulation naturelle et différente.
Ne répétez pas la même formulation que les autres questions directes.
""",
            "Russian": """
Спросите прямо, возможен ли ранний заезд.
Используйте естественную и отличающуюся формулировку.
Не повторяйте формулировки других прямых вопросов.
"""
        }[language]

    elif question_type == "Paraphrased":
        type_instruction = {
            "English": """
Ask about the same early check-in intent using a clearly different
sentence structure and vocabulary.
Do not simply replace one verb with another.
""",
            "Arabic": """
اسأل عن نفس فكرة تسجيل الوصول المبكر ولكن باستخدام تركيب مختلف
لجملة السؤال وكلمات مختلفة بوضوح.
لا تستبدل كلمة واحدة فقط.
""",
            "French": """
Posez la même question sur l'arrivée anticipée avec une structure
et un vocabulaire clairement différents.
Ne remplacez pas seulement un seul mot.
""",
            "Russian": """
Сформулируйте тот же вопрос о раннем заезде с явно другой
структурой предложения и другими словами.
Не заменяйте только одно слово.
"""
        }[language]

    else:  # Scenario
        type_instruction = {
            "English": """
Create a realistic guest situation involving arriving earlier than
the normal check-in period.
The question must clearly describe the situation first and then ask
whether early check-in is possible.

Example style:
"I expect to arrive at the hotel earlier than planned; would it be possible to check in early?"
""",
            "Arabic": """
أنشئ موقفًا واقعيًا لنزيل سيصل إلى الفندق مبكرًا عن موعد تسجيل الوصول.
يجب أن يصف السؤال الموقف أولًا ثم يسأل بوضوح عن إمكانية تسجيل الوصول المبكر.

مثال:
"سأصل إلى الفندق في وقت مبكر عن الموعد المعتاد، فهل يمكنني تسجيل الوصول مبكرًا؟"
""",
            "French": """
Créez une situation réaliste dans laquelle le client arrive plus tôt
que prévu, puis demandez clairement s'il peut bénéficier d'une arrivée anticipée.

Exemple de style:
"Je prévois d'arriver plus tôt que prévu à l'hôtel ; pourrais-je effectuer une arrivée anticipée ?"
""",
            "Russian": """
Создайте реалистичную ситуацию, когда гость приезжает раньше
обычного времени заселения, а затем спрашивает о возможности
раннего заезда.

Пример:
"Я планирую приехать в отель раньше обычного времени; смогу ли я заселиться раньше?"
"""
        }[language]

    language_instruction = {
        "English": "Write entirely in English.",
        "Arabic": "اكتب السؤال بالكامل باللغة العربية.",
        "French": "Écrivez entièrement en français.",
        "Russian": "Напишите вопрос полностью на русском языке."
    }[language]

    question_mark = "؟" if language == "Arabic" else "?"

    prompt = f"""
You are generating ONE high-quality FAQ question for Nile Pearl Hotel.

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

CORE INTENT:
early_check_in

GROUND TRUTH:
{ground_truth}

============================================================
SEMANTIC REQUIREMENT
============================================================

The question MUST be specifically about EARLY CHECK-IN.

The guest wants to know whether they can arrive,
check in, or access their room earlier than the normal
check-in period.

DO NOT ask about:
- standard check-in time
- late check-out
- room availability in general
- hotel approval in general
- booking a room
- changing a reservation
- cancellation
- payment
- fees

DO NOT INVENT:
- a specific early check-in time
- a fee
- a guarantee
- any new hotel policy

============================================================
HOTEL NAME
============================================================

If the hotel name is used, it MUST be exactly:

Nile Pearl Hotel

Never translate or modify it.

============================================================
QUESTION TYPE
============================================================

{type_instruction}

============================================================
LANGUAGE
============================================================

{language_instruction}

============================================================
DIVERSITY REQUIREMENT
============================================================

This question belongs to a dataset containing other questions
about the SAME intent.

Therefore:

- Do NOT copy common templates.
- Do NOT repeatedly start with "Can I..."
- Do NOT repeatedly use "Is early check-in possible..."
- Do NOT produce a near-duplicate of another FAQ.
- Change the sentence structure.
- For Scenario questions, ALWAYS include a realistic situation.
- For Paraphrased questions, use a genuinely different structure.
- Keep the meaning exactly the same.

============================================================
OUTPUT RULES
============================================================

Return exactly ONE question.

The question must:
- be natural
- be concise
- contain one question only
- end with "{question_mark}"
- not contain explanations
- not contain labels
- not contain quotation marks
- not contain bullet points

Return ONLY the question.

Generate now.
"""

    return prompt


print("=" * 80)
print("INT006 DIVERSITY PROMPT BUILDER READY")
print("=" * 80)

# Test
test_row = int006_df.iloc[0]
test_prompt = build_int006_diverse_prompt(test_row)

print(test_prompt)

================================================================================
INT006 DIVERSITY PROMPT BUILDER READY
================================================================================

You are generating ONE high-quality FAQ question for Nile Pearl Hotel.

FAQ ID:
FAQ0161

Language:
English

Question type:
Direct

CORE INTENT:
early_check_in

GROUND TRUTH:
Early check-in is subject to room availability and hotel approval.

============================================================
SEMANTIC REQUIREMENT
============================================================

The question MUST be specifically about EARLY CHECK-IN.

The guest wants to know whether they can arrive,
check in, or access their room earlier than the normal
check-in period.

DO NOT ask about:
- standard check-in time
- late check-out
- room availability in general
- hotel approval in general
- booking a room
- changing a reservation
- cancellation
- payment
- fees

DO NOT INVENT:
- a specific early check-in time
- a fee
- a guarantee
- any new hotel policy

============================================================
HOTEL NAME
============================================================

If the hotel name is used, it MUST be exactly:

Nile Pearl Hotel

Never translate or modify it.

============================================================
QUESTION TYPE
============================================================


Ask directly whether early check-in is possible.
Use natural wording.
Do NOT use the same wording as other direct questions.


============================================================
LANGUAGE
============================================================

Write entirely in English.

============================================================
DIVERSITY REQUIREMENT
============================================================

This question belongs to a dataset containing other questions
about the SAME intent.

Therefore:

- Do NOT copy common templates.
- Do NOT repeatedly start with "Can I..."
- Do NOT repeatedly use "Is early check-in possible..."
- Do NOT produce a near-duplicate of another FAQ.
- Change the sentence structure.
- For Scenario questions, ALWAYS include a realistic situation.
- For Paraphrased questions, use a genuinely different structure.
- Keep the meaning exactly the same.

============================================================
OUTPUT RULES
============================================================

Return exactly ONE question.

The question must:
- be natural
- be concise
- contain one question only
- end with "?"
- not contain explanations
- not contain labels
- not contain quotation marks
- not contain bullet points

Return ONLY the question.

Generate now.

In [44]:
# ============================================================
# INT006 - DIVERSE GENERATION WITH DUPLICATE PREVENTION
# ============================================================

import pandas as pd
import re
import time


def normalize_question(text):
    """
    Normalize question for exact duplicate detection.
    """
    if text is None:
        return ""

    text = str(text).strip().lower()

    # Remove surrounding quotes
    text = text.strip('"').strip("'")

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    return text


def is_duplicate_question(question, previous_questions):
    """
    Check exact duplicates.
    """
    q_norm = normalize_question(question)

    if not q_norm:
        return True

    previous_normalized = {
        normalize_question(q)
        for q in previous_questions
        if str(q).strip()
    }

    return q_norm in previous_normalized


def generate_int006_diverse_question(
    row,
    previous_questions,
    max_attempts=5
):
    """
    Generate one question while avoiding previous duplicates.
    """

    for attempt in range(1, max_attempts + 1):

        prompt = build_int006_diverse_prompt(row)

        # Add previous questions to the prompt
        if previous_questions:

            previous_text = "\n".join(
                f"- {q}"
                for q in previous_questions[-15:]
            )

            prompt += f"""

============================================================
QUESTIONS ALREADY GENERATED
============================================================

The following questions already exist in the dataset.

You MUST NOT copy or closely reproduce them:

{previous_text}

Generate a NEW question with a clearly different structure.

============================================================
"""

        try:

            question = generate_ollama_question(prompt)

            if question is None:
                continue

            question = str(question).strip()

            # Clean possible model formatting
            question = question.strip('"').strip("'")
            question = re.sub(
                r"^(Question|Answer)\s*:\s*",
                "",
                question,
                flags=re.IGNORECASE
            ).strip()

            # Validate
            validation = validate_int006_question(
                question,
                row
            )

            if not validation.get("valid", False):
                print(
                    f"Attempt {attempt}: "
                    f"validation failed -> "
                    f"{validation.get('reason', 'Unknown')}"
                )
                continue

            # Duplicate check
            if is_duplicate_question(
                question,
                previous_questions
            ):
                print(
                    f"Attempt {attempt}: "
                    f"duplicate detected -> {question}"
                )
                continue

            return question

        except Exception as e:

            print(
                f"Attempt {attempt}: ERROR -> {e}"
            )

        time.sleep(0.5)

    return ""


print("=" * 80)
print("INT006 DIVERSE GENERATION FUNCTION READY")
print("=" * 80)

================================================================================
INT006 DIVERSE GENERATION FUNCTION READY
================================================================================

In [45]:
# ============================================================
# INT006 - FINAL DIVERSE GENERATION + STORAGE
# ============================================================

print("=" * 80)
print("INT006 FINAL DIVERSE GENERATION")
print("=" * 80)

# Fresh copy
int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == "INT006"
].copy()

# Reset question column
int006_df["question"] = ""

previous_questions = []

total = len(int006_df)

print(f"Total rows: {total}")
print("=" * 80)


for idx, row in int006_df.iterrows():

    position = len(previous_questions) + 1

    print("\n" + "-" * 80)
    print(
        f"{position}/{total} | "
        f"{row['faq_id']} | "
        f"{row['language']} | "
        f"{row['question_type']}"
    )

    question = generate_int006_diverse_question(
        row=row,
        previous_questions=previous_questions,
        max_attempts=7
    )

    if question:

        int006_df.at[idx, "question"] = question
        previous_questions.append(question)

        print(f"GENERATED: {question}")

    else:

        print("FAILED: Could not generate unique question")


# ============================================================
# STORAGE VALIDATION
# ============================================================

print("\n")
print("=" * 80)
print("INT006 STORAGE VALIDATION")
print("=" * 80)

non_empty = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

empty = total - non_empty

print(f"Rows: {len(int006_df)}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")

print("\nFirst questions:")
print(
    int006_df[
        ["faq_id", "language", "question_type", "question"]
    ].head(10).to_string(index=False)
)

print("\nQuestion dtype:")
print(int006_df["question"].dtype)

print("\nNaN count:")
print(int006_df["question"].isna().sum())


# ============================================================
# EXACT DUPLICATE CHECK
# ============================================================

normalized_questions = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .map(normalize_question)
)

duplicate_mask = normalized_questions.duplicated(
    keep=False
)

duplicate_count = duplicate_mask.sum()

print("\n")
print("=" * 80)
print("INT006 EXACT DUPLICATE CHECK")
print("=" * 80)

print(f"Total questions: {total}")
print(f"Exact duplicate rows: {duplicate_count}")

if duplicate_count == 0:

    print("✅ NO EXACT DUPLICATES FOUND")

else:

    print("⚠️ EXACT DUPLICATES FOUND")

    duplicates = int006_df[
        duplicate_mask
    ][
        ["faq_id", "language", "question_type", "question"]
    ].sort_values("question")

    print(
        duplicates.to_string(index=False)
    )


# ============================================================
# SAVE INT006
# ============================================================

output_path = (
    "03_Structured_Data/CSV/"
    "faq_INT006_final.csv"
)

int006_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n")
print("=" * 80)
print("INT006 SAVED")
print("=" * 80)

print(f"Path: {output_path}")
print(f"Rows saved: {len(int006_df)}")
print("✅ SAVE COMPLETE")

================================================================================
INT006 FINAL DIVERSE GENERATION
================================================================================
Total rows: 32
================================================================================

--------------------------------------------------------------------------------
1/32 | FAQ0161 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0162 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0163 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0164 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0165 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0166 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0167 | English | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0168 | English | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0169 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0170 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0171 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0172 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0173 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0174 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0175 | Arabic | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0176 | Arabic | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0177 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0178 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0179 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
1/32 | FAQ0180 | French | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 2 required positional arguments: 'question_type' and 'ground_truth'

KeyboardInterrupt:

In [ ]:
# ============================================================
# CHECK EXISTING FUNCTIONS - FIXED
# ============================================================

import inspect

print("=" * 80)
print("AVAILABLE FUNCTIONS")
print("=" * 80)

# IMPORTANT: copy globals first
global_items = list(globals().items())

found = []

for name, obj in global_items:

    if callable(obj) and not name.startswith("_"):

        try:
            source = inspect.getsource(obj)

            if (
                "ollama" in source.lower()
                or "prompt" in source.lower()
                or "question" in source.lower()
            ):
                found.append(name)

        except (OSError, TypeError, IOError):
            pass

for name in found:
    print(name)

print("\nTotal matching functions:", len(found))

print("=" * 80)

================================================================================
AVAILABLE FUNCTIONS
================================================================================
build_int005_prompt
validate_int005_question
regenerate_int005_question
test_ollama
build_int006_prompt
is_question
validate_int006_question
regenerate_int006_question
generate_ollama_question

Total matching functions: 9
================================================================================

In [46]:
# ============================================================
# INT006 - FIXED DIVERSE GENERATION + STORAGE
# ============================================================

import pandas as pd
import re
import time


def normalize_question(text):
    """Normalize question for exact duplicate detection."""

    if text is None:
        return ""

    text = str(text).strip().lower()

    # Remove quotes
    text = text.strip('"').strip("'")

    # Normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text


def is_duplicate_question(question, previous_questions):
    """Check whether question is an exact duplicate."""

    q_norm = normalize_question(question)

    if not q_norm:
        return True

    previous_normalized = {
        normalize_question(q)
        for q in previous_questions
        if str(q).strip()
    }

    return q_norm in previous_normalized


def generate_int006_diverse_question(
    row,
    previous_questions,
    max_attempts=7
):
    """
    Generate one valid and unique INT006 question.
    """

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]
    ground_truth = row["ground_truth"]

    for attempt in range(1, max_attempts + 1):

        try:

            # ------------------------------------------------
            # Build prompt
            # ------------------------------------------------

            prompt = build_int006_diverse_prompt(row)

            # ------------------------------------------------
            # Add already generated questions
            # ------------------------------------------------

            if previous_questions:

                previous_text = "\n".join(
                    f"- {q}"
                    for q in previous_questions[-15:]
                )

                prompt += f"""

============================================================
ALREADY GENERATED QUESTIONS
============================================================

DO NOT COPY OR REPEAT THESE QUESTIONS:

{previous_text}

Generate a NEW question with a different structure.

============================================================
"""

            # ------------------------------------------------
            # Generate
            # ------------------------------------------------

            question = generate_ollama_question(prompt)

            if question is None:
                print(
                    f"Attempt {attempt}: "
                    f"empty model response"
                )
                continue

            question = str(question).strip()

            # ------------------------------------------------
            # Clean response
            # ------------------------------------------------

            question = question.strip('"').strip("'")

            question = re.sub(
                r"^(Question|Answer)\s*:\s*",
                "",
                question,
                flags=re.IGNORECASE
            ).strip()

            # ------------------------------------------------
            # Validate
            # IMPORTANT:
            # validate_int006_question needs 3 arguments
            # ------------------------------------------------

            validation = validate_int006_question(
                question,
                question_type,
                ground_truth
            )

            # ------------------------------------------------
            # Handle validator result
            # ------------------------------------------------

            if isinstance(validation, dict):

                is_valid = validation.get(
                    "valid",
                    False
                )

                reason = validation.get(
                    "reason",
                    "Unknown"
                )

            else:

                is_valid = bool(validation)
                reason = "Valid" if is_valid else "Invalid"

            if not is_valid:

                print(
                    f"Attempt {attempt}: "
                    f"validation failed -> {reason}"
                )

                continue

            # ------------------------------------------------
            # Duplicate check
            # ------------------------------------------------

            if is_duplicate_question(
                question,
                previous_questions
            ):

                print(
                    f"Attempt {attempt}: "
                    f"duplicate -> {question}"
                )

                continue

            # ------------------------------------------------
            # SUCCESS
            # ------------------------------------------------

            return question

        except Exception as e:

            print(
                f"Attempt {attempt}: ERROR -> {e}"
            )

        time.sleep(0.5)

    return ""


# ============================================================
# LOAD INT006 FRESH
# ============================================================

print("=" * 80)
print("INT006 FINAL DIVERSE GENERATION - FIXED")
print("=" * 80)

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == "INT006"
].copy()

# Reset questions
int006_df["question"] = ""

previous_questions = []

total = len(int006_df)

print(f"Total rows: {total}")
print("=" * 80)


# ============================================================
# GENERATE
# ============================================================

for counter, (idx, row) in enumerate(
    int006_df.iterrows(),
    start=1
):

    print("\n" + "-" * 80)

    print(
        f"{counter}/{total} | "
        f"{row['faq_id']} | "
        f"{row['language']} | "
        f"{row['question_type']}"
    )

    question = generate_int006_diverse_question(
        row=row,
        previous_questions=previous_questions,
        max_attempts=7
    )

    if question:

        int006_df.at[idx, "question"] = question

        previous_questions.append(question)

        print(
            f"GENERATED: {question}"
        )

    else:

        print(
            "FAILED: Could not generate "
            "a valid unique question"
        )


# ============================================================
# STORAGE VALIDATION
# ============================================================

print("\n")
print("=" * 80)
print("INT006 STORAGE VALIDATION")
print("=" * 80)

non_empty = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

empty = total - non_empty

print(f"Rows: {total}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")

print("\nFirst 10 questions:")

print(
    int006_df[
        [
            "faq_id",
            "language",
            "question_type",
            "question"
        ]
    ]
    .head(10)
    .to_string(index=False)
)


# ============================================================
# EXACT DUPLICATE CHECK
# ============================================================

normalized_questions = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .map(normalize_question)
)

duplicate_mask = (
    normalized_questions
    .duplicated(keep=False)
)

duplicate_count = int(
    duplicate_mask.sum()
)

print("\n")
print("=" * 80)
print("INT006 EXACT DUPLICATE CHECK")
print("=" * 80)

print(f"Total questions: {total}")
print(
    f"Exact duplicate rows: {duplicate_count}"
)

if duplicate_count == 0:

    print("✅ NO EXACT DUPLICATES FOUND")

else:

    print("⚠️ EXACT DUPLICATES FOUND")

    duplicates = int006_df[
        duplicate_mask
    ][
        [
            "faq_id",
            "language",
            "question_type",
            "question"
        ]
    ].sort_values("question")

    print(
        duplicates.to_string(index=False)
    )


# ============================================================
# SAVE
# ============================================================

output_path = (
    "03_Structured_Data/CSV/"
    "faq_INT006_final.csv"
)

int006_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n")
print("=" * 80)
print("INT006 SAVED")
print("=" * 80)

print(f"Path: {output_path}")
print(f"Rows saved: {len(int006_df)}")
print("✅ SAVE COMPLETE")

================================================================================
INT006 FINAL DIVERSE GENERATION - FIXED
================================================================================
Total rows: 32
================================================================================

--------------------------------------------------------------------------------
1/32 | FAQ0161 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
2/32 | FAQ0162 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
3/32 | FAQ0163 | English | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
4/32 | FAQ0164 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
5/32 | FAQ0165 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
6/32 | FAQ0166 | English | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
7/32 | FAQ0167 | English | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
8/32 | FAQ0168 | English | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
9/32 | FAQ0169 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
10/32 | FAQ0170 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
11/32 | FAQ0171 | Arabic | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
12/32 | FAQ0172 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
13/32 | FAQ0173 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
14/32 | FAQ0174 | Arabic | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
15/32 | FAQ0175 | Arabic | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
16/32 | FAQ0176 | Arabic | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
17/32 | FAQ0177 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
18/32 | FAQ0178 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
19/32 | FAQ0179 | French | Direct
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
20/32 | FAQ0180 | French | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
21/32 | FAQ0181 | French | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
22/32 | FAQ0182 | French | Paraphrased
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 2: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 3: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 4: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 5: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 6: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
Attempt 7: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'
FAILED: Could not generate a valid unique question

--------------------------------------------------------------------------------
23/32 | FAQ0183 | French | Scenario
Attempt 1: ERROR -> validate_int006_question() missing 1 required positional argument: 'ground_truth'

In [47]:
# ============================================================
# INT006 - FINAL CLEAN GENERATION + VALIDATION + STORAGE
# ============================================================

import os
import re
import time
import pandas as pd

INTENT_ID = "INT006"
OUTPUT_PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

print("=" * 80)
print("INT006 FINAL CLEAN GENERATION")
print("=" * 80)

# ------------------------------------------------------------
# 1. LOAD INT006 DATA
# ------------------------------------------------------------

int006_df = faq_generation_plan[
    faq_generation_plan["intent_id"] == INTENT_ID
].copy()

int006_df = int006_df.reset_index(drop=True)

print(f"Total rows: {len(int006_df)}")
print(f"Languages: {int006_df['language'].value_counts().to_dict()}")
print(f"Question types: {int006_df['question_type'].value_counts().to_dict()}")

# ------------------------------------------------------------
# 2. CHECK REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = [
    "faq_id",
    "intent_id",
    "intent_name",
    "category",
    "language",
    "question_type",
    "difficulty",
    "question",
    "answer",
    "ground_truth",
    "source"
]

missing = [
    col for col in required_columns
    if col not in int006_df.columns
]

if missing:
    raise ValueError(f"Missing columns: {missing}")

# ------------------------------------------------------------
# 3. SAFE QUESTION CLEANER
# ------------------------------------------------------------

def clean_generated_question(question):
    if question is None:
        return ""

    question = str(question).strip()

    # Remove common model prefixes
    question = re.sub(
        r"^(question|answer)\s*:\s*",
        "",
        question,
        flags=re.IGNORECASE
    )

    # Remove quotation marks
    question = question.strip('"').strip("'").strip()

    # Remove accidental markdown
    question = question.replace("**", "")
    question = question.replace("```", "")

    # Normalize spaces
    question = re.sub(r"\s+", " ", question).strip()

    return question


# ------------------------------------------------------------
# 4. QUESTION TYPE SPECIFIC DIVERSITY INSTRUCTIONS
# ------------------------------------------------------------

def diversity_instruction(language, question_type, faq_id):

    if language == "English":

        if question_type == "Direct":
            variants = {
                "FAQ0161": "Use 'Is early check-in available'.",
                "FAQ0162": "Use 'Can guests check in early'.",
                "FAQ0163": "Use 'Does the hotel allow early check-in'."
            }
            return variants.get(
                faq_id,
                "Ask directly using different natural wording."
            )

        elif question_type == "Paraphrased":
            variants = {
                "FAQ0164": "Use 'arrange early arrival'.",
                "FAQ0165": "Use 'request an earlier check-in'.",
                "FAQ0166": "Use 'check in before the usual time'."
            }
            return variants.get(
                faq_id,
                "Paraphrase naturally."
            )

        else:
            variants = {
                "FAQ0167": "Start with 'If I arrive before my scheduled check-in...'.",
                "FAQ0168": "Use a different realistic early-arrival situation."
            }
            return variants.get(
                faq_id,
                "Create a realistic early-arrival situation."
            )

    elif language == "Arabic":

        if question_type == "Direct":
            variants = {
                "FAQ0169": "استخدم: هل يتوفر تسجيل الوصول المبكر؟",
                "FAQ0170": "استخدم: هل يُسمح بتسجيل الوصول المبكر؟",
                "FAQ0171": "استخدم: هل يمكن للضيوف تسجيل الوصول مبكرًا؟"
            }
            return variants.get(
                faq_id,
                "استخدم صياغة عربية مختلفة للسؤال عن تسجيل الوصول المبكر."
            )

        elif question_type == "Paraphrased":
            variants = {
                "FAQ0172": "اسأل عن إمكانية تسجيل الوصول قبل الموعد المعتاد.",
                "FAQ0173": "استخدم صياغة تتحدث عن الوصول قبل موعد تسجيل الدخول.",
                "FAQ0174": "اسأل بطريقة مختلفة عن الدخول إلى الغرفة مبكرًا."
            }
            return variants.get(
                faq_id,
                "أعد صياغة السؤال بشكل طبيعي."
            )

        else:
            variants = {
                "FAQ0175": "ابدأ بموقف ضيف يصل إلى الفندق قبل موعد تسجيل الوصول.",
                "FAQ0176": "استخدم موقفًا مختلفًا لضيف يصل مبكرًا."
            }
            return variants.get(
                faq_id,
                "اكتب موقفًا واقعيًا متعلقًا بالوصول المبكر."
            )

    elif language == "French":

        if question_type == "Direct":
            variants = {
                "FAQ0177": "Use 'Le check-in anticipé est-il disponible'.",
                "FAQ0178": "Use 'Peut-on faire une arrivée anticipée'.",
                "FAQ0179": "Use 'L'hôtel autorise-t-il l'arrivée anticipée'."
            }
            return variants.get(
                faq_id,
                "Ask directly using different French wording."
            )

        elif question_type == "Paraphrased":
            variants = {
                "FAQ0180": "Use 'arriver avant l'heure prévue'.",
                "FAQ0181": "Use 'demander un enregistrement anticipé'.",
                "FAQ0182": "Use another natural French paraphrase."
            }
            return variants.get(
                faq_id,
                "Paraphrase naturally in French."
            )

        else:
            variants = {
                "FAQ0183": "Create a situation where the guest arrives earlier than expected.",
                "FAQ0184": "Create a different early-arrival situation."
            }
            return variants.get(
                faq_id,
                "Create a realistic French scenario."
            )

    elif language == "Russian":

        if question_type == "Direct":
            variants = {
                "FAQ0185": "Спросите: доступна ли ранняя регистрация заезда.",
                "FAQ0186": "Спросите: разрешает ли отель ранний заезд.",
                "FAQ0187": "Спросите другим естественным способом о раннем заезде."
            }
            return variants.get(
                faq_id,
                "Сформулируйте прямой вопрос о раннем заезде."
            )

        elif question_type == "Paraphrased":
            variants = {
                "FAQ0188": "Используйте формулировку о возможности заселиться раньше.",
                "FAQ0189": "Спросите о возможности раннего заезда другими словами.",
                "FAQ0190": "Используйте формулировку о прибытии до обычного времени заезда."
            }
            return variants.get(
                faq_id,
                "Перефразируйте вопрос естественно."
            )

        else:
            variants = {
                "FAQ0191": "Создайте ситуацию, когда гость приезжает раньше времени заезда.",
                "FAQ0192": "Создайте другую реалистичную ситуацию раннего прибытия."
            }
            return variants.get(
                faq_id,
                "Создайте реалистичный сценарий."
            )

    return ""


# ------------------------------------------------------------
# 5. IMPROVED PROMPT BUILDER
# ------------------------------------------------------------

def build_int006_diverse_prompt(row, previous_questions):

    faq_id = str(row["faq_id"])
    language = str(row["language"])
    question_type = str(row["question_type"])
    ground_truth = str(row["ground_truth"])

    diversity = diversity_instruction(
        language,
        question_type,
        faq_id
    )

    previous_text = "\n".join(
        f"- {q}"
        for q in previous_questions[-15:]
    )

    if language == "Arabic":
        question_mark = "؟"
        language_rule = """
اكتب السؤال باللغة العربية فقط.
يسمح بكتابة اسم الفندق Nile Pearl Hotel كما هو.
يجب أن ينتهي السؤال بعلامة الاستفهام العربية ؟
"""

    elif language == "French":
        question_mark = "?"
        language_rule = """
Write entirely in French.
The hotel name must remain exactly Nile Pearl Hotel.
End with ?.
"""

    elif language == "Russian":
        question_mark = "?"
        language_rule = """
Write entirely in Russian.
The hotel name must remain exactly Nile Pearl Hotel.
End with ?.
"""

    else:
        question_mark = "?"
        language_rule = """
Write entirely in English.
The hotel name must remain exactly Nile Pearl Hotel.
End with ?.
"""

    prompt = f"""
You are generating ONE high-quality FAQ question
for the Nile Pearl Hotel multilingual hotel AI dataset.

FAQ ID:
{faq_id}

Language:
{language}

Question type:
{question_type}

Core intent:
early_check_in

Ground truth:
{ground_truth}

IMPORTANT:
The question MUST be specifically about EARLY CHECK-IN.

It means the guest wants to know whether they can
arrive, check in, or access the room before the normal
check-in time.

DO NOT ask about:
- standard check-in time
- late check-out
- general room availability
- hotel approval in general
- booking a room
- cancellation
- payment
- fees

DO NOT invent:
- a specific time
- a fee
- a guarantee
- a new policy

HOTEL NAME:
If mentioned, write EXACTLY:
Nile Pearl Hotel

Never translate or modify the hotel name.

QUESTION TYPE:
{question_type}

DIVERSITY REQUIREMENT:
{diversity}

VERY IMPORTANT:
The question MUST be meaningfully different from previous questions.

Previous generated questions:
{previous_text if previous_text else "None"}

{language_rule}

Return ONLY ONE question.
No explanation.
No label.
No quotation marks.
No bullet points.
No "Question:".

Generate now.
"""

    return prompt


# ------------------------------------------------------------
# 6. LOCAL VALIDATOR
# ------------------------------------------------------------

def validate_int006_final_question(
    question,
    language,
    question_type,
    ground_truth
):

    if not question:
        return False, "Empty question"

    q = question.strip()

    # Must be one line
    if "\n" in q:
        return False, "Multiple lines"

    # No labels
    if re.match(r"^(question|answer)\s*:", q, re.I):
        return False, "Contains label"

    # Hotel name consistency
    bad_hotel_names = [
        "Нил Пирл",
        "Нил Перило",
        "Нильский Бриллиант",
        "Nile Перило",
        "_hotel_name_",
        "hôtel Nile Pearl"
    ]

    for bad_name in bad_hotel_names:
        if bad_name.lower() in q.lower():
            return False, "Invalid hotel name"

    # Language-specific question mark
    if language == "Arabic":
        if not q.endswith("؟"):
            return False, "Arabic question must end with ؟"
    else:
        if not q.endswith("?"):
            return False, "Question must end with ?"

    # Basic early check-in semantic validation
    lower_q = q.lower()

    if language == "English":
        keywords = [
            "early check-in",
            "early check in",
            "check in early",
            "arrive early",
            "earlier check-in",
            "earlier check in"
        ]

    elif language == "Arabic":
        keywords = [
            "تسجيل الوصول المبكر",
            "التسجيل المبكر",
            "تسجيل الدخول مبكر",
            "الوصول مبكر",
            "الدخول مبكر"
        ]

    elif language == "French":
        keywords = [
            "arrivée anticipée",
            "arrivée précoce",
            "check-in anticipé",
            "arriver plus tôt",
            "enregistrement anticipé"
        ]

    else:
        keywords = [
            "ранн",
            "заезд",
            "засел",
            "ранний заезд"
        ]

    if not any(k.lower() in lower_q for k in keywords):
        return False, "Not clearly about early check-in"

    # Prevent unrelated topics
    forbidden_patterns = [
        "late check-out",
        "late checkout",
        "standard check-in time",
        "check-out time",
        "cancellation",
        "payment",
        "fee",
        "price"
    ]

    if language == "English":
        for word in forbidden_patterns:
            if word in lower_q:
                return False, f"Contains unrelated topic: {word}"

    # Must not be absurdly long
    if len(q) > 220:
        return False, "Question too long"

    return True, "Valid"


# ------------------------------------------------------------
# 7. GENERATION FUNCTION
# ------------------------------------------------------------

def generate_unique_int006_question(
    row,
    previous_questions,
    max_attempts=7
):

    faq_id = str(row["faq_id"])
    language = str(row["language"])
    question_type = str(row["question_type"])
    ground_truth = str(row["ground_truth"])

    for attempt in range(1, max_attempts + 1):

        try:

            prompt = build_int006_diverse_prompt(
                row,
                previous_questions
            )

            raw_question = generate_ollama_question(prompt)

            question = clean_generated_question(raw_question)

            valid, reason = validate_int006_final_question(
                question,
                language,
                question_type,
                ground_truth
            )

            if not valid:
                print(
                    f"Attempt {attempt}: INVALID -> {reason}"
                )
                continue

            # Exact duplicate check
            if question in previous_questions:
                print(
                    f"Attempt {attempt}: DUPLICATE -> retry"
                )
                continue

            # Similarity check
            is_similar = False

            for old_q in previous_questions:

                try:
                    sim = similarity(
                        question,
                        old_q
                    )

                    if sim >= 0.90:
                        is_similar = True
                        break

                except Exception:
                    pass

            if is_similar:
                print(
                    f"Attempt {attempt}: TOO SIMILAR -> retry"
                )
                continue

            return question, True, "Valid"

        except Exception as e:

            print(
                f"Attempt {attempt}: ERROR -> {e}"
            )

    return "", False, "Could not generate unique question"


# ------------------------------------------------------------
# 8. GENERATE ALL QUESTIONS
# ------------------------------------------------------------

previous_questions = []

generated_questions = []

print("\n" + "=" * 80)
print("GENERATING INT006 QUESTIONS")
print("=" * 80)

for idx, row in int006_df.iterrows():

    faq_id = row["faq_id"]
    language = row["language"]
    question_type = row["question_type"]

    print("\n" + "-" * 80)
    print(
        f"{idx + 1}/{len(int006_df)} | "
        f"{faq_id} | {language} | {question_type}"
    )

    question, success, reason = generate_unique_int006_question(
        row,
        previous_questions,
        max_attempts=7
    )

    if success:

        print(f"GENERATED: {question}")

        previous_questions.append(question)
        generated_questions.append(question)

    else:

        print(f"FAILED: {reason}")

        generated_questions.append("")


# ------------------------------------------------------------
# 9. STORE QUESTIONS
# ------------------------------------------------------------

int006_df["question"] = generated_questions


# ------------------------------------------------------------
# 10. STORAGE VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INT006 STORAGE VALIDATION")
print("=" * 80)

non_empty = (
    int006_df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

empty = len(int006_df) - non_empty

print(f"Rows: {len(int006_df)}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")


# ------------------------------------------------------------
# 11. EXACT DUPLICATE CHECK
# ------------------------------------------------------------

duplicate_mask = (
    int006_df["question"]
    .duplicated(keep=False)
    &
    int006_df["question"].ne("")
)

duplicate_rows = int006_df[duplicate_mask]

print("\n" + "=" * 80)
print("EXACT DUPLICATE CHECK")
print("=" * 80)

print(f"Exact duplicate rows: {len(duplicate_rows)}")

if len(duplicate_rows) > 0:

    print("⚠️ DUPLICATES FOUND")

    print(
        duplicate_rows[
            ["faq_id", "language", "question_type", "question"]
        ].to_string(index=False)
    )

else:

    print("✅ NO EXACT DUPLICATES")


# ------------------------------------------------------------
# 12. SAVE
# ------------------------------------------------------------

os.makedirs(
    os.path.dirname(OUTPUT_PATH),
    exist_ok=True
)

int006_df.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 80)
print("INT006 SAVE")
print("=" * 80)

print(f"Path: {OUTPUT_PATH}")
print(f"Rows saved: {len(int006_df)}")

print("\n" + "=" * 80)
print("FINAL SAMPLE")
print("=" * 80)

print(
    int006_df[
        ["faq_id", "language", "question_type", "question"]
    ].to_string(index=False)
)

print("\n" + "=" * 80)
print("✅ INT006 PROCESS COMPLETE")
print("=" * 80)

================================================================================
INT006 FINAL CLEAN GENERATION
================================================================================
Total rows: 32
Languages: {'English': 8, 'Arabic': 8, 'French': 8, 'Russian': 8}
Question types: {'Direct': 12, 'Paraphrased': 12, 'Scenario': 8}

================================================================================
GENERATING INT006 QUESTIONS
================================================================================

--------------------------------------------------------------------------------
1/32 | FAQ0161 | English | Direct
GENERATED: Is early check-in available at Nile Pearl Hotel?

--------------------------------------------------------------------------------
2/32 | FAQ0162 | English | Direct
GENERATED: Can guests check in early at Nile Pearl Hotel?

--------------------------------------------------------------------------------
3/32 | FAQ0163 | English | Direct
GENERATED: Does the hotel allow early check-in?

--------------------------------------------------------------------------------
4/32 | FAQ0164 | English | Paraphrased
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
Attempt 3: INVALID -> Not clearly about early check-in
Attempt 4: INVALID -> Not clearly about early check-in
Attempt 5: INVALID -> Not clearly about early check-in
Attempt 6: INVALID -> Not clearly about early check-in
Attempt 7: INVALID -> Not clearly about early check-in
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
5/32 | FAQ0165 | English | Paraphrased
GENERATED: Could I request an earlier check-in at Nile Pearl Hotel?

--------------------------------------------------------------------------------
6/32 | FAQ0166 | English | Paraphrased
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
Attempt 3: INVALID -> Not clearly about early check-in
Attempt 4: INVALID -> Not clearly about early check-in
Attempt 5: INVALID -> Not clearly about early check-in
Attempt 6: INVALID -> Not clearly about early check-in
Attempt 7: INVALID -> Not clearly about early check-in
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
7/32 | FAQ0167 | English | Scenario
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
Attempt 3: INVALID -> Not clearly about early check-in
Attempt 4: INVALID -> Not clearly about early check-in
Attempt 5: INVALID -> Not clearly about early check-in
Attempt 6: INVALID -> Not clearly about early check-in
Attempt 7: INVALID -> Not clearly about early check-in
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
8/32 | FAQ0168 | English | Scenario
Attempt 1: INVALID -> Not clearly about early check-in
GENERATED: If I book a room at Nile Pearl Hotel and need to arrive early, would it be possible to have early check-in?

--------------------------------------------------------------------------------
9/32 | FAQ0169 | Arabic | Direct
GENERATED: هل يمكنني تسجيل الوصول المبكر في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
10/32 | FAQ0170 | Arabic | Direct
GENERATED: هل يُسمح بتسجيل الوصول المبكر في Nile Pearl Hotel؟

--------------------------------------------------------------------------------
11/32 | FAQ0171 | Arabic | Direct
GENERATED: هل يمكن للضيوف في Nile Pearl Hotel تسجيل الوصول مبكرًا؟؟

--------------------------------------------------------------------------------
12/32 | FAQ0172 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟

--------------------------------------------------------------------------------
13/32 | FAQ0173 | Arabic | Paraphrased
GENERATED: هل يمكنني الوصول إلى الفندق وتسجيل الوصول مبكرًا قبل الوقت المعتاد في Nile Pearl Hotel؟؟

--------------------------------------------------------------------------------
14/32 | FAQ0174 | Arabic | Paraphrased
GENERATED: هل يمكنني الاستفسار عن إمكانية تسجيل الوصول المبكر في Nile Pearl Hotel؟؟

--------------------------------------------------------------------------------
15/32 | FAQ0175 | Arabic | Scenario
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
GENERATED: كيف يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟

--------------------------------------------------------------------------------
16/32 | FAQ0176 | Arabic | Scenario
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
GENERATED: هل يمكنني الوصول إلى Nile Pearl Hotel قبل الوقت المعتاد وتحديدًا في الساعة العاشرة صباحاً وتسجيل الوصول مبكرًا؟؟

--------------------------------------------------------------------------------
17/32 | FAQ0177 | French | Direct
Attempt 1: INVALID -> Invalid hotel name
Attempt 2: INVALID -> Not clearly about early check-in
GENERATED: Le check-in anticipé est-il disponible au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
18/32 | FAQ0178 | French | Direct
GENERATED: Peut-on faire une arrivée anticipée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
19/32 | FAQ0179 | French | Direct
Attempt 1: INVALID -> Invalid hotel name
GENERATED: L'hôtel autorise-t-il l'arrivée anticipée ?

--------------------------------------------------------------------------------
20/32 | FAQ0180 | French | Paraphrased
Attempt 1: INVALID -> Invalid hotel name
Attempt 2: INVALID -> Not clearly about early check-in
Attempt 3: INVALID -> Not clearly about early check-in
Attempt 4: INVALID -> Not clearly about early check-in
Attempt 5: INVALID -> Invalid hotel name
Attempt 6: INVALID -> Invalid hotel name
Attempt 7: INVALID -> Not clearly about early check-in
FAILED: Could not generate unique question

--------------------------------------------------------------------------------
21/32 | FAQ0181 | French | Paraphrased
Attempt 1: INVALID -> Invalid hotel name
GENERATED: Est-il possible de demander un enregistrement anticipé au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
22/32 | FAQ0182 | French | Paraphrased
Attempt 1: INVALID -> Not clearly about early check-in
Attempt 2: INVALID -> Not clearly about early check-in
Attempt 3: INVALID -> Not clearly about early check-in
Attempt 4: INVALID -> Invalid hotel name
GENERATED: Est-il possible d'obtenir l'autorisation pour un check-in anticipé au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
23/32 | FAQ0183 | French | Scenario
Attempt 1: INVALID -> Invalid hotel name
Attempt 2: INVALID -> Invalid hotel name
GENERATED: Si je dois arriver tôt à l'aube sans avoir réservé à l'avance, peut-on faire une arrivée anticipée au Nile Pearl Hotel ?

--------------------------------------------------------------------------------
24/32 | FAQ0184 | French | Scenario
GENERATED: Si je dois arriver tôt en raison d'un vol matinal, est-il possible d'avoir une arrivée anticipée à l'Nile Pearl Hotel ?

--------------------------------------------------------------------------------
25/32 | FAQ0185 | Russian | Direct
GENERATED: Доступна ли ранняя регистрация заезда в Nile Pearl Hotel?

--------------------------------------------------------------------------------
26/32 | FAQ0186 | Russian | Direct
GENERATED: Разрешает ли отель Nile Pearl Hotel ранний заезд?

--------------------------------------------------------------------------------
27/32 | FAQ0187 | Russian | Direct
GENERATED: Могу ли я заранее прибыть в Nile Pearl Hotel и провести регистрацию заезда до обычного времени?

--------------------------------------------------------------------------------
28/32 | FAQ0188 | Russian | Paraphrased
Attempt 1: INVALID -> Not clearly about early check-in
GENERATED: Могу ли я заранее приехать в Nile Pearl Hotel и забронировать номер до времени обычного заезда?

--------------------------------------------------------------------------------
29/32 | FAQ0189 | Russian | Paraphrased
GENERATED: Могу ли я прибыть и зарегистрироваться заезда заранее в Nile Pearl Hotel?

--------------------------------------------------------------------------------
30/32 | FAQ0190 | Russian | Paraphrased
Attempt 1: DUPLICATE -> retry
Attempt 2: INVALID -> Question must end with ?
Attempt 3: INVALID -> Question must end with ?
GENERATED: Могу ли я прибыть заранее и зарегистрироваться заезда в Nile Pearl Hotel до обычного времени заезда?

--------------------------------------------------------------------------------
31/32 | FAQ0191 | Russian | Scenario
GENERATED: Если я приеду раньше времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?

--------------------------------------------------------------------------------
32/32 | FAQ0192 | Russian | Scenario
GENERATED: Если я приеду на несколько часов раньше обычного времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?

================================================================================
INT006 STORAGE VALIDATION
================================================================================
Rows: 32
Non-empty questions: 28
Empty questions: 4

================================================================================
EXACT DUPLICATE CHECK
================================================================================
Exact duplicate rows: 0
✅ NO EXACT DUPLICATES

================================================================================
INT006 SAVE
================================================================================
Path: 03_Structured_Data/CSV/faq_INT006_final.csv
Rows saved: 32

================================================================================
FINAL SAMPLE
================================================================================
 faq_id language question_type                                                                                                                          question
FAQ0161  English        Direct                                                                                  Is early check-in available at Nile Pearl Hotel?
FAQ0162  English        Direct                                                                                    Can guests check in early at Nile Pearl Hotel?
FAQ0163  English        Direct                                                                                              Does the hotel allow early check-in?
FAQ0164  English   Paraphrased
FAQ0165  English   Paraphrased                                                                          Could I request an earlier check-in at Nile Pearl Hotel?
FAQ0166  English   Paraphrased
FAQ0167  English      Scenario
FAQ0168  English      Scenario                       If I book a room at Nile Pearl Hotel and need to arrive early, would it be possible to have early check-in?
FAQ0169   Arabic        Direct                                                                                هل يمكنني تسجيل الوصول المبكر في Nile Pearl Hotel؟
FAQ0170   Arabic        Direct                                                                                هل يُسمح بتسجيل الوصول المبكر في Nile Pearl Hotel؟
FAQ0171   Arabic        Direct                                                                          هل يمكن للضيوف في Nile Pearl Hotel تسجيل الوصول مبكرًا؟؟
FAQ0172   Arabic   Paraphrased                                          هل يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟
FAQ0173   Arabic   Paraphrased                                          هل يمكنني الوصول إلى الفندق وتسجيل الوصول مبكرًا قبل الوقت المعتاد في Nile Pearl Hotel؟؟
FAQ0174   Arabic   Paraphrased                                                          هل يمكنني الاستفسار عن إمكانية تسجيل الوصول المبكر في Nile Pearl Hotel؟؟
FAQ0175   Arabic      Scenario                                         كيف يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟
FAQ0176   Arabic      Scenario                  هل يمكنني الوصول إلى Nile Pearl Hotel قبل الوقت المعتاد وتحديدًا في الساعة العاشرة صباحاً وتسجيل الوصول مبكرًا؟؟
FAQ0177   French        Direct                                                                      Le check-in anticipé est-il disponible au Nile Pearl Hotel ?
FAQ0178   French        Direct                                                                         Peut-on faire une arrivée anticipée au Nile Pearl Hotel ?
FAQ0179   French        Direct                                                                                       L'hôtel autorise-t-il l'arrivée anticipée ?
FAQ0180   French   Paraphrased
FAQ0181   French   Paraphrased                                                      Est-il possible de demander un enregistrement anticipé au Nile Pearl Hotel ?
FAQ0182   French   Paraphrased                                          Est-il possible d'obtenir l'autorisation pour un check-in anticipé au Nile Pearl Hotel ?
FAQ0183   French      Scenario          Si je dois arriver tôt à l'aube sans avoir réservé à l'avance, peut-on faire une arrivée anticipée au Nile Pearl Hotel ?
FAQ0184   French      Scenario           Si je dois arriver tôt en raison d'un vol matinal, est-il possible d'avoir une arrivée anticipée à l'Nile Pearl Hotel ?
FAQ0185  Russian        Direct                                                                         Доступна ли ранняя регистрация заезда в Nile Pearl Hotel?
FAQ0186  Russian        Direct                                                                                 Разрешает ли отель Nile Pearl Hotel ранний заезд?
FAQ0187  Russian        Direct                                   Могу ли я заранее прибыть в Nile Pearl Hotel и провести регистрацию заезда до обычного времени?
FAQ0188  Russian   Paraphrased                                   Могу ли я заранее приехать в Nile Pearl Hotel и забронировать номер до времени обычного заезда?
FAQ0189  Russian   Paraphrased                                                         Могу ли я прибыть и зарегистрироваться заезда заранее в Nile Pearl Hotel?
FAQ0190  Russian   Paraphrased                              Могу ли я прибыть заранее и зарегистрироваться заезда в Nile Pearl Hotel до обычного времени заезда?
FAQ0191  Russian      Scenario                             Если я приеду раньше времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?
FAQ0192  Russian      Scenario Если я приеду на несколько часов раньше обычного времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?

================================================================================
✅ INT006 PROCESS COMPLETE
================================================================================

In [48]:
# ============================================================
# INT006 - REGENERATE EMPTY QUESTIONS ONLY
# ============================================================

import pandas as pd

print("=" * 80)
print("INT006 REGENERATE EMPTY QUESTIONS")
print("=" * 80)

# Load current dataset
int006_path = "03_Structured_Data/CSV/faq_INT006_final.csv"
int006_df = pd.read_csv(int006_path)

# Find empty questions
empty_mask = (
    int006_df["question"].isna() |
    (int006_df["question"].astype(str).str.strip() == "")
)

empty_rows = int006_df[empty_mask].copy()

print(f"Total rows: {len(int006_df)}")
print(f"Empty questions: {len(empty_rows)}")
print()

if len(empty_rows) == 0:
    print("✅ No empty questions found.")
else:

    print("Questions to regenerate:")
    print(empty_rows[["faq_id", "language", "question_type"]].to_string(index=False))
    print()

    # --------------------------------------------------------
    # Targeted generation instructions
    # --------------------------------------------------------

    regeneration_prompts = {

        "FAQ0164": """
Generate ONE English paraphrased question about EARLY CHECK-IN
at Nile Pearl Hotel.

Do NOT repeat the wording:
"Is early check-in available at Nile Pearl Hotel?"

Use different wording but keep the exact same intent.

Return ONLY the question.
""",

        "FAQ0166": """
Generate ONE English paraphrased question about EARLY CHECK-IN
at Nile Pearl Hotel.

Use natural English and clearly ask whether the guest can request
or receive early check-in.

Do NOT repeat existing wording.

Return ONLY the question.
""",

        "FAQ0167": """
Generate ONE English SCENARIO question about EARLY CHECK-IN
at Nile Pearl Hotel.

The question must describe a realistic guest situation, such as
arriving before the normal check-in time.

It must clearly ask about early check-in.

Return ONLY the question.
""",

        "FAQ0180": """
Generate ONE natural French paraphrased question about
EARLY CHECK-IN at Nile Pearl Hotel.

Use correct French grammar.

Do NOT use:
"L'hôtel autorise-t-il l'arrivée anticipée ?"

The question must clearly be about requesting or getting
an early check-in.

Return ONLY the question.
"""
    }

    for idx in empty_rows.index:

        faq_id = int006_df.loc[idx, "faq_id"]
        language = int006_df.loc[idx, "language"]
        question_type = int006_df.loc[idx, "question_type"]

        print("-" * 80)
        print(f"{faq_id} | {language} | {question_type}")

        prompt = regeneration_prompts.get(faq_id)

        if prompt is None:
            print("❌ No regeneration prompt found")
            continue

        generated_question = None

        for attempt in range(1, 8):

            try:

                response = generate_ollama_question(prompt)

                if response is None:
                    print(f"Attempt {attempt}: EMPTY RESPONSE")
                    continue

                question = str(response).strip()

                # Remove accidental quotes
                question = question.strip('"').strip("'").strip()

                # Basic cleanup
                question = question.replace("؟؟", "؟")

                if not question:
                    print(f"Attempt {attempt}: EMPTY")
                    continue

                # Make sure it is a question
                if not question.endswith(("?", "؟")):
                    question += "?"

                # Basic language/intent validation
                if faq_id == "FAQ0164":
                    valid = (
                        "early check-in" in question.lower()
                        and "nile pearl hotel" in question.lower()
                    )

                elif faq_id == "FAQ0166":
                    valid = (
                        "check-in" in question.lower()
                        and "early" in question.lower()
                        and "nile pearl hotel" in question.lower()
                    )

                elif faq_id == "FAQ0167":
                    q = question.lower()

                    valid = (
                        "nile pearl hotel" in q
                        and (
                            "early check-in" in q
                            or "check in early" in q
                            or "check-in early" in q
                        )
                    )

                elif faq_id == "FAQ0180":
                    q = question.lower()

                    valid = (
                        "nile pearl hotel" in q
                        and (
                            "anticip" in q
                            or "check-in" in q
                            or "enregistrement" in q
                        )
                    )

                else:
                    valid = True

                if not valid:
                    print(f"Attempt {attempt}: INVALID -> intent/hotel check failed")
                    continue

                # Check against existing questions
                existing_questions = (
                    int006_df["question"]
                    .fillna("")
                    .astype(str)
                    .str.strip()
                )

                if question in existing_questions.values:
                    print(f"Attempt {attempt}: DUPLICATE -> retry")
                    continue

                generated_question = question
                print(f"GENERATED: {generated_question}")
                break

            except Exception as e:
                print(f"Attempt {attempt}: ERROR -> {e}")

        if generated_question:
            int006_df.loc[idx, "question"] = generated_question
        else:
            print("❌ FAILED")

# ============================================================
# SAVE
# ============================================================

int006_df.to_csv(
    int006_path,
    index=False,
    encoding="utf-8-sig"
)

print()
print("=" * 80)
print("STORAGE VALIDATION")
print("=" * 80)

non_empty = (
    int006_df["question"].notna()
    & (int006_df["question"].astype(str).str.strip() != "")
).sum()

empty = len(int006_df) - non_empty

print(f"Rows: {len(int006_df)}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")

if empty == 0:
    print("✅ ALL 32 QUESTIONS ARE STORED")
else:
    print("⚠️ SOME QUESTIONS ARE STILL EMPTY")

print("=" * 80)

================================================================================
INT006 REGENERATE EMPTY QUESTIONS
================================================================================
Total rows: 32
Empty questions: 4

Questions to regenerate:
 faq_id language question_type
FAQ0164  English   Paraphrased
FAQ0166  English   Paraphrased
FAQ0167  English      Scenario
FAQ0180   French   Paraphrased

--------------------------------------------------------------------------------
FAQ0164 | English | Paraphrased
GENERATED: Can I arrange an early check-in at Nile Pearl Hotel?
--------------------------------------------------------------------------------
FAQ0166 | English | Paraphrased
GENERATED: Can I request an early check-in at the Nile Pearl Hotel?
--------------------------------------------------------------------------------
FAQ0167 | English | Scenario
GENERATED: What should a guest do if they arrive at Nile Pearl Hotel before the normal check-in time and need early check-in arrangements?
--------------------------------------------------------------------------------
FAQ0180 | French | Paraphrased
GENERATED: Peut-on bénéficier d'une arrivée anticipée au Nile Pearl Hotel ?

================================================================================
STORAGE VALIDATION
================================================================================
Rows: 32
Non-empty questions: 32
Empty questions: 0
✅ ALL 32 QUESTIONS ARE STORED
================================================================================

In [49]:
# ============================================================
# INT006 FINAL QUALITY AUDIT
# ============================================================

import pandas as pd
from difflib import SequenceMatcher
import re

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

print("=" * 80)
print("INT006 FINAL QUALITY AUDIT")
print("=" * 80)

# ------------------------------------------------------------
# 1. BASIC VALIDATION
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("1. BASIC VALIDATION")
print("-" * 80)

print(f"Total rows: {len(df)}")

empty_mask = (
    df["question"].isna()
    | (df["question"].astype(str).str.strip() == "")
)

print(f"Non-empty questions: {(~empty_mask).sum()}")
print(f"Empty questions: {empty_mask.sum()}")

print("\nLanguages:")
print(df["language"].value_counts().to_dict())

print("\nQuestion types:")
print(df["question_type"].value_counts().to_dict())


# ------------------------------------------------------------
# 2. EXACT DUPLICATES
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("2. EXACT DUPLICATE CHECK")
print("-" * 80)

questions = df["question"].fillna("").astype(str).str.strip()

duplicate_mask = questions.duplicated(keep=False)

exact_duplicates = df[duplicate_mask].copy()

print(f"Exact duplicate rows: {len(exact_duplicates)}")

if len(exact_duplicates) == 0:
    print("✅ NO EXACT DUPLICATES")
else:
    print("⚠️ EXACT DUPLICATES FOUND")
    print(
        exact_duplicates[
            ["faq_id", "language", "question_type", "question"]
        ].to_string(index=False)
    )


# ------------------------------------------------------------
# 3. SIMILARITY CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("3. SIMILARITY CHECK")
print("-" * 80)

def normalize_question(text):
    text = str(text).lower().strip()

    # Remove punctuation
    text = re.sub(r"[?!؟.,:;\"'«»()]", " ", text)

    # Normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text


similar_pairs = []

for i in range(len(df)):
    q1 = normalize_question(df.iloc[i]["question"])

    if not q1:
        continue

    for j in range(i + 1, len(df)):
        q2 = normalize_question(df.iloc[j]["question"])

        if not q2:
            continue

        # Compare only same language
        if df.iloc[i]["language"] != df.iloc[j]["language"]:
            continue

        similarity = SequenceMatcher(None, q1, q2).ratio()

        if similarity >= 0.85:
            similar_pairs.append({
                "faq_1": df.iloc[i]["faq_id"],
                "faq_2": df.iloc[j]["faq_id"],
                "language": df.iloc[i]["language"],
                "type_1": df.iloc[i]["question_type"],
                "type_2": df.iloc[j]["question_type"],
                "similarity": round(similarity, 3),
                "question_1": df.iloc[i]["question"],
                "question_2": df.iloc[j]["question"],
            })

similar_df = pd.DataFrame(similar_pairs)

print(f"Potential similar pairs: {len(similar_df)}")

if len(similar_df) > 0:
    print("\nTop similar pairs:")

    print(
        similar_df
        .sort_values("similarity", ascending=False)
        .head(30)
        .to_string(index=False)
    )
else:
    print("✅ NO HIGH-SIMILARITY PAIRS")


# ------------------------------------------------------------
# 4. INTENT CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("4. EARLY CHECK-IN INTENT CHECK")
print("-" * 80)

def has_early_checkin_intent(question, language):

    q = str(question).lower()

    if language == "English":
        keywords = [
            "early check-in",
            "early check in",
            "check in early",
            "check-in early",
            "earlier check-in",
        ]

    elif language == "Arabic":
        keywords = [
            "تسجيل الوصول المبكر",
            "تسجيل الوصول مبكر",
            "تسجيل مبكر",
            "الوصول مبكر",
            "الدخول مبكر",
        ]

    elif language == "French":
        keywords = [
            "arrivée anticipée",
            "enregistrement anticipé",
            "check-in anticipé",
            "check in anticipé",
        ]

    elif language == "Russian":
        keywords = [
            "ранн",
            "заранее",
            "до обычного времени",
        ]

    else:
        keywords = []

    return any(keyword in q for keyword in keywords)


intent_failures = []

for idx, row in df.iterrows():

    question = str(row["question"]).strip()

    if not question:
        continue

    if not has_early_checkin_intent(
        question,
        row["language"]
    ):
        intent_failures.append({
            "faq_id": row["faq_id"],
            "language": row["language"],
            "question_type": row["question_type"],
            "question": question,
        })

print(f"Intent failures: {len(intent_failures)}")

if len(intent_failures) == 0:
    print("✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN")
else:
    print("⚠️ QUESTIONS WITH POSSIBLE INTENT ISSUES")

    print(
        pd.DataFrame(intent_failures).to_string(index=False)
    )


# ------------------------------------------------------------
# 5. QUESTION MARK CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("5. QUESTION FORMAT CHECK")
print("-" * 80)

format_failures = []

for idx, row in df.iterrows():

    q = str(row["question"]).strip()

    if not q:
        continue

    if not q.endswith(("?", "؟")):
        format_failures.append({
            "faq_id": row["faq_id"],
            "question": q
        })

print(f"Questions without question mark: {len(format_failures)}")

if len(format_failures) == 0:
    print("✅ ALL QUESTIONS HAVE QUESTION MARKS")
else:
    print(
        pd.DataFrame(format_failures).to_string(index=False)
    )


# ------------------------------------------------------------
# 6. HOTEL NAME CHECK
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("6. HOTEL NAME CHECK")
print("-" * 80)

hotel_failures = []

for idx, row in df.iterrows():

    q = str(row["question"]).strip()

    if not q:
        continue

    # Require hotel name for scenario/paraphrased questions
    # and check direct questions that should identify the hotel.
    if "Nile Pearl Hotel" not in q:

        hotel_failures.append({
            "faq_id": row["faq_id"],
            "language": row["language"],
            "question_type": row["question_type"],
            "question": q
        })

print(f"Questions without 'Nile Pearl Hotel': {len(hotel_failures)}")

if len(hotel_failures) == 0:
    print("✅ HOTEL NAME PRESENT IN ALL QUESTIONS")
else:
    print("⚠️ QUESTIONS WITHOUT HOTEL NAME")
    print(
        pd.DataFrame(hotel_failures).to_string(index=False)
    )


# ------------------------------------------------------------
# 7. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INT006 FINAL AUDIT SUMMARY")
print("=" * 80)

print(f"Total rows                  : {len(df)}")
print(f"Non-empty questions        : {(~empty_mask).sum()}")
print(f"Empty questions            : {empty_mask.sum()}")
print(f"Exact duplicate rows       : {len(exact_duplicates)}")
print(f"Similarity pairs >= 0.85   : {len(similar_df)}")
print(f"Intent failures             : {len(intent_failures)}")
print(f"Format failures             : {len(format_failures)}")
print(f"Hotel-name failures         : {len(hotel_failures)}")

print("\n" + "=" * 80)

if (
    len(df) == 32
    and empty_mask.sum() == 0
    and len(exact_duplicates) == 0
    and len(intent_failures) == 0
    and len(format_failures) == 0
):
    print("✅ INT006 PASSED CORE QUALITY CHECKS")
else:
    print("⚠️ INT006 NEEDS REVIEW")

print("=" * 80)

================================================================================
INT006 FINAL QUALITY AUDIT
================================================================================

--------------------------------------------------------------------------------
1. BASIC VALIDATION
--------------------------------------------------------------------------------
Total rows: 32
Non-empty questions: 32
Empty questions: 0

Languages:
{'English': 8, 'Arabic': 8, 'French': 8, 'Russian': 8}

Question types:
{'Direct': 12, 'Paraphrased': 12, 'Scenario': 8}

--------------------------------------------------------------------------------
2. EXACT DUPLICATE CHECK
--------------------------------------------------------------------------------
Exact duplicate rows: 0
✅ NO EXACT DUPLICATES

--------------------------------------------------------------------------------
3. SIMILARITY CHECK
--------------------------------------------------------------------------------
Potential similar pairs: 6

Top similar pairs:
  faq_1   faq_2 language      type_1      type_2  similarity                                                                                            question_1                                                                                                                        question_2
FAQ0172 FAQ0175   Arabic Paraphrased    Scenario       0.971              هل يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟                                         كيف يمكنني الوصول إلى الغرفة في Nile Pearl Hotel قبل الوقت المعتاد وتسجيل الوصول مبكرًا؟؟
FAQ0169 FAQ0170   Arabic      Direct      Direct       0.920                                                    هل يمكنني تسجيل الوصول المبكر في Nile Pearl Hotel؟                                                                                هل يُسمح بتسجيل الوصول المبكر في Nile Pearl Hotel؟
FAQ0178 FAQ0180   French      Direct Paraphrased       0.908                                             Peut-on faire une arrivée anticipée au Nile Pearl Hotel ?                                                                  Peut-on bénéficier d'une arrivée anticipée au Nile Pearl Hotel ?
FAQ0191 FAQ0192  Russian    Scenario    Scenario       0.877 Если я приеду раньше времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel? Если я приеду на несколько часов раньше обычного времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?
FAQ0165 FAQ0166  English Paraphrased Paraphrased       0.875                                              Could I request an earlier check-in at Nile Pearl Hotel?                                                                          Can I request an early check-in at the Nile Pearl Hotel?
FAQ0164 FAQ0166  English Paraphrased Paraphrased       0.870                                                  Can I arrange an early check-in at Nile Pearl Hotel?                                                                          Can I request an early check-in at the Nile Pearl Hotel?

--------------------------------------------------------------------------------
4. EARLY CHECK-IN INTENT CHECK
--------------------------------------------------------------------------------
Intent failures: 0
✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN

--------------------------------------------------------------------------------
5. QUESTION FORMAT CHECK
--------------------------------------------------------------------------------
Questions without question mark: 0
✅ ALL QUESTIONS HAVE QUESTION MARKS

--------------------------------------------------------------------------------
6. HOTEL NAME CHECK
--------------------------------------------------------------------------------
Questions without 'Nile Pearl Hotel': 2
⚠️ QUESTIONS WITHOUT HOTEL NAME
 faq_id language question_type                                    question
FAQ0163  English        Direct        Does the hotel allow early check-in?
FAQ0179   French        Direct L'hôtel autorise-t-il l'arrivée anticipée ?

================================================================================
INT006 FINAL AUDIT SUMMARY
================================================================================
Total rows                  : 32
Non-empty questions        : 32
Empty questions            : 0
Exact duplicate rows       : 0
Similarity pairs >= 0.85   : 6
Intent failures             : 0
Format failures             : 0
Hotel-name failures         : 2

================================================================================
✅ INT006 PASSED CORE QUALITY CHECKS
================================================================================

In [52]:
# ============================================================
# INT006 FINAL MANUAL POLISH
# ============================================================

import pandas as pd

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

# ------------------------------------------------------------
# Final approved replacements
# ------------------------------------------------------------

final_questions = {
    "FAQ0163":
        "Does Nile Pearl Hotel permit guests to check in before the standard check-in time?",

    "FAQ0164":
        "Is there a way to organize an earlier arrival and check-in at Nile Pearl Hotel?",

    "FAQ0175":
        "If I reach Nile Pearl Hotel before the usual check-in time, can the hotel arrange access to my room?",

    "FAQ0179":
        "Nile Pearl Hotel autorise-t-il les clients à effectuer un enregistrement avant l'heure normale ?",

    "FAQ0192":
        "Если мой приезд в Nile Pearl Hotel запланирован на несколько часов раньше обычного времени заезда, можно ли оформить раннюю регистрацию?"
}

# ------------------------------------------------------------
# Apply replacements
# ------------------------------------------------------------

print("=" * 80)
print("INT006 FINAL MANUAL POLISH")
print("=" * 80)

for faq_id, new_question in final_questions.items():

    mask = df["faq_id"] == faq_id

    if mask.any():

        old_question = df.loc[mask, "question"].iloc[0]

        print(f"\n{faq_id}")
        print(f"OLD: {old_question}")
        print(f"NEW: {new_question}")

        df.loc[mask, "question"] = new_question

    else:
        print(f"\n⚠️ {faq_id} NOT FOUND")

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

df.to_csv(
    PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 80)
print("SAVE COMPLETE")
print("=" * 80)

print(f"Path: {PATH}")
print(f"Rows: {len(df)}")

================================================================================
INT006 FINAL MANUAL POLISH
================================================================================

FAQ0163
OLD: Does Nile Pearl Hotel permit guests to check in before the standard check-in time?
NEW: Does Nile Pearl Hotel permit guests to check in before the standard check-in time?

FAQ0164
OLD: Is there a way to organize an earlier arrival and check-in at Nile Pearl Hotel?
NEW: Is there a way to organize an earlier arrival and check-in at Nile Pearl Hotel?

FAQ0175
OLD: إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟
NEW: If I reach Nile Pearl Hotel before the usual check-in time, can the hotel arrange access to my room?

FAQ0179
OLD: Nile Pearl Hotel autorise-t-il les clients à effectuer un enregistrement avant l'heure normale ?
NEW: Nile Pearl Hotel autorise-t-il les clients à effectuer un enregistrement avant l'heure normale ?

FAQ0192
OLD: Если мой приезд в Nile Pearl Hotel запланирован на несколько часов раньше обычного времени заезда, можно ли оформить раннюю регистрацию?
NEW: Если мой приезд в Nile Pearl Hotel запланирован на несколько часов раньше обычного времени заезда, можно ли оформить раннюю регистрацию?

================================================================================
SAVE COMPLETE
================================================================================
Path: 03_Structured_Data/CSV/faq_INT006_final.csv
Rows: 32

In [53]:
import pandas as pd

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

df.loc[df["faq_id"] == "FAQ0175", "question"] = (
    "إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، "
    "هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟"
)

df.to_csv(PATH, index=False, encoding="utf-8-sig")

print("✅ FAQ0175 fixed and saved")

print(
    df.loc[
        df["faq_id"] == "FAQ0175",
        ["faq_id", "language", "question_type", "question"]
    ].to_string(index=False)
)

✅ FAQ0175 fixed and saved
 faq_id language question_type                                                                                              question
FAQ0175   Arabic      Scenario إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟

In [51]:
import pandas as pd

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

df.loc[
    df["faq_id"] == "FAQ0175",
    "question"
] = "إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟"

df.to_csv(
    PATH,
    index=False,
    encoding="utf-8-sig"
)

print("✅ FAQ0175 fixed")
print(
    df.loc[
        df["faq_id"] == "FAQ0175",
        ["faq_id", "language", "question_type", "question"]
    ].to_string(index=False)
)

✅ FAQ0175 fixed
 faq_id language question_type                                                                                              question
FAQ0175   Arabic      Scenario إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟

In [54]:
import pandas as pd
from difflib import SequenceMatcher

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

print("=" * 80)
print("INT006 FINAL QUALITY AUDIT")
print("=" * 80)

# ============================================================
# 1. BASIC VALIDATION
# ============================================================

print("\n" + "-" * 80)
print("1. BASIC VALIDATION")
print("-" * 80)

total_rows = len(df)
non_empty = df["question"].fillna("").astype(str).str.strip().ne("").sum()
empty = total_rows - non_empty

print(f"Total rows: {total_rows}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")

print("\nLanguages:")
print(df["language"].value_counts().to_dict())

print("\nQuestion types:")
print(df["question_type"].value_counts().to_dict())


# ============================================================
# 2. EXACT DUPLICATE CHECK
# ============================================================

print("\n" + "-" * 80)
print("2. EXACT DUPLICATE CHECK")
print("-" * 80)

questions = df["question"].fillna("").astype(str).str.strip()

duplicate_count = questions.duplicated(keep=False).sum()

print(f"Exact duplicate rows: {duplicate_count}")

if duplicate_count == 0:
    print("✅ NO EXACT DUPLICATES")
else:
    print("⚠️ EXACT DUPLICATES FOUND")
    print(
        df[questions.duplicated(keep=False)][
            ["faq_id", "language", "question_type", "question"]
        ].to_string(index=False)
    )


# ============================================================
# 3. SIMILARITY CHECK
# ============================================================

print("\n" + "-" * 80)
print("3. SIMILARITY CHECK")
print("-" * 80)

similar_pairs = []

for i in range(len(df)):
    q1 = str(df.iloc[i]["question"]).strip()

    if not q1:
        continue

    for j in range(i + 1, len(df)):
        q2 = str(df.iloc[j]["question"]).strip()

        if not q2:
            continue

        similarity = SequenceMatcher(None, q1.lower(), q2.lower()).ratio()

        if similarity >= 0.85:
            similar_pairs.append({
                "faq_1": df.iloc[i]["faq_id"],
                "faq_2": df.iloc[j]["faq_id"],
                "language": df.iloc[i]["language"],
                "type_1": df.iloc[i]["question_type"],
                "type_2": df.iloc[j]["question_type"],
                "similarity": round(similarity, 3),
                "question_1": q1,
                "question_2": q2
            })

print(f"Potential similar pairs: {len(similar_pairs)}")

if similar_pairs:
    similarity_df = pd.DataFrame(similar_pairs)
    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print("\nTop similar pairs:")
    print(similarity_df.head(10).to_string(index=False))
else:
    print("✅ NO HIGH-SIMILARITY PAIRS")


# ============================================================
# 4. EARLY CHECK-IN INTENT CHECK
# ============================================================

print("\n" + "-" * 80)
print("4. EARLY CHECK-IN INTENT CHECK")
print("-" * 80)

intent_keywords = [
    "early check-in",
    "early check in",
    "earlier check-in",
    "earlier arrival",
    "arrive early",
    "check in early",
    "تسجيل الوصول المبكر",
    "تسجيل الوصول مبكر",
    "الوصول مبكر",
    "وصول مبكر",
    "arrivée anticipée",
    "enregistrement anticipé",
    "enregistrement avant",
    "ранний заезд",
    "ранняя регистрация",
    "зарегистрироваться раньше"
]

intent_failures = []

for _, row in df.iterrows():

    question = str(row["question"]).lower().strip()

    if not any(keyword.lower() in question for keyword in intent_keywords):
        intent_failures.append({
            "faq_id": row["faq_id"],
            "language": row["language"],
            "question_type": row["question_type"],
            "question": row["question"]
        })

print(f"Intent failures: {len(intent_failures)}")

if len(intent_failures) == 0:
    print("✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN")
else:
    print("⚠️ INTENT FAILURES FOUND")
    print(pd.DataFrame(intent_failures).to_string(index=False))


# ============================================================
# 5. QUESTION FORMAT CHECK
# ============================================================

print("\n" + "-" * 80)
print("5. QUESTION FORMAT CHECK")
print("-" * 80)

format_failures = []

for _, row in df.iterrows():

    question = str(row["question"]).strip()

    if question and not question.endswith("?") and not question.endswith("؟"):
        format_failures.append({
            "faq_id": row["faq_id"],
            "language": row["language"],
            "question": row["question"]
        })

print(f"Questions without question mark: {len(format_failures)}")

if len(format_failures) == 0:
    print("✅ ALL QUESTIONS HAVE QUESTION MARKS")
else:
    print("⚠️ FORMAT FAILURES FOUND")
    print(pd.DataFrame(format_failures).to_string(index=False))


# ============================================================
# 6. HOTEL NAME CHECK
# ============================================================

print("\n" + "-" * 80)
print("6. HOTEL NAME CHECK")
print("-" * 80)

hotel_failures = []

for _, row in df.iterrows():

    question = str(row["question"])

    if "Nile Pearl Hotel" not in question:
        hotel_failures.append({
            "faq_id": row["faq_id"],
            "language": row["language"],
            "question_type": row["question_type"],
            "question": row["question"]
        })

print(f"Questions without 'Nile Pearl Hotel': {len(hotel_failures)}")

if len(hotel_failures) == 0:
    print("✅ ALL QUESTIONS CONTAIN HOTEL NAME")
else:
    print("⚠️ QUESTIONS WITHOUT HOTEL NAME")
    print(pd.DataFrame(hotel_failures).to_string(index=False))


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("INT006 FINAL AUDIT SUMMARY")
print("=" * 80)

print(f"Total rows                  : {total_rows}")
print(f"Non-empty questions        : {non_empty}")
print(f"Empty questions            : {empty}")
print(f"Exact duplicate rows       : {duplicate_count}")
print(f"Similarity pairs >= 0.85   : {len(similar_pairs)}")
print(f"Intent failures             : {len(intent_failures)}")
print(f"Format failures             : {len(format_failures)}")
print(f"Hotel-name failures         : {len(hotel_failures)}")

print("\n" + "=" * 80)

if (
    total_rows == 32
    and non_empty == 32
    and empty == 0
    and duplicate_count == 0
    and len(intent_failures) == 0
    and len(format_failures) == 0
    and len(hotel_failures) == 0
):
    print("✅ INT006 PASSED CORE QUALITY CHECKS")
    print("✅ INT006 READY")
else:
    print("⚠️ INT006 NEEDS REVIEW")

print("=" * 80)

================================================================================
INT006 FINAL QUALITY AUDIT
================================================================================

--------------------------------------------------------------------------------
1. BASIC VALIDATION
--------------------------------------------------------------------------------
Total rows: 32
Non-empty questions: 32
Empty questions: 0

Languages:
{'English': 8, 'Arabic': 8, 'French': 8, 'Russian': 8}

Question types:
{'Direct': 12, 'Paraphrased': 12, 'Scenario': 8}

--------------------------------------------------------------------------------
2. EXACT DUPLICATE CHECK
--------------------------------------------------------------------------------
Exact duplicate rows: 0
✅ NO EXACT DUPLICATES

--------------------------------------------------------------------------------
3. SIMILARITY CHECK
--------------------------------------------------------------------------------
Potential similar pairs: 3

Top similar pairs:
  faq_1   faq_2 language      type_1      type_2  similarity                                                question_1                                                       question_2
FAQ0169 FAQ0170   Arabic      Direct      Direct       0.920        هل يمكنني تسجيل الوصول المبكر في Nile Pearl Hotel؟               هل يُسمح بتسجيل الوصول المبكر في Nile Pearl Hotel؟
FAQ0178 FAQ0180   French      Direct Paraphrased       0.909 Peut-on faire une arrivée anticipée au Nile Pearl Hotel ? Peut-on bénéficier d'une arrivée anticipée au Nile Pearl Hotel ?
FAQ0165 FAQ0166  English Paraphrased Paraphrased       0.875  Could I request an earlier check-in at Nile Pearl Hotel?         Can I request an early check-in at the Nile Pearl Hotel?

--------------------------------------------------------------------------------
4. EARLY CHECK-IN INTENT CHECK
--------------------------------------------------------------------------------
Intent failures: 10
⚠️ INTENT FAILURES FOUND
 faq_id language question_type                                                                                                                                 question
FAQ0163  English        Direct                                                       Does Nile Pearl Hotel permit guests to check in before the standard check-in time?
FAQ0175   Arabic      Scenario                                    إذا وصلت إلى Nile Pearl Hotel قبل موعد تسجيل الوصول المعتاد، هل يمكن للفندق ترتيب دخول الغرفة مبكرًا؟
FAQ0177   French        Direct                                                                             Le check-in anticipé est-il disponible au Nile Pearl Hotel ?
FAQ0182   French   Paraphrased                                                 Est-il possible d'obtenir l'autorisation pour un check-in anticipé au Nile Pearl Hotel ?
FAQ0187  Russian        Direct                                          Могу ли я заранее прибыть в Nile Pearl Hotel и провести регистрацию заезда до обычного времени?
FAQ0188  Russian   Paraphrased                                          Могу ли я заранее приехать в Nile Pearl Hotel и забронировать номер до времени обычного заезда?
FAQ0189  Russian   Paraphrased                                                                Могу ли я прибыть и зарегистрироваться заезда заранее в Nile Pearl Hotel?
FAQ0190  Russian   Paraphrased                                     Могу ли я прибыть заранее и зарегистрироваться заезда в Nile Pearl Hotel до обычного времени заезда?
FAQ0191  Russian      Scenario                                    Если я приеду раньше времени заезда, смогу ли я заранее зарегистрироваться заезда в Nile Pearl Hotel?
FAQ0192  Russian      Scenario Если мой приезд в Nile Pearl Hotel запланирован на несколько часов раньше обычного времени заезда, можно ли оформить раннюю регистрацию?

--------------------------------------------------------------------------------
5. QUESTION FORMAT CHECK
--------------------------------------------------------------------------------
Questions without question mark: 0
✅ ALL QUESTIONS HAVE QUESTION MARKS

--------------------------------------------------------------------------------
6. HOTEL NAME CHECK
--------------------------------------------------------------------------------
Questions without 'Nile Pearl Hotel': 0
✅ ALL QUESTIONS CONTAIN HOTEL NAME

================================================================================
INT006 FINAL AUDIT SUMMARY
================================================================================
Total rows                  : 32
Non-empty questions        : 32
Empty questions            : 0
Exact duplicate rows       : 0
Similarity pairs >= 0.85   : 3
Intent failures             : 10
Format failures             : 0
Hotel-name failures         : 0

================================================================================
⚠️ INT006 NEEDS REVIEW
================================================================================

In [55]:
# ============================================================
# 4. EARLY CHECK-IN INTENT CHECK - IMPROVED
# ============================================================

print("\n" + "-" * 80)
print("4. EARLY CHECK-IN INTENT CHECK")
print("-" * 80)

intent_patterns = {
    "English": [
        "early check-in",
        "early check in",
        "earlier check-in",
        "earlier arrival",
        "arrive early",
        "arrive before",
        "check in before",
        "check-in before",
        "before the standard check-in",
        "before the usual check-in",
        "before the normal check-in",
    ],

    "Arabic": [
        "تسجيل الوصول المبكر",
        "تسجيل الوصول مبكر",
        "الوصول مبكر",
        "وصول مبكر",
        "قبل موعد تسجيل الوصول",
        "قبل الوقت المعتاد",
        "دخول الغرفة مبكر",
    ],

    "French": [
        "check-in anticipé",
        "arrivée anticipée",
        "enregistrement anticipé",
        "enregistrement avant",
        "avant l'heure normale",
        "avant l'heure habituelle",
    ],

    "Russian": [
        "ранний заезд",
        "ранняя регистрация",
        "зарегистрироваться раньше",
        "приехать раньше",
        "прибыть раньше",
        "заранее прибыть",
        "заранее приехать",
        "до обычного времени",
        "до времени обычного заезда",
        "раньше времени заезда",
    ]
}

intent_failures = []

for _, row in df.iterrows():

    question = str(row["question"]).strip().lower()
    language = row["language"]

    patterns = intent_patterns.get(language, [])

    matched = any(pattern.lower() in question for pattern in patterns)

    if not matched:
        intent_failures.append({
            "faq_id": row["faq_id"],
            "language": language,
            "question_type": row["question_type"],
            "question": row["question"]
        })

print(f"Intent failures: {len(intent_failures)}")

if len(intent_failures) == 0:
    print("✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN")
else:
    print("⚠️ INTENT FAILURES FOUND")
    print(
        pd.DataFrame(intent_failures).to_string(index=False)
    )

--------------------------------------------------------------------------------
4. EARLY CHECK-IN INTENT CHECK
--------------------------------------------------------------------------------
Intent failures: 3
⚠️ INTENT FAILURES FOUND
 faq_id language question_type                                                                                                                                 question
FAQ0162  English        Direct                                                                                           Can guests check in early at Nile Pearl Hotel?
FAQ0189  Russian   Paraphrased                                                                Могу ли я прибыть и зарегистрироваться заезда заранее в Nile Pearl Hotel?
FAQ0192  Russian      Scenario Если мой приезд в Nile Pearl Hotel запланирован на несколько часов раньше обычного времени заезда, можно ли оформить раннюю регистрацию?

In [56]:
import pandas as pd
from difflib import SequenceMatcher

# ============================================================
# INT006 FINAL QUALITY AUDIT
# ============================================================

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

print("=" * 80)
print("INT006 FINAL QUALITY AUDIT")
print("=" * 80)


# ============================================================
# 1. BASIC VALIDATION
# ============================================================

print("\n" + "-" * 80)
print("1. BASIC VALIDATION")
print("-" * 80)

total_rows = len(df)

questions = (
    df["question"]
    .fillna("")
    .astype(str)
    .str.strip()
)

non_empty = questions.ne("").sum()
empty = total_rows - non_empty

print(f"Total rows: {total_rows}")
print(f"Non-empty questions: {non_empty}")
print(f"Empty questions: {empty}")

print("\nLanguages:")
print(df["language"].value_counts().to_dict())

print("\nQuestion types:")
print(df["question_type"].value_counts().to_dict())


# ============================================================
# 2. EXACT DUPLICATE CHECK
# ============================================================

print("\n" + "-" * 80)
print("2. EXACT DUPLICATE CHECK")
print("-" * 80)

duplicate_mask = questions.duplicated(keep=False)
duplicate_count = duplicate_mask.sum()

print(f"Exact duplicate rows: {duplicate_count}")

if duplicate_count == 0:
    print("✅ NO EXACT DUPLICATES")
else:
    print("⚠️ EXACT DUPLICATES FOUND")

    print(
        df.loc[
            duplicate_mask,
            ["faq_id", "language", "question_type", "question"]
        ].to_string(index=False)
    )


# ============================================================
# 3. SIMILARITY CHECK
# ============================================================

print("\n" + "-" * 80)
print("3. SIMILARITY CHECK")
print("-" * 80)

similar_pairs = []

for i in range(len(df)):

    q1 = str(df.iloc[i]["question"]).strip()

    if not q1:
        continue

    for j in range(i + 1, len(df)):

        q2 = str(df.iloc[j]["question"]).strip()

        if not q2:
            continue

        similarity = SequenceMatcher(
            None,
            q1.lower(),
            q2.lower()
        ).ratio()

        if similarity >= 0.85:

            similar_pairs.append({
                "faq_1": df.iloc[i]["faq_id"],
                "faq_2": df.iloc[j]["faq_id"],
                "language": df.iloc[i]["language"],
                "type_1": df.iloc[i]["question_type"],
                "type_2": df.iloc[j]["question_type"],
                "similarity": round(similarity, 3),
                "question_1": q1,
                "question_2": q2
            })


print(f"Potential similar pairs: {len(similar_pairs)}")

if similar_pairs:

    similarity_df = pd.DataFrame(similar_pairs)

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print("\nTop similar pairs:")

    print(
        similarity_df
        .head(10)
        .to_string(index=False)
    )

else:

    print("✅ NO HIGH-SIMILARITY PAIRS")


# ============================================================
# 4. EARLY CHECK-IN INTENT CHECK
# ============================================================

print("\n" + "-" * 80)
print("4. EARLY CHECK-IN INTENT CHECK")
print("-" * 80)


intent_patterns = {

    "English": [

        "early check-in",
        "early check in",

        "earlier check-in",
        "earlier check in",

        "earlier arrival",

        "arrive early",

        "check in early",
        "check-in early",

        "arrive before",

        "check in before",
        "check-in before",

        "before the standard check-in",
        "before the usual check-in",
        "before the normal check-in",

    ],


    "Arabic": [

        "تسجيل الوصول المبكر",
        "تسجيل الوصول مبكر",

        "الوصول مبكر",
        "وصول مبكر",

        "قبل موعد تسجيل الوصول",
        "قبل الوقت المعتاد",

        "دخول الغرفة مبكر",

    ],


    "French": [

        "check-in anticipé",
        "check in anticipé",

        "arrivée anticipée",

        "enregistrement anticipé",

        "enregistrement avant",

        "avant l'heure normale",

        "avant l'heure habituelle",

    ],


    "Russian": [

        "ранний заезд",

        "ранняя регистрация",
        "раннюю регистрацию",

        "зарегистрироваться раньше",

        "приехать раньше",

        "прибыть раньше",

        "заранее прибыть",
        "заранее приехать",

        "зарегистрироваться заезда заранее",

        "до обычного времени",

        "до времени обычного заезда",

        "раньше времени заезда",

    ]
}


intent_failures = []


for _, row in df.iterrows():

    question = str(row["question"]).strip().lower()

    language = row["language"]

    patterns = intent_patterns.get(language, [])

    matched = any(
        pattern.lower() in question
        for pattern in patterns
    )

    if not matched:

        intent_failures.append({

            "faq_id": row["faq_id"],
            "language": language,
            "question_type": row["question_type"],
            "question": row["question"]

        })


print(f"Intent failures: {len(intent_failures)}")


if len(intent_failures) == 0:

    print(
        "✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN"
    )

else:

    print("⚠️ INTENT FAILURES FOUND")

    print(
        pd.DataFrame(intent_failures)
        .to_string(index=False)
    )


# ============================================================
# 5. QUESTION FORMAT CHECK
# ============================================================

print("\n" + "-" * 80)
print("5. QUESTION FORMAT CHECK")
print("-" * 80)

format_failures = []


for _, row in df.iterrows():

    question = str(row["question"]).strip()

    if not question:
        continue

    if not (
        question.endswith("?")
        or question.endswith("؟")
    ):

        format_failures.append({

            "faq_id": row["faq_id"],
            "language": row["language"],
            "question": row["question"]

        })


print(
    f"Questions without question mark: "
    f"{len(format_failures)}"
)


if len(format_failures) == 0:

    print(
        "✅ ALL QUESTIONS HAVE QUESTION MARKS"
    )

else:

    print("⚠️ FORMAT FAILURES FOUND")

    print(
        pd.DataFrame(format_failures)
        .to_string(index=False)
    )


# ============================================================
# 6. HOTEL NAME CHECK
# ============================================================

print("\n" + "-" * 80)
print("6. HOTEL NAME CHECK")
print("-" * 80)

hotel_failures = []


for _, row in df.iterrows():

    question = str(row["question"])

    if "Nile Pearl Hotel" not in question:

        hotel_failures.append({

            "faq_id": row["faq_id"],
            "language": row["language"],
            "question_type": row["question_type"],
            "question": row["question"]

        })


print(
    f"Questions without 'Nile Pearl Hotel': "
    f"{len(hotel_failures)}"
)


if len(hotel_failures) == 0:

    print(
        "✅ ALL QUESTIONS CONTAIN HOTEL NAME"
    )

else:

    print(
        "⚠️ QUESTIONS WITHOUT HOTEL NAME"
    )

    print(
        pd.DataFrame(hotel_failures)
        .to_string(index=False)
    )


# ============================================================
# 7. EXPECTED DISTRIBUTION CHECK
# ============================================================

print("\n" + "-" * 80)
print("7. EXPECTED DISTRIBUTION CHECK")
print("-" * 80)


expected_languages = {
    "English": 8,
    "Arabic": 8,
    "French": 8,
    "Russian": 8
}

expected_types = {
    "Direct": 12,
    "Paraphrased": 12,
    "Scenario": 8
}


actual_languages = df["language"].value_counts().to_dict()
actual_types = df["question_type"].value_counts().to_dict()


language_distribution_ok = (
    actual_languages == expected_languages
)

type_distribution_ok = (
    actual_types == expected_types
)


print(
    f"Language distribution correct: "
    f"{language_distribution_ok}"
)

print(
    f"Question type distribution correct: "
    f"{type_distribution_ok}"
)


if language_distribution_ok and type_distribution_ok:

    print("✅ DISTRIBUTION IS CORRECT")

else:

    print("⚠️ DISTRIBUTION NEEDS REVIEW")


# ============================================================
# 8. FINAL AUDIT SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("INT006 FINAL AUDIT SUMMARY")
print("=" * 80)

print(
    f"Total rows                  : {total_rows}"
)

print(
    f"Non-empty questions        : {non_empty}"
)

print(
    f"Empty questions            : {empty}"
)

print(
    f"Exact duplicate rows       : {duplicate_count}"
)

print(
    f"Similarity pairs >= 0.85   : {len(similar_pairs)}"
)

print(
    f"Intent failures             : {len(intent_failures)}"
)

print(
    f"Format failures             : {len(format_failures)}"
)

print(
    f"Hotel-name failures         : {len(hotel_failures)}"
)

print(
    f"Language distribution OK    : {language_distribution_ok}"
)

print(
    f"Question types distribution : {type_distribution_ok}"
)


# ============================================================
# FINAL STATUS
# ============================================================

core_checks_passed = (

    total_rows == 32

    and non_empty == 32

    and empty == 0

    and duplicate_count == 0

    and len(intent_failures) == 0

    and len(format_failures) == 0

    and len(hotel_failures) == 0

    and language_distribution_ok

    and type_distribution_ok
)


print("\n" + "=" * 80)


if core_checks_passed:

    print("✅ INT006 PASSED ALL CORE QUALITY CHECKS")
    print("✅ INT006 READY FOR FINAL DATASET")

else:

    print("⚠️ INT006 NEEDS REVIEW")


print("=" * 80)

================================================================================
INT006 FINAL QUALITY AUDIT
================================================================================

--------------------------------------------------------------------------------
1. BASIC VALIDATION
--------------------------------------------------------------------------------
Total rows: 32
Non-empty questions: 32
Empty questions: 0

Languages:
{'English': 8, 'Arabic': 8, 'French': 8, 'Russian': 8}

Question types:
{'Direct': 12, 'Paraphrased': 12, 'Scenario': 8}

--------------------------------------------------------------------------------
2. EXACT DUPLICATE CHECK
--------------------------------------------------------------------------------
Exact duplicate rows: 0
✅ NO EXACT DUPLICATES

--------------------------------------------------------------------------------
3. SIMILARITY CHECK
--------------------------------------------------------------------------------
Potential similar pairs: 3

Top similar pairs:
  faq_1   faq_2 language      type_1      type_2  similarity                                                question_1                                                       question_2
FAQ0169 FAQ0170   Arabic      Direct      Direct       0.920        هل يمكنني تسجيل الوصول المبكر في Nile Pearl Hotel؟               هل يُسمح بتسجيل الوصول المبكر في Nile Pearl Hotel؟
FAQ0178 FAQ0180   French      Direct Paraphrased       0.909 Peut-on faire une arrivée anticipée au Nile Pearl Hotel ? Peut-on bénéficier d'une arrivée anticipée au Nile Pearl Hotel ?
FAQ0165 FAQ0166  English Paraphrased Paraphrased       0.875  Could I request an earlier check-in at Nile Pearl Hotel?         Can I request an early check-in at the Nile Pearl Hotel?

--------------------------------------------------------------------------------
4. EARLY CHECK-IN INTENT CHECK
--------------------------------------------------------------------------------
Intent failures: 0
✅ ALL QUESTIONS CLEARLY RELATE TO EARLY CHECK-IN

--------------------------------------------------------------------------------
5. QUESTION FORMAT CHECK
--------------------------------------------------------------------------------
Questions without question mark: 0
✅ ALL QUESTIONS HAVE QUESTION MARKS

--------------------------------------------------------------------------------
6. HOTEL NAME CHECK
--------------------------------------------------------------------------------
Questions without 'Nile Pearl Hotel': 0
✅ ALL QUESTIONS CONTAIN HOTEL NAME

--------------------------------------------------------------------------------
7. EXPECTED DISTRIBUTION CHECK
--------------------------------------------------------------------------------
Language distribution correct: True
Question type distribution correct: True
✅ DISTRIBUTION IS CORRECT

================================================================================
INT006 FINAL AUDIT SUMMARY
================================================================================
Total rows                  : 32
Non-empty questions        : 32
Empty questions            : 0
Exact duplicate rows       : 0
Similarity pairs >= 0.85   : 3
Intent failures             : 0
Format failures             : 0
Hotel-name failures         : 0
Language distribution OK    : True
Question types distribution : True

================================================================================
✅ INT006 PASSED ALL CORE QUALITY CHECKS
✅ INT006 READY FOR FINAL DATASET
================================================================================

In [57]:
import pandas as pd

PATH = "03_Structured_Data/CSV/faq_INT006_final.csv"

df = pd.read_csv(PATH)

print("=" * 60)
print("INT006 FINAL SAVE VALIDATION")
print("=" * 60)

print(f"Path: {PATH}")
print(f"Rows: {len(df)}")
print(f"Non-empty questions: {df['question'].fillna('').str.strip().ne('').sum()}")

print("\nLanguage distribution:")
print(df["language"].value_counts().to_dict())

print("\nQuestion type distribution:")
print(df["question_type"].value_counts().to_dict())

print("\n✅ INT006 FINAL DATASET SAVED SUCCESSFULLY")

============================================================
INT006 FINAL SAVE VALIDATION
============================================================
Path: 03_Structured_Data/CSV/faq_INT006_final.csv
Rows: 32
Non-empty questions: 32

Language distribution:
{'English': 8, 'Arabic': 8, 'French': 8, 'Russian': 8}

Question type distribution:
{'Direct': 12, 'Paraphrased': 12, 'Scenario': 8}

✅ INT006 FINAL DATASET SAVED SUCCESSFULLY

In [1]:
# ============================================================
# 🏨 HOTEL AI - CONTINUE FAQ GENERATION
# Fresh Kernel Safe Version
# ============================================================

import os
import pandas as pd
from pathlib import Path

print("=" * 100)
print("🏨 HOTEL AI - CONTINUE FAQ GENERATION")
print("=" * 100)

# ------------------------------------------------------------
# 1. PROJECT ROOT
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Users\User\OneDrive\سطح المكتب\HotelAI"
)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"❌ Project root not found:\n{PROJECT_ROOT}"
    )

print(f"📂 Project root: {PROJECT_ROOT}")

# ------------------------------------------------------------
# 2. FINAL DATASET
# ------------------------------------------------------------

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{DATASET_PATH}"
    )

print(f"✅ Dataset found:")
print(DATASET_PATH)

# ------------------------------------------------------------
# 3. LOAD DATASET
# ------------------------------------------------------------

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# ------------------------------------------------------------
# 4. BASIC VALIDATION
# ------------------------------------------------------------

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"❌ Missing required columns:\n{missing_columns}"
    )

print("\n✅ All required columns exist.")

# ------------------------------------------------------------
# 5. LANGUAGE DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

print(df["language"].value_counts())

# ------------------------------------------------------------
# 6. INTENT DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_distribution = (
    df.groupby(["intent_id", "intent_name"])
      .size()
      .reset_index(name="questions")
)

print(intent_distribution.to_string(index=False))

# ------------------------------------------------------------
# 7. INTENT × LANGUAGE
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🌍 INTENT × LANGUAGE")
print("=" * 100)

balance = pd.crosstab(
    df["intent_name"],
    df["language"]
)

print(balance)

# ------------------------------------------------------------
# 8. QUESTION TYPE
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(df["question_type"].value_counts())

# ------------------------------------------------------------
# 9. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🔁 DUPLICATE CHECK")
print("=" * 100)

duplicate_questions = (
    df["question"]
    .astype(str)
    .str.strip()
    .str.lower()
    .duplicated()
)

print(
    f"Duplicate normalized questions: "
    f"{duplicate_questions.sum()}"
)

# ------------------------------------------------------------
# 10. EMPTY QUESTIONS
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🔎 QUESTION VALIDATION")
print("=" * 100)

empty_questions = (
    df["question"].isna()
    | (df["question"].astype(str).str.strip() == "")
)

print(f"Total questions : {len(df)}")
print(f"Empty questions : {empty_questions.sum()}")

if empty_questions.sum() == 0:
    print("✅ No empty questions.")

# ------------------------------------------------------------
# 11. CURRENT FAQ RANGE
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🆔 FAQ ID RANGE")
print("=" * 100)

faq_numbers = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
    .astype(int)
)

print(f"Minimum FAQ ID : FAQ{faq_numbers.min():04d}")
print(f"Maximum FAQ ID : FAQ{faq_numbers.max():04d}")

# ------------------------------------------------------------
# 12. NEXT FAQ ID
# ------------------------------------------------------------

NEXT_ID = faq_numbers.max() + 1

print(f"\n➡️ Next available FAQ ID: FAQ{NEXT_ID:04d}")

# ------------------------------------------------------------
# 13. SHOW CURRENT DATA
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("📋 LAST 10 QUESTIONS")
print("=" * 100)

display(
    df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question"
        ]
    ].tail(10)
)

print("\n" + "=" * 100)
print("✅ DATASET LOADED SUCCESSFULLY")
print("=" * 100)

print("""
Kernel is fresh and everything is initialized.

Current dataset:
256 questions
8 intents
4 languages

Next step:
We can now continue generating the NEW questions
without losing the existing 256 questions.
""")

====================================================================================================
🏨 HOTEL AI - CONTINUE FAQ GENERATION
====================================================================================================

FileNotFoundError: ❌ Project root not found:
C:\Users\User\OneDrive\سطح المكتب\HotelAI

In [2]:
# ============================================================
# 🏨 HOTEL AI - PROJECT AUTO DETECTION
# Restart-safe / Path-safe
# ============================================================

from pathlib import Path
import pandas as pd
import os

print("=" * 100)
print("🏨 HOTEL AI - PROJECT AUTO DETECTION")
print("=" * 100)

# ------------------------------------------------------------
# 1. SEARCH FOR FINAL DATASET
# ------------------------------------------------------------

possible_paths = [
    Path.cwd(),
    Path("/mnt/data"),
    Path.home(),
]

dataset_name = "hotel_faq_final.csv"

found_dataset = None

# Search common locations
for base in possible_paths:
    if base.exists():
        try:
            matches = list(base.rglob(dataset_name))
            if matches:
                found_dataset = matches[0]
                break
        except Exception:
            pass

# ------------------------------------------------------------
# 2. IF NOT FOUND, SEARCH /mnt/data RECURSIVELY
# ------------------------------------------------------------

if found_dataset is None:
    search_roots = [
        Path("/mnt/data"),
        Path.cwd(),
    ]

    for root in search_roots:
        if root.exists():
            try:
                for p in root.rglob("hotel_faq_final.csv"):
                    found_dataset = p
                    break
            except Exception:
                pass

        if found_dataset:
            break

# ------------------------------------------------------------
# 3. VALIDATION
# ------------------------------------------------------------

if found_dataset is None:
    print("\n❌ hotel_faq_final.csv was not found.")
    print("\n📍 Current working directory:")
    print(Path.cwd())

    print("\n📁 Files/directories available here:")
    for item in list(Path.cwd().iterdir())[:50]:
        print("   ", item)

    raise FileNotFoundError(
        "\n❌ FINAL DATASET NOT FOUND.\n"
        "Upload/copy hotel_faq_final.csv into the notebook environment, "
        "then run this cell again."
    )

# ------------------------------------------------------------
# 4. LOAD DATASET
# ------------------------------------------------------------

print("\n✅ FINAL DATASET FOUND:")
print(found_dataset)

df = pd.read_csv(found_dataset, encoding="utf-8-sig")

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# ------------------------------------------------------------
# 5. BASIC VALIDATION
# ------------------------------------------------------------

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"\n❌ Missing required columns:\n{missing_columns}"
    )

print("\n✅ All required columns exist.")

# ------------------------------------------------------------
# 6. DATASET SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("📊 CURRENT DATASET SUMMARY")
print("=" * 100)

print("\n🌍 Languages:")
print(df["language"].value_counts())

print("\n🎯 Intents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    ).size().reset_index(name="questions")
)

print("\n📝 Question Types:")
print(df["question_type"].value_counts())

print("\n🔢 FAQ IDs:")
print(
    f"First : {df['faq_id'].iloc[0]}"
)
print(
    f"Last  : {df['faq_id'].iloc[-1]}"
)

print("\n" + "=" * 100)
print("✅ DATASET READY")
print("=" * 100)

# Make dataframe available for next cells
DATASET_PATH = found_dataset
df_final = df.copy()

print(f"\n📂 DATASET_PATH = {DATASET_PATH}")

====================================================================================================
🏨 HOTEL AI - PROJECT AUTO DETECTION
====================================================================================================

✅ FINAL DATASET FOUND:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 256
Columns : 13

Columns:
1. faq_id
2. intent_id
3. language
4. question_type
5. question
6. status
7. intent_name
8. ground_truth
9. category
10. source
11. attempts
12. difficulty
13. answer

✅ All required columns exist.

====================================================================================================
📊 CURRENT DATASET SUMMARY
====================================================================================================

🌍 Languages:
language
Arabic     64
English    64
French     64
Russian    64
Name: count, dtype: int64

🎯 Intents:
  intent_id              intent_name  questions
0    INT001           hotel_location         32
1    INT002           hotel_category         32
2    INT003   reception_availability         32
3    INT004            check_in_time         32
4    INT005           check_out_time         32
5    INT006           early_check_in         32
6    INT007           late_check_out         32
7    INT008  identification_required         32

📝 Question Types:
question_type
Direct         96
Paraphrased    96
Scenario       64
Name: count, dtype: int64

🔢 FAQ IDs:
First : FAQ0009
Last  : FAQ0256

====================================================================================================
✅ DATASET READY
====================================================================================================

📂 DATASET_PATH = /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

In [3]:
# ============================================================
# 🏨 HOTEL AI - BATCH 01 PREPARATION
# Add ONLY 32 Questions
# ============================================================

from pathlib import Path
import pandas as pd
import re
import shutil

print("=" * 100)
print("🏨 HOTEL AI - BATCH 01 | 32 QUESTIONS")
print("=" * 100)

# ------------------------------------------------------------
# 1. USE DATASET PATH FROM PREVIOUS CELL
# ------------------------------------------------------------

if "DATASET_PATH" not in globals():
    raise RuntimeError(
        "❌ DATASET_PATH is not initialized.\n"
        "Run the PROJECT AUTO DETECTION cell first."
    )

DATASET_PATH = Path(DATASET_PATH)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

# ------------------------------------------------------------
# 2. LOAD CURRENT DATASET
# ------------------------------------------------------------

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print(f"📂 Dataset: {DATASET_PATH}")
print(f"📊 Current rows: {len(df)}")

# ------------------------------------------------------------
# 3. VALIDATE CURRENT DATASET
# ------------------------------------------------------------

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer"
]

missing = [
    c for c in required_columns
    if c not in df.columns
]

if missing:
    raise ValueError(
        f"❌ Missing columns:\n{missing}"
    )

# ------------------------------------------------------------
# 4. FIND NEXT FAQ ID SAFELY
# ------------------------------------------------------------

faq_numbers = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
    .astype(int)
)

max_faq_number = faq_numbers.max()
next_faq_number = max_faq_number + 1

batch_size = 32

batch_start = next_faq_number
batch_end = batch_start + batch_size - 1

print("\n" + "=" * 100)
print("🆔 FAQ ID RANGE FOR THIS BATCH")
print("=" * 100)

print(f"Existing maximum : FAQ{max_faq_number:04d}")
print(f"Batch start      : FAQ{batch_start:04d}")
print(f"Batch end        : FAQ{batch_end:04d}")
print(f"Batch size       : {batch_size}")

# ------------------------------------------------------------
# 5. BALANCED BATCH PLAN
# ------------------------------------------------------------

languages = [
    "Arabic",
    "English",
    "French",
    "Russian"
]

intents = (
    df[
        ["intent_id", "intent_name"]
    ]
    .drop_duplicates()
    .sort_values("intent_id")
)

print("\n" + "=" * 100)
print("🎯 BATCH PLAN")
print("=" * 100)

print(
    f"\n8 intents × 4 languages = {len(intents) * len(languages)} questions"
)

# ------------------------------------------------------------
# 6. BUILD EMPTY BATCH TEMPLATE
# ------------------------------------------------------------

batch_rows = []

current_id = batch_start

for _, intent_row in intents.iterrows():

    intent_id = intent_row["intent_id"]
    intent_name = intent_row["intent_name"]

    for language in languages:

        batch_rows.append({
            "faq_id": f"FAQ{current_id:04d}",
            "intent_id": intent_id,
            "language": language,
            "question_type": None,
            "question": None,
            "status": "generated",
            "intent_name": intent_name,
            "ground_truth": None,
            "category": None,
            "source": "batch_01",
            "attempts": 0,
            "difficulty": "Easy",
            "answer": None
        })

        current_id += 1

batch_df = pd.DataFrame(
    batch_rows,
    columns=required_columns
)

# ------------------------------------------------------------
# 7. VALIDATE BATCH SIZE
# ------------------------------------------------------------

assert len(batch_df) == 32

print("\n" + "=" * 100)
print("📊 BATCH STRUCTURE")
print("=" * 100)

print(f"Questions: {len(batch_df)}")

print("\nIntent distribution:")
print(
    batch_df["intent_name"].value_counts()
)

print("\nLanguage distribution:")
print(
    batch_df["language"].value_counts()
)

# ------------------------------------------------------------
# 8. CREATE BATCH DIRECTORY
# ------------------------------------------------------------

project_root = DATASET_PATH

# /final/hotel_faq_final.csv
# project root = .../CSV/final
final_dir = DATASET_PATH.parent

batch_dir = final_dir / "batches"

batch_dir.mkdir(
    parents=True,
    exist_ok=True
)

batch_path = (
    batch_dir
    / "hotel_faq_batch_01_32.csv"
)

# ------------------------------------------------------------
# 9. SAVE TEMPLATE
# ------------------------------------------------------------

batch_df.to_csv(
    batch_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH TEMPLATE CREATED")
print("=" * 100)

print(f"📄 {batch_path}")

# ------------------------------------------------------------
# 10. DISPLAY BATCH
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("📋 BATCH 01")
print("=" * 100)

display(batch_df)

print("\n" + "=" * 100)
print("✅ BATCH 01 READY")
print("=" * 100)

print("""
32 سؤال فقط.

❗ لم يتم تعديل hotel_faq_final.csv.
❗ لم يتم دمج الـ32 سؤال.
❗ الـbatch محفوظ منفصلًا للمراجعة.

Next step:
سنملأ الـ32 سؤال فعليًا مع الحفاظ على:
- Intent correctness
- Language
- Question diversity
- Ground truth
- Answer
- Question type
- No duplicates
""")

====================================================================================================
🏨 HOTEL AI - BATCH 01 | 32 QUESTIONS
====================================================================================================
📂 Dataset: /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Current rows: 256

====================================================================================================
🆔 FAQ ID RANGE FOR THIS BATCH
====================================================================================================
Existing maximum : FAQ0256
Batch start      : FAQ0257
Batch end        : FAQ0288
Batch size       : 32

====================================================================================================
🎯 BATCH PLAN
====================================================================================================

8 intents × 4 languages = 32 questions

====================================================================================================
📊 BATCH STRUCTURE
====================================================================================================
Questions: 32

Intent distribution:
intent_name
hotel_location             4
hotel_category             4
reception_availability     4
check_in_time              4
check_out_time             4
early_check_in             4
late_check_out             4
identification_required    4
Name: count, dtype: int64

Language distribution:
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64

====================================================================================================
💾 BATCH TEMPLATE CREATED
====================================================================================================
📄 /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/batches/hotel_faq_batch_01_32.csv

====================================================================================================
📋 BATCH 01
====================================================================================================

,faq_id,intent_id,language,question_type,question,status,intent_name,ground_truth,category,source,attempts,difficulty,answer
0,FAQ0257,INT001,Arabic,None,None,generated,hotel_location,None,None,batch_01,0,Easy,None
1,FAQ0258,INT001,English,None,None,generated,hotel_location,None,None,batch_01,0,Easy,None
2,FAQ0259,INT001,French,None,None,generated,hotel_location,None,None,batch_01,0,Easy,None
3,FAQ0260,INT001,Russian,None,None,generated,hotel_location,None,None,batch_01,0,Easy,None
4,FAQ0261,INT002,Arabic,None,None,generated,hotel_category,None,None,batch_01,0,Easy,None
5,FAQ0262,INT002,English,None,None,generated,hotel_category,None,None,batch_01,0,Easy,None
6,FAQ0263,INT002,French,None,None,generated,hotel_category,None,None,batch_01,0,Easy,None
7,FAQ0264,INT002,Russian,None,None,generated,hotel_category,None,None,batch_01,0,Easy,None
8,FAQ0265,INT003,Arabic,None,None,generated,reception_availability,None,None,batch_01,0,Easy,None
9,FAQ0266,INT003,English,None,None,generated,reception_availability,None,None,batch_01,0,Easy,None
10,FAQ0267,INT003,French,None,None,generated,reception_availability,None,None,batch_01,0,Easy,None
11,FAQ0268,INT003,Russian,None,None,generated,reception_availability,None,None,batch_01,0,Easy,None
12,FAQ0269,INT004,Arabic,None,None,generated,check_in_time,None,None,batch_01,0,Easy,None
13,FAQ0270,INT004,English,None,None,generated,check_in_time,None,None,batch_01,0,Easy,None
14,FAQ0271,INT004,French,None,None,generated,check_in_time,None,None,batch_01,0,Easy,None
15,FAQ0272,INT004,Russian,None,None,generated,check_in_time,None,None,batch_01,0,Easy,None
16,FAQ0273,INT005,Arabic,None,None,generated,check_out_time,None,None,batch_01,0,Easy,None
17,FAQ0274,INT005,English,None,None,generated,check_out_time,None,None,batch_01,0,Easy,None
18,FAQ0275,INT005,French,None,None,generated,check_out_time,None,None,batch_01,0,Easy,None
19,FAQ0276,INT005,Russian,None,None,generated,check_out_time,None,None,batch_01,0,Easy,None
20,FAQ0277,INT006,Arabic,None,None,generated,early_check_in,None,None,batch_01,0,Easy,None
21,FAQ0278,INT006,English,None,None,generated,early_check_in,None,None,batch_01,0,Easy,None
22,FAQ0279,INT006,French,None,None,generated,early_check_in,None,None,batch_01,0,Easy,None
23,FAQ0280,INT006,Russian,None,None,generated,early_check_in,None,None,batch_01,0,Easy,None
24,FAQ0281,INT007,Arabic,None,None,generated,late_check_out,None,None,batch_01,0,Easy,None
25,FAQ0282,INT007,English,None,None,generated,late_check_out,None,None,batch_01,0,Easy,None
26,FAQ0283,INT007,French,None,None,generated,late_check_out,None,None,batch_01,0,Easy,None
27,FAQ0284,INT007,Russian,None,None,generated,late_check_out,None,None,batch_01,0,Easy,None
28,FAQ0285,INT008,Arabic,None,None,generated,identification_required,None,None,batch_01,0,Easy,None
29,FAQ0286,INT008,English,None,None,generated,identification_required,None,None,batch_01,0,Easy,None
30,FAQ0287,INT008,French,None,None,generated,identification_required,None,None,batch_01,0,Easy,None
31,FAQ0288,INT008,Russian,None,None,generated,identification_required,None,None,batch_01,0,Easy,None

====================================================================================================
✅ BATCH 01 READY
====================================================================================================

32 سؤال فقط.

❗ لم يتم تعديل hotel_faq_final.csv.
❗ لم يتم دمج الـ32 سؤال.
❗ الـbatch محفوظ منفصلًا للمراجعة.

Next step:
سنملأ الـ32 سؤال فعليًا مع الحفاظ على:
- Intent correctness
- Language
- Question diversity
- Ground truth
- Answer
- Question type
- No duplicates

In [4]:
from pathlib import Path
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - CONTINUE FAQ GENERATION")
print("=" * 100)

# ============================================================
# 1. AUTO-DETECT PROJECT ROOT
# ============================================================

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "OneDrive" / "سطح المكتب" / "HotelAI",
    Path.home() / "OneDrive" / "Desktop" / "HotelAI",
]

PROJECT_ROOT = None

for root in possible_roots:
    if root.exists() and (root / "03_Structured_Data").exists():
        PROJECT_ROOT = root
        break

if PROJECT_ROOT is None:
    # Search a few common locations
    candidates = [
        Path.home() / "Desktop",
        Path.home() / "OneDrive",
    ]

    for base in candidates:
        if base.exists():
            for p in base.glob("**/HotelAI-Intelligent-Agent"):
                if (p / "03_Structured_Data").exists():
                    PROJECT_ROOT = p
                    break

        if PROJECT_ROOT:
            break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ Could not automatically find HotelAI project.\n"
        "Please check that the repository is cloned locally."
    )

print(f"📂 Project root:\n{PROJECT_ROOT}")

# ============================================================
# 2. FINAL DATASET
# ============================================================

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{DATASET_PATH}"
    )

print(f"\n✅ Final dataset found:")
print(DATASET_PATH)

# ============================================================
# 3. LOAD CURRENT DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 CURRENT DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# ============================================================
# 4. REQUIRED COLUMNS
# ============================================================

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

missing = [c for c in required_columns if c not in df.columns]

if missing:
    raise ValueError(
        f"❌ Missing required columns:\n{missing}"
    )

print("\n✅ All required columns exist.")

# ============================================================
# 5. CURRENT FAQ ID CHECK
# ============================================================

def faq_number(x):
    try:
        return int(str(x).replace("FAQ", ""))
    except:
        return None

df["_faq_num"] = df["faq_id"].apply(faq_number)

max_faq = df["_faq_num"].max()

if pd.isna(max_faq):
    raise ValueError("❌ Could not determine last FAQ ID.")

next_faq = int(max_faq) + 1

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Current rows : {len(df)}")
print(f"Last FAQ ID  : FAQ{int(max_faq):04d}")
print(f"Next FAQ ID  : FAQ{next_faq:04d}")

# ============================================================
# 6. VALIDATION BEFORE GENERATION
# ============================================================

print("\n" + "=" * 100)
print("🔎 PRE-GENERATION VALIDATION")
print("=" * 100)

print(f"Duplicate FAQ IDs : {df['faq_id'].duplicated().sum()}")
print(f"Duplicate questions : {df['question'].duplicated().sum()}")
print(f"Empty questions : {df['question'].isna().sum()}")

print("\n🌍 Languages:")
print(df["language"].value_counts())

print("\n🎯 Intents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    ).size().reset_index(name="questions")
)

print("\n📝 Question Types:")
print(df["question_type"].value_counts())

# ============================================================
# 7. REMOVE TEMP COLUMN
# ============================================================

df = df.drop(columns=["_faq_num"])

# ============================================================
# 8. BATCH CONFIGURATION
# ============================================================

BATCH_SIZE = 32

BATCH_START_ID = next_faq
BATCH_END_ID = next_faq + BATCH_SIZE - 1

print("\n" + "=" * 100)
print("🚀 NEXT BATCH")
print("=" * 100)

print(f"Batch size : {BATCH_SIZE}")
print(f"IDs        : FAQ{BATCH_START_ID:04d} → FAQ{BATCH_END_ID:04d}")

print("\n⚠️ IMPORTANT:")
print("This cell ONLY loads and validates the existing dataset.")
print("It does NOT modify hotel_faq_final.csv.")
print("It does NOT generate or merge questions.")

print("\n" + "=" * 100)
print("✅ READY TO GENERATE BATCH 02")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - CONTINUE FAQ GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

✅ Final dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 CURRENT DATASET
====================================================================================================
Rows    : 256
Columns : 13

Columns:
1. faq_id
2. intent_id
3. language
4. question_type
5. question
6. status
7. intent_name
8. ground_truth
9. category
10. source
11. attempts
12. difficulty
13. answer

✅ All required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Current rows : 256
Last FAQ ID  : FAQ0256
Next FAQ ID  : FAQ0257

====================================================================================================
🔎 PRE-GENERATION VALIDATION
====================================================================================================
Duplicate FAQ IDs : 0
Duplicate questions : 0
Empty questions : 0

🌍 Languages:
language
Arabic     64
English    64
French     64
Russian    64
Name: count, dtype: int64

🎯 Intents:
  intent_id              intent_name  questions
0    INT001           hotel_location         32
1    INT002           hotel_category         32
2    INT003   reception_availability         32
3    INT004            check_in_time         32
4    INT005           check_out_time         32
5    INT006           early_check_in         32
6    INT007           late_check_out         32
7    INT008  identification_required         32

📝 Question Types:
question_type
Direct         96
Paraphrased    96
Scenario       64
Name: count, dtype: int64

====================================================================================================
🚀 NEXT BATCH
====================================================================================================
Batch size : 32
IDs        : FAQ0257 → FAQ0288

⚠️ IMPORTANT:
This cell ONLY loads and validates the existing dataset.
It does NOT modify hotel_faq_final.csv.
It does NOT generate or merge questions.

====================================================================================================
✅ READY TO GENERATE BATCH 02
====================================================================================================

In [5]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02
# 32 NEW QUESTIONS ONLY
# FAQ0257 → FAQ0288
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 GENERATION")
print("=" * 100)

# ============================================================
# 1. PROJECT / DATASET
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

# ============================================================
# 2. LOAD CURRENT DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print(f"📂 Dataset: {DATASET_PATH}")
print(f"📊 Current rows: {len(df)}")

# ============================================================
# 3. NORMALIZATION
# ============================================================

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).strip().lower()
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[?!.,;:]+", "", text)

    return text


existing_questions = set(
    df["question"].map(normalize_text)
)

# ============================================================
# 4. FAQ ID
# ============================================================

def get_faq_number(value):
    match = re.search(r"(\d+)", str(value))
    return int(match.group(1)) if match else 0


last_id = max(
    df["faq_id"].map(get_faq_number)
)

start_id = last_id + 1
end_id = start_id + 31

print("\n" + "=" * 100)
print("🆔 BATCH RANGE")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(f"New batch     : FAQ{start_id:04d} → FAQ{end_id:04d}")

# ============================================================
# 5. 32 QUESTIONS
#
# 1 question per INTENT × LANGUAGE combination
# ============================================================

questions = [

# ============================================================
# INT001 - HOTEL LOCATION
# ============================================================

("INT001", "hotel_location", "Arabic", "Direct",
 "أين يقع فندق Nile Pearl Hotel؟"),

("INT001", "hotel_location", "English", "Direct",
 "Where is Nile Pearl Hotel located?"),

("INT001", "hotel_location", "French", "Direct",
 "Où se trouve l’hôtel Nile Pearl Hotel ?"),

("INT001", "hotel_location", "Russian", "Direct",
 "Где находится отель Nile Pearl Hotel?"),

# ============================================================
# INT002 - HOTEL CATEGORY
# ============================================================

("INT002", "hotel_category", "Arabic", "Direct",
 "ما تصنيف فندق Nile Pearl Hotel؟"),

("INT002", "hotel_category", "English", "Direct",
 "What is the category of Nile Pearl Hotel?"),

("INT002", "hotel_category", "French", "Direct",
 "Quelle est la catégorie de l’hôtel Nile Pearl Hotel ?"),

("INT002", "hotel_category", "Russian", "Direct",
 "Какова категория отеля Nile Pearl Hotel?"),

# ============================================================
# INT003 - RECEPTION AVAILABILITY
# ============================================================

("INT003", "reception_availability", "Arabic", "Paraphrased",
 "هل مكتب الاستقبال في الفندق متاح طوال اليوم؟"),

("INT003", "reception_availability", "English", "Paraphrased",
 "Is the hotel reception available throughout the day?"),

("INT003", "reception_availability", "French", "Paraphrased",
 "La réception de l’hôtel est-elle disponible toute la journée ?"),

("INT003", "reception_availability", "Russian", "Paraphrased",
 "Работает ли стойка регистрации отеля в течение всего дня?"),

# ============================================================
# INT004 - CHECK IN TIME
# ============================================================

("INT004", "check_in_time", "Arabic", "Direct",
 "ما هو وقت تسجيل الوصول إلى الفندق؟"),

("INT004", "check_in_time", "English", "Direct",
 "What time does hotel check-in start?"),

("INT004", "check_in_time", "French", "Direct",
 "À quelle heure commence l’enregistrement à l’hôtel ?"),

("INT004", "check_in_time", "Russian", "Direct",
 "Во сколько начинается регистрация заезда в отель?"),

# ============================================================
# INT005 - CHECK OUT TIME
# ============================================================

("INT005", "check_out_time", "Arabic", "Paraphrased",
 "متى يجب مغادرة الغرفة عند تسجيل الخروج؟"),

("INT005", "check_out_time", "English", "Paraphrased",
 "What time do guests need to leave their room at check-out?"),

("INT005", "check_out_time", "French", "Paraphrased",
 "À quelle heure faut-il quitter la chambre lors du départ ?"),

("INT005", "check_out_time", "Russian", "Paraphrased",
 "Во сколько нужно освободить номер при выезде?"),

# ============================================================
# INT006 - EARLY CHECK IN
# ============================================================

("INT006", "early_check_in", "Arabic", "Scenario",
 "إذا وصلت إلى الفندق مبكرًا، هل يمكنني تسجيل الوصول قبل الموعد؟"),

("INT006", "early_check_in", "English", "Scenario",
 "If I arrive early, can I check in before the standard time?"),

("INT006", "early_check_in", "French", "Scenario",
 "Si j’arrive tôt à l’hôtel, puis-je m’enregistrer avant l’heure prévue ?"),

("INT006", "early_check_in", "Russian", "Scenario",
 "Если я приеду в отель раньше, смогу ли я заселиться до установленного времени?"),

# ============================================================
# INT007 - LATE CHECK OUT
# ============================================================

("INT007", "late_check_out", "Arabic", "Scenario",
 "إذا احتجت إلى البقاء لفترة أطول، هل يمكنني تسجيل الخروج متأخرًا؟"),

("INT007", "late_check_out", "English", "Scenario",
 "If I need to stay longer, can I request a late check-out?"),

("INT007", "late_check_out", "French", "Scenario",
 "Si j’ai besoin de rester plus longtemps, puis-je demander un départ tardif ?"),

("INT007", "late_check_out", "Russian", "Scenario",
 "Если мне нужно остаться подольше, могу ли я оформить поздний выезд?"),

# ============================================================
# INT008 - IDENTIFICATION REQUIRED
# ============================================================

("INT008", "identification_required", "Arabic", "Paraphrased",
 "ما هي وثيقة الهوية المطلوبة عند تسجيل الوصول؟"),

("INT008", "identification_required", "English", "Paraphrased",
 "What identification document is required at check-in?"),

("INT008", "identification_required", "French", "Paraphrased",
 "Quelle pièce d’identité est nécessaire lors de l’enregistrement ?"),

("INT008", "identification_required", "Russian", "Paraphrased",
 "Какой документ удостоверяющий личность нужен при регистрации заезда?"),
]

# ============================================================
# 6. EXACT COUNT VALIDATION
# ============================================================

if len(questions) != 32:
    raise ValueError(
        f"❌ Expected 32 questions, got {len(questions)}"
    )

print("\n✅ Exactly 32 questions generated.")

# ============================================================
# 7. LANGUAGE VALIDATION
# ============================================================

languages = [
    "Arabic",
    "English",
    "French",
    "Russian"
]

language_counts = {}

for lang in languages:
    language_counts[lang] = sum(
        1 for q in questions if q[2] == lang
    )

print("\n🌍 LANGUAGE DISTRIBUTION")

for lang, count in language_counts.items():
    print(f"{lang:<10} {count}")

if any(count != 8 for count in language_counts.values()):
    raise ValueError(
        "❌ Language distribution is not 8 × 4."
    )

# ============================================================
# 8. INTENT VALIDATION
# ============================================================

intent_counts = {}

for q in questions:
    intent_counts[q[0]] = intent_counts.get(q[0], 0) + 1

print("\n🎯 INTENT DISTRIBUTION")

for intent, count in sorted(intent_counts.items()):
    print(f"{intent:<8} {count}")

if len(intent_counts) != 8 or any(
    count != 4 for count in intent_counts.values()
):
    raise ValueError(
        "❌ Intent distribution is invalid."
    )

# ============================================================
# 9. DUPLICATE VALIDATION
# ============================================================

batch_normalized = [
    normalize_text(q[4])
    for q in questions
]

if len(batch_normalized) != len(set(batch_normalized)):
    raise ValueError(
        "❌ Duplicate questions inside new batch."
    )

existing_conflicts = []

for q in questions:
    if normalize_text(q[4]) in existing_questions:
        existing_conflicts.append(q[4])

if existing_conflicts:
    print("\n❌ QUESTIONS ALREADY EXIST:")
    for q in existing_conflicts:
        print("-", q)

    raise ValueError(
        "❌ Batch contains existing questions."
    )

print("\n✅ No duplicates with existing 256 questions.")

# ============================================================
# 10. BUILD BATCH DATAFRAME
# ============================================================

batch_rows = []

for i, q in enumerate(questions):

    intent_id = q[0]
    intent_name = q[1]
    language = q[2]
    question_type = q[3]
    question = q[4]

    batch_rows.append({
        "faq_id": f"FAQ{start_id + i:04d}",
        "intent_id": intent_id,
        "language": language,
        "question_type": question_type,
        "question": question,
        "status": "generated",
        "intent_name": intent_name,
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "generated_batch_02",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": ""
    })

batch_df = pd.DataFrame(
    batch_rows,
    columns=[
        "faq_id",
        "intent_id",
        "language",
        "question_type",
        "question",
        "status",
        "intent_name",
        "ground_truth",
        "category",
        "source",
        "attempts",
        "difficulty",
        "answer"
    ]
)

# ============================================================
# 11. SAVE BATCH ONLY
# ============================================================

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

BATCH_PATH = (
    BATCH_DIR
    / "faq_batch_02.csv"
)

batch_df.to_csv(
    BATCH_PATH,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 12. FINAL REPORT
# ============================================================

print("\n" + "=" * 100)
print("✅ BATCH 02 READY")
print("=" * 100)

print(f"Questions : {len(batch_df)}")
print(f"IDs       : FAQ{start_id:04d} → FAQ{end_id:04d}")

print("\n📊 Intent distribution:")
print(
    batch_df.groupby(
        ["intent_id", "intent_name"]
    ).size()
)

print("\n🌍 Language distribution:")
print(
    batch_df["language"].value_counts()
)

print("\n📝 Question types:")
print(
    batch_df["question_type"].value_counts()
)

print("\n📄 Batch saved at:")
print(BATCH_PATH)

print("\n" + "=" * 100)
print("⚠️ NO MERGE PERFORMED")
print("=" * 100)

print("❗ hotel_faq_final.csv was NOT changed.")
print("❗ Existing 256 questions were NOT changed.")
print("❗ Only the new 32-question batch was saved.")
print("❗ Review the batch before merging.")

====================================================================================================
🏨 HOTEL AI - BATCH 02 GENERATION
====================================================================================================
📂 Dataset: /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Current rows: 256

====================================================================================================
🆔 BATCH RANGE
====================================================================================================
Last existing : FAQ0256
New batch     : FAQ0257 → FAQ0288

✅ Exactly 32 questions generated.

🌍 LANGUAGE DISTRIBUTION
Arabic     8
English    8
French     8
Russian    8

🎯 INTENT DISTRIBUTION
INT001   4
INT002   4
INT003   4
INT004   4
INT005   4
INT006   4
INT007   4
INT008   4

❌ QUESTIONS ALREADY EXIST:
- Where is Nile Pearl Hotel located?

ValueError: ❌ Batch contains existing questions.

In [6]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02
# CONTINUE FROM FAQ0256
# GENERATE EXACTLY 32 NEW QUESTIONS
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 — CONTINUE")
print("=" * 100)

# ============================================================
# 1. PROJECT
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print(f"📂 Dataset: {DATASET_PATH}")
print(f"📊 Existing questions: {len(df)}")

if len(df) != 256:
    print(
        f"⚠️ Warning: expected 256 existing rows, "
        f"found {len(df)}."
    )

# ============================================================
# 3. NORMALIZATION
# ============================================================

def normalize_text(text):

    if pd.isna(text):
        return ""

    text = str(text).strip().lower()

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[?!.,;:]+",
        "",
        text
    )

    return text


existing_questions = set(
    df["question"].map(normalize_text)
)

# ============================================================
# 4. CONTINUE FAQ IDs
# ============================================================

def faq_number(value):

    match = re.search(
        r"(\d+)",
        str(value)
    )

    return int(match.group(1)) if match else 0


last_id = max(
    df["faq_id"].map(faq_number)
)

start_id = last_id + 1
end_id = start_id + 31

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(f"Next batch    : FAQ{start_id:04d} → FAQ{end_id:04d}")

# ============================================================
# 5. BATCH 02 QUESTIONS
#
# IMPORTANT:
# These are NEW phrasings.
# ============================================================

questions = [

# ------------------------------------------------------------
# INT001 - HOTEL LOCATION
# ------------------------------------------------------------

("INT001", "hotel_location", "Arabic", "Paraphrased",
 "في أي منطقة يقع فندق Nile Pearl Hotel؟"),

("INT001", "hotel_location", "English", "Paraphrased",
 "Which area is Nile Pearl Hotel situated in?"),

("INT001", "hotel_location", "French", "Paraphrased",
 "Dans quel quartier se trouve l’hôtel Nile Pearl Hotel ?"),

("INT001", "hotel_location", "Russian", "Paraphrased",
 "В каком районе расположен отель Nile Pearl Hotel?"),

# ------------------------------------------------------------
# INT002 - HOTEL CATEGORY
# ------------------------------------------------------------

("INT002", "hotel_category", "Arabic", "Paraphrased",
 "إلى أي فئة ينتمي فندق Nile Pearl Hotel؟"),

("INT002", "hotel_category", "English", "Paraphrased",
 "Which hotel category does Nile Pearl Hotel belong to?"),

("INT002", "hotel_category", "French", "Paraphrased",
 "À quelle catégorie appartient l’hôtel Nile Pearl Hotel ?"),

("INT002", "hotel_category", "Russian", "Paraphrased",
 "К какой категории относится отель Nile Pearl Hotel?"),

# ------------------------------------------------------------
# INT003 - RECEPTION AVAILABILITY
# ------------------------------------------------------------

("INT003", "reception_availability", "Arabic", "Direct",
 "هل يمكن التواصل مع مكتب الاستقبال في أي وقت؟"),

("INT003", "reception_availability", "English", "Direct",
 "Can I contact the hotel reception at any time?"),

("INT003", "reception_availability", "French", "Direct",
 "Puis-je contacter la réception de l’hôtel à tout moment ?"),

("INT003", "reception_availability", "Russian", "Direct",
 "Можно ли связаться со стойкой регистрации в любое время?"),

# ------------------------------------------------------------
# INT004 - CHECK IN TIME
# ------------------------------------------------------------

("INT004", "check_in_time", "Arabic", "Paraphrased",
 "متى يبدأ وقت الوصول وتسجيل الدخول للفندق؟"),

("INT004", "check_in_time", "English", "Paraphrased",
 "When does the hotel's check-in period begin?"),

("INT004", "check_in_time", "French", "Paraphrased",
 "Quand commence la période d’enregistrement à l’hôtel ?"),

("INT004", "check_in_time", "Russian", "Paraphrased",
 "Когда начинается время регистрации заезда в отель?"),

# ------------------------------------------------------------
# INT005 - CHECK OUT TIME
# ------------------------------------------------------------

("INT005", "check_out_time", "Direct",
 "ما الوقت المحدد لتسجيل الخروج من الفندق؟"),

("INT005", "check_out_time", "English", "Direct",
 "What is the designated check-out time at the hotel?"),

("INT005", "check_out_time", "French", "Direct",
 "Quelle est l’heure prévue pour le départ de l’hôtel ?"),

("INT005", "check_out_time", "Russian", "Direct",
 "Какое время установлено для выезда из отеля?"),

# ------------------------------------------------------------
# INT006 - EARLY CHECK IN
# ------------------------------------------------------------

("INT006", "early_check_in", "Arabic", "Scenario",
 "إذا وصلت قبل وقت تسجيل الدخول، هل يمكنني دخول غرفتي مبكرًا؟"),

("INT006", "early_check_in", "English", "Scenario",
 "If I arrive before check-in time, can I access my room early?"),

("INT006", "early_check_in", "French", "Scenario",
 "Si j’arrive avant l’heure d’enregistrement, puis-je accéder à ma chambre plus tôt ?"),

("INT006", "early_check_in", "Russian", "Scenario",
 "Если я приеду до времени заезда, смогу ли я попасть в номер раньше?"),

# ------------------------------------------------------------
# INT007 - LATE CHECK OUT
# ------------------------------------------------------------

("INT007", "late_check_out", "Arabic", "Scenario",
 "هل يمكنني الاحتفاظ بالغرفة حتى وقت متأخر من يوم المغادرة؟"),

("INT007", "late_check_out", "English", "Scenario",
 "Can I keep my room until later on the day of departure?"),

("INT007", "late_check_out", "French", "Scenario",
 "Puis-je garder ma chambre plus tard le jour de mon départ ?"),

("INT007", "late_check_out", "Russian", "Scenario",
 "Могу ли я оставить номер до более позднего времени в день выезда?"),

# ------------------------------------------------------------
# INT008 - IDENTIFICATION REQUIRED
# ------------------------------------------------------------

("INT008", "identification_required", "Direct",
 "ما المستند الذي يجب تقديمه لإثبات الهوية عند الوصول؟"),

("INT008", "identification_required", "English", "Direct",
 "Which identification document should I present when I arrive?"),

("INT008", "identification_required", "French", "Direct",
 "Quel document d’identité dois-je présenter à mon arrivée ?"),

("INT008", "identification_required", "Russian", "Direct",
 "Какой документ удостоверяющий личность нужно предъявить при прибытии?"),
]

# ============================================================
# 6. FIXED VALIDATION
# ============================================================

if len(questions) != 32:
    raise ValueError(
        f"❌ Expected 32 questions, got {len(questions)}"
    )

print("\n✅ Exactly 32 questions prepared.")

# ============================================================
# 7. CHECK DUPLICATES INSIDE BATCH
# ============================================================

batch_questions = [
    normalize_text(q[4])
    for q in questions
]

duplicate_inside_batch = (
    len(batch_questions)
    != len(set(batch_questions))
)

if duplicate_inside_batch:

    seen = set()

    print("\n❌ DUPLICATES INSIDE BATCH:")

    for q in questions:

        normalized = normalize_text(q[4])

        if normalized in seen:
            print("-", q[4])

        seen.add(normalized)

    raise ValueError(
        "❌ Batch contains duplicate questions."
    )

print("✅ No duplicates inside Batch 02.")

# ============================================================
# 8. CHECK AGAINST EXISTING 256
# ============================================================

conflicts = []

for q in questions:

    normalized = normalize_text(q[4])

    if normalized in existing_questions:
        conflicts.append(q[4])


if conflicts:

    print("\n❌ EXISTING QUESTION CONFLICTS:")

    for q in conflicts:
        print("-", q)

    raise ValueError(
        "❌ One or more questions already exist."
    )

print("✅ No conflicts with existing dataset.")

# ============================================================
# 9. LANGUAGE BALANCE
# ============================================================

language_counts = {}

for q in questions:

    language = q[2]

    language_counts[language] = (
        language_counts.get(language, 0) + 1
    )

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

for language, count in language_counts.items():

    print(
        f"{language:<10} {count}"
    )

if set(language_counts.values()) != {8}:

    raise ValueError(
        "❌ Language balance is not 8 questions per language."
    )

# ============================================================
# 10. INTENT BALANCE
# ============================================================

intent_counts = {}

for q in questions:

    intent = q[0]

    intent_counts[intent] = (
        intent_counts.get(intent, 0) + 1
    )

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

for intent, count in sorted(intent_counts.items()):

    print(
        f"{intent:<8} {count}"
    )

if len(intent_counts) != 8:

    raise ValueError(
        "❌ Expected 8 intents."
    )

if set(intent_counts.values()) != {4}:

    raise ValueError(
        "❌ Every intent must have exactly 4 questions."
    )

# ============================================================
# 11. CREATE BATCH
# ============================================================

batch_rows = []

for i, q in enumerate(questions):

    intent_id = q[0]
    intent_name = q[1]
    language = q[2]
    question_type = q[3]
    question = q[4]

    batch_rows.append({

        "faq_id":
            f"FAQ{start_id + i:04d}",

        "intent_id":
            intent_id,

        "language":
            language,

        "question_type":
            question_type,

        "question":
            question,

        "status":
            "generated",

        "intent_name":
            intent_name,

        "ground_truth":
            "",

        "category":
            "Hotel FAQ",

        "source":
            "generated_batch_02",

        "attempts":
            0,

        "difficulty":
            "Easy",

        "answer":
            ""
    })


batch_df = pd.DataFrame(
    batch_rows,
    columns=[
        "faq_id",
        "intent_id",
        "language",
        "question_type",
        "question",
        "status",
        "intent_name",
        "ground_truth",
        "category",
        "source",
        "attempts",
        "difficulty",
        "answer"
    ]
)

# ============================================================
# 12. SAVE SEPARATE BATCH
# ============================================================

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

BATCH_PATH = (
    BATCH_DIR
    / "faq_batch_02.csv"
)

batch_df.to_csv(
    BATCH_PATH,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 13. FINAL VALIDATION
# ============================================================

assert len(batch_df) == 32

assert (
    batch_df["faq_id"].nunique()
    == 32
)

assert (
    batch_df["question"].map(normalize_text).nunique()
    == 32
)

# ============================================================
# 14. REPORT
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 02 READY")
print("=" * 100)

print(
    f"Questions : {len(batch_df)}"
)

print(
    f"IDs       : FAQ{start_id:04d} → FAQ{end_id:04d}"
)

print("\n🌍 Languages:")

print(
    batch_df["language"].value_counts()
)

print("\n🎯 Intents:")

print(
    batch_df.groupby(
        ["intent_id", "intent_name"]
    ).size()
)

print("\n📝 Question Types:")

print(
    batch_df["question_type"].value_counts()
)

print("\n📄 Saved:")

print(BATCH_PATH)

print("\n" + "=" * 100)
print("🛡️ ORIGINAL DATASET PROTECTED")
print("=" * 100)

print("❗ hotel_faq_final.csv was NOT modified.")
print("❗ Existing 256 questions remain untouched.")
print("❗ Only Batch 02 was created.")
print("❗ Next step: review + fill ground_truth/answer.")

====================================================================================================
🏨 HOTEL AI - BATCH 02 — CONTINUE
====================================================================================================
📂 Dataset: /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Existing questions: 256

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0256
Next batch    : FAQ0257 → FAQ0288

✅ Exactly 32 questions prepared.

IndexError: tuple index out of range

In [7]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02 VALIDATION
# ============================================================

print("=" * 100)
print("🔎 BATCH 02 VALIDATION")
print("=" * 100)

# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

assert len(batch_df) == 32, (
    f"❌ Expected 32 questions, found {len(batch_df)}"
)

# ------------------------------------------------------------
# FAQ IDs
# ------------------------------------------------------------

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(257, 289)
]

actual_ids = batch_df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ ID sequence is incorrect."
)

print("✅ FAQ IDs: FAQ0257 → FAQ0288")

# ------------------------------------------------------------
# Duplicate IDs
# ------------------------------------------------------------

duplicate_ids = batch_df[
    batch_df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    f"❌ Duplicate FAQ IDs found:\n{duplicate_ids}"
)

print("✅ No duplicate FAQ IDs.")

# ------------------------------------------------------------
# Normalize questions
# ------------------------------------------------------------

def normalize_question(text):

    text = str(text).strip().lower()

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[?!.,;:]+",
        "",
        text
    )

    return text


batch_normalized = (
    batch_df["question"]
    .map(normalize_question)
)

# ------------------------------------------------------------
# Duplicates inside batch
# ------------------------------------------------------------

duplicate_questions = batch_df[
    batch_normalized.duplicated(keep=False)
]

assert duplicate_questions.empty, (
    f"❌ Duplicate questions inside Batch 02:\n"
    f"{duplicate_questions[['faq_id', 'question']]}"
)

print("✅ No duplicate questions inside Batch 02.")

# ------------------------------------------------------------
# Compare against existing 256
# ------------------------------------------------------------

existing_normalized = set(
    df["question"]
    .map(normalize_question)
)

conflicts = batch_df[
    batch_normalized.isin(existing_normalized)
]

assert conflicts.empty, (
    f"❌ Questions already exist in dataset:\n"
    f"{conflicts[['faq_id', 'question']]}"
)

print("✅ No Batch 02 question already exists.")

# ------------------------------------------------------------
# Empty questions
# ------------------------------------------------------------

empty_questions = batch_df[
    batch_df["question"].isna()
    |
    (
        batch_df["question"]
        .astype(str)
        .str.strip()
        .eq("")
    )
]

assert empty_questions.empty, (
    "❌ Empty questions found."
)

print("✅ No empty questions.")

# ------------------------------------------------------------
# Language balance
# ------------------------------------------------------------

language_counts = (
    batch_df["language"]
    .value_counts()
)

print("\n🌍 LANGUAGE DISTRIBUTION")
print(language_counts)

expected_languages = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8
}

assert language_counts.to_dict() == expected_languages, (
    "❌ Language distribution is incorrect."
)

print("✅ Perfect language balance.")

# ------------------------------------------------------------
# Intent balance
# ------------------------------------------------------------

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print("\n🎯 INTENT DISTRIBUTION")
print(intent_counts)

assert len(intent_counts) == 8

assert all(
    count == 4
    for count in intent_counts
), (
    "❌ Every intent must contain exactly 4 questions."
)

print("✅ Perfect intent balance.")

# ------------------------------------------------------------
# Intent ↔ Intent Name
# ------------------------------------------------------------

intent_mapping = (
    batch_df
    .groupby("intent_id")["intent_name"]
    .nunique()
)

assert all(intent_mapping == 1), (
    "❌ Intent ID maps to multiple intent names."
)

print("✅ Intent ID ↔ Intent Name consistency.")

# ------------------------------------------------------------
# Question types
# ------------------------------------------------------------

print("\n📝 QUESTION TYPES")

print(
    batch_df["question_type"]
    .value_counts()
)

# ------------------------------------------------------------
# Final result
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🎉 BATCH 02 VALIDATION PASSED")
print("=" * 100)

print("""
✅ 32 NEW QUESTIONS
✅ IDs FAQ0257 → FAQ0288
✅ No duplicate IDs
✅ No duplicate questions
✅ No overlap with existing 256
✅ No empty questions
✅ 8 questions × 4 languages
✅ 4 questions × 8 intents
✅ Intent mapping valid

🛡️ hotel_faq_final.csv is still untouched.
""")

# ------------------------------------------------------------
# Save validated batch
# ------------------------------------------------------------

BATCH_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_02_validated.csv"
)

BATCH_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

batch_df.to_csv(
    BATCH_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(f"📄 Batch saved:\n{BATCH_PATH}")

====================================================================================================
🔎 BATCH 02 VALIDATION
====================================================================================================
✅ FAQ IDs: FAQ0257 → FAQ0288
✅ No duplicate FAQ IDs.

AssertionError: ❌ Duplicate questions inside Batch 02:
     faq_id question
0   FAQ0257     None
1   FAQ0258     None
2   FAQ0259     None
3   FAQ0260     None
4   FAQ0261     None
5   FAQ0262     None
6   FAQ0263     None
7   FAQ0264     None
8   FAQ0265     None
9   FAQ0266     None
10  FAQ0267     None
11  FAQ0268     None
12  FAQ0269     None
13  FAQ0270     None
14  FAQ0271     None
15  FAQ0272     None
16  FAQ0273     None
17  FAQ0274     None
18  FAQ0275     None
19  FAQ0276     None
20  FAQ0277     None
21  FAQ0278     None
22  FAQ0279     None
23  FAQ0280     None
24  FAQ0281     None
25  FAQ0282     None
26  FAQ0283     None
27  FAQ0284     None
28  FAQ0285     None
29  FAQ0286     None
30  FAQ0287     None
31  FAQ0288     None

In [8]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02
# CONTINUE FROM FAQ0257 → FAQ0288
# ============================================================

import pandas as pd
import re
import unicodedata
from pathlib import Path

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 GENERATION")
print("=" * 100)

# ============================================================
# 1. PROJECT AUTO-DETECTION
# ============================================================

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = None

for root in possible_roots:
    if root.exists():
        PROJECT_ROOT = root
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project was not found.\n"
        "Checked:\n"
        + "\n".join(str(p) for p in possible_roots)
    )

print(f"📂 Project root:\n{PROJECT_ROOT}")

# ============================================================
# 2. FINAL DATASET
# ============================================================

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{DATASET_PATH}"
    )

print(f"✅ Final dataset found:\n{DATASET_PATH}")

# ============================================================
# 3. LOAD DATASET
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 CURRENT DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 4. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer"
]

missing_columns = [
    c for c in REQUIRED_COLUMNS
    if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"❌ Missing columns:\n{missing_columns}"
    )

print("✅ All required columns exist.")

# ============================================================
# 5. CURRENT FAQ ID
# ============================================================

faq_numbers = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d+)", expand=False)
)

faq_numbers = pd.to_numeric(
    faq_numbers,
    errors="coerce"
)

if faq_numbers.isna().any():
    raise ValueError(
        "❌ Invalid FAQ IDs found."
    )

last_id = int(faq_numbers.max())

BATCH_SIZE = 32

START_ID = last_id + 1
END_ID = last_id + BATCH_SIZE

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Current rows : {len(df)}")
print(f"Last FAQ ID  : FAQ{last_id:04d}")
print(f"Next batch   : FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}")

# ============================================================
# 6. NORMALIZATION
# ============================================================

def normalize_question(text):

    if pd.isna(text):
        return ""

    text = str(text).strip().lower()

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[?!.,;:]+",
        "",
        text
    )

    return text


existing_questions = set(
    df["question"]
    .map(normalize_question)
)

# ============================================================
# 7. EXISTING DATASET SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 EXISTING DATASET SUMMARY")
print("=" * 100)

print("\n🌍 Languages:")
print(df["language"].value_counts())

print("\n🎯 Intents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    ).size()
    .reset_index(name="questions")
    .sort_values("intent_id")
)

print("\n📝 Question Types:")
print(df["question_type"].value_counts())

# ============================================================
# 8. BATCH PLAN
# ============================================================
#
# 32 questions total
#
# 4 questions per intent
# 8 intents
#
# Language distribution:
# Arabic   8
# English  8
# French   8
# Russian  8
#
# Each intent:
# Arabic    1
# English   1
# French    1
# Russian   1
#
# ============================================================

INTENTS = [
    ("INT001", "hotel_location"),
    ("INT002", "hotel_category"),
    ("INT003", "reception_availability"),
    ("INT004", "check_in_time"),
    ("INT005", "check_out_time"),
    ("INT006", "early_check_in"),
    ("INT007", "late_check_out"),
    ("INT008", "identification_required"),
]

LANGUAGES = [
    "Arabic",
    "English",
    "French",
    "Russian",
]

# ============================================================
# 9. QUESTION BANK
# ============================================================
#
# IMPORTANT:
# These are NEW paraphrases.
# They are designed to continue the existing dataset,
# NOT restart it.
#
# ============================================================

QUESTION_BANK = {

    "INT001": {
        "Arabic": (
            "أين يقع فندق Nile Pearl Hotel؟"
        ),
        "English": (
            "What part of the city is Nile Pearl Hotel located in?"
        ),
        "French": (
            "Dans quelle partie de la ville se trouve le Nile Pearl Hotel ?"
        ),
        "Russian": (
            "В какой части города расположен отель Nile Pearl Hotel?"
        ),
    },

    "INT002": {
        "Arabic": (
            "ما تصنيف فندق Nile Pearl Hotel؟"
        ),
        "English": (
            "What category does Nile Pearl Hotel belong to?"
        ),
        "French": (
            "À quelle catégorie appartient le Nile Pearl Hotel ?"
        ),
        "Russian": (
            "К какой категории относится отель Nile Pearl Hotel?"
        ),
    },

    "INT003": {
        "Arabic": (
            "هل مكتب الاستقبال في الفندق متاح طوال اليوم؟"
        ),
        "English": (
            "Is the hotel reception available around the clock?"
        ),
        "French": (
            "La réception de l'hôtel est-elle disponible 24 heures sur 24 ?"
        ),
        "Russian": (
            "Работает ли стойка регистрации отеля круглосуточно?"
        ),
    },

    "INT004": {
        "Arabic": (
            "متى يمكنني تسجيل الوصول إلى الفندق؟"
        ),
        "English": (
            "What time can I check in at the hotel?"
        ),
        "French": (
            "À quelle heure puis-je effectuer mon enregistrement à l'hôtel ?"
        ),
        "Russian": (
            "Во сколько можно пройти регистрацию заезда в отеле?"
        ),
    },

    "INT005": {
        "Arabic": (
            "متى يجب أن أغادر الغرفة عند تسجيل المغادرة؟"
        ),
        "English": (
            "What time do I need to check out of the hotel?"
        ),
        "French": (
            "À quelle heure dois-je quitter la chambre lors du départ ?"
        ),
        "Russian": (
            "Во сколько нужно освободить номер при выезде?"
        ),
    },

    "INT006": {
        "Arabic": (
            "هل يمكنني تسجيل الوصول قبل الموعد المعتاد؟"
        ),
        "English": (
            "Can I check in before the standard check-in time?"
        ),
        "French": (
            "Est-il possible de s'enregistrer avant l'heure habituelle ?"
        ),
        "Russian": (
            "Можно ли заселиться в отель раньше установленного времени?"
        ),
    },

    "INT007": {
        "Arabic": (
            "هل يمكنني البقاء في الغرفة بعد موعد تسجيل المغادرة؟"
        ),
        "English": (
            "Can I stay in my room after the standard check-out time?"
        ),
        "French": (
            "Puis-je rester dans ma chambre après l'heure normale de départ ?"
        ),
        "Russian": (
            "Можно ли остаться в номере после установленного времени выезда?"
        ),
    },

    "INT008": {
        "Arabic": (
            "ما وثائق الهوية المطلوبة عند تسجيل الوصول؟"
        ),
        "English": (
            "Which identification documents are required at check-in?"
        ),
        "French": (
            "Quels documents d'identité sont nécessaires lors de l'enregistrement ?"
        ),
        "Russian": (
            "Какие документы удостоверяющие личность нужны при регистрации заезда?"
        ),
    },
}

# ============================================================
# 10. BUILD BATCH
# ============================================================

batch_rows = []

current_id = START_ID

for intent_id, intent_name in INTENTS:

    for language in LANGUAGES:

        question = QUESTION_BANK[
            intent_id
        ][language]

        batch_rows.append({

            "faq_id":
                f"FAQ{current_id:04d}",

            "intent_id":
                intent_id,

            "language":
                language,

            "question_type":
                "Paraphrased",

            "question":
                question,

            "status":
                "generated",

            "intent_name":
                intent_name,

            # IMPORTANT:
            # These will be completed from the
            # project's knowledge/ground truth
            # before final merge.
            "ground_truth":
                "",

            "category":
                intent_name,

            "source":
                "batch_02",

            "attempts":
                1,

            "difficulty":
                "Easy",

            "answer":
                "",
        })

        current_id += 1

batch_df = pd.DataFrame(
    batch_rows,
    columns=REQUIRED_COLUMNS
)

# ============================================================
# 11. VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🔎 BATCH 02 VALIDATION")
print("=" * 100)

assert len(batch_df) == 32

print("✅ Exactly 32 questions.")

# ------------------------------------------------------------
# IDs
# ------------------------------------------------------------

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID
    )
]

assert (
    batch_df["faq_id"].tolist()
    == expected_ids
)

print(
    f"✅ IDs: FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# ------------------------------------------------------------
# No duplicate IDs
# ------------------------------------------------------------

assert not batch_df["faq_id"].duplicated().any()

print("✅ No duplicate FAQ IDs.")

# ------------------------------------------------------------
# No empty questions
# ------------------------------------------------------------

assert (
    batch_df["question"]
    .notna()
    .all()
)

assert (
    batch_df["question"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ No empty questions.")

# ------------------------------------------------------------
# Duplicate questions inside batch
# ------------------------------------------------------------

batch_normalized = (
    batch_df["question"]
    .map(normalize_question)
)

duplicate_questions = batch_df[
    batch_normalized.duplicated(
        keep=False
    )
]

if not duplicate_questions.empty:

    print(
        "\n❌ DUPLICATE QUESTIONS:"
    )

    print(
        duplicate_questions[
            ["faq_id", "language", "question"]
        ].to_string(index=False)
    )

    raise ValueError(
        "Duplicate questions found inside Batch 02."
    )

print(
    "✅ No duplicate questions inside Batch 02."
)

# ------------------------------------------------------------
# Compare against existing dataset
# ------------------------------------------------------------

conflicts = batch_df[
    batch_normalized.isin(
        existing_questions
    )
]

if not conflicts.empty:

    print(
        "\n❌ QUESTIONS ALREADY EXIST:"
    )

    print(
        conflicts[
            ["faq_id", "language", "question"]
        ].to_string(index=False)
    )

    raise ValueError(
        "Batch contains questions already present "
        "in the existing dataset."
    )

print(
    "✅ No overlap with existing 256 questions."
)

# ------------------------------------------------------------
# Languages
# ------------------------------------------------------------

language_counts = (
    batch_df["language"]
    .value_counts()
    .to_dict()
)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert (
    language_counts
    == expected_language_counts
)

print("✅ Language balance: 8 × 4.")

# ------------------------------------------------------------
# Intents
# ------------------------------------------------------------

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

assert len(intent_counts) == 8

assert (
    intent_counts == 4
).all()

print(
    "✅ Intent balance: "
    "4 questions × 8 intents."
)

# ------------------------------------------------------------
# Intent names
# ------------------------------------------------------------

for intent_id, intent_name in INTENTS:

    rows = batch_df[
        batch_df["intent_id"]
        == intent_id
    ]

    assert (
        rows["intent_name"]
        .eq(intent_name)
        .all()
    )

print(
    "✅ Intent ID ↔ Intent Name consistency."
)

# ============================================================
# 12. DISPLAY BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 02 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question"
        ]
    ].to_string(index=False)
)

# ============================================================
# 13. SAVE BATCH ONLY
# ============================================================

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

BATCH_PATH = (
    BATCH_DIR
    / "faq_batch_02.csv"
)

batch_df.to_csv(
    BATCH_PATH,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# FINAL
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 02 READY")
print("=" * 100)

print("""
32 NEW QUESTIONS ONLY.

Current dataset:
256 questions

New batch:
32 questions

Future total:
288 questions

⚠️ hotel_faq_final.csv was NOT modified.
⚠️ The batch is saved separately.
⚠️ ground_truth and answer are intentionally left empty
   until we validate them against the project's knowledge.
""")

print(f"📄 Batch file:")
print(BATCH_PATH)

====================================================================================================
🏨 HOTEL AI - BATCH 02 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Final dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 CURRENT DATASET
====================================================================================================
Rows    : 256
Columns : 13
✅ All required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Current rows : 256
Last FAQ ID  : FAQ0256
Next batch   : FAQ0257 → FAQ0287

====================================================================================================
📊 EXISTING DATASET SUMMARY
====================================================================================================

🌍 Languages:
language
Arabic     64
English    64
French     64
Russian    64
Name: count, dtype: int64

🎯 Intents:
  intent_id              intent_name  questions
0    INT001           hotel_location         32
1    INT002           hotel_category         32
2    INT003   reception_availability         32
3    INT004            check_in_time         32
4    INT005           check_out_time         32
5    INT006           early_check_in         32
6    INT007           late_check_out         32
7    INT008  identification_required         32

📝 Question Types:
question_type
Direct         96
Paraphrased    96
Scenario       64
Name: count, dtype: int64

====================================================================================================
🔎 BATCH 02 VALIDATION
====================================================================================================
✅ Exactly 32 questions.

AssertionError:

In [9]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02
# CONTINUE FROM EXISTING 256 QUESTIONS
# Generate ONLY FAQ0257 → FAQ0288
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata


# ============================================================
# 1. PROJECT AUTO DETECTION
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 GENERATION")
print("=" * 100)

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = None

for root in possible_roots:
    if root.exists():
        PROJECT_ROOT = root
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project folder was not found.\n\n"
        "Checked locations:\n"
        + "\n".join(str(x) for x in possible_roots)
    )

print(f"📂 Project root:\n{PROJECT_ROOT}")


# ============================================================
# 2. FINAL DATASET PATH
# ============================================================

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{DATASET_PATH}"
    )

print(f"\n✅ Final dataset found:")
print(DATASET_PATH)


# ============================================================
# 3. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")


# ============================================================
# 4. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

missing_columns = [
    col
    for col in REQUIRED_COLUMNS
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        "❌ Missing required columns:\n"
        + "\n".join(missing_columns)
    )

print("\n✅ All required columns exist.")


# ============================================================
# 5. CURRENT DATASET VALIDATION
# ============================================================

if len(df) != 256:
    raise ValueError(
        f"❌ Expected exactly 256 existing questions.\n"
        f"Found: {len(df)}"
    )

print("\n✅ Existing dataset contains exactly 256 questions.")


# ============================================================
# 6. FAQ ID EXTRACTION
# ============================================================

def extract_faq_number(value):

    match = re.fullmatch(
        r"FAQ(\d+)",
        str(value).strip()
    )

    if not match:
        return None

    return int(match.group(1))


faq_numbers = df["faq_id"].apply(
    extract_faq_number
)

if faq_numbers.isna().any():

    invalid_ids = df.loc[
        faq_numbers.isna(),
        "faq_id"
    ].tolist()

    raise ValueError(
        f"❌ Invalid FAQ IDs:\n{invalid_ids}"
    )


# ============================================================
# 7. LAST FAQ ID
# ============================================================

last_faq_number = int(
    faq_numbers.max()
)

if last_faq_number != 256:
    raise ValueError(
        f"❌ Expected last FAQ ID = FAQ0256.\n"
        f"Found = FAQ{last_faq_number:04d}"
    )

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print("Current rows : 256")
print("Last FAQ ID  : FAQ0256")


# ============================================================
# 8. BATCH SETTINGS
# ============================================================

BATCH_SIZE = 32

START_ID = last_faq_number + 1
END_ID = START_ID + BATCH_SIZE - 1

NEW_IDS = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID + 1
    )
]

if len(NEW_IDS) != BATCH_SIZE:
    raise AssertionError(
        f"❌ Internal error: expected 32 IDs, "
        f"got {len(NEW_IDS)}"
    )


print("\n" + "=" * 100)
print("🚀 NEXT BATCH")
print("=" * 100)

print(f"Batch size : {BATCH_SIZE}")
print(f"IDs        : {NEW_IDS[0]} → {NEW_IDS[-1]}")


# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = text.strip().lower()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[؟?!.,;:]+",
        "",
        text
    )

    return text


existing_questions = set(
    df["question"]
    .map(normalize_question)
)


# ============================================================
# 10. EXISTING DATASET SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 EXISTING DATASET SUMMARY")
print("=" * 100)

print("\n🌍 Languages:")
print(
    df["language"]
    .value_counts()
    .sort_index()
)

print("\n🎯 Intents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
    .sort_values("intent_id")
)

print("\n📝 Question Types:")
print(
    df["question_type"]
    .value_counts()
)


# ============================================================
# 11. BATCH CONTENT
#
# 8 intents × 4 languages = 32 questions
# Each intent gets exactly 4 questions.
# ============================================================

batch_content = [

    # --------------------------------------------------------
    # INT001 - hotel_location
    # --------------------------------------------------------

    {
        "intent_id": "INT001",
        "intent_name": "hotel_location",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "في أي منطقة من المدينة يقع فندق Nile Pearl Hotel؟",
        "ground_truth": "The question asks about the location of Nile Pearl Hotel.",
        "answer": "Nile Pearl Hotel is located in the specified hotel area of the city."
    },

    {
        "intent_id": "INT001",
        "intent_name": "hotel_location",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Which part of the city is Nile Pearl Hotel located in?",
        "ground_truth": "The question asks about the location of Nile Pearl Hotel.",
        "answer": "Nile Pearl Hotel is located in the specified hotel area of the city."
    },

    {
        "intent_id": "INT001",
        "intent_name": "hotel_location",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Dans quel quartier de la ville se trouve le Nile Pearl Hotel ?",
        "ground_truth": "La question porte sur l'emplacement du Nile Pearl Hotel.",
        "answer": "Le Nile Pearl Hotel se trouve dans la zone indiquée de la ville."
    },

    {
        "intent_id": "INT001",
        "intent_name": "hotel_location",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "В каком районе города находится отель Nile Pearl Hotel?",
        "ground_truth": "Вопрос касается расположения отеля Nile Pearl Hotel.",
        "answer": "Отель Nile Pearl Hotel расположен в указанной части города."
    },


    # --------------------------------------------------------
    # INT002 - hotel_category
    # --------------------------------------------------------

    {
        "intent_id": "INT002",
        "intent_name": "hotel_category",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما فئة فندق Nile Pearl Hotel؟",
        "ground_truth": "The question asks about the category of Nile Pearl Hotel.",
        "answer": "Nile Pearl Hotel belongs to the hotel category specified in the hotel information."
    },

    {
        "intent_id": "INT002",
        "intent_name": "hotel_category",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What hotel category is Nile Pearl Hotel?",
        "ground_truth": "The question asks about the category of Nile Pearl Hotel.",
        "answer": "Nile Pearl Hotel belongs to the hotel category specified in the hotel information."
    },

    {
        "intent_id": "INT002",
        "intent_name": "hotel_category",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est la catégorie du Nile Pearl Hotel ?",
        "ground_truth": "La question porte sur la catégorie du Nile Pearl Hotel.",
        "answer": "Le Nile Pearl Hotel appartient à la catégorie indiquée dans les informations de l'hôtel."
    },

    {
        "intent_id": "INT002",
        "intent_name": "hotel_category",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какова категория отеля Nile Pearl Hotel?",
        "ground_truth": "Вопрос касается категории отеля Nile Pearl Hotel.",
        "answer": "Отель Nile Pearl Hotel относится к категории, указанной в информации об отеле."
    },


    # --------------------------------------------------------
    # INT003 - reception_availability
    # --------------------------------------------------------

    {
        "intent_id": "INT003",
        "intent_name": "reception_availability",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل مكتب استقبال الفندق يعمل على مدار الساعة؟",
        "ground_truth": "The question asks whether the hotel reception is available around the clock.",
        "answer": "The hotel's reception availability is provided in the hotel reception policy."
    },

    {
        "intent_id": "INT003",
        "intent_name": "reception_availability",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Does the hotel reception operate 24 hours a day?",
        "ground_truth": "The question asks whether the hotel reception is available around the clock.",
        "answer": "The hotel's reception availability is provided in the hotel reception policy."
    },

    {
        "intent_id": "INT003",
        "intent_name": "reception_availability",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "La réception de l'hôtel est-elle ouverte 24 heures sur 24 ?",
        "ground_truth": "La question porte sur la disponibilité de la réception de l'hôtel.",
        "answer": "Les horaires de disponibilité de la réception sont indiqués dans la politique de l'hôtel."
    },

    {
        "intent_id": "INT003",
        "intent_name": "reception_availability",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Работает ли стойка регистрации отеля круглосуточно?",
        "ground_truth": "Вопрос касается круглосуточной работы стойки регистрации.",
        "answer": "Время работы стойки регистрации указано в правилах отеля."
    },


    # --------------------------------------------------------
    # INT004 - check_in_time
    # --------------------------------------------------------

    {
        "intent_id": "INT004",
        "intent_name": "check_in_time",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما هو الوقت المحدد لتسجيل الوصول إلى الفندق؟",
        "ground_truth": "The question asks for the standard hotel check-in time.",
        "answer": "The standard check-in time is provided in the hotel's check-in policy."
    },

    {
        "intent_id": "INT004",
        "intent_name": "check_in_time",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What is the hotel's standard check-in time?",
        "ground_truth": "The question asks for the standard hotel check-in time.",
        "answer": "The standard check-in time is provided in the hotel's check-in policy."
    },

    {
        "intent_id": "INT004",
        "intent_name": "check_in_time",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est l'heure habituelle d'arrivée à l'hôtel ?",
        "ground_truth": "La question demande l'heure standard d'enregistrement à l'hôtel.",
        "answer": "L'heure standard d'enregistrement est indiquée dans la politique d'arrivée de l'hôtel."
    },

    {
        "intent_id": "INT004",
        "intent_name": "check_in_time",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какое стандартное время регистрации заезда в отеле?",
        "ground_truth": "Вопрос касается стандартного времени регистрации заезда.",
        "answer": "Стандартное время заезда указано в правилах регистрации отеля."
    },


    # --------------------------------------------------------
    # INT005 - check_out_time
    # --------------------------------------------------------

    {
        "intent_id": "INT005",
        "intent_name": "check_out_time",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما هو الوقت المعتاد لتسجيل المغادرة من الفندق؟",
        "ground_truth": "The question asks for the standard hotel check-out time.",
        "answer": "The standard check-out time is provided in the hotel's check-out policy."
    },

    {
        "intent_id": "INT005",
        "intent_name": "check_out_time",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What is the hotel's standard check-out time?",
        "ground_truth": "The question asks for the standard hotel check-out time.",
        "answer": "The standard check-out time is provided in the hotel's check-out policy."
    },

    {
        "intent_id": "INT005",
        "intent_name": "check_out_time",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est l'heure habituelle de départ de l'hôtel ?",
        "ground_truth": "La question demande l'heure standard de départ de l'hôtel.",
        "answer": "L'heure standard de départ est indiquée dans la politique de départ de l'hôtel."
    },

    {
        "intent_id": "INT005",
        "intent_name": "check_out_time",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какое стандартное время регистрации выезда из отеля?",
        "ground_truth": "Вопрос касается стандартного времени выезда.",
        "answer": "Стандартное время выезда указано в правилах отеля."
    },


    # --------------------------------------------------------
    # INT006 - early_check_in
    # --------------------------------------------------------

    {
        "intent_id": "INT006",
        "intent_name": "early_check_in",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل يسمح الفندق بتسجيل الوصول في وقت مبكر؟",
        "ground_truth": "The question asks whether early check-in is allowed.",
        "answer": "Early check-in is subject to the hotel's early check-in policy and availability."
    },

    {
        "intent_id": "INT006",
        "intent_name": "early_check_in",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Does the hotel allow early check-in?",
        "ground_truth": "The question asks whether early check-in is allowed.",
        "answer": "Early check-in is subject to the hotel's early check-in policy and availability."
    },

    {
        "intent_id": "INT006",
        "intent_name": "early_check_in",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "L'hôtel autorise-t-il l'enregistrement anticipé ?",
        "ground_truth": "La question porte sur la possibilité d'un enregistrement anticipé.",
        "answer": "L'enregistrement anticipé dépend de la politique de l'hôtel et des disponibilités."
    },

    {
        "intent_id": "INT006",
        "intent_name": "early_check_in",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Разрешена ли в отеле ранняя регистрация заезда?",
        "ground_truth": "Вопрос касается возможности раннего заезда.",
        "answer": "Ранний заезд зависит от правил отеля и наличия свободных номеров."
    },


    # --------------------------------------------------------
    # INT007 - late_check_out
    # --------------------------------------------------------

    {
        "intent_id": "INT007",
        "intent_name": "late_check_out",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل يمكنني طلب تسجيل المغادرة في وقت متأخر؟",
        "ground_truth": "The question asks whether late check-out can be requested.",
        "answer": "Late check-out is subject to the hotel's policy and availability."
    },

    {
        "intent_id": "INT007",
        "intent_name": "late_check_out",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Can I request a late check-out?",
        "ground_truth": "The question asks whether late check-out can be requested.",
        "answer": "Late check-out is subject to the hotel's policy and availability."
    },

    {
        "intent_id": "INT007",
        "intent_name": "late_check_out",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Puis-je demander un départ tardif de l'hôtel ?",
        "ground_truth": "La question porte sur la possibilité de demander un départ tardif.",
        "answer": "Le départ tardif dépend de la politique de l'hôtel et des disponibilités."
    },

    {
        "intent_id": "INT007",
        "intent_name": "late_check_out",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Можно ли запросить поздний выезд из отеля?",
        "ground_truth": "Вопрос касается возможности позднего выезда.",
        "answer": "Поздний выезд зависит от правил отеля и наличия свободных номеров."
    },


    # --------------------------------------------------------
    # INT008 - identification_required
    # --------------------------------------------------------

    {
        "intent_id": "INT008",
        "intent_name": "identification_required",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما هي وثيقة إثبات الهوية المطلوبة عند تسجيل الوصول؟",
        "ground_truth": "The question asks which identification document is required at check-in.",
        "answer": "The required identification document is specified in the hotel's identification policy."
    },

    {
        "intent_id": "INT008",
        "intent_name": "identification_required",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What identification document do I need when checking in?",
        "ground_truth": "The question asks which identification document is required at check-in.",
        "answer": "The required identification document is specified in the hotel's identification policy."
    },

    {
        "intent_id": "INT008",
        "intent_name": "identification_required",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?",
        "ground_truth": "La question demande quelle pièce d'identité est nécessaire lors de l'enregistrement.",
        "answer": "La pièce d'identité requise est indiquée dans la politique d'identification de l'hôtel."
    },

    {
        "intent_id": "INT008",
        "intent_name": "identification_required",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какой документ удостоверяющий личность нужно предъявить при регистрации?",
        "ground_truth": "Вопрос касается документа удостоверяющего личность, необходимого при регистрации.",
        "answer": "Требуемый документ удостоверяющий личность указан в правилах отеля."
    },
]


# ============================================================
# 12. CREATE DATAFRAME
# ============================================================

batch_df = pd.DataFrame(
    batch_content
)

# Add IDs
batch_df.insert(
    0,
    "faq_id",
    NEW_IDS
)

# Add remaining columns
batch_df["status"] = "generated"
batch_df["category"] = batch_df["intent_name"]
batch_df["source"] = "batch_02"
batch_df["attempts"] = 1
batch_df["difficulty"] = "Easy"


# ============================================================
# 13. REORDER COLUMNS
# ============================================================

batch_df = batch_df[
    REQUIRED_COLUMNS
]


# ============================================================
# 14. HARD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🔎 BATCH 02 VALIDATION")
print("=" * 100)


# ------------------------------------------------------------
# Exact row count
# ------------------------------------------------------------

assert len(batch_df) == 32, (
    f"❌ Expected 32 rows, found {len(batch_df)}"
)

print("✅ Exactly 32 questions.")


# ------------------------------------------------------------
# Exact IDs
# ------------------------------------------------------------

actual_ids = batch_df["faq_id"].tolist()

assert actual_ids == NEW_IDS, (
    "❌ FAQ IDs are incorrect.\n"
    f"Expected: {NEW_IDS}\n"
    f"Actual:   {actual_ids}"
)

print(
    f"✅ IDs: {NEW_IDS[0]} → {NEW_IDS[-1]}"
)


# ------------------------------------------------------------
# Duplicate IDs
# ------------------------------------------------------------

assert not batch_df["faq_id"].duplicated().any()

print("✅ No duplicate FAQ IDs.")


# ------------------------------------------------------------
# Empty questions
# ------------------------------------------------------------

empty_questions = (
    batch_df["question"]
    .isna()
    |
    batch_df["question"]
    .astype(str)
    .str.strip()
    .eq("")
)

assert not empty_questions.any(), (
    "❌ Empty questions detected."
)

print("✅ No empty questions.")


# ------------------------------------------------------------
# Empty ground truth
# ------------------------------------------------------------

assert (
    batch_df["ground_truth"]
    .notna()
    .all()
)

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")


# ------------------------------------------------------------
# Empty answers
# ------------------------------------------------------------

assert (
    batch_df["answer"]
    .notna()
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Answers complete.")


# ------------------------------------------------------------
# Duplicate questions inside batch
# ------------------------------------------------------------

batch_normalized = (
    batch_df["question"]
    .map(normalize_question)
)

duplicate_mask = (
    batch_normalized
    .duplicated(keep=False)
)

if duplicate_mask.any():

    print("\n❌ DUPLICATES INSIDE BATCH:")

    print(
        batch_df.loc[
            duplicate_mask,
            [
                "faq_id",
                "language",
                "intent_id",
                "question"
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Duplicate questions inside Batch 02."
    )

print("✅ No duplicate questions inside batch.")


# ------------------------------------------------------------
# Compare with existing dataset
# ------------------------------------------------------------

existing_conflicts = batch_df[
    batch_normalized.isin(
        existing_questions
    )
]

if not existing_conflicts.empty:

    print("\n❌ QUESTIONS ALREADY EXIST:")

    print(
        existing_conflicts[
            [
                "faq_id",
                "language",
                "intent_id",
                "question"
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Batch contains questions already "
        "present in the existing dataset."
    )

print(
    "✅ No questions overlap with existing 256."
)


# ============================================================
# 15. LANGUAGE BALANCE
# ============================================================

language_counts = (
    batch_df["language"]
    .value_counts()
    .to_dict()
)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert (
    language_counts
    == expected_language_counts
)

print(
    "✅ Language balance: "
    "Arabic 8 / English 8 / French 8 / Russian 8"
)


# ============================================================
# 16. INTENT BALANCE
# ============================================================

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .to_dict()
)

for intent_id in [
    "INT001",
    "INT002",
    "INT003",
    "INT004",
    "INT005",
    "INT006",
    "INT007",
    "INT008",
]:

    assert intent_counts.get(
        intent_id,
        0
    ) == 4

print(
    "✅ Intent balance: 4 questions × 8 intents"
)


# ============================================================
# 17. INTENT NAME CONSISTENCY
# ============================================================

intent_mapping = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for intent_id, intent_name in intent_mapping.items():

    subset = batch_df[
        batch_df["intent_id"]
        == intent_id
    ]

    assert (
        subset["intent_name"]
        == intent_name
    ).all()

print("✅ Intent ID ↔ Intent Name consistency.")


# ============================================================
# 18. SHOW BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 02 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question"
        ]
    ].to_string(index=False)
)


# ============================================================
# 19. SAVE BATCH SEPARATELY
# ============================================================

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

BATCH_PATH = (
    BATCH_DIR
    / "faq_batch_02.csv"
)

batch_df.to_csv(
    BATCH_PATH,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 20. FINAL CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 02 READY")
print("=" * 100)

print(
    f"""
Existing dataset : 256 questions
New batch        : 32 questions

FAQ IDs:
{NEW_IDS[0]} → {NEW_IDS[-1]}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 rows
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 256
✅ Ground truth complete
✅ Answers complete
✅ Language balance correct
✅ Intent balance correct

⚠️ IMPORTANT:
hotel_faq_final.csv was NOT modified.

📄 Batch file:
{BATCH_PATH}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 02 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

✅ Final dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 256
Columns : 13

Columns:
1. faq_id
2. intent_id
3. language
4. question_type
5. question
6. status
7. intent_name
8. ground_truth
9. category
10. source
11. attempts
12. difficulty
13. answer

✅ All required columns exist.

✅ Existing dataset contains exactly 256 questions.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Current rows : 256
Last FAQ ID  : FAQ0256

====================================================================================================
🚀 NEXT BATCH
====================================================================================================
Batch size : 32
IDs        : FAQ0257 → FAQ0288

====================================================================================================
📊 EXISTING DATASET SUMMARY
====================================================================================================

🌍 Languages:
language
Arabic     64
English    64
French     64
Russian    64
Name: count, dtype: int64

🎯 Intents:
  intent_id              intent_name  questions
0    INT001           hotel_location         32
1    INT002           hotel_category         32
2    INT003   reception_availability         32
3    INT004            check_in_time         32
4    INT005           check_out_time         32
5    INT006           early_check_in         32
6    INT007           late_check_out         32
7    INT008  identification_required         32

📝 Question Types:
question_type
Direct         96
Paraphrased    96
Scenario       64
Name: count, dtype: int64

====================================================================================================
🔎 BATCH 02 VALIDATION
====================================================================================================
✅ Exactly 32 questions.
✅ IDs: FAQ0257 → FAQ0288
✅ No duplicate FAQ IDs.
✅ No empty questions.
✅ Ground truth complete.
✅ Answers complete.
✅ No duplicate questions inside batch.
✅ No questions overlap with existing 256.
✅ Language balance: Arabic 8 / English 8 / French 8 / Russian 8
✅ Intent balance: 4 questions × 8 intents
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 BATCH 02 QUESTIONS
====================================================================================================
 faq_id intent_id language question_type                                                                 question
FAQ0257    INT001   Arabic   Paraphrased                        في أي منطقة من المدينة يقع فندق Nile Pearl Hotel؟
FAQ0258    INT001  English   Paraphrased                   Which part of the city is Nile Pearl Hotel located in?
FAQ0259    INT001   French   Paraphrased           Dans quel quartier de la ville se trouve le Nile Pearl Hotel ?
FAQ0260    INT001  Russian   Paraphrased                  В каком районе города находится отель Nile Pearl Hotel?
FAQ0261    INT002   Arabic   Paraphrased                                            ما فئة فندق Nile Pearl Hotel؟
FAQ0262    INT002  English   Paraphrased                                 What hotel category is Nile Pearl Hotel?
FAQ0263    INT002   French   Paraphrased                            Quelle est la catégorie du Nile Pearl Hotel ?
FAQ0264    INT002  Russian   Paraphrased                                 Какова категория отеля Nile Pearl Hotel?
FAQ0265    INT003   Arabic   Paraphrased                             هل مكتب استقبال الفندق يعمل على مدار الساعة؟
FAQ0266    INT003  English   Paraphrased                         Does the hotel reception operate 24 hours a day?
FAQ0267    INT003   French   Paraphrased              La réception de l'hôtel est-elle ouverte 24 heures sur 24 ?
FAQ0268    INT003  Russian   Paraphrased                      Работает ли стойка регистрации отеля круглосуточно?
FAQ0269    INT004   Arabic   Paraphrased                             ما هو الوقت المحدد لتسجيل الوصول إلى الفندق؟
FAQ0270    INT004  English   Paraphrased                              What is the hotel's standard check-in time?
FAQ0271    INT004   French   Paraphrased                      Quelle est l'heure habituelle d'arrivée à l'hôtel ?
FAQ0272    INT004  Russian   Paraphrased                      Какое стандартное время регистрации заезда в отеле?
FAQ0273    INT005   Arabic   Paraphrased                           ما هو الوقت المعتاد لتسجيل المغادرة من الفندق؟
FAQ0274    INT005  English   Paraphrased                             What is the hotel's standard check-out time?
FAQ0275    INT005   French   Paraphrased                     Quelle est l'heure habituelle de départ de l'hôtel ?
FAQ0276    INT005  Russian   Paraphrased                     Какое стандартное время регистрации выезда из отеля?
FAQ0277    INT006   Arabic   Paraphrased                                هل يسمح الفندق بتسجيل الوصول في وقت مبكر؟
FAQ0278    INT006  English   Paraphrased                                     Does the hotel allow early check-in?
FAQ0279    INT006   French   Paraphrased                        L'hôtel autorise-t-il l'enregistrement anticipé ?
FAQ0280    INT006  Russian   Paraphrased                          Разрешена ли в отеле ранняя регистрация заезда?
FAQ0281    INT007   Arabic   Paraphrased                               هل يمكنني طلب تسجيل المغادرة في وقت متأخر؟
FAQ0282    INT007  English   Paraphrased                                          Can I request a late check-out?
FAQ0283    INT007   French   Paraphrased                           Puis-je demander un départ tardif de l'hôtel ?
FAQ0284    INT007  Russian   Paraphrased                               Можно ли запросить поздний выезд из отеля?
FAQ0285    INT008   Arabic   Paraphrased                      ما هي وثيقة إثبات الهوية المطلوبة عند تسجيل الوصول؟
FAQ0286    INT008  English   Paraphrased                 What identification document do I need when checking in?
FAQ0287    INT008   French   Paraphrased     Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?
FAQ0288    INT008  Russian   Paraphrased Какой документ удостоверяющий личность нужно предъявить при регистрации?

====================================================================================================
🎉 BATCH 02 READY
====================================================================================================

Existing dataset : 256 questions
New batch        : 32 questions

FAQ IDs:
FAQ0257 → FAQ0288

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 rows
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 256
✅ Ground truth complete
✅ Answers complete
✅ Language balance correct
✅ Intent balance correct

⚠️ IMPORTANT:
hotel_faq_final.csv was NOT modified.

📄 Batch file:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_02.csv

====================================================================================================

In [10]:
from pathlib import Path
import pandas as pd
import re

# ============================================================
# 🏨 HOTEL AI - BATCH 02 FINAL CHECK
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 FINAL CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent")

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_02.csv"
)

# ============================================================
# 2. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

EXPECTED_INTENTS = {
    "INT001",
    "INT002",
    "INT003",
    "INT004",
    "INT005",
    "INT006",
    "INT007",
    "INT008",
}

INTENT_NAMES = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 3. CHECK FILES
# ============================================================

print("\n" + "=" * 100)
print("📂 FILE VALIDATION")
print("=" * 100)

assert PROJECT_ROOT.exists(), f"❌ Project root not found:\n{PROJECT_ROOT}"
assert DATASET_PATH.exists(), f"❌ Final dataset not found:\n{DATASET_PATH}"
assert BATCH_PATH.exists(), f"❌ Batch 02 not found:\n{BATCH_PATH}"

print("✅ Project root found.")
print("✅ Final dataset found.")
print("✅ Batch 02 found.")

# ============================================================
# 4. LOAD DATA
# ============================================================

df = pd.read_csv(DATASET_PATH, dtype=str).fillna("")
batch_df = pd.read_csv(BATCH_PATH, dtype=str).fillna("")

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Existing rows : {len(df)}")
print(f"Batch rows    : {len(batch_df)}")

# ============================================================
# 5. COLUMN CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_dataset = [
    col for col in REQUIRED_COLUMNS
    if col not in df.columns
]

missing_batch = [
    col for col in REQUIRED_COLUMNS
    if col not in batch_df.columns
]

assert not missing_dataset, (
    f"❌ Missing columns in final dataset: {missing_dataset}"
)

assert not missing_batch, (
    f"❌ Missing columns in Batch 02: {missing_batch}"
)

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Final dataset column order is incorrect."
)

assert list(batch_df.columns) == REQUIRED_COLUMNS, (
    "❌ Batch 02 column order is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 6. EXISTING DATASET CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔎 EXISTING DATASET CHECK")
print("=" * 100)

assert len(df) == 256, (
    f"❌ Expected 256 existing rows, found {len(df)}"
)

print("✅ Existing dataset contains exactly 256 questions.")

# ============================================================
# 7. BATCH SIZE
# ============================================================

print("\n" + "=" * 100)
print("📦 BATCH SIZE CHECK")
print("=" * 100)

assert len(batch_df) == 32, (
    f"❌ Batch 02 must contain exactly 32 rows, found {len(batch_df)}"
)

print("✅ Batch 02 contains exactly 32 questions.")

# ============================================================
# 8. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(257, 289)
]

actual_ids = batch_df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "\n❌ Batch 02 IDs are incorrect.\n"
    f"Expected:\n{expected_ids}\n\n"
    f"Actual:\n{actual_ids}"
)

assert batch_df["faq_id"].is_unique, (
    "❌ Duplicate FAQ IDs inside Batch 02."
)

assert df["faq_id"].is_unique, (
    "❌ Duplicate FAQ IDs inside existing dataset."
)

overlap_ids = set(df["faq_id"]) & set(batch_df["faq_id"])

assert not overlap_ids, (
    f"❌ Batch IDs overlap existing IDs:\n{sorted(overlap_ids)}"
)

print("✅ IDs are exactly FAQ0257 → FAQ0288.")
print("✅ No duplicate IDs inside batch.")
print("✅ No overlap with existing IDs.")

# ============================================================
# 9. QUESTION VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION VALIDATION")
print("=" * 100)

empty_questions = batch_df[
    batch_df["question"].str.strip() == ""
]

assert empty_questions.empty, (
    f"❌ Empty questions found:\n{empty_questions}"
)

assert batch_df["question"].is_unique, (
    "❌ Duplicate questions inside Batch 02."
)

existing_questions = set(
    df["question"]
    .str.strip()
    .str.casefold()
)

batch_questions = set(
    batch_df["question"]
    .str.strip()
    .str.casefold()
)

overlap_questions = existing_questions & batch_questions

assert not overlap_questions, (
    "❌ Batch 02 contains questions already existing "
    f"in the 256-question dataset:\n{sorted(overlap_questions)}"
)

print("✅ No empty questions.")
print("✅ No duplicate questions inside Batch 02.")
print("✅ No overlap with existing 256 questions.")

# ============================================================
# 10. LANGUAGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE VALIDATION")
print("=" * 100)

invalid_languages = set(batch_df["language"]) - EXPECTED_LANGUAGES

assert not invalid_languages, (
    f"❌ Invalid languages: {invalid_languages}"
)

language_counts = batch_df["language"].value_counts()

for language in EXPECTED_LANGUAGES:
    count = int(language_counts.get(language, 0))

    assert count == 8, (
        f"❌ {language}: expected 8, found {count}"
    )

print(language_counts.sort_index())
print("✅ Language balance: 8 × 4 languages.")

# ============================================================
# 11. INTENT VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT VALIDATION")
print("=" * 100)

invalid_intents = set(batch_df["intent_id"]) - EXPECTED_INTENTS

assert not invalid_intents, (
    f"❌ Invalid intent IDs: {invalid_intents}"
)

intent_counts = batch_df["intent_id"].value_counts()

for intent_id in sorted(EXPECTED_INTENTS):
    count = int(intent_counts.get(intent_id, 0))

    assert count == 4, (
        f"❌ {intent_id}: expected 4, found {count}"
    )

    expected_name = INTENT_NAMES[intent_id]

    actual_names = set(
        batch_df.loc[
            batch_df["intent_id"] == intent_id,
            "intent_name"
        ]
    )

    assert actual_names == {expected_name}, (
        f"❌ {intent_id} intent_name mismatch.\n"
        f"Expected: {expected_name}\n"
        f"Found: {actual_names}"
    )

print(intent_counts.sort_index())
print("✅ Intent balance: 4 × 8 intents.")
print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 12. QUESTION TYPE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE VALIDATION")
print("=" * 100)

allowed_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = set(batch_df["question_type"]) - allowed_types

assert not invalid_types, (
    f"❌ Invalid question types: {invalid_types}"
)

print(batch_df["question_type"].value_counts())

print("✅ All question types are valid.")

# ============================================================
# 13. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for column in REQUIRED_COLUMNS:

    missing = batch_df[column].isna().sum()

    empty = (
        batch_df[column]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    assert missing == 0, (
        f"❌ {column}: {missing} missing values"
    )

    assert empty == 0, (
        f"❌ {column}: {empty} empty values"
    )

    print(
        f"✅ {column:<18} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

# ============================================================
# 14. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert (
    batch_df["ground_truth"].str.strip() != ""
).all()

assert (
    batch_df["answer"].str.strip() != ""
).all()

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 15. STATUS / DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS / DIFFICULTY")
print("=" * 100)

print("Status:")
print(batch_df["status"].value_counts())

print("\nDifficulty:")
print(batch_df["difficulty"].value_counts())

print("✅ Status and difficulty fields are populated.")

# ============================================================
# 16. NORMALIZED DUPLICATE CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔁 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

def normalize_question(text):
    text = str(text).strip().casefold()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[؟?!.,;:]+$", "", text)
    return text

batch_normalized = batch_df["question"].apply(normalize_question)
existing_normalized = df["question"].apply(normalize_question)

assert not batch_normalized.duplicated().any(), (
    "❌ Normalized duplicate found inside Batch 02."
)

existing_set = set(existing_normalized)

normalized_overlap = [
    q for q in batch_normalized
    if q in existing_set
]

assert not normalized_overlap, (
    "❌ Normalized question overlap with existing dataset:\n"
    f"{normalized_overlap}"
)

print("✅ No normalized duplicates.")
print("✅ No normalized overlap with existing dataset.")

# ============================================================
# 17. FINAL PROJECTED DATASET CHECK
# ============================================================

print("\n" + "=" * 100)
print("📊 PROJECTED DATASET AFTER MERGE")
print("=" * 100)

merged_preview = pd.concat(
    [df, batch_df],
    ignore_index=True
)

assert len(merged_preview) == 288

print(f"Current dataset : {len(df)}")
print(f"Batch 02        : {len(batch_df)}")
print(f"After merge     : {len(merged_preview)}")

assert merged_preview["faq_id"].is_unique

print("✅ Projected dataset will contain exactly 288 questions.")
print("✅ All FAQ IDs will remain unique.")

# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 02 FINAL CHECK RESULT")
print("=" * 100)

print("""
🟢 BATCH 02 IS VALID

✅ 32 questions
✅ FAQ0257 → FAQ0288
✅ No duplicate IDs
✅ No duplicate questions
✅ No overlap with existing 256
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Normalized duplicate check passed
✅ Projected total = 288 questions

⚠️ hotel_faq_final.csv was NOT modified.
⚠️ This was a READ-ONLY validation.
""")

print("=" * 100)
print("🎉 SAFE TO MERGE BATCH 02")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 02 FINAL CHECK
====================================================================================================

====================================================================================================
📂 FILE VALIDATION
====================================================================================================
✅ Project root found.
✅ Final dataset found.
✅ Batch 02 found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Existing rows : 256
Batch rows    : 32

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
🔎 EXISTING DATASET CHECK
====================================================================================================
✅ Existing dataset contains exactly 256 questions.

====================================================================================================
📦 BATCH SIZE CHECK
====================================================================================================
✅ Batch 02 contains exactly 32 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0257 → FAQ0288.
✅ No duplicate IDs inside batch.
✅ No overlap with existing IDs.

====================================================================================================
📝 QUESTION VALIDATION
====================================================================================================
✅ No empty questions.
✅ No duplicate questions inside Batch 02.
✅ No overlap with existing 256 questions.

====================================================================================================
🌍 LANGUAGE VALIDATION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ Language balance: 8 × 4 languages.

====================================================================================================
🎯 INTENT VALIDATION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ Intent balance: 4 × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE VALIDATION
====================================================================================================
question_type
Paraphrased    32
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id             Missing: 0   Empty: 0
✅ intent_id          Missing: 0   Empty: 0
✅ language           Missing: 0   Empty: 0
✅ question_type      Missing: 0   Empty: 0
✅ question           Missing: 0   Empty: 0
✅ status             Missing: 0   Empty: 0
✅ intent_name        Missing: 0   Empty: 0
✅ ground_truth       Missing: 0   Empty: 0
✅ category           Missing: 0   Empty: 0
✅ source             Missing: 0   Empty: 0
✅ attempts           Missing: 0   Empty: 0
✅ difficulty         Missing: 0   Empty: 0
✅ answer             Missing: 0   Empty: 0

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📌 STATUS / DIFFICULTY
====================================================================================================
Status:
status
generated    32
Name: count, dtype: int64

Difficulty:
difficulty
Easy    32
Name: count, dtype: int64
✅ Status and difficulty fields are populated.

====================================================================================================
🔁 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicates.
✅ No normalized overlap with existing dataset.

====================================================================================================
📊 PROJECTED DATASET AFTER MERGE
====================================================================================================
Current dataset : 256
Batch 02        : 32
After merge     : 288
✅ Projected dataset will contain exactly 288 questions.
✅ All FAQ IDs will remain unique.

====================================================================================================
🏆 BATCH 02 FINAL CHECK RESULT
====================================================================================================

🟢 BATCH 02 IS VALID

✅ 32 questions
✅ FAQ0257 → FAQ0288
✅ No duplicate IDs
✅ No duplicate questions
✅ No overlap with existing 256
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Normalized duplicate check passed
✅ Projected total = 288 questions

⚠️ hotel_faq_final.csv was NOT modified.
⚠️ This was a READ-ONLY validation.

====================================================================================================
🎉 SAFE TO MERGE BATCH 02
====================================================================================================

In [11]:
from pathlib import Path
import pandas as pd
from datetime import datetime
import shutil
import re

# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 02
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 02 INTO FINAL DATASET")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_02.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "backups"
)

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ============================================================
# 2. VALIDATE FILES
# ============================================================

assert FINAL_PATH.exists(), (
    f"❌ Final dataset not found:\n{FINAL_PATH}"
)

assert BATCH_PATH.exists(), (
    f"❌ Batch 02 not found:\n{BATCH_PATH}"
)

print("\n📂 Files found.")
print(f"Final : {FINAL_PATH}")
print(f"Batch : {BATCH_PATH}")

# ============================================================
# 3. LOAD DATA
# ============================================================

df = pd.read_csv(
    FINAL_PATH,
    dtype=str
).fillna("")

batch_df = pd.read_csv(
    BATCH_PATH,
    dtype=str
).fillna("")

print("\n" + "=" * 100)
print("📊 BEFORE MERGE")
print("=" * 100)

print(f"Existing dataset : {len(df)}")
print(f"Batch 02         : {len(batch_df)}")

# ============================================================
# 4. BASIC SAFETY CHECKS
# ============================================================

assert len(df) == 256, (
    f"❌ Expected existing dataset = 256, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Expected Batch 02 = 32, found {len(batch_df)}"
)

print("✅ Existing dataset = 256")
print("✅ Batch 02 = 32")

# ============================================================
# 5. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Final dataset columns/order are incorrect."
)

assert list(batch_df.columns) == REQUIRED_COLUMNS, (
    "❌ Batch 02 columns/order are incorrect."
)

print("✅ All 13 columns are correct.")

# ============================================================
# 6. BATCH ID VALIDATION
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(257, 289)
]

assert batch_df["faq_id"].tolist() == expected_ids, (
    "❌ Batch 02 IDs are not exactly FAQ0257 → FAQ0288."
)

print("✅ Batch IDs = FAQ0257 → FAQ0288")

# ============================================================
# 7. DUPLICATE ID CHECK
# ============================================================

assert df["faq_id"].is_unique, (
    "❌ Existing dataset contains duplicate FAQ IDs."
)

assert batch_df["faq_id"].is_unique, (
    "❌ Batch 02 contains duplicate FAQ IDs."
)

overlap_ids = (
    set(df["faq_id"])
    &
    set(batch_df["faq_id"])
)

assert not overlap_ids, (
    f"❌ FAQ ID overlap detected:\n{sorted(overlap_ids)}"
)

print("✅ No FAQ ID conflicts.")

# ============================================================
# 8. QUESTION NORMALIZATION
# ============================================================

def normalize_question(text):

    text = str(text).strip().casefold()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[؟?!.,;:]+$",
        "",
        text
    )

    return text


existing_questions = (
    df["question"]
    .apply(normalize_question)
)

batch_questions = (
    batch_df["question"]
    .apply(normalize_question)
)

# ============================================================
# 9. DUPLICATE QUESTIONS
# ============================================================

assert not existing_questions.duplicated().any(), (
    "❌ Existing dataset contains duplicate questions."
)

assert not batch_questions.duplicated().any(), (
    "❌ Batch 02 contains duplicate questions."
)

question_overlap = (
    set(existing_questions)
    &
    set(batch_questions)
)

assert not question_overlap, (
    "❌ Question overlap detected between existing dataset "
    "and Batch 02."
)

print("✅ No duplicate questions.")
print("✅ No question overlap.")

# ============================================================
# 10. REQUIRED DATA CHECK
# ============================================================

for column in REQUIRED_COLUMNS:

    assert (
        batch_df[column]
        .astype(str)
        .str.strip()
        .ne("")
        .all()
    ), (
        f"❌ Empty value detected in column: {column}"
    )

print("✅ All Batch 02 required fields are complete.")

# ============================================================
# 11. CREATE MERGED DATAFRAME
# ============================================================

merged_df = pd.concat(
    [
        df,
        batch_df
    ],
    ignore_index=True
)

print("\n" + "=" * 100)
print("🔗 MERGING")
print("=" * 100)

print(
    f"{len(df)} existing + "
    f"{len(batch_df)} new = "
    f"{len(merged_df)} total"
)

assert len(merged_df) == 288

print("✅ Merge created in memory.")

# ============================================================
# 12. FINAL MERGED VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🔎 POST-MERGE VALIDATION")
print("=" * 100)

# Rows
assert len(merged_df) == 288

# IDs
assert merged_df["faq_id"].is_unique

# Questions
merged_normalized = (
    merged_df["question"]
    .apply(normalize_question)
)

assert not merged_normalized.duplicated().any()

# Empty questions
assert (
    merged_df["question"]
    .str.strip()
    .ne("")
    .all()
)

# Ground truth
assert (
    merged_df["ground_truth"]
    .str.strip()
    .ne("")
    .all()
)

# Answers
assert (
    merged_df["answer"]
    .str.strip()
    .ne("")
    .all()
)

print("✅ Total rows = 288")
print("✅ FAQ IDs unique")
print("✅ Questions unique")
print("✅ No empty questions")
print("✅ Ground truth complete")
print("✅ Answers complete")

# ============================================================
# 13. LANGUAGE BALANCE
# ============================================================

language_counts = (
    merged_df["language"]
    .value_counts()
    .sort_index()
)

print("\n🌍 Languages:")
print(language_counts)

expected_language_count = {
    "Arabic": 72,
    "English": 72,
    "French": 72,
    "Russian": 72,
}

for language, expected in expected_language_count.items():

    actual = int(
        language_counts.get(
            language,
            0
        )
    )

    assert actual == expected, (
        f"❌ {language}: expected {expected}, found {actual}"
    )

print("✅ PERFECT LANGUAGE BALANCE: 72 × 4")

# ============================================================
# 14. INTENT BALANCE
# ============================================================

intent_counts = (
    merged_df["intent_id"]
    .value_counts()
    .sort_index()
)

print("\n🎯 Intents:")
print(intent_counts)

for intent_id in [
    "INT001",
    "INT002",
    "INT003",
    "INT004",
    "INT005",
    "INT006",
    "INT007",
    "INT008",
]:

    actual = int(
        intent_counts.get(
            intent_id,
            0
        )
    )

    assert actual == 36, (
        f"❌ {intent_id}: expected 36, found {actual}"
    )

print("✅ PERFECT INTENT BALANCE: 36 × 8")

# ============================================================
# 15. INTENT × LANGUAGE
# ============================================================

cross_table = pd.crosstab(
    merged_df["intent_id"],
    merged_df["language"]
)

print("\n🌍 INTENT × LANGUAGE:")
print(cross_table)

for intent_id in cross_table.index:

    for language in [
        "Arabic",
        "English",
        "French",
        "Russian",
    ]:

        value = int(
            cross_table.loc[
                intent_id,
                language
            ]
        )

        assert value == 9, (
            f"❌ {intent_id} × {language}: "
            f"expected 9, found {value}"
        )

print("✅ PERFECT: 9 questions × 8 intents × 4 languages")

# ============================================================
# 16. BACKUP EXISTING 256
# ============================================================

print("\n" + "=" * 100)
print("🛡️ CREATING BACKUP")
print("=" * 100)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_batch_02_{timestamp}.csv"
)

shutil.copy2(
    FINAL_PATH,
    backup_path
)

assert backup_path.exists()

print(f"✅ Backup created:")
print(backup_path)

# ============================================================
# 17. SAVE MERGED DATASET
# ============================================================

print("\n" + "=" * 100)
print("💾 SAVING MERGED DATASET")
print("=" * 100)

TEMP_PATH = FINAL_PATH.with_suffix(
    ".tmp.csv"
)

# Save temporary first
merged_df.to_csv(
    TEMP_PATH,
    index=False,
    encoding="utf-8-sig"
)

assert TEMP_PATH.exists()

# Replace final only after successful save
TEMP_PATH.replace(FINAL_PATH)

print("✅ Final dataset updated.")

# ============================================================
# 18. RELOAD FROM DISK
# ============================================================

print("\n" + "=" * 100)
print("🔄 RELOADING SAVED DATASET")
print("=" * 100)

final_check = pd.read_csv(
    FINAL_PATH,
    dtype=str
).fillna("")

assert len(final_check) == 288

assert list(final_check.columns) == REQUIRED_COLUMNS

assert final_check["faq_id"].is_unique

final_questions = (
    final_check["question"]
    .apply(normalize_question)
)

assert not final_questions.duplicated().any()

assert (
    final_check["ground_truth"]
    .str.strip()
    .ne("")
    .all()
)

assert (
    final_check["answer"]
    .str.strip()
    .ne("")
    .all()
)

print("✅ Saved file reloaded successfully.")
print("✅ 288 rows confirmed.")
print("✅ No duplicate IDs.")
print("✅ No duplicate questions.")
print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 19. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 02 MERGE COMPLETED")
print("=" * 100)

print(f"""
🟢 SUCCESS

Previous dataset : 256
Batch 02         : 32
Final dataset    : 288

New IDs:
FAQ0257 → FAQ0288

Languages:
Arabic   : 72
English  : 72
French   : 72
Russian  : 72

Intents:
INT001 : 36
INT002 : 36
INT003 : 36
INT004 : 36
INT005 : 36
INT006 : 36
INT007 : 36
INT008 : 36

Backup:
{backup_path}

Final dataset:
{FINAL_PATH}

✅ Batch 02 successfully merged.
✅ Dataset now contains 288 questions.
""")

print("=" * 100)
print("🚀 READY FOR BATCH 03")
print("=" * 100)
print("Next IDs: FAQ0289 → FAQ0320")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 02 INTO FINAL DATASET
====================================================================================================

📂 Files found.
Final : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
Batch : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_02.csv

====================================================================================================
📊 BEFORE MERGE
====================================================================================================
Existing dataset : 256
Batch 02         : 32
✅ Existing dataset = 256
✅ Batch 02 = 32
✅ All 13 columns are correct.
✅ Batch IDs = FAQ0257 → FAQ0288
✅ No FAQ ID conflicts.
✅ No duplicate questions.
✅ No question overlap.
✅ All Batch 02 required fields are complete.

====================================================================================================
🔗 MERGING
====================================================================================================
256 existing + 32 new = 288 total
✅ Merge created in memory.

====================================================================================================
🔎 POST-MERGE VALIDATION
====================================================================================================
✅ Total rows = 288
✅ FAQ IDs unique
✅ Questions unique
✅ No empty questions
✅ Ground truth complete
✅ Answers complete

🌍 Languages:
language
Arabic     72
English    72
French     72
Russian    72
Name: count, dtype: int64
✅ PERFECT LANGUAGE BALANCE: 72 × 4

🎯 Intents:
intent_id
INT001    36
INT002    36
INT003    36
INT004    36
INT005    36
INT006    36
INT007    36
INT008    36
Name: count, dtype: int64
✅ PERFECT INTENT BALANCE: 36 × 8

🌍 INTENT × LANGUAGE:
language   Arabic  English  French  Russian
intent_id
INT001          9        9       9        9
INT002          9        9       9        9
INT003          9        9       9        9
INT004          9        9       9        9
INT005          9        9       9        9
INT006          9        9       9        9
INT007          9        9       9        9
INT008          9        9       9        9
✅ PERFECT: 9 questions × 8 intents × 4 languages

====================================================================================================
🛡️ CREATING BACKUP
====================================================================================================
✅ Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/backups/hotel_faq_before_batch_02_20260821_142821.csv

====================================================================================================
💾 SAVING MERGED DATASET
====================================================================================================
✅ Final dataset updated.

====================================================================================================
🔄 RELOADING SAVED DATASET
====================================================================================================
✅ Saved file reloaded successfully.
✅ 288 rows confirmed.
✅ No duplicate IDs.
✅ No duplicate questions.
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🏆 BATCH 02 MERGE COMPLETED
====================================================================================================

🟢 SUCCESS

Previous dataset : 256
Batch 02         : 32
Final dataset    : 288

New IDs:
FAQ0257 → FAQ0288

Languages:
Arabic   : 72
English  : 72
French   : 72
Russian  : 72

Intents:
INT001 : 36
INT002 : 36
INT003 : 36
INT004 : 36
INT005 : 36
INT006 : 36
INT007 : 36
INT008 : 36

Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/backups/hotel_faq_before_batch_02_20260821_142821.csv

Final dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

✅ Batch 02 successfully merged.
✅ Dataset now contains 288 questions.

====================================================================================================
🚀 READY FOR BATCH 03
====================================================================================================
Next IDs: FAQ0289 → FAQ0320
====================================================================================================

In [12]:
from pathlib import Path
import pandas as pd
import re

# ============================================================
# 🏨 HOTEL AI - FINAL CHECK AFTER BATCH 02 MERGE
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - FINAL DATASET CHECK — 288 QUESTIONS")
print("=" * 100)

# ============================================================
# 1. AUTO DETECT PROJECT
# ============================================================

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = None

for root in possible_roots:
    if root.exists():
        PROJECT_ROOT = root
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project root was not found."
    )

print(f"\n📂 Project root:")
print(PROJECT_ROOT)

# ============================================================
# 2. FINAL DATASET
# ============================================================

FINAL_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not FINAL_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{FINAL_PATH}"
    )

print("\n✅ Final dataset found:")
print(FINAL_PATH)

# ============================================================
# 3. LOAD DATA
# ============================================================

df = pd.read_csv(
    FINAL_PATH,
    dtype=str
).fillna("")

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# ============================================================
# 4. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Column names/order are incorrect."
)

print("\n✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 5. ROW COUNT
# ============================================================

assert len(df) == 288, (
    f"❌ Expected 288 rows, found {len(df)}"
)

print("\n✅ Exactly 288 questions.")

# ============================================================
# 6. FAQ ID FORMAT
# ============================================================

faq_pattern = re.compile(r"^FAQ\d{4}$")

invalid_ids = [
    x for x in df["faq_id"]
    if not faq_pattern.match(str(x))
]

assert not invalid_ids, (
    f"❌ Invalid FAQ IDs:\n{invalid_ids}"
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# 7. FAQ ID UNIQUENESS
# ============================================================

assert df["faq_id"].is_unique, (
    "❌ Duplicate FAQ IDs found."
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 8. EXPECTED FAQ ID SEQUENCE
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(9, 289)
]

actual_ids = df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ ID sequence is incorrect.\n"
    f"Expected first: {expected_ids[:5]}\n"
    f"Actual first  : {actual_ids[:5]}\n"
    f"Expected last : {expected_ids[-5:]}\n"
    f"Actual last   : {actual_ids[-5:]}"
)

print("✅ FAQ IDs are continuous: FAQ0009 → FAQ0288.")

# ============================================================
# 9. EMPTY REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for column in REQUIRED_COLUMNS:

    missing = int(df[column].isna().sum())

    empty = int(
        df[column]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {column:<20} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

# ============================================================
# 10. QUESTION NORMALIZATION
# ============================================================

def normalize_question(text):

    text = str(text).strip().casefold()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r"[؟?!.,;:]+$",
        "",
        text
    )

    return text

normalized_questions = (
    df["question"]
    .apply(normalize_question)
)

# ============================================================
# 11. DUPLICATE QUESTIONS
# ============================================================

duplicate_mask = (
    normalized_questions
    .duplicated(keep=False)
)

duplicate_questions = df.loc[
    duplicate_mask,
    ["faq_id", "question"]
]

assert duplicate_questions.empty, (
    "❌ Duplicate questions found:\n"
    f"{duplicate_questions.to_string(index=False)}"
)

print("\n" + "=" * 100)
print("🔁 DUPLICATE QUESTION CHECK")
print("=" * 100)

print("✅ Exact/normalized duplicate questions: 0")

# ============================================================
# 12. LANGUAGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE VALIDATION")
print("=" * 100)

language_counts = (
    df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

expected_languages = {
    "Arabic": 72,
    "English": 72,
    "French": 72,
    "Russian": 72,
}

assert set(language_counts.index) == set(
    expected_languages.keys()
)

for language, expected in expected_languages.items():

    actual = int(
        language_counts[language]
    )

    assert actual == expected, (
        f"❌ {language}: "
        f"expected {expected}, found {actual}"
    )

print("\n✅ PERFECT LANGUAGE BALANCE")
print("Arabic 72 | English 72 | French 72 | Russian 72")

# ============================================================
# 13. INTENT VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT VALIDATION")
print("=" * 100)

intent_counts = (
    df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

expected_intents = [
    "INT001",
    "INT002",
    "INT003",
    "INT004",
    "INT005",
    "INT006",
    "INT007",
    "INT008",
]

assert set(intent_counts.index) == set(
    expected_intents
)

for intent in expected_intents:

    assert int(
        intent_counts[intent]
    ) == 36

print("\n✅ PERFECT INTENT BALANCE")
print("36 questions × 8 intents")

# ============================================================
# 14. INTENT ↔ INTENT NAME
# ============================================================

intent_mapping = (
    df.groupby("intent_id")["intent_name"]
    .nunique()
)

assert (intent_mapping == 1).all()

print("✅ Every intent_id maps to exactly one intent_name.")

# ============================================================
# 15. INTENT × LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 INTENT × LANGUAGE BALANCE")
print("=" * 100)

cross = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(cross)

for intent in expected_intents:

    for language in expected_languages:

        assert int(
            cross.loc[intent, language]
        ) == 9

print("\n✅ PERFECT")
print("9 questions × 8 intents × 4 languages")

# ============================================================
# 16. QUESTION TYPE
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(question_type_counts)

allowed_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert set(question_type_counts.index).issubset(
    allowed_types
)

print("✅ All question types are valid.")

# ============================================================
# 17. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS")
print("=" * 100)

print(
    df["status"].value_counts()
)

assert (
    df["status"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Status values are populated.")

# ============================================================
# 18. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📊 DIFFICULTY")
print("=" * 100)

print(
    df["difficulty"].value_counts()
)

assert (
    df["difficulty"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Difficulty values are populated.")

# ============================================================
# 19. GROUND TRUTH / ANSWERS
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWERS")
print("=" * 100)

assert (
    df["ground_truth"]
    .str.strip()
    .ne("")
    .all()
)

assert (
    df["answer"]
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 20. QUESTION LENGTH
# ============================================================

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

print("\n" + "=" * 100)
print("📏 QUESTION LENGTH")
print("=" * 100)

print(f"Shortest : {question_lengths.min()} characters")
print(f"Longest  : {question_lengths.max()} characters")
print(f"Average  : {question_lengths.mean():.2f} characters")

assert (
    question_lengths > 0
).all()

print("✅ No empty/zero-length questions.")

# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET CHECK RESULT")
print("=" * 100)

print("""
🟢 DATASET IS VALID

✅ 288 total questions
✅ FAQ0009 → FAQ0288
✅ No duplicate FAQ IDs
✅ No duplicate questions
✅ No empty questions
✅ 72 Arabic
✅ 72 English
✅ 72 French
✅ 72 Russian
✅ 36 questions per intent
✅ Intent ↔ Intent Name consistent
✅ 9 questions per intent/language combination
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Question types valid
✅ Status populated
✅ Difficulty populated

🎉 BATCH 02 IS SUCCESSFULLY MERGED.

🚀 NEXT BATCH:
FAQ0289 → FAQ0320
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FINAL DATASET CHECK — 288 QUESTIONS
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

✅ Final dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 288
Columns : 13

Columns:
1. faq_id
2. intent_id
3. language
4. question_type
5. question
6. status
7. intent_name
8. ground_truth
9. category
10. source
11. attempts
12. difficulty
13. answer

✅ All 13 required columns exist.
✅ Column order is correct.

✅ Exactly 288 questions.
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

AssertionError: ❌ FAQ ID sequence is incorrect.
Expected first: ['FAQ0009', 'FAQ0010', 'FAQ0011', 'FAQ0012', 'FAQ0013']
Actual first  : ['FAQ0009', 'FAQ0010', 'FAQ0011', 'FAQ0012', 'FAQ0013']
Expected last : ['FAQ0284', 'FAQ0285', 'FAQ0286', 'FAQ0287', 'FAQ0288']
Actual last   : ['FAQ0284', 'FAQ0285', 'FAQ0286', 'FAQ0287', 'FAQ0288']

In [13]:
from pathlib import Path
import pandas as pd
import re

# ============================================================
# 🏨 HOTEL AI - FAQ ID DIAGNOSTIC CHECK
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - FAQ ID DIAGNOSTIC CHECK")
print("=" * 100)

# ------------------------------------------------------------
# 1. AUTO DETECT PROJECT
# ------------------------------------------------------------

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = next(
    (p for p in possible_roots if p.exists()),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project root not found."
    )

FINAL_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not FINAL_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{FINAL_PATH}"
    )

print(f"\n📂 Dataset:")
print(FINAL_PATH)

# ------------------------------------------------------------
# 2. LOAD
# ------------------------------------------------------------

df = pd.read_csv(
    FINAL_PATH,
    dtype=str
).fillna("")

print(f"\n📊 Rows: {len(df)}")

# ------------------------------------------------------------
# 3. EXTRACT NUMERIC ID
# ------------------------------------------------------------

df["_faq_num"] = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"(\d+)$")[0]
    .astype(int)
)

# ------------------------------------------------------------
# 4. CHECK DUPLICATES
# ------------------------------------------------------------

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

print("\n" + "=" * 100)
print("🆔 DUPLICATE ID CHECK")
print("=" * 100)

if duplicate_ids.empty:
    print("✅ No duplicate FAQ IDs.")
else:
    print("❌ Duplicate IDs found:")
    print(
        duplicate_ids[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ------------------------------------------------------------
# 5. CHECK MISSING IDS
# ------------------------------------------------------------

expected_numbers = set(
    range(9, 289)
)

actual_numbers = set(
    df["_faq_num"]
)

missing_numbers = sorted(
    expected_numbers - actual_numbers
)

extra_numbers = sorted(
    actual_numbers - expected_numbers
)

print("\n" + "=" * 100)
print("🔎 MISSING / EXTRA IDs")
print("=" * 100)

if not missing_numbers:
    print("✅ No missing IDs.")
else:
    print("❌ Missing IDs:")
    print(
        [
            f"FAQ{x:04d}"
            for x in missing_numbers
        ]
    )

if not extra_numbers:
    print("✅ No extra IDs.")
else:
    print("❌ Extra IDs:")
    print(
        [
            f"FAQ{x:04d}"
            for x in extra_numbers
        ]
    )

# ------------------------------------------------------------
# 6. CHECK ORDER
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🔢 ORDER CHECK")
print("=" * 100)

actual = df["_faq_num"].tolist()
expected = list(range(9, 289))

wrong_positions = []

for position, (a, e) in enumerate(
    zip(actual, expected),
    start=1
):

    if a != e:
        wrong_positions.append(
            {
                "row_position": position,
                "expected": f"FAQ{e:04d}",
                "actual": f"FAQ{a:04d}",
            }
        )

if not wrong_positions:

    print(
        "✅ FAQ IDs are perfectly ordered."
    )

else:

    print(
        f"❌ {len(wrong_positions)} "
        "position(s) are out of order."
    )

    print("\nFirst problems:")

    for item in wrong_positions[:20]:
        print(
            f"Row {item['row_position']}: "
            f"Expected {item['expected']} "
            f"but found {item['actual']}"
        )

# ------------------------------------------------------------
# 7. SHOW PROBLEM AREA
# ------------------------------------------------------------

if wrong_positions:

    first_problem = (
        wrong_positions[0]["row_position"]
    )

    start = max(
        0,
        first_problem - 5
    )

    end = min(
        len(df),
        first_problem + 5
    )

    print("\n" + "=" * 100)
    print("📍 FIRST PROBLEM AREA")
    print("=" * 100)

    print(
        df.iloc[
            start:end
        ][
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ------------------------------------------------------------
# 8. FINAL ID RANGE
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("📌 ID RANGE")
print("=" * 100)

print(
    f"First ID : {df['faq_id'].iloc[0]}"
)

print(
    f"Last ID  : {df['faq_id'].iloc[-1]}"
)

print(
    f"Min ID   : FAQ{df['_faq_num'].min():04d}"
)

print(
    f"Max ID   : FAQ{df['_faq_num'].max():04d}"
)

# ------------------------------------------------------------
# 9. CLEAN TEMP COLUMN
# ------------------------------------------------------------

df.drop(
    columns=["_faq_num"],
    inplace=True
)

# ------------------------------------------------------------
# 10. RESULT
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🏁 DIAGNOSTIC RESULT")
print("=" * 100)

if (
    not duplicate_ids.empty
    or missing_numbers
    or extra_numbers
    or wrong_positions
):

    print("""
🔴 THERE IS AN ID/ORDER ISSUE.

⚠️ DO NOT MODIFY THE DATASET YET.
⚠️ DO NOT GENERATE BATCH 03 YET.

The output above shows exactly where the problem is.
""")

else:

    print("""
🟢 FAQ ID STRUCTURE IS PERFECT.

✅ FAQ0009 → FAQ0288
✅ 280 IDs
✅ No duplicates
✅ No missing IDs
✅ No extra IDs
✅ Correct order

🚀 READY FOR THE FULL 288-QUESTION CHECK.
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FAQ ID DIAGNOSTIC CHECK
====================================================================================================

📂 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

📊 Rows: 288

====================================================================================================
🆔 DUPLICATE ID CHECK
====================================================================================================
✅ No duplicate FAQ IDs.

====================================================================================================
🔎 MISSING / EXTRA IDs
====================================================================================================
✅ No missing IDs.
❌ Extra IDs:
['FAQ0001', 'FAQ0002', 'FAQ0003', 'FAQ0004', 'FAQ0005', 'FAQ0006', 'FAQ0007', 'FAQ0008']

====================================================================================================
🔢 ORDER CHECK
====================================================================================================
❌ 216 position(s) are out of order.

First problems:
Row 9: Expected FAQ0017 but found FAQ0001
Row 10: Expected FAQ0018 but found FAQ0002
Row 11: Expected FAQ0019 but found FAQ0003
Row 12: Expected FAQ0020 but found FAQ0004
Row 13: Expected FAQ0021 but found FAQ0005
Row 14: Expected FAQ0022 but found FAQ0006
Row 15: Expected FAQ0023 but found FAQ0007
Row 16: Expected FAQ0024 but found FAQ0008
Row 17: Expected FAQ0025 but found FAQ0017
Row 18: Expected FAQ0026 but found FAQ0018
Row 19: Expected FAQ0027 but found FAQ0019
Row 20: Expected FAQ0028 but found FAQ0020
Row 21: Expected FAQ0029 but found FAQ0021
Row 22: Expected FAQ0030 but found FAQ0022
Row 23: Expected FAQ0031 but found FAQ0023
Row 24: Expected FAQ0032 but found FAQ0024
Row 25: Expected FAQ0033 but found FAQ0025
Row 26: Expected FAQ0034 but found FAQ0026
Row 27: Expected FAQ0035 but found FAQ0027
Row 28: Expected FAQ0036 but found FAQ0028

====================================================================================================
📍 FIRST PROBLEM AREA
====================================================================================================
 faq_id intent_id language                                                                                                question
FAQ0013    INT001   Arabic                                                                  في أي منطقة يقع فندق Nile Pearl Hotel؟
FAQ0014    INT001   Arabic                                                       كيف يمكنني الوصول إلى موقع فندق Nile Pearl Hotel؟
FAQ0015    INT001   Arabic                    أنا مهتم بزيارة مصر وحجز غرفة في Nile Pearl Hotel، فهل يمكنك معرفة موقعه في القاهرة؟
FAQ0016    INT001   Arabic أنا أخطط لزيارة مصر وقمت بالبحث عن فندق Nile Pearl Hotel، هل يمكنني أن أعرف موقع هذا الفندق في القاهرة؟
FAQ0001    INT001  English                                                                      Where is Nile Pearl Hotel located?
FAQ0002    INT001  English                                                                     Where is Nile Pearl Hotel situated?
FAQ0003    INT001  English                                                              In which city is Nile Pearl Hotel located?
FAQ0004    INT001  English                                                          In which city can I find the Nile Pearl Hotel?
FAQ0005    INT001  English                                                                  Where can I find the Nile Pearl Hotel?
FAQ0006    INT001  English                                                      In which major city can Nile Pearl Hotel be found?

====================================================================================================
📌 ID RANGE
====================================================================================================
First ID : FAQ0009
Last ID  : FAQ0288
Min ID   : FAQ0001
Max ID   : FAQ0288

====================================================================================================
🏁 DIAGNOSTIC RESULT
====================================================================================================

🔴 THERE IS AN ID/ORDER ISSUE.

⚠️ DO NOT MODIFY THE DATASET YET.
⚠️ DO NOT GENERATE BATCH 03 YET.

The output above shows exactly where the problem is.

====================================================================================================

In [14]:
from pathlib import Path
import pandas as pd

# ============================================================
# 🏨 HOTEL AI - FIX FAQ ORDER
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print("=" * 100)
print("🏨 HOTEL AI - FIX FAQ ID ORDER")
print("=" * 100)

# ============================================================
# 1. CHECK FILE
# ============================================================

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

print(f"✅ Dataset found:\n{DATASET_PATH}")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(DATASET_PATH)

print(f"\n📊 Rows before: {len(df)}")

# ============================================================
# 3. CHECK REQUIRED COLUMN
# ============================================================

if "faq_id" not in df.columns:
    raise ValueError("❌ faq_id column not found.")

# ============================================================
# 4. SAVE ORIGINAL CONTENT FOR SAFETY
# ============================================================

original = df.copy()

# ============================================================
# 5. CHECK DUPLICATE IDs
# ============================================================

if df["faq_id"].duplicated().any():
    duplicates = df.loc[
        df["faq_id"].duplicated(keep=False),
        "faq_id"
    ].tolist()

    raise ValueError(
        f"❌ Duplicate FAQ IDs found:\n{duplicates}"
    )

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 6. EXTRACT NUMBER
# ============================================================

df["_id_number"] = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d+)", expand=False)
    .astype(int)
)

# ============================================================
# 7. SORT BY FAQ ID
# ============================================================

df = (
    df.sort_values(
        "_id_number",
        ascending=True,
        kind="stable"
    )
    .drop(columns="_id_number")
    .reset_index(drop=True)
)

# ============================================================
# 8. EXPECTED IDs
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 289)
]

actual_ids = df["faq_id"].tolist()

# ============================================================
# 9. VERIFY EXACT ORDER
# ============================================================

if actual_ids != expected_ids:

    print("\n❌ Order is still incorrect.")

    for i, (actual, expected) in enumerate(
        zip(actual_ids, expected_ids)
    ):
        if actual != expected:
            print(
                f"Position {i + 1}: "
                f"Expected {expected}, "
                f"Found {actual}"
            )

    raise AssertionError(
        "❌ FAQ ID order validation failed."
    )

print(
    "\n✅ FAQ IDs are perfectly ordered:"
    "\n   FAQ0001 → FAQ0288"
)

# ============================================================
# 10. VERIFY ROW COUNT
# ============================================================

assert len(df) == 288

print("✅ Row count: 288")

# ============================================================
# 11. VERIFY NO QUESTIONS LOST
# ============================================================

before_questions = set(
    original["faq_id"].astype(str)
)

after_questions = set(
    df["faq_id"].astype(str)
)

assert before_questions == after_questions

print("✅ No FAQ IDs were lost or added.")

# ============================================================
# 12. VERIFY ALL COLUMNS PRESERVED
# ============================================================

assert df.columns.tolist() == original.columns.tolist()

print("✅ Column structure preserved.")

# ============================================================
# 13. SAVE FIXED DATASET
# ============================================================

df.to_csv(
    DATASET_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(
    f"\n💾 Dataset saved successfully:\n"
    f"{DATASET_PATH}"
)

# ============================================================
# 14. FINAL DISPLAY
# ============================================================

print("\n" + "=" * 100)
print("🏁 FINAL CHECK")
print("=" * 100)

print("\nFirst 12 IDs:")
print(df["faq_id"].head(12).tolist())

print("\nLast 12 IDs:")
print(df["faq_id"].tail(12).tolist())

print("\n" + "=" * 100)
print("🎉 PROBLEM FIXED")
print("=" * 100)

print("""
✅ 288 questions preserved
✅ FAQ0001 → FAQ0288
✅ No duplicate IDs
✅ No missing IDs
✅ No questions deleted
✅ No questions generated
✅ Only row order was corrected
""")

====================================================================================================
🏨 HOTEL AI - FIX FAQ ID ORDER
====================================================================================================
✅ Dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

📊 Rows before: 288
✅ No duplicate FAQ IDs.

✅ FAQ IDs are perfectly ordered:
   FAQ0001 → FAQ0288
✅ Row count: 288
✅ No FAQ IDs were lost or added.
✅ Column structure preserved.

💾 Dataset saved successfully:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏁 FINAL CHECK
====================================================================================================

First 12 IDs:
['FAQ0001', 'FAQ0002', 'FAQ0003', 'FAQ0004', 'FAQ0005', 'FAQ0006', 'FAQ0007', 'FAQ0008', 'FAQ0009', 'FAQ0010', 'FAQ0011', 'FAQ0012']

Last 12 IDs:
['FAQ0277', 'FAQ0278', 'FAQ0279', 'FAQ0280', 'FAQ0281', 'FAQ0282', 'FAQ0283', 'FAQ0284', 'FAQ0285', 'FAQ0286', 'FAQ0287', 'FAQ0288']

====================================================================================================
🎉 PROBLEM FIXED
====================================================================================================

✅ 288 questions preserved
✅ FAQ0001 → FAQ0288
✅ No duplicate IDs
✅ No missing IDs
✅ No questions deleted
✅ No questions generated
✅ Only row order was corrected

In [15]:
# ============================================================
# 🏨 HOTEL AI - FINAL DATASET CHECK
# READ-ONLY — DOES NOT MODIFY THE DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re

print("=" * 100)
print("🏨 HOTEL AI - FINAL DATASET CHECK")
print("=" * 100)

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print(f"\n📂 Dataset:")
print(DATASET_PATH)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"❌ Project root not found:\n{PROJECT_ROOT}"
    )

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

print("✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

extra_columns = [
    col for col in df.columns
    if col not in required_columns
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

assert df.columns.tolist() == required_columns, (
    "❌ Column order is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

if extra_columns:
    print(f"⚠️ Extra columns: {extra_columns}")

# ============================================================
# 4. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

assert len(df) == 288, (
    f"❌ Expected 288 rows, found {len(df)}"
)

print("✅ Dataset contains exactly 288 questions.")

# ============================================================
# 5. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

invalid_ids = df[
    ~df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
]

assert invalid_ids.empty, (
    f"❌ Invalid FAQ IDs:\n"
    f"{invalid_ids[['faq_id']].to_string(index=False)}"
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# 6. DUPLICATE IDS
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    f"❌ Duplicate FAQ IDs:\n"
    f"{duplicate_ids[['faq_id']].to_string(index=False)}"
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 7. EXACT ID SEQUENCE
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 289)
]

actual_ids = df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ ID sequence is incorrect.\n"
    f"Expected first: {expected_ids[:5]}\n"
    f"Actual first  : {actual_ids[:5]}\n"
    f"Expected last : {expected_ids[-5:]}\n"
    f"Actual last   : {actual_ids[-5:]}"
)

print("✅ FAQ IDs are continuous: FAQ0001 → FAQ0288.")

# ============================================================
# 8. EMPTY REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in required_columns:

    missing = df[col].isna().sum()

    empty = (
        df[col]
        .astype(str)
        .str.strip()
        .isin(["", "nan", "None", "null"])
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, (
        f"❌ Missing values in {col}"
    )

    assert empty == 0, (
        f"❌ Empty values in {col}"
    )

# ============================================================
# 9. QUESTION DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION DUPLICATE CHECK")
print("=" * 100)

duplicate_questions = df[
    df["question"]
    .astype(str)
    .str.strip()
    .duplicated(keep=False)
]

assert duplicate_questions.empty, (
    f"❌ Duplicate questions found:\n"
    f"{duplicate_questions[['faq_id', 'question']].to_string(index=False)}"
)

print("✅ No duplicate questions.")

# ============================================================
# 10. NORMALIZED DUPLICATE CHECK
# ============================================================

def normalize_text(text):
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text

normalized_questions = (
    df["question"]
    .map(normalize_text)
)

duplicate_normalized = df[
    normalized_questions.duplicated(keep=False)
]

assert duplicate_normalized.empty, (
    "❌ Normalized duplicate questions found:\n"
    f"{duplicate_normalized[['faq_id', 'question']].to_string(index=False)}"
)

print("✅ No normalized duplicate questions.")

# ============================================================
# 11. LANGUAGES
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts)

expected_languages = {
    "Arabic": 72,
    "English": 72,
    "French": 72,
    "Russian": 72,
}

assert language_counts.to_dict() == expected_languages, (
    f"❌ Language distribution incorrect:\n"
    f"{language_counts}"
)

print("✅ Language balance: 72 × 4 languages.")

# ============================================================
# 12. INTENTS
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
)

print(intent_counts.to_string(index=False))

expected_intents = {
    "INT001": 36,
    "INT002": 36,
    "INT003": 36,
    "INT004": 36,
    "INT005": 36,
    "INT006": 36,
    "INT007": 36,
    "INT008": 36,
}

actual_intents = (
    df["intent_id"]
    .value_counts()
    .sort_index()
    .to_dict()
)

assert actual_intents == expected_intents, (
    f"❌ Intent distribution incorrect:\n"
    f"{actual_intents}"
)

print("✅ Intent balance: 36 × 8 intents.")

# ============================================================
# 13. INTENT NAME CONSISTENCY
# ============================================================

intent_mapping = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for intent_id, expected_name in intent_mapping.items():

    actual_names = (
        df.loc[
            df["intent_id"] == intent_id,
            "intent_name"
        ]
        .unique()
        .tolist()
    )

    assert actual_names == [expected_name], (
        f"❌ Intent mismatch for {intent_id}: "
        f"{actual_names}"
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 14. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(question_type_counts)

allowed_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert set(question_type_counts.index).issubset(
    allowed_types
), "❌ Invalid question type found."

print("✅ All question types are valid.")

# ============================================================
# 15. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS")
print("=" * 100)

print(df["status"].value_counts())

assert df["status"].notna().all()

print("✅ Status field complete.")

# ============================================================
# 16. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY")
print("=" * 100)

print(df["difficulty"].value_counts())

assert df["difficulty"].notna().all()

print("✅ Difficulty field complete.")

# ============================================================
# 17. GROUND TRUTH / ANSWERS
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert df["ground_truth"].notna().all()
assert df["answer"].notna().all()

assert (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 18. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET CHECK RESULT")
print("=" * 100)

print("""
🟢 DATASET IS VALID

✅ 288 questions
✅ FAQ0001 → FAQ0288
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ 72 Arabic
✅ 72 English
✅ 72 French
✅ 72 Russian
✅ 36 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Column structure correct
✅ Dataset was NOT modified
""")

print("=" * 100)
print("🎉 SAFE TO START BATCH 03")
print("=" * 100)

print("""
Next batch:
FAQ0289 → FAQ0320

Batch size:
32 questions
""")

====================================================================================================
🏨 HOTEL AI - FINAL DATASET CHECK
====================================================================================================

📂 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
✅ Project root found.
✅ Dataset found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 288
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
✅ Dataset contains exactly 288 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ FAQ IDs are continuous: FAQ0001 → FAQ0288.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0

====================================================================================================
📝 QUESTION DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions.
✅ No normalized duplicate questions.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    72
Arabic     72
French     72
Russian    72
Name: count, dtype: int64
✅ Language balance: 72 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         36
   INT002          hotel_category         36
   INT003  reception_availability         36
   INT004           check_in_time         36
   INT005          check_out_time         36
   INT006          early_check_in         36
   INT007          late_check_out         36
   INT008 identification_required         36
✅ Intent balance: 36 × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    128
Direct          96
Scenario        64
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS
====================================================================================================
status
valid        224
generated     64
Name: count, dtype: int64
✅ Status field complete.

====================================================================================================
📌 DIFFICULTY
====================================================================================================
difficulty
Easy    288
Name: count, dtype: int64
✅ Difficulty field complete.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🏆 FINAL DATASET CHECK RESULT
====================================================================================================

🟢 DATASET IS VALID

✅ 288 questions
✅ FAQ0001 → FAQ0288
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ 72 Arabic
✅ 72 English
✅ 72 French
✅ 72 Russian
✅ 36 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Column structure correct
✅ Dataset was NOT modified

====================================================================================================
🎉 SAFE TO START BATCH 03
====================================================================================================

Next batch:
FAQ0289 → FAQ0320

Batch size:
32 questions

In [16]:
# ============================================================
# 🏨 HOTEL AI - BATCH 02 vs ORIGINAL 256 QUESTIONS
# READ-ONLY DUPLICATE / OVERLAP CHECK
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 02 vs ORIGINAL 256")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_02.csv"
)

# ============================================================
# 2. CHECK FILES
# ============================================================

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

assert BATCH_FILE.exists(), (
    f"❌ Batch 02 not found:\n{BATCH_FILE}"
)

print(f"✅ Final dataset found.")
print(f"✅ Batch 02 found.")

# ============================================================
# 3. LOAD
# ============================================================

df = pd.read_csv(FINAL_DATASET)
batch = pd.read_csv(BATCH_FILE)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Final dataset rows : {len(df)}")
print(f"Batch 02 rows      : {len(batch)}")

# ============================================================
# 4. MAKE SURE BATCH IS THE EXPECTED 32
# ============================================================

assert len(batch) == 32, (
    f"❌ Batch 02 should contain 32 questions, "
    f"found {len(batch)}."
)

print("✅ Batch 02 contains exactly 32 questions.")

# ============================================================
# 5. ORIGINAL 256
# ============================================================
# IMPORTANT:
# Original questions = FAQ0009 → FAQ0256
#
# We intentionally exclude FAQ0001 → FAQ0008 because
# those are outside the original 256 being compared here.

original_256 = df[
    df["faq_id"].between("FAQ0009", "FAQ0256")
].copy()

print("\n" + "=" * 100)
print("📦 ORIGINAL DATASET")
print("=" * 100)

print(f"Original questions selected: {len(original_256)}")

assert len(original_256) == 248, (
    "⚠️ Note: FAQ0009 → FAQ0256 contains 248 questions, "
    "not 256."
)

print(
    "⚠️ IMPORTANT: Your current ID structure has FAQ0001 → FAQ0288."
)
print(
    "FAQ0009 → FAQ0256 = 248 questions."
)
print(
    "Therefore, this check cannot represent the old 256 exactly "
    "using IDs alone."
)

# ============================================================
# 6. BETTER METHOD:
#    TAKE THE FIRST 256 ROWS OF THE ORIGINAL DATASET
# ============================================================

original_256 = df.iloc[:256].copy()

print("\n" + "=" * 100)
print("📌 ORIGINAL 256 USED FOR COMPARISON")
print("=" * 100)

print(
    f"First ID : {original_256.iloc[0]['faq_id']}"
)

print(
    f"Last ID  : {original_256.iloc[-1]['faq_id']}"
)

print(
    f"Rows     : {len(original_256)}"
)

assert len(original_256) == 256

# ============================================================
# 7. NORMALIZATION FUNCTION
# ============================================================

def normalize_question(text):

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # Lowercase
    text = text.lower()

    # Remove extra spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    # Remove punctuation
    text = re.sub(
        r"[^\w\s]",
        "",
        text,
        flags=re.UNICODE
    )

    # Final trim
    text = text.strip()

    return text


original_256["_normalized_question"] = (
    original_256["question"]
    .map(normalize_question)
)

batch["_normalized_question"] = (
    batch["question"]
    .map(normalize_question)
)

# ============================================================
# 8. EXACT DUPLICATE CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔎 EXACT QUESTION OVERLAP")
print("=" * 100)

old_questions = set(
    original_256["question"]
    .astype(str)
    .str.strip()
)

new_questions = set(
    batch["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = (
    new_questions
    .intersection(old_questions)
)

if exact_overlap:

    print(
        f"❌ {len(exact_overlap)} exact duplicate(s) found:"
    )

    for q in sorted(exact_overlap):
        print(f"- {q}")

else:

    print(
        "✅ No exact duplicate questions."
    )

# ============================================================
# 9. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED QUESTION OVERLAP")
print("=" * 100)

old_normalized = set(
    original_256["_normalized_question"]
)

new_normalized = set(
    batch["_normalized_question"]
)

normalized_overlap = (
    new_normalized
    .intersection(old_normalized)
)

if normalized_overlap:

    print(
        f"❌ {len(normalized_overlap)} normalized "
        f"duplicate(s) found."
    )

    for normalized in sorted(normalized_overlap):

        old_rows = original_256[
            original_256["_normalized_question"]
            == normalized
        ]

        new_rows = batch[
            batch["_normalized_question"]
            == normalized
        ]

        print("\nOLD:")
        print(
            old_rows[
                ["faq_id", "question"]
            ].to_string(index=False)
        )

        print("\nNEW:")
        print(
            new_rows[
                ["faq_id", "question"]
            ].to_string(index=False)
        )

else:

    print(
        "✅ No normalized duplicate questions."
    )

# ============================================================
# 10. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 02")
print("=" * 100)

batch_duplicates = batch[
    batch["_normalized_question"]
    .duplicated(keep=False)
]

if not batch_duplicates.empty:

    print(
        "❌ Duplicate questions inside Batch 02:"
    )

    print(
        batch_duplicates[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

else:

    print(
        "✅ No duplicates inside Batch 02."
    )

# ============================================================
# 11. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 02 vs ORIGINAL 256 RESULT")
print("=" * 100)

if (
    not exact_overlap
    and not normalized_overlap
    and batch_duplicates.empty
):

    print("""
🟢 PASS

✅ 32 new questions checked
✅ Compared against original 256
✅ No exact duplicates
✅ No normalized duplicates
✅ No duplicates inside Batch 02
✅ Dataset was NOT modified
""")

else:

    print("""
🔴 FAIL

⚠️ There are duplicate/overlapping questions.

DO NOT MERGE BATCH 02 yet.
Review the questions listed above.
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 02 vs ORIGINAL 256
====================================================================================================
✅ Final dataset found.
✅ Batch 02 found.

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Final dataset rows : 288
Batch 02 rows      : 32
✅ Batch 02 contains exactly 32 questions.

====================================================================================================
📦 ORIGINAL DATASET
====================================================================================================
Original questions selected: 248
⚠️ IMPORTANT: Your current ID structure has FAQ0001 → FAQ0288.
FAQ0009 → FAQ0256 = 248 questions.
Therefore, this check cannot represent the old 256 exactly using IDs alone.

====================================================================================================
📌 ORIGINAL 256 USED FOR COMPARISON
====================================================================================================
First ID : FAQ0001
Last ID  : FAQ0256
Rows     : 256

====================================================================================================
🔎 EXACT QUESTION OVERLAP
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED QUESTION OVERLAP
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 02
====================================================================================================
✅ No duplicates inside Batch 02.

====================================================================================================
🏆 BATCH 02 vs ORIGINAL 256 RESULT
====================================================================================================

🟢 PASS

✅ 32 new questions checked
✅ Compared against original 256
✅ No exact duplicates
✅ No normalized duplicates
✅ No duplicates inside Batch 02
✅ Dataset was NOT modified

====================================================================================================

In [17]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
# READ-ONLY — DOES NOT MODIFY THE DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

# ============================================================
# 1. PROJECT AUTO DETECTION
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK")
print("=" * 100)

possible_paths = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "OneDrive" / "سطح المكتب" / "HotelAI",
    Path.home() / "OneDrive" / "Desktop" / "HotelAI",
]

PROJECT_ROOT = None

for path in possible_paths:
    if path.exists():
        PROJECT_ROOT = path
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ Could not automatically detect HotelAI project root.\n"
        "Please update PROJECT_ROOT manually."
    )

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print(f"\n📂 Project root:")
print(PROJECT_ROOT)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"\n❌ Dataset not found:\n{DATASET_PATH}"
    )

print(f"\n📄 Dataset:")
print(DATASET_PATH)

# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    col for col in REQUIRED_COLUMNS
    if col not in df.columns
]

extra_columns = [
    col for col in df.columns
    if col not in REQUIRED_COLUMNS
]

if missing_columns:
    print("❌ Missing columns:")
    print(missing_columns)
else:
    print("✅ All 13 required columns exist.")

if list(df.columns) == REQUIRED_COLUMNS:
    print("✅ Column order is correct.")
else:
    print("⚠️ Column order differs from expected.")
    print("\nActual:")
    print(list(df.columns))

# ============================================================
# 4. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

print(f"Total questions: {len(df)}")

if len(df) == 288:
    print("✅ Dataset contains exactly 288 questions.")
else:
    print(
        f"⚠️ Expected 288 questions, found {len(df)}."
    )

# ============================================================
# 5. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

id_pattern = re.compile(r"^FAQ\d{4}$")

invalid_ids = df[
    ~df["faq_id"].astype(str).str.match(id_pattern)
]

if invalid_ids.empty:
    print("✅ All FAQ IDs have valid format.")
else:
    print("❌ Invalid FAQ IDs:")
    print(
        invalid_ids[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 6. DUPLICATE FAQ IDs
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

if duplicate_ids.empty:
    print("✅ No duplicate FAQ IDs.")
else:
    print("❌ Duplicate FAQ IDs:")
    print(
        duplicate_ids[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 7. FAQ ID CONTINUITY
# ============================================================

print("\n" + "=" * 100)
print("🔢 FAQ ID CONTINUITY")
print("=" * 100)

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
)

numeric_ids = pd.to_numeric(
    numeric_ids,
    errors="coerce"
)

expected_ids = list(
    range(
        int(numeric_ids.min()),
        int(numeric_ids.max()) + 1
    )
)

actual_ids_sorted = sorted(
    numeric_ids.dropna().astype(int).tolist()
)

missing_ids = sorted(
    set(expected_ids) - set(actual_ids_sorted)
)

extra_count = len(
    actual_ids_sorted
) - len(
    set(actual_ids_sorted)
)

if not missing_ids and extra_count == 0:
    print(
        f"✅ IDs are continuous: "
        f"FAQ{int(numeric_ids.min()):04d} → "
        f"FAQ{int(numeric_ids.max()):04d}"
    )
else:
    print("❌ ID continuity problem.")

    if missing_ids:
        print("Missing IDs:")
        print(
            [
                f"FAQ{x:04d}"
                for x in missing_ids
            ]
        )

# ============================================================
# 8. ID ORDER
# ============================================================

ordered_ids = numeric_ids.tolist()

expected_order = list(
    range(
        int(numeric_ids.min()),
        int(numeric_ids.max()) + 1
    )
)

if ordered_ids == expected_order:
    print("✅ FAQ IDs are correctly ordered.")
else:
    print("❌ FAQ IDs are NOT correctly ordered.")

    problems = []

    for i, (actual, expected) in enumerate(
        zip(ordered_ids, expected_order),
        start=1
    ):
        if actual != expected:
            problems.append(
                (
                    i,
                    f"FAQ{expected:04d}",
                    f"FAQ{int(actual):04d}"
                )
            )

    print("\nFirst order problems:")
    for row, expected, actual in problems[:20]:
        print(
            f"Row {row}: "
            f"Expected {expected} "
            f"but found {actual}"
        )

# ============================================================
# 9. REQUIRED FIELD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

field_errors = False

for col in REQUIRED_COLUMNS:

    missing = df[col].isna().sum()

    empty = (
        df[col]
        .astype(str)
        .str.strip()
        .isin(["", "nan", "None"])
        .sum()
    )

    print(
        f"{'✅' if missing == 0 and empty == 0 else '❌'} "
        f"{col:<15} "
        f"Missing: {missing:<4} "
        f"Empty: {empty}"
    )

    if missing > 0 or empty > 0:
        field_errors = True

# ============================================================
# 10. NORMALIZATION FUNCTION
# ============================================================

def normalize_question(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = text.strip().lower()

    # Remove punctuation
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    # Normalize spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 11. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"]
    .astype(str)
    .str.strip()
    .duplicated(keep=False)
]

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(
        f"❌ Found "
        f"{len(exact_duplicates)} rows "
        f"in duplicate groups."
    )

    print(
        exact_duplicates[
            ["faq_id", "language", "intent_id", "question"]
        ]
        .sort_values("question")
        .to_string(index=False)
    )

# ============================================================
# 12. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED QUESTION DUPLICATE CHECK")
print("=" * 100)

df["_normalized_question"] = (
    df["question"].apply(normalize_question)
)

normalized_duplicates = df[
    df["_normalized_question"]
    .duplicated(keep=False)
]

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(
        f"❌ Found "
        f"{len(normalized_duplicates)} rows "
        f"with normalized duplicates."
    )

    print(
        normalized_duplicates[
            [
                "faq_id",
                "language",
                "intent_id",
                "question",
            ]
        ]
        .sort_values("_normalized_question")
        .to_string(index=False)
    )

# ============================================================
# 13. LANGUAGE DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    df["language"]
    .value_counts()
)

print(language_counts)

expected_languages = {
    "Arabic": 72,
    "English": 72,
    "French": 72,
    "Russian": 72,
}

language_ok = True

for lang, expected in expected_languages.items():

    actual = language_counts.get(lang, 0)

    if actual != expected:
        language_ok = False
        print(
            f"❌ {lang}: expected "
            f"{expected}, found {actual}"
        )

if language_ok:
    print(
        "✅ Language balance: "
        "72 × 4 languages."
    )

# ============================================================
# 14. INTENT DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_summary = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
)

print(
    intent_summary.to_string(index=False)
)

intent_ok = True

for intent_id in [
    "INT001",
    "INT002",
    "INT003",
    "INT004",
    "INT005",
    "INT006",
    "INT007",
    "INT008",
]:

    count = (
        df["intent_id"] == intent_id
    ).sum()

    if count != 36:
        intent_ok = False
        print(
            f"❌ {intent_id}: "
            f"expected 36, found {count}"
        )

if intent_ok:
    print(
        "✅ Intent balance: "
        "36 × 8 intents."
    )

# ============================================================
# 15. INTENT ID ↔ NAME CONSISTENCY
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_mapping = (
    df.groupby("intent_id")["intent_name"]
    .nunique()
)

bad_mappings = (
    intent_mapping[
        intent_mapping > 1
    ]
)

if bad_mappings.empty:
    print(
        "✅ Every intent_id maps "
        "to exactly one intent_name."
    )
else:
    print(
        "❌ Intent ID ↔ name inconsistency:"
    )

    for intent_id in bad_mappings.index:

        names = (
            df.loc[
                df["intent_id"] == intent_id,
                "intent_name"
            ]
            .unique()
        )

        print(
            intent_id,
            "→",
            list(names)
        )

# ============================================================
# 16. QUESTION TYPE
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(question_type_counts)

allowed_question_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = set(
    question_type_counts.index
) - allowed_question_types

if not invalid_types:
    print("✅ All question types are valid.")
else:
    print(
        "❌ Invalid question types:"
    )
    print(invalid_types)

# ============================================================
# 17. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS DISTRIBUTION")
print("=" * 100)

print(
    df["status"].value_counts()
)

# ============================================================
# 18. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)

print(
    df["difficulty"].value_counts()
)

# ============================================================
# 19. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

ground_truth_empty = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .isin(["", "nan", "None"])
)

answer_empty = (
    df["answer"]
    .astype(str)
    .str.strip()
    .isin(["", "nan", "None"])
)

print(
    "✅ Ground truth complete."
    if ground_truth_empty.sum() == 0
    else
    f"❌ Ground truth missing: "
    f"{ground_truth_empty.sum()}"
)

print(
    "✅ Answers complete."
    if answer_empty.sum() == 0
    else
    f"❌ Answers missing: "
    f"{answer_empty.sum()}"
)

# ============================================================
# 20. QUESTIONS PER LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(matrix)

# ============================================================
# 21. QUESTION TYPE × LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("📊 QUESTION TYPE × LANGUAGE")
print("=" * 100)

type_language = pd.crosstab(
    df["language"],
    df["question_type"]
)

print(type_language)

# ============================================================
# 22. POSSIBLE SAME-INTENT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES BY INTENT")
print("=" * 100)

same_intent_duplicates = (
    df.groupby(
        ["intent_id", "_normalized_question"]
    )
    .size()
    .reset_index(name="count")
)

same_intent_duplicates = (
    same_intent_duplicates[
        same_intent_duplicates["count"] > 1
    ]
)

if same_intent_duplicates.empty:
    print(
        "✅ No normalized duplicates "
        "inside the same intent."
    )
else:
    print(
        "⚠️ Possible repeated questions "
        "inside the same intent:"
    )

    for _, row in same_intent_duplicates.iterrows():

        subset = df[
            (df["intent_id"] == row["intent_id"])
            &
            (
                df["_normalized_question"]
                == row["_normalized_question"]
            )
        ]

        print("\nIntent:", row["intent_id"])

        print(
            subset[
                [
                    "faq_id",
                    "language",
                    "question",
                ]
            ].to_string(index=False)
        )

# ============================================================
# 23. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET CHECK RESULT")
print("=" * 100)

errors = []

if missing_columns:
    errors.append("Missing columns")

if not invalid_ids.empty:
    errors.append("Invalid FAQ IDs")

if not duplicate_ids.empty:
    errors.append("Duplicate FAQ IDs")

if missing_ids:
    errors.append("Missing FAQ IDs")

if ordered_ids != expected_order:
    errors.append("FAQ ID order")

if field_errors:
    errors.append("Required fields")

if not exact_duplicates.empty:
    errors.append("Exact duplicate questions")

if not normalized_duplicates.empty:
    errors.append("Normalized duplicate questions")

if not language_ok:
    errors.append("Language balance")

if not intent_ok:
    errors.append("Intent balance")

if not bad_mappings.empty:
    errors.append("Intent mapping")

if invalid_types:
    errors.append("Invalid question types")

if ground_truth_empty.sum() > 0:
    errors.append("Missing ground truth")

if answer_empty.sum() > 0:
    errors.append("Missing answers")

if not errors:

    print("""
🟢 DATASET IS VALID

✅ All IDs valid
✅ IDs continuous and ordered
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ Required fields complete
✅ Languages validated
✅ Intents validated
✅ Intent names consistent
✅ Question types valid
✅ Ground truth complete
✅ Answers complete
""")

else:

    print("🔴 DATASET HAS ISSUES")
    print("\nProblems found:")

    for error in errors:
        print(f"❌ {error}")

print("\n" + "=" * 100)
print("🔒 READ-ONLY CHECK")
print("=" * 100)

print(
    "✅ hotel_faq_final.csv was NOT modified."
)

# ============================================================
# 24. CLEAN TEMP COLUMN
# ============================================================

df.drop(
    columns=["_normalized_question"],
    inplace=True
)

print("\n" + "=" * 100)
print("🏁 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 288
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
Total questions: 288
✅ Dataset contains exactly 288 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

====================================================================================================
🔢 FAQ ID CONTINUITY
====================================================================================================
✅ IDs are continuous: FAQ0001 → FAQ0288
✅ FAQ IDs are correctly ordered.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0    Empty: 0
✅ intent_id       Missing: 0    Empty: 0
✅ language        Missing: 0    Empty: 0
✅ question_type   Missing: 0    Empty: 0
✅ question        Missing: 0    Empty: 0
✅ status          Missing: 0    Empty: 0
✅ intent_name     Missing: 0    Empty: 0
✅ ground_truth    Missing: 0    Empty: 0
✅ category        Missing: 0    Empty: 0
✅ source          Missing: 0    Empty: 0
✅ attempts        Missing: 0    Empty: 0
✅ difficulty      Missing: 0    Empty: 0
✅ answer          Missing: 0    Empty: 0

====================================================================================================
📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED QUESTION DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    72
Arabic     72
French     72
Russian    72
Name: count, dtype: int64
✅ Language balance: 72 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         36
   INT002          hotel_category         36
   INT003  reception_availability         36
   INT004           check_in_time         36
   INT005          check_out_time         36
   INT006          early_check_in         36
   INT007          late_check_out         36
   INT008 identification_required         36
✅ Intent balance: 36 × 8 intents.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ Every intent_id maps to exactly one intent_name.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    128
Direct          96
Scenario        64
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated     64
Name: count, dtype: int64

====================================================================================================
📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    288
Name: count, dtype: int64

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001          9        9       9        9
INT002          9        9       9        9
INT003          9        9       9        9
INT004          9        9       9        9
INT005          9        9       9        9
INT006          9        9       9        9
INT007          9        9       9        9
INT008          9        9       9        9

====================================================================================================
📊 QUESTION TYPE × LANGUAGE
====================================================================================================
question_type  Direct  Paraphrased  Scenario
language
Arabic             25           33        14
English            29           29        14
French             21           37        14
Russian            21           29        22

====================================================================================================
🔍 DUPLICATES BY INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🏆 FINAL DATASET CHECK RESULT
====================================================================================================

🟢 DATASET IS VALID

✅ All IDs valid
✅ IDs continuous and ordered
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ Required fields complete
✅ Languages validated
✅ Intents validated
✅ Intent names consistent
✅ Question types valid
✅ Ground truth complete
✅ Answers complete


====================================================================================================
🔒 READ-ONLY CHECK
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🏁 CHECK COMPLETE
====================================================================================================

In [18]:
# ============================================================
# 🏨 HOTEL AI - BATCH 03 GENERATION
# 32 NEW QUESTIONS ONLY
# READ-ONLY AGAINST FINAL DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 03 GENERATION")
print("=" * 100)

# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = BATCH_DIR / "faq_batch_03.csv"

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"❌ Project root not found:\n{PROJECT_ROOT}"
    )

if not FINAL_DATASET.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{FINAL_DATASET}"
    )

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print(f"\n✅ Final dataset found.")

# ============================================================
# 2. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(FINAL_DATASET)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

missing_columns = [
    c for c in REQUIRED_COLUMNS
    if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"❌ Missing columns:\n{missing_columns}"
    )

print("✅ All required columns exist.")

# ============================================================
# 3. CURRENT DATASET VALIDATION
# ============================================================

if len(df) != 288:
    raise ValueError(
        f"❌ Expected 288 existing questions, "
        f"found {len(df)}."
    )

print("✅ Existing dataset contains exactly 288 questions.")

# ============================================================
# 4. FIND NEXT FAQ ID
# ============================================================

id_numbers = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = id_numbers.max()

START_ID = last_id + 1
END_ID = START_ID + 32

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(
    f"Last existing : FAQ{last_id:04d}"
)

print(
    f"Next batch    : FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}"
)

assert START_ID == 289
assert END_ID == 321

# ============================================================
# 5. INTENT DEFINITIONS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 6. BATCH 03 QUESTIONS
# ============================================================

questions = [

    # --------------------------------------------------------
    # INT001 - HOTEL LOCATION
    # --------------------------------------------------------

    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا كنت أبحث عن الفندق في القاهرة، فأين يقع Nile Pearl Hotel تحديدًا؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I am looking for the hotel in Cairo, where exactly is Nile Pearl Hotel located?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si je cherche l'hôtel au Caire, où se trouve exactement le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я ищу отель в Каире, где именно находится Nile Pearl Hotel?",
    },

    # --------------------------------------------------------
    # INT002 - HOTEL CATEGORY
    # --------------------------------------------------------

    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "أخطط للإقامة في Nile Pearl Hotel، فما تصنيف الفندق الذي يمكنني توقعه؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Scenario",
        "question": "I am planning to stay at Nile Pearl Hotel; what category is the hotel?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Scenario",
        "question": "Je prévois de séjourner au Nile Pearl Hotel ; quelle est la catégorie de cet hôtel ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я планирую остановиться в Nile Pearl Hotel; к какой категории относится этот отель?",
    },

    # --------------------------------------------------------
    # INT003 - RECEPTION AVAILABILITY
    # --------------------------------------------------------

    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يمكنني الوصول إلى موظفي الاستقبال في أي وقت من اليوم؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I reach the reception staff at any time of the day?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je contacter le personnel de la réception à n'importe quelle heure de la journée ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Могу ли я обратиться к сотрудникам стойки регистрации в любое время суток?",
    },

    # --------------------------------------------------------
    # INT004 - CHECK IN TIME
    # --------------------------------------------------------

    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "سأصل إلى الفندق في يوم تسجيل الوصول، فمتى يمكنني تسجيل الدخول بشكل عادي؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Scenario",
        "question": "I will arrive at the hotel on my check-in day; when can I normally check in?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Scenario",
        "question": "J'arriverai à l'hôtel le jour de mon arrivée ; à quelle heure puis-je normalement m'enregistrer ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я приеду в отель в день заезда; когда я обычно могу зарегистрироваться?",
    },

    # --------------------------------------------------------
    # INT005 - CHECK OUT TIME
    # --------------------------------------------------------

    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "في أي وقت ينبغي أن أغادر الغرفة في يوم تسجيل المغادرة؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Direct",
        "question": "What time should I leave my room on the day of check-out?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question": "À quelle heure dois-je libérer ma chambre le jour du départ ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question": "В какое время нужно освободить номер в день выезда?",
    },

    # --------------------------------------------------------
    # INT006 - EARLY CHECK IN
    # --------------------------------------------------------

    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "سأصل قبل موعد تسجيل الوصول، فهل يمكنني الدخول إلى غرفتي مبكرًا؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Scenario",
        "question": "I will arrive before the check-in time; can I enter my room early?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Scenario",
        "question": "J'arriverai avant l'heure d'arrivée prévue ; puis-je accéder à ma chambre plus tôt ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?",
    },

    # --------------------------------------------------------
    # INT007 - LATE CHECK OUT
    # --------------------------------------------------------

    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يوفر الفندق خيار تمديد وقت تسجيل المغادرة إلى وقت لاحق؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Direct",
        "question": "Does the hotel offer an option to extend the check-out time?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Direct",
        "question": "L'hôtel propose-t-il de prolonger l'heure de départ ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Предлагает ли отель возможность продлить время выезда?",
    },

    # --------------------------------------------------------
    # INT008 - IDENTIFICATION REQUIRED
    # --------------------------------------------------------

    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "عند وصولي إلى الفندق لتسجيل الدخول، ماذا يجب أن أقدم لإثبات هويتي؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Scenario",
        "question": "When I arrive at the hotel to check in, what should I provide as identification?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Scenario",
        "question": "À mon arrivée à l'hôtel pour m'enregistrer, quel justificatif d'identité dois-je fournir ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "При заселении в отель какой документ удостоверяющий личность нужно предоставить?",
    },
]

# ============================================================
# 7. BUILD BATCH DATA
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 03",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(batch)

# ============================================================
# 8. BASIC VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🔎 BATCH 03 VALIDATION")
print("=" * 100)

assert len(batch_df) == 32

print("✅ Exactly 32 questions.")

# IDs
expected_ids = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID
    )
]

assert (
    batch_df["faq_id"].tolist()
    == expected_ids
)

print(
    f"✅ IDs: FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# Duplicate IDs
assert not batch_df["faq_id"].duplicated().any()

print("✅ No duplicate FAQ IDs.")

# Empty questions
assert not (
    batch_df["question"]
    .astype(str)
    .str.strip()
    .eq("")
    .any()
)

print("✅ No empty questions.")

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.lower()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

batch_normalized = (
    batch_df["question"]
    .apply(normalize_question)
)

assert not batch_normalized.duplicated().any()

print("✅ No duplicate questions inside Batch 03.")

# ============================================================
# 10. COMPARE WITH EXISTING 288
# ============================================================

existing_normalized = set(
    df["question"]
    .astype(str)
    .apply(normalize_question)
)

overlap = []

for idx, normalized in enumerate(
    batch_normalized
):

    if normalized in existing_normalized:

        overlap.append(
            batch_df.iloc[idx]
        )

if overlap:

    overlap_df = pd.DataFrame(overlap)

    print("\n❌ QUESTIONS ALREADY EXIST:")
    print(
        overlap_df[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Batch 03 contains questions "
        "that overlap with the existing dataset."
    )

print(
    "✅ No questions overlap with existing 288."
)

# ============================================================
# 11. LANGUAGE BALANCE
# ============================================================

language_counts = (
    batch_df["language"]
    .value_counts()
)

print("\n🌍 LANGUAGE DISTRIBUTION")
print(language_counts)

expected_languages = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert language_counts.to_dict() == expected_languages

print(
    "✅ Language balance: "
    "8 × 4 languages."
)

# ============================================================
# 12. INTENT BALANCE
# ============================================================

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print("\n🎯 INTENT DISTRIBUTION")
print(intent_counts)

for intent_id in INTENTS:

    assert (
        intent_counts.get(intent_id, 0)
        == 4
    )

print(
    "✅ Intent balance: "
    "4 questions × 8 intents."
)

# ============================================================
# 13. INTENT NAME CONSISTENCY
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        INTENTS[row["intent_id"]]
        == row["intent_name"]
    )

print(
    "✅ Intent ID ↔ Intent Name consistency."
)

# ============================================================
# 14. QUESTION TYPES
# ============================================================

valid_question_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert set(
    batch_df["question_type"]
) <= valid_question_types

print(
    "✅ All question types are valid."
)

print("\nQuestion types:")
print(
    batch_df["question_type"]
    .value_counts()
)

# ============================================================
# 15. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 03 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 16. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 17. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 03 READY")
print("=" * 100)

print(
    f"""
Existing dataset : {len(df)} questions
New batch        : {len(batch_df)} questions

FAQ IDs:
FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 rows
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 288
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch file:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 03 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 288
Columns : 13
✅ All required columns exist.
✅ Existing dataset contains exactly 288 questions.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0288
Next batch    : FAQ0289 → FAQ0320

KeyError: 'question_type'

In [19]:
# ============================================================
# 🏨 HOTEL AI - BATCH 03 GENERATION
# EXACTLY 32 NEW QUESTIONS
# CONTINUE FROM FAQ0288
# READ-ONLY FINAL DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 03 GENERATION")
print("=" * 100)

# ============================================================
# 1. PROJECT
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = (
    BATCH_DIR
    / "faq_batch_03.csv"
)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"❌ Project root not found:\n{PROJECT_ROOT}"
    )

if not FINAL_DATASET.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{FINAL_DATASET}"
    )

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print("✅ Project root found.")
print("✅ Final dataset found.")

# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

missing = [
    col
    for col in REQUIRED_COLUMNS
    if col not in df.columns
]

assert not missing, (
    f"❌ Missing columns: {missing}"
)

print("✅ All 13 required columns exist.")

assert len(df) == 288, (
    f"❌ Expected 288 rows, found {len(df)}"
)

print("✅ Existing dataset contains exactly 288 questions.")

# ============================================================
# 3. FAQ ID CONTINUATION
# ============================================================

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = numeric_ids.max()

START_ID = last_id + 1
END_ID = START_ID + 32

assert START_ID == 289
assert END_ID == 321

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(
    f"New batch     : FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}"
)

# ============================================================
# 4. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 5. BATCH 03 QUESTIONS
# ============================================================

questions = [

    # INT001
    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا كنت أبحث عن الفندق في القاهرة، فأين يقع Nile Pearl Hotel تحديدًا؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I am looking for the hotel in Cairo, where exactly is Nile Pearl Hotel located?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si je cherche l'hôtel au Caire, où se trouve exactement le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я ищу отель в Каире, где именно находится Nile Pearl Hotel?",
    },

    # INT002
    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "أخطط للإقامة في Nile Pearl Hotel، فما تصنيف الفندق الذي يمكنني توقعه؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Scenario",
        "question": "I am planning to stay at Nile Pearl Hotel; what category is the hotel?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Scenario",
        "question": "Je prévois de séjourner au Nile Pearl Hotel ; quelle est la catégorie de cet hôtel ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я планирую остановиться в Nile Pearl Hotel; к какой категории относится этот отель?",
    },

    # INT003
    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يمكنني الوصول إلى موظفي الاستقبال في أي وقت من اليوم؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I reach the reception staff at any time of the day?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je contacter le personnel de la réception à n'importe quelle heure de la journée ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Могу ли я обратиться к сотрудникам стойки регистрации в любое время суток?",
    },

    # INT004
    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "سأصل إلى الفندق في يوم تسجيل الوصول، فمتى يمكنني تسجيل الدخول بشكل عادي؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Scenario",
        "question": "I will arrive at the hotel on my check-in day; when can I normally check in?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Scenario",
        "question": "J'arriverai à l'hôtel le jour de mon arrivée ; à quelle heure puis-je normalement m'enregistrer ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я приеду в отель в день заезда; когда я обычно могу зарегистрироваться?",
    },

    # INT005
    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "في أي وقت ينبغي أن أغادر الغرفة في يوم تسجيل المغادرة؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Direct",
        "question": "What time should I leave my room on the day of check-out?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question_type": "Direct",
        "question": "À quelle heure dois-je libérer ma chambre le jour du départ ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question_type": "Direct",
        "question": "В какое время нужно освободить номер в день выезда?",
    },

    # INT006
    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "سأصل قبل موعد تسجيل الوصول، فهل يمكنني الدخول إلى غرفتي مبكرًا؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Scenario",
        "question": "I will arrive before the check-in time; can I enter my room early?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Scenario",
        "question": "J'arriverai avant l'heure d'arrivée prévue ; puis-je accéder à ma chambre plus tôt ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?",
    },

    # INT007
    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يوفر الفندق خيار تمديد وقت تسجيل المغادرة إلى وقت لاحق؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Direct",
        "question": "Does the hotel offer an option to extend the check-out time?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Direct",
        "question": "L'hôtel propose-t-il de prolonger l'heure de départ ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Предлагает ли отель возможность продлить время выезда?",
    },

    # INT008
    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "عند وصولي إلى الفندق لتسجيل الدخول، ماذا يجب أن أقدم لإثبات هويتي؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Scenario",
        "question": "When I arrive at the hotel to check in, what should I provide as identification?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Scenario",
        "question": "À mon arrivée à l'hôtel pour m'enregistrer, quel justificatif d'identité dois-je fournir ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "При заселении в отель какой документ удостоверяющий личность нужно предоставить?",
    },
]

# ============================================================
# 6. SAFETY CHECK
# ============================================================

assert len(questions) == 32, (
    f"❌ Expected 32 questions, found {len(questions)}"
)

for index, item in enumerate(questions, start=1):

    required = [
        "intent_id",
        "language",
        "question_type",
        "question",
    ]

    for field in required:

        assert field in item, (
            f"❌ Question #{index} missing field: {field}"
        )

        assert str(item[field]).strip(), (
            f"❌ Question #{index} has empty {field}"
        )

print("\n" + "=" * 100)
print("🧪 QUESTION STRUCTURE CHECK")
print("=" * 100)

print("✅ All 32 questions contain:")
print("   - intent_id")
print("   - language")
print("   - question_type")
print("   - question")

# ============================================================
# 7. BUILD BATCH
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 03",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(batch)

# ============================================================
# 8. ID CHECK
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID
    )
]

assert batch_df["faq_id"].tolist() == expected_ids

assert not batch_df["faq_id"].duplicated().any()

print("\n" + "=" * 100)
print("🆔 ID VALIDATION")
print("=" * 100)

print("✅ IDs are exactly FAQ0289 → FAQ0320.")
print("✅ No duplicate IDs.")

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.lower()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


batch_normalized = (
    batch_df["question"]
    .apply(normalize_question)
)

existing_normalized = (
    df["question"]
    .astype(str)
    .apply(normalize_question)
)

# ============================================================
# 10. DUPLICATES INSIDE BATCH
# ============================================================

assert not batch_normalized.duplicated().any()

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

print("✅ No duplicate questions inside Batch 03.")

# ============================================================
# 11. OVERLAP WITH EXISTING 288
# ============================================================

existing_set = set(
    existing_normalized
)

overlap_mask = batch_normalized.isin(
    existing_set
)

if overlap_mask.any():

    overlap_df = batch_df.loc[
        overlap_mask,
        [
            "faq_id",
            "intent_id",
            "language",
            "question",
        ]
    ]

    print("\n❌ OVERLAP FOUND:")
    print(
        overlap_df.to_string(
            index=False
        )
    )

    raise AssertionError(
        "❌ Batch 03 overlaps with existing questions."
    )

print(
    "✅ No exact/normalized overlap with existing 288."
)

# ============================================================
# 12. LANGUAGE BALANCE
# ============================================================

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

print(language_counts)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert language_counts.to_dict() == (
    expected_language_counts
)

print(
    "✅ 8 questions per language."
)

# ============================================================
# 13. INTENT BALANCE
# ============================================================

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

print(intent_counts)

for intent_id in INTENTS:

    assert (
        intent_counts.get(intent_id, 0)
        == 4
    )

print(
    "✅ 4 questions × 8 intents."
)

# ============================================================
# 14. INTENT NAME CONSISTENCY
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print(
    "✅ Intent ID ↔ Intent Name consistency."
)

# ============================================================
# 15. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert set(
    batch_df["question_type"]
) <= VALID_TYPES

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 16. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 03 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 17. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("🎉 BATCH 03 READY")
print("=" * 100)

print(
    f"""
Existing dataset : 288 questions
New batch        : 32 questions

FAQ IDs:
FAQ0289 → FAQ0320

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty fields
✅ No duplicate questions
✅ No overlap with existing 288
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 03 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Project root found.
✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 288
Columns : 13
✅ All 13 required columns exist.
✅ Existing dataset contains exactly 288 questions.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0288
New batch     : FAQ0289 → FAQ0320

====================================================================================================
🧪 QUESTION STRUCTURE CHECK
====================================================================================================
✅ All 32 questions contain:
   - intent_id
   - language
   - question_type
   - question

====================================================================================================
🆔 ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0289 → FAQ0320.
✅ No duplicate IDs.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions inside Batch 03.
✅ No exact/normalized overlap with existing 288.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 questions per language.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Scenario    20
Direct      12
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📝 BATCH 03 QUESTIONS
====================================================================================================
 faq_id intent_id language question_type                                                                                          question
FAQ0289    INT001   Arabic      Scenario                             إذا كنت أبحث عن الفندق في القاهرة، فأين يقع Nile Pearl Hotel تحديدًا؟
FAQ0290    INT001  English      Scenario                If I am looking for the hotel in Cairo, where exactly is Nile Pearl Hotel located?
FAQ0291    INT001   French      Scenario                     Si je cherche l'hôtel au Caire, où se trouve exactement le Nile Pearl Hotel ?
FAQ0292    INT001  Russian      Scenario                                  Если я ищу отель в Каире, где именно находится Nile Pearl Hotel?
FAQ0293    INT002   Arabic      Scenario                             أخطط للإقامة في Nile Pearl Hotel، فما تصنيف الفندق الذي يمكنني توقعه؟
FAQ0294    INT002  English      Scenario                            I am planning to stay at Nile Pearl Hotel; what category is the hotel?
FAQ0295    INT002   French      Scenario              Je prévois de séjourner au Nile Pearl Hotel ; quelle est la catégorie de cet hôtel ?
FAQ0296    INT002  Russian      Scenario               Я планирую остановиться в Nile Pearl Hotel; к какой категории относится этот отель?
FAQ0297    INT003   Arabic        Direct                                          هل يمكنني الوصول إلى موظفي الاستقبال في أي وقت من اليوم؟
FAQ0298    INT003  English        Direct                                           Can I reach the reception staff at any time of the day?
FAQ0299    INT003   French        Direct           Puis-je contacter le personnel de la réception à n'importe quelle heure de la journée ?
FAQ0300    INT003  Russian        Direct                        Могу ли я обратиться к сотрудникам стойки регистрации в любое время суток?
FAQ0301    INT004   Arabic      Scenario                          سأصل إلى الفندق في يوم تسجيل الوصول، فمتى يمكنني تسجيل الدخول بشكل عادي؟
FAQ0302    INT004  English      Scenario                      I will arrive at the hotel on my check-in day; when can I normally check in?
FAQ0303    INT004   French      Scenario J'arriverai à l'hôtel le jour de mon arrivée ; à quelle heure puis-je normalement m'enregistrer ?
FAQ0304    INT004  Russian      Scenario                           Я приеду в отель в день заезда; когда я обычно могу зарегистрироваться?
FAQ0305    INT005   Arabic        Direct                                            في أي وقت ينبغي أن أغادر الغرفة في يوم تسجيل المغادرة؟
FAQ0306    INT005  English        Direct                                         What time should I leave my room on the day of check-out?
FAQ0307    INT005   French        Direct                                     À quelle heure dois-je libérer ma chambre le jour du départ ?
FAQ0308    INT005  Russian        Direct                                               В какое время нужно освободить номер в день выезда?
FAQ0309    INT006   Arabic      Scenario                                   سأصل قبل موعد تسجيل الوصول، فهل يمكنني الدخول إلى غرفتي مبكرًا؟
FAQ0310    INT006  English      Scenario                                I will arrive before the check-in time; can I enter my room early?
FAQ0311    INT006   French      Scenario              J'arriverai avant l'heure d'arrivée prévue ; puis-je accéder à ma chambre plus tôt ?
FAQ0312    INT006  Russian      Scenario                        Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?
FAQ0313    INT007   Arabic        Direct                                        هل يوفر الفندق خيار تمديد وقت تسجيل المغادرة إلى وقت لاحق؟
FAQ0314    INT007  English        Direct                                      Does the hotel offer an option to extend the check-out time?
FAQ0315    INT007   French        Direct                                             L'hôtel propose-t-il de prolonger l'heure de départ ?
FAQ0316    INT007  Russian        Direct                                            Предлагает ли отель возможность продлить время выезда?
FAQ0317    INT008   Arabic      Scenario                                عند وصولي إلى الفندق لتسجيل الدخول، ماذا يجب أن أقدم لإثبات هويتي؟
FAQ0318    INT008  English      Scenario                  When I arrive at the hotel to check in, what should I provide as identification?
FAQ0319    INT008   French      Scenario        À mon arrivée à l'hôtel pour m'enregistrer, quel justificatif d'identité dois-je fournir ?
FAQ0320    INT008  Russian      Scenario                  При заселении в отель какой документ удостоверяющий личность нужно предоставить?

====================================================================================================
🎉 BATCH 03 READY
====================================================================================================

Existing dataset : 288 questions
New batch        : 32 questions

FAQ IDs:
FAQ0289 → FAQ0320

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty fields
✅ No duplicate questions
✅ No overlap with existing 288
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_03.csv

====================================================================================================

In [20]:
# ============================================================
# 🏨 HOTEL AI - BATCH 03 FINAL CHECK
# READ-ONLY — DOES NOT MODIFY DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 03 FINAL CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_03.csv"
)

assert PROJECT_ROOT.exists(), f"❌ Project root not found:\n{PROJECT_ROOT}"
assert FINAL_DATASET.exists(), f"❌ Final dataset not found:\n{FINAL_DATASET}"
assert BATCH_FILE.exists(), f"❌ Batch 03 not found:\n{BATCH_FILE}"

print("✅ Project root found.")
print("✅ Final dataset found.")
print("✅ Batch 03 found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(FINAL_DATASET)
batch_df = pd.read_csv(BATCH_FILE)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset rows : {len(df)}")
print(f"Batch 03 rows         : {len(batch_df)}")

assert len(df) == 288, (
    f"❌ Expected existing dataset to contain 288 rows, "
    f"found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 03 must contain exactly 32 rows, "
    f"found {len(batch_df)}"
)

print("✅ Existing dataset contains exactly 288 questions.")
print("✅ Batch 03 contains exactly 32 questions.")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Final dataset column structure is incorrect."
)

assert list(batch_df.columns) == REQUIRED_COLUMNS, (
    "❌ Batch 03 column structure is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(289, 321)
]

actual_ids = batch_df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ Batch 03 FAQ ID sequence is incorrect.\n"
    f"Expected: {expected_ids}\n"
    f"Actual  : {actual_ids}"
)

print("✅ IDs are exactly FAQ0289 → FAQ0320.")

assert batch_df["faq_id"].is_unique
print("✅ No duplicate FAQ IDs inside Batch 03.")

existing_ids = set(df["faq_id"].astype(str))
new_ids = set(batch_df["faq_id"].astype(str))

overlap_ids = existing_ids.intersection(new_ids)

assert not overlap_ids, (
    f"❌ Batch 03 contains existing FAQ IDs:\n{sorted(overlap_ids)}"
)

print("✅ No FAQ ID overlap with existing dataset.")

# ============================================================
# 5. EMPTY FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = batch_df[col].isna().sum()

    empty = (
        batch_df[col]
        .astype(str)
        .str.strip()
        .isin(["", "None", "nan"])
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, f"❌ Missing values in {col}"
    assert empty == 0, f"❌ Empty values in {col}"

# ============================================================
# 6. NORMALIZATION FUNCTION
# ============================================================

def normalize_question(text):
    text = str(text)

    text = unicodedata.normalize("NFKC", text)

    text = text.casefold()

    # Remove punctuation
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

# ============================================================
# 7. EXACT DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

batch_questions = batch_df["question"].astype(str)

duplicates_inside = batch_questions[
    batch_questions.duplicated(keep=False)
]

assert duplicates_inside.empty, (
    "❌ Exact duplicate questions inside Batch 03:\n"
    + str(
        batch_df.loc[
            batch_questions.duplicated(keep=False),
            ["faq_id", "question"]
        ]
    )
)

print("✅ No exact duplicate questions inside Batch 03.")

# ============================================================
# 8. NORMALIZED DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

batch_normalized = batch_df["question"].map(normalize_question)

duplicate_mask = batch_normalized.duplicated(keep=False)

assert not duplicate_mask.any(), (
    "❌ Normalized duplicate questions inside Batch 03:\n"
    + str(
        batch_df.loc[
            duplicate_mask,
            ["faq_id", "question"]
        ]
    )
)

print("✅ No normalized duplicates inside Batch 03.")

# ============================================================
# 9. COMPARE AGAINST EXISTING 288
# ============================================================

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = existing_exact.intersection(batch_exact)

assert not exact_overlap, (
    "❌ Exact question overlap with existing 288:\n"
    + "\n".join(sorted(exact_overlap))
)

print("✅ No exact question overlap with existing 288.")

# ============================================================
# 10. NORMALIZED OVERLAP
# ============================================================

existing_normalized = set(
    df["question"].map(normalize_question)
)

batch_normalized_set = set(batch_normalized)

normalized_overlap = (
    existing_normalized.intersection(
        batch_normalized_set
    )
)

assert not normalized_overlap, (
    "❌ Normalized question overlap with existing 288:\n"
    + "\n".join(sorted(normalized_overlap))
)

print("✅ No normalized question overlap with existing 288.")

# ============================================================
# 11. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE VALIDATION")
print("=" * 100)

language_counts = batch_df["language"].value_counts()

print(language_counts)

expected_languages = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert language_counts.to_dict() == expected_languages, (
    f"❌ Incorrect language distribution:\n"
    f"{language_counts}"
)

print("✅ Language balance: 8 × 4 languages.")

# ============================================================
# 12. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT VALIDATION")
print("=" * 100)

intent_counts = batch_df["intent_id"].value_counts().sort_index()

print(intent_counts)

expected_intents = {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

assert intent_counts.to_dict() == expected_intents, (
    f"❌ Incorrect intent distribution:\n"
    f"{intent_counts}"
)

print("✅ Intent balance: 4 × 8 intents.")

# ============================================================
# 13. INTENT NAME CONSISTENCY
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_map = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for _, row in batch_df.iterrows():

    expected_name = intent_map[row["intent_id"]]

    assert row["intent_name"] == expected_name, (
        f"❌ Intent mismatch at {row['faq_id']}:\n"
        f"Expected: {expected_name}\n"
        f"Found   : {row['intent_name']}"
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 14. QUESTION TYPE
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE VALIDATION")
print("=" * 100)

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = set(
    batch_df["question_type"]
) - VALID_TYPES

assert not invalid_types, (
    f"❌ Invalid question types: {invalid_types}"
)

print(batch_df["question_type"].value_counts())
print("✅ All question types are valid.")

# ============================================================
# 15. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert batch_df["ground_truth"].notna().all()
assert batch_df["answer"].notna().all()

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 16. PROJECTED MERGE
# ============================================================

print("\n" + "=" * 100)
print("📊 PROJECTED DATASET")
print("=" * 100)

projected_rows = len(df) + len(batch_df)

print(f"Current dataset : {len(df)}")
print(f"Batch 03        : {len(batch_df)}")
print(f"After merge     : {projected_rows}")

assert projected_rows == 320

print("✅ Projected dataset will contain exactly 320 questions.")

# ============================================================
# 17. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 03 FINAL CHECK RESULT")
print("=" * 100)

print("""
🟢 BATCH 03 IS VALID

✅ 32 questions
✅ FAQ0289 → FAQ0320
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 288
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ Question types valid
✅ Projected total = 320

⚠️ hotel_faq_final.csv was NOT modified.
⚠️ This was a READ-ONLY validation.

🎉 SAFE TO MERGE BATCH 03
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 03 FINAL CHECK
====================================================================================================
✅ Project root found.
✅ Final dataset found.
✅ Batch 03 found.

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset rows : 288
Batch 03 rows         : 32
✅ Existing dataset contains exactly 288 questions.
✅ Batch 03 contains exactly 32 questions.

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0289 → FAQ0320.
✅ No duplicate FAQ IDs inside Batch 03.
✅ No FAQ ID overlap with existing dataset.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 32  Empty: 32

AssertionError: ❌ Missing values in ground_truth

In [21]:
# ============================================================
# 🏨 HOTEL AI - BATCH 03 REPAIR + FINAL VALIDATION
# ============================================================
# IMPORTANT:
# - Repairs Batch 03 ONLY
# - Does NOT modify hotel_faq_final.csv
# - Fills ground_truth + answer
# - Validates Batch 03 against existing 288 questions
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 03 REPAIR + FINAL VALIDATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_03.csv"
)

assert PROJECT_ROOT.exists()
assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

print("✅ Project root found.")
print("✅ Final dataset found.")
print("✅ Batch 03 found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(FINAL_DATASET)
batch_df = pd.read_csv(BATCH_FILE)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 03         : {len(batch_df)} rows")

assert len(df) == 288
assert len(batch_df) == 32

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 required columns exist.")

# ============================================================
# 4. INTENT MAP
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 5. HOTEL KNOWLEDGE
# ============================================================

HOTEL_NAME = "Nile Pearl Hotel"

# These are the canonical answers already represented
# by the existing FAQ dataset.

GROUND_TRUTH = {
    "INT001": {
        "Arabic": "يقع Nile Pearl Hotel في القاهرة، مصر.",
        "English": "Nile Pearl Hotel is located in Cairo, Egypt.",
        "French": "Le Nile Pearl Hotel est situé au Caire, en Égypte.",
        "Russian": "Отель Nile Pearl Hotel расположен в Каире, Египет."
    },

    "INT002": {
        "Arabic": "Nile Pearl Hotel هو فندق من فئة 5 نجوم.",
        "English": "Nile Pearl Hotel is a 5-star hotel.",
        "French": "Le Nile Pearl Hotel est un hôtel 5 étoiles.",
        "Russian": "Nile Pearl Hotel — пятизвездочный отель."
    },

    "INT003": {
        "Arabic": "مكتب استقبال Nile Pearl Hotel متاح على مدار الساعة.",
        "English": "Nile Pearl Hotel reception is available 24 hours a day.",
        "French": "La réception du Nile Pearl Hotel est disponible 24 heures sur 24.",
        "Russian": "Стойка регистрации Nile Pearl Hotel работает круглосуточно."
    },

    "INT004": {
        "Arabic": "وقت تسجيل الوصول المعتاد هو الساعة 2:00 مساءً.",
        "English": "The standard check-in time is 2:00 PM.",
        "French": "L'heure normale d'arrivée est 14h00.",
        "Russian": "Стандартное время заезда — 14:00."
    },

    "INT005": {
        "Arabic": "وقت تسجيل المغادرة المعتاد هو الساعة 12:00 ظهرًا.",
        "English": "The standard check-out time is 12:00 PM.",
        "French": "L'heure normale de départ est 12h00.",
        "Russian": "Стандартное время выезда — 12:00."
    },

    "INT006": {
        "Arabic": "يمكن طلب تسجيل الوصول المبكر، ويعتمد ذلك على التوافر.",
        "English": "Early check-in can be requested and is subject to availability.",
        "French": "L'arrivée anticipée peut être demandée et dépend de la disponibilité.",
        "Russian": "Ранний заезд можно запросить, но он зависит от наличия свободных номеров."
    },

    "INT007": {
        "Arabic": "يمكن طلب تسجيل المغادرة المتأخر، ويعتمد ذلك على التوافر.",
        "English": "Late check-out can be requested and is subject to availability.",
        "French": "Un départ tardif peut être demandé et dépend de la disponibilité.",
        "Russian": "Поздний выезд можно запросить, но он зависит от наличия."
    },

    "INT008": {
        "Arabic": "يجب تقديم وثيقة هوية سارية عند تسجيل الوصول.",
        "English": "A valid identification document is required at check-in.",
        "French": "Une pièce d'identité valide est requise lors de l'enregistrement.",
        "Russian": "При регистрации необходимо предъявить действительный документ, удостоверяющий личность."
    },
}

# ============================================================
# 6. FILL GROUND TRUTH + ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🛠️ REPAIRING BATCH 03")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(row["intent_id"]).strip()
    language = str(row["language"]).strip()

    assert intent_id in INTENTS, (
        f"❌ Unknown intent: {intent_id}"
    )

    assert language in {
        "Arabic",
        "English",
        "French",
        "Russian"
    }, (
        f"❌ Unknown language: {language}"
    )

    gt = GROUND_TRUTH[intent_id][language]

    batch_df.at[idx, "ground_truth"] = gt
    batch_df.at[idx, "answer"] = gt

    batch_df.at[idx, "status"] = "generated"
    batch_df.at[idx, "category"] = "Hotel FAQ"
    batch_df.at[idx, "source"] = "Generated Batch 03"
    batch_df.at[idx, "attempts"] = 0
    batch_df.at[idx, "difficulty"] = "Easy"

print("✅ Ground truth filled for all 32 questions.")
print("✅ Answers filled for all 32 questions.")

# ============================================================
# 7. SAVE REPAIRED BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print(f"💾 Batch 03 repaired and saved:")
print(BATCH_FILE)

print("\n⚠️ hotel_faq_final.csv was NOT modified.")

# ============================================================
# 8. ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(289, 321)
]

actual_ids = batch_df["faq_id"].tolist()

assert actual_ids == expected_ids

print("✅ IDs are exactly FAQ0289 → FAQ0320.")
print("✅ No duplicate IDs.")

assert batch_df["faq_id"].is_unique

existing_ids = set(df["faq_id"])
batch_ids = set(batch_df["faq_id"])

assert not existing_ids.intersection(batch_ids)

print("✅ No ID overlap with existing 288.")

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = str(text)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 10. QUESTION DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION DUPLICATE CHECK")
print("=" * 100)

assert not batch_df["question"].duplicated().any()

print("✅ No exact duplicate questions inside Batch 03.")

batch_normalized = batch_df["question"].map(
    normalize_question
)

assert not batch_normalized.duplicated().any()

print("✅ No normalized duplicates inside Batch 03.")

# ============================================================
# 11. COMPARE WITH EXISTING 288
# ============================================================

existing_questions = set(
    df["question"]
    .astype(str)
    .str.strip()
)

new_questions = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = (
    existing_questions
    .intersection(new_questions)
)

assert not exact_overlap

print("✅ No exact overlap with existing 288.")

existing_normalized = set(
    df["question"].map(normalize_question)
)

normalized_overlap = (
    existing_normalized
    .intersection(set(batch_normalized))
)

assert not normalized_overlap

print("✅ No normalized overlap with existing 288.")

# ============================================================
# 12. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = batch_df[col].isna().sum()

    empty = (
        batch_df[col]
        .astype(str)
        .str.strip()
        .isin(["", "None", "nan"])
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

# ============================================================
# 13. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert language_counts.to_dict() == (
    expected_language_counts
)

print("✅ 8 questions × 4 languages.")

# ============================================================
# 14. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

expected_intent_counts = {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

assert intent_counts.to_dict() == (
    expected_intent_counts
)

print("✅ 4 questions × 8 intents.")

# ============================================================
# 15. INTENT NAME CONSISTENCY
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

for _, row in batch_df.iterrows():

    expected_name = INTENTS[row["intent_id"]]

    assert row["intent_name"] == expected_name

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 16. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPES")
print("=" * 100)

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario"
}

invalid_types = (
    set(batch_df["question_type"])
    - VALID_TYPES
)

assert not invalid_types

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 17. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert batch_df["ground_truth"].notna().all()
assert batch_df["answer"].notna().all()

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 03 FINAL RESULT")
print("=" * 100)

print("""
🟢 BATCH 03 IS VALID

✅ 32 questions
✅ FAQ0289 → FAQ0320
✅ Ground truth complete
✅ Answers complete
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 288
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Question types valid
✅ Existing dataset NOT modified

🎉 SAFE TO MERGE BATCH 03
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 03 REPAIR + FINAL VALIDATION
====================================================================================================
✅ Project root found.
✅ Final dataset found.
✅ Batch 03 found.

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 288 rows
Batch 03         : 32 rows
✅ All 13 required columns exist.

====================================================================================================
🛠️ REPAIRING BATCH 03
====================================================================================================
✅ Ground truth filled for all 32 questions.
✅ Answers filled for all 32 questions.
💾 Batch 03 repaired and saved:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_03.csv

⚠️ hotel_faq_final.csv was NOT modified.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0289 → FAQ0320.
✅ No duplicate IDs.
✅ No ID overlap with existing 288.

====================================================================================================
📝 QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions inside Batch 03.
✅ No normalized duplicates inside Batch 03.
✅ No exact overlap with existing 288.
✅ No normalized overlap with existing 288.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 questions × 8 intents.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPES
====================================================================================================
question_type
Scenario    20
Direct      12
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🏆 BATCH 03 FINAL RESULT
====================================================================================================

🟢 BATCH 03 IS VALID

✅ 32 questions
✅ FAQ0289 → FAQ0320
✅ Ground truth complete
✅ Answers complete
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 288
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Required fields complete
✅ Question types valid
✅ Existing dataset NOT modified

🎉 SAFE TO MERGE BATCH 03

====================================================================================================

/var/folders/3j/_3bjs5gd14318wgzhfc9xhth0000gn/T/ipykernel_47090/1909602235.py:203: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'يقع Nile Pearl Hotel في القاهرة، مصر.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_df.at[idx, "ground_truth"] = gt
/var/folders/3j/_3bjs5gd14318wgzhfc9xhth0000gn/T/ipykernel_47090/1909602235.py:204: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'يقع Nile Pearl Hotel في القاهرة، مصر.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_df.at[idx, "answer"] = gt

In [22]:
from pathlib import Path
import pandas as pd
from datetime import datetime

# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 03
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_03.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 03")
print("=" * 100)

# ------------------------------------------------------------
# 1. LOAD
# ------------------------------------------------------------

df = pd.read_csv(FINAL_DATASET)
batch_df = pd.read_csv(BATCH_FILE)

assert len(df) == 288
assert len(batch_df) == 32

print(f"Current dataset : {len(df)}")
print(f"Batch 03        : {len(batch_df)}")

# ------------------------------------------------------------
# 2. VERIFY BATCH IDS
# ------------------------------------------------------------

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(289, 321)
]

assert batch_df["faq_id"].tolist() == expected_ids

print("✅ Batch IDs: FAQ0289 → FAQ0320")

# ------------------------------------------------------------
# 3. VERIFY NO ID OVERLAP
# ------------------------------------------------------------

existing_ids = set(df["faq_id"])
batch_ids = set(batch_df["faq_id"])

assert not existing_ids.intersection(batch_ids)

print("✅ No FAQ ID overlap.")

# ------------------------------------------------------------
# 4. VERIFY NO QUESTION OVERLAP
# ------------------------------------------------------------

def normalize_question(text):
    return (
        str(text)
        .casefold()
        .strip()
    )

existing_questions = set(
    df["question"]
    .map(normalize_question)
)

batch_questions = set(
    batch_df["question"]
    .map(normalize_question)
)

assert not existing_questions.intersection(
    batch_questions
)

print("✅ No question overlap.")

# ------------------------------------------------------------
# 5. BACKUP CURRENT 288
# ------------------------------------------------------------

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_file = (
    BACKUP_DIR
    / f"hotel_faq_before_batch03_{timestamp}.csv"
)

df.to_csv(
    backup_file,
    index=False,
    encoding="utf-8-sig"
)

print("💾 Backup created:")
print(backup_file)

# ------------------------------------------------------------
# 6. MERGE
# ------------------------------------------------------------

merged_df = pd.concat(
    [df, batch_df],
    ignore_index=True
)

# ------------------------------------------------------------
# 7. FINAL ID CHECK
# ------------------------------------------------------------

expected_final_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

assert merged_df["faq_id"].tolist() == expected_final_ids

print("✅ Final IDs are continuous:")
print("   FAQ0001 → FAQ0320")

# ------------------------------------------------------------
# 8. FINAL ROW COUNT
# ------------------------------------------------------------

assert len(merged_df) == 320

print("✅ Final row count: 320")

# ------------------------------------------------------------
# 9. DUPLICATE CHECK
# ------------------------------------------------------------

assert merged_df["faq_id"].is_unique
assert not merged_df["question"].duplicated().any()

print("✅ No duplicate FAQ IDs.")
print("✅ No duplicate questions.")

# ------------------------------------------------------------
# 10. SAVE
# ------------------------------------------------------------

merged_df.to_csv(
    FINAL_DATASET,
    index=False,
    encoding="utf-8-sig"
)

print("\n💾 FINAL DATASET UPDATED:")
print(FINAL_DATASET)

# ------------------------------------------------------------
# 11. RELOAD CHECK
# ------------------------------------------------------------

check_df = pd.read_csv(FINAL_DATASET)

assert len(check_df) == 320

assert check_df["faq_id"].tolist() == expected_final_ids

assert check_df["faq_id"].is_unique

assert not check_df["question"].duplicated().any()

# ------------------------------------------------------------
# 12. RESULT
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("🏆 MERGE RESULT")
print("=" * 100)

print("""
🟢 BATCH 03 MERGED SUCCESSFULLY

Previous dataset : 288
Added questions  : 32
Final dataset    : 320

IDs:
FAQ0001 → FAQ0320

✅ Backup created
✅ 32 new questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ IDs continuous
✅ Final dataset reloaded successfully
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 03
====================================================================================================
Current dataset : 288
Batch 03        : 32
✅ Batch IDs: FAQ0289 → FAQ0320
✅ No FAQ ID overlap.
✅ No question overlap.
💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch03_20260821_144420.csv
✅ Final IDs are continuous:
   FAQ0001 → FAQ0320
✅ Final row count: 320
✅ No duplicate FAQ IDs.
✅ No duplicate questions.

💾 FINAL DATASET UPDATED:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 MERGE RESULT
====================================================================================================

🟢 BATCH 03 MERGED SUCCESSFULLY

Previous dataset : 288
Added questions  : 32
Final dataset    : 320

IDs:
FAQ0001 → FAQ0320

✅ Backup created
✅ 32 new questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ IDs continuous
✅ Final dataset reloaded successfully

====================================================================================================

In [23]:
from pathlib import Path
import pandas as pd
import re

# ============================================================
# 🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
# READ-ONLY
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_03 = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_03.csv"
)

# ============================================================
# REQUIRED STRUCTURE
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

VALID_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

# ============================================================
# NORMALIZATION
# ============================================================

def normalize_question(text):
    text = str(text).casefold().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[?!.,،؛:]+$", "", text)
    return text

# ============================================================
# HEADER
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK")
print("=" * 100)

print(f"\n📂 Project root:")
print(PROJECT_ROOT)

print(f"\n📄 Dataset:")
print(DATASET)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert DATASET.exists(), "❌ Final dataset not found."

print("✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(DATASET)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# COLUMN VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Column structure/order is incorrect.\n"
    f"Expected:\n{REQUIRED_COLUMNS}\n"
    f"Actual:\n{list(df.columns)}"
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

print(f"Total questions: {len(df)}")

assert len(df) == 320, (
    f"❌ Expected 320 questions, found {len(df)}"
)

print("✅ Dataset contains exactly 320 questions.")

# ============================================================
# FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

id_pattern = re.compile(r"^FAQ\d{4}$")

invalid_ids = [
    x for x in df["faq_id"].astype(str)
    if not id_pattern.fullmatch(x)
]

assert not invalid_ids, (
    f"❌ Invalid FAQ IDs:\n{invalid_ids}"
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# DUPLICATE IDS
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    f"❌ Duplicate FAQ IDs:\n"
    f"{duplicate_ids[['faq_id']]}"
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# ID CONTINUITY
# ============================================================

print("\n" + "=" * 100)
print("🔢 FAQ ID CONTINUITY")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

actual_ids = df["faq_id"].astype(str).tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ ID sequence is incorrect.\n"
    f"Expected first 10: {expected_ids[:10]}\n"
    f"Actual first 10  : {actual_ids[:10]}\n"
    f"Expected last 10 : {expected_ids[-10:]}\n"
    f"Actual last 10   : {actual_ids[-10:]}"
)

print("✅ IDs are continuous: FAQ0001 → FAQ0320")
print("✅ FAQ IDs are correctly ordered.")

# ============================================================
# REQUIRED FIELD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(df[col].isna().sum())

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, (
        f"❌ Missing values in {col}"
    )

    assert empty == 0, (
        f"❌ Empty values in {col}"
    )

# ============================================================
# EXACT QUESTION DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

assert exact_duplicates.empty, (
    "❌ Exact duplicate questions found:\n"
    f"{exact_duplicates[['faq_id', 'question']]}"
)

print("✅ No exact duplicate questions.")

# ============================================================
# NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED QUESTION DUPLICATE CHECK")
print("=" * 100)

df["_normalized_question"] = (
    df["question"]
    .map(normalize_question)
)

normalized_duplicates = df[
    df["_normalized_question"].duplicated(keep=False)
]

assert normalized_duplicates.empty, (
    "❌ Normalized duplicate questions found:\n"
    f"{normalized_duplicates[['faq_id', 'question']]}"
)

print("✅ No normalized duplicate questions.")

# ============================================================
# LANGUAGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts)

assert set(language_counts.index) == VALID_LANGUAGES

assert all(
    language_counts.get(lang, 0) == 80
    for lang in VALID_LANGUAGES
)

print("✅ Language balance: 80 × 4 languages.")

# ============================================================
# INTENT DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
)

print(intent_counts.to_string(index=False))

assert set(df["intent_id"]) == set(INTENTS)

for intent_id, intent_name in INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    assert len(subset) == 40, (
        f"❌ {intent_id} expected 40 questions, "
        f"found {len(subset)}"
    )

    assert (
        subset["intent_name"] == intent_name
    ).all(), (
        f"❌ Intent name mismatch for {intent_id}"
    )

print("✅ Intent balance: 40 × 8 intents.")

# ============================================================
# INTENT ID ↔ NAME
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

for intent_id, intent_name in INTENTS.items():

    names = set(
        df.loc[
            df["intent_id"] == intent_id,
            "intent_name"
        ]
    )

    assert names == {intent_name}

print("✅ Every intent_id maps to exactly one intent_name.")

# ============================================================
# QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(question_type_counts)

assert set(question_type_counts.index) <= VALID_QUESTION_TYPES

print("✅ All question types are valid.")

# ============================================================
# STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS DISTRIBUTION")
print("=" * 100)

print(df["status"].value_counts())

assert set(df["status"]) <= VALID_STATUS

print("✅ Status values are valid.")

# ============================================================
# DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)

print(df["difficulty"].value_counts())

assert set(df["difficulty"]) <= VALID_DIFFICULTY

print("✅ Difficulty values are valid.")

# ============================================================
# GROUND TRUTH / ANSWERS
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

gt_empty = (
    df["ground_truth"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

answer_empty = (
    df["answer"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

assert gt_empty == 0
assert answer_empty == 0

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# LANGUAGE × INTENT MATRIX
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(language_intent)

for intent_id in INTENTS:

    for language in VALID_LANGUAGES:

        value = language_intent.loc[
            intent_id,
            language
        ]

        assert value == 10, (
            f"❌ {intent_id} / {language}: "
            f"expected 10, found {value}"
        )

print("✅ Every intent has 10 questions per language.")

# ============================================================
# DUPLICATES BY INTENT
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES BY INTENT")
print("=" * 100)

duplicates_by_intent = df[
    df.groupby(
        "intent_id"
    )["_normalized_question"]
    .transform("duplicated")
]

assert duplicates_by_intent.empty, (
    "❌ Duplicate questions found inside an intent."
)

print("✅ No normalized duplicates inside the same intent.")

# ============================================================
# BATCH 03 vs ORIGINAL 288
# ============================================================

print("\n" + "=" * 100)
print("🔄 BATCH 03 vs ORIGINAL 288")
print("=" * 100)

assert BATCH_03.exists(), (
    "❌ Batch 03 file not found."
)

batch03 = pd.read_csv(BATCH_03)

assert len(batch03) == 32

print("Batch 03 rows: 32")
print("Original rows: 288")

original_df = df[
    df["faq_id"].isin(
        [
            f"FAQ{i:04d}"
            for i in range(1, 289)
        ]
    )
]

batch_questions = set(
    batch03["question"]
    .map(normalize_question)
)

original_questions = set(
    original_df["question"]
    .map(normalize_question)
)

overlap = batch_questions.intersection(
    original_questions
)

assert not overlap, (
    f"❌ Batch 03 overlaps with original 288:\n{overlap}"
)

print("✅ No normalized overlap.")
print("✅ Batch 03 is clean against original 288.")

# ============================================================
# REMOVE TEMP COLUMN
# ============================================================

df.drop(
    columns=["_normalized_question"],
    inplace=True
)

# ============================================================
# FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET QUALITY RESULT")
print("=" * 100)

print("""
🟢 DATASET IS VALID

✅ 320 questions
✅ FAQ0001 → FAQ0320
✅ IDs continuous and ordered
✅ No duplicate IDs
✅ No exact duplicate questions
✅ No normalized duplicate questions
✅ Required fields complete
✅ 80 Arabic
✅ 80 English
✅ 80 French
✅ 80 Russian
✅ 40 questions per intent
✅ 10 questions per language × intent
✅ Intent names consistent
✅ Question types valid
✅ Status values valid
✅ Difficulty values valid
✅ Ground truth complete
✅ Answers complete
✅ Batch 03 has no overlap with original 288

🔒 READ-ONLY CHECK
✅ hotel_faq_final.csv was NOT modified.
""")

print("=" * 100)
print("🎉 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
✅ Project root found.
✅ Dataset found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 320
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
Total questions: 320
✅ Dataset contains exactly 320 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

====================================================================================================
🔢 FAQ ID CONTINUITY
====================================================================================================
✅ IDs are continuous: FAQ0001 → FAQ0320
✅ FAQ IDs are correctly ordered.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0

====================================================================================================
📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED QUESTION DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    80
Arabic     80
French     80
Russian    80
Name: count, dtype: int64
✅ Language balance: 80 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         40
   INT002          hotel_category         40
   INT003  reception_availability         40
   INT004           check_in_time         40
   INT005          check_out_time         40
   INT006          early_check_in         40
   INT007          late_check_out         40
   INT008 identification_required         40
✅ Intent balance: 40 × 8 intents.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ Every intent_id maps to exactly one intent_name.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    128
Direct         108
Scenario        84
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated     96
Name: count, dtype: int64
✅ Status values are valid.

====================================================================================================
📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    320
Name: count, dtype: int64
✅ Difficulty values are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         10       10      10       10
INT002         10       10      10       10
INT003         10       10      10       10
INT004         10       10      10       10
INT005         10       10      10       10
INT006         10       10      10       10
INT007         10       10      10       10
INT008         10       10      10       10
✅ Every intent has 10 questions per language.

====================================================================================================
🔍 DUPLICATES BY INTENT
====================================================================================================

ValueError: 'duplicated' is not a valid function name for transform(name)

In [24]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
# ============================================================
# READ-ONLY
# This code DOES NOT modify the dataset.
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

# ============================================================
# 1. PROJECT AUTO DETECTION
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK")
print("=" * 100)

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = next(
    (p for p in possible_roots if p.exists()),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project root not found."
    )

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Final dataset not found:\n{DATASET_PATH}"
    )

print(f"\n📂 Project root:\n{PROJECT_ROOT}")
print(f"\n📄 Dataset:\n{DATASET_PATH}")
print("✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    col for col in REQUIRED_COLUMNS
    if col not in df.columns
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

print(f"✅ All {len(REQUIRED_COLUMNS)} required columns exist.")

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Column order is incorrect.\n"
    f"Expected: {REQUIRED_COLUMNS}\n"
    f"Actual  : {list(df.columns)}"
)

print("✅ Column order is correct.")

# ============================================================
# 4. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

assert len(df) == 320, (
    f"❌ Expected 320 questions, found {len(df)}"
)

print("Total questions:", len(df))
print("✅ Dataset contains exactly 320 questions.")

# ============================================================
# 5. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

id_pattern = re.compile(r"^FAQ\d{4}$")

invalid_ids = df[
    ~df["faq_id"].astype(str).str.match(id_pattern)
]

assert invalid_ids.empty, (
    "❌ Invalid FAQ IDs found:\n"
    + invalid_ids[
        ["faq_id"]
    ].to_string(index=False)
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# 6. DUPLICATE FAQ IDS
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    "❌ Duplicate FAQ IDs found:\n"
    + duplicate_ids[
        ["faq_id"]
    ].to_string(index=False)
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 7. FAQ ID CONTINUITY + ORDER
# ============================================================

print("\n" + "=" * 100)
print("🔢 FAQ ID CONTINUITY")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

actual_ids = df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ ID sequence is incorrect.\n"
    f"Expected first: {expected_ids[:10]}\n"
    f"Actual first  : {actual_ids[:10]}\n"
    f"Expected last : {expected_ids[-10:]}\n"
    f"Actual last   : {actual_ids[-10:]}"
)

print("✅ IDs are continuous: FAQ0001 → FAQ0320")
print("✅ FAQ IDs are correctly ordered.")

# ============================================================
# 8. REQUIRED FIELD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = df[col].isna().sum()

    empty = (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, (
        f"❌ Missing values in {col}"
    )

    assert empty == 0, (
        f"❌ Empty values in {col}"
    )

# ============================================================
# 9. NORMALIZATION FUNCTION
# ============================================================

def normalize_question(text):
    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # Lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    # Normalize whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


df["_normalized_question"] = (
    df["question"]
    .apply(normalize_question)
)

# ============================================================
# 10. EXACT QUESTION DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(
        exact_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Exact duplicate questions found."
    )

# ============================================================
# 11. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED QUESTION DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized_question"].duplicated(
        keep=False
    )
]

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Normalized duplicate questions found."
    )

# ============================================================
# 12. DUPLICATES INSIDE SAME INTENT
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES BY INTENT")
print("=" * 100)

duplicate_mask = df.duplicated(
    subset=[
        "intent_id",
        "_normalized_question"
    ],
    keep=False
)

duplicates_by_intent = df.loc[
    duplicate_mask,
    [
        "faq_id",
        "intent_id",
        "language",
        "question",
    ]
]

if duplicates_by_intent.empty:
    print(
        "✅ No normalized duplicates inside "
        "the same intent."
    )
else:
    print(
        duplicates_by_intent.to_string(
            index=False
        )
    )

    raise AssertionError(
        "❌ Duplicate questions found inside an intent."
    )

# ============================================================
# 13. LANGUAGE DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts)

expected_languages = {
    "Arabic": 80,
    "English": 80,
    "French": 80,
    "Russian": 80,
}

assert set(language_counts.index) == set(
    expected_languages.keys()
)

for language, expected_count in expected_languages.items():

    actual_count = language_counts.get(
        language,
        0
    )

    assert actual_count == expected_count, (
        f"❌ {language}: expected "
        f"{expected_count}, found "
        f"{actual_count}"
    )

print("✅ Language balance: 80 × 4 languages.")

# ============================================================
# 14. INTENT DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(
        name="questions"
    )
)

print(
    intent_counts.to_string(
        index=False
    )
)

assert len(intent_counts) == 8, (
    "❌ Expected 8 intents."
)

assert all(
    intent_counts["questions"] == 40
), (
    "❌ Each intent should contain 40 questions."
)

print("✅ Intent balance: 40 × 8 intents.")

# ============================================================
# 15. INTENT ID ↔ NAME CONSISTENCY
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_mapping = (
    df.groupby("intent_id")["intent_name"]
    .nunique()
)

assert all(
    intent_mapping == 1
), (
    "❌ An intent_id maps to multiple intent names."
)

print(
    "✅ Every intent_id maps to exactly "
    "one intent_name."
)

# ============================================================
# 16. EXPECTED INTENTS
# ============================================================

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    assert not subset.empty, (
        f"❌ Missing intent: {intent_id}"
    )

    assert (
        subset["intent_name"]
        .eq(intent_name)
        .all()
    ), (
        f"❌ Incorrect intent_name "
        f"for {intent_id}"
    )

print(
    "✅ All 8 intent mappings are correct."
)

# ============================================================
# 17. QUESTION TYPE
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(question_type_counts)

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = set(
    question_type_counts.index
) - VALID_TYPES

assert not invalid_types, (
    f"❌ Invalid question types: {invalid_types}"
)

print("✅ All question types are valid.")

# ============================================================
# 18. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS DISTRIBUTION")
print("=" * 100)

print(
    df["status"].value_counts()
)

print("✅ Status field complete.")

# ============================================================
# 19. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)

print(
    df["difficulty"].value_counts()
)

assert (
    df["difficulty"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Difficulty field complete.")

# ============================================================
# 20. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 21. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(language_intent)

for intent_id in EXPECTED_INTENTS:

    for language in expected_languages:

        count = language_intent.loc[
            intent_id,
            language
        ]

        assert count == 10, (
            f"❌ {intent_id} / {language}: "
            f"expected 10, found {count}"
        )

print(
    "✅ Every intent contains "
    "10 questions in each language."
)

# ============================================================
# 22. QUESTION TYPE × LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("📊 QUESTION TYPE × LANGUAGE")
print("=" * 100)

print(
    pd.crosstab(
        df["language"],
        df["question_type"]
    )
)

# ============================================================
# 23. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET CHECK RESULT")
print("=" * 100)

print("""
🟢 DATASET IS VALID

✅ 320 questions
✅ FAQ0001 → FAQ0320
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No duplicates inside the same intent
✅ Required fields complete
✅ 80 Arabic
✅ 80 English
✅ 80 French
✅ 80 Russian
✅ 40 questions per intent
✅ Intent names consistent
✅ Question types valid
✅ Ground truth complete
✅ Answers complete
✅ Language × Intent balanced
""")

# ============================================================
# 24. READ-ONLY CONFIRMATION
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CHECK")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows were added.")
print("✅ No rows were deleted.")
print("✅ No values were changed.")

# Remove temporary column from memory only
df = df.drop(
    columns=["_normalized_question"]
)

print("\n" + "=" * 100)
print("🎉 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE DATASET QUALITY CHECK
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
✅ Project root found.
✅ Dataset found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 320
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
Total questions: 320
✅ Dataset contains exactly 320 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

====================================================================================================
🔢 FAQ ID CONTINUITY
====================================================================================================
✅ IDs are continuous: FAQ0001 → FAQ0320
✅ FAQ IDs are correctly ordered.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0

====================================================================================================
📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED QUESTION DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 DUPLICATES BY INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    80
Arabic     80
French     80
Russian    80
Name: count, dtype: int64
✅ Language balance: 80 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         40
   INT002          hotel_category         40
   INT003  reception_availability         40
   INT004           check_in_time         40
   INT005          check_out_time         40
   INT006          early_check_in         40
   INT007          late_check_out         40
   INT008 identification_required         40
✅ Intent balance: 40 × 8 intents.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ Every intent_id maps to exactly one intent_name.
✅ All 8 intent mappings are correct.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    128
Direct         108
Scenario        84
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated     96
Name: count, dtype: int64
✅ Status field complete.

====================================================================================================
📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    320
Name: count, dtype: int64
✅ Difficulty field complete.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         10       10      10       10
INT002         10       10      10       10
INT003         10       10      10       10
INT004         10       10      10       10
INT005         10       10      10       10
INT006         10       10      10       10
INT007         10       10      10       10
INT008         10       10      10       10
✅ Every intent contains 10 questions in each language.

====================================================================================================
📊 QUESTION TYPE × LANGUAGE
====================================================================================================
question_type  Direct  Paraphrased  Scenario
language
Arabic             28           33        19
English            32           29        19
French             24           37        19
Russian            24           29        27

====================================================================================================
🏆 FINAL DATASET CHECK RESULT
====================================================================================================

🟢 DATASET IS VALID

✅ 320 questions
✅ FAQ0001 → FAQ0320
✅ No duplicate IDs
✅ No missing IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No duplicates inside the same intent
✅ Required fields complete
✅ 80 Arabic
✅ 80 English
✅ 80 French
✅ 80 Russian
✅ 40 questions per intent
✅ Intent names consistent
✅ Question types valid
✅ Ground truth complete
✅ Answers complete
✅ Language × Intent balanced

====================================================================================================
🔒 READ-ONLY CHECK
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ No rows were added.
✅ No rows were deleted.
✅ No values were changed.

====================================================================================================
🎉 CHECK COMPLETE
====================================================================================================

In [25]:
# ============================================================
# 🏨 HOTEL AI - FULL DATASET CHECK
# ============================================================
# READ-ONLY — NO MODIFICATIONS
# Checks ALL existing questions.
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - FULL DATASET QUALITY CHECK")
print("=" * 100)

# ============================================================
# 1. FIND PROJECT
# ============================================================

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = next(
    (p for p in possible_roots if p.exists()),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project root was not found."
    )

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

print(f"\n📂 Project root:\n{PROJECT_ROOT}")
print(f"\n📄 Dataset:\n{DATASET_PATH}")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN CHECK")
print("=" * 100)

missing_columns = [
    c for c in REQUIRED_COLUMNS
    if c not in df.columns
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Column order is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

print(f"Total questions: {len(df)}")

assert len(df) == 320, (
    f"❌ Expected 320 questions, found {len(df)}"
)

print("✅ Exactly 320 questions.")

# ============================================================
# 5. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID CHECK")
print("=" * 100)

valid_id = df["faq_id"].astype(str).str.fullmatch(
    r"FAQ\d{4}"
)

assert valid_id.all(), (
    "❌ Invalid FAQ ID format found."
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# 6. DUPLICATE IDS
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    "❌ Duplicate FAQ IDs found:\n"
    + duplicate_ids.to_string(index=False)
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 7. ID CONTINUITY
# ============================================================

print("\n" + "=" * 100)
print("🔢 FAQ ID CONTINUITY")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

actual_ids = df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ IDs are not continuous or correctly ordered.\n"
    f"First actual IDs: {actual_ids[:10]}\n"
    f"Last actual IDs : {actual_ids[-10:]}"
)

print("✅ FAQ0001 → FAQ0320")
print("✅ IDs continuous and correctly ordered.")

# ============================================================
# 8. REQUIRED VALUES
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD CHECK")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = df[col].isna().sum()

    empty = (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, (
        f"❌ Missing values in {col}"
    )

    assert empty == 0, (
        f"❌ Empty values in {col}"
    )

print("✅ All required fields complete.")

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.lower()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


normalized = df["question"].apply(
    normalize_question
)

# ============================================================
# 10. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATES")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        exact_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Exact duplicate questions found."
    )

# ============================================================
# 11. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED DUPLICATES")
print("=" * 100)

normalized_duplicates = df[
    normalized.duplicated(keep=False)
]

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Normalized duplicate questions found."
    )

# ============================================================
# 12. DUPLICATES INSIDE SAME INTENT
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

temp = df[
    [
        "faq_id",
        "intent_id",
        "language",
        "question"
    ]
].copy()

temp["_normalized"] = normalized

same_intent_duplicates = temp[
    temp.duplicated(
        subset=[
            "intent_id",
            "_normalized"
        ],
        keep=False
    )
]

assert same_intent_duplicates.empty, (
    "❌ Duplicate questions found inside same intent:\n"
    + same_intent_duplicates.to_string(index=False)
)

print(
    "✅ No normalized duplicates inside the same intent."
)

# ============================================================
# 13. LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts)

expected_languages = {
    "Arabic": 80,
    "English": 80,
    "French": 80,
    "Russian": 80,
}

assert set(language_counts.index) == set(
    expected_languages
)

for language, expected in expected_languages.items():

    actual = language_counts.get(
        language,
        0
    )

    assert actual == expected, (
        f"❌ {language}: "
        f"expected {expected}, found {actual}"
    )

print("✅ 80 questions × 4 languages.")

# ============================================================
# 14. INTENTS
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(
        name="questions"
    )
)

print(
    intent_counts.to_string(
        index=False
    )
)

assert len(intent_counts) == 8

assert all(
    intent_counts["questions"] == 40
)

print("✅ 40 questions × 8 intents.")

# ============================================================
# 15. INTENT MAPPING
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for intent_id, expected_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    assert len(subset) == 40

    assert (
        subset["intent_name"]
        .eq(expected_name)
        .all()
    ), (
        f"❌ Incorrect intent name for {intent_id}"
    )

print("✅ All intent mappings are correct.")

# ============================================================
# 16. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE CHECK")
print("=" * 100)

question_types = df["question_type"].value_counts()

print(question_types)

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = (
    set(question_types.index)
    - VALID_TYPES
)

assert not invalid_types, (
    f"❌ Invalid question types: {invalid_types}"
)

print("✅ All question types are valid.")

# ============================================================
# 17. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS CHECK")
print("=" * 100)

print(
    df["status"].value_counts()
)

print("✅ Status values populated.")

# ============================================================
# 18. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY CHECK")
print("=" * 100)

print(
    df["difficulty"].value_counts()
)

assert (
    df["difficulty"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Difficulty values populated.")

# ============================================================
# 19. GROUND TRUTH + ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert (
    df["ground_truth"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    df["answer"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 20. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT")
print("=" * 100)

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(matrix)

for intent_id in EXPECTED_INTENTS:

    for language in expected_languages:

        count = matrix.loc[
            intent_id,
            language
        ]

        assert count == 10, (
            f"❌ {intent_id} / {language}: "
            f"expected 10, found {count}"
        )

print(
    "✅ Every intent has 10 questions "
    "in every language."
)

# ============================================================
# 21. QUESTION TYPE × LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("📊 QUESTION TYPE × LANGUAGE")
print("=" * 100)

print(
    pd.crosstab(
        df["language"],
        df["question_type"]
    )
)

# ============================================================
# 22. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL DATASET CHECK RESULT")
print("=" * 100)

print("""
🟢 DATASET IS VALID

✅ ALL 320 QUESTIONS CHECKED
✅ FAQ0001 → FAQ0320
✅ No duplicate IDs
✅ No missing IDs
✅ No exact duplicate questions
✅ No normalized duplicate questions
✅ No duplicates inside the same intent
✅ All 13 columns valid
✅ All required fields complete
✅ 80 Arabic
✅ 80 English
✅ 80 French
✅ 80 Russian
✅ 40 questions per intent
✅ Intent mappings correct
✅ Question types valid
✅ Ground truth complete
✅ Answers complete
✅ Language × Intent balanced
""")

# ============================================================
# 23. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 COMPLETE CHECK FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FULL DATASET QUALITY CHECK
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 320
Columns : 13

====================================================================================================
🧪 COLUMN CHECK
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
Total questions: 320
✅ Exactly 320 questions.

====================================================================================================
🆔 FAQ ID CHECK
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

====================================================================================================
🔢 FAQ ID CONTINUITY
====================================================================================================
✅ FAQ0001 → FAQ0320
✅ IDs continuous and correctly ordered.

====================================================================================================
🧪 REQUIRED FIELD CHECK
====================================================================================================
faq_id          Missing: 0   Empty: 0
intent_id       Missing: 0   Empty: 0
language        Missing: 0   Empty: 0
question_type   Missing: 0   Empty: 0
question        Missing: 0   Empty: 0
status          Missing: 0   Empty: 0
intent_name     Missing: 0   Empty: 0
ground_truth    Missing: 0   Empty: 0
category        Missing: 0   Empty: 0
source          Missing: 0   Empty: 0
attempts        Missing: 0   Empty: 0
difficulty      Missing: 0   Empty: 0
answer          Missing: 0   Empty: 0
✅ All required fields complete.

====================================================================================================
📝 EXACT QUESTION DUPLICATES
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED DUPLICATES
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    80
Arabic     80
French     80
Russian    80
Name: count, dtype: int64
✅ 80 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         40
   INT002          hotel_category         40
   INT003  reception_availability         40
   INT004           check_in_time         40
   INT005          check_out_time         40
   INT006          early_check_in         40
   INT007          late_check_out         40
   INT008 identification_required         40
✅ 40 questions × 8 intents.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ All intent mappings are correct.

====================================================================================================
📝 QUESTION TYPE CHECK
====================================================================================================
question_type
Paraphrased    128
Direct         108
Scenario        84
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS CHECK
====================================================================================================
status
valid        224
generated     96
Name: count, dtype: int64
✅ Status values populated.

====================================================================================================
📌 DIFFICULTY CHECK
====================================================================================================
difficulty
Easy    320
Name: count, dtype: int64
✅ Difficulty values populated.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📊 LANGUAGE × INTENT
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         10       10      10       10
INT002         10       10      10       10
INT003         10       10      10       10
INT004         10       10      10       10
INT005         10       10      10       10
INT006         10       10      10       10
INT007         10       10      10       10
INT008         10       10      10       10
✅ Every intent has 10 questions in every language.

====================================================================================================
📊 QUESTION TYPE × LANGUAGE
====================================================================================================
question_type  Direct  Paraphrased  Scenario
language
Arabic             28           33        19
English            32           29        19
French             24           37        19
Russian            24           29        27

====================================================================================================
🏆 FINAL DATASET CHECK RESULT
====================================================================================================

🟢 DATASET IS VALID

✅ ALL 320 QUESTIONS CHECKED
✅ FAQ0001 → FAQ0320
✅ No duplicate IDs
✅ No missing IDs
✅ No exact duplicate questions
✅ No normalized duplicate questions
✅ No duplicates inside the same intent
✅ All 13 columns valid
✅ All required fields complete
✅ 80 Arabic
✅ 80 English
✅ 80 French
✅ 80 Russian
✅ 40 questions per intent
✅ Intent mappings correct
✅ Question types valid
✅ Ground truth complete
✅ Answers complete
✅ Language × Intent balanced

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 COMPLETE CHECK FINISHED
====================================================================================================

In [26]:
# ============================================================
# 🏨 HOTEL AI - DUPLICATE + SIMILARITY CHECK
# ============================================================
# READ-ONLY
# Checks:
# 1. Exact duplicates
# 2. Normalized duplicates
# 3. Very similar questions
# 4. Similar questions inside the SAME intent
# 5. Similar questions across DIFFERENT intents
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - DUPLICATE + SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 1. FIND DATASET
# ============================================================

possible_roots = [
    Path("/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"),
    Path.home() / "Desktop" / "HotelAI-Intelligent-Agent",
    Path.home() / "Desktop" / "HotelAI",
]

PROJECT_ROOT = next(
    (p for p in possible_roots if p.exists()),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "❌ HotelAI project root not found."
    )

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

df = pd.read_csv(DATASET_PATH)

print(f"\n📄 Dataset:\n{DATASET_PATH}")
print(f"📊 Total questions: {len(df)}")

# ============================================================
# 2. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.lower().strip()

    # Remove punctuation
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    # Normalize spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


df["_normalized"] = df["question"].apply(
    normalize_question
)

# ============================================================
# 3. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 1. EXACT DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
].copy()

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        f"🔴 Found {len(exact_duplicates)} rows "
        "in exact duplicate groups.\n"
    )

    print(
        exact_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 4. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 2. NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized"].duplicated(keep=False)
].copy()

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        f"🔴 Found {len(normalized_duplicates)} rows "
        "with normalized duplicates.\n"
    )

    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 5. SIMILARITY FUNCTION
# ============================================================

def similarity(a, b):

    return SequenceMatcher(
        None,
        normalize_question(a),
        normalize_question(b)
    ).ratio()

# ============================================================
# 6. PAIRWISE SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 3. QUESTION SIMILARITY CHECK")
print("=" * 100)

print("""
Similarity levels:

🟢 < 0.70  = Usually different
🟡 0.70–0.84 = Similar wording
🟠 0.85–0.94 = Very similar
🔴 >= 0.95 = Almost duplicate
""")

THRESHOLD = 0.85

similar_pairs = []

questions = df[
    [
        "faq_id",
        "intent_id",
        "language",
        "question"
    ]
].to_dict("records")

total_comparisons = (
    len(questions) * (len(questions) - 1) // 2
)

print(
    f"🔄 Comparing {total_comparisons:,} question pairs..."
)

for i in range(len(questions)):

    q1 = questions[i]

    for j in range(i + 1, len(questions)):

        q2 = questions[j]

        # Skip exact same normalized text
        if normalize_question(q1["question"]) == normalize_question(
            q2["question"]
        ):
            continue

        score = similarity(
            q1["question"],
            q2["question"]
        )

        if score >= THRESHOLD:

            similar_pairs.append({
                "faq_id_1": q1["faq_id"],
                "intent_1": q1["intent_id"],
                "language_1": q1["language"],
                "question_1": q1["question"],

                "faq_id_2": q2["faq_id"],
                "intent_2": q2["intent_id"],
                "language_2": q2["language"],
                "question_2": q2["question"],

                "similarity": round(score, 3)
            })

print(
    f"\n🔎 Similar pairs found: {len(similar_pairs)}"
)

# ============================================================
# 7. DISPLAY SIMILAR QUESTIONS
# ============================================================

if similar_pairs:

    similarity_df = pd.DataFrame(
        similar_pairs
    ).sort_values(
        "similarity",
        ascending=False
    )

    print("\n" + "=" * 100)
    print("📋 MOST SIMILAR QUESTIONS")
    print("=" * 100)

    pd.set_option(
        "display.max_colwidth",
        120
    )

    print(
        similarity_df[
            [
                "similarity",
                "faq_id_1",
                "intent_1",
                "question_1",
                "faq_id_2",
                "intent_2",
                "question_2"
            ]
        ].head(50).to_string(index=False)
    )

else:

    print(
        "✅ No highly similar questions found "
        f"at threshold {THRESHOLD}."
    )

# ============================================================
# 8. SAME INTENT SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🎯 4. SIMILARITY INSIDE SAME INTENT")
print("=" * 100)

same_intent_pairs = [
    x for x in similar_pairs
    if x["intent_1"] == x["intent_2"]
]

print(
    f"Same-intent similar pairs: "
    f"{len(same_intent_pairs)}"
)

if same_intent_pairs:

    same_intent_df = pd.DataFrame(
        same_intent_pairs
    ).sort_values(
        "similarity",
        ascending=False
    )

    print(
        same_intent_df[
            [
                "similarity",
                "faq_id_1",
                "intent_1",
                "question_1",
                "faq_id_2",
                "question_2"
            ]
        ].head(50).to_string(index=False)
    )

else:

    print(
        "✅ No highly similar questions "
        "inside the same intent."
    )

# ============================================================
# 9. DIFFERENT INTENT SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("⚠️ 5. SIMILARITY ACROSS DIFFERENT INTENTS")
print("=" * 100)

different_intent_pairs = [
    x for x in similar_pairs
    if x["intent_1"] != x["intent_2"]
]

print(
    f"Different-intent similar pairs: "
    f"{len(different_intent_pairs)}"
)

if different_intent_pairs:

    different_intent_df = pd.DataFrame(
        different_intent_pairs
    ).sort_values(
        "similarity",
        ascending=False
    )

    print(
        different_intent_df[
            [
                "similarity",
                "faq_id_1",
                "intent_1",
                "question_1",
                "faq_id_2",
                "intent_2",
                "question_2"
            ]
        ].head(50).to_string(index=False)
    )

else:

    print(
        "✅ No highly similar questions "
        "across different intents."
    )

# ============================================================
# 10. SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 SIMILARITY CHECK SUMMARY")
print("=" * 100)

print(
    f"""
Total questions                 : {len(df)}
Exact duplicate rows            : {len(exact_duplicates)}
Normalized duplicate rows       : {len(normalized_duplicates)}
Similarity threshold            : {THRESHOLD}
Highly similar pairs             : {len(similar_pairs)}
Same-intent similar pairs        : {len(same_intent_pairs)}
Different-intent similar pairs   : {len(different_intent_pairs)}
"""
)

# ============================================================
# 11. FINAL INTERPRETATION
# ============================================================

print("=" * 100)
print("📌 INTERPRETATION")
print("=" * 100)

if exact_duplicates.empty:
    print("✅ Exact duplicates: PASS")
else:
    print("🔴 Exact duplicates: REVIEW")

if normalized_duplicates.empty:
    print("✅ Normalized duplicates: PASS")
else:
    print("🔴 Normalized duplicates: REVIEW")

if len(same_intent_pairs) == 0:
    print("✅ Same-intent similarity: PASS")
else:
    print(
        f"🟡 Same-intent similarity: "
        f"{len(same_intent_pairs)} pairs need review"
    )

if len(different_intent_pairs) == 0:
    print("✅ Cross-intent similarity: PASS")
else:
    print(
        f"🟠 Cross-intent similarity: "
        f"{len(different_intent_pairs)} pairs need review"
    )

print("\n" + "=" * 100)
print("🔒 READ-ONLY")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 DUPLICATE + SIMILARITY CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - DUPLICATE + SIMILARITY CHECK
====================================================================================================

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Total questions: 320

====================================================================================================
📝 1. EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 2. NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 3. QUESTION SIMILARITY CHECK
====================================================================================================

Similarity levels:

🟢 < 0.70  = Usually different
🟡 0.70–0.84 = Similar wording
🟠 0.85–0.94 = Very similar
🔴 >= 0.95 = Almost duplicate

🔄 Comparing 51,040 question pairs...

🔎 Similar pairs found: 24

====================================================================================================
📋 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1                                                                                                                                  question_1 faq_id_2 intent_2                                                                                                                              question_2
      0.961  FAQ0061   INT002                                                                                                   Какая категория отеля «Nile Pearl Hotel»?  FAQ0264   INT002                                                                                                Какова категория отеля Nile Pearl Hotel?
      0.941  FAQ0270   INT004                                                                                                 What is the hotel's standard check-in time?  FAQ0274   INT005                                                                                            What is the hotel's standard check-out time?
      0.911  FAQ0272   INT004                                                                                         Какое стандартное время регистрации заезда в отеле?  FAQ0276   INT005                                                                                    Какое стандартное время регистрации выезда из отеля?
      0.896  FAQ0007   INT001 While planning my trip to Egypt, I want to make sure I can easily find the Nile Pearl Hotel. Could you tell me which city it is located in?  FAQ0008   INT001 While planning my trip to Egypt, I want to make sure I know where to find Nile Pearl Hotel. Can you tell me which city it's located in?
      0.896  FAQ0001   INT001                                                                                                          Where is Nile Pearl Hotel located?  FAQ0002   INT001                                                                                                     Where is Nile Pearl Hotel situated?
      0.894  FAQ0051   INT002                                                                                        Quelle est la catégorie d'hôtel de Nile Pearl Hotel?  FAQ0263   INT002                                                                                           Quelle est la catégorie du Nile Pearl Hotel ?
      0.889  FAQ0133   INT005                                                            What is the designated time by which I need to check out by at Nile Pearl Hotel?  FAQ0134   INT005                                                             What is the specific time by which I need to check out at Nile Pearl Hotel?
      0.884  FAQ0129   INT005                                                                   At what time must guests normally complete check-out at Nile Pearl Hotel?  FAQ0135   INT005                                                            What time do guests normally need to complete check-out at Nile Pearl Hotel?
      0.881  FAQ0019   INT001                                                                                       Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?  FAQ0021   INT001                                                                            Dans quelle ville puis-je trouver l'hôtel Nile Pearl Hotel ?
      0.881  FAQ0145   INT005                                                                                Quelle est l'heure habituelle de départ au Nile Pearl Hotel?  FAQ0275   INT005                                                                                    Quelle est l'heure habituelle de départ de l'hôtel ?
      0.879  FAQ0251   INT008                                  Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0252   INT008             Нужно ли предоставить действительный документ, удостоверяющий личность, перед регистрацией при прибытии в Nile Pearl Hotel?
      0.874  FAQ0219   INT007                                              Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, на какие условия это зависит?  FAQ0220   INT007                                                   Как можно получить поздний выезд из Nile Pearl Hotel, и на какие условия это зависит?
      0.871  FAQ0027   INT001                                                                                                      Где расположен отель Nile Pearl Hotel?  FAQ0029   INT001                                                                                       В каком городе расположен отель Nile Pearl Hotel?
      0.871  FAQ0013   INT001                                                                                                      في أي منطقة يقع فندق Nile Pearl Hotel؟  FAQ0257   INT001                                                                                       في أي منطقة من المدينة يقع فندق Nile Pearl Hotel؟
      0.870  FAQ0105   INT004                                                                                                 ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟  FAQ0141   INT005                                                                                     ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟
      0.869  FAQ0271   INT004                                                                                         Quelle est l'heure habituelle d'arrivée à l'hôtel ?  FAQ0275   INT005                                                                                    Quelle est l'heure habituelle de départ de l'hôtel ?
      0.864  FAQ0218   INT007                                                     Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?  FAQ0219   INT007                                          Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, на какие условия это зависит?
      0.864  FAQ0034   INT002                                                                                                What star rating does Nile Pearl Hotel have?  FAQ0037   INT002                                                                                                 What rating does Nile Pearl Hotel hold?
      0.862  FAQ0011   INT001                                                                                                             ما عنوان فندق Nile Pearl Hotel؟  FAQ0261   INT002                                                                                                           ما فئة فندق Nile Pearl Hotel؟
      0.860  FAQ0034   INT002                                                                                                What star rating does Nile Pearl Hotel have?  FAQ0038   INT002                                                                                     What star rating does the Nile Pearl Hotel possess?
      0.857  FAQ0053   INT002                                                                                    Quelle est la categorisation étoile du Nile Pearl Hotel?  FAQ0263   INT002                                                                                           Quelle est la catégorie du Nile Pearl Hotel ?
      0.857  FAQ0011   INT001                                                                                                             ما عنوان فندق Nile Pearl Hotel؟  FAQ0041   INT002                                                                                                      كم عدد نجوم فندق Nile Pearl Hotel؟
      0.854  FAQ0058   INT002                                                                                        Какая категория отеля является для Nile Pearl Hotel?  FAQ0061   INT002                                                                                               Какая категория отеля «Nile Pearl Hotel»?
      0.852  FAQ0043   INT002                                                                                                          ما هو تصنيف فندق Nile Pearl Hotel؟  FAQ0261   INT002                                                                                                           ما فئة فندق Nile Pearl Hotel؟

====================================================================================================
🎯 4. SIMILARITY INSIDE SAME INTENT
====================================================================================================
Same-intent similar pairs: 18
 similarity faq_id_1 intent_1                                                                                                                                  question_1 faq_id_2                                                                                                                              question_2
      0.961  FAQ0061   INT002                                                                                                   Какая категория отеля «Nile Pearl Hotel»?  FAQ0264                                                                                                Какова категория отеля Nile Pearl Hotel?
      0.896  FAQ0001   INT001                                                                                                          Where is Nile Pearl Hotel located?  FAQ0002                                                                                                     Where is Nile Pearl Hotel situated?
      0.896  FAQ0007   INT001 While planning my trip to Egypt, I want to make sure I can easily find the Nile Pearl Hotel. Could you tell me which city it is located in?  FAQ0008 While planning my trip to Egypt, I want to make sure I know where to find Nile Pearl Hotel. Can you tell me which city it's located in?
      0.894  FAQ0051   INT002                                                                                        Quelle est la catégorie d'hôtel de Nile Pearl Hotel?  FAQ0263                                                                                           Quelle est la catégorie du Nile Pearl Hotel ?
      0.889  FAQ0133   INT005                                                            What is the designated time by which I need to check out by at Nile Pearl Hotel?  FAQ0134                                                             What is the specific time by which I need to check out at Nile Pearl Hotel?
      0.884  FAQ0129   INT005                                                                   At what time must guests normally complete check-out at Nile Pearl Hotel?  FAQ0135                                                            What time do guests normally need to complete check-out at Nile Pearl Hotel?
      0.881  FAQ0145   INT005                                                                                Quelle est l'heure habituelle de départ au Nile Pearl Hotel?  FAQ0275                                                                                    Quelle est l'heure habituelle de départ de l'hôtel ?
      0.881  FAQ0019   INT001                                                                                       Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?  FAQ0021                                                                            Dans quelle ville puis-je trouver l'hôtel Nile Pearl Hotel ?
      0.879  FAQ0251   INT008                                  Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0252             Нужно ли предоставить действительный документ, удостоверяющий личность, перед регистрацией при прибытии в Nile Pearl Hotel?
      0.874  FAQ0219   INT007                                              Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, на какие условия это зависит?  FAQ0220                                                   Как можно получить поздний выезд из Nile Pearl Hotel, и на какие условия это зависит?
      0.871  FAQ0027   INT001                                                                                                      Где расположен отель Nile Pearl Hotel?  FAQ0029                                                                                       В каком городе расположен отель Nile Pearl Hotel?
      0.871  FAQ0013   INT001                                                                                                      في أي منطقة يقع فندق Nile Pearl Hotel؟  FAQ0257                                                                                       في أي منطقة من المدينة يقع فندق Nile Pearl Hotel؟
      0.864  FAQ0034   INT002                                                                                                What star rating does Nile Pearl Hotel have?  FAQ0037                                                                                                 What rating does Nile Pearl Hotel hold?
      0.864  FAQ0218   INT007                                                     Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?  FAQ0219                                          Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, на какие условия это зависит?
      0.860  FAQ0034   INT002                                                                                                What star rating does Nile Pearl Hotel have?  FAQ0038                                                                                     What star rating does the Nile Pearl Hotel possess?
      0.857  FAQ0053   INT002                                                                                    Quelle est la categorisation étoile du Nile Pearl Hotel?  FAQ0263                                                                                           Quelle est la catégorie du Nile Pearl Hotel ?
      0.854  FAQ0058   INT002                                                                                        Какая категория отеля является для Nile Pearl Hotel?  FAQ0061                                                                                               Какая категория отеля «Nile Pearl Hotel»?
      0.852  FAQ0043   INT002                                                                                                          ما هو تصنيف فندق Nile Pearl Hotel؟  FAQ0261                                                                                                           ما فئة فندق Nile Pearl Hotel؟

====================================================================================================
⚠️ 5. SIMILARITY ACROSS DIFFERENT INTENTS
====================================================================================================
Different-intent similar pairs: 6
 similarity faq_id_1 intent_1                                          question_1 faq_id_2 intent_2                                           question_2
      0.941  FAQ0270   INT004         What is the hotel's standard check-in time?  FAQ0274   INT005         What is the hotel's standard check-out time?
      0.911  FAQ0272   INT004 Какое стандартное время регистрации заезда в отеле?  FAQ0276   INT005 Какое стандартное время регистрации выезда из отеля?
      0.870  FAQ0105   INT004         ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟  FAQ0141   INT005  ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟
      0.869  FAQ0271   INT004 Quelle est l'heure habituelle d'arrivée à l'hôtel ?  FAQ0275   INT005 Quelle est l'heure habituelle de départ de l'hôtel ?
      0.862  FAQ0011   INT001                     ما عنوان فندق Nile Pearl Hotel؟  FAQ0261   INT002                        ما فئة فندق Nile Pearl Hotel؟
      0.857  FAQ0011   INT001                     ما عنوان فندق Nile Pearl Hotel؟  FAQ0041   INT002                   كم عدد نجوم فندق Nile Pearl Hotel؟

====================================================================================================
🏆 SIMILARITY CHECK SUMMARY
====================================================================================================

Total questions                 : 320
Exact duplicate rows            : 0
Normalized duplicate rows       : 0
Similarity threshold            : 0.85
Highly similar pairs             : 24
Same-intent similar pairs        : 18
Different-intent similar pairs   : 6

====================================================================================================
📌 INTERPRETATION
====================================================================================================
✅ Exact duplicates: PASS
✅ Normalized duplicates: PASS
🟡 Same-intent similarity: 18 pairs need review
🟠 Cross-intent similarity: 6 pairs need review

====================================================================================================
🔒 READ-ONLY
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 DUPLICATE + SIMILARITY CHECK COMPLETE
====================================================================================================

In [27]:
# ============================================================
# 🏨 HOTEL AI - FIX HIGH SIMILARITY QUESTIONS
# ============================================================

from pathlib import Path
from datetime import datetime
import pandas as pd
import re
import shutil

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path.home() / "Desktop" / "HotelAI-Intelligent-Agent"

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

BACKUP_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 100)
print("🏨 HOTEL AI - FIX HIGH SIMILARITY QUESTIONS")
print("=" * 100)

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

print(f"📄 Dataset found:\n{DATASET_PATH}")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(DATASET_PATH)

print(f"📊 Current rows: {len(df)}")

assert len(df) == 320, (
    f"❌ Expected 320 rows, found {len(df)}"
)

# ============================================================
# 3. BACKUP
# ============================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_similarity_fix_{timestamp}.csv"
)

shutil.copy2(DATASET_PATH, backup_path)

print(f"💾 Backup created:\n{backup_path}")

# ============================================================
# 4. QUESTIONS TO REWRITE
# ============================================================
#
# IMPORTANT:
# We only modify the questions that were identified
# as highly similar.
#
# Other columns remain untouched.
#
# ============================================================

replacements = {

    # --------------------------------------------------------
    # INT001 - Hotel Location
    # --------------------------------------------------------

    "FAQ0002": {
        "English":
        "Could you tell me which city and area Nile Pearl Hotel is in?"
    },

    "FAQ0008": {
        "English":
        "For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?"
    },

    "FAQ0021": {
        "French":
        "Dans quelle ville et dans quel secteur se situe le Nile Pearl Hotel ?"
    },

    "FAQ0029": {
        "Russian":
        "В какой части города расположен Nile Pearl Hotel?"
    },

    "FAQ0013": {
        "Arabic":
        "في أي جزء من القاهرة يقع فندق Nile Pearl Hotel؟"
    },

    "FAQ0257": {
        "Arabic":
        "إذا أردت معرفة موقع الفندق بالنسبة لمناطق القاهرة، فأين يوجد Nile Pearl Hotel؟"
    },

    # --------------------------------------------------------
    # INT002 - Hotel Category
    # --------------------------------------------------------

    "FAQ0061": {
        "Russian":
        "К какому уровню или категории относится Nile Pearl Hotel?"
    },

    "FAQ0264": {
        "Russian":
        "Сколько звёзд или какой класс имеет Nile Pearl Hotel?"
    },

    "FAQ0051": {
        "French":
        "Quel niveau de classement hôtelier est attribué au Nile Pearl Hotel ?"
    },

    "FAQ0263": {
        "French":
        "Combien d'étoiles possède le Nile Pearl Hotel ?"
    },

    "FAQ0037": {
        "English":
        "How is Nile Pearl Hotel classified within the hotel rating system?"
    },

    "FAQ0038": {
        "English":
        "What star classification is assigned to Nile Pearl Hotel?"
    },

    "FAQ0043": {
        "Arabic":
        "كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟"
    },

    "FAQ0261": {
        "Arabic":
        "كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟"
    },

    # --------------------------------------------------------
    # INT004 - Check-in
    # --------------------------------------------------------

    "FAQ0270": {
        "English":
        "From what time are guests normally allowed to enter their rooms?"
    },

    "FAQ0272": {
        "Russian":
        "С какого времени обычно разрешено заселение гостей в номер?"
    },

    # --------------------------------------------------------
    # INT005 - Check-out
    # --------------------------------------------------------

    "FAQ0274": {
        "English":
        "By what time do guests normally need to vacate their rooms?"
    },

    "FAQ0276": {
        "Russian":
        "До какого времени гости обычно должны освободить номер?"
    },

    "FAQ0134": {
        "English":
        "When is the latest standard time for completing the check-out process?"
    },

    "FAQ0135": {
        "English":
        "What is the usual deadline for guests to leave their rooms?"
    },

    "FAQ0145": {
        "French":
        "Quand les clients doivent-ils généralement quitter leur chambre ?"
    },

    "FAQ0275": {
        "French":
        "À quel moment la chambre doit-elle être libérée lors du départ ?"
    },

    # --------------------------------------------------------
    # INT007 - Late check-out
    # --------------------------------------------------------

    "FAQ0220": {
        "Russian":
        "Quelles démarches faut-il suivre pour demander un départ tardif ?"
    },

    "FAQ0219": {
        "Russian":
        "Dans quelles situations un départ après l'heure normale peut-il être accordé ?"
    },

    # --------------------------------------------------------
    # INT008 - Identification
    # --------------------------------------------------------

    "FAQ0252": {
        "Russian":
        "Какое удостоверение личности принимается от гостя при заселении?"
    },
}

# ============================================================
# 5. APPLY REPLACEMENTS
# ============================================================

modified_ids = []

for faq_id, language_data in replacements.items():

    matches = df.index[df["faq_id"] == faq_id].tolist()

    if len(matches) != 1:
        print(
            f"⚠️ {faq_id}: expected 1 row, found {len(matches)}"
        )
        continue

    idx = matches[0]

    new_question = list(language_data.values())[0]

    old_question = df.at[idx, "question"]

    df.at[idx, "question"] = new_question

    modified_ids.append(faq_id)

    print(f"\n🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")

# ============================================================
# 6. BASIC VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 BASIC VALIDATION")
print("=" * 100)

assert len(df) == 320

assert df["faq_id"].is_unique

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

for col in required_columns:
    missing = df[col].isna().sum()

    empty = (
        df[col]
        .astype(str)
        .str.strip()
        .isin(["", "nan", "None"])
        .sum()
    )

    assert missing == 0, f"❌ Missing values in {col}"
    assert empty == 0, f"❌ Empty values in {col}"

print("✅ All required fields complete.")

# ============================================================
# 7. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = str(text).lower()

    text = re.sub(r"\s+", " ", text)

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(r"\s+", " ", text)

    return text.strip()


df["_normalized_question"] = (
    df["question"]
    .map(normalize_question)
)

# ============================================================
# 8. EXACT DUPLICATES
# ============================================================

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

print("\n📝 EXACT DUPLICATES")

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(exact_duplicates[
        ["faq_id", "intent_id", "question"]
    ])

# ============================================================
# 9. NORMALIZED DUPLICATES
# ============================================================

normalized_duplicates = df[
    df["_normalized_question"].duplicated(keep=False)
]

print("\n🔎 NORMALIZED DUPLICATES")

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(normalized_duplicates[
        ["faq_id", "intent_id", "question"]
    ])

# ============================================================
# 10. SAVE
# ============================================================

df = df.drop(columns=["_normalized_question"])

df.to_csv(
    DATASET_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 DATASET SAVED")
print("=" * 100)

print(f"Modified questions: {len(modified_ids)}")
print(f"Dataset rows      : {len(df)}")
print(f"Dataset path      : {DATASET_PATH}")

# ============================================================
# 11. FINAL CHECK
# ============================================================

check_df = pd.read_csv(DATASET_PATH)

assert len(check_df) == 320
assert check_df["faq_id"].is_unique

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

assert check_df["faq_id"].tolist() == expected_ids

print("\n" + "=" * 100)
print("🏆 FINAL RESULT")
print("=" * 100)

print("🟢 SIMILARITY FIX COMPLETED")

print("✅ 320 questions preserved")
print("✅ FAQ0001 → FAQ0320")
print("✅ No rows added")
print("✅ No rows deleted")
print("✅ IDs preserved")
print("✅ Backup created")
print("✅ Only selected similar questions were rewritten")

print("\n🔒 Backup:")
print(backup_path)

print("\n🎉 READY FOR A NEW SIMILARITY CHECK")

====================================================================================================
🏨 HOTEL AI - FIX HIGH SIMILARITY QUESTIONS
====================================================================================================
📄 Dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Current rows: 320
💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_similarity_fix_20260821_145409.csv

🔄 FAQ0002
OLD: Where is Nile Pearl Hotel situated?
NEW: Could you tell me which city and area Nile Pearl Hotel is in?

🔄 FAQ0008
OLD: While planning my trip to Egypt, I want to make sure I know where to find Nile Pearl Hotel. Can you tell me which city it's located in?
NEW: For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?

🔄 FAQ0021
OLD: Dans quelle ville puis-je trouver l'hôtel Nile Pearl Hotel ?
NEW: Dans quelle ville et dans quel secteur se situe le Nile Pearl Hotel ?

🔄 FAQ0029
OLD: В каком городе расположен отель Nile Pearl Hotel?
NEW: В какой части города расположен Nile Pearl Hotel?

🔄 FAQ0013
OLD: في أي منطقة يقع فندق Nile Pearl Hotel؟
NEW: في أي جزء من القاهرة يقع فندق Nile Pearl Hotel؟

🔄 FAQ0257
OLD: في أي منطقة من المدينة يقع فندق Nile Pearl Hotel؟
NEW: إذا أردت معرفة موقع الفندق بالنسبة لمناطق القاهرة، فأين يوجد Nile Pearl Hotel؟

🔄 FAQ0061
OLD: Какая категория отеля «Nile Pearl Hotel»?
NEW: К какому уровню или категории относится Nile Pearl Hotel?

🔄 FAQ0264
OLD: Какова категория отеля Nile Pearl Hotel?
NEW: Сколько звёзд или какой класс имеет Nile Pearl Hotel?

🔄 FAQ0051
OLD: Quelle est la catégorie d'hôtel de Nile Pearl Hotel?
NEW: Quel niveau de classement hôtelier est attribué au Nile Pearl Hotel ?

🔄 FAQ0263
OLD: Quelle est la catégorie du Nile Pearl Hotel ?
NEW: Combien d'étoiles possède le Nile Pearl Hotel ?

🔄 FAQ0037
OLD: What rating does Nile Pearl Hotel hold?
NEW: How is Nile Pearl Hotel classified within the hotel rating system?

🔄 FAQ0038
OLD: What star rating does the Nile Pearl Hotel possess?
NEW: What star classification is assigned to Nile Pearl Hotel?

🔄 FAQ0043
OLD: ما هو تصنيف فندق Nile Pearl Hotel؟
NEW: كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟

🔄 FAQ0261
OLD: ما فئة فندق Nile Pearl Hotel؟
NEW: كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟

🔄 FAQ0270
OLD: What is the hotel's standard check-in time?
NEW: From what time are guests normally allowed to enter their rooms?

🔄 FAQ0272
OLD: Какое стандартное время регистрации заезда в отеле?
NEW: С какого времени обычно разрешено заселение гостей в номер?

🔄 FAQ0274
OLD: What is the hotel's standard check-out time?
NEW: By what time do guests normally need to vacate their rooms?

🔄 FAQ0276
OLD: Какое стандартное время регистрации выезда из отеля?
NEW: До какого времени гости обычно должны освободить номер?

🔄 FAQ0134
OLD: What is the specific time by which I need to check out at Nile Pearl Hotel?
NEW: When is the latest standard time for completing the check-out process?

🔄 FAQ0135
OLD: What time do guests normally need to complete check-out at Nile Pearl Hotel?
NEW: What is the usual deadline for guests to leave their rooms?

🔄 FAQ0145
OLD: Quelle est l'heure habituelle de départ au Nile Pearl Hotel?
NEW: Quand les clients doivent-ils généralement quitter leur chambre ?

🔄 FAQ0275
OLD: Quelle est l'heure habituelle de départ de l'hôtel ?
NEW: À quel moment la chambre doit-elle être libérée lors du départ ?

🔄 FAQ0220
OLD: Как можно получить поздний выезд из Nile Pearl Hotel, и на какие условия это зависит?
NEW: Quelles démarches faut-il suivre pour demander un départ tardif ?

🔄 FAQ0219
OLD: Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, на какие условия это зависит?
NEW: Dans quelles situations un départ après l'heure normale peut-il être accordé ?

🔄 FAQ0252
OLD: Нужно ли предоставить действительный документ, удостоверяющий личность, перед регистрацией при прибытии в Nile Pearl Hotel?
NEW: Какое удостоверение личности принимается от гостя при заселении?

====================================================================================================
🧪 BASIC VALIDATION
====================================================================================================
✅ All required fields complete.

📝 EXACT DUPLICATES
✅ No exact duplicate questions.

🔎 NORMALIZED DUPLICATES
✅ No normalized duplicate questions.

====================================================================================================
💾 DATASET SAVED
====================================================================================================
Modified questions: 25
Dataset rows      : 320
Dataset path      : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 FINAL RESULT
====================================================================================================
🟢 SIMILARITY FIX COMPLETED
✅ 320 questions preserved
✅ FAQ0001 → FAQ0320
✅ No rows added
✅ No rows deleted
✅ IDs preserved
✅ Backup created
✅ Only selected similar questions were rewritten

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_similarity_fix_20260821_145409.csv

🎉 READY FOR A NEW SIMILARITY CHECK

In [28]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE DATASET + SIMILARITY QUALITY CHECK
# READ-ONLY — DOES NOT MODIFY THE DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import re
from difflib import SequenceMatcher
from itertools import combinations

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path.home() / "Desktop" / "HotelAI-Intelligent-Agent"

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE DATASET QUALITY + SIMILARITY CHECK")
print("=" * 100)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"❌ Project root not found:\n{PROJECT_ROOT}"
    )

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"❌ Dataset not found:\n{DATASET_PATH}"
    )

print(f"📂 Project root:\n{PROJECT_ROOT}")
print(f"\n📄 Dataset:\n{DATASET_PATH}")

# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

required_columns = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

print("✅ All 13 required columns exist.")

assert df.columns.tolist() == required_columns, (
    "❌ Column order is incorrect."
)

print("✅ Column order is correct.")

# ============================================================
# 4. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

assert len(df) == 320, (
    f"❌ Expected 320 rows, found {len(df)}"
)

print("✅ Dataset contains exactly 320 questions.")

# ============================================================
# 5. FAQ ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

id_pattern = r"^FAQ\d{4}$"

invalid_ids = df[
    ~df["faq_id"]
    .astype(str)
    .str.match(id_pattern)
]

assert invalid_ids.empty, (
    f"❌ Invalid FAQ IDs:\n"
    f"{invalid_ids[['faq_id']]}"
)

print("✅ All FAQ IDs have valid format.")

assert df["faq_id"].is_unique

print("✅ No duplicate FAQ IDs.")

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

actual_ids = df["faq_id"].tolist()

assert actual_ids == expected_ids, (
    "❌ FAQ IDs are not continuous or correctly ordered."
)

print("✅ IDs are continuous and correctly ordered:")
print("   FAQ0001 → FAQ0320")

# ============================================================
# 6. REQUIRED FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in required_columns:

    missing = df[col].isna().sum()

    empty = (
        df[col]
        .astype(str)
        .str.strip()
        .isin(["", "nan", "None"])
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    assert missing == 0, (
        f"❌ Missing values in {col}"
    )

    assert empty == 0, (
        f"❌ Empty values in {col}"
    )

print("\n✅ All required fields are complete.")

# ============================================================
# 7. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = str(text).lower()

    # Remove punctuation while preserving Unicode letters
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


df["_normalized_question"] = (
    df["question"]
    .map(normalize_question)
)

# ============================================================
# 8. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Exact duplicate questions found."
    )

# ============================================================
# 9. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized_question"]
    .duplicated(keep=False)
]

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Normalized duplicate questions found."
    )

# ============================================================
# 10. INTENT ↔ INTENT NAME
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_mapping = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for intent_id, expected_name in intent_mapping.items():

    rows = df[df["intent_id"] == intent_id]

    assert not rows.empty

    actual_names = rows["intent_name"].unique().tolist()

    assert actual_names == [expected_name], (
        f"❌ {intent_id} mapping incorrect: "
        f"{actual_names}"
    )

print("✅ All intent mappings are correct.")

# ============================================================
# 11. LANGUAGE DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts)

expected_languages = {
    "Arabic": 80,
    "English": 80,
    "French": 80,
    "Russian": 80,
}

assert language_counts.to_dict() == expected_languages

print("✅ 80 questions × 4 languages.")

# ============================================================
# 12. INTENT DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
)

print(intent_counts.to_string(index=False))

assert len(intent_counts) == 8

assert all(
    intent_counts["questions"] == 40
)

print("✅ 40 questions × 8 intents.")

# ============================================================
# 13. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(language_intent)

assert set(language_intent.columns) == {
    "Arabic",
    "English",
    "French",
    "Russian",
}

assert (
    language_intent
    .values
    == 10
).all()

print(
    "✅ Every intent has 10 questions "
    "in every language."
)

# ============================================================
# 14. QUESTION TYPE
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE")
print("=" * 100)

valid_question_types = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = set(
    df["question_type"].unique()
) - valid_question_types

assert not invalid_types, (
    f"❌ Invalid question types: {invalid_types}"
)

print(df["question_type"].value_counts())

print("✅ All question types are valid.")

# ============================================================
# 15. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS")
print("=" * 100)

print(df["status"].value_counts())

print("✅ Status field complete.")

# ============================================================
# 16. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY")
print("=" * 100)

print(df["difficulty"].value_counts())

print("✅ Difficulty field complete.")

# ============================================================
# 17. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 18. DUPLICATES INSIDE SAME INTENT
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

same_intent_duplicates = (
    df[
        df.duplicated(
            subset=[
                "intent_id",
                "_normalized_question"
            ],
            keep=False
        )
    ]
)

if same_intent_duplicates.empty:

    print(
        "✅ No normalized duplicates "
        "inside the same intent."
    )

else:

    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "question"
            ]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Duplicate questions found "
        "inside the same intent."
    )

# ============================================================
# 19. SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔎 QUESTION SIMILARITY CHECK")
print("=" * 100)

print("Comparing 51,040 question pairs...")

questions = df["question"].astype(str).tolist()
faq_ids = df["faq_id"].tolist()
intent_ids = df["intent_id"].tolist()

similar_pairs = []

for i, j in combinations(range(len(questions)), 2):

    q1 = questions[i]
    q2 = questions[j]

    similarity = SequenceMatcher(
        None,
        q1.lower(),
        q2.lower()
    ).ratio()

    if similarity >= 0.85:

        similar_pairs.append({
            "similarity": round(similarity, 3),
            "faq_id_1": faq_ids[i],
            "intent_1": intent_ids[i],
            "question_1": q1,
            "faq_id_2": faq_ids[j],
            "intent_2": intent_ids[j],
            "question_2": q2,
        })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No highly similar questions found.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"🔎 Highly similar pairs found: "
        f"{len(similarity_df)}"
    )

    print("\n" + "=" * 100)
    print("📋 TOP SIMILAR QUESTIONS")
    print("=" * 100)

    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 20. SAME-INTENT SIMILARITY
# ============================================================

if not similarity_df.empty:

    same_intent_similarity = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

else:

    same_intent_similarity = pd.DataFrame()

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Same-intent similar pairs: "
    f"{len(same_intent_similarity)}"
)

if not same_intent_similarity.empty:

    print(
        same_intent_similarity.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 21. DIFFERENT-INTENT SIMILARITY
# ============================================================

if not similarity_df.empty:

    different_intent_similarity = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

else:

    different_intent_similarity = pd.DataFrame()

print("\n" + "=" * 100)
print("⚠️ DIFFERENT-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Different-intent similar pairs: "
    f"{len(different_intent_similarity)}"
)

if not different_intent_similarity.empty:

    print(
        different_intent_similarity.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 22. SIMILARITY SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 SIMILARITY SUMMARY")
print("=" * 100)

print(f"Total questions              : {len(df)}")
print(f"Exact duplicates             : {len(exact_duplicates)}")
print(f"Normalized duplicates       : {len(normalized_duplicates)}")
print(
    f"Similarity threshold        : 0.85"
)
print(
    f"Highly similar pairs        : "
    f"{len(similarity_df)}"
)
print(
    f"Same-intent similar pairs   : "
    f"{len(same_intent_similarity)}"
)
print(
    f"Different-intent pairs      : "
    f"{len(different_intent_similarity)}"
)

# ============================================================
# 23. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏁 FINAL DATASET CHECK RESULT")
print("=" * 100)

print("🟢 STRUCTURAL DATASET CHECK: PASS")
print("🟢 DUPLICATE CHECK: PASS")

if len(similarity_df) == 0:

    print(
        "🟢 SIMILARITY CHECK: PASS"
    )

else:

    print(
        "🟡 SIMILARITY CHECK: REVIEW REQUIRED"
    )

    print(
        f"   {len(similarity_df)} pairs "
        f"have similarity >= 0.85."
    )

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 24. REMOVE TEMP COLUMN
# ============================================================

df.drop(
    columns=["_normalized_question"],
    inplace=True
)

print("\n" + "=" * 100)
print("🎉 COMPLETE CHECK FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE DATASET QUALITY + SIMILARITY CHECK
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 320
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
✅ Dataset contains exactly 320 questions.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ IDs are continuous and correctly ordered:
   FAQ0001 → FAQ0320

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0

✅ All required fields are complete.

====================================================================================================
📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ All intent mappings are correct.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    80
Arabic     80
French     80
Russian    80
Name: count, dtype: int64
✅ 80 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         40
   INT002          hotel_category         40
   INT003  reception_availability         40
   INT004           check_in_time         40
   INT005          check_out_time         40
   INT006          early_check_in         40
   INT007          late_check_out         40
   INT008 identification_required         40
✅ 40 questions × 8 intents.

====================================================================================================
📊 LANGUAGE × INTENT
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         10       10      10       10
INT002         10       10      10       10
INT003         10       10      10       10
INT004         10       10      10       10
INT005         10       10      10       10
INT006         10       10      10       10
INT007         10       10      10       10
INT008         10       10      10       10
✅ Every intent has 10 questions in every language.

====================================================================================================
📝 QUESTION TYPE
====================================================================================================
question_type
Paraphrased    128
Direct         108
Scenario        84
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📌 STATUS
====================================================================================================
status
valid        224
generated     96
Name: count, dtype: int64
✅ Status field complete.

====================================================================================================
📌 DIFFICULTY
====================================================================================================
difficulty
Easy    320
Name: count, dtype: int64
✅ Difficulty field complete.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🔎 QUESTION SIMILARITY CHECK
====================================================================================================
Comparing 51,040 question pairs...
🔎 Highly similar pairs found: 2

====================================================================================================
📋 TOP SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1                                  question_1 faq_id_2 intent_2                                          question_2
      0.872  FAQ0105   INT004 ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟  FAQ0141   INT005 ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟
      0.862  FAQ0011   INT001             ما عنوان فندق Nile Pearl Hotel؟  FAQ0041   INT002                  كم عدد نجوم فندق Nile Pearl Hotel؟

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent similar pairs: 0

====================================================================================================
⚠️ DIFFERENT-INTENT SIMILARITY
====================================================================================================
Different-intent similar pairs: 2
 similarity faq_id_1 intent_1                                  question_1 faq_id_2 intent_2                                          question_2
      0.872  FAQ0105   INT004 ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟  FAQ0141   INT005 ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟
      0.862  FAQ0011   INT001             ما عنوان فندق Nile Pearl Hotel؟  FAQ0041   INT002                  كم عدد نجوم فندق Nile Pearl Hotel؟

====================================================================================================
🏆 SIMILARITY SUMMARY
====================================================================================================
Total questions              : 320
Exact duplicates             : 0
Normalized duplicates       : 0
Similarity threshold        : 0.85
Highly similar pairs        : 2
Same-intent similar pairs   : 0
Different-intent pairs      : 2

====================================================================================================
🏁 FINAL DATASET CHECK RESULT
====================================================================================================
🟢 STRUCTURAL DATASET CHECK: PASS
🟢 DUPLICATE CHECK: PASS
🟡 SIMILARITY CHECK: REVIEW REQUIRED
   2 pairs have similarity >= 0.85.

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 COMPLETE CHECK FINISHED
====================================================================================================

In [29]:
import pandas as pd
import os
import re
from datetime import datetime
from difflib import SequenceMatcher

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"

DATASET_PATH = os.path.join(
    PROJECT_ROOT,
    "03_Structured_Data",
    "CSV",
    "final",
    "hotel_faq_final.csv"
)

BACKUP_DIR = os.path.join(
    PROJECT_ROOT,
    "03_Structured_Data",
    "CSV",
    "final",
    "backups"
)

os.makedirs(BACKUP_DIR, exist_ok=True)

print("=" * 100)
print("🏨 HOTEL AI - FIX FINAL CROSS-INTENT SIMILARITY")
print("=" * 100)

# ============================================================
# LOAD
# ============================================================

assert os.path.exists(DATASET_PATH), "❌ Dataset not found."

df = pd.read_csv(DATASET_PATH)

print(f"📊 Rows before: {len(df)}")

# ============================================================
# BACKUP
# ============================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

backup_path = os.path.join(
    BACKUP_DIR,
    f"hotel_faq_before_final_similarity_fix_{timestamp}.csv"
)

df.to_csv(backup_path, index=False)

print(f"💾 Backup created:")
print(backup_path)

# ============================================================
# ORIGINAL VALUES
# ============================================================

original_questions = {
    "FAQ0105": "ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟",
    "FAQ0141": "ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟",
    "FAQ0011": "ما عنوان فندق Nile Pearl Hotel؟",
    "FAQ0041": "كم عدد نجوم فندق Nile Pearl Hotel؟",
}

# ============================================================
# NEW QUESTIONS
# ============================================================

new_questions = {

    # INT004 - Check-in
    "FAQ0105":
        "عند الوصول إلى Nile Pearl Hotel، متى يُسمح للضيف ببدء إجراءات تسجيل الوصول؟",

    # INT005 - Check-out
    "FAQ0141":
        "عند انتهاء الإقامة في Nile Pearl Hotel، ما الموعد النهائي لمغادرة الغرفة؟",

    # INT001 - Hotel location/address
    "FAQ0011":
        "ما الموقع أو العنوان الذي يمكنني استخدامه للوصول إلى Nile Pearl Hotel؟",

    # INT002 - Hotel category/stars
    "FAQ0041":
        "كم نجمة مُصنَّف بها Nile Pearl Hotel؟",
}

# ============================================================
# VALIDATE IDs
# ============================================================

target_ids = list(new_questions.keys())

assert df["faq_id"].isin(target_ids).sum() == 4, \
    "❌ One or more target FAQ IDs were not found."

# ============================================================
# APPLY CHANGES
# ============================================================

print()
print("=" * 100)
print("🔄 APPLYING QUESTION CHANGES")
print("=" * 100)

for faq_id, new_question in new_questions.items():

    idx = df.index[df["faq_id"] == faq_id][0]

    old_question = df.at[idx, "question"]

    print()
    print(f"🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")

    df.at[idx, "question"] = new_question

# ============================================================
# BASIC STRUCTURE CHECK
# ============================================================

print()
print("=" * 100)
print("🧪 BASIC VALIDATION")
print("=" * 100)

assert len(df) == 320, \
    "❌ Row count changed."

assert df["faq_id"].nunique() == 320, \
    "❌ FAQ IDs are no longer unique."

assert df["question"].notna().all(), \
    "❌ Missing questions found."

assert df["question"].astype(str).str.strip().ne("").all(), \
    "❌ Empty questions found."

print("✅ Row count preserved: 320")
print("✅ FAQ IDs preserved.")
print("✅ No missing questions.")
print("✅ No empty questions.")

# ============================================================
# EXACT DUPLICATES
# ============================================================

print()
print("=" * 100)
print("📝 EXACT DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print("❌ Exact duplicates found:")
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "question"]
        ].to_string(index=False)
    )
    raise AssertionError("Exact duplicates detected.")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):
    text = str(text).lower().strip()

    text = re.sub(r"\s+", " ", text)

    text = re.sub(r"[؟?!.,;:،؛\"'«»()\-]", "", text)

    return text

df["_normalized"] = df["question"].apply(normalize)

# ============================================================
# NORMALIZED DUPLICATES
# ============================================================

print()
print("=" * 100)
print("🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized"].duplicated(keep=False)
]

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print("❌ Normalized duplicates found:")
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "question"]
        ].sort_values("_normalized").to_string(index=False)
    )
    raise AssertionError("Normalized duplicates detected.")

# ============================================================
# SIMILARITY CHECK
# ============================================================

print()
print("=" * 100)
print("🔍 QUESTION SIMILARITY CHECK")
print("=" * 100)

questions = df[
    ["faq_id", "intent_id", "question"]
].to_dict("records")

similar_pairs = []

for i in range(len(questions)):
    for j in range(i + 1, len(questions)):

        q1 = questions[i]
        q2 = questions[j]

        score = SequenceMatcher(
            None,
            normalize(q1["question"]),
            normalize(q2["question"])
        ).ratio()

        if score >= 0.85:

            similar_pairs.append({
                "similarity": round(score, 3),
                "faq_id_1": q1["faq_id"],
                "intent_1": q1["intent_id"],
                "question_1": q1["question"],
                "faq_id_2": q2["faq_id"],
                "intent_2": q2["intent_id"],
                "question_2": q2["question"],
            })

similar_df = pd.DataFrame(similar_pairs)

if similar_df.empty:

    print("🎉 No highly similar questions found.")
    print("✅ Similarity < 0.85 for all question pairs.")

else:

    similar_df = similar_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"⚠️ Highly similar pairs remaining: "
        f"{len(similar_df)}"
    )

    print()
    print(similar_df.to_string(index=False))

# ============================================================
# SAME INTENT SIMILARITY
# ============================================================

print()
print("=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

same_intent = []

if not similar_df.empty:

    for _, row in similar_df.iterrows():

        if row["intent_1"] == row["intent_2"]:
            same_intent.append(row)

if not same_intent:

    print("✅ No highly similar questions inside the same intent.")

else:

    same_intent_df = pd.DataFrame(same_intent)

    print(
        f"⚠️ Same-intent similar pairs: "
        f"{len(same_intent_df)}"
    )

    print(
        same_intent_df.to_string(index=False)
    )

# ============================================================
# DIFFERENT INTENT SIMILARITY
# ============================================================

print()
print("=" * 100)
print("⚠️ DIFFERENT-INTENT SIMILARITY")
print("=" * 100)

different_intent = []

if not similar_df.empty:

    for _, row in similar_df.iterrows():

        if row["intent_1"] != row["intent_2"]:
            different_intent.append(row)

if not different_intent:

    print("✅ No highly similar questions across different intents.")

else:

    different_intent_df = pd.DataFrame(
        different_intent
    )

    print(
        f"⚠️ Different-intent similar pairs: "
        f"{len(different_intent_df)}"
    )

    print(
        different_intent_df.to_string(index=False)
    )

# ============================================================
# REMOVE TEMP COLUMN
# ============================================================

df.drop(columns=["_normalized"], inplace=True)

# ============================================================
# FINAL SAFETY CHECK
# ============================================================

assert len(df) == 320
assert df["faq_id"].tolist() == [
    f"FAQ{i:04d}" for i in range(1, 321)
]

# ============================================================
# SAVE
# ============================================================

df.to_csv(DATASET_PATH, index=False)

print()
print("=" * 100)
print("💾 DATASET SAVED")
print("=" * 100)

print(DATASET_PATH)

# ============================================================
# FINAL RESULT
# ============================================================

print()
print("=" * 100)
print("🏆 FINAL RESULT")
print("=" * 100)

print("🟢 FINAL SIMILARITY FIX COMPLETED")
print()
print("✅ 320 questions preserved")
print("✅ FAQ0001 → FAQ0320")
print("✅ No rows added")
print("✅ No rows deleted")
print("✅ FAQ IDs preserved")
print("✅ Backup created")
print("✅ Only 4 selected questions modified")
print("✅ No exact duplicates")
print("✅ No normalized duplicates")

if similar_df.empty:
    print("✅ No similarity >= 0.85")
else:
    print(
        f"⚠️ Similarity pairs >= 0.85 remaining: "
        f"{len(similar_df)}"
    )

print()
print("🔒 Backup:")
print(backup_path)

print("=" * 100)
print("🎉 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FIX FINAL CROSS-INTENT SIMILARITY
====================================================================================================
📊 Rows before: 320
💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_final_similarity_fix_20260821_145722.csv

====================================================================================================
🔄 APPLYING QUESTION CHANGES
====================================================================================================

🔄 FAQ0105
OLD: ما هو وقت تسجيل الوصول في Nile Pearl Hotel؟
NEW: عند الوصول إلى Nile Pearl Hotel، متى يُسمح للضيف ببدء إجراءات تسجيل الوصول؟

🔄 FAQ0141
OLD: ما هو وقت تسجيل الخروج المعتاد في Nile Pearl Hotel؟
NEW: عند انتهاء الإقامة في Nile Pearl Hotel، ما الموعد النهائي لمغادرة الغرفة؟

🔄 FAQ0011
OLD: ما عنوان فندق Nile Pearl Hotel؟
NEW: ما الموقع أو العنوان الذي يمكنني استخدامه للوصول إلى Nile Pearl Hotel؟

🔄 FAQ0041
OLD: كم عدد نجوم فندق Nile Pearl Hotel؟
NEW: كم نجمة مُصنَّف بها Nile Pearl Hotel؟

====================================================================================================
🧪 BASIC VALIDATION
====================================================================================================
✅ Row count preserved: 320
✅ FAQ IDs preserved.
✅ No missing questions.
✅ No empty questions.

====================================================================================================
📝 EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 QUESTION SIMILARITY CHECK
====================================================================================================
⚠️ Highly similar pairs remaining: 1

 similarity faq_id_1 intent_1                                    question_1 faq_id_2 intent_2                                      question_2
      0.851  FAQ0050   INT002 Combien d'étoiles a l'hôtel Nile Pearl Hotel?  FAQ0263   INT002 Combien d'étoiles possède le Nile Pearl Hotel ?

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
⚠️ Same-intent similar pairs: 1
 similarity faq_id_1 intent_1                                    question_1 faq_id_2 intent_2                                      question_2
      0.851  FAQ0050   INT002 Combien d'étoiles a l'hôtel Nile Pearl Hotel?  FAQ0263   INT002 Combien d'étoiles possède le Nile Pearl Hotel ?

====================================================================================================
⚠️ DIFFERENT-INTENT SIMILARITY
====================================================================================================
✅ No highly similar questions across different intents.

====================================================================================================
💾 DATASET SAVED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 FINAL RESULT
====================================================================================================
🟢 FINAL SIMILARITY FIX COMPLETED

✅ 320 questions preserved
✅ FAQ0001 → FAQ0320
✅ No rows added
✅ No rows deleted
✅ FAQ IDs preserved
✅ Backup created
✅ Only 4 selected questions modified
✅ No exact duplicates
✅ No normalized duplicates
⚠️ Similarity pairs >= 0.85 remaining: 1

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_final_similarity_fix_20260821_145722.csv
====================================================================================================
🎉 CHECK COMPLETE
====================================================================================================

In [30]:
import pandas as pd
import os
import re
from datetime import datetime
from difflib import SequenceMatcher

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"

DATASET_PATH = os.path.join(
    PROJECT_ROOT,
    "03_Structured_Data",
    "CSV",
    "final",
    "hotel_faq_final.csv"
)

BACKUP_DIR = os.path.join(
    PROJECT_ROOT,
    "03_Structured_Data",
    "CSV",
    "final",
    "backups"
)

os.makedirs(BACKUP_DIR, exist_ok=True)

print("=" * 100)
print("🏨 HOTEL AI - FINAL FAQ0263 SIMILARITY FIX")
print("=" * 100)

# ============================================================
# LOAD DATASET
# ============================================================

assert os.path.exists(DATASET_PATH), "❌ Dataset not found."

df = pd.read_csv(DATASET_PATH)

print(f"📊 Rows before: {len(df)}")

assert len(df) == 320, "❌ Dataset must contain exactly 320 rows."

# ============================================================
# BACKUP
# ============================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

backup_path = os.path.join(
    BACKUP_DIR,
    f"hotel_faq_before_faq0263_fix_{timestamp}.csv"
)

df.to_csv(backup_path, index=False)

print("💾 Backup created:")
print(backup_path)

# ============================================================
# FIND FAQ0263
# ============================================================

target_id = "FAQ0263"

idx_list = df.index[df["faq_id"] == target_id].tolist()

assert len(idx_list) == 1, \
    "❌ FAQ0263 was not found exactly once."

idx = idx_list[0]

old_question = df.at[idx, "question"]

# ============================================================
# NEW QUESTION
# ============================================================

new_question = (
    "À quelle catégorie hôtelière appartient le Nile Pearl Hotel ?"
)

print()
print("=" * 100)
print("🔄 MODIFYING FAQ0263")
print("=" * 100)

print(f"OLD: {old_question}")
print(f"NEW: {new_question}")

df.at[idx, "question"] = new_question

# ============================================================
# BASIC VALIDATION
# ============================================================

print()
print("=" * 100)
print("🧪 BASIC VALIDATION")
print("=" * 100)

assert len(df) == 320

assert df["faq_id"].nunique() == 320

assert df["question"].notna().all()

assert df["question"].astype(str).str.strip().ne("").all()

print("✅ Row count preserved: 320")
print("✅ FAQ IDs remain unique.")
print("✅ No missing questions.")
print("✅ No empty questions.")

# ============================================================
# EXACT DUPLICATES
# ============================================================

print()
print("=" * 100)
print("📝 EXACT DUPLICATE CHECK")
print("=" * 100)

exact_dupes = df[
    df["question"].duplicated(keep=False)
]

assert exact_dupes.empty, \
    "❌ Exact duplicate questions found."

print("✅ No exact duplicate questions.")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(
        r"[؟?!.,;:،؛\"'«»()\-]",
        "",
        text
    )
    return text

df["_normalized"] = df["question"].apply(normalize)

# ============================================================
# NORMALIZED DUPLICATES
# ============================================================

print()
print("=" * 100)
print("🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_dupes = df[
    df["_normalized"].duplicated(keep=False)
]

assert normalized_dupes.empty, \
    "❌ Normalized duplicate questions found."

print("✅ No normalized duplicate questions.")

# ============================================================
# SIMILARITY CHECK
# ============================================================

print()
print("=" * 100)
print("🔍 FULL QUESTION SIMILARITY CHECK")
print("=" * 100)

questions = df[
    ["faq_id", "intent_id", "question"]
].to_dict("records")

similar_pairs = []

for i in range(len(questions)):

    for j in range(i + 1, len(questions)):

        q1 = questions[i]
        q2 = questions[j]

        score = SequenceMatcher(
            None,
            normalize(q1["question"]),
            normalize(q2["question"])
        ).ratio()

        if score >= 0.85:

            similar_pairs.append({
                "similarity": round(score, 3),
                "faq_id_1": q1["faq_id"],
                "intent_1": q1["intent_id"],
                "question_1": q1["question"],
                "faq_id_2": q2["faq_id"],
                "intent_2": q2["intent_id"],
                "question_2": q2["question"],
            })

similar_df = pd.DataFrame(similar_pairs)

if similar_df.empty:

    print("🎉 No highly similar pairs found.")
    print("✅ All question pairs have similarity < 0.85.")

else:

    similar_df = similar_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"⚠️ Highly similar pairs remaining: "
        f"{len(similar_df)}"
    )

    print()
    print(similar_df.to_string(index=False))

# ============================================================
# SAME INTENT CHECK
# ============================================================

print()
print("=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similar_df.empty:

    same_intent_df = pd.DataFrame()

else:

    same_intent_df = similar_df[
        similar_df["intent_1"] ==
        similar_df["intent_2"]
    ]

if same_intent_df.empty:

    print("✅ No highly similar questions inside the same intent.")

else:

    print(
        f"⚠️ Same-intent similar pairs: "
        f"{len(same_intent_df)}"
    )

    print(
        same_intent_df.to_string(index=False)
    )

# ============================================================
# DIFFERENT INTENT CHECK
# ============================================================

print()
print("=" * 100)
print("⚠️ DIFFERENT-INTENT SIMILARITY")
print("=" * 100)

if similar_df.empty:

    different_intent_df = pd.DataFrame()

else:

    different_intent_df = similar_df[
        similar_df["intent_1"] !=
        similar_df["intent_2"]
    ]

if different_intent_df.empty:

    print("✅ No highly similar questions across different intents.")

else:

    print(
        f"⚠️ Different-intent similar pairs: "
        f"{len(different_intent_df)}"
    )

    print(
        different_intent_df.to_string(index=False)
    )

# ============================================================
# REMOVE TEMP COLUMN
# ============================================================

df.drop(columns=["_normalized"], inplace=True)

# ============================================================
# ID ORDER CHECK
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 321)
]

assert df["faq_id"].tolist() == expected_ids, \
    "❌ FAQ ID order changed."

print()
print("✅ FAQ IDs remain continuous: FAQ0001 → FAQ0320")

# ============================================================
# SAVE DATASET
# ============================================================

df.to_csv(DATASET_PATH, index=False)

print()
print("=" * 100)
print("💾 DATASET SAVED")
print("=" * 100)

print(DATASET_PATH)

# ============================================================
# FINAL RESULT
# ============================================================

print()
print("=" * 100)
print("🏆 FINAL RESULT")
print("=" * 100)

if similar_df.empty:

    print("🟢 DATASET PASSED FINAL SIMILARITY CHECK")
    print()
    print("✅ 320 questions preserved")
    print("✅ FAQ0001 → FAQ0320")
    print("✅ No exact duplicates")
    print("✅ No normalized duplicates")
    print("✅ No similarity >= 0.85")
    print("✅ No same-intent similarity >= 0.85")
    print("✅ No cross-intent similarity >= 0.85")

else:

    print("🟡 DATASET SAVED — SIMILARITY REVIEW STILL REQUIRED")
    print()
    print(
        f"⚠️ Remaining similarity pairs: "
        f"{len(similar_df)}"
    )

print()
print("🔒 Backup:")
print(backup_path)

print("=" * 100)
print("🎉 FINAL FAQ0263 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FINAL FAQ0263 SIMILARITY FIX
====================================================================================================
📊 Rows before: 320
💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_faq0263_fix_20260821_145824.csv

====================================================================================================
🔄 MODIFYING FAQ0263
====================================================================================================
OLD: Combien d'étoiles possède le Nile Pearl Hotel ?
NEW: À quelle catégorie hôtelière appartient le Nile Pearl Hotel ?

====================================================================================================
🧪 BASIC VALIDATION
====================================================================================================
✅ Row count preserved: 320
✅ FAQ IDs remain unique.
✅ No missing questions.
✅ No empty questions.

====================================================================================================
📝 EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 FULL QUESTION SIMILARITY CHECK
====================================================================================================
🎉 No highly similar pairs found.
✅ All question pairs have similarity < 0.85.

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
✅ No highly similar questions inside the same intent.

====================================================================================================
⚠️ DIFFERENT-INTENT SIMILARITY
====================================================================================================
✅ No highly similar questions across different intents.

✅ FAQ IDs remain continuous: FAQ0001 → FAQ0320

====================================================================================================
💾 DATASET SAVED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 FINAL RESULT
====================================================================================================
🟢 DATASET PASSED FINAL SIMILARITY CHECK

✅ 320 questions preserved
✅ FAQ0001 → FAQ0320
✅ No exact duplicates
✅ No normalized duplicates
✅ No similarity >= 0.85
✅ No same-intent similarity >= 0.85
✅ No cross-intent similarity >= 0.85

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_faq0263_fix_20260821_145824.csv
====================================================================================================
🎉 FINAL FAQ0263 CHECK COMPLETE
====================================================================================================

In [31]:
# ============================================================
# 🏨 HOTEL AI - FULL DATASET QUALITY + DUPLICATE + SIMILARITY CHECK
# READ-ONLY — DOES NOT MODIFY THE DATASET
# ============================================================

from pathlib import Path
from itertools import combinations
import re
import unicodedata
import pandas as pd
import numpy as np
from difflib import SequenceMatcher

# ============================================================
# 1. CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 320

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

EXPECTED_STATUS = {
    "valid",
    "generated",
}

EXPECTED_DIFFICULTY = {
    "Easy",
}

SIMILARITY_THRESHOLD = 0.85

print("=" * 100)
print("🏨 HOTEL AI - FULL DATASET QUALITY + DUPLICATE + SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 2. PATH CHECK
# ============================================================

print("\n📂 PATH VALIDATION")
print("=" * 100)

assert PROJECT_ROOT.exists(), f"❌ Project root not found: {PROJECT_ROOT}"
print(f"✅ Project root found:\n{PROJECT_ROOT}")

assert DATASET_PATH.exists(), f"❌ Dataset not found: {DATASET_PATH}"
print(f"✅ Dataset found:\n{DATASET_PATH}")

# ============================================================
# 3. LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("\n📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 4. COLUMN CHECK
# ============================================================

print("\n🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    col for col in EXPECTED_COLUMNS
    if col not in df.columns
]

extra_columns = [
    col for col in df.columns
    if col not in EXPECTED_COLUMNS
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

assert not extra_columns, (
    f"❌ Unexpected columns: {extra_columns}"
)

assert list(df.columns) == EXPECTED_COLUMNS, (
    "❌ Column order is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 5. ROW COUNT
# ============================================================

print("\n📦 ROW COUNT")
print("=" * 100)

assert len(df) == EXPECTED_ROWS, (
    f"❌ Expected {EXPECTED_ROWS} rows, found {len(df)}"
)

print(f"Total questions: {len(df)}")
print(f"✅ Exactly {EXPECTED_ROWS} questions.")

# ============================================================
# 6. REQUIRED FIELD CHECK
# ============================================================

print("\n🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

required_fields_ok = True

for col in EXPECTED_COLUMNS:

    missing = int(df[col].isna().sum())

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15} "
        f"Missing: {missing:<3} "
        f"Empty: {empty:<3}"
    )

    if missing > 0 or empty > 0:
        required_fields_ok = False

assert required_fields_ok, (
    "❌ Required fields contain missing/empty values."
)

print("\n✅ All required fields are complete.")

# ============================================================
# 7. FAQ ID VALIDATION
# ============================================================

print("\n🆔 FAQ ID VALIDATION")
print("=" * 100)

id_pattern = re.compile(r"^FAQ\d{4}$")

invalid_ids = df[
    ~df["faq_id"]
    .astype(str)
    .str.match(id_pattern)
]

assert invalid_ids.empty, (
    f"❌ Invalid FAQ IDs:\n{invalid_ids[['faq_id']]}"
)

print("✅ All FAQ IDs have valid format.")

duplicate_ids = df[df["faq_id"].duplicated(keep=False)]

assert duplicate_ids.empty, (
    f"❌ Duplicate FAQ IDs:\n{duplicate_ids[['faq_id']]}"
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 8. FAQ ID CONTINUITY + ORDER
# ============================================================

print("\n🔢 FAQ ID CONTINUITY")
print("=" * 100)

numeric_ids = (
    df["faq_id"]
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

expected_ids = np.arange(1, EXPECTED_ROWS + 1)

missing_ids = sorted(
    set(expected_ids) - set(numeric_ids)
)

extra_ids = sorted(
    set(numeric_ids) - set(expected_ids)
)

assert not missing_ids, (
    f"❌ Missing IDs: {missing_ids}"
)

assert not extra_ids, (
    f"❌ Unexpected IDs: {extra_ids}"
)

assert numeric_ids.tolist() == expected_ids.tolist(), (
    "❌ FAQ IDs are not correctly ordered."
)

print(
    f"✅ IDs continuous and ordered: "
    f"FAQ0001 → FAQ{EXPECTED_ROWS:04d}"
)

# ============================================================
# 9. NORMALIZATION FUNCTION
# ============================================================

def normalize_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 10. EXACT DUPLICATES
# ============================================================

print("\n📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"]
    .duplicated(keep=False)
]

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        f"🔴 Exact duplicate rows: "
        f"{len(exact_duplicates)}"
    )

    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ]
        .sort_values("question")
        .to_string(index=False)
    )

# ============================================================
# 11. NORMALIZED DUPLICATES
# ============================================================

print("\n🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized_question"]
    .duplicated(keep=False)
]

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        f"🔴 Normalized duplicate rows: "
        f"{len(normalized_duplicates)}"
    )

    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
                "_normalized_question",
            ]
        ]
        .sort_values("_normalized_question")
        .to_string(index=False)
    )

# ============================================================
# 12. DUPLICATES INSIDE SAME INTENT
# ============================================================

print("\n🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

same_intent_duplicates = (
    df[
        df.duplicated(
            subset=["intent_id", "_normalized_question"],
            keep=False
        )
    ]
)

if same_intent_duplicates.empty:

    print(
        "✅ No normalized duplicates "
        "inside the same intent."
    )

else:

    print(
        f"🔴 Same-intent duplicate rows: "
        f"{len(same_intent_duplicates)}"
    )

    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ]
        .sort_values(
            ["intent_id", "question"]
        )
        .to_string(index=False)
    )

# ============================================================
# 13. INTENT ID ↔ INTENT NAME
# ============================================================

print("\n🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_errors = []

for intent_id, expected_name in EXPECTED_INTENTS.items():

    rows = df[df["intent_id"] == intent_id]

    if rows.empty:
        intent_errors.append(
            f"{intent_id}: missing"
        )
        continue

    actual_names = set(
        rows["intent_name"]
        .dropna()
        .astype(str)
    )

    if actual_names != {expected_name}:

        intent_errors.append(
            f"{intent_id}: "
            f"expected {expected_name}, "
            f"found {actual_names}"
        )

unexpected_intents = set(df["intent_id"]) - set(
    EXPECTED_INTENTS
)

if unexpected_intents:
    intent_errors.append(
        f"Unexpected intent IDs: {unexpected_intents}"
    )

assert not intent_errors, (
    "❌ Intent mapping errors:\n"
    + "\n".join(intent_errors)
)

print("✅ All intent mappings are correct.")

# ============================================================
# 14. LANGUAGE VALIDATION
# ============================================================

print("\n🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts.to_string())

unexpected_languages = (
    set(df["language"]) - EXPECTED_LANGUAGES
)

assert not unexpected_languages, (
    f"❌ Unexpected languages: {unexpected_languages}"
)

assert set(language_counts.index) == EXPECTED_LANGUAGES, (
    "❌ Language set is incorrect."
)

for language in EXPECTED_LANGUAGES:

    count = int(language_counts.get(language, 0))

    assert count == 80, (
        f"❌ {language}: expected 80, found {count}"
    )

print("\n✅ 80 questions × 4 languages.")

# ============================================================
# 15. INTENT DISTRIBUTION
# ============================================================

print("\n🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_distribution = (
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .reset_index(name="questions")
)

print(
    intent_distribution.to_string(index=False)
)

for intent_id in EXPECTED_INTENTS:

    count = int(
        (df["intent_id"] == intent_id).sum()
    )

    assert count == 40, (
        f"❌ {intent_id}: "
        f"expected 40, found {count}"
    )

print("\n✅ 40 questions × 8 intents.")

# ============================================================
# 16. QUESTION TYPE VALIDATION
# ============================================================

print("\n📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = df["question_type"].value_counts()

print(question_type_counts.to_string())

unexpected_types = (
    set(df["question_type"])
    - EXPECTED_QUESTION_TYPES
)

assert not unexpected_types, (
    f"❌ Unexpected question types: {unexpected_types}"
)

print("\n✅ All question types are valid.")

# ============================================================
# 17. STATUS VALIDATION
# ============================================================

print("\n📌 STATUS DISTRIBUTION")
print("=" * 100)

status_counts = df["status"].value_counts()

print(status_counts.to_string())

unexpected_status = (
    set(df["status"])
    - EXPECTED_STATUS
)

assert not unexpected_status, (
    f"❌ Unexpected status values: {unexpected_status}"
)

print("\n✅ Status values are valid.")

# ============================================================
# 18. DIFFICULTY VALIDATION
# ============================================================

print("\n📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)

difficulty_counts = df["difficulty"].value_counts()

print(difficulty_counts.to_string())

unexpected_difficulty = (
    set(df["difficulty"])
    - EXPECTED_DIFFICULTY
)

assert not unexpected_difficulty, (
    f"❌ Unexpected difficulty values: "
    f"{unexpected_difficulty}"
)

print("\n✅ Difficulty values are valid.")

# ============================================================
# 19. GROUND TRUTH / ANSWER CHECK
# ============================================================

print("\n🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

gt_empty = (
    df["ground_truth"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
)

answer_empty = (
    df["answer"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
)

assert not gt_empty.any(), (
    "❌ Empty ground_truth values found."
)

assert not answer_empty.any(), (
    "❌ Empty answer values found."
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 20. GROUND TRUTH ↔ ANSWER CONSISTENCY
# ============================================================

print("\n🔗 GROUND TRUTH ↔ ANSWER CONSISTENCY")
print("=" * 100)

df["_normalized_ground_truth"] = (
    df["ground_truth"]
    .map(normalize_text)
)

df["_normalized_answer"] = (
    df["answer"]
    .map(normalize_text)
)

answer_mismatches = df[
    df["_normalized_ground_truth"]
    != df["_normalized_answer"]
]

if answer_mismatches.empty:

    print(
        "✅ Ground truth and answer are identical "
        "after normalization."
    )

else:

    print(
        f"🟡 {len(answer_mismatches)} rows have "
        "different ground_truth and answer text."
    )

    print(
        answer_mismatches[
            [
                "faq_id",
                "ground_truth",
                "answer",
            ]
        ]
        .to_string(index=False)
    )

# ============================================================
# 21. LANGUAGE × INTENT
# ============================================================

print("\n📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(language_intent.to_string())

for intent_id in EXPECTED_INTENTS:

    for language in EXPECTED_LANGUAGES:

        count = int(
            language_intent
            .get(language, pd.Series())
            .get(intent_id, 0)
        )

        assert count == 10, (
            f"❌ {intent_id} × {language}: "
            f"expected 10, found {count}"
        )

print(
    "\n✅ Every intent contains "
    "10 questions in every language."
)

# ============================================================
# 22. QUESTION TYPE × LANGUAGE
# ============================================================

print("\n📊 QUESTION TYPE × LANGUAGE")
print("=" * 100)

type_language = pd.crosstab(
    df["language"],
    df["question_type"]
)

print(type_language.to_string())

# ============================================================
# 23. QUESTION LENGTH CHECK
# ============================================================

print("\n📏 QUESTION LENGTH CHECK")
print("=" * 100)

df["_question_length"] = (
    df["question"]
    .astype(str)
    .str.len()
)

too_short = df[
    df["_question_length"] < 10
]

if too_short.empty:

    print(
        "✅ No suspiciously short questions "
        "(< 10 characters)."
    )

else:

    print(
        f"⚠️ {len(too_short)} suspiciously short questions:"
    )

    print(
        too_short[
            ["faq_id", "language", "question"]
        ]
        .to_string(index=False)
    )

# ============================================================
# 24. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n🔎 FULL QUESTION SIMILARITY CHECK")
print("=" * 100)

questions = df["question"].astype(str).tolist()
faq_ids = df["faq_id"].tolist()
intents = df["intent_id"].tolist()
languages = df["language"].tolist()

pairs = []

total_pairs = len(questions) * (len(questions) - 1) // 2

print(
    f"Comparing {total_pairs:,} question pairs..."
)

for i, j in combinations(range(len(questions)), 2):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.80:

        pairs.append({
            "similarity": round(score, 3),
            "faq_id_1": faq_ids[i],
            "intent_1": intents[i],
            "language_1": languages[i],
            "question_1": questions[i],
            "faq_id_2": faq_ids[j],
            "intent_2": intents[j],
            "language_2": languages[j],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(pairs)

if similarity_df.empty:

    print(
        "🎉 No pairs with similarity >= 0.80."
    )

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"🔎 Pairs with similarity >= 0.80: "
        f"{len(similarity_df)}"
    )

# ============================================================
# 25. SIMILARITY THRESHOLD COUNTS
# ============================================================

print("\n📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

if similarity_df.empty:

    for threshold in [0.80, 0.85, 0.90, 0.95]:

        print(
            f"{threshold:.2f}+ : 0 pairs"
        )

else:

    for threshold in [0.80, 0.85, 0.90, 0.95]:

        count = int(
            (similarity_df["similarity"] >= threshold)
            .sum()
        )

        print(
            f"{threshold:.2f}+ : {count} pairs"
        )

# ============================================================
# 26. TOP 30 MOST SIMILAR
# ============================================================

print("\n📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:

    print("None.")

else:

    print(
        similarity_df
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 27. SAME-INTENT SIMILARITY
# ============================================================

print("\n🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

if same_intent.empty:

    print(
        "✅ No similar pairs inside the same intent "
        "at >= 0.80."
    )

else:

    print(
        f"⚠️ Same-intent similar pairs: "
        f"{len(same_intent)}"
    )

    print(
        same_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 28. CROSS-INTENT SIMILARITY
# ============================================================

print("\n⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

if cross_intent.empty:

    print(
        "✅ No cross-intent similar pairs "
        "at >= 0.80."
    )

else:

    print(
        f"⚠️ Cross-intent similar pairs: "
        f"{len(cross_intent)}"
    )

    print(
        cross_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 29. SAME-LANGUAGE SIMILARITY
# ============================================================

print("\n🌍 SAME-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_language = pd.DataFrame()

else:

    same_language = similarity_df[
        similarity_df["language_1"]
        ==
        similarity_df["language_2"]
    ]

if same_language.empty:

    print(
        "✅ No same-language similar pairs "
        "at >= 0.80."
    )

else:

    print(
        f"Same-language similar pairs: "
        f"{len(same_language)}"
    )

# ============================================================
# 30. CROSS-LANGUAGE SIMILARITY
# ============================================================

print("\n🌐 CROSS-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_language = pd.DataFrame()

else:

    cross_language = similarity_df[
        similarity_df["language_1"]
        !=
        similarity_df["language_2"]
    ]

if cross_language.empty:

    print(
        "✅ No cross-language similar pairs "
        "at >= 0.80."
    )

else:

    print(
        f"Cross-language similar pairs: "
        f"{len(cross_language)}"
    )

# ============================================================
# 31. HIGH-SIMILARITY REVIEW
# ============================================================

print("\n🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"]
        >= SIMILARITY_THRESHOLD
    ]

if high_similarity.empty:

    print(
        f"🎉 No similarity >= "
        f"{SIMILARITY_THRESHOLD:.2f}"
    )

else:

    print(
        f"⚠️ {len(high_similarity)} pairs "
        f"have similarity >= "
        f"{SIMILARITY_THRESHOLD:.2f}"
    )

    print(
        high_similarity
        .to_string(index=False)
    )

# ============================================================
# 32. VERY HIGH SIMILARITY
# ============================================================

print("\n🔴 VERY HIGH SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    very_high = pd.DataFrame()

else:

    very_high = similarity_df[
        similarity_df["similarity"]
        >= 0.90
    ]

if very_high.empty:

    print(
        "✅ No pairs with similarity >= 0.90."
    )

else:

    print(
        f"🔴 {len(very_high)} pairs "
        "with similarity >= 0.90:"
    )

    print(
        very_high.to_string(index=False)
    )

# ============================================================
# 33. EXTREME SIMILARITY
# ============================================================

print("\n🔴 EXTREME SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    extreme = pd.DataFrame()

else:

    extreme = similarity_df[
        similarity_df["similarity"]
        >= 0.95
    ]

if extreme.empty:

    print(
        "✅ No pairs with similarity >= 0.95."
    )

else:

    print(
        f"🚨 {len(extreme)} pairs "
        "with similarity >= 0.95:"
    )

    print(
        extreme.to_string(index=False)
    )

# ============================================================
# 34. SOURCE / CATEGORY CONSISTENCY
# ============================================================

print("\n📌 CATEGORY / SOURCE CHECK")
print("=" * 100)

for col in ["category", "source"]:

    unique_values = (
        df[col]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    print(
        f"{col}: {len(unique_values)} unique value(s)"
    )

    print(
        list(unique_values)
    )

# ============================================================
# 35. ATTEMPTS VALIDATION
# ============================================================

print("\n🔢 ATTEMPTS VALIDATION")
print("=" * 100)

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

invalid_attempts = df[
    attempts_numeric.isna()
]

negative_attempts = df[
    attempts_numeric < 0
]

assert invalid_attempts.empty, (
    "❌ Non-numeric attempts found."
)

assert negative_attempts.empty, (
    "❌ Negative attempts found."
)

print("✅ Attempts values are numeric and non-negative.")

print(
    f"Attempts min : {attempts_numeric.min()}"
)

print(
    f"Attempts max : {attempts_numeric.max()}"
)

print(
    f"Attempts mean: {attempts_numeric.mean():.2f}"
)

# ============================================================
# 36. NULL / WHITESPACE CHECK ACROSS ALL TEXT
# ============================================================

print("\n🧹 WHITESPACE / EMPTY TEXT CHECK")
print("=" * 100)

whitespace_issues = []

for col in EXPECTED_COLUMNS:

    series = df[col].astype(str)

    leading = series[
        series.str.match(r"^\s")
    ]

    trailing = series[
        series.str.match(r".*\s$")
    ]

    if len(leading) > 0:

        whitespace_issues.append(
            (col, "leading", len(leading))
        )

    if len(trailing) > 0:

        whitespace_issues.append(
            (col, "trailing", len(trailing))
        )

if not whitespace_issues:

    print(
        "✅ No obvious leading/trailing whitespace issues."
    )

else:

    print(
        "⚠️ Whitespace issues detected:"
    )

    for issue in whitespace_issues:

        print(issue)

# ============================================================
# 37. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL FULL DATASET CHECK RESULT")
print("=" * 100)

structural_pass = True

if len(df) != EXPECTED_ROWS:
    structural_pass = False

if missing_columns or extra_columns:
    structural_pass = False

if not duplicate_ids.empty:
    structural_pass = False

if not missing_ids == []:
    structural_pass = False

if not extra_ids == []:
    structural_pass = False

if not required_fields_ok:
    structural_pass = False

if not intent_errors == []:
    structural_pass = False

if not exact_duplicates.empty:
    structural_pass = False

if not normalized_duplicates.empty:
    structural_pass = False

if not gt_empty.any() == False:
    structural_pass = False

if not answer_empty.any() == False:
    structural_pass = False

if structural_pass:

    print("🟢 STRUCTURAL CHECK: PASS")

else:

    print("🔴 STRUCTURAL CHECK: FAIL")

# Similarity result

if similarity_df.empty:

    similarity_pass = True

else:

    similarity_pass = (
        (similarity_df["similarity"] >= 0.85)
        .sum()
        == 0
    )

if similarity_pass:

    print("🟢 SIMILARITY CHECK: PASS")
    print("✅ No similarity >= 0.85.")

else:

    print("🟡 SIMILARITY CHECK: REVIEW REQUIRED")
    print(
        f"⚠️ {len(high_similarity)} "
        "pairs >= 0.85."
    )

# ============================================================
# 38. FINAL CHECKLIST
# ============================================================

print("\n" + "=" * 100)
print("📋 FINAL CHECKLIST")
print("=" * 100)

checks = [
    ("320 questions", len(df) == 320),
    ("13 columns", len(df.columns) == 13),
    ("Valid FAQ IDs", invalid_ids.empty),
    ("No duplicate IDs", duplicate_ids.empty),
    ("Continuous IDs", numeric_ids.tolist() == expected_ids.tolist()),
    ("Required fields complete", required_fields_ok),
    ("No exact duplicates", exact_duplicates.empty),
    ("No normalized duplicates", normalized_duplicates.empty),
    ("No same-intent duplicates", same_intent_duplicates.empty),
    ("Intent mappings correct", not intent_errors),
    ("4 languages", set(df["language"]) == EXPECTED_LANGUAGES),
    ("40 questions per intent", all(
        (df["intent_id"] == x).sum() == 40
        for x in EXPECTED_INTENTS
    )),
    ("10 per language per intent", all(
        language_intent.loc[x, y] == 10
        for x in EXPECTED_INTENTS
        for y in EXPECTED_LANGUAGES
    )),
    ("Question types valid", not bool(unexpected_types)),
    ("Status valid", not bool(unexpected_status)),
    ("Difficulty valid", not bool(unexpected_difficulty)),
    ("Ground truth complete", not gt_empty.any()),
    ("Answers complete", not answer_empty.any()),
    ("No similarity >= 0.85", similarity_pass),
]

for name, result in checks:

    print(
        f"{'✅' if result else '❌'} {name}"
    )

# ============================================================
# 39. READ-ONLY CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 40. FINAL STATUS
# ============================================================

print("\n" + "=" * 100)

all_pass = all(
    result for _, result in checks
)

if all_pass:

    print("🎉🟢 FULL DATASET CHECK PASSED")
    print("=" * 100)
    print("✅ ALL 320 QUESTIONS PASSED ALL CHECKS.")
    print("✅ Dataset is clean and ready.")

else:

    print("⚠️🟡 FULL DATASET CHECK REQUIRES REVIEW")
    print("=" * 100)
    print("⚠️ One or more checks require attention.")

print("=" * 100)

# ============================================================
# 41. CLEAN TEMPORARY COLUMNS
# ============================================================

# مهم:
# ده فقط في الذاكرة، ولن يتم حفظ أي تعديل على CSV.

df.drop(
    columns=[
        "_normalized_question",
        "_normalized_ground_truth",
        "_normalized_answer",
        "_question_length",
    ],
    inplace=True,
    errors="ignore"
)

print("\n🏁 CHECK COMPLETE")

====================================================================================================
🏨 HOTEL AI - FULL DATASET QUALITY + DUPLICATE + SIMILARITY CHECK
====================================================================================================

📂 PATH VALIDATION
====================================================================================================
✅ Project root found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Dataset found:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

📊 DATASET INFORMATION
====================================================================================================
Rows    : 320
Columns : 13

🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

📦 ROW COUNT
====================================================================================================
Total questions: 320
✅ Exactly 320 questions.

🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0

✅ All required fields are complete.

🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

🔢 FAQ ID CONTINUITY
====================================================================================================
✅ IDs continuous and ordered: FAQ0001 → FAQ0320

📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ All intent mappings are correct.

🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    80
Arabic     80
French     80
Russian    80

✅ 80 questions × 4 languages.

🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         40
   INT002          hotel_category         40
   INT003  reception_availability         40
   INT004           check_in_time         40
   INT005          check_out_time         40
   INT006          early_check_in         40
   INT007          late_check_out         40
   INT008 identification_required         40

✅ 40 questions × 8 intents.

📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    128
Direct         108
Scenario        84

✅ All question types are valid.

📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated     96

✅ Status values are valid.

📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    320

✅ Difficulty values are valid.

🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

🔗 GROUND TRUTH ↔ ANSWER CONSISTENCY
====================================================================================================
🟡 283 rows have different ground_truth and answer text.
 faq_id                                                                         ground_truth                                                                                                                                                                                                                                                           answer
FAQ0002                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                    Nile Pearl Hotel is situated in Cairo, Egypt.
FAQ0004                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                 The Nile Pearl Hotel is located in Cairo, Egypt.
FAQ0006                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel can be found in Cairo, Egypt.
FAQ0009                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                       يقع فندق Nile Pearl Hotel في القاهرة، مصر.
FAQ0010                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                            يقع Nile Pearl Hotel في القاهرة، مصر.
FAQ0011                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                     يقع فندق نيل بيرل في القاهرة، مصر. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0012                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                            يقع Nile Pearl Hotel في القاهرة، مصر.
FAQ0013                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                            تقع Nile Pearl Hotel في القاهرة، مصر.
FAQ0014                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                       يقع فندق Nile Pearl Hotel في القاهرة، مصر.
FAQ0015                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                           موقع Nile Pearl Hotel في القاهرة، مصر.
FAQ0016                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                       يقع فندق Nile Pearl Hotel في القاهرة، مصر.
FAQ0017                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0018                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0019                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0020                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0021                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0022                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0023                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0024                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                   Nile Pearl Hotel se trouve à Cairo, en Égypte.
FAQ0025                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                      Nile Pearl Hotel находится в Каире, Египет.
FAQ0026                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                      Nile Pearl Hotel находится в Каире, Египет.
FAQ0027                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                     Nile Pearl Hotel расположен в Каире, Египет.
FAQ0028                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                               Nile Pearl Hotel находится в городе Каире, Египет.
FAQ0029                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                              Nile Pearl Hotel расположен в городе Каире, Египет.
FAQ0030                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                      Nile Pearl Hotel находится в Каире, Египет.
FAQ0031                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                                      Nile Pearl Hotel находится в Каире, Египет.
FAQ0032                                         Nile Pearl Hotel is located in Cairo, Egypt.                                                                                                                                                                                                               Nile Pearl Hotel находится в городе Каире, Египет.
FAQ0033                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                               Nile Pearl Hotel is rated 5 stars.
FAQ0034                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                      Nile Pearl Hotel is a 5-star establishment.
FAQ0035                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                Nile Pearl Hotel is classified as a 5-star hotel.
FAQ0036                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                      Nile Pearl Hotel is a 5-star establishment.
FAQ0037                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                          Nile Pearl Hotel holds a 5-star rating.
FAQ0038                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                      Nile Pearl Hotel is a 5-star establishment.
FAQ0039                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                      Nile Pearl Hotel is a 5-star establishment.
FAQ0040                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                      Nile Pearl Hotel is a 5-star establishment.
FAQ0041                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                     نile pearl hotel هو فندق خمس نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0042                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                               نيل بيرل هو فندق 5 نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0043                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                         فندق Nile Pearl Hotel مصنف كفندق 5 نجوم.
FAQ0044                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                               نيل بيرل هو فندق 5 نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0045                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                       نيل بيرل هوôtel من فئة خمس نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0046                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                                                            يقع Nile Pearl Hotel في فئة خمس نجوم.
FAQ0047                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                            نيل بيرل هوتل في القاهرة مصنف كفندق 5 نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.
FAQ0048                                                  Nile Pearl Hotel is a 5-star hotel.                                                                                                                                                                                          نيل بيرل هوتل هو فندق 5 نجوم. تنطبق هذه المعلومات على Nile Pearl Hotel.

In [32]:
# ============================================================
# 🏆 HOTEL AI - VALIDATION SCORE
# ============================================================

checks = {
    "Row count": len(df) == 320,
    "13 columns": len(df.columns) == 13,
    "Valid FAQ IDs": invalid_ids.empty,
    "No duplicate IDs": duplicate_ids.empty,
    "Continuous IDs": numeric_ids.tolist() == expected_ids.tolist(),
    "Required fields complete": required_fields_ok,
    "No exact duplicates": exact_duplicates.empty,
    "No normalized duplicates": normalized_duplicates.empty,
    "No same-intent duplicates": same_intent_duplicates.empty,
    "Intent mappings": not intent_errors,
    "Language balance": set(df["language"]) == EXPECTED_LANGUAGES,
    "Intent balance": all(
        (df["intent_id"] == intent_id).sum() == 40
        for intent_id in EXPECTED_INTENTS
    ),
    "Question types valid": not unexpected_types,
    "Status valid": not unexpected_status,
    "Difficulty valid": not unexpected_difficulty,
    "Ground truth complete": not gt_empty.any(),
    "Answers complete": not answer_empty.any(),
    "Language × Intent balance": all(
        language_intent.loc[intent_id, language] == 10
        for intent_id in EXPECTED_INTENTS
        for language in EXPECTED_LANGUAGES
    ),
    "Similarity < 0.85": (
        similarity_df.empty
        or not (similarity_df["similarity"] >= 0.85).any()
    ),
}

passed = sum(checks.values())
total = len(checks)
score = passed / total * 100

print("=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():
    print(
        f"{'✅' if result else '❌'} {name}"
    )

print("-" * 100)
print(f"Passed checks : {passed}/{total}")
print(f"Validation Score : {score:.1f}%")

if score == 100:
    print("🟢 DATASET IS FULLY VALIDATED")
else:
    print("🟡 DATASET NEEDS REVIEW")

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ Row count
✅ 13 columns
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ Required fields complete
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Question types valid
✅ Status valid
✅ Difficulty valid
✅ Ground truth complete
✅ Answers complete
✅ Language × Intent balance
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks : 19/19
Validation Score : 100.0%
🟢 DATASET IS FULLY VALIDATED

In [33]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 GENERATION
# 32 NEW QUESTIONS ONLY
# CONTINUE FROM FAQ0320
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 GENERATION")
print("=" * 100)

# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = (
    BATCH_DIR
    / "faq_batch_04.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print("✅ Project root found.")
print("✅ Final dataset found.")

# ============================================================
# 2. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

assert len(df) == 320, (
    f"❌ Expected 320 existing questions, "
    f"found {len(df)}"
)

print("✅ Existing dataset contains exactly 320 questions.")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Existing dataset column structure is incorrect."
)

print("✅ All 13 required columns exist.")

# ============================================================
# 4. FAQ ID CONTINUATION
# ============================================================

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = numeric_ids.max()

START_ID = last_id + 1
END_ID = START_ID + 32

assert START_ID == 321
assert END_ID == 353

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(
    f"New batch     : FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# ============================================================
# 5. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 6. BATCH 04 QUESTIONS
# ============================================================

questions = [

    # ========================================================
    # INT001 - HOTEL LOCATION
    # ========================================================

    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما أقرب منطقة أو معلم يمكنني استخدامه لتحديد موقع Nile Pearl Hotel؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What nearby area or landmark can I use to identify the location of Nile Pearl Hotel?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quel quartier ou point de repère proche puis-je utiliser pour localiser le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какой ближайший район или ориентир можно использовать, чтобы найти Nile Pearl Hotel?",
    },

    # ========================================================
    # INT002 - HOTEL CATEGORY
    # ========================================================

    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "How is Nile Pearl Hotel classified in terms of hotel standard?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Comment le Nile Pearl Hotel est-il classé selon son niveau hôtelier ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Как классифицируется Nile Pearl Hotel по уровню гостиничного сервиса?",
    },

    # ========================================================
    # INT003 - RECEPTION AVAILABILITY
    # ========================================================

    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا احتجت إلى مساعدة في الفندق ليلًا، هل سأجد موظف استقبال متاحًا؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I need assistance at the hotel late at night, will a reception staff member be available?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'ai besoin d'aide à l'hôtel tard dans la nuit, un membre de la réception sera-t-il disponible ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если мне понадобится помощь в отеле поздно ночью, будет ли сотрудник стойки регистрации на месте?",
    },

    # ========================================================
    # INT004 - CHECK IN TIME
    # ========================================================

    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Direct",
        "question": "When does the standard check-in period begin at Nile Pearl Hotel?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Direct",
        "question": "À quelle heure commence normalement l'enregistrement au Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Во сколько обычно начинается регистрация заезда в Nile Pearl Hotel?",
    },

    # ========================================================
    # INT005 - CHECK OUT TIME
    # ========================================================

    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما آخر وقت معتاد لمغادرة الغرفة في Nile Pearl Hotel؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What is the usual latest time to vacate the room at Nile Pearl Hotel?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "До какого времени обычно нужно освободить номер в Nile Pearl Hotel?",
    },

    # ========================================================
    # INT006 - EARLY CHECK IN
    # ========================================================

    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل أستطيع تقديم طلب لتسجيل الوصول قبل الموعد المعتاد؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I submit a request for check-in before the standard time?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je demander un enregistrement avant l'heure habituelle ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Можно ли подать запрос на заселение раньше обычного времени?",
    },

    # ========================================================
    # INT007 - LATE CHECK OUT
    # ========================================================

    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل توجد إمكانية للبقاء في الغرفة بعد موعد تسجيل المغادرة المعتاد؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Is it possible to remain in the room after the usual check-out time?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Est-il possible de rester dans la chambre après l'heure habituelle de départ ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Можно ли остаться в номере после обычного времени выезда?",
    },

    # ========================================================
    # INT008 - IDENTIFICATION REQUIRED
    # ========================================================

    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يتعين علي إبراز بطاقة أو وثيقة هوية عند تسجيل الوصول؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Direct",
        "question": "Do I need to show an identification document when checking in?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Direct",
        "question": "Dois-je présenter une pièce d'identité lors de l'enregistrement ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Нужно ли предъявлять удостоверение личности при регистрации заезда?",
    },
]

# ============================================================
# 7. STRUCTURE CHECK
# ============================================================

assert len(questions) == 32, (
    f"❌ Expected 32 questions, found {len(questions)}"
)

required_question_fields = [
    "intent_id",
    "language",
    "question_type",
    "question",
]

for index, item in enumerate(questions, start=1):

    for field in required_question_fields:

        assert field in item, (
            f"❌ Question #{index} missing field: {field}"
        )

        assert str(item[field]).strip(), (
            f"❌ Question #{index} empty field: {field}"
        )

print("\n" + "=" * 100)
print("🧪 QUESTION STRUCTURE CHECK")
print("=" * 100)

print("✅ All 32 questions contain all required question fields.")

# ============================================================
# 8. BUILD DATAFRAME
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 04",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(batch)

# ============================================================
# 9. ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 ID VALIDATION")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(START_ID, END_ID)
]

assert batch_df["faq_id"].tolist() == expected_batch_ids

assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0321 → FAQ0352.")
print("✅ No duplicate IDs.")

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 11. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

batch_normalized = batch_df["question"].map(
    normalize_question
)

assert not batch_normalized.duplicated().any()

print("✅ No duplicate questions inside Batch 04.")

# ============================================================
# 12. COMPARE WITH EXISTING 320
# ============================================================

existing_normalized = set(
    df["question"].map(normalize_question)
)

overlap_mask = batch_normalized.isin(
    existing_normalized
)

if overlap_mask.any():

    overlap_df = batch_df.loc[
        overlap_mask,
        [
            "faq_id",
            "intent_id",
            "language",
            "question",
        ]
    ]

    print("\n❌ OVERLAP FOUND:")
    print(
        overlap_df.to_string(index=False)
    )

    raise AssertionError(
        "❌ Batch 04 contains questions "
        "already present in the existing 320."
    )

print("✅ No exact/normalized overlap with existing 320.")

# ============================================================
# 13. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert language_counts.to_dict() == (
    expected_language_counts
)

print("✅ 8 questions × 4 languages.")

# ============================================================
# 14. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

expected_intent_counts = {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

assert intent_counts.to_dict() == (
    expected_intent_counts
)

print("✅ 4 questions × 8 intents.")

# ============================================================
# 15. INTENT NAME CONSISTENCY
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 16. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = (
    set(batch_df["question_type"])
    - VALID_TYPES
)

assert not invalid_types

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 17. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 04 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 18. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 19. FINAL
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 04 READY")
print("=" * 100)

print(
    f"""
Existing dataset : {len(df)} questions
New batch        : {len(batch_df)} questions

FAQ IDs:
FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 320
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Project root found.
✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 320
Columns : 13
✅ Existing dataset contains exactly 320 questions.
✅ All 13 required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0320
New batch     : FAQ0321 → FAQ0352

====================================================================================================
🧪 QUESTION STRUCTURE CHECK
====================================================================================================
✅ All 32 questions contain all required question fields.

====================================================================================================
🆔 ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0321 → FAQ0352.
✅ No duplicate IDs.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions inside Batch 04.
✅ No exact/normalized overlap with existing 320.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    16
Direct         12
Scenario        4
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📝 BATCH 04 QUESTIONS
====================================================================================================
 faq_id intent_id language question_type                                                                                            question
FAQ0321    INT001   Arabic   Paraphrased                                 ما أقرب منطقة أو معلم يمكنني استخدامه لتحديد موقع Nile Pearl Hotel؟
FAQ0322    INT001  English   Paraphrased                What nearby area or landmark can I use to identify the location of Nile Pearl Hotel?
FAQ0323    INT001   French   Paraphrased       Quel quartier ou point de repère proche puis-je utiliser pour localiser le Nile Pearl Hotel ?
FAQ0324    INT001  Russian   Paraphrased                Какой ближайший район или ориентир можно использовать, чтобы найти Nile Pearl Hotel?
FAQ0325    INT002   Arabic   Paraphrased                                              كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟
FAQ0326    INT002  English   Paraphrased                                      How is Nile Pearl Hotel classified in terms of hotel standard?
FAQ0327    INT002   French   Paraphrased                               Comment le Nile Pearl Hotel est-il classé selon son niveau hôtelier ?
FAQ0328    INT002  Russian   Paraphrased                               Как классифицируется Nile Pearl Hotel по уровню гостиничного сервиса?
FAQ0329    INT003   Arabic      Scenario                                  إذا احتجت إلى مساعدة في الفندق ليلًا، هل سأجد موظف استقبال متاحًا؟
FAQ0330    INT003  English      Scenario        If I need assistance at the hotel late at night, will a reception staff member be available?
FAQ0331    INT003   French      Scenario Si j'ai besoin d'aide à l'hôtel tard dans la nuit, un membre de la réception sera-t-il disponible ?
FAQ0332    INT003  Russian      Scenario   Если мне понадобится помощь в отеле поздно ночью, будет ли сотрудник стойки регистрации на месте?
FAQ0333    INT004   Arabic        Direct                                              متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟
FAQ0334    INT004  English        Direct                                   When does the standard check-in period begin at Nile Pearl Hotel?
FAQ0335    INT004   French        Direct                          À quelle heure commence normalement l'enregistrement au Nile Pearl Hotel ?
FAQ0336    INT004  Russian        Direct                                 Во сколько обычно начинается регистрация заезда в Nile Pearl Hotel?
FAQ0337    INT005   Arabic   Paraphrased                                                ما آخر وقت معتاد لمغادرة الغرفة في Nile Pearl Hotel؟
FAQ0338    INT005  English   Paraphrased                               What is the usual latest time to vacate the room at Nile Pearl Hotel?
FAQ0339    INT005   French   Paraphrased                  Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?
FAQ0340    INT005  Russian   Paraphrased                                 До какого времени обычно нужно освободить номер в Nile Pearl Hotel?
FAQ0341    INT006   Arabic        Direct                                               هل أستطيع تقديم طلب لتسجيل الوصول قبل الموعد المعتاد؟
FAQ0342    INT006  English        Direct                                       Can I submit a request for check-in before the standard time?
FAQ0343    INT006   French        Direct                                       Puis-je demander un enregistrement avant l'heure habituelle ?
FAQ0344    INT006  Russian        Direct                                        Можно ли подать запрос на заселение раньше обычного времени?
FAQ0345    INT007   Arabic   Paraphrased                                   هل توجد إمكانية للبقاء في الغرفة بعد موعد تسجيل المغادرة المعتاد؟
FAQ0346    INT007  English   Paraphrased                                Is it possible to remain in the room after the usual check-out time?
FAQ0347    INT007   French   Paraphrased                      Est-il possible de rester dans la chambre après l'heure habituelle de départ ?
FAQ0348    INT007  Russian   Paraphrased                                           Можно ли остаться в номере после обычного времени выезда?
FAQ0349    INT008   Arabic        Direct                                            هل يتعين علي إبراز بطاقة أو وثيقة هوية عند تسجيل الوصول؟
FAQ0350    INT008  English        Direct                                      Do I need to show an identification document when checking in?
FAQ0351    INT008   French        Direct                                   Dois-je présenter une pièce d'identité lors de l'enregistrement ?
FAQ0352    INT008  Russian        Direct                                 Нужно ли предъявлять удостоверение личности при регистрации заезда?

====================================================================================================
🎉 BATCH 04 READY
====================================================================================================

Existing dataset : 320 questions
New batch        : 32 questions

FAQ IDs:
FAQ0321 → FAQ0352

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 320
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_04.csv

====================================================================================================

In [34]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 vs EXISTING 320
# DUPLICATE + SIMILARITY CHECK
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 vs EXISTING 320")
print("=" * 100)

assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

df = pd.read_csv(FINAL_DATASET)
batch_df = pd.read_csv(BATCH_FILE)

assert len(df) == 320
assert len(batch_df) == 32

print(f"Existing questions : {len(df)}")
print(f"Batch 04 questions : {len(batch_df)}")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):
    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = existing_exact.intersection(
    batch_exact
)

if exact_overlap:
    print("❌ Exact overlap found:")
    for q in sorted(exact_overlap):
        print(q)
else:
    print("✅ No exact overlap.")

# ============================================================
# NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_norm = set(
    df["question"].map(normalize)
)

batch_norm = set(
    batch_df["question"].map(normalize)
)

normalized_overlap = (
    existing_norm.intersection(batch_norm)
)

if normalized_overlap:
    print("❌ Normalized overlap found:")
    for q in sorted(normalized_overlap):
        print(q)
else:
    print("✅ No normalized overlap.")

# ============================================================
# DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 04")
print("=" * 100)

batch_duplicate = batch_df[
    batch_df["question"].duplicated(keep=False)
]

if batch_duplicate.empty:
    print("✅ No duplicate questions inside Batch 04.")
else:
    print(
        batch_duplicate[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(pairs)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs with similarity >= 0.80: "
        f"{len(similarity_df)}"
    )

    print("\nTOP 30:")
    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# SAME INTENT
# ============================================================

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print(
    f"Same-intent pairs >= 0.80: "
    f"{len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# CROSS INTENT
# ============================================================

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print(
    f"Cross-intent pairs >= 0.80: "
    f"{len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# HIGH SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high = pd.DataFrame()

else:

    high = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

print(
    f"Similarity >= 0.85: {len(high)}"
)

if not high.empty:

    print(
        high.to_string(index=False)
    )
else:
    print("✅ No similarity >= 0.85.")

# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 04 SIMILARITY SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 320
Batch 04 questions           : 32
Exact overlaps               : {len(exact_overlap)}
Normalized overlaps          : {len(normalized_overlap)}
Pairs >= 0.80                : {len(similarity_df)}
Same-intent pairs >= 0.80    : {len(same_intent)}
Cross-intent pairs >= 0.80   : {len(cross_intent)}
Pairs >= 0.85                : {len(high)}
"""
)

# ============================================================
# FINAL
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY")
print("=" * 100)

print("✅ Existing dataset was NOT modified.")
print("✅ Batch 04 was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")

print("\n" + "=" * 100)
print("🎉 BATCH 04 CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 vs EXISTING 320
====================================================================================================
Existing questions : 320
Batch 04 questions : 32

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 04
====================================================================================================
✅ No duplicate questions inside Batch 04.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs with similarity >= 0.80: 8

TOP 30:
 similarity new_faq_id new_intent new_language                                                          new_question old_faq_id old_intent old_language                                                             old_question
      0.860    FAQ0325     INT002       Arabic                كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0043     INT002       Arabic                         كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
      0.860    FAQ0325     INT002       Arabic                كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0046     INT002       Arabic                        كيف يُصنَّف Nile Pearl Hotel من حيث مستوى النجوم؟
      0.857    FAQ0333     INT004       Arabic                متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0108     INT004       Arabic      متى يبدأ موعد تسجيل الوصول المعتاد للضيوف في فندق Nile Pearl Hotel؟
      0.844    FAQ0336     INT004      Russian   Во сколько обычно начинается регистрация заезда в Nile Pearl Hotel?    FAQ0123     INT004      Russian          В какое время начинается регистрация заезда в Nile Pearl Hotel?
      0.832    FAQ0333     INT004       Arabic                متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0111     INT004       Arabic            هل يمكنني معرفة وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟
      0.830    FAQ0334     INT004      English     When does the standard check-in period begin at Nile Pearl Hotel?    FAQ0097     INT004      English At what time does the standard guest check-in begin at Nile Pearl Hotel?
      0.826    FAQ0333     INT004       Arabic                متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0140     INT005       Arabic                متى تنتهي فترة تسجيل الخروج المعتادة في Nile Pearl Hotel؟
      0.819    FAQ0338     INT005      English What is the usual latest time to vacate the room at Nile Pearl Hotel?    FAQ0132     INT005      English             What is the latest time I can check out at Nile Pearl Hotel?

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent pairs >= 0.80: 7
 similarity new_faq_id new_intent new_language                                                          new_question old_faq_id old_intent old_language                                                             old_question
      0.860    FAQ0325     INT002       Arabic                كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0043     INT002       Arabic                         كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
      0.860    FAQ0325     INT002       Arabic                كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0046     INT002       Arabic                        كيف يُصنَّف Nile Pearl Hotel من حيث مستوى النجوم؟
      0.857    FAQ0333     INT004       Arabic                متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0108     INT004       Arabic      متى يبدأ موعد تسجيل الوصول المعتاد للضيوف في فندق Nile Pearl Hotel؟
      0.844    FAQ0336     INT004      Russian   Во сколько обычно начинается регистрация заезда в Nile Pearl Hotel?    FAQ0123     INT004      Russian          В какое время начинается регистрация заезда в Nile Pearl Hotel?
      0.832    FAQ0333     INT004       Arabic                متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0111     INT004       Arabic            هل يمكنني معرفة وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟
      0.830    FAQ0334     INT004      English     When does the standard check-in period begin at Nile Pearl Hotel?    FAQ0097     INT004      English At what time does the standard guest check-in begin at Nile Pearl Hotel?
      0.819    FAQ0338     INT005      English What is the usual latest time to vacate the room at Nile Pearl Hotel?    FAQ0132     INT005      English             What is the latest time I can check out at Nile Pearl Hotel?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Cross-intent pairs >= 0.80: 1
 similarity new_faq_id new_intent new_language                                           new_question old_faq_id old_intent old_language                                              old_question
      0.826    FAQ0333     INT004       Arabic متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0140     INT005       Arabic متى تنتهي فترة تسجيل الخروج المعتادة في Nile Pearl Hotel؟

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 3
 similarity new_faq_id new_intent new_language                                           new_question old_faq_id old_intent old_language                                                        old_question
      0.860    FAQ0325     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0043     INT002       Arabic                    كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
      0.860    FAQ0325     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel من حيث المستوى الفندقي؟    FAQ0046     INT002       Arabic                   كيف يُصنَّف Nile Pearl Hotel من حيث مستوى النجوم؟
      0.857    FAQ0333     INT004       Arabic متى يبدأ وقت تسجيل الوصول المعتاد في Nile Pearl Hotel؟    FAQ0108     INT004       Arabic متى يبدأ موعد تسجيل الوصول المعتاد للضيوف في فندق Nile Pearl Hotel؟

====================================================================================================
🏆 BATCH 04 SIMILARITY SUMMARY
====================================================================================================

Existing questions          : 320
Batch 04 questions           : 32
Exact overlaps               : 0
Normalized overlaps          : 0
Pairs >= 0.80                : 8
Same-intent pairs >= 0.80    : 7
Cross-intent pairs >= 0.80   : 1
Pairs >= 0.85                : 3

====================================================================================================
🔒 READ-ONLY
====================================================================================================
✅ Existing dataset was NOT modified.
✅ Batch 04 was NOT modified.
✅ No rows added.
✅ No rows deleted.

====================================================================================================
🎉 BATCH 04 CHECK COMPLETE
====================================================================================================

In [36]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 SIMILARITY REPAIR
# READ-ONLY AGAINST FINAL DATASET
# MODIFIES BATCH 04 ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 SIMILARITY REPAIR")
print("=" * 100)

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

assert BATCH_FILE.exists(), "❌ Batch 04 not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(batch_df) == 32
assert len(df) == 320

# ============================================================
# REWRITES
# ============================================================

rewrites = {

    # INT002 Arabic
    "FAQ0325":
        "ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟",

    # INT004 Arabic
    "FAQ0333":
        "في أي ساعة يمكن للنزلاء بدء إجراءات الوصول إلى Nile Pearl Hotel؟",

    # INT004 Russian
    "FAQ0336":
        "С какого часа гостям разрешается заселение в Nile Pearl Hotel?",

    # INT004 English
    "FAQ0334":
        "What time are guests first permitted to check in at Nile Pearl Hotel?",

    # INT005 English
    "FAQ0338":
        "By what time should I have completed my departure from Nile Pearl Hotel?",

    # Cross-intent protection / stronger distinction
    "FAQ0326":
        "What hotel classification does Nile Pearl Hotel have?",
}

# ============================================================
# APPLY
# ============================================================

print("\n" + "=" * 100)
print("✍️ APPLYING REWRITES")
print("=" * 100)

for faq_id, new_question in rewrites.items():

    idx = batch_df.index[
        batch_df["faq_id"] == faq_id
    ].tolist()

    assert len(idx) == 1, (
        f"❌ {faq_id} not found exactly once."
    )

    idx = idx[0]

    old_question = batch_df.at[
        idx,
        "question"
    ]

    batch_df.at[
        idx,
        "question"
    ] = new_question

    print(f"\n🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# DUPLICATES INSIDE BATCH
# ============================================================

batch_normalized = batch_df["question"].map(
    normalize
)

assert not batch_df["question"].duplicated().any(), (
    "❌ Exact duplicate inside Batch 04."
)

assert not batch_normalized.duplicated().any(), (
    "❌ Normalized duplicate inside Batch 04."
)

# ============================================================
# OVERLAP WITH EXISTING DATASET
# ============================================================

existing_normalized = set(
    df["question"].map(normalize)
)

overlap = [
    q for q in batch_normalized
    if q in existing_normalized
]

assert not overlap, (
    f"❌ Batch 04 overlaps with existing 320:\n{overlap}"
)

print("\n✅ No duplicate/normalized overlap with existing 320.")

# ============================================================
# SAVE BATCH
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 04 UPDATED")
print("=" * 100)

print(f"📄 {BATCH_FILE}")
print(f"✅ Rows preserved: {len(batch_df)}")
print("✅ hotel_faq_final.csv was NOT modified.")

print("\n" + "=" * 100)
print("🎉 BATCH 04 SIMILARITY REPAIR COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 SIMILARITY REPAIR
====================================================================================================

====================================================================================================
✍️ APPLYING REWRITES
====================================================================================================

🔄 FAQ0325
OLD: ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟
NEW: ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟

🔄 FAQ0333
OLD: في أي ساعة يمكن للنزلاء بدء إجراءات الوصول إلى Nile Pearl Hotel؟
NEW: في أي ساعة يمكن للنزلاء بدء إجراءات الوصول إلى Nile Pearl Hotel؟

🔄 FAQ0336
OLD: С какого часа гостям разрешается заселение в Nile Pearl Hotel?
NEW: С какого часа гостям разрешается заселение в Nile Pearl Hotel?

🔄 FAQ0334
OLD: What time are guests first permitted to check in at Nile Pearl Hotel?
NEW: What time are guests first permitted to check in at Nile Pearl Hotel?

🔄 FAQ0338
OLD: By what time should I have completed my departure from Nile Pearl Hotel?
NEW: By what time should I have completed my departure from Nile Pearl Hotel?

🔄 FAQ0326
OLD: What hotel classification does Nile Pearl Hotel have?
NEW: What hotel classification does Nile Pearl Hotel have?

✅ No duplicate/normalized overlap with existing 320.

====================================================================================================
💾 BATCH 04 UPDATED
====================================================================================================
📄 /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_04.csv
✅ Rows preserved: 32
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🎉 BATCH 04 SIMILARITY REPAIR COMPLETE
====================================================================================================

In [37]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 FINAL SIMILARITY CHECK
# ============================================================
# READ-ONLY
# Existing dataset : 320 questions
# Batch 04         : 32 questions
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 FINAL SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

assert BATCH_FILE.exists(), (
    f"❌ Batch 04 not found:\n{BATCH_FILE}"
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print(f"📄 Existing dataset:\n{FINAL_DATASET}")
print(f"📄 Batch 04:\n{BATCH_FILE}")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset rows : {len(df)}")
print(f"Batch 04 rows         : {len(batch_df)}")

assert len(df) == 320, (
    f"❌ Existing dataset must contain 320 rows, "
    f"found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 04 must contain 32 rows, "
    f"found {len(batch_df)}"
)

print("✅ Existing dataset = 320")
print("✅ Batch 04 = 32")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Existing dataset columns are incorrect."
)

assert list(batch_df.columns) == REQUIRED_COLUMNS, (
    "❌ Batch 04 columns are incorrect."
)

print("\n✅ All 13 columns exist in both files.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 04 FAQ ID CHECK")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(321, 353)
]

actual_batch_ids = batch_df["faq_id"].tolist()

assert actual_batch_ids == expected_batch_ids, (
    "❌ Batch 04 FAQ IDs are incorrect.\n"
    f"Expected first: {expected_batch_ids[:5]}\n"
    f"Actual first  : {actual_batch_ids[:5]}\n"
    f"Expected last : {expected_batch_ids[-5:]}\n"
    f"Actual last  : {actual_batch_ids[-5:]}"
)

assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0321 → FAQ0352.")
print("✅ No duplicate IDs inside Batch 04.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:

    print("❌ Exact overlaps found:")

    for question in exact_overlap:
        print(f"- {question}")

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(
        normalize_question
    )
)

batch_normalized = set(
    batch_df["question"].map(
        normalize_question
    )
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for question in normalized_overlap:
        print(f"- {question}")

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 04")
print("=" * 100)

batch_duplicate_exact = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

batch_normalized_series = (
    batch_df["question"]
    .map(normalize_question)
)

batch_duplicate_normalized = batch_df[
    batch_normalized_series.duplicated(
        keep=False
    )
]

if batch_duplicate_exact.empty:

    print("✅ No exact duplicates inside Batch 04.")

else:

    print("❌ Exact duplicates inside Batch 04:")
    print(
        batch_duplicate_exact[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

if batch_duplicate_normalized.empty:

    print(
        "✅ No normalized duplicates inside Batch 04."
    )

else:

    print(
        "❌ Normalized duplicates inside Batch 04:"
    )

    print(
        batch_duplicate_normalized[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. PAIRWISE SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize_question(
                new_row["question"]
            ),
            normalize_question(
                old_row["question"]
            )
        ).ratio()

        # Collect >= 0.80
        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print(
        "🎉 No pairs with similarity >= 0.80."
    )

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"Pairs with similarity >= 0.80: "
        f"{len(similarity_df)}"
    )

    print("\nTOP SIMILAR PAIRS:")
    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 10. SIMILARITY THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [0.80, 0.85, 0.90, 0.95]:

    if similarity_df.empty:

        count = 0

    else:

        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME-INTENT
# ============================================================

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ].copy()

print(
    f"Same-intent pairs >= 0.80: "
    f"{len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 12. CROSS-INTENT
# ============================================================

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ].copy()

print(
    f"Cross-intent pairs >= 0.80: "
    f"{len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 13. SAME-LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 SAME-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_language = pd.DataFrame()

else:

    same_language = similarity_df[
        similarity_df["new_language"]
        ==
        similarity_df["old_language"]
    ].copy()

print(
    f"Same-language pairs >= 0.80: "
    f"{len(same_language)}"
)

# ============================================================
# 14. CROSS-LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌐 CROSS-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_language = pd.DataFrame()

else:

    cross_language = similarity_df[
        similarity_df["new_language"]
        !=
        similarity_df["old_language"]
    ].copy()

print(
    f"Cross-language pairs >= 0.80: "
    f"{len(cross_language)}"
)

# ============================================================
# 15. HIGH SIMILARITY REVIEW
# ============================================================

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ].copy()

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(
            index=False
        )
    )

# ============================================================
# 16. VERY HIGH SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    very_high = pd.DataFrame()

else:

    very_high = similarity_df[
        similarity_df["similarity"] >= 0.90
    ].copy()

print(
    f"Similarity >= 0.90: "
    f"{len(very_high)}"
)

if not very_high.empty:

    print(
        very_high.to_string(
            index=False
        )
    )
else:

    print("✅ No similarity >= 0.90.")

# ============================================================
# 17. EXTREME SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    extreme = pd.DataFrame()

else:

    extreme = similarity_df[
        similarity_df["similarity"] >= 0.95
    ].copy()

print(
    f"Similarity >= 0.95: "
    f"{len(extreme)}"
)

if not extreme.empty:

    print(
        extreme.to_string(
            index=False
        )
    )

else:

    print("✅ No similarity >= 0.95.")

# ============================================================
# 18. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 04 FINAL SIMILARITY SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions            : 320
Batch 04 questions             : 32

Exact overlaps                 : {len(exact_overlap)}
Normalized overlaps            : {len(normalized_overlap)}

Pairs >= 0.80                  : {len(similarity_df)}
Same-intent >= 0.80            : {len(same_intent)}
Cross-intent >= 0.80           : {len(cross_intent)}

Pairs >= 0.85                  : {len(high_similarity)}
Pairs >= 0.90                  : {len(very_high)}
Pairs >= 0.95                  : {len(extreme)}
"""
)

# ============================================================
# 19. DECISION
# ============================================================

print("=" * 100)
print("🏁 BATCH 04 DECISION")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and batch_duplicate_exact.empty
    and batch_duplicate_normalized.empty
    and len(high_similarity) == 0
    and len(cross_intent) == 0
):

    print("""
🟢 BATCH 04 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 04
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
""")

else:

    print("""
🟡 BATCH 04 STILL NEEDS REVIEW

⚠️ One or more similarity/duplicate checks
still require attention.
""")

# ============================================================
# 20. READ-ONLY CONFIRMATION
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_04.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 04 FINAL CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 FINAL SIMILARITY CHECK
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
📄 Existing dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📄 Batch 04:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_04.csv

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset rows : 320
Batch 04 rows         : 32
✅ Existing dataset = 320
✅ Batch 04 = 32

✅ All 13 columns exist in both files.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 04 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0321 → FAQ0352.
✅ No duplicate IDs inside Batch 04.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 04
====================================================================================================
✅ No exact duplicates inside Batch 04.
✅ No normalized duplicates inside Batch 04.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs with similarity >= 0.80: 2

TOP SIMILAR PAIRS:
 similarity new_faq_id new_intent new_language                                          new_question old_faq_id old_intent old_language                                     old_question
        0.8    FAQ0325     INT002       Arabic          ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟    FAQ0043     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
        0.8    FAQ0326     INT002      English What hotel classification does Nile Pearl Hotel have?    FAQ0034     INT002      English     What star rating does Nile Pearl Hotel have?

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 2 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent pairs >= 0.80: 2
 similarity new_faq_id new_intent new_language                                          new_question old_faq_id old_intent old_language                                     old_question
        0.8    FAQ0325     INT002       Arabic          ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟    FAQ0043     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
        0.8    FAQ0326     INT002      English What hotel classification does Nile Pearl Hotel have?    FAQ0034     INT002      English     What star rating does Nile Pearl Hotel have?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Cross-intent pairs >= 0.80: 0

====================================================================================================
🌍 SAME-LANGUAGE SIMILARITY
====================================================================================================
Same-language pairs >= 0.80: 2

====================================================================================================
🌐 CROSS-LANGUAGE SIMILARITY
====================================================================================================
Cross-language pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 0
✅ No similarity >= 0.90.

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 0
✅ No similarity >= 0.95.

====================================================================================================
🏆 BATCH 04 FINAL SIMILARITY SUMMARY
====================================================================================================

Existing questions            : 320
Batch 04 questions             : 32

Exact overlaps                 : 0
Normalized overlaps            : 0

Pairs >= 0.80                  : 2
Same-intent >= 0.80            : 2
Cross-intent >= 0.80           : 0

Pairs >= 0.85                  : 0
Pairs >= 0.90                  : 0
Pairs >= 0.95                  : 0

====================================================================================================
🏁 BATCH 04 DECISION
====================================================================================================

🟢 BATCH 04 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 04
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_04.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 04 FINAL CHECK COMPLETE
====================================================================================================

In [38]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 REPAIR
# GROUND TRUTH + ANSWER + FULL BATCH VALIDATION
# ============================================================
# IMPORTANT:
# - Modifies BATCH 04 only
# - Does NOT modify hotel_faq_final.csv
# - Uses existing dataset knowledge as the source of truth
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 REPAIR + FINAL VALIDATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

assert BATCH_FILE.exists(), (
    f"❌ Batch 04 not found:\n{BATCH_FILE}"
)

print("✅ Project root found.")
print("✅ Final dataset found.")
print("✅ Batch 04 found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 04         : {len(batch_df)} rows")

assert len(df) == 320
assert len(batch_df) == 32

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. INTENT MAP
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

VALID_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

# ============================================================
# 5. FAQ ID VALIDATION
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(321, 353)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

print("✅ IDs are exactly FAQ0321 → FAQ0352.")
print("✅ No duplicate IDs.")

# ============================================================
# 6. NORMALIZATION
# ============================================================

def normalize_text(text):
    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


def normalize_question(text):
    text = normalize_text(text)

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 7. CHECK BATCH QUESTION OVERLAP
# ============================================================

existing_questions = set(
    df["question"]
    .map(normalize_question)
)

batch_questions = batch_df["question"].map(
    normalize_question
)

assert not batch_questions.duplicated().any()

overlap = [
    q for q in batch_questions
    if q in existing_questions
]

assert not overlap, (
    f"❌ Batch 04 contains questions already in "
    f"the existing dataset:\n{overlap}"
)

print("\n" + "=" * 100)
print("📝 QUESTION OVERLAP")
print("=" * 100)

print("✅ No duplicate questions inside Batch 04.")
print("✅ No normalized overlap with existing 320.")

# ============================================================
# 8. BUILD CANONICAL KNOWLEDGE MAP
# ============================================================
# We extract a canonical answer for every
# Intent × Language from the existing dataset.
#
# Priority:
# 1. Existing non-empty ground_truth
# 2. Existing non-empty answer
#
# We choose the most frequent normalized ground_truth
# within each Intent × Language.

print("\n" + "=" * 100)
print("🧠 BUILDING CANONICAL KNOWLEDGE MAP")
print("=" * 100)

knowledge_map = {}

for intent_id, intent_name in INTENTS.items():

    for language in VALID_LANGUAGES:

        subset = df[
            (df["intent_id"] == intent_id)
            &
            (df["language"] == language)
        ].copy()

        assert len(subset) == 10, (
            f"❌ Expected 10 rows for "
            f"{intent_id} × {language}, "
            f"found {len(subset)}"
        )

        # Ground truth candidates
        gt_values = (
            subset["ground_truth"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        gt_values = gt_values[
            gt_values.ne("")
        ]

        assert not gt_values.empty, (
            f"❌ No ground truth available for "
            f"{intent_id} × {language}"
        )

        # Most common exact ground truth
        canonical_gt = (
            gt_values
            .value_counts()
            .index[0]
        )

        # Answer fallback
        answer_values = (
            subset["answer"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        answer_values = answer_values[
            answer_values.ne("")
        ]

        assert not answer_values.empty, (
            f"❌ No answer available for "
            f"{intent_id} × {language}"
        )

        canonical_answer = (
            answer_values
            .value_counts()
            .index[0]
        )

        knowledge_map[
            (intent_id, language)
        ] = {
            "ground_truth": canonical_gt,
            "answer": canonical_answer,
        }

        print(
            f"✅ {intent_id:<6} "
            f"{language:<8}"
        )

print("✅ Canonical knowledge map created.")

# ============================================================
# 9. APPLY GROUND TRUTH + ANSWER
# ============================================================

print("\n" + "=" * 100)
print("✍️ APPLYING GROUND TRUTH + ANSWERS")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(
        row["intent_id"]
    ).strip()

    language = str(
        row["language"]
    ).strip()

    assert intent_id in INTENTS, (
        f"❌ Unknown intent: {intent_id}"
    )

    assert language in VALID_LANGUAGES, (
        f"❌ Unknown language: {language}"
    )

    source_knowledge = knowledge_map[
        (intent_id, language)
    ]

    batch_df.at[
        idx,
        "ground_truth"
    ] = source_knowledge["ground_truth"]

    batch_df.at[
        idx,
        "answer"
    ] = source_knowledge["answer"]

    batch_df.at[
        idx,
        "status"
    ] = "generated"

    batch_df.at[
        idx,
        "category"
    ] = "Hotel FAQ"

    batch_df.at[
        idx,
        "source"
    ] = "Generated Batch 04"

    batch_df.at[
        idx,
        "attempts"
    ] = 0

    batch_df.at[
        idx,
        "difficulty"
    ] = "Easy"

print("✅ Ground truth filled for all 32.")
print("✅ Answers filled for all 32.")

# ============================================================
# 10. REQUIRED FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 11. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

expected_language_counts = {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

assert (
    language_counts.to_dict()
    == expected_language_counts
)

print("✅ 8 × 4 languages.")

# ============================================================
# 12. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

expected_intent_counts = {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

assert (
    intent_counts.to_dict()
    == expected_intent_counts
)

print("✅ 4 × 8 intents.")

# ============================================================
# 13. INTENT NAME
# ============================================================

for _, row in batch_df.iterrows():

    expected_name = INTENTS[
        row["intent_id"]
    ]

    assert row["intent_name"] == expected_name

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 14. QUESTION TYPES
# ============================================================

invalid_types = (
    set(batch_df["question_type"])
    - VALID_QUESTION_TYPES
)

assert not invalid_types

print("\n" + "=" * 100)
print("📝 QUESTION TYPES")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 15. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 16. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 04 SAVED")
print("=" * 100)

print(BATCH_FILE)
print("✅ hotel_faq_final.csv was NOT modified.")

# ============================================================
# 17. FINAL BATCH RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 04 REPAIR RESULT")
print("=" * 100)

print("""
🟢 BATCH 04 IS COMPLETE

✅ 32 questions
✅ FAQ0321 → FAQ0352
✅ Ground truth complete
✅ Answers complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Required fields complete
✅ Intent mapping correct
✅ Question types valid
✅ No duplicate questions
✅ No overlap with existing 320

⚠️ hotel_faq_final.csv was NOT modified.

🎉 SAFE FOR FINAL BATCH 04 VALIDATION
""")

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 REPAIR + FINAL VALIDATION
====================================================================================================
✅ Project root found.
✅ Final dataset found.
✅ Batch 04 found.

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 320 rows
Batch 04         : 32 rows
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0321 → FAQ0352.
✅ No duplicate IDs.

====================================================================================================
📝 QUESTION OVERLAP
====================================================================================================
✅ No duplicate questions inside Batch 04.
✅ No normalized overlap with existing 320.

====================================================================================================
🧠 BUILDING CANONICAL KNOWLEDGE MAP
====================================================================================================
✅ INT001 Russian
✅ INT001 English
✅ INT001 French
✅ INT001 Arabic
✅ INT002 Russian
✅ INT002 English
✅ INT002 French
✅ INT002 Arabic
✅ INT003 Russian
✅ INT003 English
✅ INT003 French
✅ INT003 Arabic
✅ INT004 Russian
✅ INT004 English
✅ INT004 French
✅ INT004 Arabic
✅ INT005 Russian
✅ INT005 English
✅ INT005 French
✅ INT005 Arabic
✅ INT006 Russian
✅ INT006 English
✅ INT006 French
✅ INT006 Arabic
✅ INT007 Russian
✅ INT007 English
✅ INT007 French
✅ INT007 Arabic
✅ INT008 Russian
✅ INT008 English
✅ INT008 French
✅ INT008 Arabic
✅ Canonical knowledge map created.

====================================================================================================
✍️ APPLYING GROUND TRUTH + ANSWERS
====================================================================================================
✅ Ground truth filled for all 32.
✅ Answers filled for all 32.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPES
====================================================================================================
question_type
Paraphrased    16
Direct         12
Scenario        4
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
💾 BATCH 04 SAVED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_04.csv
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🏆 BATCH 04 REPAIR RESULT
====================================================================================================

🟢 BATCH 04 IS COMPLETE

✅ 32 questions
✅ FAQ0321 → FAQ0352
✅ Ground truth complete
✅ Answers complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Required fields complete
✅ Intent mapping correct
✅ Question types valid
✅ No duplicate questions
✅ No overlap with existing 320

⚠️ hotel_faq_final.csv was NOT modified.

🎉 SAFE FOR FINAL BATCH 04 VALIDATION

====================================================================================================

/var/folders/3j/_3bjs5gd14318wgzhfc9xhth0000gn/T/ipykernel_47090/2393029070.py:354: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Nile Pearl Hotel is located in Cairo, Egypt.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_df.at[
/var/folders/3j/_3bjs5gd14318wgzhfc9xhth0000gn/T/ipykernel_47090/2393029070.py:359: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'يقع فندق Nile Pearl Hotel في القاهرة، مصر.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_df.at[

In [39]:
# ============================================================
# 🏨 HOTEL AI - BATCH 04 FINAL CHECK
# GROUND TRUTH + ANSWER + DUPLICATE + SIMILARITY
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - BATCH 04 FINAL CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 04 not found."

df = pd.read_csv(FINAL_DATASET, encoding="utf-8-sig")
batch_df = pd.read_csv(BATCH_FILE, encoding="utf-8-sig")

# ============================================================
# 2. BASIC FILE CHECK
# ============================================================

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)}")
print(f"Batch 04         : {len(batch_df)}")

assert len(df) == 320
assert len(batch_df) == 32

print("✅ Existing dataset = 320")
print("✅ Batch 04 = 32")

# ============================================================
# 3. COLUMN CHECK
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order correct.")

# ============================================================
# 4. ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(321, 353)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs: FAQ0321 → FAQ0352")
print("✅ No duplicate IDs.")

# ============================================================
# 5. REQUIRED FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD CHECK")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(batch_df[col].isna().sum())

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f" Missing: {missing:<3}"
        f" Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 6. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 7. DUPLICATE CHECK INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH DUPLICATE CHECK")
print("=" * 100)

assert not batch_df["question"].duplicated().any()

batch_norm = batch_df["question"].map(normalize)

assert not batch_norm.duplicated().any()

print("✅ No exact duplicates inside Batch 04.")
print("✅ No normalized duplicates inside Batch 04.")

# ============================================================
# 8. OVERLAP AGAINST 320
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP WITH EXISTING 320")
print("=" * 100)

existing_norm = set(
    df["question"].map(normalize)
)

overlap = [
    q for q in batch_norm
    if q in existing_norm
]

assert not overlap, (
    f"❌ Overlap found:\n{overlap}"
)

print("✅ No exact/normalized overlap with existing 320.")

# ============================================================
# 9. LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE CHECK")
print("=" * 100)

language_counts = batch_df["language"].value_counts()

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 × 4 languages.")

# ============================================================
# 10. INTENT
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT CHECK")
print("=" * 100)

intent_counts = batch_df["intent_id"].value_counts()

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 × 8 intents.")

# ============================================================
# 11. INTENT NAME
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for _, row in batch_df.iterrows():

    assert row["intent_name"] == INTENTS[row["intent_id"]]

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 12. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert (
    set(batch_df["question_type"])
    <= VALID_TYPES
)

print("\n" + "=" * 100)
print("📝 QUESTION TYPE CHECK")
print("=" * 100)

print(batch_df["question_type"].value_counts())
print("✅ All question types valid.")

# ============================================================
# 13. GROUND TRUTH + ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER CHECK")
print("=" * 100)

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 14. FULL SIMILARITY AGAINST 320
# ============================================================

print("\n" + "=" * 100)
print("🔍 BATCH 04 vs EXISTING 320 SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),
                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],
                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("✅ No pairs >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df.to_string(index=False)
    )

# ============================================================
# 15. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [0.80, 0.85, 0.90, 0.95]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count}"
    )

# ============================================================
# 16. SAME INTENT
# ============================================================

if similarity_df.empty:
    same_intent = pd.DataFrame()
else:
    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80: {len(same_intent)}"
)

if not same_intent.empty:
    print(
        same_intent.to_string(index=False)
    )

# ============================================================
# 17. CROSS INTENT
# ============================================================

if similarity_df.empty:
    cross_intent = pd.DataFrame()
else:
    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80: {len(cross_intent)}"
)

if not cross_intent.empty:
    print(
        cross_intent.to_string(index=False)
    )

# ============================================================
# 18. FINAL DECISION
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🏆 BATCH 04 FINAL RESULT")
print("=" * 100)

if (
    len(overlap) == 0
    and high_similarity.empty
    and cross_intent.empty
    and not batch_df["question"].duplicated().any()
    and not batch_norm.duplicated().any()
):

    print("""
🟢 BATCH 04 IS FULLY VALID

✅ 32 questions
✅ FAQ0321 → FAQ0352
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balanced
✅ Intent balanced
✅ Intent mapping correct
✅ Question types valid

🎉 SAFE TO MERGE BATCH 04
""")

else:

    print("""
🟡 BATCH 04 STILL NEEDS REVIEW
""")

# ============================================================
# 19. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_04.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 04 FINAL CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 04 FINAL CHECK
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 320
Batch 04         : 32
✅ Existing dataset = 320
✅ Batch 04 = 32
✅ All 13 columns exist.
✅ Column order correct.

====================================================================================================
🆔 FAQ ID CHECK
====================================================================================================
✅ IDs: FAQ0321 → FAQ0352
✅ No duplicate IDs.

====================================================================================================
🧪 REQUIRED FIELD CHECK
====================================================================================================
✅ faq_id          Missing: 0   Empty: 0
✅ intent_id       Missing: 0   Empty: 0
✅ language        Missing: 0   Empty: 0
✅ question_type   Missing: 0   Empty: 0
✅ question        Missing: 0   Empty: 0
✅ status          Missing: 0   Empty: 0
✅ intent_name     Missing: 0   Empty: 0
✅ ground_truth    Missing: 0   Empty: 0
✅ category        Missing: 0   Empty: 0
✅ source          Missing: 0   Empty: 0
✅ attempts        Missing: 0   Empty: 0
✅ difficulty      Missing: 0   Empty: 0
✅ answer          Missing: 0   Empty: 0
✅ All required fields complete.

====================================================================================================
📝 BATCH DUPLICATE CHECK
====================================================================================================
✅ No exact duplicates inside Batch 04.
✅ No normalized duplicates inside Batch 04.

====================================================================================================
🔎 OVERLAP WITH EXISTING 320
====================================================================================================
✅ No exact/normalized overlap with existing 320.

====================================================================================================
🌍 LANGUAGE CHECK
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 × 4 languages.

====================================================================================================
🎯 INTENT CHECK
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE CHECK
====================================================================================================
question_type
Paraphrased    16
Direct         12
Scenario        4
Name: count, dtype: int64
✅ All question types valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER CHECK
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🔍 BATCH 04 vs EXISTING 320 SIMILARITY
====================================================================================================
Pairs >= 0.80: 2
 similarity new_faq_id new_intent new_language                                          new_question old_faq_id old_intent old_language                                     old_question
        0.8    FAQ0325     INT002       Arabic          ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟    FAQ0043     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
        0.8    FAQ0326     INT002      English What hotel classification does Nile Pearl Hotel have?    FAQ0034     INT002      English     What star rating does Nile Pearl Hotel have?

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 2
0.85+ : 0
0.90+ : 0
0.95+ : 0

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80: 2
 similarity new_faq_id new_intent new_language                                          new_question old_faq_id old_intent old_language                                     old_question
        0.8    FAQ0325     INT002       Arabic          ما فئة Nile Pearl Hotel ضمن تصنيفات الفنادق؟    FAQ0043     INT002       Arabic كيف يتم تصنيف Nile Pearl Hotel ضمن فئات الفنادق؟
        0.8    FAQ0326     INT002      English What hotel classification does Nile Pearl Hotel have?    FAQ0034     INT002      English     What star rating does Nile Pearl Hotel have?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80: 0

====================================================================================================
🏆 BATCH 04 FINAL RESULT
====================================================================================================

🟢 BATCH 04 IS FULLY VALID

✅ 32 questions
✅ FAQ0321 → FAQ0352
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balanced
✅ Intent balanced
✅ Intent mapping correct
✅ Question types valid

🎉 SAFE TO MERGE BATCH 04

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_04.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 04 FINAL CHECK COMPLETE
====================================================================================================

In [40]:
# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 04
# 320 + 32 = 352
# ============================================================

from pathlib import Path
from datetime import datetime
import pandas as pd

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_04.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 04")
print("=" * 100)

# ------------------------------------------------------------
# 1. LOAD
# ------------------------------------------------------------

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 320
assert len(batch_df) == 32

print(f"Current dataset : {len(df)}")
print(f"Batch 04        : {len(batch_df)}")

# ------------------------------------------------------------
# 2. BACKUP
# ------------------------------------------------------------

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_batch04_{timestamp}.csv"
)

df.to_csv(
    backup_path,
    index=False,
    encoding="utf-8-sig"
)

print(f"💾 Backup created:\n{backup_path}")

# ------------------------------------------------------------
# 3. SAFETY CHECK - IDS
# ------------------------------------------------------------

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(321, 353)
]

assert batch_df["faq_id"].tolist() == expected_batch_ids
assert batch_df["faq_id"].is_unique

existing_ids = set(df["faq_id"])
batch_ids = set(batch_df["faq_id"])

assert not existing_ids.intersection(batch_ids)

print("✅ No FAQ ID overlap.")

# ------------------------------------------------------------
# 4. SAFETY CHECK - QUESTIONS
# ------------------------------------------------------------

def normalize_question(text):
    return (
        str(text)
        .casefold()
        .strip()
    )

existing_questions = set(
    df["question"].map(normalize_question)
)

batch_questions = set(
    batch_df["question"].map(normalize_question)
)

assert not existing_questions.intersection(
    batch_questions
)

assert not batch_df["question"].duplicated().any()

print("✅ No question overlap.")
print("✅ No duplicate questions inside Batch 04.")

# ------------------------------------------------------------
# 5. FIX DTYPE WARNING BEFORE CONCAT
# ------------------------------------------------------------

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:
    df[col] = df[col].astype("string")
    batch_df[col] = batch_df[col].astype("string")

# attempts numeric
df["attempts"] = pd.to_numeric(
    df["attempts"],
    errors="raise"
)

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ------------------------------------------------------------
# 6. MERGE
# ------------------------------------------------------------

merged_df = pd.concat(
    [df, batch_df],
    ignore_index=True
)

# ------------------------------------------------------------
# 7. FINAL ID CHECK
# ------------------------------------------------------------

expected_final_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 353)
]

assert merged_df["faq_id"].tolist() == expected_final_ids

assert merged_df["faq_id"].is_unique

# ------------------------------------------------------------
# 8. FINAL QUESTION CHECK
# ------------------------------------------------------------

assert not merged_df["question"].duplicated().any()

normalized_final = (
    merged_df["question"]
    .map(normalize_question)
)

assert not normalized_final.duplicated().any()

# ------------------------------------------------------------
# 9. FINAL ROW COUNT
# ------------------------------------------------------------

assert len(merged_df) == 352

# ------------------------------------------------------------
# 10. SAVE
# ------------------------------------------------------------

merged_df.to_csv(
    FINAL_DATASET,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 FINAL DATASET UPDATED")
print("=" * 100)

print(FINAL_DATASET)

# ------------------------------------------------------------
# 11. RELOAD VALIDATION
# ------------------------------------------------------------

check_df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(check_df) == 352

assert check_df["faq_id"].tolist() == expected_final_ids

assert check_df["faq_id"].is_unique

assert not check_df["question"].duplicated().any()

print("\n" + "=" * 100)
print("🏆 MERGE RESULT")
print("=" * 100)

print("""
🟢 BATCH 04 MERGED SUCCESSFULLY

Previous dataset : 320
Added questions  : 32
Final dataset    : 352

IDs:
FAQ0001 → FAQ0352

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully
""")

print(f"🔒 Backup:\n{backup_path}")

print("=" * 100)
print("🎉 MERGE COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 04
====================================================================================================
Current dataset : 320
Batch 04        : 32
💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch04_20260821_151914.csv
✅ No FAQ ID overlap.
✅ No question overlap.
✅ No duplicate questions inside Batch 04.

====================================================================================================
💾 FINAL DATASET UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 MERGE RESULT
====================================================================================================

🟢 BATCH 04 MERGED SUCCESSFULLY

Previous dataset : 320
Added questions  : 32
Final dataset    : 352

IDs:
FAQ0001 → FAQ0352

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch04_20260821_151914.csv
====================================================================================================
🎉 MERGE COMPLETE
====================================================================================================

In [41]:
# ============================================================
# 🏨 HOTEL AI - FULL DATASET QUALITY + SIMILARITY CHECK
# VERSION: 352 QUESTIONS
# READ-ONLY — DOES NOT MODIFY THE DATASET
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

# ============================================================
# 1. CONFIG
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 352

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

STATUS_VALUES = {
    "valid",
    "generated",
}

DIFFICULTY_VALUES = {
    "Easy",
}

print("=" * 100)
print("🏨 HOTEL AI - FULL DATASET QUALITY + SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 2. PATH
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

print("\n📂 Project root:")
print(PROJECT_ROOT)

print("\n📄 Dataset:")
print(DATASET_PATH)

print("\n✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# 3. LOAD
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 4. COLUMN CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 COLUMN VALIDATION")
print("=" * 100)

missing_columns = [
    c for c in REQUIRED_COLUMNS
    if c not in df.columns
]

extra_columns = [
    c for c in df.columns
    if c not in REQUIRED_COLUMNS
]

assert not missing_columns, (
    f"❌ Missing columns: {missing_columns}"
)

assert not extra_columns, (
    f"❌ Unexpected columns: {extra_columns}"
)

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Column order is incorrect."
)

print("✅ All 13 required columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 5. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 ROW COUNT")
print("=" * 100)

assert len(df) == EXPECTED_ROWS, (
    f"❌ Expected {EXPECTED_ROWS}, found {len(df)}"
)

print(f"✅ Exactly {EXPECTED_ROWS} questions.")

# ============================================================
# 6. REQUIRED FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

required_fields_ok = True

for col in REQUIRED_COLUMNS:

    missing = int(df[col].isna().sum())

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if missing > 0 or empty > 0:
        required_fields_ok = False

assert required_fields_ok, (
    "❌ Required fields contain missing or empty values."
)

print("\n✅ All required fields complete.")

# ============================================================
# 7. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

valid_id_mask = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
)

invalid_ids = df[~valid_id_mask]

assert invalid_ids.empty, (
    f"❌ Invalid FAQ IDs:\n"
    f"{invalid_ids[['faq_id']]}"
)

print("✅ All FAQ IDs have valid format.")

# ============================================================
# 8. DUPLICATE IDS
# ============================================================

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

assert duplicate_ids.empty, (
    f"❌ Duplicate FAQ IDs:\n"
    f"{duplicate_ids[['faq_id']]}"
)

print("✅ No duplicate FAQ IDs.")

# ============================================================
# 9. ID CONTINUITY
# ============================================================

print("\n" + "=" * 100)
print("🔢 FAQ ID CONTINUITY")
print("=" * 100)

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

expected_numeric_ids = list(
    range(1, EXPECTED_ROWS + 1)
)

assert numeric_ids.tolist() == expected_numeric_ids, (
    "❌ FAQ IDs are not continuous or ordered."
)

print(
    f"✅ FAQ0001 → FAQ{EXPECTED_ROWS:04d}"
)
print("✅ IDs are continuous and correctly ordered.")

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 11. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 12. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized_question"].duplicated(keep=False)
]

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 13. SAME INTENT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized_question"
        ],
        keep=False
    )
]

if same_intent_duplicates.empty:

    print(
        "✅ No normalized duplicates "
        "inside the same intent."
    )

else:

    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 14. INTENT MAPPING
# ============================================================

print("\n" + "=" * 100)
print("🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_errors = []

for intent_id, intent_name in INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    if len(subset) != 44:
        intent_errors.append(
            f"{intent_id}: expected 44, found {len(subset)}"
        )

    names = set(
        subset["intent_name"]
        .astype(str)
    )

    if names != {intent_name}:
        intent_errors.append(
            f"{intent_id}: expected {intent_name}, found {names}"
        )

unexpected_intents = (
    set(df["intent_id"])
    - set(INTENTS.keys())
)

if unexpected_intents:
    intent_errors.append(
        f"Unexpected intents: {unexpected_intents}"
    )

assert not intent_errors, (
    "❌ Intent validation errors:\n"
    + "\n".join(intent_errors)
)

print("✅ All intent mappings are correct.")
print("✅ 44 questions × 8 intents.")

# ============================================================
# 15. LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = df["language"].value_counts()

print(language_counts.to_string())

assert set(language_counts.index) == LANGUAGES

for language in LANGUAGES:

    count = int(
        language_counts.get(language, 0)
    )

    assert count == 88, (
        f"❌ {language}: expected 88, found {count}"
    )

print("✅ 88 questions × 4 languages.")

# ============================================================
# 16. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(language_intent.to_string())

for intent_id in INTENTS:

    for language in LANGUAGES:

        count = int(
            language_intent.loc[
                intent_id,
                language
            ]
        )

        assert count == 11, (
            f"❌ {intent_id} × {language}: "
            f"expected 11, found {count}"
        )

print(
    "\n✅ Every intent has "
    "11 questions per language."
)

# ============================================================
# 17. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(
    question_type_counts.to_string()
)

unexpected_types = (
    set(df["question_type"])
    - QUESTION_TYPES
)

assert not unexpected_types

print("✅ All question types are valid.")

# ============================================================
# 18. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS DISTRIBUTION")
print("=" * 100)

status_counts = df["status"].value_counts()

print(
    status_counts.to_string()
)

unexpected_status = (
    set(df["status"])
    - STATUS_VALUES
)

assert not unexpected_status

print("✅ Status values are valid.")

# ============================================================
# 19. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)

difficulty_counts = df["difficulty"].value_counts()

print(
    difficulty_counts.to_string()
)

unexpected_difficulty = (
    set(df["difficulty"])
    - DIFFICULTY_VALUES
)

assert not unexpected_difficulty

print("✅ Difficulty values are valid.")

# ============================================================
# 20. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

gt_empty = (
    df["ground_truth"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
)

answer_empty = (
    df["answer"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
)

assert not gt_empty.any(), (
    "❌ Empty ground_truth found."
)

assert not answer_empty.any(), (
    "❌ Empty answer found."
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 21. GROUND TRUTH vs ANSWER DIFFERENCE REPORT
# ============================================================

print("\n" + "=" * 100)
print("🔗 GROUND TRUTH ↔ ANSWER")
print("=" * 100)

gt_norm = (
    df["ground_truth"]
    .map(normalize_text)
)

answer_norm = (
    df["answer"]
    .map(normalize_text)
)

answer_difference = df[
    gt_norm != answer_norm
]

print(
    f"Rows with different wording: "
    f"{len(answer_difference)}"
)

print(
    "ℹ️ Different wording is not automatically an error."
)

# ============================================================
# 22. ATTEMPTS
# ============================================================

print("\n" + "=" * 100)
print("🔢 ATTEMPTS VALIDATION")
print("=" * 100)

attempts = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

assert not attempts.isna().any()
assert (attempts >= 0).all()

print("✅ Attempts are numeric and non-negative.")
print(f"Min    : {attempts.min()}")
print(f"Max    : {attempts.max()}")
print(f"Average: {attempts.mean():.2f}")

# ============================================================
# 23. QUESTION LENGTH
# ============================================================

print("\n" + "=" * 100)
print("📏 QUESTION LENGTH")
print("=" * 100)

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

print(f"Shortest : {question_lengths.min()}")
print(f"Longest  : {question_lengths.max()}")
print(f"Average  : {question_lengths.mean():.2f}")

very_short = df[
    question_lengths < 10
]

if very_short.empty:

    print("✅ No very short questions.")

else:

    print(
        f"⚠️ Very short questions: "
        f"{len(very_short)}"
    )

# ============================================================
# 24. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL QUESTION SIMILARITY CHECK")
print("=" * 100)

questions = df["question"].astype(str).tolist()
faq_ids = df["faq_id"].tolist()
intents = df["intent_id"].tolist()
languages = df["language"].tolist()

total_comparisons = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparisons performed: "
    f"{total_comparisons:,}"
)

similar_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.80:

        similar_pairs.append({
            "similarity": round(score, 3),

            "faq_id_1": faq_ids[i],
            "intent_1": intents[i],
            "language_1": languages[i],
            "question_1": questions[i],

            "faq_id_2": faq_ids[j],
            "intent_2": intents[j],
            "language_2": languages[j],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print(
        "✅ No pairs with similarity >= 0.80."
    )

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"Pairs >= 0.80: "
        f"{len(similarity_df)}"
    )

# ============================================================
# 25. THRESHOLD SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95
]:

    if similarity_df.empty:

        count = 0

    else:

        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 26. TOP SIMILAR QUESTIONS
# ============================================================

print("\n" + "=" * 100)
print("📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:

    print("None.")

else:

    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 27. SAME-INTENT
# ============================================================

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

print(
    f"Same-intent pairs >= 0.80: "
    f"{len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 28. CROSS-INTENT
# ============================================================

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

print(
    f"Cross-intent pairs >= 0.80: "
    f"{len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 29. SAME LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 SAME-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_language = pd.DataFrame()

else:

    same_language = similarity_df[
        similarity_df["language_1"]
        ==
        similarity_df["language_2"]
    ]

print(
    f"Same-language pairs >= 0.80: "
    f"{len(same_language)}"
)

# ============================================================
# 30. CROSS LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌐 CROSS-LANGUAGE SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_language = pd.DataFrame()

else:

    cross_language = similarity_df[
        similarity_df["language_1"]
        !=
        similarity_df["language_2"]
    ]

print(
    f"Cross-language pairs >= 0.80: "
    f"{len(cross_language)}"
)

# ============================================================
# 31. HIGH SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

if high_similarity.empty:

    print(
        "✅ No similarity >= 0.85."
    )

else:

    print(
        f"⚠️ {len(high_similarity)} "
        f"pairs >= 0.85"
    )

    print(
        high_similarity.to_string(
            index=False
        )
    )

# ============================================================
# 32. VERY HIGH
# ============================================================

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    very_high = pd.DataFrame()

else:

    very_high = similarity_df[
        similarity_df["similarity"] >= 0.90
    ]

print(
    f">= 0.90 : {len(very_high)}"
)

if not very_high.empty:

    print(
        very_high.to_string(
            index=False
        )
    )

# ============================================================
# 33. EXTREME
# ============================================================

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    extreme = pd.DataFrame()

else:

    extreme = similarity_df[
        similarity_df["similarity"] >= 0.95
    ]

print(
    f">= 0.95 : {len(extreme)}"
)

if not extreme.empty:

    print(
        extreme.to_string(
            index=False
        )
    )

# ============================================================
# 34. FINAL CHECKS
# ============================================================

structural_pass = all([
    len(df) == EXPECTED_ROWS,
    list(df.columns) == REQUIRED_COLUMNS,
    invalid_ids.empty,
    duplicate_ids.empty,
    numeric_ids.tolist() == expected_numeric_ids,
    required_fields_ok,
    exact_duplicates.empty,
    normalized_duplicates.empty,
    same_intent_duplicates.empty,
    not intent_errors,
    set(language_counts.index) == LANGUAGES,
    all(
        (df["intent_id"] == x).sum() == 44
        for x in INTENTS
    ),
    all(
        language_intent.loc[x, y] == 11
        for x in INTENTS
        for y in LANGUAGES
    ),
    not unexpected_types,
    not unexpected_status,
    not unexpected_difficulty,
    not gt_empty.any(),
    not answer_empty.any(),
    very_short.empty,
])

similarity_pass = (
    similarity_df.empty
    or not (
        similarity_df["similarity"] >= 0.85
    ).any()
)

# ============================================================
# 35. FINAL SCORE
# ============================================================

checks = {
    "352 questions": len(df) == 352,
    "13 columns": len(df.columns) == 13,
    "Valid FAQ IDs": invalid_ids.empty,
    "No duplicate IDs": duplicate_ids.empty,
    "Continuous IDs": numeric_ids.tolist() == expected_numeric_ids,
    "Required fields": required_fields_ok,
    "No exact duplicates": exact_duplicates.empty,
    "No normalized duplicates": normalized_duplicates.empty,
    "No same-intent duplicates": same_intent_duplicates.empty,
    "Intent mappings": not intent_errors,
    "Language balance": all(
        language_counts.get(x, 0) == 88
        for x in LANGUAGES
    ),
    "Intent balance": all(
        (df["intent_id"] == x).sum() == 44
        for x in INTENTS
    ),
    "Language × Intent": all(
        language_intent.loc[x, y] == 11
        for x in INTENTS
        for y in LANGUAGES
    ),
    "Question types": not unexpected_types,
    "Status": not unexpected_status,
    "Difficulty": not unexpected_difficulty,
    "Ground truth": not gt_empty.any(),
    "Answers": not answer_empty.any(),
    "Similarity < 0.85": similarity_pass,
}

passed = sum(checks.values())
total = len(checks)
score = passed / total * 100

print("\n" + "=" * 100)
print("🏆 FINAL DATASET VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

print("-" * 100)
print(f"Passed checks : {passed}/{total}")
print(f"Validation Score : {score:.1f}%")

if score == 100:
    print("🟢 DATASET IS FULLY VALIDATED")
else:
    print("🟡 DATASET NEEDS REVIEW")

# ============================================================
# 36. READ ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 37. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=[
        "_normalized_question"
    ],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 FULL 352-QUESTION CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FULL DATASET QUALITY + SIMILARITY CHECK
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

✅ Project root found.
✅ Dataset found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 352
Columns : 13

====================================================================================================
🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 ROW COUNT
====================================================================================================
✅ Exactly 352 questions.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0

✅ All required fields complete.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.

====================================================================================================
🔢 FAQ ID CONTINUITY
====================================================================================================
✅ FAQ0001 → FAQ0352
✅ IDs are continuous and correctly ordered.

====================================================================================================
📝 EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ All intent mappings are correct.
✅ 44 questions × 8 intents.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    88
Arabic     88
French     88
Russian    88
✅ 88 questions × 4 languages.

====================================================================================================
📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         11       11      11       11
INT002         11       11      11       11
INT003         11       11      11       11
INT004         11       11      11       11
INT005         11       11      11       11
INT006         11       11      11       11
INT007         11       11      11       11
INT008         11       11      11       11

✅ Every intent has 11 questions per language.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    144
Direct         120
Scenario        88
✅ All question types are valid.

====================================================================================================
📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated    128
✅ Status values are valid.

====================================================================================================
📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    352
✅ Difficulty values are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🔗 GROUND TRUTH ↔ ANSWER
====================================================================================================
Rows with different wording: 314
ℹ️ Different wording is not automatically an error.

====================================================================================================
🔢 ATTEMPTS VALIDATION
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 6
Average: 0.38

====================================================================================================
📏 QUESTION LENGTH
====================================================================================================
Shortest : 31
Longest  : 186
Average  : 77.64
✅ No very short questions.

====================================================================================================
🔍 FULL QUESTION SIMILARITY CHECK
====================================================================================================
Comparisons performed: 61,776
Pairs >= 0.80: 26

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 26 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
📋 TOP 30 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1 language_1                                                                                                                              question_1 faq_id_2 intent_2 language_2                                                                                                                                                      question_2
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                                     What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                                                هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                                              هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                                        В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                                               Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.829  FAQ0004   INT001    English                                                                                          In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                                          Where can I find the Nile Pearl Hotel?
      0.828  FAQ0121   INT004    Russian                                                                                              Когда можно заселиться в Nile Pearl Hotel?  FAQ0125   INT004    Russian                                                                                                     Когда стандартно можно заселиться в отель Nile Pearl Hotel?
      0.827  FAQ0235   INT008     Arabic                                                                  هل يجب علي تقديم إثبات هوية ساري عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0237   INT008     Arabic                                                                              هل يحتاج الضيوف إلى تقديم وثائق إثبات الهوية عند تسجيل الوصول في Nile Pearl Hotel?
      0.824  FAQ0066   INT003    English                                                             What are the hours of operation for the reception desk at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.821  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0100   INT004    English                                                                                                    What time is check-in usually available at Nile Pearl Hotel?
      0.818  FAQ0017   INT001     French                                                                                                  Où se trouve l'hôtel Nile Pearl Hotel?  FAQ0019   INT001     French                                                                                                           Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.818  FAQ0223   INT007    Russian                     Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?  FAQ0224   INT007    Russian                      Могу ли я получить поздний выезд из Nile Pearl Hotel, и если это возможно, под какие условия и будут ли какие-либо дополнительные расходы?
      0.816  FAQ0025   INT001    Russian                                                                                      По какому адресу находится отель Nile Pearl Hotel?  FAQ0260   INT001    Russian                                                                                                         В каком районе города находится отель Nile Pearl Hotel?
      0.814  FAQ0233   INT008     Arabic                                                            ما نوع مستند إثبات الهوية المقبول عند تسجيل الوصول في فندق Nile Pearl Hotel؟  FAQ0234   INT008     Arabic                                                                                         ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?
      0.814  FAQ0222   INT007    Russian                                          Могу ли я получить поздний выезд из Nile Pearl Hotel, и какие возможны дополнительные расходы?  FAQ0223   INT007    Russian                                             Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?
      0.812  FAQ0044   INT002     Arabic                                                                                   كم عدد النجوم التي يُصنَّف بها فندق Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.811  FAQ0001   INT001    English                                                                                                      Where is Nile Pearl Hotel located?  FAQ0003   INT001    English                                                                                                                      In which city is Nile Pearl Hotel located?
      0.809  FAQ0003   INT001    English                                                                                              In which city is Nile Pearl Hotel located?  FAQ0258   INT001    English                                                                                                          Which part of the city is Nile Pearl Hotel located in?
      0.807  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0102   INT004    English                                                                                                       At what time can I normally check in at Nile Pearl Hotel?
      0.805  FAQ0204   INT007     Arabic                                           هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وما العوامل التي تحدد إمكانية ذلك؟  FAQ0205   INT007     Arabic                                                                                هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وهل توجد رسوم إضافية؟
      0.804  FAQ0045   INT002     Arabic                                                                                        ما فئة النجوم التي ينتمي إليها Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.804  FAQ0036   INT002    English                                                                                    What is the star classification of Nile Pearl Hotel?  FAQ0038   INT002    English                                                                                                       What star classification is assigned to Nile Pearl Hotel?
      0.804  FAQ0251   INT008    Russian                              Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0253   INT008    Russian                                                   Требуется ли гостям предъявлять документ, удостоверяющий личность, при регистрации заезда в Nile Pearl Hotel?
      0.802  FAQ0217   INT007    Russian                                                   Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, что мне нужно знать?  FAQ0218   INT007    Russian                                                                         Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?
      0.800  FAQ0137   INT005     Arabic                                                                      متى يجب على النزيل إتمام إجراءات تسجيل الخروج من Nile Pearl Hotel؟  FAQ0139   INT005     Arabic                                                                                         متى يجب على الضيوف إتمام تسجيل الخروج المعتاد من فندق Nile Pearl Hotel؟
      0.800  FAQ0085   INT003     French Si vous avez besoin d'aide urgente à l'hôtel Nile Pearl Hotel en pleine nuit, quelles sont les heures d'ouverture du service d'accueil?  FAQ0086   INT003     French Si vous avez besoin d'assistance tout au long de la journée ou de la nuit à l'hôtel Nile Pearl Hotel, quelles sont les heures d'ouverture du service d'accueil?
      0.800  FAQ0234   INT008     Arabic                                                                 ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0285   INT008     Arabic                                                                                                             ما هي وثيقة إثبات الهوية المطلوبة عند تسجيل الوصول؟

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent pairs >= 0.80: 26
 similarity faq_id_1 intent_1 language_1                                                                                                                              question_1 faq_id_2 intent_2 language_2                                                                                                                                                      question_2
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                                     What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                                                هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                                              هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                                        В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                                               Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.829  FAQ0004   INT001    English                                                                                          In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                                          Where can I find the Nile Pearl Hotel?

In [42]:
# ============================================================
# 🏆 HOTEL AI - CORRECT FINAL VALIDATION SCORE
# READ-ONLY
# ============================================================

import pandas as pd
import re

DATASET_PATH = (
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/"
    "03_Structured_Data/CSV/final/hotel_faq_final.csv"
)

df_score = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# EXPECTED
# ------------------------------------------------------------

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

# ------------------------------------------------------------
# BASIC
# ------------------------------------------------------------

row_count_ok = len(df_score) == 352

columns_ok = (
    len(df_score.columns) == 13
    and df_score.columns.tolist()
    == EXPECTED_COLUMNS
)

# ------------------------------------------------------------
# FAQ IDs
# ------------------------------------------------------------

id_format_ok = (
    df_score["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

no_duplicate_ids = (
    not df_score["faq_id"].duplicated().any()
)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 353)
]

ids_continuous = (
    df_score["faq_id"].tolist()
    == expected_ids
)

# ------------------------------------------------------------
# REQUIRED FIELDS
# ------------------------------------------------------------

required_fields_ok = True

for col in EXPECTED_COLUMNS:

    if df_score[col].isna().any():
        required_fields_ok = False
        break

    if (
        df_score[col]
        .astype(str)
        .str.strip()
        .eq("")
        .any()
    ):
        required_fields_ok = False
        break

# ------------------------------------------------------------
# DUPLICATES
# ------------------------------------------------------------

exact_duplicates_ok = (
    not df_score["question"]
    .duplicated()
    .any()
)

def normalize_question(text):

    text = str(text).casefold().strip()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

normalized_questions = (
    df_score["question"]
    .map(normalize_question)
)

normalized_duplicates_ok = (
    not normalized_questions
    .duplicated()
    .any()
)

same_intent_duplicates_ok = (
    not df_score.duplicated(
        subset=[
            "intent_id",
            normalized_questions.name
        ],
        keep=False
    ).any()
)

# The above can depend on Series naming, so use a safe DataFrame:
tmp = df_score[
    ["intent_id", "question"]
].copy()

tmp["_normalized"] = normalized_questions.values

same_intent_duplicates_ok = not tmp.duplicated(
    subset=[
        "intent_id",
        "_normalized"
    ],
    keep=False
).any()

# ------------------------------------------------------------
# INTENT MAPPING
# ------------------------------------------------------------

intent_mapping_ok = True

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df_score[
        df_score["intent_id"] == intent_id
    ]

    if len(subset) != 44:
        intent_mapping_ok = False
        break

    if set(subset["intent_name"]) != {intent_name}:
        intent_mapping_ok = False
        break

# ------------------------------------------------------------
# LANGUAGE
# ------------------------------------------------------------

language_counts = (
    df_score["language"]
    .value_counts()
)

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        language_counts.get(lang, 0) == 88
        for lang in EXPECTED_LANGUAGES
    )
)

# ------------------------------------------------------------
# INTENT BALANCE
# ------------------------------------------------------------

intent_balance_ok = all(
    (df_score["intent_id"] == intent_id).sum() == 44
    for intent_id in EXPECTED_INTENTS
)

# ------------------------------------------------------------
# LANGUAGE × INTENT
# ------------------------------------------------------------

matrix = pd.crosstab(
    df_score["intent_id"],
    df_score["language"]
)

language_intent_ok = all(
    matrix.loc[intent_id, language] == 11
    for intent_id in EXPECTED_INTENTS
    for language in EXPECTED_LANGUAGES
)

# ------------------------------------------------------------
# QUESTION TYPES
# ------------------------------------------------------------

question_types_ok = (
    set(df_score["question_type"])
    <= VALID_TYPES
)

# ------------------------------------------------------------
# STATUS
# ------------------------------------------------------------

status_ok = (
    set(df_score["status"])
    <= VALID_STATUS
)

# ------------------------------------------------------------
# DIFFICULTY
# ------------------------------------------------------------

difficulty_ok = (
    set(df_score["difficulty"])
    <= VALID_DIFFICULTY
)

# ------------------------------------------------------------
# GROUND TRUTH
# ------------------------------------------------------------

ground_truth_ok = (
    df_score["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ------------------------------------------------------------
# ANSWERS
# ------------------------------------------------------------

answers_ok = (
    df_score["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ------------------------------------------------------------
# SIMILARITY
# ------------------------------------------------------------
# Your established passing rule:
# No similarity >= 0.85

from difflib import SequenceMatcher
from itertools import combinations

questions = (
    df_score["question"]
    .astype(str)
    .tolist()
)

high_similarity_found = False

for i, j in combinations(
    range(len(questions)),
    2
):

    score = SequenceMatcher(
        None,
        normalize_question(questions[i]),
        normalize_question(questions[j])
    ).ratio()

    if score >= 0.85:
        high_similarity_found = True
        break

similarity_ok = not high_similarity_found

# ------------------------------------------------------------
# FINAL CHECKS
# ------------------------------------------------------------

checks = {
    "352 questions": row_count_ok,
    "13 columns": columns_ok,
    "Valid FAQ IDs": id_format_ok,
    "No duplicate IDs": no_duplicate_ids,
    "Continuous IDs": ids_continuous,
    "Required fields": required_fields_ok,
    "No exact duplicates": exact_duplicates_ok,
    "No normalized duplicates": normalized_duplicates_ok,
    "No same-intent duplicates": same_intent_duplicates_ok,
    "Intent mappings": intent_mapping_ok,
    "Language balance": language_balance_ok,
    "Intent balance": intent_balance_ok,
    "Language × Intent": language_intent_ok,
    "Question types": question_types_ok,
    "Status": status_ok,
    "Difficulty": difficulty_ok,
    "Ground truth": ground_truth_ok,
    "Answers": answers_ok,
    "Similarity < 0.85": similarity_ok,
}

passed = sum(checks.values())
total = len(checks)
score = passed / total * 100

# ------------------------------------------------------------
# OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("🏆 CORRECT FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():
    print(
        f"{'✅' if result else '❌'} {name}"
    )

print("-" * 100)
print(f"Passed checks     : {passed}/{total}")
print(f"Validation Score  : {score:.1f}%")

if score == 100:
    print("🟢 DATASET IS FULLY VALIDATED")
else:
    print("🟡 DATASET NEEDS REVIEW")

print("=" * 100)
print("🔒 READ-ONLY")
print("=" * 100)
print("✅ Dataset was NOT modified.")

====================================================================================================
🏆 CORRECT FINAL VALIDATION SCORE
====================================================================================================
✅ 352 questions
✅ 13 columns
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ Required fields
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks     : 19/19
Validation Score  : 100.0%
🟢 DATASET IS FULLY VALIDATED
====================================================================================================
🔒 READ-ONLY
====================================================================================================
✅ Dataset was NOT modified.

In [43]:
# ============================================================
# 🏨 HOTEL AI - FINAL FULL VALIDATION + SCORE
# DATASET: 352 QUESTIONS
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from itertools import combinations
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - FINAL FULL VALIDATION + SCORE")
print("=" * 100)

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

print("\n📂 Project root:")
print(PROJECT_ROOT)

print("\n📄 Dataset:")
print(DATASET_PATH)

print("\n✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 DATASET INFORMATION")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. EXPECTED CONFIG
# ============================================================

EXPECTED_ROWS = 352

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

# ============================================================
# 4. COLUMN CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 01. COLUMN CHECK")
print("=" * 100)

missing_columns = [
    c for c in REQUIRED_COLUMNS
    if c not in df.columns
]

extra_columns = [
    c for c in df.columns
    if c not in REQUIRED_COLUMNS
]

columns_ok = (
    not missing_columns
    and not extra_columns
    and df.columns.tolist() == REQUIRED_COLUMNS
)

print(
    "✅ PASS"
    if columns_ok
    else "❌ FAIL"
)

# ============================================================
# 5. ROW COUNT
# ============================================================

print("\n" + "=" * 100)
print("📦 02. ROW COUNT")
print("=" * 100)

row_count_ok = len(df) == EXPECTED_ROWS

print(
    f"Rows: {len(df)}"
)

print(
    "✅ PASS"
    if row_count_ok
    else "❌ FAIL"
)

# ============================================================
# 6. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 03. FAQ ID FORMAT")
print("=" * 100)

valid_id_mask = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
)

id_format_ok = valid_id_mask.all()

print(
    "✅ PASS"
    if id_format_ok
    else "❌ FAIL"
)

# ============================================================
# 7. DUPLICATE IDS
# ============================================================

print("\n" + "=" * 100)
print("🆔 04. DUPLICATE FAQ IDs")
print("=" * 100)

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

duplicate_ids_ok = duplicate_ids.empty

print(
    "✅ PASS"
    if duplicate_ids_ok
    else "❌ FAIL"
)

# ============================================================
# 8. CONTINUOUS IDS
# ============================================================

print("\n" + "=" * 100)
print("🔢 05. FAQ ID CONTINUITY")
print("=" * 100)

try:

    numeric_ids = (
        df["faq_id"]
        .astype(str)
        .str.extract(r"FAQ(\d{4})")[0]
        .astype(int)
    )

    expected_ids = list(
        range(1, EXPECTED_ROWS + 1)
    )

    continuous_ids_ok = (
        numeric_ids.tolist()
        == expected_ids
    )

except Exception:
    continuous_ids_ok = False

print(
    "✅ FAQ0001 → FAQ0352"
    if continuous_ids_ok
    else "❌ FAIL"
)

# ============================================================
# 9. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 06. REQUIRED FIELDS")
print("=" * 100)

required_fields_ok = True

for col in REQUIRED_COLUMNS:

    missing = int(df[col].isna().sum())

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if missing > 0 or empty > 0:
        required_fields_ok = False

print(
    "✅ PASS"
    if required_fields_ok
    else "❌ FAIL"
)

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 11. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 07. EXACT DUPLICATE QUESTIONS")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

exact_duplicates_ok = exact_duplicates.empty

print(
    "✅ PASS"
    if exact_duplicates_ok
    else "❌ FAIL"
)

if not exact_duplicates_ok:
    print(
        exact_duplicates[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 12. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 08. NORMALIZED DUPLICATE QUESTIONS")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized"].duplicated(keep=False)
]

normalized_duplicates_ok = normalized_duplicates.empty

print(
    "✅ PASS"
    if normalized_duplicates_ok
    else "❌ FAIL"
)

# ============================================================
# 13. SAME INTENT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔍 09. SAME-INTENT DUPLICATES")
print("=" * 100)

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized"
        ],
        keep=False
    )
]

same_intent_duplicates_ok = (
    same_intent_duplicates.empty
)

print(
    "✅ PASS"
    if same_intent_duplicates_ok
    else "❌ FAIL"
)

# ============================================================
# 14. INTENT MAPPING
# ============================================================

print("\n" + "=" * 100)
print("🔗 10. INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_mapping_ok = True

for intent_id, intent_name in INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    if len(subset) != 44:
        intent_mapping_ok = False
        break

    if set(subset["intent_name"]) != {intent_name}:
        intent_mapping_ok = False
        break

print(
    "✅ PASS"
    if intent_mapping_ok
    else "❌ FAIL"
)

# ============================================================
# 15. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 11. LANGUAGE BALANCE")
print("=" * 100)

language_counts = (
    df["language"]
    .value_counts()
)

print(language_counts.to_string())

language_balance_ok = (
    set(language_counts.index) == LANGUAGES
    and all(
        language_counts.get(language, 0) == 88
        for language in LANGUAGES
    )
)

print(
    "✅ PASS"
    if language_balance_ok
    else "❌ FAIL"
)

# ============================================================
# 16. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 12. INTENT BALANCE")
print("=" * 100)

intent_balance_ok = all(
    (df["intent_id"] == intent_id).sum() == 44
    for intent_id in INTENTS
)

print(
    "✅ PASS — 44 × 8 intents"
    if intent_balance_ok
    else "❌ FAIL"
)

# ============================================================
# 17. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 13. LANGUAGE × INTENT")
print("=" * 100)

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

print(matrix.to_string())

language_intent_ok = all(
    matrix.loc[intent_id, language] == 11
    for intent_id in INTENTS
    for language in LANGUAGES
)

print(
    "✅ PASS"
    if language_intent_ok
    else "❌ FAIL"
)

# ============================================================
# 18. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 14. QUESTION TYPES")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

print(
    question_type_counts.to_string()
)

question_types_ok = (
    set(df["question_type"])
    <= VALID_QUESTION_TYPES
)

print(
    "✅ PASS"
    if question_types_ok
    else "❌ FAIL"
)

# ============================================================
# 19. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 15. STATUS")
print("=" * 100)

status_counts = (
    df["status"]
    .value_counts()
)

print(
    status_counts.to_string()
)

status_ok = (
    set(df["status"])
    <= VALID_STATUS
)

print(
    "✅ PASS"
    if status_ok
    else "❌ FAIL"
)

# ============================================================
# 20. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 16. DIFFICULTY")
print("=" * 100)

difficulty_counts = (
    df["difficulty"]
    .value_counts()
)

print(
    difficulty_counts.to_string()
)

difficulty_ok = (
    set(df["difficulty"])
    <= VALID_DIFFICULTY
)

print(
    "✅ PASS"
    if difficulty_ok
    else "❌ FAIL"
)

# ============================================================
# 21. GROUND TRUTH
# ============================================================

print("\n" + "=" * 100)
print("🎯 17. GROUND TRUTH")
print("=" * 100)

ground_truth_ok = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print(
    "✅ PASS"
    if ground_truth_ok
    else "❌ FAIL"
)

# ============================================================
# 22. ANSWERS
# ============================================================

print("\n" + "=" * 100)
print("🎯 18. ANSWERS")
print("=" * 100)

answers_ok = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print(
    "✅ PASS"
    if answers_ok
    else "❌ FAIL"
)

# ============================================================
# 23. SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 19. FULL SIMILARITY CHECK")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} pairs..."
)

high_similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.85:

        high_similarity_pairs.append(
            (
                round(score, 3),
                df.iloc[i]["faq_id"],
                df.iloc[j]["faq_id"],
                df.iloc[i]["intent_id"],
                df.iloc[j]["intent_id"],
                df.iloc[i]["question"],
                df.iloc[j]["question"],
            )
        )

similarity_ok = (
    len(high_similarity_pairs) == 0
)

print(
    f"Pairs >= 0.85: "
    f"{len(high_similarity_pairs)}"
)

if not similarity_ok:

    print("\n🚨 HIGH SIMILARITY PAIRS:")

    for pair in sorted(
        high_similarity_pairs,
        reverse=True
    )[:30]:

        print(
            f"\nSimilarity: {pair[0]}"
        )
        print(
            f"{pair[1]} | {pair[3]} | {pair[5]}"
        )
        print(
            f"{pair[2]} | {pair[4]} | {pair[6]}"
        )

print(
    "\n✅ PASS"
    if similarity_ok
    else "\n❌ FAIL"
)

# ============================================================
# 24. VALIDATION SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

checks = {
    "352 questions": row_count_ok,
    "13 columns": columns_ok,
    "Valid FAQ IDs": id_format_ok,
    "No duplicate IDs": duplicate_ids_ok,
    "Continuous IDs": continuous_ids_ok,
    "Required fields": required_fields_ok,
    "No exact duplicates": exact_duplicates_ok,
    "No normalized duplicates": normalized_duplicates_ok,
    "No same-intent duplicates": same_intent_duplicates_ok,
    "Intent mappings": intent_mapping_ok,
    "Language balance": language_balance_ok,
    "Intent balance": intent_balance_ok,
    "Language × Intent": language_intent_ok,
    "Question types": question_types_ok,
    "Status": status_ok,
    "Difficulty": difficulty_ok,
    "Ground truth": ground_truth_ok,
    "Answers": answers_ok,
    "Similarity < 0.85": similarity_ok,
}

passed = sum(checks.values())
total = len(checks)
score = passed / total * 100

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

print("-" * 100)
print(
    f"Passed checks     : {passed}/{total}"
)
print(
    f"Validation Score  : {score:.1f}%"
)

if passed == total:
    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )
else:
    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 25. READ-ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 26. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=["_normalized"],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 VALIDATION COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FINAL FULL VALIDATION + SCORE
====================================================================================================

📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

✅ Project root found.
✅ Dataset found.

====================================================================================================
📊 DATASET INFORMATION
====================================================================================================
Rows    : 352
Columns : 13

====================================================================================================
🧪 01. COLUMN CHECK
====================================================================================================
✅ PASS

====================================================================================================
📦 02. ROW COUNT
====================================================================================================
Rows: 352
✅ PASS

====================================================================================================
🆔 03. FAQ ID FORMAT
====================================================================================================
✅ PASS

====================================================================================================
🆔 04. DUPLICATE FAQ IDs
====================================================================================================
✅ PASS

====================================================================================================
🔢 05. FAQ ID CONTINUITY
====================================================================================================
✅ FAQ0001 → FAQ0352

====================================================================================================
🧪 06. REQUIRED FIELDS
====================================================================================================
faq_id         Missing: 0  Empty: 0
intent_id      Missing: 0  Empty: 0
language       Missing: 0  Empty: 0
question_type  Missing: 0  Empty: 0
question       Missing: 0  Empty: 0
status         Missing: 0  Empty: 0
intent_name    Missing: 0  Empty: 0
ground_truth   Missing: 0  Empty: 0
category       Missing: 0  Empty: 0
source         Missing: 0  Empty: 0
attempts       Missing: 0  Empty: 0
difficulty     Missing: 0  Empty: 0
answer         Missing: 0  Empty: 0
✅ PASS

====================================================================================================
📝 07. EXACT DUPLICATE QUESTIONS
====================================================================================================
✅ PASS

====================================================================================================
🔎 08. NORMALIZED DUPLICATE QUESTIONS
====================================================================================================
✅ PASS

====================================================================================================
🔍 09. SAME-INTENT DUPLICATES
====================================================================================================
✅ PASS

====================================================================================================
🔗 10. INTENT ID ↔ INTENT NAME
====================================================================================================
✅ PASS

====================================================================================================
🌍 11. LANGUAGE BALANCE
====================================================================================================
language
English    88
Arabic     88
French     88
Russian    88
✅ PASS

====================================================================================================
🎯 12. INTENT BALANCE
====================================================================================================
✅ PASS — 44 × 8 intents

====================================================================================================
📊 13. LANGUAGE × INTENT
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         11       11      11       11
INT002         11       11      11       11
INT003         11       11      11       11
INT004         11       11      11       11
INT005         11       11      11       11
INT006         11       11      11       11
INT007         11       11      11       11
INT008         11       11      11       11
✅ PASS

====================================================================================================
📝 14. QUESTION TYPES
====================================================================================================
question_type
Paraphrased    144
Direct         120
Scenario        88
✅ PASS

====================================================================================================
📌 15. STATUS
====================================================================================================
status
valid        224
generated    128
✅ PASS

====================================================================================================
📌 16. DIFFICULTY
====================================================================================================
difficulty
Easy    352
✅ PASS

====================================================================================================
🎯 17. GROUND TRUTH
====================================================================================================
✅ PASS

====================================================================================================
🎯 18. ANSWERS
====================================================================================================
✅ PASS

====================================================================================================
🔍 19. FULL SIMILARITY CHECK
====================================================================================================
Comparing 61,776 pairs...
Pairs >= 0.85: 0

✅ PASS

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 352 questions
✅ 13 columns
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ Required fields
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks     : 19/19
Validation Score  : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 VALIDATION COMPLETE
====================================================================================================

In [44]:
# ============================================================
# 🏨 HOTEL AI - FINAL VALIDATION SCORE CHECK
# ALL 352 QUESTIONS
# READ-ONLY
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("=" * 100)
print("🏨 HOTEL AI - FINAL DATASET VALIDATION")
print("=" * 100)

print(f"\n📄 Dataset:\n{DATASET_PATH}")
print(f"📊 Rows: {len(df)}")
print(f"📊 Columns: {len(df.columns)}")

# ============================================================
# 3. CONFIG
# ============================================================

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

EXPECTED_ROWS = 352

# ============================================================
# 4. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 5. CHECKS
# ============================================================

checks = {}

# ------------------------------------------------------------
# Check 1 - Row count
# ------------------------------------------------------------

checks["352 questions"] = (
    len(df) == EXPECTED_ROWS
)

# ------------------------------------------------------------
# Check 2 - Columns
# ------------------------------------------------------------

checks["13 columns"] = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

# ------------------------------------------------------------
# Check 3 - FAQ ID format
# ------------------------------------------------------------

valid_id = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

checks["Valid FAQ IDs"] = bool(valid_id)

# ------------------------------------------------------------
# Check 4 - Duplicate IDs
# ------------------------------------------------------------

checks["No duplicate IDs"] = (
    not df["faq_id"].duplicated().any()
)

# ------------------------------------------------------------
# Check 5 - Continuous IDs
# ------------------------------------------------------------

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 353)
]

checks["Continuous IDs"] = (
    df["faq_id"].tolist() == expected_ids
)

# ------------------------------------------------------------
# Check 6 - Required fields
# ------------------------------------------------------------

required_fields_ok = True

for col in EXPECTED_COLUMNS:

    if df[col].isna().any():
        required_fields_ok = False
        break

    if (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .any()
    ):
        required_fields_ok = False
        break

checks["Required fields"] = required_fields_ok

# ------------------------------------------------------------
# Normalized questions
# ------------------------------------------------------------

df["_normalized"] = (
    df["question"]
    .map(normalize_question)
)

# ------------------------------------------------------------
# Check 7 - Exact duplicates
# ------------------------------------------------------------

checks["No exact duplicates"] = (
    not df["question"]
    .duplicated()
    .any()
)

# ------------------------------------------------------------
# Check 8 - Normalized duplicates
# ------------------------------------------------------------

checks["No normalized duplicates"] = (
    not df["_normalized"]
    .duplicated()
    .any()
)

# ------------------------------------------------------------
# Check 9 - Same-intent duplicates
# ------------------------------------------------------------

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized"
        ],
        keep=False
    )
]

checks["No same-intent duplicates"] = (
    same_intent_duplicates.empty
)

# ------------------------------------------------------------
# Check 10 - Intent mappings
# ------------------------------------------------------------

intent_mapping_ok = True

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    if len(subset) != 44:
        intent_mapping_ok = False
        break

    if set(subset["intent_name"]) != {intent_name}:
        intent_mapping_ok = False
        break

checks["Intent mappings"] = intent_mapping_ok

# ------------------------------------------------------------
# Check 11 - Language balance
# ------------------------------------------------------------

language_counts = df["language"].value_counts()

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        language_counts.get(lang, 0) == 88
        for lang in EXPECTED_LANGUAGES
    )
)

checks["Language balance"] = language_balance_ok

# ------------------------------------------------------------
# Check 12 - Intent balance
# ------------------------------------------------------------

intent_balance_ok = all(
    (
        df["intent_id"] == intent_id
    ).sum() == 44
    for intent_id in EXPECTED_INTENTS
)

checks["Intent balance"] = intent_balance_ok

# ------------------------------------------------------------
# Check 13 - Language × Intent
# ------------------------------------------------------------

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

language_intent_ok = True

for intent_id in EXPECTED_INTENTS:

    for language in EXPECTED_LANGUAGES:

        if (
            matrix.loc[
                intent_id,
                language
            ] != 11
        ):
            language_intent_ok = False

checks["Language × Intent"] = language_intent_ok

# ------------------------------------------------------------
# Check 14 - Question types
# ------------------------------------------------------------

checks["Question types"] = (
    set(df["question_type"])
    <= VALID_TYPES
)

# ------------------------------------------------------------
# Check 15 - Status
# ------------------------------------------------------------

checks["Status"] = (
    set(df["status"])
    <= VALID_STATUS
)

# ------------------------------------------------------------
# Check 16 - Difficulty
# ------------------------------------------------------------

checks["Difficulty"] = (
    set(df["difficulty"])
    <= VALID_DIFFICULTY
)

# ------------------------------------------------------------
# Check 17 - Ground truth
# ------------------------------------------------------------

checks["Ground truth"] = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ------------------------------------------------------------
# Check 18 - Answers
# ------------------------------------------------------------

checks["Answers"] = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ============================================================
# 6. SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 SIMILARITY CHECK")
print("=" * 100)

questions = df["question"].astype(str).tolist()

total_pairs = (
    len(questions)
    * (len(questions) - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

high_similarity_pairs = []

for i, j in combinations(
    range(len(questions)),
    2
):

    score = SequenceMatcher(
        None,
        questions[i].casefold(),
        questions[j].casefold()
    ).ratio()

    if score >= 0.85:

        high_similarity_pairs.append({
            "faq_id_1": df.iloc[i]["faq_id"],
            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "similarity": round(score, 3),
            "question_1": questions[i],
            "question_2": questions[j],
        })

checks["Similarity < 0.85"] = (
    len(high_similarity_pairs) == 0
)

print(
    f"Pairs >= 0.85: "
    f"{len(high_similarity_pairs)}"
)

if high_similarity_pairs:

    similarity_df = pd.DataFrame(
        high_similarity_pairs
    ).sort_values(
        "similarity",
        ascending=False
    )

    print(
        similarity_df.to_string(
            index=False
        )
    )

else:

    print("✅ No similarity >= 0.85.")

# ============================================================
# 7. SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed = sum(checks.values())
total = len(checks)
score = (
    passed / total * 100
)

print("-" * 100)
print(f"Passed checks      : {passed}/{total}")
print(
    f"Validation Score  : {score:.1f}%"
)

# ============================================================
# 8. FINAL RESULT
# ============================================================

if score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 9. QUICK SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 QUICK DATASET SUMMARY")
print("=" * 100)

print(f"Questions : {len(df)}")

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    ).size()
    .to_string()
)

print("\nQuestion types:")
print(
    df["question_type"]
    .value_counts()
    .to_string()
)

# ============================================================
# 10. READ-ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# Remove temp column from memory only
df.drop(
    columns=["_normalized"],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 VALIDATION COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FINAL DATASET VALIDATION
====================================================================================================

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Rows: 352
📊 Columns: 13

====================================================================================================
🔍 SIMILARITY CHECK
====================================================================================================
Comparing 61,776 question pairs...
Pairs >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 352 questions
✅ 13 columns
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ Required fields
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks      : 19/19
Validation Score  : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 QUICK DATASET SUMMARY
====================================================================================================
Questions : 352

Languages:
language
English    88
Arabic     88
French     88
Russian    88

Intents:
intent_id  intent_name
INT001     hotel_location             44
INT002     hotel_category             44
INT003     reception_availability     44
INT004     check_in_time              44
INT005     check_out_time             44
INT006     early_check_in             44
INT007     late_check_out             44
INT008     identification_required    44

Question types:
question_type
Paraphrased    144
Direct         120
Scenario        88

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 VALIDATION COMPLETE
====================================================================================================

In [45]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 GENERATION
# 32 NEW QUESTIONS ONLY
# CONTINUE FROM FAQ0352
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 GENERATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = (
    BATCH_DIR
    / "faq_batch_05.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print("✅ Project root found.")
print("✅ Final dataset found.")

# ============================================================
# 2. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

assert len(df) == 352, (
    f"❌ Expected 352 existing questions, "
    f"found {len(df)}"
)

print("✅ Existing dataset contains exactly 352 questions.")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Existing dataset column structure is incorrect."
)

print("✅ All 13 required columns exist.")

# ============================================================
# 4. FAQ ID CONTINUATION
# ============================================================

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = numeric_ids.max()

START_ID = last_id + 1
END_ID = START_ID + 32

assert START_ID == 353
assert END_ID == 385

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(
    f"New batch     : FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# ============================================================
# 5. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 6. BATCH 05 QUESTIONS
# ============================================================
# 4 questions per intent
# 1 per language
# Designed to vary wording and question style
# ============================================================

questions = [

    # ========================================================
    # INT001 - HOTEL LOCATION
    # ========================================================

    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا وصلت إلى القاهرة وأردت التوجه مباشرة إلى Nile Pearl Hotel، فأي موقع أو منطقة أبحث عنها؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I arrive in Cairo and want to head directly to Nile Pearl Hotel, which area should I look for?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'arrive au Caire et que je veux me rendre directement au Nile Pearl Hotel, dans quel secteur dois-je aller ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я приеду в Каир и захочу сразу отправиться в Nile Pearl Hotel, в каком районе мне его искать?",
    },

    # ========================================================
    # INT002 - HOTEL CATEGORY
    # ========================================================

    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "ما مستوى تصنيف Nile Pearl Hotel بين الفنادق؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Direct",
        "question": "What category does Nile Pearl Hotel fall under among hotels?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Direct",
        "question": "Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Direct",
        "question": "К какой гостиничной категории относится Nile Pearl Hotel?",
    },

    # ========================================================
    # INT003 - RECEPTION AVAILABILITY
    # ========================================================

    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل تظل خدمة الاستقبال متاحة للضيوف طوال الليل؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Is the front desk still available to guests throughout the night?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "La réception reste-t-elle accessible aux clients pendant toute la nuit ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Остаётся ли стойка регистрации доступной для гостей в течение всей ночи?",
    },

    # ========================================================
    # INT004 - CHECK IN TIME
    # ========================================================

    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا وصلت إلى الفندق في فترة ما بعد الظهر، من أي ساعة يمكنني بدء تسجيل الوصول؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I arrive at the hotel in the afternoon, from what time can I start checking in?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'arrive à l'hôtel dans l'après-midi, à partir de quelle heure puis-je commencer mon enregistrement ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я приеду в отель днём, с какого времени я смогу начать заселение?",
    },

    # ========================================================
    # INT005 - CHECK OUT TIME
    # ========================================================

    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "متى يجب أن تكون الغرفة خالية في يوم المغادرة؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Direct",
        "question": "What time does the room need to be vacated on the day of departure?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question_type": "Direct",
        "question": "À quelle heure la chambre doit-elle être libérée le jour du départ ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question_type": "Direct",
        "question": "К какому времени номер должен быть освобождён в день выезда?",
    },

    # ========================================================
    # INT006 - EARLY CHECK IN
    # ========================================================

    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا وصلت قبل وقت تسجيل الوصول، هل يمكنني طلب الدخول إلى الغرفة مبكرًا؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I arrive before check-in time, can I ask to access the room early?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'arrive avant l'heure d'enregistrement, puis-je demander à accéder à ma chambre plus tôt ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?",
    },

    # ========================================================
    # INT007 - LATE CHECK OUT
    # ========================================================

    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يمكن تمديد إقامتي في الغرفة إلى ما بعد وقت المغادرة؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I extend my room stay beyond the normal departure time?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je prolonger mon séjour dans la chambre au-delà de l'heure normale de départ ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Можно ли продлить пребывание в номере после обычного времени выезда?",
    },

    # ========================================================
    # INT008 - IDENTIFICATION
    # ========================================================

    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما الذي يجب أن أحمله لإثبات هويتي عند الوصول للفندق؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What should I bring to prove my identity when I arrive at the hotel?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quel document dois-je avoir avec moi pour prouver mon identité à mon arrivée à l'hôtel ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какой документ нужно иметь при себе, чтобы подтвердить личность при прибытии в отель?",
    },
]

# ============================================================
# 7. BASIC STRUCTURE
# ============================================================

assert len(questions) == 32, (
    f"❌ Expected 32 questions, found {len(questions)}"
)

required_question_fields = [
    "intent_id",
    "language",
    "question_type",
    "question",
]

for index, item in enumerate(
    questions,
    start=1
):

    for field in required_question_fields:

        assert field in item, (
            f"❌ Question #{index} missing {field}"
        )

        assert str(item[field]).strip(), (
            f"❌ Question #{index} empty {field}"
        )

print("\n" + "=" * 100)
print("🧪 QUESTION STRUCTURE CHECK")
print("=" * 100)

print("✅ All 32 questions contain required fields.")

# ============================================================
# 8. BUILD BATCH DATAFRAME
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 05",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(
    batch,
    columns=REQUIRED_COLUMNS
)

# ============================================================
# 9. ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 ID VALIDATION")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID
    )
]

assert batch_df["faq_id"].tolist() == expected_batch_ids
assert batch_df["faq_id"].is_unique

print(
    f"✅ IDs are exactly "
    f"FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}"
)

print("✅ No duplicate IDs.")

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 11. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

batch_normalized = batch_df["question"].map(
    normalize_question
)

assert not batch_df["question"].duplicated().any()

assert not batch_normalized.duplicated().any()

print("✅ No duplicate questions inside Batch 05.")

# ============================================================
# 12. OVERLAP WITH EXISTING 352
# ============================================================

existing_normalized = set(
    df["question"].map(normalize_question)
)

overlap_mask = batch_normalized.isin(
    existing_normalized
)

assert not overlap_mask.any(), (
    "❌ Batch 05 contains an existing question."
)

print("✅ No exact/normalized overlap with existing 352.")

# ============================================================
# 13. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 questions × 4 languages.")

# ============================================================
# 14. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 questions × 8 intents.")

# ============================================================
# 15. INTENT NAME CHECK
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 16. QUESTION TYPE
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = (
    set(batch_df["question_type"])
    - VALID_TYPES
)

assert not invalid_types

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 17. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 05 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 18. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 19. FINAL
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 05 READY")
print("=" * 100)

print(
    f"""
Existing dataset : {len(df)} questions
New batch        : {len(batch_df)} questions

FAQ IDs:
FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 352
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Project root found.
✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 352
Columns : 13
✅ Existing dataset contains exactly 352 questions.
✅ All 13 required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0352
New batch     : FAQ0353 → FAQ0384

====================================================================================================
🧪 QUESTION STRUCTURE CHECK
====================================================================================================
✅ All 32 questions contain required fields.

====================================================================================================
🆔 ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0353 → FAQ0384
✅ No duplicate IDs.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions inside Batch 05.
✅ No exact/normalized overlap with existing 352.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Scenario       12
Direct         12
Paraphrased     8
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📝 BATCH 05 QUESTIONS
====================================================================================================
 faq_id intent_id language question_type                                                                                                         question
FAQ0353    INT001   Arabic      Scenario                      إذا وصلت إلى القاهرة وأردت التوجه مباشرة إلى Nile Pearl Hotel، فأي موقع أو منطقة أبحث عنها؟
FAQ0354    INT001  English      Scenario                If I arrive in Cairo and want to head directly to Nile Pearl Hotel, which area should I look for?
FAQ0355    INT001   French      Scenario Si j'arrive au Caire et que je veux me rendre directement au Nile Pearl Hotel, dans quel secteur dois-je aller ?
FAQ0356    INT001  Russian      Scenario               Если я приеду в Каир и захочу сразу отправиться в Nile Pearl Hotel, в каком районе мне его искать?
FAQ0357    INT002   Arabic        Direct                                                                     ما مستوى تصنيف Nile Pearl Hotel بين الفنادق؟
FAQ0358    INT002  English        Direct                                                     What category does Nile Pearl Hotel fall under among hotels?
FAQ0359    INT002   French        Direct                                                   Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?
FAQ0360    INT002  Russian        Direct                                                        К какой гостиничной категории относится Nile Pearl Hotel?
FAQ0361    INT003   Arabic   Paraphrased                                                                   هل تظل خدمة الاستقبال متاحة للضيوف طوال الليل؟
FAQ0362    INT003  English   Paraphrased                                                Is the front desk still available to guests throughout the night?
FAQ0363    INT003   French   Paraphrased                                         La réception reste-t-elle accessible aux clients pendant toute la nuit ?
FAQ0364    INT003  Russian   Paraphrased                                         Остаётся ли стойка регистрации доступной для гостей в течение всей ночи?
FAQ0365    INT004   Arabic      Scenario                                    إذا وصلت إلى الفندق في فترة ما بعد الظهر، من أي ساعة يمكنني بدء تسجيل الوصول؟
FAQ0366    INT004  English      Scenario                               If I arrive at the hotel in the afternoon, from what time can I start checking in?
FAQ0367    INT004   French      Scenario         Si j'arrive à l'hôtel dans l'après-midi, à partir de quelle heure puis-je commencer mon enregistrement ?
FAQ0368    INT004  Russian      Scenario                                           Если я приеду в отель днём, с какого времени я смогу начать заселение?
FAQ0369    INT005   Arabic        Direct                                                                    متى يجب أن تكون الغرفة خالية في يوم المغادرة؟
FAQ0370    INT005  English        Direct                                              What time does the room need to be vacated on the day of departure?
FAQ0371    INT005   French        Direct                                             À quelle heure la chambre doit-elle être libérée le jour du départ ?
FAQ0372    INT005  Russian        Direct                                                     К какому времени номер должен быть освобождён в день выезда?
FAQ0373    INT006   Arabic      Scenario                                           إذا وصلت قبل وقت تسجيل الوصول، هل يمكنني طلب الدخول إلى الغرفة مبكرًا؟
FAQ0374    INT006  English      Scenario                                            If I arrive before check-in time, can I ask to access the room early?
FAQ0375    INT006   French      Scenario                   Si j'arrive avant l'heure d'enregistrement, puis-je demander à accéder à ma chambre plus tôt ?
FAQ0376    INT006  Russian      Scenario                              Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?
FAQ0377    INT007   Arabic        Direct                                                          هل يمكن تمديد إقامتي في الغرفة إلى ما بعد وقت المغادرة؟
FAQ0378    INT007  English        Direct                                                      Can I extend my room stay beyond the normal departure time?
FAQ0379    INT007   French        Direct                              Puis-je prolonger mon séjour dans la chambre au-delà de l'heure normale de départ ?
FAQ0380    INT007  Russian        Direct                                             Можно ли продлить пребывание в номере после обычного времени выезда?
FAQ0381    INT008   Arabic   Paraphrased                                                             ما الذي يجب أن أحمله لإثبات هويتي عند الوصول للفندق؟
FAQ0382    INT008  English   Paraphrased                                             What should I bring to prove my identity when I arrive at the hotel?
FAQ0383    INT008   French   Paraphrased                         Quel document dois-je avoir avec moi pour prouver mon identité à mon arrivée à l'hôtel ?
FAQ0384    INT008  Russian   Paraphrased                            Какой документ нужно иметь при себе, чтобы подтвердить личность при прибытии в отель?

====================================================================================================
🎉 BATCH 05 READY
====================================================================================================

Existing dataset : 352 questions
New batch        : 32 questions

FAQ IDs:
FAQ0353 → FAQ0384

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 352
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_05.csv

====================================================================================================

In [46]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 vs EXISTING 352
# DUPLICATE + SIMILARITY CHECK
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 vs EXISTING 352")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/User/Desktop/HotelAI-Intelligent-Agent"
)

# Fallback to the actual path used in the notebook
if not PROJECT_ROOT.exists():
    PROJECT_ROOT = Path(
        "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
    )

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

assert BATCH_FILE.exists(), (
    f"❌ Batch 05 not found:\n{BATCH_FILE}"
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print(f"📄 Existing dataset:\n{FINAL_DATASET}")
print(f"📄 Batch 05:\n{BATCH_FILE}")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing questions : {len(df)}")
print(f"Batch 05 questions : {len(batch_df)}")

assert len(df) == 352
assert len(batch_df) == 32

print("✅ Existing dataset = 352")
print("✅ Batch 05 = 32")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. BATCH ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 05 FAQ ID CHECK")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(353, 385)
]

assert batch_df["faq_id"].tolist() == expected_batch_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0353 → FAQ0384.")
print("✅ No duplicate IDs.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:

    print("❌ Exact overlaps found:")

    for q in exact_overlap:
        print(f"- {q}")

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize_question)
)

batch_normalized = set(
    batch_df["question"].map(normalize_question)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for q in normalized_overlap:
        print(f"- {q}")

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 05")
print("=" * 100)

batch_exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

batch_norm_series = batch_df[
    "question"
].map(normalize_question)

batch_normalized_duplicates = batch_df[
    batch_norm_series.duplicated(
        keep=False
    )
]

if batch_exact_duplicates.empty:
    print("✅ No exact duplicates inside Batch 05.")
else:
    print(
        batch_exact_duplicates[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

if batch_normalized_duplicates.empty:
    print("✅ No normalized duplicates inside Batch 05.")
else:
    print(
        batch_normalized_duplicates[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize_question(
                new_row["question"]
            ),
            normalize_question(
                old_row["question"]
            )
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"Pairs with similarity >= 0.80: "
        f"{len(similarity_df)}"
    )

    print("\nTOP 30 SIMILAR PAIRS:")
    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 10. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [0.80, 0.85, 0.90, 0.95]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME INTENT
# ============================================================

if similarity_df.empty:
    same_intent = pd.DataFrame()
else:
    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Same-intent pairs >= 0.80: "
    f"{len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 12. CROSS INTENT
# ============================================================

if similarity_df.empty:
    cross_intent = pd.DataFrame()
else:
    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Cross-intent pairs >= 0.80: "
    f"{len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 13. HIGH SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(
            index=False
        )
    )

# ============================================================
# 14. VERY HIGH
# ============================================================

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    very_high = pd.DataFrame()

else:

    very_high = similarity_df[
        similarity_df["similarity"] >= 0.90
    ]

print(
    f"Similarity >= 0.90: "
    f"{len(very_high)}"
)

if not very_high.empty:

    print(
        very_high.to_string(
            index=False
        )
    )

# ============================================================
# 15. EXTREME
# ============================================================

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    extreme = pd.DataFrame()

else:

    extreme = similarity_df[
        similarity_df["similarity"] >= 0.95
    ]

print(
    f"Similarity >= 0.95: "
    f"{len(extreme)}"
)

if not extreme.empty:

    print(
        extreme.to_string(
            index=False
        )
    )

# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 05 SIMILARITY SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 352
Batch 05 questions           : 32

Exact overlaps               : {len(exact_overlap)}
Normalized overlaps          : {len(normalized_overlap)}

Pairs >= 0.80                : {len(similarity_df)}
Same-intent pairs >= 0.80    : {len(same_intent)}
Cross-intent pairs >= 0.80   : {len(cross_intent)}

Pairs >= 0.85                : {len(high_similarity)}
Pairs >= 0.90                : {len(very_high)}
Pairs >= 0.95                : {len(extreme)}
"""
)

# ============================================================
# 17. DECISION
# ============================================================

print("=" * 100)
print("🏁 BATCH 05 DECISION")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and batch_exact_duplicates.empty
    and batch_normalized_duplicates.empty
    and len(high_similarity) == 0
    and len(cross_intent) == 0
):

    print("""
🟢 BATCH 05 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 05
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
""")

else:

    print("""
🟡 BATCH 05 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks
require attention.
""")

# ============================================================
# 18. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_05.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 05 SIMILARITY CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 vs EXISTING 352
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
📄 Existing dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📄 Batch 05:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_05.csv

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing questions : 352
Batch 05 questions : 32
✅ Existing dataset = 352
✅ Batch 05 = 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 05 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0353 → FAQ0384.
✅ No duplicate IDs.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 05
====================================================================================================
✅ No exact duplicates inside Batch 05.
✅ No normalized duplicates inside Batch 05.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs with similarity >= 0.80: 6

TOP 30 SIMILAR PAIRS:
 similarity new_faq_id new_intent new_language                                                           new_question old_faq_id old_intent old_language                                                        old_question
      0.873    FAQ0359     INT002       French         Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?    FAQ0054     INT002       French Dans quelle catégorie d'hôtel se situe exactement Nile Pearl Hotel?
      0.859    FAQ0371     INT005       French   À quelle heure la chambre doit-elle être libérée le jour du départ ?    FAQ0275     INT005       French    À quel moment la chambre doit-elle être libérée lors du départ ?
      0.840    FAQ0359     INT002       French         Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?    FAQ0263     INT002       French       À quelle catégorie hôtelière appartient le Nile Pearl Hotel ?
      0.839    FAQ0360     INT002      Russian              К какой гостиничной категории относится Nile Pearl Hotel?    FAQ0061     INT002      Russian           К какому уровню или категории относится Nile Pearl Hotel?
      0.829    FAQ0380     INT007      Russian   Можно ли продлить пребывание в номере после обычного времени выезда?    FAQ0348     INT007      Russian           Можно ли остаться в номере после обычного времени выезда?
      0.822    FAQ0373     INT006       Arabic إذا وصلت قبل وقت تسجيل الوصول، هل يمكنني طلب الدخول إلى الغرفة مبكرًا؟    FAQ0309     INT006       Arabic     سأصل قبل موعد تسجيل الوصول، فهل يمكنني الدخول إلى غرفتي مبكرًا؟

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 6 pairs
0.85+ : 2 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent pairs >= 0.80: 6
 similarity new_faq_id new_intent new_language                                                           new_question old_faq_id old_intent old_language                                                        old_question
      0.873    FAQ0359     INT002       French         Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?    FAQ0054     INT002       French Dans quelle catégorie d'hôtel se situe exactement Nile Pearl Hotel?
      0.859    FAQ0371     INT005       French   À quelle heure la chambre doit-elle être libérée le jour du départ ?    FAQ0275     INT005       French    À quel moment la chambre doit-elle être libérée lors du départ ?
      0.840    FAQ0359     INT002       French         Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?    FAQ0263     INT002       French       À quelle catégorie hôtelière appartient le Nile Pearl Hotel ?
      0.839    FAQ0360     INT002      Russian              К какой гостиничной категории относится Nile Pearl Hotel?    FAQ0061     INT002      Russian           К какому уровню или категории относится Nile Pearl Hotel?
      0.829    FAQ0380     INT007      Russian   Можно ли продлить пребывание в номере после обычного времени выезда?    FAQ0348     INT007      Russian           Можно ли остаться в номере после обычного времени выезда?
      0.822    FAQ0373     INT006       Arabic إذا وصلت قبل وقت تسجيل الوصول، هل يمكنني طلب الدخول إلى الغرفة مبكرًا؟    FAQ0309     INT006       Arabic     سأصل قبل موعد تسجيل الوصول، فهل يمكنني الدخول إلى غرفتي مبكرًا؟

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Cross-intent pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 2
 similarity new_faq_id new_intent new_language                                                         new_question old_faq_id old_intent old_language                                                        old_question
      0.873    FAQ0359     INT002       French       Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?    FAQ0054     INT002       French Dans quelle catégorie d'hôtel se situe exactement Nile Pearl Hotel?
      0.859    FAQ0371     INT005       French À quelle heure la chambre doit-elle être libérée le jour du départ ?    FAQ0275     INT005       French    À quel moment la chambre doit-elle être libérée lors du départ ?

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 0

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 0

====================================================================================================
🏆 BATCH 05 SIMILARITY SUMMARY
====================================================================================================

Existing questions          : 352
Batch 05 questions           : 32

Exact overlaps               : 0
Normalized overlaps          : 0

Pairs >= 0.80                : 6
Same-intent pairs >= 0.80    : 6
Cross-intent pairs >= 0.80   : 0

Pairs >= 0.85                : 2
Pairs >= 0.90                : 0
Pairs >= 0.95                : 0

====================================================================================================
🏁 BATCH 05 DECISION
====================================================================================================

🟡 BATCH 05 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks
require attention.

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_05.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 05 SIMILARITY CHECK COMPLETE
====================================================================================================

In [47]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 SIMILARITY REPAIR
# MODIFIES BATCH 05 ONLY
# FINAL DATASET IS NOT TOUCHED
# ============================================================

from pathlib import Path
import pandas as pd
import unicodedata
import re

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 SIMILARITY REPAIR")
print("=" * 100)

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

assert BATCH_FILE.exists(), "❌ Batch 05 not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(batch_df) == 32
assert len(df) == 352

print("✅ Existing dataset = 352")
print("✅ Batch 05 = 32")

# ============================================================
# REWRITES
# ============================================================

rewrites = {

    # --------------------------------------------------------
    # INT002 - French
    # Avoid FAQ0054 / FAQ0263 similarity
    # --------------------------------------------------------
    "FAQ0359":
        "Quel est le classement général attribué au Nile Pearl Hotel ?",

    # --------------------------------------------------------
    # INT005 - French
    # Avoid FAQ0275 similarity
    # --------------------------------------------------------
    "FAQ0371":
        "À quelle heure les clients doivent-ils rendre leur chambre le jour du départ ?",

    # --------------------------------------------------------
    # INT002 - Russian
    # Avoid FAQ0061 similarity
    # --------------------------------------------------------
    "FAQ0360":
        "Какой статус имеет Nile Pearl Hotel в системе гостиничной классификации?",

    # --------------------------------------------------------
    # INT007 - Russian
    # Avoid FAQ0348 similarity
    # --------------------------------------------------------
    "FAQ0380":
        "Предусмотрено ли продление времени проживания в номере после установленного выезда?",

    # --------------------------------------------------------
    # INT006 - Arabic
    # Avoid FAQ0309 similarity
    # --------------------------------------------------------
    "FAQ0373":
        "هل يمكنني الحصول على الغرفة قبل بداية وقت تسجيل الوصول الرسمي؟",

}

# ============================================================
# APPLY REWRITES
# ============================================================

print("\n" + "=" * 100)
print("✍️ APPLYING REWRITES")
print("=" * 100)

for faq_id, new_question in rewrites.items():

    matches = batch_df.index[
        batch_df["faq_id"] == faq_id
    ].tolist()

    assert len(matches) == 1, (
        f"❌ {faq_id} not found exactly once."
    )

    idx = matches[0]

    old_question = batch_df.at[
        idx,
        "question"
    ]

    batch_df.at[
        idx,
        "question"
    ] = new_question

    print(f"\n🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# BASIC VALIDATION
# ============================================================

assert len(batch_df) == 32

assert batch_df["faq_id"].is_unique

assert not batch_df["question"].duplicated().any()

batch_norm = batch_df["question"].map(normalize)

assert not batch_norm.duplicated().any()

print("\n✅ No duplicates inside Batch 05.")

# ============================================================
# OVERLAP WITH EXISTING 352
# ============================================================

existing_norm = set(
    df["question"].map(normalize)
)

overlap = [
    q for q in batch_norm
    if q in existing_norm
]

assert not overlap, (
    f"❌ Batch 05 overlap with existing 352:\n{overlap}"
)

print("✅ No exact/normalized overlap with existing 352.")

# ============================================================
# SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 05 UPDATED")
print("=" * 100)

print(BATCH_FILE)
print("✅ 32 rows preserved.")
print("✅ hotel_faq_final.csv was NOT modified.")

print("\n" + "=" * 100)
print("🎉 BATCH 05 SIMILARITY REPAIR COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 SIMILARITY REPAIR
====================================================================================================
✅ Existing dataset = 352
✅ Batch 05 = 32

====================================================================================================
✍️ APPLYING REWRITES
====================================================================================================

🔄 FAQ0359
OLD: Dans quelle catégorie hôtelière se situe le Nile Pearl Hotel ?
NEW: Quel est le classement général attribué au Nile Pearl Hotel ?

🔄 FAQ0371
OLD: À quelle heure la chambre doit-elle être libérée le jour du départ ?
NEW: À quelle heure les clients doivent-ils rendre leur chambre le jour du départ ?

🔄 FAQ0360
OLD: К какой гостиничной категории относится Nile Pearl Hotel?
NEW: Какой статус имеет Nile Pearl Hotel в системе гостиничной классификации?

🔄 FAQ0380
OLD: Можно ли продлить пребывание в номере после обычного времени выезда?
NEW: Предусмотрено ли продление времени проживания в номере после установленного выезда?

🔄 FAQ0373
OLD: إذا وصلت قبل وقت تسجيل الوصول، هل يمكنني طلب الدخول إلى الغرفة مبكرًا؟
NEW: هل يمكنني الحصول على الغرفة قبل بداية وقت تسجيل الوصول الرسمي؟

✅ No duplicates inside Batch 05.
✅ No exact/normalized overlap with existing 352.

====================================================================================================
💾 BATCH 05 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_05.csv
✅ 32 rows preserved.
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🎉 BATCH 05 SIMILARITY REPAIR COMPLETE
====================================================================================================

In [48]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 FINAL SIMILARITY CHECK
# Existing dataset : 352
# Batch 05         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata
from difflib import SequenceMatcher

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 FINAL SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 05 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print(f"📄 Existing dataset:\n{FINAL_DATASET}")
print(f"📄 Batch 05:\n{BATCH_FILE}")

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing questions : {len(df)}")
print(f"Batch 05 questions : {len(batch_df)}")

assert len(df) == 352, (
    f"❌ Existing dataset must contain 352 rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 05 must contain 32 rows, found {len(batch_df)}"
)

print("✅ Existing dataset = 352")
print("✅ Batch 05 = 32")

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. BATCH ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 05 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(353, 385)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0353 → FAQ0384.")
print("✅ No duplicate IDs.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:

    print("❌ Exact overlaps found:")

    for q in exact_overlap:
        print(f"- {q}")

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize_question)
)

batch_normalized = set(
    batch_df["question"].map(normalize_question)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for q in normalized_overlap:
        print(f"- {q}")

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 05")
print("=" * 100)

exact_dupes = batch_df[
    batch_df["question"].duplicated(keep=False)
]

batch_norm_series = (
    batch_df["question"]
    .map(normalize_question)
)

normalized_dupes = batch_df[
    batch_norm_series.duplicated(keep=False)
]

if exact_dupes.empty:
    print("✅ No exact duplicates inside Batch 05.")
else:
    print(
        exact_dupes[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

if normalized_dupes.empty:
    print("✅ No normalized duplicates inside Batch 05.")
else:
    print(
        normalized_dupes[
            ["faq_id", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize_question(new_row["question"]),
            normalize_question(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"Pairs with similarity >= 0.80: "
        f"{len(similarity_df)}"
    )

    print("\nTOP SIMILAR PAIRS:")

    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 10. THRESHOLD SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [0.80, 0.85, 0.90, 0.95]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(f"{threshold:.2f}+ : {count} pairs")

# ============================================================
# 11. SAME INTENT
# ============================================================

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print(
    f"Same-intent pairs >= 0.80: "
    f"{len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 12. CROSS INTENT
# ============================================================

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print(
    f"Cross-intent pairs >= 0.80: "
    f"{len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 13. HIGH SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(
            index=False
        )
    )

# ============================================================
# 14. VERY HIGH
# ============================================================

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    very_high = pd.DataFrame()

else:

    very_high = similarity_df[
        similarity_df["similarity"] >= 0.90
    ]

print(
    f"Similarity >= 0.90: "
    f"{len(very_high)}"
)

if not very_high.empty:

    print(
        very_high.to_string(
            index=False
        )
    )

# ============================================================
# 15. EXTREME
# ============================================================

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

if similarity_df.empty:

    extreme = pd.DataFrame()

else:

    extreme = similarity_df[
        similarity_df["similarity"] >= 0.95
    ]

print(
    f"Similarity >= 0.95: "
    f"{len(extreme)}"
)

if not extreme.empty:

    print(
        extreme.to_string(
            index=False
        )
    )

# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 05 FINAL SIMILARITY SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 352
Batch 05 questions           : 32

Exact overlaps               : {len(exact_overlap)}
Normalized overlaps          : {len(normalized_overlap)}

Pairs >= 0.80                : {len(similarity_df)}
Same-intent >= 0.80          : {len(same_intent)}
Cross-intent >= 0.80         : {len(cross_intent)}

Pairs >= 0.85                : {len(high_similarity)}
Pairs >= 0.90                : {len(very_high)}
Pairs >= 0.95                : {len(extreme)}
"""
)

# ============================================================
# 17. DECISION
# ============================================================

print("=" * 100)
print("🏁 BATCH 05 DECISION")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_dupes.empty
    and normalized_dupes.empty
    and len(high_similarity) == 0
    and len(cross_intent) == 0
):

    print("""
🟢 BATCH 05 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 05
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
""")

else:

    print("""
🟡 BATCH 05 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks
require attention.
""")

# ============================================================
# 18. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_05.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 05 FINAL SIMILARITY CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 FINAL SIMILARITY CHECK
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
📄 Existing dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📄 Batch 05:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_05.csv

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing questions : 352
Batch 05 questions : 32
✅ Existing dataset = 352
✅ Batch 05 = 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 05 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0353 → FAQ0384.
✅ No duplicate IDs.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 05
====================================================================================================
✅ No exact duplicates inside Batch 05.
✅ No normalized duplicates inside Batch 05.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
🎉 No pairs with similarity >= 0.80.

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 0 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Same-intent pairs >= 0.80: 0

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Cross-intent pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 0

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 0

====================================================================================================
🏆 BATCH 05 FINAL SIMILARITY SUMMARY
====================================================================================================

Existing questions          : 352
Batch 05 questions           : 32

Exact overlaps               : 0
Normalized overlaps          : 0

Pairs >= 0.80                : 0
Same-intent >= 0.80          : 0
Cross-intent >= 0.80         : 0

Pairs >= 0.85                : 0
Pairs >= 0.90                : 0
Pairs >= 0.95                : 0

====================================================================================================
🏁 BATCH 05 DECISION
====================================================================================================

🟢 BATCH 05 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 05
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_05.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 05 FINAL SIMILARITY CHECK COMPLETE
====================================================================================================

In [49]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 REPAIR
# GROUND TRUTH + ANSWER + VALIDATION
# ============================================================
# Modifies:
#   03_Structured_Data/CSV/batches/faq_batch_05.csv
#
# Does NOT modify:
#   03_Structured_Data/CSV/final/hotel_faq_final.csv
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 REPAIR + VALIDATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

assert BATCH_FILE.exists(), (
    f"❌ Batch 05 not found:\n{BATCH_FILE}"
)

print("✅ Project root found.")
print("✅ Final dataset found.")
print("✅ Batch 05 found.")

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 352
assert len(batch_df) == 32

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 05         : {len(batch_df)} rows")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FORCE CORRECT DTYPES
# ============================================================
# Prevents pandas FutureWarning when writing text into columns
# that may have been inferred as float64 because they were empty.

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:
    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 5. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

# ============================================================
# 6. BATCH ID VALIDATION
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(353, 385)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

print("✅ IDs are exactly FAQ0353 → FAQ0384.")
print("✅ No duplicate IDs.")

# ============================================================
# 7. NORMALIZATION
# ============================================================

def normalize_text(text):
    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 8. DUPLICATE / OVERLAP CHECK
# ============================================================

batch_norm = batch_df["question"].map(
    normalize_text
)

existing_norm = set(
    df["question"].map(normalize_text)
)

assert not batch_df["question"].duplicated().any()
assert not batch_norm.duplicated().any()

overlap = [
    q for q in batch_norm
    if q in existing_norm
]

assert not overlap, (
    f"❌ Batch 05 overlaps with existing 352:\n{overlap}"
)

print("\n" + "=" * 100)
print("📝 QUESTION OVERLAP")
print("=" * 100)

print("✅ No exact duplicates inside Batch 05.")
print("✅ No normalized duplicates inside Batch 05.")
print("✅ No overlap with existing 352.")

# ============================================================
# 9. BUILD CANONICAL KNOWLEDGE MAP
# ============================================================
# Use the existing 352 as the source of truth.
#
# We pick the most common ground_truth and answer
# for each Intent × Language.

print("\n" + "=" * 100)
print("🧠 BUILDING KNOWLEDGE MAP")
print("=" * 100)

knowledge_map = {}

for intent_id, intent_name in INTENTS.items():

    for language in LANGUAGES:

        subset = df[
            (df["intent_id"] == intent_id)
            &
            (df["language"] == language)
        ].copy()

        assert len(subset) == 11, (
            f"❌ Expected 11 rows for "
            f"{intent_id} × {language}, "
            f"found {len(subset)}"
        )

        # -----------------------------
        # Ground truth candidates
        # -----------------------------

        gt = (
            subset["ground_truth"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        gt = gt[gt.ne("")]

        assert not gt.empty, (
            f"❌ No ground truth for "
            f"{intent_id} × {language}"
        )

        canonical_gt = (
            gt.value_counts()
            .index[0]
        )

        # -----------------------------
        # Answer candidates
        # -----------------------------

        answers = (
            subset["answer"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        answers = answers[
            answers.ne("")
        ]

        assert not answers.empty, (
            f"❌ No answer for "
            f"{intent_id} × {language}"
        )

        canonical_answer = (
            answers.value_counts()
            .index[0]
        )

        knowledge_map[
            (intent_id, language)
        ] = {
            "ground_truth": canonical_gt,
            "answer": canonical_answer,
        }

        print(
            f"✅ {intent_id:<6} "
            f"{language:<8}"
        )

print("✅ Knowledge map created.")

# ============================================================
# 10. APPLY GROUND TRUTH + ANSWERS
# ============================================================

print("\n" + "=" * 100)
print("✍️ APPLYING GROUND TRUTH + ANSWERS")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(
        row["intent_id"]
    ).strip()

    language = str(
        row["language"]
    ).strip()

    assert intent_id in INTENTS
    assert language in LANGUAGES

    knowledge = knowledge_map[
        (intent_id, language)
    ]

    batch_df.at[
        idx,
        "ground_truth"
    ] = knowledge["ground_truth"]

    batch_df.at[
        idx,
        "answer"
    ] = knowledge["answer"]

    batch_df.at[
        idx,
        "status"
    ] = "generated"

    batch_df.at[
        idx,
        "category"
    ] = "Hotel FAQ"

    batch_df.at[
        idx,
        "source"
    ] = "Generated Batch 05"

    batch_df.at[
        idx,
        "attempts"
    ] = 0

    batch_df.at[
        idx,
        "difficulty"
    ] = "Easy"

print("✅ Ground truth filled for all 32.")
print("✅ Answers filled for all 32.")

# ============================================================
# 11. RECAST TEXT COLUMNS AFTER ASSIGNMENT
# ============================================================

for col in TEXT_COLUMNS:
    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

# ============================================================
# 12. REQUIRED FIELD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 13. LANGUAGE CHECK
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 questions × 4 languages.")

# ============================================================
# 14. INTENT CHECK
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 questions × 8 intents.")

# ============================================================
# 15. INTENT NAME CHECK
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 16. QUESTION TYPE CHECK
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert (
    set(batch_df["question_type"])
    <= VALID_TYPES
)

print("\n" + "=" * 100)
print("📝 QUESTION TYPES")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 17. GROUND TRUTH / ANSWER CHECK
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

assert (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 18. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 19. RELOAD CHECK
# ============================================================

reloaded = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(reloaded) == 32

assert reloaded["faq_id"].tolist() == expected_ids

assert (
    reloaded["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    reloaded["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ============================================================
# 20. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 05 REPAIR RESULT")
print("=" * 100)

print("""
🟢 BATCH 05 IS COMPLETE

✅ 32 questions
✅ FAQ0353 → FAQ0384
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Question types valid
✅ No duplicate questions
✅ No normalized overlap with existing 352

⚠️ hotel_faq_final.csv was NOT modified.

🎉 SAFE FOR FINAL BATCH 05 VALIDATION
""")

print(f"📄 Batch saved to:")
print(BATCH_FILE)

print("=" * 100)
print("🎉 BATCH 05 REPAIR COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 REPAIR + VALIDATION
====================================================================================================
✅ Project root found.
✅ Final dataset found.
✅ Batch 05 found.

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 352 rows
Batch 05         : 32 rows
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0353 → FAQ0384.
✅ No duplicate IDs.

====================================================================================================
📝 QUESTION OVERLAP
====================================================================================================
✅ No exact duplicates inside Batch 05.
✅ No normalized duplicates inside Batch 05.
✅ No overlap with existing 352.

====================================================================================================
🧠 BUILDING KNOWLEDGE MAP
====================================================================================================
✅ INT001 Russian
✅ INT001 English
✅ INT001 French
✅ INT001 Arabic
✅ INT002 Russian
✅ INT002 English
✅ INT002 French
✅ INT002 Arabic
✅ INT003 Russian
✅ INT003 English
✅ INT003 French
✅ INT003 Arabic
✅ INT004 Russian
✅ INT004 English
✅ INT004 French
✅ INT004 Arabic
✅ INT005 Russian
✅ INT005 English
✅ INT005 French
✅ INT005 Arabic
✅ INT006 Russian
✅ INT006 English
✅ INT006 French
✅ INT006 Arabic
✅ INT007 Russian
✅ INT007 English
✅ INT007 French
✅ INT007 Arabic
✅ INT008 Russian
✅ INT008 English
✅ INT008 French
✅ INT008 Arabic
✅ Knowledge map created.

====================================================================================================
✍️ APPLYING GROUND TRUTH + ANSWERS
====================================================================================================
✅ Ground truth filled for all 32.
✅ Answers filled for all 32.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: Int64
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: Int64
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPES
====================================================================================================
question_type
Scenario       12
Direct         12
Paraphrased     8
Name: count, dtype: Int64
✅ All question types are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🏆 BATCH 05 REPAIR RESULT
====================================================================================================

🟢 BATCH 05 IS COMPLETE

✅ 32 questions
✅ FAQ0353 → FAQ0384
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions per intent
✅ Intent names consistent
✅ Question types valid
✅ No duplicate questions
✅ No normalized overlap with existing 352

⚠️ hotel_faq_final.csv was NOT modified.

🎉 SAFE FOR FINAL BATCH 05 VALIDATION

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_05.csv
====================================================================================================
🎉 BATCH 05 REPAIR COMPLETE
====================================================================================================

In [50]:
# ============================================================
# 🏨 HOTEL AI - BATCH 05 FINAL VALIDATION
# AFTER GROUND TRUTH + ANSWER REPAIR
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 05 FINAL VALIDATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print(f"Existing dataset : {len(df)}")
print(f"Batch 05         : {len(batch_df)}")

assert len(df) == 352
assert len(batch_df) == 32

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. IDS
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(353, 385)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0353 → FAQ0384.")
print("✅ No duplicate IDs.")

# ============================================================
# 5. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD CHECK")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"✅ {col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 6. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 7. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

assert not batch_df["question"].duplicated().any()

batch_normalized = (
    batch_df["question"]
    .map(normalize)
)

assert not batch_normalized.duplicated().any()

print("✅ No exact duplicates.")
print("✅ No normalized duplicates.")

# ============================================================
# 8. OVERLAP WITH EXISTING 352
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP WITH EXISTING 352")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize)
)

overlap = [
    q for q in batch_normalized
    if q in existing_normalized
]

assert not overlap, (
    f"❌ Overlap found:\n{overlap}"
)

print("✅ No exact/normalized overlap.")

# ============================================================
# 9. LANGUAGE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 × 4 languages.")

# ============================================================
# 10. INTENTS
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 × 8 intents.")

# ============================================================
# 11. INTENT NAME
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 12. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert (
    set(batch_df["question_type"])
    <= VALID_TYPES
)

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 13. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

ground_truth_ok = (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_ok = (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert ground_truth_ok
assert answers_ok

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 14. STATUS / DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS / DIFFICULTY")
print("=" * 100)

print(
    batch_df["status"]
    .value_counts()
)

print(
    batch_df["difficulty"]
    .value_counts()
)

assert set(batch_df["status"]) <= {
    "valid",
    "generated",
}

assert set(batch_df["difficulty"]) <= {
    "Easy",
}

print("✅ Status valid.")
print("✅ Difficulty valid.")

# ============================================================
# 15. SIMILARITY AGAINST 352
# ============================================================

print("\n" + "=" * 100)
print("🔍 SIMILARITY AGAINST EXISTING 352")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),
                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],
                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print("🎉 No similarity >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs >= 0.80: "
        f"{len(similarity_df)}"
    )

    print(
        similarity_df.head(30)
        .to_string(index=False)
    )

# ============================================================
# 16. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

thresholds = {}

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    thresholds[threshold] = count

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 17. SAME INTENT
# ============================================================

if similarity_df.empty:
    same_intent = pd.DataFrame()
else:
    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 18. CROSS INTENT
# ============================================================

if similarity_df.empty:
    cross_intent = pd.DataFrame()
else:
    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 19. FINAL BATCH RESULT
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🏆 BATCH 05 FINAL RESULT")
print("=" * 100)

if (
    exact_dupes.empty
    and normalized_overlap == []
    and high_similarity.empty
    and cross_intent.empty
    and ground_truth_ok
    and answers_ok
):

    print("""
🟢 BATCH 05 IS FULLY VALID

✅ 32 questions
✅ FAQ0353 → FAQ0384
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

🎉 SAFE TO MERGE BATCH 05
""")

else:

    print("""
🟡 BATCH 05 NEEDS REVIEW
⚠️ One or more checks failed.
""")

# ============================================================
# 20. READ ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_05.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 05 FINAL CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 05 FINAL VALIDATION
====================================================================================================
Existing dataset : 352
Batch 05         : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0353 → FAQ0384.
✅ No duplicate IDs.

====================================================================================================
🧪 REQUIRED FIELD CHECK
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No exact duplicates.
✅ No normalized duplicates.

====================================================================================================
🔎 OVERLAP WITH EXISTING 352
====================================================================================================
✅ No exact/normalized overlap.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Scenario       12
Direct         12
Paraphrased     8
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📌 STATUS / DIFFICULTY
====================================================================================================
status
generated    32
Name: count, dtype: int64
difficulty
Easy    32
Name: count, dtype: int64
✅ Status valid.
✅ Difficulty valid.

====================================================================================================
🔍 SIMILARITY AGAINST EXISTING 352
====================================================================================================
🎉 No similarity >= 0.80.

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 0 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 0

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 0

====================================================================================================
🏆 BATCH 05 FINAL RESULT
====================================================================================================

🟢 BATCH 05 IS FULLY VALID

✅ 32 questions
✅ FAQ0353 → FAQ0384
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

🎉 SAFE TO MERGE BATCH 05

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_05.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 05 FINAL CHECK COMPLETE
====================================================================================================

In [51]:
# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 05
# 352 + 32 = 384 QUESTIONS
# ============================================================

from pathlib import Path
from datetime import datetime
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 05")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_05.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

# ============================================================
# 2. VALIDATE FILES
# ============================================================

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 05 not found."

# ============================================================
# 3. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print(f"Current dataset : {len(df)}")
print(f"Batch 05        : {len(batch_df)}")

assert len(df) == 352, (
    f"❌ Expected 352 current rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Expected 32 batch rows, found {len(batch_df)}"
)

# ============================================================
# 4. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 5. BACKUP
# ============================================================

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_batch05_{timestamp}.csv"
)

df.to_csv(
    backup_path,
    index=False,
    encoding="utf-8-sig"
)

print()
print("💾 Backup created:")
print(backup_path)

# ============================================================
# 6. BATCH ID VALIDATION
# ============================================================

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(353, 385)
]

assert (
    batch_df["faq_id"].tolist()
    == expected_batch_ids
)

assert batch_df["faq_id"].is_unique

print("✅ Batch IDs: FAQ0353 → FAQ0384")
print("✅ No duplicate batch IDs.")

# ============================================================
# 7. CHECK ID OVERLAP
# ============================================================

existing_ids = set(
    df["faq_id"]
)

batch_ids = set(
    batch_df["faq_id"]
)

id_overlap = existing_ids.intersection(
    batch_ids
)

assert not id_overlap, (
    f"❌ FAQ ID overlap found: {id_overlap}"
)

print("✅ No FAQ ID overlap.")

# ============================================================
# 8. NORMALIZATION
# ============================================================

def normalize_question(text):
    return (
        str(text)
        .casefold()
        .strip()
    )

existing_questions = set(
    df["question"].map(normalize_question)
)

batch_questions = set(
    batch_df["question"].map(normalize_question)
)

question_overlap = (
    existing_questions.intersection(
        batch_questions
    )
)

assert not question_overlap, (
    f"❌ Question overlap found:\n{question_overlap}"
)

assert not (
    batch_df["question"].duplicated().any()
)

print("✅ No question overlap.")
print("✅ No duplicate questions inside Batch 05.")

# ============================================================
# 9. FIX DTYPES
# ============================================================
# Prevent pandas dtype warnings during concat/save.

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:
    df[col] = (
        df[col]
        .fillna("")
        .astype("string")
    )

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

df["attempts"] = pd.to_numeric(
    df["attempts"],
    errors="raise"
)

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 10. MERGE
# ============================================================

merged_df = pd.concat(
    [df, batch_df],
    ignore_index=True
)

# ============================================================
# 11. FINAL ID VALIDATION
# ============================================================

expected_final_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 385)
]

assert (
    merged_df["faq_id"].tolist()
    == expected_final_ids
), "❌ Final FAQ IDs are incorrect."

assert merged_df["faq_id"].is_unique, (
    "❌ Duplicate FAQ IDs after merge."
)

# ============================================================
# 12. FINAL QUESTION VALIDATION
# ============================================================

assert not (
    merged_df["question"]
    .duplicated()
    .any()
), "❌ Duplicate questions after merge."

merged_normalized = (
    merged_df["question"]
    .map(normalize_question)
)

assert not (
    merged_normalized
    .duplicated()
    .any()
), "❌ Normalized duplicate questions after merge."

# ============================================================
# 13. FINAL ROW COUNT
# ============================================================

assert len(merged_df) == 384, (
    f"❌ Expected 384 rows, found {len(merged_df)}"
)

print()
print("=" * 100)
print("📊 MERGE VALIDATION")
print("=" * 100)

print("✅ Final row count: 384")
print("✅ IDs continuous: FAQ0001 → FAQ0384")
print("✅ No duplicate IDs")
print("✅ No duplicate questions")
print("✅ No normalized duplicates")

# ============================================================
# 14. SAVE
# ============================================================

merged_df.to_csv(
    FINAL_DATASET,
    index=False,
    encoding="utf-8-sig"
)

print()
print("=" * 100)
print("💾 FINAL DATASET UPDATED")
print("=" * 100)

print(FINAL_DATASET)

# ============================================================
# 15. RELOAD AND VERIFY
# ============================================================

check_df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(check_df) == 384

assert (
    check_df["faq_id"].tolist()
    == expected_final_ids
)

assert check_df["faq_id"].is_unique

assert not (
    check_df["question"]
    .duplicated()
    .any()
)

check_normalized = (
    check_df["question"]
    .map(normalize_question)
)

assert not (
    check_normalized
    .duplicated()
    .any()
)

# ============================================================
# 16. FINAL RESULT
# ============================================================

print()
print("=" * 100)
print("🏆 MERGE RESULT")
print("=" * 100)

print("""
🟢 BATCH 05 MERGED SUCCESSFULLY

Previous dataset : 352
Added questions  : 32
Final dataset    : 384

IDs:
FAQ0001 → FAQ0384

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully
""")

print("🔒 Backup:")
print(backup_path)

print("=" * 100)
print("🎉 MERGE BATCH 05 COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 05
====================================================================================================
Current dataset : 352
Batch 05        : 32
✅ All 13 columns exist.
✅ Column order is correct.

💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch05_20260821_153750.csv
✅ Batch IDs: FAQ0353 → FAQ0384
✅ No duplicate batch IDs.
✅ No FAQ ID overlap.
✅ No question overlap.
✅ No duplicate questions inside Batch 05.

====================================================================================================
📊 MERGE VALIDATION
====================================================================================================
✅ Final row count: 384
✅ IDs continuous: FAQ0001 → FAQ0384
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates

====================================================================================================
💾 FINAL DATASET UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 MERGE RESULT
====================================================================================================

🟢 BATCH 05 MERGED SUCCESSFULLY

Previous dataset : 352
Added questions  : 32
Final dataset    : 384

IDs:
FAQ0001 → FAQ0384

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch05_20260821_153750.csv
====================================================================================================
🎉 MERGE BATCH 05 COMPLETE
====================================================================================================

In [52]:
# ============================================================
# 🏨 HOTEL AI - FULL VALIDATION SCORE
# ALL 384 QUESTIONS
# READ-ONLY
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

# ============================================================
# 1. CONFIG
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 384

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

print("=" * 100)
print("🏨 HOTEL AI - FULL DATASET VALIDATION")
print("=" * 100)

# ============================================================
# 2. LOAD
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print(f"\n📄 Dataset:\n{DATASET_PATH}")
print(f"📊 Rows    : {len(df)}")
print(f"📊 Columns : {len(df.columns)}")

# ============================================================
# 3. SCORE DICTIONARY
# ============================================================

checks = {}

# ============================================================
# 4. ROW COUNT
# ============================================================

checks["384 questions"] = (
    len(df) == EXPECTED_ROWS
)

# ============================================================
# 5. COLUMNS
# ============================================================

checks["13 columns"] = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

# ============================================================
# 6. REQUIRED FIELDS
# ============================================================

required_fields_ok = True

for col in EXPECTED_COLUMNS:

    if df[col].isna().any():
        required_fields_ok = False
        break

    if (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .any()
    ):
        required_fields_ok = False
        break

checks["Required fields"] = required_fields_ok

# ============================================================
# 7. FAQ ID FORMAT
# ============================================================

valid_id_format = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

checks["Valid FAQ IDs"] = bool(valid_id_format)

# ============================================================
# 8. DUPLICATE IDs
# ============================================================

checks["No duplicate IDs"] = (
    not df["faq_id"].duplicated().any()
)

# ============================================================
# 9. CONTINUOUS IDs
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, EXPECTED_ROWS + 1)
]

checks["Continuous IDs"] = (
    df["faq_id"].tolist()
    == expected_ids
)

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized"] = (
    df["question"]
    .map(normalize_question)
)

# ============================================================
# 11. EXACT DUPLICATES
# ============================================================

checks["No exact duplicates"] = (
    not df["question"].duplicated().any()
)

# ============================================================
# 12. NORMALIZED DUPLICATES
# ============================================================

checks["No normalized duplicates"] = (
    not df["_normalized"].duplicated().any()
)

# ============================================================
# 13. SAME-INTENT DUPLICATES
# ============================================================

same_intent_dupes = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized"
        ],
        keep=False
    )
]

checks["No same-intent duplicates"] = (
    same_intent_dupes.empty
)

# ============================================================
# 14. INTENT MAPPING
# ============================================================

intent_mapping_ok = True

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    if len(subset) != 48:
        intent_mapping_ok = False
        break

    if set(subset["intent_name"]) != {intent_name}:
        intent_mapping_ok = False
        break

checks["Intent mappings"] = intent_mapping_ok

# ============================================================
# 15. LANGUAGE BALANCE
# ============================================================

language_counts = df["language"].value_counts()

checks["Language balance"] = (
    set(language_counts.index) == EXPECTED_LANGUAGES
    and all(
        language_counts.get(lang, 0) == 96
        for lang in EXPECTED_LANGUAGES
    )
)

# ============================================================
# 16. INTENT BALANCE
# ============================================================

checks["Intent balance"] = all(
    (
        df["intent_id"] == intent_id
    ).sum() == 48
    for intent_id in EXPECTED_INTENTS
)

# ============================================================
# 17. LANGUAGE × INTENT
# ============================================================

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

checks["Language × Intent"] = all(
    matrix.loc[intent_id, language] == 12
    for intent_id in EXPECTED_INTENTS
    for language in EXPECTED_LANGUAGES
)

# ============================================================
# 18. QUESTION TYPES
# ============================================================

checks["Question types"] = (
    set(df["question_type"])
    <= VALID_TYPES
)

# ============================================================
# 19. STATUS
# ============================================================

checks["Status"] = (
    set(df["status"])
    <= VALID_STATUS
)

# ============================================================
# 20. DIFFICULTY
# ============================================================

checks["Difficulty"] = (
    set(df["difficulty"])
    <= VALID_DIFFICULTY
)

# ============================================================
# 21. GROUND TRUTH
# ============================================================

checks["Ground truth"] = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ============================================================
# 22. ANSWERS
# ============================================================

checks["Answers"] = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ============================================================
# 23. SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL QUESTION SIMILARITY CHECK")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

high_similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_question(questions[i]),
        normalize_question(questions[j])
    ).ratio()

    if score >= 0.85:

        high_similarity_pairs.append({
            "similarity": round(score, 3),
            "faq_id_1": df.iloc[i]["faq_id"],
            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "question_1": questions[i],
            "question_2": questions[j],
        })

checks["Similarity < 0.85"] = (
    len(high_similarity_pairs) == 0
)

print(
    f"Pairs >= 0.85: {len(high_similarity_pairs)}"
)

if high_similarity_pairs:

    similarity_df = pd.DataFrame(
        high_similarity_pairs
    ).sort_values(
        "similarity",
        ascending=False
    )

    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

else:

    print("✅ No similarity >= 0.85.")

# ============================================================
# 24. FINAL SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed = sum(checks.values())
total = len(checks)
score = (
    passed / total * 100
)

print("-" * 100)
print(f"Passed checks      : {passed}/{total}")
print(f"Validation Score   : {score:.1f}%")

if score == 100:

    print("🟢 DATASET IS FULLY VALIDATED")

else:

    print("🟡 DATASET NEEDS REVIEW")

# ============================================================
# 25. QUICK SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 QUICK DATASET SUMMARY")
print("=" * 100)

print(f"Questions : {len(df)}")

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    ).size()
    .to_string()
)

print("\nLanguage × Intent:")
print(
    matrix.to_string()
)

print("\nQuestion types:")
print(
    df["question_type"]
    .value_counts()
    .to_string()
)

print("\nStatus:")
print(
    df["status"]
    .value_counts()
    .to_string()
)

print("\nDifficulty:")
print(
    df["difficulty"]
    .value_counts()
    .to_string()
)

# ============================================================
# 26. READ-ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# Remove temporary column from memory only
df.drop(
    columns=["_normalized"],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 VALIDATION COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FULL DATASET VALIDATION
====================================================================================================

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Rows    : 384
📊 Columns : 13

====================================================================================================
🔍 FULL QUESTION SIMILARITY CHECK
====================================================================================================
Comparing 73,536 question pairs...
Pairs >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 384 questions
✅ 13 columns
✅ Required fields
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks      : 19/19
Validation Score   : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 QUICK DATASET SUMMARY
====================================================================================================
Questions : 384

Languages:
language
English    96
Arabic     96
French     96
Russian    96

Intents:
intent_id  intent_name
INT001     hotel_location             48
INT002     hotel_category             48
INT003     reception_availability     48
INT004     check_in_time              48
INT005     check_out_time             48
INT006     early_check_in             48
INT007     late_check_out             48
INT008     identification_required    48

Language × Intent:
language   Arabic  English  French  Russian
intent_id
INT001         12       12      12       12
INT002         12       12      12       12
INT003         12       12      12       12
INT004         12       12      12       12
INT005         12       12      12       12
INT006         12       12      12       12
INT007         12       12      12       12
INT008         12       12      12       12

Question types:
question_type
Paraphrased    152
Direct         132
Scenario       100

Status:
status
valid        224
generated    160

Difficulty:
difficulty
Easy    384

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 VALIDATION COMPLETE
====================================================================================================

In [53]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE 384 DATASET AUDIT
# FULL QUALITY + DUPLICATE + SIMILARITY + BALANCE CHECK
# READ-ONLY — DOES NOT MODIFY CSV
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import numpy as np
import re
import unicodedata

# ============================================================
# 1. PATHS / CONFIG
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 384

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

SIMILARITY_THRESHOLD = 0.85

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE 384 DATASET AUDIT")
print("=" * 100)

# ============================================================
# 2. PATH VALIDATION
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

print("\n📂 PROJECT")
print("=" * 100)
print(PROJECT_ROOT)

print("\n📄 DATASET")
print("=" * 100)
print(DATASET_PATH)

print("\n✅ Project root found.")
print("✅ Dataset found.")

# ============================================================
# 3. LOAD
# ============================================================

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n📊 DATASET INFORMATION")
print("=" * 100)
print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 4. CHECK REGISTRY
# ============================================================

checks = {}

# ============================================================
# 5. COLUMN CHECK
# ============================================================

missing_columns = [
    col
    for col in EXPECTED_COLUMNS
    if col not in df.columns
]

extra_columns = [
    col
    for col in df.columns
    if col not in EXPECTED_COLUMNS
]

columns_ok = (
    not missing_columns
    and not extra_columns
    and df.columns.tolist() == EXPECTED_COLUMNS
)

checks["13 columns"] = columns_ok

print("\n🧪 COLUMN VALIDATION")
print("=" * 100)

if columns_ok:
    print("✅ All 13 required columns exist.")
    print("✅ Column order is correct.")
else:
    print("❌ Column validation failed.")
    print("Missing:", missing_columns)
    print("Extra:", extra_columns)

# ============================================================
# 6. ROW COUNT
# ============================================================

row_count_ok = (
    len(df) == EXPECTED_ROWS
)

checks["384 questions"] = row_count_ok

print("\n📦 ROW COUNT")
print("=" * 100)
print(f"Total questions: {len(df)}")

if row_count_ok:
    print("✅ Exactly 384 questions.")
else:
    print("❌ Expected 384 questions.")

# ============================================================
# 7. REQUIRED FIELD CHECK
# ============================================================

required_fields_ok = True

print("\n🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

if columns_ok:

    for col in EXPECTED_COLUMNS:

        missing = int(df[col].isna().sum())

        empty = int(
            df[col]
            .fillna("")
            .astype(str)
            .str.strip()
            .eq("")
            .sum()
        )

        print(
            f"{'✅' if missing == 0 and empty == 0 else '❌'} "
            f"{col:<15}"
            f"Missing: {missing:<3}"
            f"Empty: {empty:<3}"
        )

        if missing > 0 or empty > 0:
            required_fields_ok = False

else:
    required_fields_ok = False

checks["Required fields"] = required_fields_ok

# ============================================================
# 8. FAQ ID CHECK
# ============================================================

print("\n🆔 FAQ ID VALIDATION")
print("=" * 100)

if "faq_id" in df.columns:

    valid_id_format = (
        df["faq_id"]
        .astype(str)
        .str.fullmatch(r"FAQ\d{4}")
        .all()
    )

    duplicate_ids = (
        df[df["faq_id"].duplicated(keep=False)]
        .copy()
    )

    numeric_ids = pd.to_numeric(
        df["faq_id"]
        .astype(str)
        .str.extract(r"FAQ(\d{4})")[0],
        errors="coerce"
    )

    expected_numeric_ids = np.arange(
        1,
        EXPECTED_ROWS + 1
    )

    continuous_ids = (
        numeric_ids.notna().all()
        and numeric_ids.astype(int).tolist()
        == expected_numeric_ids.tolist()
    )

else:

    valid_id_format = False
    duplicate_ids = pd.DataFrame()
    continuous_ids = False

checks["Valid FAQ IDs"] = bool(valid_id_format)
checks["No duplicate IDs"] = duplicate_ids.empty
checks["Continuous IDs"] = bool(continuous_ids)

print(
    "✅ All FAQ IDs have valid format."
    if valid_id_format
    else "❌ Invalid FAQ ID format."
)

print(
    "✅ No duplicate FAQ IDs."
    if duplicate_ids.empty
    else f"❌ Duplicate FAQ IDs: {len(duplicate_ids)}"
)

print(
    "✅ IDs continuous: FAQ0001 → FAQ0384"
    if continuous_ids
    else "❌ FAQ IDs are not continuous/ordered."
)

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 10. EXACT DUPLICATES
# ============================================================

exact_duplicates = df[
    df["question"]
    .duplicated(keep=False)
].copy()

checks["No exact duplicates"] = (
    exact_duplicates.empty
)

print("\n📝 EXACT DUPLICATE CHECK")
print("=" * 100)

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 11. NORMALIZED DUPLICATES
# ============================================================

normalized_duplicates = df[
    df["_normalized_question"]
    .duplicated(keep=False)
].copy()

checks["No normalized duplicates"] = (
    normalized_duplicates.empty
)

print("\n🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 12. SAME-INTENT DUPLICATES
# ============================================================

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized_question"
        ],
        keep=False
    )
].copy()

checks["No same-intent duplicates"] = (
    same_intent_duplicates.empty
)

print("\n🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

if same_intent_duplicates.empty:
    print("✅ No normalized duplicates inside the same intent.")
else:
    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 13. INTENT MAPPING
# ============================================================

intent_mapping_ok = True

print("\n🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    actual_names = set(
        subset["intent_name"]
        .astype(str)
    )

    if len(subset) != 48:
        intent_mapping_ok = False

    if actual_names != {intent_name}:
        intent_mapping_ok = False

    print(
        f"{'✅' if len(subset) == 48 and actual_names == {intent_name} else '❌'} "
        f"{intent_id} → {intent_name} | rows={len(subset)}"
    )

unexpected_intents = (
    set(df["intent_id"])
    - set(EXPECTED_INTENTS.keys())
)

if unexpected_intents:
    intent_mapping_ok = False
    print(
        f"❌ Unexpected intent IDs: {unexpected_intents}"
    )

checks["Intent mappings"] = intent_mapping_ok

# ============================================================
# 14. LANGUAGE DISTRIBUTION
# ============================================================

language_counts = (
    df["language"]
    .value_counts()
)

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        int(language_counts.get(language, 0)) == 96
        for language in EXPECTED_LANGUAGES
    )
)

checks["Language balance"] = language_balance_ok

print("\n🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)
print(language_counts.to_string())

print(
    "✅ 96 questions × 4 languages."
    if language_balance_ok
    else "❌ Language balance failed."
)

# ============================================================
# 15. INTENT DISTRIBUTION
# ============================================================

intent_counts = (
    df["intent_id"]
    .value_counts()
)

intent_balance_ok = all(
    int(intent_counts.get(intent_id, 0)) == 48
    for intent_id in EXPECTED_INTENTS
)

checks["Intent balance"] = intent_balance_ok

print("\n🎯 INTENT DISTRIBUTION")
print("=" * 100)

print(
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .rename("questions")
    .reset_index()
    .to_string(index=False)
)

print(
    "✅ 48 questions × 8 intents."
    if intent_balance_ok
    else "❌ Intent balance failed."
)

# ============================================================
# 16. LANGUAGE × INTENT
# ============================================================

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

language_intent_ok = True

for intent_id in EXPECTED_INTENTS:
    for language in EXPECTED_LANGUAGES:

        count = int(
            language_intent.loc[
                intent_id,
                language
            ]
        )

        if count != 12:
            language_intent_ok = False

checks["Language × Intent"] = language_intent_ok

print("\n📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)
print(language_intent.to_string())

print(
    "✅ Every intent has 12 questions per language."
    if language_intent_ok
    else "❌ Language × Intent balance failed."
)

# ============================================================
# 17. QUESTION TYPES
# ============================================================

question_type_counts = (
    df["question_type"]
    .value_counts()
)

unexpected_types = (
    set(df["question_type"])
    - VALID_TYPES
)

question_types_ok = (
    not unexpected_types
    and question_type_counts.sum() == EXPECTED_ROWS
)

checks["Question types"] = question_types_ok

print("\n📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)
print(question_type_counts.to_string())

print(
    "✅ All question types are valid."
    if question_types_ok
    else f"❌ Invalid question types: {unexpected_types}"
)

# ============================================================
# 18. STATUS
# ============================================================

status_counts = (
    df["status"]
    .value_counts()
)

unexpected_status = (
    set(df["status"])
    - VALID_STATUS
)

status_ok = (
    not unexpected_status
)

checks["Status"] = status_ok

print("\n📌 STATUS DISTRIBUTION")
print("=" * 100)
print(status_counts.to_string())

print(
    "✅ Status values are valid."
    if status_ok
    else f"❌ Invalid status values: {unexpected_status}"
)

# ============================================================
# 19. DIFFICULTY
# ============================================================

difficulty_counts = (
    df["difficulty"]
    .value_counts()
)

unexpected_difficulty = (
    set(df["difficulty"])
    - VALID_DIFFICULTY
)

difficulty_ok = (
    not unexpected_difficulty
)

checks["Difficulty"] = difficulty_ok

print("\n📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)
print(difficulty_counts.to_string())

print(
    "✅ Difficulty values are valid."
    if difficulty_ok
    else f"❌ Invalid difficulty: {unexpected_difficulty}"
)

# ============================================================
# 20. GROUND TRUTH / ANSWERS
# ============================================================

ground_truth_ok = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_ok = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

checks["Ground truth"] = bool(ground_truth_ok)
checks["Answers"] = bool(answers_ok)

print("\n🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

print(
    "✅ Ground truth complete."
    if ground_truth_ok
    else "❌ Ground truth contains empty values."
)

print(
    "✅ Answers complete."
    if answers_ok
    else "❌ Answers contain empty values."
)

# ============================================================
# 21. GROUND TRUTH / ANSWER WORDING DIFFERENCE
# ============================================================

gt_norm = (
    df["ground_truth"]
    .map(normalize_text)
)

answer_norm = (
    df["answer"]
    .map(normalize_text)
)

answer_wording_difference = (
    gt_norm != answer_norm
)

print("\n🔗 GROUND TRUTH ↔ ANSWER")
print("=" * 100)

print(
    "Rows with different wording:",
    int(answer_wording_difference.sum())
)

print(
    "ℹ️ Different wording alone is not treated as an error."
)

# ============================================================
# 22. ATTEMPTS
# ============================================================

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

attempts_ok = (
    attempts_numeric.notna().all()
    and (attempts_numeric >= 0).all()
)

checks["Attempts"] = attempts_ok

print("\n🔢 ATTEMPTS")
print("=" * 100)

print(
    "✅ Attempts are numeric and non-negative."
    if attempts_ok
    else "❌ Invalid attempts values."
)

print(
    f"Min    : {attempts_numeric.min()}"
)
print(
    f"Max    : {attempts_numeric.max()}"
)
print(
    f"Average: {attempts_numeric.mean():.2f}"
)

# ============================================================
# 23. QUESTION LENGTH
# ============================================================

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

very_short_questions = df[
    question_lengths < 10
].copy()

question_length_ok = (
    very_short_questions.empty
)

checks["Question length"] = question_length_ok

print("\n📏 QUESTION LENGTH")
print("=" * 100)

print(
    f"Shortest : {question_lengths.min()}"
)
print(
    f"Longest  : {question_lengths.max()}"
)
print(
    f"Average  : {question_lengths.mean():.2f}"
)

print(
    "✅ No suspiciously short questions."
    if question_length_ok
    else "⚠️ Suspiciously short questions found."
)

# ============================================================
# 24. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n🔍 FULL QUESTION SIMILARITY")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.80:

        similarity_pairs.append({
            "similarity": round(score, 3),
            "faq_id_1": df.iloc[i]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "language_1": df.iloc[i]["language"],
            "question_1": questions[i],
            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "language_2": df.iloc[j]["language"],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(
    similarity_pairs
)

# ============================================================
# 25. SIMILARITY THRESHOLDS
# ============================================================

threshold_counts = {}

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    threshold_counts[threshold] = count

print("\n📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold, count in threshold_counts.items():
    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 26. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

print("\n🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

print("\n⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

# ============================================================
# 27. TOP SIMILAR PAIRS
# ============================================================

print("\n📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:
    print("None.")
else:
    print(
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 28. HIGH SIMILARITY DECISION
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"]
        >= SIMILARITY_THRESHOLD
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

similarity_ok = (
    high_similarity.empty
)

checks["Similarity < 0.85"] = similarity_ok

print("\n🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        f"❌ {len(high_similarity)} pairs >= 0.85"
    )

    print(
        high_similarity
        .sort_values(
            "similarity",
            ascending=False
        )
        .to_string(index=False)
    )

# ============================================================
# 29. SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed = sum(checks.values())
total = len(checks)

score = (
    passed / total * 100
)

print("-" * 100)
print(
    f"Passed checks      : "
    f"{passed}/{total}"
)

print(
    f"Validation Score   : "
    f"{score:.1f}%"
)

if score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 30. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 FINAL SUMMARY")
print("=" * 100)

print(f"Questions: {len(df)}")

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    intent_counts.to_string()
)

print("\nQuestion types:")
print(
    question_type_counts.to_string()
)

print("\nStatus:")
print(
    status_counts.to_string()
)

print("\nDifficulty:")
print(
    difficulty_counts.to_string()
)

print(
    "\nSimilarity >= 0.85:",
    len(high_similarity)
)

# ============================================================
# 31. READ-ONLY CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ Dataset was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 32. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=[
        "_normalized_question"
    ],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 COMPLETE 384-QUESTION AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE 384 DATASET AUDIT
====================================================================================================

📂 PROJECT
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 DATASET
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

✅ Project root found.
✅ Dataset found.

📊 DATASET INFORMATION
====================================================================================================
Rows    : 384
Columns : 13

🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

📦 ROW COUNT
====================================================================================================
Total questions: 384
✅ Exactly 384 questions.

🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0

🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ IDs continuous: FAQ0001 → FAQ0384

📝 EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ INT001 → hotel_location | rows=48
✅ INT002 → hotel_category | rows=48
✅ INT003 → reception_availability | rows=48
✅ INT004 → check_in_time | rows=48
✅ INT005 → check_out_time | rows=48
✅ INT006 → early_check_in | rows=48
✅ INT007 → late_check_out | rows=48
✅ INT008 → identification_required | rows=48

🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    96
Arabic     96
French     96
Russian    96
✅ 96 questions × 4 languages.

🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         48
   INT002          hotel_category         48
   INT003  reception_availability         48
   INT004           check_in_time         48
   INT005          check_out_time         48
   INT006          early_check_in         48
   INT007          late_check_out         48
   INT008 identification_required         48
✅ 48 questions × 8 intents.

📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         12       12      12       12
INT002         12       12      12       12
INT003         12       12      12       12
INT004         12       12      12       12
INT005         12       12      12       12
INT006         12       12      12       12
INT007         12       12      12       12
INT008         12       12      12       12
✅ Every intent has 12 questions per language.

📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    152
Direct         132
Scenario       100
✅ All question types are valid.

📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated    160
✅ Status values are valid.

📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    384
✅ Difficulty values are valid.

🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

🔗 GROUND TRUTH ↔ ANSWER
====================================================================================================
Rows with different wording: 345
ℹ️ Different wording alone is not treated as an error.

🔢 ATTEMPTS
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 6
Average: 0.35

📏 QUESTION LENGTH
====================================================================================================
Shortest : 31
Longest  : 186
Average  : 77.30
✅ No suspiciously short questions.

🔍 FULL QUESTION SIMILARITY
====================================================================================================
Comparing 73,536 question pairs...

📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 27 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 27

⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

📋 TOP 30 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1 language_1                                                                                                                              question_1 faq_id_2 intent_2 language_2                                                                                                                                                      question_2
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                                     What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                                                هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                                              هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                                        В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                                               Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.829  FAQ0004   INT001    English                                                                                          In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                                          Where can I find the Nile Pearl Hotel?
      0.828  FAQ0121   INT004    Russian                                                                                              Когда можно заселиться в Nile Pearl Hotel?  FAQ0125   INT004    Russian                                                                                                     Когда стандартно можно заселиться в отель Nile Pearl Hotel?
      0.827  FAQ0235   INT008     Arabic                                                                  هل يجب علي تقديم إثبات هوية ساري عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0237   INT008     Arabic                                                                              هل يحتاج الضيوف إلى تقديم وثائق إثبات الهوية عند تسجيل الوصول في Nile Pearl Hotel?
      0.824  FAQ0066   INT003    English                                                             What are the hours of operation for the reception desk at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.821  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0100   INT004    English                                                                                                    What time is check-in usually available at Nile Pearl Hotel?
      0.818  FAQ0017   INT001     French                                                                                                  Où se trouve l'hôtel Nile Pearl Hotel?  FAQ0019   INT001     French                                                                                                           Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.818  FAQ0223   INT007    Russian                     Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?  FAQ0224   INT007    Russian                      Могу ли я получить поздний выезд из Nile Pearl Hotel, и если это возможно, под какие условия и будут ли какие-либо дополнительные расходы?
      0.816  FAQ0025   INT001    Russian                                                                                      По какому адресу находится отель Nile Pearl Hotel?  FAQ0260   INT001    Russian                                                                                                         В каком районе города находится отель Nile Pearl Hotel?
      0.814  FAQ0233   INT008     Arabic                                                            ما نوع مستند إثبات الهوية المقبول عند تسجيل الوصول في فندق Nile Pearl Hotel؟  FAQ0234   INT008     Arabic                                                                                         ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?
      0.814  FAQ0222   INT007    Russian                                          Могу ли я получить поздний выезд из Nile Pearl Hotel, и какие возможны дополнительные расходы?  FAQ0223   INT007    Russian                                             Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?
      0.812  FAQ0044   INT002     Arabic                                                                                   كم عدد النجوم التي يُصنَّف بها فندق Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.811  FAQ0001   INT001    English                                                                                                      Where is Nile Pearl Hotel located?  FAQ0003   INT001    English                                                                                                                      In which city is Nile Pearl Hotel located?
      0.810  FAQ0312   INT006    Russian                                                              Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?  FAQ0376   INT006    Russian                                                                             Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?
      0.809  FAQ0003   INT001    English                                                                                              In which city is Nile Pearl Hotel located?  FAQ0258   INT001    English                                                                                                          Which part of the city is Nile Pearl Hotel located in?
      0.807  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0102   INT004    English                                                                                                       At what time can I normally check in at Nile Pearl Hotel?
      0.805  FAQ0204   INT007     Arabic                                           هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وما العوامل التي تحدد إمكانية ذلك؟  FAQ0205   INT007     Arabic                                                                                هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وهل توجد رسوم إضافية؟
      0.804  FAQ0045   INT002     Arabic                                                                                        ما فئة النجوم التي ينتمي إليها Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.804  FAQ0036   INT002    English                                                                                    What is the star classification of Nile Pearl Hotel?  FAQ0038   INT002    English                                                                                                       What star classification is assigned to Nile Pearl Hotel?
      0.804  FAQ0251   INT008    Russian                              Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0253   INT008    Russian                                                   Требуется ли гостям предъявлять документ, удостоверяющий личность, при регистрации заезда в Nile Pearl Hotel?
      0.802  FAQ0217   INT007    Russian                                                   Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, что мне нужно знать?  FAQ0218   INT007    Russian                                                                         Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?
      0.800  FAQ0137   INT005     Arabic                                                                      متى يجب على النزيل إتمام إجراءات تسجيل الخروج من Nile Pearl Hotel؟  FAQ0139   INT005     Arabic                                                                                         متى يجب على الضيوف إتمام تسجيل الخروج المعتاد من فندق Nile Pearl Hotel؟
      0.800  FAQ0085   INT003     French Si vous avez besoin d'aide urgente à l'hôtel Nile Pearl Hotel en pleine nuit, quelles sont les heures d'ouverture du service d'accueil?  FAQ0086   INT003     French Si vous avez besoin d'assistance tout au long de la journée ou de la nuit à l'hôtel Nile Pearl Hotel, quelles sont les heures d'ouverture du service d'accueil?
      0.800  FAQ0234   INT008     Arabic                                                                 ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0285   INT008     Arabic                                                                                                             ما هي وثيقة إثبات الهوية المطلوبة عند تسجيل الوصول؟

🚨 HIGH-SIMILARITY REVIEW
====================================================================================================
✅ No similarity >= 0.85.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 13 columns
✅ 384 questions
✅ Required fields
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Attempts
✅ Question length
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks      : 21/21
Validation Score   : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 FINAL SUMMARY
====================================================================================================
Questions: 384

Languages:
language
English    96
Arabic     96
French     96
Russian    96

Intents:
intent_id
INT001    48
INT002    48
INT003    48
INT004    48
INT005    48
INT006    48
INT007    48
INT008    48

Question types:
question_type
Paraphrased    152
Direct         132
Scenario       100

Status:
status
valid        224
generated    160

Difficulty:
difficulty
Easy    384

Similarity >= 0.85: 0

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ Dataset was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 COMPLETE 384-QUESTION AUDIT FINISHED
====================================================================================================

In [54]:
# ============================================================
# 🏨 HOTEL AI - VALIDATION SCORE FOR ALL 384 QUESTIONS
# READ-ONLY
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - 384 QUESTIONS VALIDATION SCORE")
print("=" * 100)

# ============================================================
# 1. PATH
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert DATASET_PATH.exists(), "❌ Dataset not found."

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print(f"\n📄 Dataset:\n{DATASET_PATH}")
print(f"📊 Questions: {len(df)}")

# ============================================================
# 2. EXPECTED STRUCTURE
# ============================================================

EXPECTED_ROWS = 384

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

# ============================================================
# 3. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# ============================================================
# 4. INDIVIDUAL SCORE CALCULATIONS
# ============================================================

score_checks = {}

# ------------------------------------------------------------
# CHECK 1 - ROW COUNT
# ------------------------------------------------------------

score_checks["Row Count"] = (
    len(df) == EXPECTED_ROWS
)

# ------------------------------------------------------------
# CHECK 2 - COLUMNS
# ------------------------------------------------------------

score_checks["Columns"] = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

# ------------------------------------------------------------
# CHECK 3 - REQUIRED FIELDS
# ------------------------------------------------------------

required_fields_ok = True

for col in EXPECTED_COLUMNS:

    if df[col].isna().any():
        required_fields_ok = False
        break

    if (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .any()
    ):
        required_fields_ok = False
        break

score_checks["Required Fields"] = required_fields_ok

# ------------------------------------------------------------
# CHECK 4 - FAQ ID FORMAT
# ------------------------------------------------------------

score_checks["FAQ ID Format"] = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

# ------------------------------------------------------------
# CHECK 5 - DUPLICATE IDS
# ------------------------------------------------------------

score_checks["Duplicate IDs"] = (
    not df["faq_id"].duplicated().any()
)

# ------------------------------------------------------------
# CHECK 6 - CONTINUOUS IDS
# ------------------------------------------------------------

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 385)
]

score_checks["Continuous IDs"] = (
    df["faq_id"].tolist()
    == expected_ids
)

# ------------------------------------------------------------
# NORMALIZED QUESTIONS
# ------------------------------------------------------------

df["_normalized"] = (
    df["question"]
    .map(normalize_question)
)

# ------------------------------------------------------------
# CHECK 7 - EXACT DUPLICATES
# ------------------------------------------------------------

score_checks["Exact Duplicates"] = (
    not df["question"].duplicated().any()
)

# ------------------------------------------------------------
# CHECK 8 - NORMALIZED DUPLICATES
# ------------------------------------------------------------

score_checks["Normalized Duplicates"] = (
    not df["_normalized"].duplicated().any()
)

# ------------------------------------------------------------
# CHECK 9 - SAME INTENT DUPLICATES
# ------------------------------------------------------------

same_intent_dupes = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized"
        ],
        keep=False
    )
]

score_checks["Same-Intent Duplicates"] = (
    same_intent_dupes.empty
)

# ------------------------------------------------------------
# CHECK 10 - INTENT MAPPING
# ------------------------------------------------------------

intent_mapping_ok = True

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    if len(subset) != 48:
        intent_mapping_ok = False
        break

    if set(subset["intent_name"]) != {intent_name}:
        intent_mapping_ok = False
        break

score_checks["Intent Mapping"] = (
    intent_mapping_ok
)

# ------------------------------------------------------------
# CHECK 11 - LANGUAGE BALANCE
# ------------------------------------------------------------

language_counts = (
    df["language"]
    .value_counts()
)

score_checks["Language Balance"] = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        language_counts.get(
            language,
            0
        ) == 96
        for language in EXPECTED_LANGUAGES
    )
)

# ------------------------------------------------------------
# CHECK 12 - INTENT BALANCE
# ------------------------------------------------------------

score_checks["Intent Balance"] = all(
    (
        df["intent_id"] == intent_id
    ).sum() == 48
    for intent_id in EXPECTED_INTENTS
)

# ------------------------------------------------------------
# CHECK 13 - LANGUAGE × INTENT
# ------------------------------------------------------------

matrix = pd.crosstab(
    df["intent_id"],
    df["language"]
)

score_checks["Language × Intent"] = all(
    matrix.loc[
        intent_id,
        language
    ] == 12

    for intent_id in EXPECTED_INTENTS

    for language in EXPECTED_LANGUAGES
)

# ------------------------------------------------------------
# CHECK 14 - QUESTION TYPES
# ------------------------------------------------------------

score_checks["Question Types"] = (
    set(df["question_type"])
    <= VALID_TYPES
)

# ------------------------------------------------------------
# CHECK 15 - STATUS
# ------------------------------------------------------------

score_checks["Status"] = (
    set(df["status"])
    <= VALID_STATUS
)

# ------------------------------------------------------------
# CHECK 16 - DIFFICULTY
# ------------------------------------------------------------

score_checks["Difficulty"] = (
    set(df["difficulty"])
    <= VALID_DIFFICULTY
)

# ------------------------------------------------------------
# CHECK 17 - GROUND TRUTH
# ------------------------------------------------------------

score_checks["Ground Truth"] = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ------------------------------------------------------------
# CHECK 18 - ANSWERS
# ------------------------------------------------------------

score_checks["Answers"] = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

# ------------------------------------------------------------
# CHECK 19 - ATTEMPTS
# ------------------------------------------------------------

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

score_checks["Attempts"] = (
    attempts_numeric.notna().all()
    and (attempts_numeric >= 0).all()
)

# ------------------------------------------------------------
# CHECK 20 - QUESTION LENGTH
# ------------------------------------------------------------

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

score_checks["Question Length"] = (
    not (question_lengths < 10).any()
)

# ============================================================
# 5. SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL SIMILARITY CHECK")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

high_similarity_count = 0

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_question(questions[i]),
        normalize_question(questions[j])
    ).ratio()

    if score >= 0.85:
        high_similarity_count += 1

score_checks["Similarity < 0.85"] = (
    high_similarity_count == 0
)

print(
    f"Pairs >= 0.85: {high_similarity_count}"
)

if high_similarity_count == 0:
    print("✅ No similarity >= 0.85.")
else:
    print(
        f"⚠️ {high_similarity_count} "
        f"high-similarity pairs found."
    )

# ============================================================
# 6. CALCULATE SCORE
# ============================================================

passed = sum(
    score_checks.values()
)

total = len(score_checks)

validation_score = (
    passed / total * 100
)

# ============================================================
# 7. DISPLAY EACH CHECK
# ============================================================

print("\n" + "=" * 100)
print("🏆 VALIDATION CHECKLIST")
print("=" * 100)

for check_name, result in score_checks.items():

    print(
        f"{'✅' if result else '❌'} "
        f"{check_name}"
    )

# ============================================================
# 8. FINAL SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

print(
    f"Passed Checks      : {passed}/{total}"
)

print(
    f"Validation Score   : {validation_score:.1f}%"
)

if validation_score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 9. DATASET SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 DATASET SUMMARY")
print("=" * 100)

print(
    f"Total Questions : {len(df)}"
)

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .to_string()
)

print("\nQuestion Types:")
print(
    df["question_type"]
    .value_counts()
    .to_string()
)

print("\nStatus:")
print(
    df["status"]
    .value_counts()
    .to_string()
)

print("\nDifficulty:")
print(
    df["difficulty"]
    .value_counts()
    .to_string()
)

# ============================================================
# 10. READ-ONLY CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 11. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=["_normalized"],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 VALIDATION SCORE CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - 384 QUESTIONS VALIDATION SCORE
====================================================================================================

📄 Dataset:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📊 Questions: 384

====================================================================================================
🔍 FULL SIMILARITY CHECK
====================================================================================================
Comparing 73,536 question pairs...
Pairs >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🏆 VALIDATION CHECKLIST
====================================================================================================
✅ Row Count
✅ Columns
✅ Required Fields
✅ FAQ ID Format
✅ Duplicate IDs
✅ Continuous IDs
✅ Exact Duplicates
✅ Normalized Duplicates
✅ Same-Intent Duplicates
✅ Intent Mapping
✅ Language Balance
✅ Intent Balance
✅ Language × Intent
✅ Question Types
✅ Status
✅ Difficulty
✅ Ground Truth
✅ Answers
✅ Attempts
✅ Question Length
✅ Similarity < 0.85

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
Passed Checks      : 21/21
Validation Score   : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 DATASET SUMMARY
====================================================================================================
Total Questions : 384

Languages:
language
English    96
Arabic     96
French     96
Russian    96

Intents:
intent_id  intent_name
INT001     hotel_location             48
INT002     hotel_category             48
INT003     reception_availability     48
INT004     check_in_time              48
INT005     check_out_time             48
INT006     early_check_in             48
INT007     late_check_out             48
INT008     identification_required    48

Question Types:
question_type
Paraphrased    152
Direct         132
Scenario       100

Status:
status
valid        224
generated    160

Difficulty:
difficulty
Easy    384

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 VALIDATION SCORE CHECK COMPLETE
====================================================================================================

In [55]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 GENERATION
# 32 NEW QUESTIONS ONLY
# CONTINUE FROM FAQ0384
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 GENERATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = (
    BATCH_DIR
    / "faq_batch_06.csv"
)

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert FINAL_DATASET.exists(), (
    f"❌ Final dataset not found:\n{FINAL_DATASET}"
)

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print("✅ Project root found.")
print("✅ Final dataset found.")

# ============================================================
# 2. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

assert len(df) == 384, (
    f"❌ Expected 384 existing questions, "
    f"found {len(df)}"
)

print("✅ Existing dataset contains exactly 384 questions.")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS, (
    "❌ Existing dataset column structure is incorrect."
)

print("✅ All 13 required columns exist.")

# ============================================================
# 4. FAQ ID CONTINUATION
# ============================================================

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = numeric_ids.max()

START_ID = last_id + 1
END_ID = START_ID + 32

assert START_ID == 385
assert END_ID == 417

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(
    f"New batch     : FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# ============================================================
# 5. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 6. BATCH 06 QUESTIONS
# ============================================================

questions = [

    # ========================================================
    # INT001 - HOTEL LOCATION
    # ========================================================

    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "في أي مدينة يوجد Nile Pearl Hotel؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Direct",
        "question": "Which city is Nile Pearl Hotel in?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Direct",
        "question": "Dans quelle ville se trouve le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Direct",
        "question": "В каком городе находится Nile Pearl Hotel?",
    },

    # ========================================================
    # INT002 - HOTEL CATEGORY
    # ========================================================

    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "قبل حجز الغرفة، كيف أعرف الفئة التي ينتمي إليها Nile Pearl Hotel؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Scenario",
        "question": "Before booking a room, how can I tell what category Nile Pearl Hotel belongs to?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Scenario",
        "question": "Avant de réserver une chambre, comment puis-je savoir à quelle catégorie appartient le Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Перед бронированием номера как узнать, к какой категории относится Nile Pearl Hotel?",
    },

    # ========================================================
    # INT003 - RECEPTION AVAILABILITY
    # ========================================================

    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل يمكنني التواصل مع مكتب الاستقبال في أي وقت؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I contact the reception desk at any time?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je contacter la réception à tout moment ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Могу ли я связаться со стойкой регистрации в любое время?",
    },

    # ========================================================
    # INT004 - CHECK IN TIME
    # ========================================================

    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما الساعة التي يُفتح فيها تسجيل الوصول المعتاد للضيوف؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "At what hour is regular guest check-in available?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "À partir de quelle heure l'enregistrement habituel est-il disponible pour les clients ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "С какого часа гостям доступна обычная регистрация заезда?",
    },

    # ========================================================
    # INT005 - CHECK OUT TIME
    # ========================================================

    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا كان يوم المغادرة قد حان، فما الوقت الذي يجب أن أخلي فيه الغرفة؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Scenario",
        "question": "When my departure day arrives, what time do I need to leave the room?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question_type": "Scenario",
        "question": "Le jour de mon départ, à quelle heure dois-je quitter la chambre ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "В день выезда в какое время мне нужно покинуть номер?",
    },

    # ========================================================
    # INT006 - EARLY CHECK IN
    # ========================================================

    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل يسمح الفندق بتسجيل الوصول قبل الموعد المقرر إذا كانت الغرفة جاهزة؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Does the hotel allow check-in before the scheduled time if the room is ready?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "L'hôtel autorise-t-il l'enregistrement avant l'heure prévue si la chambre est prête ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Разрешает ли отель заселение раньше назначенного времени, если номер уже готов?",
    },

    # ========================================================
    # INT007 - LATE CHECK OUT
    # ========================================================

    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا احتجت للبقاء لفترة أطول في يوم المغادرة، هل يمكنني طلب خروج متأخر؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I need to stay longer on my departure day, can I request a later check-out?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'ai besoin de rester plus longtemps le jour du départ, puis-je demander un départ tardif ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если мне нужно остаться подольше в день выезда, могу ли я попросить поздний выезд?",
    },

    # ========================================================
    # INT008 - IDENTIFICATION
    # ========================================================

    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "ما وثيقة الهوية التي يجب أن أقدمها عند تسجيل الوصول؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Direct",
        "question": "Which identification document must I present at check-in?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Direct",
        "question": "Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?",
    },
]

# ============================================================
# 7. STRUCTURE CHECK
# ============================================================

assert len(questions) == 32, (
    f"❌ Expected 32 questions, found {len(questions)}"
)

required_question_fields = [
    "intent_id",
    "language",
    "question_type",
    "question",
]

for index, item in enumerate(
    questions,
    start=1
):

    for field in required_question_fields:

        assert field in item, (
            f"❌ Question #{index} missing field: {field}"
        )

        assert str(item[field]).strip(), (
            f"❌ Question #{index} empty field: {field}"
        )

print("\n" + "=" * 100)
print("🧪 QUESTION STRUCTURE CHECK")
print("=" * 100)

print("✅ All 32 questions contain required fields.")

# ============================================================
# 8. BUILD DATAFRAME
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 06",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(
    batch,
    columns=REQUIRED_COLUMNS
)

# ============================================================
# 9. ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 ID VALIDATION")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(
        START_ID,
        END_ID
    )
]

assert batch_df["faq_id"].tolist() == expected_batch_ids
assert batch_df["faq_id"].is_unique

print(
    f"✅ IDs are exactly "
    f"FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}"
)

print("✅ No duplicate IDs.")

# ============================================================
# 10. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 11. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

batch_normalized = batch_df["question"].map(
    normalize_question
)

assert not batch_df["question"].duplicated().any()

assert not batch_normalized.duplicated().any()

print("✅ No duplicate questions inside Batch 06.")

# ============================================================
# 12. OVERLAP WITH EXISTING 384
# ============================================================

existing_normalized = set(
    df["question"].map(normalize_question)
)

overlap_mask = batch_normalized.isin(
    existing_normalized
)

assert not overlap_mask.any(), (
    "❌ Batch 06 contains a question "
    "already present in existing 384."
)

print("✅ No exact/normalized overlap with existing 384.")

# ============================================================
# 13. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 questions × 4 languages.")

# ============================================================
# 14. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 questions × 8 intents.")

# ============================================================
# 15. INTENT NAME CHECK
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 16. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

invalid_types = (
    set(batch_df["question_type"])
    - VALID_TYPES
)

assert not invalid_types

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 17. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 06 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 18. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 19. FINAL
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 06 READY")
print("=" * 100)

print(
    f"""
Existing dataset : {len(df)} questions
New batch        : {len(batch_df)} questions

FAQ IDs:
FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 384
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Project root found.
✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 384
Columns : 13
✅ Existing dataset contains exactly 384 questions.
✅ All 13 required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0384
New batch     : FAQ0385 → FAQ0416

====================================================================================================
🧪 QUESTION STRUCTURE CHECK
====================================================================================================
✅ All 32 questions contain required fields.

====================================================================================================
🆔 ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0385 → FAQ0416
✅ No duplicate IDs.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions inside Batch 06.

AssertionError: ❌ Batch 06 contains a question already present in existing 384.

In [56]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 OVERLAP DIAGNOSTIC
# READ-ONLY
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

# IMPORTANT:
# The batch file may NOT exist because the previous cell stopped
# before saving. لذلك نعيد بناء الأسئلة بنفس IDs من الخلية السابقة.

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 OVERLAP DIAGNOSTIC")
print("=" * 100)

assert len(df) == 384

# ============================================================
# NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# ============================================================
# BATCH 06 QUESTIONS FROM PREVIOUS CELL
# ============================================================

questions = [

    ("FAQ0385", "INT001", "Arabic",
     "في أي مدينة يوجد Nile Pearl Hotel؟"),

    ("FAQ0386", "INT001", "English",
     "Which city is Nile Pearl Hotel in?"),

    ("FAQ0387", "INT001", "French",
     "Dans quelle ville se trouve le Nile Pearl Hotel ?"),

    ("FAQ0388", "INT001", "Russian",
     "В каком городе находится Nile Pearl Hotel?"),

    ("FAQ0389", "INT002", "Arabic",
     "قبل حجز الغرفة، كيف أعرف الفئة التي ينتمي إليها Nile Pearl Hotel؟"),

    ("FAQ0390", "INT002", "English",
     "Before booking a room, how can I tell what category Nile Pearl Hotel belongs to?"),

    ("FAQ0391", "INT002", "French",
     "Avant de réserver une chambre, comment puis-je savoir à quelle catégorie appartient le Nile Pearl Hotel ?"),

    ("FAQ0392", "INT002", "Russian",
     "Перед бронированием номера как узнать, к какой категории относится Nile Pearl Hotel?"),

    ("FAQ0393", "INT003", "Arabic",
     "هل يمكنني التواصل مع مكتب الاستقبال في أي وقت؟"),

    ("FAQ0394", "INT003", "English",
     "Can I contact the reception desk at any time?"),

    ("FAQ0395", "INT003", "French",
     "Puis-je contacter la réception à tout moment ?"),

    ("FAQ0396", "INT003", "Russian",
     "Могу ли я связаться со стойкой регистрации в любое время?"),

    ("FAQ0397", "INT004", "Arabic",
     "ما الساعة التي يُفتح فيها تسجيل الوصول المعتاد للضيوف؟"),

    ("FAQ0398", "INT004", "English",
     "At what hour is regular guest check-in available?"),

    ("FAQ0399", "INT004", "French",
     "À partir de quelle heure l'enregistrement habituel est-il disponible pour les clients ?"),

    ("FAQ0400", "INT004", "Russian",
     "С какого часа гостям доступна обычная регистрация заезда؟"),

    ("FAQ0401", "INT005", "Arabic",
     "إذا كان يوم المغادرة قد حان، فما الوقت الذي يجب أن أخلي فيه الغرفة؟"),

    ("FAQ0402", "INT005", "English",
     "When my departure day arrives, what time do I need to leave the room?"),

    ("FAQ0403", "INT005", "French",
     "Le jour de mon départ, à quelle heure dois-je quitter la chambre ?"),

    ("FAQ0404", "INT005", "Russian",
     "В день выезда в какое время мне нужно покинуть номер?"),

    ("FAQ0405", "INT006", "Arabic",
     "هل يسمح الفندق بتسجيل الوصول قبل الموعد المقرر إذا كانت الغرفة جاهزة؟"),

    ("FAQ0406", "INT006", "English",
     "Does the hotel allow check-in before the scheduled time if the room is ready?"),

    ("FAQ0407", "INT006", "French",
     "L'hôtel autorise-t-il l'enregistrement avant l'heure prévue si la chambre est prête ?"),

    ("FAQ0408", "INT006", "Russian",
     "Разрешает ли отель заселение раньше назначенного времени, если номер уже готов؟"),

    ("FAQ0409", "INT007", "Arabic",
     "إذا احتجت للبقاء لفترة أطول في يوم المغادرة، هل يمكنني طلب خروج متأخر؟"),

    ("FAQ0410", "INT007", "English",
     "If I need to stay longer on my departure day, can I request a later check-out?"),

    ("FAQ0411", "INT007", "French",
     "Si j'ai besoin de rester plus longtemps le jour du départ, puis-je demander un départ tardif ?"),

    ("FAQ0412", "INT007", "Russian",
     "Если мне нужно остаться подольше в день выезда, могу ли я попросить поздний выезд?"),

    ("FAQ0413", "INT008", "Arabic",
     "ما وثيقة الهوية التي يجب أن أقدمها عند تسجيل الوصول؟"),

    ("FAQ0414", "INT008", "English",
     "Which identification document must I present at check-in?"),

    ("FAQ0415", "INT008", "French",
     "Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?"),

    ("FAQ0416", "INT008", "Russian",
     "Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда؟"),
]

batch_df = pd.DataFrame(
    questions,
    columns=[
        "faq_id",
        "intent_id",
        "language",
        "question",
    ]
)

# ============================================================
# NORMALIZED MAP
# ============================================================

existing_map = {}

for _, row in df.iterrows():

    normalized = normalize_question(
        row["question"]
    )

    existing_map.setdefault(
        normalized,
        []
    ).append({
        "faq_id": row["faq_id"],
        "intent_id": row["intent_id"],
        "language": row["language"],
        "question": row["question"],
    })

# ============================================================
# FIND OVERLAPS
# ============================================================

overlaps = []

for _, row in batch_df.iterrows():

    normalized = normalize_question(
        row["question"]
    )

    if normalized in existing_map:

        for old in existing_map[normalized]:

            overlaps.append({
                "new_faq_id": row["faq_id"],
                "new_intent": row["intent_id"],
                "new_language": row["language"],
                "new_question": row["question"],
                "existing_faq_id": old["faq_id"],
                "existing_intent": old["intent_id"],
                "existing_language": old["language"],
                "existing_question": old["question"],
            })

# ============================================================
# RESULT
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP RESULT")
print("=" * 100)

if not overlaps:

    print("✅ No normalized overlap found.")

else:

    overlap_df = pd.DataFrame(overlaps)

    print(
        f"❌ Overlaps found: {len(overlap_df)}"
    )

    print(
        overlap_df.to_string(
            index=False
        )
    )

# ============================================================
# SAVE DIAGNOSTIC ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ Batch 06 was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")

====================================================================================================
🏨 HOTEL AI - BATCH 06 OVERLAP DIAGNOSTIC
====================================================================================================

====================================================================================================
🔎 OVERLAP RESULT
====================================================================================================
❌ Overlaps found: 1
new_faq_id new_intent new_language                                                         new_question existing_faq_id existing_intent existing_language                                                    existing_question
   FAQ0415     INT008       French Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?         FAQ0287          INT008            French Quelle pièce d'identité dois-je présenter lors de l'enregistrement ?

====================================================================================================
🔒 READ-ONLY
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ Batch 06 was NOT modified.
✅ No rows added.
✅ No rows deleted.

In [57]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 FIX FAQ0415
# ONLY REPAIRS THE DUPLICATE QUESTION
# ============================================================

from pathlib import Path
import pandas as pd
import unicodedata
import re

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 DUPLICATE REPAIR")
print("=" * 100)

# ------------------------------------------------------------
# IMPORTANT
# Previous generation stopped before saving because of the
# overlap assertion, so recreate Batch 06 if the file does
# not exist yet.
# ------------------------------------------------------------

questions = [

    ("FAQ0385", "INT001", "Arabic",
     "في أي مدينة يوجد Nile Pearl Hotel؟"),

    ("FAQ0386", "INT001", "English",
     "Which city is Nile Pearl Hotel in?"),

    ("FAQ0387", "INT001", "French",
     "Dans quelle ville se trouve le Nile Pearl Hotel ?"),

    ("FAQ0388", "INT001", "Russian",
     "В каком городе находится Nile Pearl Hotel?"),

    ("FAQ0389", "INT002", "Arabic",
     "قبل حجز الغرفة، كيف أعرف الفئة التي ينتمي إليها Nile Pearl Hotel؟"),

    ("FAQ0390", "INT002", "English",
     "Before booking a room, how can I tell what category Nile Pearl Hotel belongs to?"),

    ("FAQ0391", "INT002", "French",
     "Avant de réserver une chambre, comment puis-je savoir à quelle catégorie appartient le Nile Pearl Hotel ?"),

    ("FAQ0392", "INT002", "Russian",
     "Перед бронированием номера как узнать, к какой категории относится Nile Pearl Hotel?"),

    ("FAQ0393", "INT003", "Arabic",
     "هل يمكنني التواصل مع مكتب الاستقبال في أي وقت؟"),

    ("FAQ0394", "INT003", "English",
     "Can I contact the reception desk at any time?"),

    ("FAQ0395", "INT003", "French",
     "Puis-je contacter la réception à tout moment ?"),

    ("FAQ0396", "INT003", "Russian",
     "Могу ли я связаться со стойкой регистрации в любое время?"),

    ("FAQ0397", "INT004", "Arabic",
     "ما الساعة التي يُفتح فيها تسجيل الوصول المعتاد للضيوف؟"),

    ("FAQ0398", "INT004", "English",
     "At what hour is regular guest check-in available?"),

    ("FAQ0399", "INT004", "French",
     "À partir de quelle heure l'enregistrement habituel est-il disponible pour les clients ?"),

    ("FAQ0400", "INT004", "Russian",
     "С какого часа гостям доступна обычная регистрация заезда?"),

    ("FAQ0401", "INT005", "Arabic",
     "إذا كان يوم المغادرة قد حان، فما الوقت الذي يجب أن أخلي فيه الغرفة؟"),

    ("FAQ0402", "INT005", "English",
     "When my departure day arrives, what time do I need to leave the room?"),

    ("FAQ0403", "INT005", "French",
     "Le jour de mon départ, à quelle heure dois-je quitter la chambre ?"),

    ("FAQ0404", "INT005", "Russian",
     "В день выезда в какое время мне нужно покинуть номер?"),

    ("FAQ0405", "INT006", "Arabic",
     "هل يسمح الفندق بتسجيل الوصول قبل الموعد المقرر إذا كانت الغرفة جاهزة؟"),

    ("FAQ0406", "INT006", "English",
     "Does the hotel allow check-in before the scheduled time if the room is ready?"),

    ("FAQ0407", "INT006", "French",
     "L'hôtel autorise-t-il l'enregistrement avant l'heure prévue si la chambre est prête ?"),

    ("FAQ0408", "INT006", "Russian",
     "Разрешает ли отель заселение раньше назначенного времени, если номер уже готов?"),

    ("FAQ0409", "INT007", "Arabic",
     "إذا احتجت للبقاء لفترة أطول في يوم المغادرة، هل يمكنني طلب خروج متأخر؟"),

    ("FAQ0410", "INT007", "English",
     "If I need to stay longer on my departure day, can I request a later check-out?"),

    ("FAQ0411", "INT007", "French",
     "Si j'ai besoin de rester plus longtemps le jour du départ, puis-je demander un départ tardif ?"),

    ("FAQ0412", "INT007", "Russian",
     "Если мне нужно остаться подольше в день выезда, могу ли я попросить поздний выезд?"),

    ("FAQ0413", "INT008", "Arabic",
     "ما وثيقة الهوية التي يجب أن أقدمها عند تسجيل الوصول؟"),

    ("FAQ0414", "INT008", "English",
     "Which identification document must I present at check-in?"),

    # FIXED QUESTION
    ("FAQ0415", "INT008", "French",
     "Quel justificatif d'identité dois-je fournir lors de mon arrivée à l'hôtel ?"),

    ("FAQ0416", "INT008", "Russian",
     "Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?"),
]

batch_df = pd.DataFrame(
    questions,
    columns=[
        "faq_id",
        "intent_id",
        "language",
        "question",
    ]
)

# ------------------------------------------------------------
# INTENT NAMES
# ------------------------------------------------------------

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

QUESTION_TYPES = {
    "INT001": "Direct",
    "INT002": "Scenario",
    "INT003": "Paraphrased",
    "INT004": "Paraphrased",
    "INT005": "Scenario",
    "INT006": "Paraphrased",
    "INT007": "Scenario",
    "INT008": "Direct",
}

# ------------------------------------------------------------
# EXISTING DATASET
# ------------------------------------------------------------

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(df) == 384

# ------------------------------------------------------------
# NORMALIZATION
# ------------------------------------------------------------

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ------------------------------------------------------------
# BUILD FINAL BATCH WITH ALL 13 COLUMNS
# ------------------------------------------------------------

final_batch = []

for _, row in batch_df.iterrows():

    intent_id = row["intent_id"]

    final_batch.append({
        "faq_id": row["faq_id"],
        "intent_id": intent_id,
        "language": row["language"],
        "question_type": QUESTION_TYPES[intent_id],
        "question": row["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 06",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(final_batch)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

assert len(batch_df) == 32

assert batch_df["faq_id"].tolist() == [
    f"FAQ{i:04d}"
    for i in range(385, 417)
]

assert batch_df["faq_id"].is_unique

batch_norm = batch_df["question"].map(normalize)

assert not batch_norm.duplicated().any()

existing_norm = set(
    df["question"].map(normalize)
)

overlap_mask = batch_norm.isin(
    existing_norm
)

if overlap_mask.any():

    print("\n❌ OVERLAP STILL EXISTS:")

    print(
        batch_df.loc[
            overlap_mask,
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

    raise AssertionError(
        "❌ Batch 06 still contains overlap."
    )

print("\n✅ FAQ0415 duplicate repaired.")
print("✅ No duplicate questions inside Batch 06.")
print("✅ No normalized overlap with existing 384.")

# ------------------------------------------------------------
# SAVE BATCH
# ------------------------------------------------------------

BATCH_DIR = BATCH_FILE.parent
BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 06 UPDATED")
print("=" * 100)

print(BATCH_FILE)
print("✅ 32 rows saved.")
print("✅ hotel_faq_final.csv was NOT modified.")

print("\n" + "=" * 100)
print("🎉 BATCH 06 DUPLICATE REPAIR COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 DUPLICATE REPAIR
====================================================================================================

✅ FAQ0415 duplicate repaired.
✅ No duplicate questions inside Batch 06.
✅ No normalized overlap with existing 384.

====================================================================================================
💾 BATCH 06 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_06.csv
✅ 32 rows saved.
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🎉 BATCH 06 DUPLICATE REPAIR COMPLETE
====================================================================================================

In [58]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 FINAL SIMILARITY CHECK
# Existing dataset : 384
# Batch 06         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 FINAL SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 06 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 384
assert len(batch_df) == 32

print(f"Existing questions : {len(df)}")
print(f"Batch 06 questions : {len(batch_df)}")

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 06 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(385, 417)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0385 → FAQ0416.")
print("✅ No duplicate IDs.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:

    print("❌ Exact overlaps found:")
    for q in exact_overlap:
        print("-", q)

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize_question)
)

batch_normalized = set(
    batch_df["question"].map(normalize_question)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for q in normalized_overlap:
        print("-", q)

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 06")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(keep=False)
]

normalized_series = batch_df[
    "question"
].map(normalize_question)

normalized_duplicates = batch_df[
    normalized_series.duplicated(keep=False)
]

assert exact_duplicates.empty
assert normalized_duplicates.empty

print("✅ No exact duplicates inside Batch 06.")
print("✅ No normalized duplicates inside Batch 06.")

# ============================================================
# 9. SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize_question(
                new_row["question"]
            ),
            normalize_question(
                old_row["question"]
            )
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 10. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 12. CROSS INTENT
# ============================================================

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30).to_string(
            index=False
        )
    )

# ============================================================
# 13. HIGH SIMILARITY
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(
            index=False
        )
    )

# ============================================================
# 14. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 06 FINAL RESULT")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and high_similarity.empty
    and cross_intent.empty
):

    print("""
🟢 BATCH 06 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 06
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS
""")

else:

    print("""
🟡 BATCH 06 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.
""")

# ============================================================
# 15. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_06.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 06 SIMILARITY CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 FINAL SIMILARITY CHECK
====================================================================================================
Existing questions : 384
Batch 06 questions : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 06 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0385 → FAQ0416.
✅ No duplicate IDs.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 06
====================================================================================================
✅ No exact duplicates inside Batch 06.
✅ No normalized duplicates inside Batch 06.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs >= 0.80: 7
 similarity new_faq_id new_intent new_language                                                                      new_question old_faq_id old_intent old_language                                                             old_question
      0.953    FAQ0416     INT008      Russian Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?    FAQ0288     INT008      Russian Какой документ удостоверяющий личность нужно предъявить при регистрации?
      0.878    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0019     INT001       French                    Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.860    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0259     INT001       French           Dans quel quartier de la ville se trouve le Nile Pearl Hotel ?
      0.842    FAQ0388     INT001      Russian                                        В каком городе находится Nile Pearl Hotel?    FAQ0260     INT001      Russian                  В каком районе города находится отель Nile Pearl Hotel?
      0.841    FAQ0388     INT001      Russian                                        В каком городе находится Nile Pearl Hotel?    FAQ0059     INT002      Russian                         В каком классе отеля находится Nile Pearl Hotel?
      0.838    FAQ0386     INT001      English                                                Which city is Nile Pearl Hotel in?    FAQ0003     INT001      English                               In which city is Nile Pearl Hotel located?
      0.800    FAQ0388     INT001      Russian                                        В каком городе находится Nile Pearl Hotel?    FAQ0025     INT001      Russian                       По какому адресу находится отель Nile Pearl Hotel?

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 7 pairs
0.85+ : 3 pairs
0.90+ : 1 pairs
0.95+ : 1 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 6
 similarity new_faq_id new_intent new_language                                                                      new_question old_faq_id old_intent old_language                                                             old_question
      0.953    FAQ0416     INT008      Russian Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?    FAQ0288     INT008      Russian Какой документ удостоверяющий личность нужно предъявить при регистрации?
      0.878    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0019     INT001       French                    Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.860    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0259     INT001       French           Dans quel quartier de la ville se trouve le Nile Pearl Hotel ?
      0.842    FAQ0388     INT001      Russian                                        В каком городе находится Nile Pearl Hotel?    FAQ0260     INT001      Russian                  В каком районе города находится отель Nile Pearl Hotel?
      0.838    FAQ0386     INT001      English                                                Which city is Nile Pearl Hotel in?    FAQ0003     INT001      English                               In which city is Nile Pearl Hotel located?
      0.800    FAQ0388     INT001      Russian                                        В каком городе находится Nile Pearl Hotel?    FAQ0025     INT001      Russian                       По какому адресу находится отель Nile Pearl Hotel?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 1
 similarity new_faq_id new_intent new_language                               new_question old_faq_id old_intent old_language                                     old_question
      0.841    FAQ0388     INT001      Russian В каком городе находится Nile Pearl Hotel?    FAQ0059     INT002      Russian В каком классе отеля находится Nile Pearl Hotel?

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 3
 similarity new_faq_id new_intent new_language                                                                      new_question old_faq_id old_intent old_language                                                             old_question
      0.953    FAQ0416     INT008      Russian Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?    FAQ0288     INT008      Russian Какой документ удостоверяющий личность нужно предъявить при регистрации?
      0.878    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0019     INT001       French                    Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.860    FAQ0387     INT001       French                                 Dans quelle ville se trouve le Nile Pearl Hotel ?    FAQ0259     INT001       French           Dans quel quartier de la ville se trouve le Nile Pearl Hotel ?

====================================================================================================
🏆 BATCH 06 FINAL RESULT
====================================================================================================

🟡 BATCH 06 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_06.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 06 SIMILARITY CHECK COMPLETE
====================================================================================================

In [59]:
from pathlib import Path
import pandas as pd
import unicodedata
import re

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

rewrites = {

    # INT001 French
    "FAQ0387":
        "Pouvez-vous me préciser où se situe le Nile Pearl Hotel au Caire ?",

    # INT001 Russian
    "FAQ0388":
        "Где в Каире расположен Nile Pearl Hotel?",

    # INT001 English
    "FAQ0386":
        "In which part of Cairo should I look for Nile Pearl Hotel?",

    # INT008 Russian
    "FAQ0416":
        "Какой вид удостоверения личности требуется гостю при заселении?",

}

for faq_id, new_question in rewrites.items():

    matches = batch_df.index[
        batch_df["faq_id"] == faq_id
    ].tolist()

    assert len(matches) == 1, (
        f"❌ {faq_id} not found exactly once."
    )

    idx = matches[0]

    old_question = batch_df.at[
        idx,
        "question"
    ]

    batch_df.at[
        idx,
        "question"
    ] = new_question

    print(f"\n🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    return re.sub(
        r"\s+",
        " ",
        text
    ).strip()

# ============================================================
# BASIC CHECK
# ============================================================

assert len(batch_df) == 32
assert batch_df["faq_id"].is_unique

normalized = batch_df["question"].map(normalize)

assert not batch_df["question"].duplicated().any()
assert not normalized.duplicated().any()

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 06 UPDATED")
print("=" * 100)

print(BATCH_FILE)
print("✅ 32 rows preserved.")
print("✅ hotel_faq_final.csv was NOT modified.")

🔄 FAQ0387
OLD: Dans quelle ville se trouve le Nile Pearl Hotel ?
NEW: Pouvez-vous me préciser où se situe le Nile Pearl Hotel au Caire ?

🔄 FAQ0388
OLD: В каком городе находится Nile Pearl Hotel?
NEW: Где в Каире расположен Nile Pearl Hotel?

🔄 FAQ0386
OLD: Which city is Nile Pearl Hotel in?
NEW: In which part of Cairo should I look for Nile Pearl Hotel?

🔄 FAQ0416
OLD: Какой документ, удостоверяющий личность, нужно предъявить при регистрации заезда?
NEW: Какой вид удостоверения личности требуется гостю при заселении?

====================================================================================================
💾 BATCH 06 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_06.csv
✅ 32 rows preserved.
✅ hotel_faq_final.csv was NOT modified.

In [61]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT
# Existing dataset : 384
# Batch 06         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 06 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 384
assert len(batch_df) == 32

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 06         : {len(batch_df)} rows")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 5. BATCH ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(385, 417)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0385 → FAQ0416.")
print("✅ No duplicate IDs.")

# ============================================================
# 6. CHECK ID OVERLAP
# ============================================================

id_overlap = set(
    df["faq_id"]
).intersection(
    set(batch_df["faq_id"])
)

assert not id_overlap

print("✅ No ID overlap with existing 384.")

# ============================================================
# 7. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

required_ok = True

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{'✅' if missing == 0 and empty == 0 else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if missing or empty:
        required_ok = False

assert required_ok

print("✅ All required fields complete.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK INSIDE BATCH 06")
print("=" * 100)

exact_dupes = batch_df[
    batch_df["question"].duplicated(keep=False)
]

batch_norm = batch_df["question"].map(normalize)

normalized_dupes = batch_df[
    batch_norm.duplicated(keep=False)
]

assert exact_dupes.empty
assert normalized_dupes.empty

print("✅ No exact duplicates.")
print("✅ No normalized duplicates.")

# ============================================================
# 9. OVERLAP WITH EXISTING 384
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP WITH EXISTING 384")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

existing_normalized = set(
    df["question"].map(normalize)
)

normalized_overlap = sorted(
    set(batch_norm).intersection(
        existing_normalized
    )
)

assert not exact_overlap
assert not normalized_overlap

print("✅ No exact overlap.")
print("✅ No normalized overlap.")

# ============================================================
# 10. INTENT VALIDATION
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

VALID_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

print("\n" + "=" * 100)
print("🎯 INTENT VALIDATION")
print("=" * 100)

intent_counts = batch_df["intent_id"].value_counts()

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

for _, row in batch_df.iterrows():

    assert row["intent_id"] in INTENTS

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print(intent_counts.to_string())
print("✅ 4 questions × 8 intents.")
print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 11. LANGUAGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE VALIDATION")
print("=" * 100)

language_counts = batch_df["language"].value_counts()

assert set(language_counts.index) == VALID_LANGUAGES

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print(language_counts.to_string())
print("✅ 8 questions × 4 languages.")

# ============================================================
# 12. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE VALIDATION")
print("=" * 100)

assert set(
    batch_df["question_type"]
) <= VALID_TYPES

print(
    batch_df["question_type"]
    .value_counts()
    .to_string()
)

print("✅ All question types are valid.")

# ============================================================
# 13. STATUS / DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS / DIFFICULTY")
print("=" * 100)

assert set(batch_df["status"]) <= {
    "valid",
    "generated"
}

assert set(batch_df["difficulty"]) <= {
    "Easy"
}

print("Status:")
print(
    batch_df["status"]
    .value_counts()
    .to_string()
)

print("\nDifficulty:")
print(
    batch_df["difficulty"]
    .value_counts()
    .to_string()
)

print("✅ Status and difficulty values valid.")

# ============================================================
# 14. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

ground_truth_complete = (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_complete = (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print(
    "✅ Ground truth complete."
    if ground_truth_complete
    else "⚠️ Ground truth not filled yet."
)

print(
    "✅ Answers complete."
    if answers_complete
    else "⚠️ Answers not filled yet."
)

# ============================================================
# 15. QUESTION LENGTH
# ============================================================

print("\n" + "=" * 100)
print("📏 QUESTION LENGTH")
print("=" * 100)

lengths = (
    batch_df["question"]
    .astype(str)
    .str.len()
)

print(f"Shortest : {lengths.min()}")
print(f"Longest  : {lengths.max()}")
print(f"Average  : {lengths.mean():.2f}")

short_questions = batch_df[
    lengths < 10
]

assert short_questions.empty

print("✅ No suspiciously short questions.")

# ============================================================
# 16. FULL SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL SIMILARITY CHECK")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df.head(30)
        .to_string(index=False)
    )

# ============================================================
# 17. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    count = (
        0
        if similarity_df.empty
        else int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )
    )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 18. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

# ============================================================
# 19. HIGH SIMILARITY
# ============================================================

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(index=False)
    )

# ============================================================
# 20. FINAL DECISION
# ============================================================

batch_structure_ok = (
    len(batch_df) == 32
    and batch_df["faq_id"].is_unique
    and exact_dupes.empty
    and normalized_dupes.empty
    and not exact_overlap
    and not normalized_overlap
)

similarity_ok = (
    high_similarity.empty
    and cross_intent.empty
)

print("\n" + "=" * 100)
print("🏆 BATCH 06 COMPLETE AUDIT RESULT")
print("=" * 100)

if batch_structure_ok and similarity_ok:

    print("""
🟢 BATCH 06 PASSED STRUCTURAL + SIMILARITY CHECK

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 384
✅ Language balance correct
✅ Intent balance correct
✅ Intent names correct
✅ Question types valid
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
""")

else:

    print("""
🟡 BATCH 06 NEEDS REVIEW

⚠️ One or more checks require attention.
""")

# ============================================================
# 21. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_06.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 06 COMPLETE AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 384 rows
Batch 06         : 32 rows
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0385 → FAQ0416.
✅ No duplicate IDs.
✅ No ID overlap with existing 384.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
❌ ground_truth   Missing: 32 Empty: 32
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
❌ answer         Missing: 32 Empty: 32

AssertionError:

In [62]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 REPAIR
# FILL GROUND TRUTH + ANSWER
# DOES NOT MODIFY FINAL DATASET
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 GROUND TRUTH + ANSWER REPAIR")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 384
assert len(batch_df) == 32

print(f"Existing dataset : {len(df)}")
print(f"Batch 06         : {len(batch_df)}")

# ============================================================
# 3. CONVERT TEXT COLUMNS
# ============================================================

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 4. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 5. BUILD KNOWLEDGE MAP
# ============================================================
# Use the existing 384 as source of truth.
# One canonical answer per Intent × Language.

print("\n" + "=" * 100)
print("🧠 BUILDING KNOWLEDGE MAP")
print("=" * 100)

knowledge_map = {}

for intent_id, intent_name in INTENTS.items():

    for language in [
        "Arabic",
        "English",
        "French",
        "Russian",
    ]:

        subset = df[
            (df["intent_id"] == intent_id)
            &
            (df["language"] == language)
        ].copy()

        assert len(subset) == 12, (
            f"❌ Expected 12 rows for "
            f"{intent_id} × {language}, "
            f"found {len(subset)}"
        )

        # ----------------------------------------------------
        # Ground Truth
        # ----------------------------------------------------

        gt = (
            subset["ground_truth"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        gt = gt[gt.ne("")]

        assert not gt.empty, (
            f"❌ No ground truth for "
            f"{intent_id} × {language}"
        )

        canonical_gt = (
            gt.value_counts()
            .index[0]
        )

        # ----------------------------------------------------
        # Answer
        # ----------------------------------------------------

        answers = (
            subset["answer"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        answers = answers[
            answers.ne("")
        ]

        assert not answers.empty, (
            f"❌ No answer for "
            f"{intent_id} × {language}"
        )

        canonical_answer = (
            answers.value_counts()
            .index[0]
        )

        knowledge_map[
            (intent_id, language)
        ] = {
            "ground_truth": canonical_gt,
            "answer": canonical_answer,
        }

        print(
            f"✅ {intent_id:<6} {language:<8}"
        )

print("✅ Knowledge map created.")

# ============================================================
# 6. APPLY
# ============================================================

print("\n" + "=" * 100)
print("✍️ FILLING GROUND TRUTH + ANSWERS")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(
        row["intent_id"]
    ).strip()

    language = str(
        row["language"]
    ).strip()

    knowledge = knowledge_map[
        (intent_id, language)
    ]

    batch_df.at[
        idx,
        "ground_truth"
    ] = knowledge["ground_truth"]

    batch_df.at[
        idx,
        "answer"
    ] = knowledge["answer"]

    batch_df.at[
        idx,
        "status"
    ] = "generated"

    batch_df.at[
        idx,
        "category"
    ] = "Hotel FAQ"

    batch_df.at[
        idx,
        "source"
    ] = "Generated Batch 06"

    batch_df.at[
        idx,
        "attempts"
    ] = 0

    batch_df.at[
        idx,
        "difficulty"
    ] = "Easy"

# Restore text dtype
for col in TEXT_COLUMNS:

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

print("✅ Ground truth filled for all 32.")
print("✅ Answers filled for all 32.")

# ============================================================
# 7. VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in TEXT_COLUMNS + ["attempts"]:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{'✅' if missing == 0 and empty == 0 else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 8. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 9. RELOAD
# ============================================================

check = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(check) == 32

assert (
    check["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    check["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("\n" + "=" * 100)
print("🏆 BATCH 06 REPAIR RESULT")
print("=" * 100)

print("""
🟢 BATCH 06 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ Existing 384 dataset NOT modified

🎉 READY FOR FINAL BATCH 06 VALIDATION
""")

print("📄 Batch:")
print(BATCH_FILE)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 GROUND TRUTH + ANSWER REPAIR
====================================================================================================
Existing dataset : 384
Batch 06         : 32

====================================================================================================
🧠 BUILDING KNOWLEDGE MAP
====================================================================================================
✅ INT001 Arabic
✅ INT001 English
✅ INT001 French
✅ INT001 Russian
✅ INT002 Arabic
✅ INT002 English
✅ INT002 French
✅ INT002 Russian
✅ INT003 Arabic
✅ INT003 English
✅ INT003 French
✅ INT003 Russian
✅ INT004 Arabic
✅ INT004 English
✅ INT004 French
✅ INT004 Russian
✅ INT005 Arabic
✅ INT005 English
✅ INT005 French
✅ INT005 Russian
✅ INT006 Arabic
✅ INT006 English
✅ INT006 French
✅ INT006 Russian
✅ INT007 Arabic
✅ INT007 English
✅ INT007 French
✅ INT007 Russian
✅ INT008 Arabic
✅ INT008 English
✅ INT008 French
✅ INT008 Russian
✅ Knowledge map created.

====================================================================================================
✍️ FILLING GROUND TRUTH + ANSWERS
====================================================================================================
✅ Ground truth filled for all 32.
✅ Answers filled for all 32.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
🏆 BATCH 06 REPAIR RESULT
====================================================================================================

🟢 BATCH 06 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ Existing 384 dataset NOT modified

🎉 READY FOR FINAL BATCH 06 VALIDATION

📄 Batch:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_06.csv
====================================================================================================

In [63]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 REPAIR
# FILL GROUND TRUTH + ANSWER
# DOES NOT MODIFY FINAL DATASET
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 GROUND TRUTH + ANSWER REPAIR")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 384
assert len(batch_df) == 32

print(f"Existing dataset : {len(df)}")
print(f"Batch 06         : {len(batch_df)}")

# ============================================================
# 3. CONVERT TEXT COLUMNS
# ============================================================

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 4. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 5. BUILD KNOWLEDGE MAP
# ============================================================
# Use the existing 384 as source of truth.
# One canonical answer per Intent × Language.

print("\n" + "=" * 100)
print("🧠 BUILDING KNOWLEDGE MAP")
print("=" * 100)

knowledge_map = {}

for intent_id, intent_name in INTENTS.items():

    for language in [
        "Arabic",
        "English",
        "French",
        "Russian",
    ]:

        subset = df[
            (df["intent_id"] == intent_id)
            &
            (df["language"] == language)
        ].copy()

        assert len(subset) == 12, (
            f"❌ Expected 12 rows for "
            f"{intent_id} × {language}, "
            f"found {len(subset)}"
        )

        # ----------------------------------------------------
        # Ground Truth
        # ----------------------------------------------------

        gt = (
            subset["ground_truth"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        gt = gt[gt.ne("")]

        assert not gt.empty, (
            f"❌ No ground truth for "
            f"{intent_id} × {language}"
        )

        canonical_gt = (
            gt.value_counts()
            .index[0]
        )

        # ----------------------------------------------------
        # Answer
        # ----------------------------------------------------

        answers = (
            subset["answer"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        answers = answers[
            answers.ne("")
        ]

        assert not answers.empty, (
            f"❌ No answer for "
            f"{intent_id} × {language}"
        )

        canonical_answer = (
            answers.value_counts()
            .index[0]
        )

        knowledge_map[
            (intent_id, language)
        ] = {
            "ground_truth": canonical_gt,
            "answer": canonical_answer,
        }

        print(
            f"✅ {intent_id:<6} {language:<8}"
        )

print("✅ Knowledge map created.")

# ============================================================
# 6. APPLY
# ============================================================

print("\n" + "=" * 100)
print("✍️ FILLING GROUND TRUTH + ANSWERS")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(
        row["intent_id"]
    ).strip()

    language = str(
        row["language"]
    ).strip()

    knowledge = knowledge_map[
        (intent_id, language)
    ]

    batch_df.at[
        idx,
        "ground_truth"
    ] = knowledge["ground_truth"]

    batch_df.at[
        idx,
        "answer"
    ] = knowledge["answer"]

    batch_df.at[
        idx,
        "status"
    ] = "generated"

    batch_df.at[
        idx,
        "category"
    ] = "Hotel FAQ"

    batch_df.at[
        idx,
        "source"
    ] = "Generated Batch 06"

    batch_df.at[
        idx,
        "attempts"
    ] = 0

    batch_df.at[
        idx,
        "difficulty"
    ] = "Easy"

# Restore text dtype
for col in TEXT_COLUMNS:

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

print("✅ Ground truth filled for all 32.")
print("✅ Answers filled for all 32.")

# ============================================================
# 7. VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in TEXT_COLUMNS + ["attempts"]:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{'✅' if missing == 0 and empty == 0 else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert missing == 0
    assert empty == 0

print("✅ All required fields complete.")

# ============================================================
# 8. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 9. RELOAD
# ============================================================

check = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(check) == 32

assert (
    check["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    check["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("\n" + "=" * 100)
print("🏆 BATCH 06 REPAIR RESULT")
print("=" * 100)

print("""
🟢 BATCH 06 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ Existing 384 dataset NOT modified

🎉 READY FOR FINAL BATCH 06 VALIDATION
""")

print("📄 Batch:")
print(BATCH_FILE)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 GROUND TRUTH + ANSWER REPAIR
====================================================================================================
Existing dataset : 384
Batch 06         : 32

====================================================================================================
🧠 BUILDING KNOWLEDGE MAP
====================================================================================================
✅ INT001 Arabic
✅ INT001 English
✅ INT001 French
✅ INT001 Russian
✅ INT002 Arabic
✅ INT002 English
✅ INT002 French
✅ INT002 Russian
✅ INT003 Arabic
✅ INT003 English
✅ INT003 French
✅ INT003 Russian
✅ INT004 Arabic
✅ INT004 English
✅ INT004 French
✅ INT004 Russian
✅ INT005 Arabic
✅ INT005 English
✅ INT005 French
✅ INT005 Russian
✅ INT006 Arabic
✅ INT006 English
✅ INT006 French
✅ INT006 Russian
✅ INT007 Arabic
✅ INT007 English
✅ INT007 French
✅ INT007 Russian
✅ INT008 Arabic
✅ INT008 English
✅ INT008 French
✅ INT008 Russian
✅ Knowledge map created.

====================================================================================================
✍️ FILLING GROUND TRUTH + ANSWERS
====================================================================================================
✅ Ground truth filled for all 32.
✅ Answers filled for all 32.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
🏆 BATCH 06 REPAIR RESULT
====================================================================================================

🟢 BATCH 06 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ Existing 384 dataset NOT modified

🎉 READY FOR FINAL BATCH 06 VALIDATION

📄 Batch:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_06.csv
====================================================================================================

In [64]:
# ============================================================
# 🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT
# Existing dataset : 384
# Batch 06         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 06 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 384
assert len(batch_df) == 32

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 06         : {len(batch_df)} rows")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 5. BATCH ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(385, 417)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0385 → FAQ0416.")
print("✅ No duplicate IDs.")

# ============================================================
# 6. CHECK ID OVERLAP
# ============================================================

id_overlap = set(
    df["faq_id"]
).intersection(
    set(batch_df["faq_id"])
)

assert not id_overlap

print("✅ No ID overlap with existing 384.")

# ============================================================
# 7. REQUIRED FIELDS
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

required_ok = True

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        f"{'✅' if missing == 0 and empty == 0 else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if missing or empty:
        required_ok = False

assert required_ok

print("✅ All required fields complete.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK INSIDE BATCH 06")
print("=" * 100)

exact_dupes = batch_df[
    batch_df["question"].duplicated(keep=False)
]

batch_norm = batch_df["question"].map(normalize)

normalized_dupes = batch_df[
    batch_norm.duplicated(keep=False)
]

assert exact_dupes.empty
assert normalized_dupes.empty

print("✅ No exact duplicates.")
print("✅ No normalized duplicates.")

# ============================================================
# 9. OVERLAP WITH EXISTING 384
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP WITH EXISTING 384")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

existing_normalized = set(
    df["question"].map(normalize)
)

normalized_overlap = sorted(
    set(batch_norm).intersection(
        existing_normalized
    )
)

assert not exact_overlap
assert not normalized_overlap

print("✅ No exact overlap.")
print("✅ No normalized overlap.")

# ============================================================
# 10. INTENT VALIDATION
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

VALID_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

print("\n" + "=" * 100)
print("🎯 INTENT VALIDATION")
print("=" * 100)

intent_counts = batch_df["intent_id"].value_counts()

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

for _, row in batch_df.iterrows():

    assert row["intent_id"] in INTENTS

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print(intent_counts.to_string())
print("✅ 4 questions × 8 intents.")
print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 11. LANGUAGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE VALIDATION")
print("=" * 100)

language_counts = batch_df["language"].value_counts()

assert set(language_counts.index) == VALID_LANGUAGES

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print(language_counts.to_string())
print("✅ 8 questions × 4 languages.")

# ============================================================
# 12. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 QUESTION TYPE VALIDATION")
print("=" * 100)

assert set(
    batch_df["question_type"]
) <= VALID_TYPES

print(
    batch_df["question_type"]
    .value_counts()
    .to_string()
)

print("✅ All question types are valid.")

# ============================================================
# 13. STATUS / DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS / DIFFICULTY")
print("=" * 100)

assert set(batch_df["status"]) <= {
    "valid",
    "generated"
}

assert set(batch_df["difficulty"]) <= {
    "Easy"
}

print("Status:")
print(
    batch_df["status"]
    .value_counts()
    .to_string()
)

print("\nDifficulty:")
print(
    batch_df["difficulty"]
    .value_counts()
    .to_string()
)

print("✅ Status and difficulty values valid.")

# ============================================================
# 14. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

ground_truth_complete = (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_complete = (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print(
    "✅ Ground truth complete."
    if ground_truth_complete
    else "⚠️ Ground truth not filled yet."
)

print(
    "✅ Answers complete."
    if answers_complete
    else "⚠️ Answers not filled yet."
)

# ============================================================
# 15. QUESTION LENGTH
# ============================================================

print("\n" + "=" * 100)
print("📏 QUESTION LENGTH")
print("=" * 100)

lengths = (
    batch_df["question"]
    .astype(str)
    .str.len()
)

print(f"Shortest : {lengths.min()}")
print(f"Longest  : {lengths.max()}")
print(f"Average  : {lengths.mean():.2f}")

short_questions = batch_df[
    lengths < 10
]

assert short_questions.empty

print("✅ No suspiciously short questions.")

# ============================================================
# 16. FULL SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL SIMILARITY CHECK")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df.head(30)
        .to_string(index=False)
    )

# ============================================================
# 17. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    count = (
        0
        if similarity_df.empty
        else int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )
    )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 18. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

# ============================================================
# 19. HIGH SIMILARITY
# ============================================================

if similarity_df.empty:

    high_similarity = pd.DataFrame()

else:

    high_similarity = similarity_df[
        similarity_df["similarity"] >= 0.85
    ]

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(index=False)
    )

# ============================================================
# 20. FINAL DECISION
# ============================================================

batch_structure_ok = (
    len(batch_df) == 32
    and batch_df["faq_id"].is_unique
    and exact_dupes.empty
    and normalized_dupes.empty
    and not exact_overlap
    and not normalized_overlap
)

similarity_ok = (
    high_similarity.empty
    and cross_intent.empty
)

print("\n" + "=" * 100)
print("🏆 BATCH 06 COMPLETE AUDIT RESULT")
print("=" * 100)

if batch_structure_ok and similarity_ok:

    print("""
🟢 BATCH 06 PASSED STRUCTURAL + SIMILARITY CHECK

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 384
✅ Language balance correct
✅ Intent balance correct
✅ Intent names correct
✅ Question types valid
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
""")

else:

    print("""
🟡 BATCH 06 NEEDS REVIEW

⚠️ One or more checks require attention.
""")

# ============================================================
# 21. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_06.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 06 COMPLETE AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 06 COMPLETE AUDIT
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 384 rows
Batch 06         : 32 rows
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0385 → FAQ0416.
✅ No duplicate IDs.
✅ No ID overlap with existing 384.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
📝 DUPLICATE CHECK INSIDE BATCH 06
====================================================================================================
✅ No exact duplicates.
✅ No normalized duplicates.

====================================================================================================
🔎 OVERLAP WITH EXISTING 384
====================================================================================================
✅ No exact overlap.
✅ No normalized overlap.

====================================================================================================
🎯 INTENT VALIDATION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
🌍 LANGUAGE VALIDATION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
✅ 8 questions × 4 languages.

====================================================================================================
📝 QUESTION TYPE VALIDATION
====================================================================================================
question_type
Scenario       12
Paraphrased    12
Direct          8
✅ All question types are valid.

====================================================================================================
📌 STATUS / DIFFICULTY
====================================================================================================
Status:
status
generated    32

Difficulty:
difficulty
Easy    32
✅ Status and difficulty values valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
📏 QUESTION LENGTH
====================================================================================================
Shortest : 34
Longest  : 105
Average  : 65.94
✅ No suspiciously short questions.

====================================================================================================
🔍 FULL SIMILARITY CHECK
====================================================================================================
Pairs >= 0.80: 3
 similarity new_faq_id new_intent new_language                                                    new_question old_faq_id old_intent old_language                                                                    old_question
      0.836    FAQ0386     INT001      English      In which part of Cairo should I look for Nile Pearl Hotel?    FAQ0008     INT001      English For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?
      0.816    FAQ0388     INT001      Russian                        Где в Каире расположен Nile Pearl Hotel?    FAQ0027     INT001      Russian                                          Где расположен отель Nile Pearl Hotel?
      0.816    FAQ0416     INT008      Russian Какой вид удостоверения личности требуется гостю при заселении?    FAQ0252     INT008      Russian                Какое удостоверение личности принимается от гостя при заселении?

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 3 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 3

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
✅ No similarity >= 0.85.

====================================================================================================
🏆 BATCH 06 COMPLETE AUDIT RESULT
====================================================================================================

🟢 BATCH 06 PASSED STRUCTURAL + SIMILARITY CHECK

✅ 32 questions
✅ FAQ0385 → FAQ0416
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ No overlap with existing 384
✅ Language balance correct
✅ Intent balance correct
✅ Intent names correct
✅ Question types valid
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_06.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 06 COMPLETE AUDIT FINISHED
====================================================================================================

In [65]:
# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 06
# 384 + 32 = 416 QUESTIONS
# ============================================================

from pathlib import Path
from datetime import datetime
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 06")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_06.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

assert PROJECT_ROOT.exists()
assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

print(f"Current dataset : {len(df)}")
print(f"Batch 06        : {len(batch_df)}")

assert len(df) == 384
assert len(batch_df) == 32

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. BACKUP
# ============================================================

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_batch06_{timestamp}.csv"
)

df.to_csv(
    backup_path,
    index=False,
    encoding="utf-8-sig"
)

print()
print("💾 Backup created:")
print(backup_path)

# ============================================================
# 5. BATCH ID VALIDATION
# ============================================================

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(385, 417)
]

assert (
    batch_df["faq_id"].tolist()
    == expected_batch_ids
)

assert batch_df["faq_id"].is_unique

print("✅ Batch IDs: FAQ0385 → FAQ0416")
print("✅ No duplicate batch IDs.")

# ============================================================
# 6. ID OVERLAP
# ============================================================

existing_ids = set(
    df["faq_id"]
)

batch_ids = set(
    batch_df["faq_id"]
)

assert not existing_ids.intersection(
    batch_ids
)

print("✅ No FAQ ID overlap.")

# ============================================================
# 7. QUESTION OVERLAP
# ============================================================

def normalize_question(text):
    return (
        str(text)
        .casefold()
        .strip()
    )

existing_questions = set(
    df["question"].map(normalize_question)
)

batch_questions = set(
    batch_df["question"].map(normalize_question)
)

assert not existing_questions.intersection(
    batch_questions
)

assert not batch_df["question"].duplicated().any()

print("✅ No question overlap.")
print("✅ No duplicate questions inside Batch 06.")

# ============================================================
# 8. FIX DTYPES BEFORE MERGE
# ============================================================

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:

    df[col] = (
        df[col]
        .fillna("")
        .astype("string")
    )

    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

df["attempts"] = pd.to_numeric(
    df["attempts"],
    errors="raise"
)

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 9. MERGE
# ============================================================

merged_df = pd.concat(
    [df, batch_df],
    ignore_index=True
)

# ============================================================
# 10. FINAL ID CHECK
# ============================================================

expected_final_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 417)
]

assert (
    merged_df["faq_id"].tolist()
    == expected_final_ids
), "❌ Final FAQ IDs are incorrect."

assert merged_df["faq_id"].is_unique

# ============================================================
# 11. FINAL QUESTION CHECK
# ============================================================

assert not (
    merged_df["question"]
    .duplicated()
    .any()
)

merged_normalized = (
    merged_df["question"]
    .map(normalize_question)
)

assert not (
    merged_normalized.duplicated()
    .any()
)

# ============================================================
# 12. FINAL ROW COUNT
# ============================================================

assert len(merged_df) == 416

print()
print("=" * 100)
print("📊 MERGE VALIDATION")
print("=" * 100)

print("✅ Final row count: 416")
print("✅ IDs continuous: FAQ0001 → FAQ0416")
print("✅ No duplicate IDs")
print("✅ No duplicate questions")
print("✅ No normalized duplicates")

# ============================================================
# 13. SAVE
# ============================================================

merged_df.to_csv(
    FINAL_DATASET,
    index=False,
    encoding="utf-8-sig"
)

print()
print("=" * 100)
print("💾 FINAL DATASET UPDATED")
print("=" * 100)

print(FINAL_DATASET)

# ============================================================
# 14. RELOAD + VERIFY
# ============================================================

check_df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(check_df) == 416

assert (
    check_df["faq_id"].tolist()
    == expected_final_ids
)

assert check_df["faq_id"].is_unique

assert not (
    check_df["question"]
    .duplicated()
    .any()
)

check_normalized = (
    check_df["question"]
    .map(normalize_question)
)

assert not (
    check_normalized
    .duplicated()
    .any()
)

# ============================================================
# 15. FINAL RESULT
# ============================================================

print()
print("=" * 100)
print("🏆 MERGE RESULT")
print("=" * 100)

print("""
🟢 BATCH 06 MERGED SUCCESSFULLY

Previous dataset : 384
Added questions  : 32
Final dataset    : 416

IDs:
FAQ0001 → FAQ0416

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully
""")

print("🔒 Backup:")
print(backup_path)

print("=" * 100)
print("🎉 MERGE BATCH 06 COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 06
====================================================================================================
Current dataset : 384
Batch 06        : 32
✅ All 13 columns exist.
✅ Column order is correct.

💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch06_20260821_155217.csv
✅ Batch IDs: FAQ0385 → FAQ0416
✅ No duplicate batch IDs.
✅ No FAQ ID overlap.
✅ No question overlap.
✅ No duplicate questions inside Batch 06.

====================================================================================================
📊 MERGE VALIDATION
====================================================================================================
✅ Final row count: 416
✅ IDs continuous: FAQ0001 → FAQ0416
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates

====================================================================================================
💾 FINAL DATASET UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 MERGE RESULT
====================================================================================================

🟢 BATCH 06 MERGED SUCCESSFULLY

Previous dataset : 384
Added questions  : 32
Final dataset    : 416

IDs:
FAQ0001 → FAQ0416

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ Final dataset reloaded successfully

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch06_20260821_155217.csv
====================================================================================================
🎉 MERGE BATCH 06 COMPLETE
====================================================================================================

In [66]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE 416 DATASET AUDIT
# FULL QUALITY + DUPLICATE + SIMILARITY CHECK
# READ-ONLY
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata
import numpy as np

# ============================================================
# 1. CONFIG
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 416

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

SIMILARITY_THRESHOLD = 0.85

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE 416 DATASET AUDIT")
print("=" * 100)

# ============================================================
# 2. LOAD
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n📂 PROJECT")
print("=" * 100)
print(PROJECT_ROOT)

print("\n📄 DATASET")
print("=" * 100)
print(DATASET_PATH)

print("\n📊 DATASET INFORMATION")
print("=" * 100)
print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

# ============================================================
# 3. CHECK REGISTRY
# ============================================================

checks = {}

# ============================================================
# 4. COLUMN CHECK
# ============================================================

columns_ok = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

checks["13 columns"] = columns_ok

print("\n🧪 COLUMN VALIDATION")
print("=" * 100)

print(
    "✅ All 13 required columns exist."
    if columns_ok
    else "❌ Column validation failed."
)

if columns_ok:
    print("✅ Column order is correct.")

# ============================================================
# 5. ROW COUNT
# ============================================================

row_count_ok = (
    len(df) == EXPECTED_ROWS
)

checks["416 questions"] = row_count_ok

print("\n📦 ROW COUNT")
print("=" * 100)
print(f"Total questions: {len(df)}")

print(
    "✅ Exactly 416 questions."
    if row_count_ok
    else "❌ Expected 416 questions."
)

# ============================================================
# 6. REQUIRED FIELD VALIDATION
# ============================================================

required_fields_ok = True

print("\n🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in EXPECTED_COLUMNS:

    if col not in df.columns:
        required_fields_ok = False
        print(f"❌ Missing column: {col}")
        continue

    missing = int(
        df[col].isna().sum()
    )

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    ok = (
        missing == 0
        and empty == 0
    )

    print(
        f"{'✅' if ok else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if not ok:
        required_fields_ok = False

checks["Required fields"] = required_fields_ok

# ============================================================
# 7. FAQ ID CHECK
# ============================================================

print("\n🆔 FAQ ID VALIDATION")
print("=" * 100)

valid_id_format = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

duplicate_ids = df[
    df["faq_id"]
    .duplicated(keep=False)
]

numeric_ids = pd.to_numeric(
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0],
    errors="coerce"
)

expected_numeric_ids = np.arange(
    1,
    EXPECTED_ROWS + 1
)

continuous_ids = (
    numeric_ids.notna().all()
    and numeric_ids.astype(int).tolist()
    == expected_numeric_ids.tolist()
)

checks["Valid FAQ IDs"] = bool(valid_id_format)
checks["No duplicate IDs"] = duplicate_ids.empty
checks["Continuous IDs"] = bool(continuous_ids)

print(
    "✅ All FAQ IDs have valid format."
    if valid_id_format
    else "❌ Invalid FAQ IDs."
)

print(
    "✅ No duplicate FAQ IDs."
    if duplicate_ids.empty
    else f"❌ Duplicate IDs found: {len(duplicate_ids)}"
)

print(
    "✅ IDs continuous: FAQ0001 → FAQ0416"
    if continuous_ids
    else "❌ IDs are not continuous."
)

# ============================================================
# 8. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 9. EXACT DUPLICATES
# ============================================================

exact_duplicates = df[
    df["question"]
    .duplicated(keep=False)
]

checks["No exact duplicates"] = (
    exact_duplicates.empty
)

print("\n📝 EXACT DUPLICATE CHECK")
print("=" * 100)

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 10. NORMALIZED DUPLICATES
# ============================================================

normalized_duplicates = df[
    df["_normalized_question"]
    .duplicated(keep=False)
]

checks["No normalized duplicates"] = (
    normalized_duplicates.empty
)

print("\n🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 11. SAME-INTENT DUPLICATES
# ============================================================

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized_question"
        ],
        keep=False
    )
]

checks["No same-intent duplicates"] = (
    same_intent_duplicates.empty
)

print("\n🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

if same_intent_duplicates.empty:
    print("✅ No normalized duplicates inside the same intent.")
else:
    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question"
            ]
        ].to_string(index=False)
    )

# ============================================================
# 12. INTENT MAPPING
# ============================================================

intent_mapping_ok = True

print("\n🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    actual_names = set(
        subset["intent_name"]
        .astype(str)
    )

    ok = (
        len(subset) == 52
        and actual_names == {intent_name}
    )

    if not ok:
        intent_mapping_ok = False

    print(
        f"{'✅' if ok else '❌'} "
        f"{intent_id} → {intent_name} "
        f"| rows={len(subset)}"
    )

checks["Intent mappings"] = intent_mapping_ok

# ============================================================
# 13. LANGUAGE DISTRIBUTION
# ============================================================

language_counts = (
    df["language"]
    .value_counts()
)

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        language_counts.get(
            lang,
            0
        ) == 104
        for lang in EXPECTED_LANGUAGES
    )
)

checks["Language balance"] = language_balance_ok

print("\n🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)
print(language_counts.to_string())

print(
    "✅ 104 questions × 4 languages."
    if language_balance_ok
    else "❌ Language balance failed."
)

# ============================================================
# 14. INTENT DISTRIBUTION
# ============================================================

intent_counts = (
    df["intent_id"]
    .value_counts()
)

intent_balance_ok = all(
    int(
        intent_counts.get(
            intent_id,
            0
        )
    ) == 52
    for intent_id in EXPECTED_INTENTS
)

checks["Intent balance"] = intent_balance_ok

print("\n🎯 INTENT DISTRIBUTION")
print("=" * 100)

print(
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .rename("questions")
    .reset_index()
    .to_string(index=False)
)

print(
    "✅ 52 questions × 8 intents."
    if intent_balance_ok
    else "❌ Intent balance failed."
)

# ============================================================
# 15. LANGUAGE × INTENT
# ============================================================

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

language_intent_ok = True

for intent_id in EXPECTED_INTENTS:

    for language in EXPECTED_LANGUAGES:

        count = int(
            language_intent.loc[
                intent_id,
                language
            ]
        )

        if count != 13:
            language_intent_ok = False

checks["Language × Intent"] = language_intent_ok

print("\n📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)
print(language_intent.to_string())

print(
    "✅ Every intent has 13 questions per language."
    if language_intent_ok
    else "❌ Language × Intent balance failed."
)

# ============================================================
# 16. QUESTION TYPES
# ============================================================

question_type_counts = (
    df["question_type"]
    .value_counts()
)

unexpected_types = (
    set(df["question_type"])
    - VALID_TYPES
)

question_types_ok = (
    not unexpected_types
)

checks["Question types"] = question_types_ok

print("\n📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)
print(question_type_counts.to_string())

print(
    "✅ All question types are valid."
    if question_types_ok
    else f"❌ Invalid question types: {unexpected_types}"
)

# ============================================================
# 17. STATUS
# ============================================================

status_counts = (
    df["status"]
    .value_counts()
)

unexpected_status = (
    set(df["status"])
    - VALID_STATUS
)

status_ok = (
    not unexpected_status
)

checks["Status"] = status_ok

print("\n📌 STATUS DISTRIBUTION")
print("=" * 100)
print(status_counts.to_string())

print(
    "✅ Status values are valid."
    if status_ok
    else f"❌ Invalid statuses: {unexpected_status}"
)

# ============================================================
# 18. DIFFICULTY
# ============================================================

difficulty_counts = (
    df["difficulty"]
    .value_counts()
)

unexpected_difficulty = (
    set(df["difficulty"])
    - VALID_DIFFICULTY
)

difficulty_ok = (
    not unexpected_difficulty
)

checks["Difficulty"] = difficulty_ok

print("\n📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)
print(difficulty_counts.to_string())

print(
    "✅ Difficulty values are valid."
    if difficulty_ok
    else f"❌ Invalid difficulty: {unexpected_difficulty}"
)

# ============================================================
# 19. GROUND TRUTH / ANSWERS
# ============================================================

ground_truth_ok = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_ok = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

checks["Ground truth"] = bool(ground_truth_ok)
checks["Answers"] = bool(answers_ok)

print("\n🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

print(
    "✅ Ground truth complete."
    if ground_truth_ok
    else "❌ Ground truth incomplete."
)

print(
    "✅ Answers complete."
    if answers_ok
    else "❌ Answers incomplete."
)

# ============================================================
# 20. GROUND TRUTH / ANSWER WORDING
# ============================================================

gt_norm = (
    df["ground_truth"]
    .map(normalize_text)
)

answer_norm = (
    df["answer"]
    .map(normalize_text)
)

wording_difference = (
    gt_norm != answer_norm
)

print("\n🔗 GROUND TRUTH ↔ ANSWER")
print("=" * 100)

print(
    "Rows with different wording:",
    int(wording_difference.sum())
)

print(
    "ℹ️ Different wording is not treated as a failure."
)

# ============================================================
# 21. ATTEMPTS
# ============================================================

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

attempts_ok = (
    attempts_numeric.notna().all()
    and (attempts_numeric >= 0).all()
)

checks["Attempts"] = attempts_ok

print("\n🔢 ATTEMPTS VALIDATION")
print("=" * 100)

print(
    "✅ Attempts are numeric and non-negative."
    if attempts_ok
    else "❌ Invalid attempts values."
)

print(
    f"Min    : {attempts_numeric.min()}"
)
print(
    f"Max    : {attempts_numeric.max()}"
)
print(
    f"Average: {attempts_numeric.mean():.2f}"
)

# ============================================================
# 22. QUESTION LENGTH
# ============================================================

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

very_short = df[
    question_lengths < 10
]

question_length_ok = (
    very_short.empty
)

checks["Question length"] = question_length_ok

print("\n📏 QUESTION LENGTH")
print("=" * 100)

print(
    f"Shortest : {question_lengths.min()}"
)
print(
    f"Longest  : {question_lengths.max()}"
)
print(
    f"Average  : {question_lengths.mean():.2f}"
)

print(
    "✅ No suspiciously short questions."
    if question_length_ok
    else "⚠️ Suspiciously short questions found."
)

# ============================================================
# 23. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n🔍 FULL QUESTION SIMILARITY")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.80:

        similarity_pairs.append({
            "similarity": round(score, 3),
            "faq_id_1": df.iloc[i]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "language_1": df.iloc[i]["language"],
            "question_1": questions[i],
            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "language_2": df.iloc[j]["language"],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(
    similarity_pairs
)

# ============================================================
# 24. THRESHOLD SUMMARY
# ============================================================

print("\n📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:

        count = 0

    else:

        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 25. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

print("\n🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

print("\n⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

# ============================================================
# 26. TOP SIMILAR PAIRS
# ============================================================

print("\n📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:

    print("None.")

else:

    print(
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 27. HIGH SIMILARITY DECISION
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"]
        >= SIMILARITY_THRESHOLD
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

checks["Similarity < 0.85"] = (
    high_similarity.empty
)

print("\n🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        f"❌ {len(high_similarity)} pairs >= 0.85"
    )

    print(
        high_similarity
        .sort_values(
            "similarity",
            ascending=False
        )
        .to_string(index=False)
    )

# ============================================================
# 28. FINAL SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed = sum(checks.values())
total = len(checks)

score = (
    passed / total * 100
)

print("-" * 100)
print(
    f"Passed checks      : {passed}/{total}"
)

print(
    f"Validation Score   : {score:.1f}%"
)

if score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 29. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 FINAL SUMMARY")
print("=" * 100)

print(
    f"Questions : {len(df)}"
)

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    intent_counts.to_string()
)

print("\nLanguage × Intent:")
print(
    language_intent.to_string()
)

print("\nQuestion Types:")
print(
    question_type_counts.to_string()
)

print("\nStatus:")
print(
    status_counts.to_string()
)

print("\nDifficulty:")
print(
    difficulty_counts.to_string()
)

print(
    f"\nSimilarity >= 0.85: "
    f"{len(high_similarity)}"
)

# ============================================================
# 30. READ-ONLY CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 31. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=[
        "_normalized_question"
    ],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 COMPLETE 416-QUESTION AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE 416 DATASET AUDIT
====================================================================================================

📂 PROJECT
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 DATASET
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

📊 DATASET INFORMATION
====================================================================================================
Rows    : 416
Columns : 13

🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

📦 ROW COUNT
====================================================================================================
Total questions: 416
✅ Exactly 416 questions.

🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0

🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ IDs continuous: FAQ0001 → FAQ0416

📝 EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ INT001 → hotel_location | rows=52
✅ INT002 → hotel_category | rows=52
✅ INT003 → reception_availability | rows=52
✅ INT004 → check_in_time | rows=52
✅ INT005 → check_out_time | rows=52
✅ INT006 → early_check_in | rows=52
✅ INT007 → late_check_out | rows=52
✅ INT008 → identification_required | rows=52

🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    104
Arabic     104
French     104
Russian    104
✅ 104 questions × 4 languages.

🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         52
   INT002          hotel_category         52
   INT003  reception_availability         52
   INT004           check_in_time         52
   INT005          check_out_time         52
   INT006          early_check_in         52
   INT007          late_check_out         52
   INT008 identification_required         52
✅ 52 questions × 8 intents.

📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         13       13      13       13
INT002         13       13      13       13
INT003         13       13      13       13
INT004         13       13      13       13
INT005         13       13      13       13
INT006         13       13      13       13
INT007         13       13      13       13
INT008         13       13      13       13
✅ Every intent has 13 questions per language.

📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    164
Direct         140
Scenario       112
✅ All question types are valid.

📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated    192
✅ Status values are valid.

📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    416
✅ Difficulty values are valid.

🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

🔗 GROUND TRUTH ↔ ANSWER
====================================================================================================
Rows with different wording: 376
ℹ️ Different wording is not treated as a failure.

🔢 ATTEMPTS VALIDATION
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 6
Average: 0.32

📏 QUESTION LENGTH
====================================================================================================
Shortest : 31
Longest  : 186
Average  : 76.43
✅ No suspiciously short questions.

🔍 FULL QUESTION SIMILARITY
====================================================================================================
Comparing 86,320 question pairs...

📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 30 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 30

⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

📋 TOP 30 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1 language_1                                                                                                                              question_1 faq_id_2 intent_2 language_2                                                                                                                                                      question_2
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                                     What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                                     What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                                                هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                                              هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                                        В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                                               Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.836  FAQ0008   INT001    English                                                         For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?  FAQ0386   INT001    English                                                                                                      In which part of Cairo should I look for Nile Pearl Hotel?
      0.829  FAQ0004   INT001    English                                                                                          In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                                          Where can I find the Nile Pearl Hotel?
      0.828  FAQ0121   INT004    Russian                                                                                              Когда можно заселиться в Nile Pearl Hotel?  FAQ0125   INT004    Russian                                                                                                     Когда стандартно можно заселиться в отель Nile Pearl Hotel?
      0.827  FAQ0235   INT008     Arabic                                                                  هل يجب علي تقديم إثبات هوية ساري عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0237   INT008     Arabic                                                                              هل يحتاج الضيوف إلى تقديم وثائق إثبات الهوية عند تسجيل الوصول في Nile Pearl Hotel?
      0.824  FAQ0066   INT003    English                                                             What are the hours of operation for the reception desk at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                                     What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.821  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0100   INT004    English                                                                                                    What time is check-in usually available at Nile Pearl Hotel?
      0.818  FAQ0017   INT001     French                                                                                                  Où se trouve l'hôtel Nile Pearl Hotel?  FAQ0019   INT001     French                                                                                                           Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.818  FAQ0223   INT007    Russian                     Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?  FAQ0224   INT007    Russian                      Могу ли я получить поздний выезд из Nile Pearl Hotel, и если это возможно, под какие условия и будут ли какие-либо дополнительные расходы?
      0.816  FAQ0252   INT008    Russian                                                                        Какое удостоверение личности принимается от гостя при заселении?  FAQ0416   INT008    Russian                                                                                                 Какой вид удостоверения личности требуется гостю при заселении?
      0.816  FAQ0027   INT001    Russian                                                                                                  Где расположен отель Nile Pearl Hotel?  FAQ0388   INT001    Russian                                                                                                                        Где в Каире расположен Nile Pearl Hotel?
      0.816  FAQ0025   INT001    Russian                                                                                      По какому адресу находится отель Nile Pearl Hotel?  FAQ0260   INT001    Russian                                                                                                         В каком районе города находится отель Nile Pearl Hotel?
      0.814  FAQ0233   INT008     Arabic                                                            ما نوع مستند إثبات الهوية المقبول عند تسجيل الوصول في فندق Nile Pearl Hotel؟  FAQ0234   INT008     Arabic                                                                                         ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?
      0.814  FAQ0222   INT007    Russian                                          Могу ли я получить поздний выезд из Nile Pearl Hotel, и какие возможны дополнительные расходы?  FAQ0223   INT007    Russian                                             Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?
      0.812  FAQ0044   INT002     Arabic                                                                                   كم عدد النجوم التي يُصنَّف بها فندق Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.811  FAQ0001   INT001    English                                                                                                      Where is Nile Pearl Hotel located?  FAQ0003   INT001    English                                                                                                                      In which city is Nile Pearl Hotel located?
      0.810  FAQ0312   INT006    Russian                                                              Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?  FAQ0376   INT006    Russian                                                                             Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?
      0.809  FAQ0003   INT001    English                                                                                              In which city is Nile Pearl Hotel located?  FAQ0258   INT001    English                                                                                                          Which part of the city is Nile Pearl Hotel located in?
      0.807  FAQ0098   INT004    English                                                                             What time does check-in normally begin at Nile Pearl Hotel?  FAQ0102   INT004    English                                                                                                       At what time can I normally check in at Nile Pearl Hotel?
      0.805  FAQ0204   INT007     Arabic                                           هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وما العوامل التي تحدد إمكانية ذلك؟  FAQ0205   INT007     Arabic                                                                                هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وهل توجد رسوم إضافية؟
      0.804  FAQ0045   INT002     Arabic                                                                                        ما فئة النجوم التي ينتمي إليها Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                                                  كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.804  FAQ0251   INT008    Russian                              Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0253   INT008    Russian                                                   Требуется ли гостям предъявлять документ, удостоверяющий личность, при регистрации заезда в Nile Pearl Hotel?
      0.804  FAQ0036   INT002    English                                                                                    What is the star classification of Nile Pearl Hotel?  FAQ0038   INT002    English                                                                                                       What star classification is assigned to Nile Pearl Hotel?
      0.802  FAQ0217   INT007    Russian                                                   Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, что мне нужно знать?  FAQ0218   INT007    Russian                                                                         Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?
      0.800  FAQ0137   INT005     Arabic                                                                      متى يجب على النزيل إتمام إجراءات تسجيل الخروج من Nile Pearl Hotel؟  FAQ0139   INT005     Arabic                                                                                         متى يجب على الضيوف إتمام تسجيل الخروج المعتاد من فندق Nile Pearl Hotel؟
      0.800  FAQ0085   INT003     French Si vous avez besoin d'aide urgente à l'hôtel Nile Pearl Hotel en pleine nuit, quelles sont les heures d'ouverture du service d'accueil?  FAQ0086   INT003     French Si vous avez besoin d'assistance tout au long de la journée ou de la nuit à l'hôtel Nile Pearl Hotel, quelles sont les heures d'ouverture du service d'accueil?
      0.800  FAQ0234   INT008     Arabic                                                                 ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0285   INT008     Arabic                                                                                                             ما هي وثيقة إثبات الهوية المطلوبة عند تسجيل الوصول؟

🚨 HIGH-SIMILARITY REVIEW
====================================================================================================
✅ No similarity >= 0.85.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 13 columns
✅ 416 questions
✅ Required fields
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Attempts
✅ Question length
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks      : 21/21
Validation Score   : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 FINAL SUMMARY
====================================================================================================
Questions : 416

Languages:
language
English    104
Arabic     104
French     104
Russian    104

Intents:
intent_id
INT001    52
INT002    52
INT003    52
INT004    52
INT005    52
INT006    52
INT007    52
INT008    52

Language × Intent:
language   Arabic  English  French  Russian
intent_id
INT001         13       13      13       13
INT002         13       13      13       13
INT003         13       13      13       13
INT004         13       13      13       13
INT005         13       13      13       13
INT006         13       13      13       13
INT007         13       13      13       13
INT008         13       13      13       13

Question Types:
question_type
Paraphrased    164
Direct         140
Scenario       112

Status:
status
valid        224
generated    192

Difficulty:
difficulty
Easy    416

Similarity >= 0.85: 0

====================================================================================================
🔒 READ-ONLY CONFIRMATION

In [67]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 GENERATION
# 32 NEW QUESTIONS ONLY
# CONTINUE FROM FAQ0416
# ============================================================

from pathlib import Path
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 GENERATION")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
)

BATCH_FILE = (
    BATCH_DIR
    / "faq_batch_07.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."

BATCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"📂 Project root:\n{PROJECT_ROOT}")
print("✅ Project root found.")
print("✅ Final dataset found.")

# ============================================================
# 2. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📊 EXISTING DATASET")
print("=" * 100)

print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

assert len(df) == 416, (
    f"❌ Expected 416 existing questions, found {len(df)}"
)

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS

print("✅ Existing dataset contains exactly 416 questions.")
print("✅ All 13 required columns exist.")

# ============================================================
# 3. FAQ ID CONTINUATION
# ============================================================

numeric_ids = (
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0]
    .astype(int)
)

last_id = numeric_ids.max()

START_ID = last_id + 1
END_ID = START_ID + 32

assert START_ID == 417
assert END_ID == 449

print("\n" + "=" * 100)
print("🆔 FAQ ID CONTINUATION")
print("=" * 100)

print(f"Last existing : FAQ{last_id:04d}")
print(
    f"New batch     : FAQ{START_ID:04d} → "
    f"FAQ{END_ID - 1:04d}"
)

# ============================================================
# 4. INTENTS
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

# ============================================================
# 5. BATCH 07 QUESTIONS
# ============================================================

questions = [

    # ========================================================
    # INT001 - HOTEL LOCATION
    # ========================================================

    {
        "intent_id": "INT001",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "كيف يمكنني معرفة موقع Nile Pearl Hotel داخل القاهرة؟",
    },
    {
        "intent_id": "INT001",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "How can I identify the location of Nile Pearl Hotel within Cairo?",
    },
    {
        "intent_id": "INT001",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Comment puis-je situer le Nile Pearl Hotel dans la ville du Caire ?",
    },
    {
        "intent_id": "INT001",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Как определить местоположение Nile Pearl Hotel в Каире?",
    },

    # ========================================================
    # INT002 - HOTEL CATEGORY
    # ========================================================

    {
        "intent_id": "INT002",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما تصنيف Nile Pearl Hotel الفندقي؟",
    },
    {
        "intent_id": "INT002",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What is the hotel classification of Nile Pearl Hotel?",
    },
    {
        "intent_id": "INT002",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est la classification hôtelière du Nile Pearl Hotel ?",
    },
    {
        "intent_id": "INT002",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какова гостиничная классификация Nile Pearl Hotel?",
    },

    # ========================================================
    # INT003 - RECEPTION AVAILABILITY
    # ========================================================

    {
        "intent_id": "INT003",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "إذا وصلت متأخرًا جدًا إلى الفندق، هل سأتمكن من العثور على موظف استقبال؟",
    },
    {
        "intent_id": "INT003",
        "language": "English",
        "question_type": "Scenario",
        "question": "If I arrive at the hotel very late, will a reception employee still be available?",
    },
    {
        "intent_id": "INT003",
        "language": "French",
        "question_type": "Scenario",
        "question": "Si j'arrive très tard à l'hôtel, y aura-t-il encore un réceptionniste disponible ?",
    },
    {
        "intent_id": "INT003",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Если я приеду в отель очень поздно, будет ли сотрудник стойки регистрации на месте?",
    },

    # ========================================================
    # INT004 - CHECK IN TIME
    # ========================================================

    {
        "intent_id": "INT004",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "متى يبدأ تسجيل الوصول للضيوف في الفندق؟",
    },
    {
        "intent_id": "INT004",
        "language": "English",
        "question_type": "Direct",
        "question": "When does guest check-in begin at the hotel?",
    },
    {
        "intent_id": "INT004",
        "language": "French",
        "question_type": "Direct",
        "question": "Quand commence l'enregistrement des clients à l'hôtel ?",
    },
    {
        "intent_id": "INT004",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Когда начинается регистрация гостей в отеле?",
    },

    # ========================================================
    # INT005 - CHECK OUT TIME
    # ========================================================

    {
        "intent_id": "INT005",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "ما الموعد المعتاد الذي يجب فيه إنهاء المغادرة من الغرفة؟",
    },
    {
        "intent_id": "INT005",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "What is the usual deadline for leaving the room?",
    },
    {
        "intent_id": "INT005",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Quelle est l'heure habituelle limite pour quitter la chambre ?",
    },
    {
        "intent_id": "INT005",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Какое обычное время является крайним для освобождения номера?",
    },

    # ========================================================
    # INT006 - EARLY CHECK IN
    # ========================================================

    {
        "intent_id": "INT006",
        "language": "Arabic",
        "question_type": "Direct",
        "question": "هل أستطيع طلب تسجيل الوصول المبكر قبل الموعد الرسمي؟",
    },
    {
        "intent_id": "INT006",
        "language": "English",
        "question_type": "Direct",
        "question": "Can I request early check-in before the official time?",
    },
    {
        "intent_id": "INT006",
        "language": "French",
        "question_type": "Direct",
        "question": "Puis-je demander un enregistrement anticipé avant l'heure officielle ?",
    },
    {
        "intent_id": "INT006",
        "language": "Russian",
        "question_type": "Direct",
        "question": "Могу ли я запросить раннюю регистрацию до официального времени заезда?",
    },

    # ========================================================
    # INT007 - LATE CHECK OUT
    # ========================================================

    {
        "intent_id": "INT007",
        "language": "Arabic",
        "question_type": "Paraphrased",
        "question": "هل يمكنني تأخير وقت مغادرة الغرفة عن الموعد المعتاد؟",
    },
    {
        "intent_id": "INT007",
        "language": "English",
        "question_type": "Paraphrased",
        "question": "Can I move my room departure time later than usual?",
    },
    {
        "intent_id": "INT007",
        "language": "French",
        "question_type": "Paraphrased",
        "question": "Puis-je repousser l'heure de départ de ma chambre au-delà de l'horaire habituel ?",
    },
    {
        "intent_id": "INT007",
        "language": "Russian",
        "question_type": "Paraphrased",
        "question": "Можно ли перенести время выезда из номера на более поздний срок?",
    },

    # ========================================================
    # INT008 - IDENTIFICATION
    # ========================================================

    {
        "intent_id": "INT008",
        "language": "Arabic",
        "question_type": "Scenario",
        "question": "عند وصولي للفندق لإتمام الإقامة، ما إثبات الهوية الذي ينبغي أن يكون معي؟",
    },
    {
        "intent_id": "INT008",
        "language": "English",
        "question_type": "Scenario",
        "question": "When I arrive at the hotel to check in, what proof of identity should I have with me?",
    },
    {
        "intent_id": "INT008",
        "language": "French",
        "question_type": "Scenario",
        "question": "À mon arrivée à l'hôtel pour m'enregistrer, quelle pièce d'identité dois-je avoir avec moi ?",
    },
    {
        "intent_id": "INT008",
        "language": "Russian",
        "question_type": "Scenario",
        "question": "Когда я приеду в отель для заселения, какой документ, удостоверяющий личность, должен быть у меня с собой?",
    },
]

# ============================================================
# 6. STRUCTURE CHECK
# ============================================================

assert len(questions) == 32

required_question_fields = [
    "intent_id",
    "language",
    "question_type",
    "question",
]

for index, item in enumerate(
    questions,
    start=1
):

    for field in required_question_fields:

        assert field in item, (
            f"❌ Question #{index} missing {field}"
        )

        assert str(item[field]).strip(), (
            f"❌ Question #{index} empty {field}"
        )

print("\n" + "=" * 100)
print("🧪 QUESTION STRUCTURE CHECK")
print("=" * 100)

print("✅ All 32 questions contain required fields.")

# ============================================================
# 7. BUILD BATCH DATAFRAME
# ============================================================

batch = []

for i, item in enumerate(
    questions,
    start=START_ID
):

    intent_id = item["intent_id"]

    batch.append({
        "faq_id": f"FAQ{i:04d}",
        "intent_id": intent_id,
        "language": item["language"],
        "question_type": item["question_type"],
        "question": item["question"],
        "status": "generated",
        "intent_name": INTENTS[intent_id],
        "ground_truth": "",
        "category": "Hotel FAQ",
        "source": "Generated Batch 07",
        "attempts": 0,
        "difficulty": "Easy",
        "answer": "",
    })

batch_df = pd.DataFrame(
    batch,
    columns=REQUIRED_COLUMNS
)

# ============================================================
# 8. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 ID VALIDATION")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(START_ID, END_ID)
]

assert batch_df["faq_id"].tolist() == expected_batch_ids
assert batch_df["faq_id"].is_unique

print(
    f"✅ IDs are exactly FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}"
)
print("✅ No duplicate IDs.")

# ============================================================
# 9. NORMALIZATION
# ============================================================

def normalize_question(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 10. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK")
print("=" * 100)

batch_normalized = batch_df["question"].map(
    normalize_question
)

assert not batch_df["question"].duplicated().any()
assert not batch_normalized.duplicated().any()

print("✅ No duplicate questions inside Batch 07.")
print("✅ No normalized duplicates inside Batch 07.")

# ============================================================
# 11. OVERLAP WITH EXISTING 416
# ============================================================

existing_normalized = set(
    df["question"].map(normalize_question)
)

overlap_mask = batch_normalized.isin(
    existing_normalized
)

assert not overlap_mask.any(), (
    "❌ Batch 07 contains an existing question."
)

print("✅ No exact/normalized overlap with existing 416.")

# ============================================================
# 12. LANGUAGE BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts)

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 questions × 4 languages.")

# ============================================================
# 13. INTENT BALANCE
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts)

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 questions × 8 intents.")

# ============================================================
# 14. INTENT NAME CHECK
# ============================================================

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 15. QUESTION TYPE CHECK
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert (
    set(batch_df["question_type"])
    <= VALID_TYPES
)

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
)

print("✅ All question types are valid.")

# ============================================================
# 16. PREVIEW
# ============================================================

print("\n" + "=" * 100)
print("📝 BATCH 07 QUESTIONS")
print("=" * 100)

print(
    batch_df[
        [
            "faq_id",
            "intent_id",
            "language",
            "question_type",
            "question",
        ]
    ].to_string(index=False)
)

# ============================================================
# 17. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🎉 BATCH 07 READY")
print("=" * 100)

print(
    f"""
Existing dataset : {len(df)} questions
New batch        : {len(batch_df)} questions

FAQ IDs:
FAQ{START_ID:04d} → FAQ{END_ID - 1:04d}

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 416
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
{BATCH_FILE}
"""
)

print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 GENERATION
====================================================================================================
📂 Project root:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
✅ Project root found.
✅ Final dataset found.

====================================================================================================
📊 EXISTING DATASET
====================================================================================================
Rows    : 416
Columns : 13
✅ Existing dataset contains exactly 416 questions.
✅ All 13 required columns exist.

====================================================================================================
🆔 FAQ ID CONTINUATION
====================================================================================================
Last existing : FAQ0416
New batch     : FAQ0417 → FAQ0448

====================================================================================================
🧪 QUESTION STRUCTURE CHECK
====================================================================================================
✅ All 32 questions contain required fields.

====================================================================================================
🆔 ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448
✅ No duplicate IDs.

====================================================================================================
📝 DUPLICATE CHECK
====================================================================================================
✅ No duplicate questions inside Batch 07.
✅ No normalized duplicates inside Batch 07.
✅ No exact/normalized overlap with existing 416.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
Name: count, dtype: int64
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
Name: count, dtype: int64
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    16
Scenario        8
Direct          8
Name: count, dtype: int64
✅ All question types are valid.

====================================================================================================
📝 BATCH 07 QUESTIONS
====================================================================================================
 faq_id intent_id language question_type                                                                                                   question
FAQ0417    INT001   Arabic   Paraphrased                                                       كيف يمكنني معرفة موقع Nile Pearl Hotel داخل القاهرة؟
FAQ0418    INT001  English   Paraphrased                                          How can I identify the location of Nile Pearl Hotel within Cairo?
FAQ0419    INT001   French   Paraphrased                                        Comment puis-je situer le Nile Pearl Hotel dans la ville du Caire ?
FAQ0420    INT001  Russian   Paraphrased                                                    Как определить местоположение Nile Pearl Hotel в Каире?
FAQ0421    INT002   Arabic   Paraphrased                                                                         ما تصنيف Nile Pearl Hotel الفندقي؟
FAQ0422    INT002  English   Paraphrased                                                      What is the hotel classification of Nile Pearl Hotel?
FAQ0423    INT002   French   Paraphrased                                               Quelle est la classification hôtelière du Nile Pearl Hotel ?
FAQ0424    INT002  Russian   Paraphrased                                                         Какова гостиничная классификация Nile Pearl Hotel?
FAQ0425    INT003   Arabic      Scenario                                    إذا وصلت متأخرًا جدًا إلى الفندق، هل سأتمكن من العثور على موظف استقبال؟
FAQ0426    INT003  English      Scenario                          If I arrive at the hotel very late, will a reception employee still be available?
FAQ0427    INT003   French      Scenario                         Si j'arrive très tard à l'hôtel, y aura-t-il encore un réceptionniste disponible ?
FAQ0428    INT003  Russian      Scenario                        Если я приеду в отель очень поздно, будет ли сотрудник стойки регистрации на месте?
FAQ0429    INT004   Arabic        Direct                                                                    متى يبدأ تسجيل الوصول للضيوف في الفندق؟
FAQ0430    INT004  English        Direct                                                               When does guest check-in begin at the hotel?
FAQ0431    INT004   French        Direct                                                    Quand commence l'enregistrement des clients à l'hôtel ?
FAQ0432    INT004  Russian        Direct                                                               Когда начинается регистрация гостей в отеле?
FAQ0433    INT005   Arabic   Paraphrased                                                   ما الموعد المعتاد الذي يجب فيه إنهاء المغادرة من الغرفة؟
FAQ0434    INT005  English   Paraphrased                                                           What is the usual deadline for leaving the room?
FAQ0435    INT005   French   Paraphrased                                             Quelle est l'heure habituelle limite pour quitter la chambre ?
FAQ0436    INT005  Russian   Paraphrased                                              Какое обычное время является крайним для освобождения номера?
FAQ0437    INT006   Arabic        Direct                                                       هل أستطيع طلب تسجيل الوصول المبكر قبل الموعد الرسمي؟
FAQ0438    INT006  English        Direct                                                     Can I request early check-in before the official time?
FAQ0439    INT006   French        Direct                                     Puis-je demander un enregistrement anticipé avant l'heure officielle ?
FAQ0440    INT006  Russian        Direct                                     Могу ли я запросить раннюю регистрацию до официального времени заезда?
FAQ0441    INT007   Arabic   Paraphrased                                                       هل يمكنني تأخير وقت مغادرة الغرفة عن الموعد المعتاد؟
FAQ0442    INT007  English   Paraphrased                                                        Can I move my room departure time later than usual?
FAQ0443    INT007   French   Paraphrased                          Puis-je repousser l'heure de départ de ma chambre au-delà de l'horaire habituel ?
FAQ0444    INT007  Russian   Paraphrased                                           Можно ли перенести время выезда из номера на более поздний срок?
FAQ0445    INT008   Arabic      Scenario                                   عند وصولي للفندق لإتمام الإقامة، ما إثبات الهوية الذي ينبغي أن يكون معي؟
FAQ0446    INT008  English      Scenario                      When I arrive at the hotel to check in, what proof of identity should I have with me?
FAQ0447    INT008   French      Scenario               À mon arrivée à l'hôtel pour m'enregistrer, quelle pièce d'identité dois-je avoir avec moi ?
FAQ0448    INT008  Russian      Scenario Когда я приеду в отель для заселения, какой документ, удостоверяющий личность, должен быть у меня с собой?

====================================================================================================
🎉 BATCH 07 READY
====================================================================================================

Existing dataset : 416 questions
New batch        : 32 questions

FAQ IDs:
FAQ0417 → FAQ0448

Languages:
Arabic   : 8
English  : 8
French   : 8
Russian  : 8

Intents:
INT001 : 4
INT002 : 4
INT003 : 4
INT004 : 4
INT005 : 4
INT006 : 4
INT007 : 4
INT008 : 4

Validation:
✅ Exactly 32 questions
✅ IDs correct
✅ No duplicate IDs
✅ No empty questions
✅ No duplicate questions
✅ No overlap with existing 416
✅ Language balance correct
✅ Intent balance correct
✅ Intent names consistent
✅ Question types valid

⚠️ hotel_faq_final.csv was NOT modified.

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv

====================================================================================================

In [68]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 vs EXISTING 416
# DUPLICATE + SIMILARITY CHECK
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 vs EXISTING 416")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416
assert len(batch_df) == 32

print(f"Existing questions : {len(df)}")
print(f"Batch 07 questions : {len(batch_df)}")

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 07 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

print("✅ IDs are exactly FAQ0417 → FAQ0448.")
print("✅ No duplicate IDs.")

id_overlap = set(
    df["faq_id"]
).intersection(
    set(batch_df["faq_id"])
)

assert not id_overlap

print("✅ No ID overlap with existing 416.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:

    print("❌ Exact overlaps found:")

    for q in exact_overlap:
        print("-", q)

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize)
)

batch_normalized = set(
    batch_df["question"].map(normalize)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for q in normalized_overlap:
        print("-", q)

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 07")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

normalized_series = batch_df[
    "question"
].map(normalize)

normalized_duplicates = batch_df[
    normalized_series.duplicated(
        keep=False
    )
]

assert exact_duplicates.empty
assert normalized_duplicates.empty

print("✅ No exact duplicates inside Batch 07.")
print("✅ No normalized duplicates inside Batch 07.")

# ============================================================
# 9. SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print("🎉 No pairs >= 0.80.")

else:

    similarity_df = similarity_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df.head(30)
        .to_string(index=False)
    )

# ============================================================
# 10. THRESHOLD SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 12. CROSS INTENT
# ============================================================

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent.head(30)
        .to_string(index=False)
    )

# ============================================================
# 13. HIGH SIMILARITY
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity.to_string(index=False)
    )

# ============================================================
# 14. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 07 DECISION")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and high_similarity.empty
    and cross_intent.empty
):

    print("""
🟢 BATCH 07 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 07
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS
""")

else:

    print("""
🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.
""")

# ============================================================
# 15. READ ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_07.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 SIMILARITY CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 vs EXISTING 416
====================================================================================================
Existing questions : 416
Batch 07 questions : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 07 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448.
✅ No duplicate IDs.
✅ No ID overlap with existing 416.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 07
====================================================================================================
✅ No exact duplicates inside Batch 07.
✅ No normalized duplicates inside Batch 07.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs >= 0.80: 8
 similarity new_faq_id new_intent new_language                                                                                 new_question old_faq_id old_intent old_language                                                                               old_question
      0.932    FAQ0422     INT002      English                                        What is the hotel classification of Nile Pearl Hotel?    FAQ0036     INT002      English                                       What is the star classification of Nile Pearl Hotel?
      0.850    FAQ0439     INT006       French                       Puis-je demander un enregistrement anticipé avant l'heure officielle ?    FAQ0343     INT006       French                              Puis-je demander un enregistrement avant l'heure habituelle ?
      0.846    FAQ0422     INT002      English                                        What is the hotel classification of Nile Pearl Hotel?    FAQ0326     INT002      English                                      What hotel classification does Nile Pearl Hotel have?
      0.842    FAQ0421     INT002       Arabic                                                           ما تصنيف Nile Pearl Hotel الفندقي؟    FAQ0357     INT002       Arabic                                               ما مستوى تصنيف Nile Pearl Hotel بين الفنادق؟
      0.838    FAQ0434     INT005      English                                             What is the usual deadline for leaving the room?    FAQ0135     INT005      English                                What is the usual deadline for guests to leave their rooms?
      0.830    FAQ0447     INT008       French À mon arrivée à l'hôtel pour m'enregistrer, quelle pièce d'identité dois-je avoir avec moi ?    FAQ0319     INT008       French À mon arrivée à l'hôtel pour m'enregistrer, quel justificatif d'identité dois-je fournir ?
      0.814    FAQ0423     INT002       French                                 Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                                   Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.800    FAQ0435     INT005       French                               Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French         Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 8 pairs
0.85+ : 2 pairs
0.90+ : 1 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 8
 similarity new_faq_id new_intent new_language                                                                                 new_question old_faq_id old_intent old_language                                                                               old_question
      0.932    FAQ0422     INT002      English                                        What is the hotel classification of Nile Pearl Hotel?    FAQ0036     INT002      English                                       What is the star classification of Nile Pearl Hotel?
      0.850    FAQ0439     INT006       French                       Puis-je demander un enregistrement anticipé avant l'heure officielle ?    FAQ0343     INT006       French                              Puis-je demander un enregistrement avant l'heure habituelle ?
      0.846    FAQ0422     INT002      English                                        What is the hotel classification of Nile Pearl Hotel?    FAQ0326     INT002      English                                      What hotel classification does Nile Pearl Hotel have?
      0.842    FAQ0421     INT002       Arabic                                                           ما تصنيف Nile Pearl Hotel الفندقي؟    FAQ0357     INT002       Arabic                                               ما مستوى تصنيف Nile Pearl Hotel بين الفنادق؟
      0.838    FAQ0434     INT005      English                                             What is the usual deadline for leaving the room?    FAQ0135     INT005      English                                What is the usual deadline for guests to leave their rooms?
      0.830    FAQ0447     INT008       French À mon arrivée à l'hôtel pour m'enregistrer, quelle pièce d'identité dois-je avoir avec moi ?    FAQ0319     INT008       French À mon arrivée à l'hôtel pour m'enregistrer, quel justificatif d'identité dois-je fournir ?
      0.814    FAQ0423     INT002       French                                 Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                                   Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.800    FAQ0435     INT005       French                               Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French         Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 2
 similarity new_faq_id new_intent new_language                                                           new_question old_faq_id old_intent old_language                                                  old_question
      0.932    FAQ0422     INT002      English                  What is the hotel classification of Nile Pearl Hotel?    FAQ0036     INT002      English          What is the star classification of Nile Pearl Hotel?
      0.850    FAQ0439     INT006       French Puis-je demander un enregistrement anticipé avant l'heure officielle ?    FAQ0343     INT006       French Puis-je demander un enregistrement avant l'heure habituelle ?

====================================================================================================
🏆 BATCH 07 DECISION
====================================================================================================

🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_07.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 07 SIMILARITY CHECK COMPLETE
====================================================================================================

In [69]:
from pathlib import Path
import pandas as pd
import unicodedata
import re

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

rewrites = {

    # INT002 - English
    "FAQ0422":
        "How many stars is Nile Pearl Hotel rated?",

    # INT006 - French
    "FAQ0439":
        "L'arrivée anticipée est-elle disponible sur demande au Nile Pearl Hotel ?",

    # INT002 - Arabic
    "FAQ0421":
        "إلى أي فئة من فئات الفنادق يُنسب Nile Pearl Hotel؟",

    # INT005 - English
    "FAQ0434":
        "By what time are guests expected to vacate their room?",

    # INT008 - French
    "FAQ0447":
        "Quel document d'identité faut-il avoir avec soi lors de l'arrivée à l'hôtel ?",
}

for faq_id, new_question in rewrites.items():

    matches = batch_df.index[
        batch_df["faq_id"] == faq_id
    ].tolist()

    assert len(matches) == 1, (
        f"❌ {faq_id} not found exactly once."
    )

    idx = matches[0]

    old_question = batch_df.at[
        idx,
        "question"
    ]

    batch_df.at[
        idx,
        "question"
    ] = new_question

    print(f"\n🔄 {faq_id}")
    print(f"OLD: {old_question}")
    print(f"NEW: {new_question}")


def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    return re.sub(
        r"\s+",
        " ",
        text
    ).strip()


batch_normalized = batch_df["question"].map(normalize)

assert not batch_df["question"].duplicated().any()
assert not batch_normalized.duplicated().any()

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 07 UPDATED")
print("=" * 100)
print(BATCH_FILE)
print("✅ 32 rows preserved.")
print("✅ hotel_faq_final.csv was NOT modified.")

🔄 FAQ0422
OLD: What is the hotel classification of Nile Pearl Hotel?
NEW: How many stars is Nile Pearl Hotel rated?

🔄 FAQ0439
OLD: Puis-je demander un enregistrement anticipé avant l'heure officielle ?
NEW: L'arrivée anticipée est-elle disponible sur demande au Nile Pearl Hotel ?

🔄 FAQ0421
OLD: ما تصنيف Nile Pearl Hotel الفندقي؟
NEW: إلى أي فئة من فئات الفنادق يُنسب Nile Pearl Hotel؟

🔄 FAQ0434
OLD: What is the usual deadline for leaving the room?
NEW: By what time are guests expected to vacate their room?

🔄 FAQ0447
OLD: À mon arrivée à l'hôtel pour m'enregistrer, quelle pièce d'identité dois-je avoir avec moi ?
NEW: Quel document d'identité faut-il avoir avec soi lors de l'arrivée à l'hôtel ?

====================================================================================================
💾 BATCH 07 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv
✅ 32 rows preserved.
✅ hotel_faq_final.csv was NOT modified.

In [70]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 FINAL COMPLETE SIMILARITY CHECK
# Existing dataset : 416
# Batch 07         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 FINAL COMPLETE SIMILARITY CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 07 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416, (
    f"❌ Existing dataset must contain 416 rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 07 must contain 32 rows, found {len(batch_df)}"
)

print(f"📄 Existing dataset : {FINAL_DATASET}")
print(f"📄 Batch 07         : {BATCH_FILE}")

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing questions : {len(df)}")
print(f"Batch 07 questions : {len(batch_df)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH 07 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

existing_ids = set(df["faq_id"])
batch_ids = set(batch_df["faq_id"])

id_overlap = existing_ids.intersection(batch_ids)

assert not id_overlap, (
    f"❌ ID overlap found: {id_overlap}"
)

print("✅ IDs are exactly FAQ0417 → FAQ0448.")
print("✅ No duplicate IDs.")
print("✅ No ID overlap with existing 416.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(batch_exact)
)

if exact_overlap:

    print("❌ Exact overlaps found:")

    for q in exact_overlap:
        print(f"- {q}")

else:

    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize)
)

batch_normalized = set(
    batch_df["question"].map(normalize)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:

    print("❌ Normalized overlaps found:")

    for q in normalized_overlap:
        print(f"- {q}")

else:

    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 07")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

normalized_series = (
    batch_df["question"]
    .map(normalize)
)

normalized_duplicates = batch_df[
    normalized_series.duplicated(
        keep=False
    )
]

if exact_duplicates.empty:
    print("✅ No exact duplicates inside Batch 07.")
else:
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

if normalized_duplicates.empty:
    print("✅ No normalized duplicates inside Batch 07.")
else:
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. SEMANTIC / TEXT SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = (
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print("\nTOP SIMILAR PAIRS:")

    print(
        similarity_df
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 10. THRESHOLD SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

threshold_counts = {}

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:

        count = 0

    else:

        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    threshold_counts[threshold] = count

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME-INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 12. CROSS-INTENT
# ============================================================

if similarity_df.empty:

    cross_intent = pd.DataFrame()

else:

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 13. HIGH SIMILARITY
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

print(
    f"Similarity >= 0.85: "
    f"{len(high_similarity)}"
)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        high_similarity
        .to_string(index=False)
    )

# ============================================================
# 14. VERY HIGH
# ============================================================

very_high = (
    similarity_df[
        similarity_df["similarity"] >= 0.90
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.90: "
    f"{len(very_high)}"
)

if not very_high.empty:

    print(
        very_high
        .to_string(index=False)
    )

# ============================================================
# 15. EXTREME
# ============================================================

extreme = (
    similarity_df[
        similarity_df["similarity"] >= 0.95
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.95: "
    f"{len(extreme)}"
)

if not extreme.empty:

    print(
        extreme
        .to_string(index=False)
    )

# ============================================================
# 16. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 07 FINAL DECISION")
print("=" * 100)

if (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and high_similarity.empty
    and cross_intent.empty
):

    print("""
🟢 BATCH 07 IS READY FOR THE NEXT STEP

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 07
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS
""")

else:

    print("""
🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks
require attention.
""")

# ============================================================
# 17. SUMMARY
# ============================================================

print("=" * 100)
print("🏆 BATCH 07 SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 416
Batch 07 questions           : 32

Exact overlaps               : {len(exact_overlap)}
Normalized overlaps          : {len(normalized_overlap)}

Pairs >= 0.80                : {len(similarity_df)}
Same-intent >= 0.80          : {len(same_intent)}
Cross-intent >= 0.80         : {len(cross_intent)}

Pairs >= 0.85                : {len(high_similarity)}
Pairs >= 0.90                : {len(very_high)}
Pairs >= 0.95                : {len(extreme)}
"""
)

# ============================================================
# 18. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_07.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 FINAL CHECK COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 FINAL COMPLETE SIMILARITY CHECK
====================================================================================================
📄 Existing dataset : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
📄 Batch 07         : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing questions : 416
Batch 07 questions : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 BATCH 07 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448.
✅ No duplicate IDs.
✅ No ID overlap with existing 416.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
❌ Exact overlaps found:
- How many stars is Nile Pearl Hotel rated?

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
❌ Normalized overlaps found:
- how many stars is nile pearl hotel rated

====================================================================================================
📝 DUPLICATES INSIDE BATCH 07
====================================================================================================
✅ No exact duplicates inside Batch 07.
✅ No normalized duplicates inside Batch 07.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs >= 0.80: 4

TOP SIMILAR PAIRS:
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      1.000    FAQ0422     INT002      English                      How many stars is Nile Pearl Hotel rated?    FAQ0033     INT002      English                                          How many stars is Nile Pearl Hotel rated?
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 4 pairs
0.85+ : 1 pairs
0.90+ : 1 pairs
0.95+ : 1 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 4
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      1.000    FAQ0422     INT002      English                      How many stars is Nile Pearl Hotel rated?    FAQ0033     INT002      English                                          How many stars is Nile Pearl Hotel rated?
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 1
 similarity new_faq_id new_intent new_language                              new_question old_faq_id old_intent old_language                              old_question
        1.0    FAQ0422     INT002      English How many stars is Nile Pearl Hotel rated?    FAQ0033     INT002      English How many stars is Nile Pearl Hotel rated?

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 1
 similarity new_faq_id new_intent new_language                              new_question old_faq_id old_intent old_language                              old_question
        1.0    FAQ0422     INT002      English How many stars is Nile Pearl Hotel rated?    FAQ0033     INT002      English How many stars is Nile Pearl Hotel rated?

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 1
 similarity new_faq_id new_intent new_language                              new_question old_faq_id old_intent old_language                              old_question
        1.0    FAQ0422     INT002      English How many stars is Nile Pearl Hotel rated?    FAQ0033     INT002      English How many stars is Nile Pearl Hotel rated?

====================================================================================================
🏆 BATCH 07 FINAL DECISION
====================================================================================================

🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks
require attention.

====================================================================================================
🏆 BATCH 07 SUMMARY
====================================================================================================

Existing questions          : 416
Batch 07 questions           : 32

Exact overlaps               : 1
Normalized overlaps          : 1

Pairs >= 0.80                : 4
Same-intent >= 0.80          : 4
Cross-intent >= 0.80         : 0

Pairs >= 0.85                : 1
Pairs >= 0.90                : 1
Pairs >= 0.95                : 1

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_07.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 07 FINAL CHECK COMPLETE
====================================================================================================

In [71]:
from pathlib import Path
import pandas as pd
import unicodedata
import re

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

print("=" * 100)
print("🏨 HOTEL AI - FIX BATCH 07 FAQ0422")
print("=" * 100)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(batch_df) == 32
assert len(df) == 416

# ============================================================
# OLD / NEW
# ============================================================

faq_id = "FAQ0422"

new_question = (
    "What star rating does Nile Pearl Hotel receive?"
)

idx_list = batch_df.index[
    batch_df["faq_id"] == faq_id
].tolist()

assert len(idx_list) == 1

idx = idx_list[0]

old_question = batch_df.at[
    idx,
    "question"
]

batch_df.at[
    idx,
    "question"
] = new_question

print(f"\n🔄 {faq_id}")
print(f"OLD: {old_question}")
print(f"NEW: {new_question}")

# ============================================================
# NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    return re.sub(
        r"\s+",
        " ",
        text
    ).strip()

# ============================================================
# BATCH DUPLICATE CHECK
# ============================================================

batch_normalized = (
    batch_df["question"]
    .map(normalize)
)

assert not batch_df["question"].duplicated().any()
assert not batch_normalized.duplicated().any()

# ============================================================
# EXISTING DATASET OVERLAP
# ============================================================

existing_normalized = set(
    df["question"].map(normalize)
)

normalized_overlap = (
    set(batch_normalized)
    .intersection(existing_normalized)
)

# The new FAQ0422 must no longer overlap.
assert normalize(new_question) not in existing_normalized

print("\n✅ FAQ0422 no longer overlaps with existing dataset.")
print("✅ No duplicates inside Batch 07.")
print("✅ No normalized duplicates inside Batch 07.")

# ============================================================
# SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 07 UPDATED")
print("=" * 100)

print(BATCH_FILE)
print("✅ 32 rows preserved.")
print("✅ hotel_faq_final.csv was NOT modified.")

print("\n" + "=" * 100)
print("🎉 FAQ0422 DUPLICATE FIX COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FIX BATCH 07 FAQ0422
====================================================================================================

🔄 FAQ0422
OLD: How many stars is Nile Pearl Hotel rated?
NEW: What star rating does Nile Pearl Hotel receive?

✅ FAQ0422 no longer overlaps with existing dataset.
✅ No duplicates inside Batch 07.
✅ No normalized duplicates inside Batch 07.

====================================================================================================
💾 BATCH 07 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv
✅ 32 rows preserved.
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🎉 FAQ0422 DUPLICATE FIX COMPLETE
====================================================================================================

In [72]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK
# Existing dataset : 416
# Batch 07         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 07 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416, (
    f"❌ Existing dataset must contain 416 rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 07 must contain 32 rows, found {len(batch_df)}"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing questions : {len(df)}")
print(f"Batch 07 questions : {len(batch_df)}")

# ============================================================
# 3. COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

id_overlap = (
    set(df["faq_id"])
    .intersection(set(batch_df["faq_id"]))
)

assert not id_overlap

print("✅ IDs are exactly FAQ0417 → FAQ0448.")
print("✅ No duplicate IDs.")
print("✅ No ID overlap with existing 416.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:
    print("❌ Exact overlaps found:")
    for q in exact_overlap:
        print("-", q)
else:
    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize)
)

batch_normalized = set(
    batch_df["question"].map(normalize)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:
    print("❌ Normalized overlaps found:")
    for q in normalized_overlap:
        print("-", q)
else:
    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 07")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

normalized_series = batch_df[
    "question"
].map(normalize)

normalized_duplicates = batch_df[
    normalized_series.duplicated(
        keep=False
    )
]

print(
    "✅ No exact duplicates inside Batch 07."
    if exact_duplicates.empty
    else "❌ Exact duplicates found."
)

print(
    "✅ No normalized duplicates inside Batch 07."
    if normalized_duplicates.empty
    else "❌ Normalized duplicates found."
)

# ============================================================
# 9. SIMILARITY CHECK
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(
    similar_pairs
)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = (
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print("\nTOP SIMILAR PAIRS:")
    print(
        similarity_df
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 10. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

threshold_counts = {}

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    threshold_counts[threshold] = count

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME INTENT
# ============================================================

if similarity_df.empty:
    same_intent = pd.DataFrame()
else:
    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 12. CROSS INTENT
# ============================================================

if similarity_df.empty:
    cross_intent = pd.DataFrame()
else:
    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 13. HIGH / VERY HIGH / EXTREME
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

very_high = (
    similarity_df[
        similarity_df["similarity"] >= 0.90
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

extreme = (
    similarity_df[
        similarity_df["similarity"] >= 0.95
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

print(
    f"Similarity >= 0.85: {len(high_similarity)}"
)

if not high_similarity.empty:
    print(
        high_similarity
        .to_string(index=False)
    )
else:
    print("✅ No similarity >= 0.85.")

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.90: {len(very_high)}"
)

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.95: {len(extreme)}"
)

# ============================================================
# 14. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 07 FINAL DECISION")
print("=" * 100)

passed = (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and len(high_similarity) == 0
    and len(cross_intent) == 0
)

if passed:

    print("""
🟢 BATCH 07 IS READY

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 07
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS
""")

else:

    print("""
🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.
""")

# ============================================================
# 15. SUMMARY
# ============================================================

print("=" * 100)
print("📊 BATCH 07 SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 416
Batch 07 questions          : 32

Exact overlaps              : {len(exact_overlap)}
Normalized overlaps         : {len(normalized_overlap)}

Pairs >= 0.80               : {len(similarity_df)}
Same-intent >= 0.80         : {len(same_intent)}
Cross-intent >= 0.80        : {len(cross_intent)}

Pairs >= 0.85               : {len(high_similarity)}
Pairs >= 0.90               : {len(very_high)}
Pairs >= 0.95               : {len(extreme)}
"""
)

# ============================================================
# 16. READ-ONLY CONFIRMATION
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_07.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 FINAL COMPLETE CHECK FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing questions : 416
Batch 07 questions : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448.
✅ No duplicate IDs.
✅ No ID overlap with existing 416.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 07
====================================================================================================
✅ No exact duplicates inside Batch 07.
✅ No normalized duplicates inside Batch 07.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs >= 0.80: 4

TOP SIMILAR PAIRS:
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      0.921    FAQ0422     INT002      English                What star rating does Nile Pearl Hotel receive?    FAQ0034     INT002      English                                       What star rating does Nile Pearl Hotel have?
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 4 pairs
0.85+ : 1 pairs
0.90+ : 1 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 4
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      0.921    FAQ0422     INT002      English                What star rating does Nile Pearl Hotel receive?    FAQ0034     INT002      English                                       What star rating does Nile Pearl Hotel have?
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 1
 similarity new_faq_id new_intent new_language                                    new_question old_faq_id old_intent old_language                                 old_question
      0.921    FAQ0422     INT002      English What star rating does Nile Pearl Hotel receive?    FAQ0034     INT002      English What star rating does Nile Pearl Hotel have?

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 1

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 0

====================================================================================================
🏆 BATCH 07 FINAL DECISION
====================================================================================================

🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.

====================================================================================================
📊 BATCH 07 SUMMARY
====================================================================================================

Existing questions          : 416
Batch 07 questions          : 32

Exact overlaps              : 0
Normalized overlaps         : 0

Pairs >= 0.80               : 4
Same-intent >= 0.80         : 4
Cross-intent >= 0.80        : 0

Pairs >= 0.85               : 1
Pairs >= 0.90               : 1
Pairs >= 0.95               : 0

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_07.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 07 FINAL COMPLETE CHECK FINISHED
====================================================================================================

In [73]:
from pathlib import Path
import pandas as pd
import unicodedata
import re

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

faq_id = "FAQ0422"

new_question = (
    "How is Nile Pearl Hotel categorized within hotel classifications?"
)

idx = batch_df.index[
    batch_df["faq_id"] == faq_id
].tolist()

assert len(idx) == 1

idx = idx[0]

old_question = batch_df.at[
    idx,
    "question"
]

batch_df.at[
    idx,
    "question"
] = new_question

print("=" * 100)
print("🏨 HOTEL AI - FINAL FAQ0422 REWRITE")
print("=" * 100)

print(f"\n🔄 {faq_id}")
print(f"OLD: {old_question}")
print(f"NEW: {new_question}")

# ------------------------------------------------------------
# BASIC CHECK
# ------------------------------------------------------------

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    return re.sub(
        r"\s+",
        " ",
        text
    ).strip()

batch_normalized = (
    batch_df["question"]
    .map(normalize)
)

assert not batch_df["question"].duplicated().any()
assert not batch_normalized.duplicated().any()

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 BATCH 07 UPDATED")
print("=" * 100)

print(BATCH_FILE)
print("✅ 32 rows preserved.")
print("✅ hotel_faq_final.csv was NOT modified.")

print("\n" + "=" * 100)
print("🎉 FAQ0422 FINAL REWRITE COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - FINAL FAQ0422 REWRITE
====================================================================================================

🔄 FAQ0422
OLD: What star rating does Nile Pearl Hotel receive?
NEW: How is Nile Pearl Hotel categorized within hotel classifications?

====================================================================================================
💾 BATCH 07 UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv
✅ 32 rows preserved.
✅ hotel_faq_final.csv was NOT modified.

====================================================================================================
🎉 FAQ0422 FINAL REWRITE COMPLETE
====================================================================================================

In [74]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK
# Existing dataset : 416
# Batch 07         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 07 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416, (
    f"❌ Existing dataset must contain 416 rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Batch 07 must contain 32 rows, found {len(batch_df)}"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing questions : {len(df)}")
print(f"Batch 07 questions : {len(batch_df)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID CHECK")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

id_overlap = (
    set(df["faq_id"])
    .intersection(set(batch_df["faq_id"]))
)

assert not id_overlap, (
    f"❌ ID overlap found: {id_overlap}"
)

print("✅ IDs are exactly FAQ0417 → FAQ0448.")
print("✅ No duplicate IDs.")
print("✅ No ID overlap with existing 416.")

# ============================================================
# 5. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 6. EXACT OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("📝 EXACT OVERLAP")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = sorted(
    existing_exact.intersection(
        batch_exact
    )
)

if exact_overlap:
    print("❌ Exact overlaps found:")
    for q in exact_overlap:
        print("-", q)
else:
    print("✅ No exact overlap.")

# ============================================================
# 7. NORMALIZED OVERLAP
# ============================================================

print("\n" + "=" * 100)
print("🔎 NORMALIZED OVERLAP")
print("=" * 100)

existing_normalized = set(
    df["question"].map(normalize)
)

batch_normalized = set(
    batch_df["question"].map(normalize)
)

normalized_overlap = sorted(
    existing_normalized.intersection(
        batch_normalized
    )
)

if normalized_overlap:
    print("❌ Normalized overlaps found:")
    for q in normalized_overlap:
        print("-", q)
else:
    print("✅ No normalized overlap.")

# ============================================================
# 8. DUPLICATES INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATES INSIDE BATCH 07")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

normalized_series = (
    batch_df["question"]
    .map(normalize)
)

normalized_duplicates = batch_df[
    normalized_series.duplicated(
        keep=False
    )
]

if exact_duplicates.empty:
    print("✅ No exact duplicates inside Batch 07.")
else:
    print("❌ Exact duplicates found:")
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

if normalized_duplicates.empty:
    print("✅ No normalized duplicates inside Batch 07.")
else:
    print("❌ Normalized duplicates found:")
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. SEMANTIC / TEXT SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 SEMANTIC / TEXT SIMILARITY")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs with similarity >= 0.80.")

else:

    similarity_df = (
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print("\nTOP SIMILAR PAIRS:")
    print(
        similarity_df
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 10. THRESHOLD SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 11. SAME-INTENT
# ============================================================

if similarity_df.empty:
    same_intent = pd.DataFrame()
else:
    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

if not same_intent.empty:

    print(
        same_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 12. CROSS-INTENT
# ============================================================

if similarity_df.empty:
    cross_intent = pd.DataFrame()
else:
    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

if not cross_intent.empty:

    print(
        cross_intent
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 13. HIGH / VERY HIGH / EXTREME
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

very_high = (
    similarity_df[
        similarity_df["similarity"] >= 0.90
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

extreme = (
    similarity_df[
        similarity_df["similarity"] >= 0.95
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY REVIEW")
print("=" * 100)

print(
    f"Similarity >= 0.85: {len(high_similarity)}"
)

if not high_similarity.empty:
    print(
        high_similarity
        .to_string(index=False)
    )
else:
    print("✅ No similarity >= 0.85.")

print("\n" + "=" * 100)
print("🔴 VERY HIGH SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.90: {len(very_high)}"
)

if not very_high.empty:
    print(
        very_high
        .to_string(index=False)
    )

print("\n" + "=" * 100)
print("🚨 EXTREME SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.95: {len(extreme)}"
)

if not extreme.empty:
    print(
        extreme
        .to_string(index=False)
    )

# ============================================================
# 14. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 07 FINAL DECISION")
print("=" * 100)

passed = (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and len(high_similarity) == 0
    and len(cross_intent) == 0
)

if passed:

    print("""
🟢 BATCH 07 IS READY

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 07
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS
""")

else:

    print("""
🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more duplicate/similarity checks require attention.
""")

# ============================================================
# 15. SUMMARY
# ============================================================

print("=" * 100)
print("📊 BATCH 07 SUMMARY")
print("=" * 100)

print(
    f"""
Existing questions          : 416
Batch 07 questions          : 32

Exact overlaps              : {len(exact_overlap)}
Normalized overlaps         : {len(normalized_overlap)}

Pairs >= 0.80               : {len(similarity_df)}
Same-intent >= 0.80         : {len(same_intent)}
Cross-intent >= 0.80        : {len(cross_intent)}

Pairs >= 0.85               : {len(high_similarity)}
Pairs >= 0.90               : {len(very_high)}
Pairs >= 0.95               : {len(extreme)}
"""
)

# ============================================================
# 16. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_07.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 FINAL COMPLETE CHECK FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 FINAL COMPLETE CHECK
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing questions : 416
Batch 07 questions : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID CHECK
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448.
✅ No duplicate IDs.
✅ No ID overlap with existing 416.

====================================================================================================
📝 EXACT OVERLAP
====================================================================================================
✅ No exact overlap.

====================================================================================================
🔎 NORMALIZED OVERLAP
====================================================================================================
✅ No normalized overlap.

====================================================================================================
📝 DUPLICATES INSIDE BATCH 07
====================================================================================================
✅ No exact duplicates inside Batch 07.
✅ No normalized duplicates inside Batch 07.

====================================================================================================
🔍 SEMANTIC / TEXT SIMILARITY
====================================================================================================
Pairs >= 0.80: 3

TOP SIMILAR PAIRS:
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 3 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 3
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

====================================================================================================
🚨 HIGH SIMILARITY REVIEW
====================================================================================================
Similarity >= 0.85: 0
✅ No similarity >= 0.85.

====================================================================================================
🔴 VERY HIGH SIMILARITY
====================================================================================================
Similarity >= 0.90: 0

====================================================================================================
🚨 EXTREME SIMILARITY
====================================================================================================
Similarity >= 0.95: 0

====================================================================================================
🏆 BATCH 07 FINAL DECISION
====================================================================================================

🟢 BATCH 07 IS READY

✅ No exact overlap
✅ No normalized overlap
✅ No duplicates inside Batch 07
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80

🎉 SAFE TO FILL GROUND TRUTH + ANSWERS

====================================================================================================
📊 BATCH 07 SUMMARY
====================================================================================================

Existing questions          : 416
Batch 07 questions          : 32

Exact overlaps              : 0
Normalized overlaps         : 0

Pairs >= 0.80               : 3
Same-intent >= 0.80         : 3
Cross-intent >= 0.80        : 0

Pairs >= 0.85               : 0
Pairs >= 0.90               : 0
Pairs >= 0.95               : 0

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_07.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 07 FINAL COMPLETE CHECK FINISHED
====================================================================================================

In [75]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 GROUND TRUTH + ANSWER REPAIR
# FILL ONLY BATCH 07
# FINAL DATASET REMAINS UNCHANGED
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 GROUND TRUTH + ANSWER REPAIR")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert FINAL_DATASET.exists(), "❌ Final dataset not found."
assert BATCH_FILE.exists(), "❌ Batch 07 not found."

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416
assert len(batch_df) == 32

print(f"Existing dataset : {len(df)}")
print(f"Batch 07         : {len(batch_df)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. TEXT DTYPES
# ============================================================

TEXT_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "difficulty",
    "answer",
]

for col in TEXT_COLUMNS:
    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

batch_df["attempts"] = pd.to_numeric(
    batch_df["attempts"],
    errors="raise"
)

# ============================================================
# 5. INTENT MAP
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

LANGUAGES = [
    "Arabic",
    "English",
    "French",
    "Russian",
]

# ============================================================
# 6. BUILD CANONICAL KNOWLEDGE MAP
# ============================================================

print("\n" + "=" * 100)
print("🧠 BUILDING KNOWLEDGE MAP")
print("=" * 100)

knowledge_map = {}

for intent_id, intent_name in INTENTS.items():

    for language in LANGUAGES:

        subset = df[
            (df["intent_id"] == intent_id)
            &
            (df["language"] == language)
        ].copy()

        assert len(subset) == 13, (
            f"❌ Expected 13 rows for "
            f"{intent_id} × {language}, "
            f"found {len(subset)}"
        )

        # Ground truth candidates
        gt = (
            subset["ground_truth"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        gt = gt[gt.ne("")]

        assert not gt.empty, (
            f"❌ Ground truth missing for "
            f"{intent_id} × {language}"
        )

        canonical_gt = (
            gt.value_counts()
            .index[0]
        )

        # Answer candidates
        answers = (
            subset["answer"]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        answers = answers[answers.ne("")]

        assert not answers.empty, (
            f"❌ Answer missing for "
            f"{intent_id} × {language}"
        )

        canonical_answer = (
            answers.value_counts()
            .index[0]
        )

        knowledge_map[
            (intent_id, language)
        ] = {
            "ground_truth": canonical_gt,
            "answer": canonical_answer,
        }

        print(
            f"✅ {intent_id:<6} {language:<8}"
        )

print("✅ Knowledge map created.")

# ============================================================
# 7. APPLY GROUND TRUTH + ANSWER
# ============================================================

print("\n" + "=" * 100)
print("✍️ FILLING GROUND TRUTH + ANSWERS")
print("=" * 100)

for idx, row in batch_df.iterrows():

    intent_id = str(
        row["intent_id"]
    ).strip()

    language = str(
        row["language"]
    ).strip()

    key = (
        intent_id,
        language
    )

    assert key in knowledge_map

    batch_df.at[
        idx,
        "ground_truth"
    ] = knowledge_map[key]["ground_truth"]

    batch_df.at[
        idx,
        "answer"
    ] = knowledge_map[key]["answer"]

    batch_df.at[
        idx,
        "status"
    ] = "generated"

    batch_df.at[
        idx,
        "category"
    ] = "Hotel FAQ"

    batch_df.at[
        idx,
        "source"
    ] = "Generated Batch 07"

    batch_df.at[
        idx,
        "attempts"
    ] = 0

    batch_df.at[
        idx,
        "difficulty"
    ] = "Easy"

# Re-cast text columns safely
for col in TEXT_COLUMNS:
    batch_df[col] = (
        batch_df[col]
        .fillna("")
        .astype("string")
    )

print("✅ Ground truth filled for all 32.")
print("✅ Answers filled for all 32.")

# ============================================================
# 8. REQUIRED FIELD VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    ok = (
        missing == 0
        and empty == 0
    )

    print(
        f"{'✅' if ok else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    assert ok, (
        f"❌ Invalid values in {col}"
    )

print("✅ All required fields complete.")

# ============================================================
# 9. BASIC BATCH VALIDATION
# ============================================================

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

assert batch_df["intent_id"].value_counts().to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

assert batch_df["language"].value_counts().to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

# ============================================================
# 10. SAVE BATCH ONLY
# ============================================================

batch_df.to_csv(
    BATCH_FILE,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 11. RELOAD + FINAL CHECK
# ============================================================

check_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(check_df) == 32

assert (
    check_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert (
    check_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

print("\n" + "=" * 100)
print("🏆 BATCH 07 REPAIR RESULT")
print("=" * 100)

print("""
🟢 BATCH 07 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0417 → FAQ0448
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions × 8 intents
✅ Existing 416 dataset NOT modified

🎉 READY FOR FINAL BATCH 07 AUDIT
""")

print("📄 Batch saved to:")
print(BATCH_FILE)

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)
print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows added to final dataset.")
print("✅ No rows deleted from final dataset.")
print("✅ No final-dataset values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 REPAIR COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 GROUND TRUTH + ANSWER REPAIR
====================================================================================================
Existing dataset : 416
Batch 07         : 32
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🧠 BUILDING KNOWLEDGE MAP
====================================================================================================
✅ INT001 Arabic
✅ INT001 English
✅ INT001 French
✅ INT001 Russian
✅ INT002 Arabic
✅ INT002 English
✅ INT002 French
✅ INT002 Russian
✅ INT003 Arabic
✅ INT003 English
✅ INT003 French
✅ INT003 Russian
✅ INT004 Arabic
✅ INT004 English
✅ INT004 French
✅ INT004 Russian
✅ INT005 Arabic
✅ INT005 English
✅ INT005 French
✅ INT005 Russian
✅ INT006 Arabic
✅ INT006 English
✅ INT006 French
✅ INT006 Russian
✅ INT007 Arabic
✅ INT007 English
✅ INT007 French
✅ INT007 Russian
✅ INT008 Arabic
✅ INT008 English
✅ INT008 French
✅ INT008 Russian
✅ Knowledge map created.

====================================================================================================
✍️ FILLING GROUND TRUTH + ANSWERS
====================================================================================================
✅ Ground truth filled for all 32.
✅ Answers filled for all 32.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
🏆 BATCH 07 REPAIR RESULT
====================================================================================================

🟢 BATCH 07 GROUND TRUTH + ANSWER COMPLETE

✅ 32 questions
✅ FAQ0417 → FAQ0448
✅ Ground truth complete
✅ Answers complete
✅ Required fields complete
✅ 8 Arabic
✅ 8 English
✅ 8 French
✅ 8 Russian
✅ 4 questions × 8 intents
✅ Existing 416 dataset NOT modified

🎉 READY FOR FINAL BATCH 07 AUDIT

📄 Batch saved to:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/batches/faq_batch_07.csv

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ No rows added to final dataset.
✅ No rows deleted from final dataset.
✅ No final-dataset values changed.

====================================================================================================
🎉 BATCH 07 REPAIR COMPLETE
====================================================================================================

In [76]:
# ============================================================
# 🏨 HOTEL AI - BATCH 07 FINAL COMPLETE AUDIT
# Existing dataset : 416
# Batch 07         : 32
# READ-ONLY
# ============================================================

from pathlib import Path
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata

print("=" * 100)
print("🏨 HOTEL AI - BATCH 07 FINAL COMPLETE AUDIT")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

assert PROJECT_ROOT.exists()
assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416, (
    f"❌ Expected 416 existing rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Expected 32 batch rows, found {len(batch_df)}"
)

print("\n" + "=" * 100)
print("📊 FILE INFORMATION")
print("=" * 100)

print(f"Existing dataset : {len(df)} rows")
print(f"Batch 07         : {len(batch_df)} rows")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. FAQ ID VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("🆔 FAQ ID VALIDATION")
print("=" * 100)

expected_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert batch_df["faq_id"].tolist() == expected_ids
assert batch_df["faq_id"].is_unique

id_overlap = (
    set(df["faq_id"])
    .intersection(set(batch_df["faq_id"]))
)

assert not id_overlap

print("✅ IDs are exactly FAQ0417 → FAQ0448.")
print("✅ No duplicate IDs.")
print("✅ No ID overlap with existing 416.")

# ============================================================
# 5. REQUIRED FIELD CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

required_ok = True

for col in REQUIRED_COLUMNS:

    missing = int(
        batch_df[col].isna().sum()
    )

    empty = int(
        batch_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    ok = (
        missing == 0
        and empty == 0
    )

    print(
        f"{'✅' if ok else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if not ok:
        required_ok = False

assert required_ok

print("✅ All required fields complete.")

# ============================================================
# 6. NORMALIZATION
# ============================================================

def normalize(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

# ============================================================
# 7. DUPLICATE CHECK INSIDE BATCH
# ============================================================

print("\n" + "=" * 100)
print("📝 DUPLICATE CHECK INSIDE BATCH 07")
print("=" * 100)

exact_duplicates = batch_df[
    batch_df["question"].duplicated(
        keep=False
    )
]

batch_normalized = (
    batch_df["question"]
    .map(normalize)
)

normalized_duplicates = batch_df[
    batch_normalized.duplicated(
        keep=False
    )
]

assert exact_duplicates.empty
assert normalized_duplicates.empty

print("✅ No exact duplicates.")
print("✅ No normalized duplicates.")

# ============================================================
# 8. OVERLAP WITH EXISTING 416
# ============================================================

print("\n" + "=" * 100)
print("🔎 OVERLAP WITH EXISTING 416")
print("=" * 100)

existing_exact = set(
    df["question"]
    .astype(str)
    .str.strip()
)

batch_exact = set(
    batch_df["question"]
    .astype(str)
    .str.strip()
)

exact_overlap = (
    existing_exact
    .intersection(batch_exact)
)

existing_normalized = set(
    df["question"]
    .map(normalize)
)

normalized_overlap = (
    existing_normalized
    .intersection(set(batch_normalized))
)

assert not exact_overlap
assert not normalized_overlap

print("✅ No exact overlap.")
print("✅ No normalized overlap.")

# ============================================================
# 9. LANGUAGE CHECK
# ============================================================

print("\n" + "=" * 100)
print("🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    batch_df["language"]
    .value_counts()
    .sort_index()
)

print(language_counts.to_string())

assert language_counts.to_dict() == {
    "Arabic": 8,
    "English": 8,
    "French": 8,
    "Russian": 8,
}

print("✅ 8 questions × 4 languages.")

# ============================================================
# 10. INTENT CHECK
# ============================================================

print("\n" + "=" * 100)
print("🎯 INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    batch_df["intent_id"]
    .value_counts()
    .sort_index()
)

print(intent_counts.to_string())

assert intent_counts.to_dict() == {
    "INT001": 4,
    "INT002": 4,
    "INT003": 4,
    "INT004": 4,
    "INT005": 4,
    "INT006": 4,
    "INT007": 4,
    "INT008": 4,
}

print("✅ 4 questions × 8 intents.")

# ============================================================
# 11. INTENT NAME CONSISTENCY
# ============================================================

INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

for _, row in batch_df.iterrows():

    assert (
        row["intent_name"]
        == INTENTS[row["intent_id"]]
    )

print("✅ Intent ID ↔ Intent Name consistency.")

# ============================================================
# 12. QUESTION TYPES
# ============================================================

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

assert (
    set(batch_df["question_type"])
    <= VALID_TYPES
)

print("\n" + "=" * 100)
print("📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)

print(
    batch_df["question_type"]
    .value_counts()
    .to_string()
)

print("✅ All question types are valid.")

# ============================================================
# 13. STATUS / DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 STATUS / DIFFICULTY")
print("=" * 100)

assert set(batch_df["status"]) <= {
    "valid",
    "generated"
}

assert set(batch_df["difficulty"]) <= {
    "Easy"
}

print("Status:")
print(
    batch_df["status"]
    .value_counts()
    .to_string()
)

print("\nDifficulty:")
print(
    batch_df["difficulty"]
    .value_counts()
    .to_string()
)

print("✅ Status valid.")
print("✅ Difficulty valid.")

# ============================================================
# 14. GROUND TRUTH / ANSWER
# ============================================================

print("\n" + "=" * 100)
print("🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

ground_truth_ok = (
    batch_df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_ok = (
    batch_df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

assert ground_truth_ok
assert answers_ok

print("✅ Ground truth complete.")
print("✅ Answers complete.")

# ============================================================
# 15. ATTEMPTS
# ============================================================

attempts_numeric = pd.to_numeric(
    batch_df["attempts"],
    errors="coerce"
)

assert attempts_numeric.notna().all()
assert (attempts_numeric >= 0).all()

print("\n" + "=" * 100)
print("🔢 ATTEMPTS")
print("=" * 100)

print("✅ Attempts are numeric and non-negative.")
print(f"Min    : {attempts_numeric.min()}")
print(f"Max    : {attempts_numeric.max()}")
print(f"Average: {attempts_numeric.mean():.2f}")

# ============================================================
# 16. QUESTION LENGTH
# ============================================================

question_lengths = (
    batch_df["question"]
    .astype(str)
    .str.len()
)

short_questions = batch_df[
    question_lengths < 10
]

assert short_questions.empty

print("\n" + "=" * 100)
print("📏 QUESTION LENGTH")
print("=" * 100)

print(f"Shortest : {question_lengths.min()}")
print(f"Longest  : {question_lengths.max()}")
print(f"Average  : {question_lengths.mean():.2f}")
print("✅ No suspiciously short questions.")

# ============================================================
# 17. FULL SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 FULL SIMILARITY CHECK")
print("=" * 100)

similar_pairs = []

for _, new_row in batch_df.iterrows():

    for _, old_row in df.iterrows():

        score = SequenceMatcher(
            None,
            normalize(new_row["question"]),
            normalize(old_row["question"])
        ).ratio()

        if score >= 0.80:

            similar_pairs.append({
                "similarity": round(score, 3),

                "new_faq_id": new_row["faq_id"],
                "new_intent": new_row["intent_id"],
                "new_language": new_row["language"],
                "new_question": new_row["question"],

                "old_faq_id": old_row["faq_id"],
                "old_intent": old_row["intent_id"],
                "old_language": old_row["language"],
                "old_question": old_row["question"],
            })

similarity_df = pd.DataFrame(similar_pairs)

if similarity_df.empty:

    print("🎉 No pairs >= 0.80.")

else:

    similarity_df = (
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print(
        f"Pairs >= 0.80: {len(similarity_df)}"
    )

    print(
        similarity_df
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 18. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 SIMILARITY THRESHOLDS")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95,
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 19. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["new_intent"]
        ==
        similarity_df["old_intent"]
    ]

    cross_intent = similarity_df[
        similarity_df["new_intent"]
        !=
        similarity_df["old_intent"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(same_intent)}"
)

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f">= 0.80 : {len(cross_intent)}"
)

# ============================================================
# 20. HIGH SIMILARITY
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"] >= 0.85
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

print("\n" + "=" * 100)
print("🚨 HIGH SIMILARITY")
print("=" * 100)

print(
    f"Similarity >= 0.85 : {len(high_similarity)}"
)

if not high_similarity.empty:

    print(
        high_similarity
        .to_string(index=False)
    )

else:

    print("✅ No similarity >= 0.85.")

# ============================================================
# 21. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("🏆 BATCH 07 FINAL RESULT")
print("=" * 100)

passed = (
    len(exact_overlap) == 0
    and len(normalized_overlap) == 0
    and exact_duplicates.empty
    and normalized_duplicates.empty
    and ground_truth_ok
    and answers_ok
    and high_similarity.empty
    and cross_intent.empty
)

if passed:

    print("""
🟢 BATCH 07 IS FULLY VALID

✅ 32 questions
✅ FAQ0417 → FAQ0448
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balanced
✅ Intent balanced
✅ Intent names consistent
✅ Question types valid

🎉 SAFE TO MERGE BATCH 07
""")

else:

    print("""
🟡 BATCH 07 STILL NEEDS REVIEW

⚠️ One or more checks require attention.
""")

# ============================================================
# 22. READ-ONLY
# ============================================================

print("=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ faq_batch_07.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

print("\n" + "=" * 100)
print("🎉 BATCH 07 FINAL AUDIT COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - BATCH 07 FINAL COMPLETE AUDIT
====================================================================================================

====================================================================================================
📊 FILE INFORMATION
====================================================================================================
Existing dataset : 416 rows
Batch 07         : 32 rows
✅ All 13 columns exist.
✅ Column order is correct.

====================================================================================================
🆔 FAQ ID VALIDATION
====================================================================================================
✅ IDs are exactly FAQ0417 → FAQ0448.
✅ No duplicate IDs.
✅ No ID overlap with existing 416.

====================================================================================================
🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0
✅ All required fields complete.

====================================================================================================
📝 DUPLICATE CHECK INSIDE BATCH 07
====================================================================================================
✅ No exact duplicates.
✅ No normalized duplicates.

====================================================================================================
🔎 OVERLAP WITH EXISTING 416
====================================================================================================
✅ No exact overlap.
✅ No normalized overlap.

====================================================================================================
🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
Arabic     8
English    8
French     8
Russian    8
✅ 8 questions × 4 languages.

====================================================================================================
🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id
INT001    4
INT002    4
INT003    4
INT004    4
INT005    4
INT006    4
INT007    4
INT008    4
✅ 4 questions × 8 intents.
✅ Intent ID ↔ Intent Name consistency.

====================================================================================================
📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    16
Scenario        8
Direct          8
✅ All question types are valid.

====================================================================================================
📌 STATUS / DIFFICULTY
====================================================================================================
Status:
status
generated    32

Difficulty:
difficulty
Easy    32
✅ Status valid.
✅ Difficulty valid.

====================================================================================================
🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🔢 ATTEMPTS
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 0
Average: 0.00

====================================================================================================
📏 QUESTION LENGTH
====================================================================================================
Shortest : 39
Longest  : 106
Average  : 63.53
✅ No suspiciously short questions.

====================================================================================================
🔍 FULL SIMILARITY CHECK
====================================================================================================
Pairs >= 0.80: 3
 similarity new_faq_id new_intent new_language                                                   new_question old_faq_id old_intent old_language                                                                       old_question
      0.814    FAQ0423     INT002       French   Quelle est la classification hôtelière du Nile Pearl Hotel ?    FAQ0053     INT002       French                           Quelle est la categorisation étoile du Nile Pearl Hotel?
      0.811    FAQ0434     INT005      English         By what time are guests expected to vacate their room?    FAQ0274     INT005      English                        By what time do guests normally need to vacate their rooms?
      0.800    FAQ0435     INT005       French Quelle est l'heure habituelle limite pour quitter la chambre ?    FAQ0339     INT005       French Quelle est l'heure habituelle limite pour libérer la chambre au Nile Pearl Hotel ?

====================================================================================================
📊 SIMILARITY THRESHOLDS
====================================================================================================
0.80+ : 3 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 3

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
>= 0.80 : 0

====================================================================================================
🚨 HIGH SIMILARITY
====================================================================================================
Similarity >= 0.85 : 0
✅ No similarity >= 0.85.

====================================================================================================
🏆 BATCH 07 FINAL RESULT
====================================================================================================

🟢 BATCH 07 IS FULLY VALID

✅ 32 questions
✅ FAQ0417 → FAQ0448
✅ Required fields complete
✅ Ground truth complete
✅ Answers complete
✅ No duplicate questions
✅ No normalized overlap
✅ No similarity >= 0.85
✅ No cross-intent similarity >= 0.80
✅ Language balanced
✅ Intent balanced
✅ Intent names consistent
✅ Question types valid

🎉 SAFE TO MERGE BATCH 07

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ faq_batch_07.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 BATCH 07 FINAL AUDIT COMPLETE
====================================================================================================

In [77]:
# ============================================================
# 🏨 HOTEL AI - MERGE BATCH 07
# 416 + 32 = 448 QUESTIONS
# ============================================================

from pathlib import Path
from datetime import datetime
import pandas as pd

print("=" * 100)
print("🏨 HOTEL AI - MERGE BATCH 07")
print("=" * 100)

# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

FINAL_DATASET = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

BATCH_FILE = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "batches"
    / "faq_batch_07.csv"
)

BACKUP_DIR = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "backups"
)

assert PROJECT_ROOT.exists()
assert FINAL_DATASET.exists()
assert BATCH_FILE.exists()

# ============================================================
# 2. LOAD FILES
# ============================================================

df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

batch_df = pd.read_csv(
    BATCH_FILE,
    encoding="utf-8-sig"
)

assert len(df) == 416, (
    f"❌ Expected 416 current rows, found {len(df)}"
)

assert len(batch_df) == 32, (
    f"❌ Expected 32 batch rows, found {len(batch_df)}"
)

print(f"Current dataset : {len(df)}")
print(f"Batch 07        : {len(batch_df)}")

# ============================================================
# 3. REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

assert list(df.columns) == REQUIRED_COLUMNS
assert list(batch_df.columns) == REQUIRED_COLUMNS

print("✅ All 13 columns exist.")
print("✅ Column order is correct.")

# ============================================================
# 4. BACKUP
# ============================================================

BACKUP_DIR.mkdir(
    parents=True,
    exist_ok=True
)

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_path = (
    BACKUP_DIR
    / f"hotel_faq_before_batch07_{timestamp}.csv"
)

df.to_csv(
    backup_path,
    index=False,
    encoding="utf-8-sig"
)

print()
print("💾 Backup created:")
print(backup_path)

# ============================================================
# 5. BATCH ID CHECK
# ============================================================

print("\n" + "=" * 100)
print("🆔 BATCH ID VALIDATION")
print("=" * 100)

expected_batch_ids = [
    f"FAQ{i:04d}"
    for i in range(417, 449)
]

assert (
    batch_df["faq_id"].tolist()
    == expected_batch_ids
)

assert batch_df["faq_id"].is_unique

print("✅ Batch IDs: FAQ0417 → FAQ0448")
print("✅ No duplicate batch IDs.")

# ============================================================
# 6. ID OVERLAP
# ============================================================

existing_ids = set(df["faq_id"])
batch_ids = set(batch_df["faq_id"])

id_overlap = existing_ids.intersection(
    batch_ids
)

assert not id_overlap, (
    f"❌ FAQ ID overlap found: {id_overlap}"
)

print("✅ No FAQ ID overlap.")

# ============================================================
# 7. NORMALIZATION
# ============================================================

def normalize_question(text):
    return (
        str(text)
        .casefold()
        .strip()
    )

# ============================================================
# 8. QUESTION OVERLAP
# ============================================================

existing_questions = set(
    df["question"]
    .map(normalize_question)
)

batch_questions = set(
    batch_df["question"]
    .map(normalize_question)
)

question_overlap = (
    existing_questions
    .intersection(batch_questions)
)

assert not question_overlap, (
    f"❌ Question overlap found: {question_overlap}"
)

assert not batch_df[
    "question"
].duplicated().any()

print("✅ No question overlap.")
print("✅ No duplicate questions inside Batch 07.")

# ============================================================
# 9. MERGE
# ============================================================

merged_df = pd.concat(
    [
        df,
        batch_df
    ],
    ignore_index=True
)

# ============================================================
# 10. FINAL ROW COUNT
# ============================================================

assert len(merged_df) == 448

# ============================================================
# 11. FINAL IDS
# ============================================================

expected_final_ids = [
    f"FAQ{i:04d}"
    for i in range(1, 449)
]

assert (
    merged_df["faq_id"].tolist()
    == expected_final_ids
)

assert merged_df["faq_id"].is_unique

# ============================================================
# 12. FINAL QUESTION DUPLICATES
# ============================================================

assert not merged_df[
    "question"
].duplicated().any()

merged_normalized = (
    merged_df["question"]
    .map(normalize_question)
)

assert not merged_normalized.duplicated().any()

# ============================================================
# 13. REQUIRED FIELD CHECK
# ============================================================

for col in REQUIRED_COLUMNS:

    assert not merged_df[col].isna().any()

    assert not (
        merged_df[col]
        .astype(str)
        .str.strip()
        .eq("")
        .any()
    )

# ============================================================
# 14. MERGE VALIDATION
# ============================================================

print("\n" + "=" * 100)
print("📊 MERGE VALIDATION")
print("=" * 100)

print("✅ Final row count: 448")
print("✅ IDs continuous: FAQ0001 → FAQ0448")
print("✅ No duplicate IDs")
print("✅ No duplicate questions")
print("✅ No normalized duplicates")
print("✅ All required fields complete")

# ============================================================
# 15. SAVE
# ============================================================

merged_df.to_csv(
    FINAL_DATASET,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("💾 FINAL DATASET UPDATED")
print("=" * 100)

print(FINAL_DATASET)

# ============================================================
# 16. RELOAD + VERIFY
# ============================================================

check_df = pd.read_csv(
    FINAL_DATASET,
    encoding="utf-8-sig"
)

assert len(check_df) == 448

assert (
    check_df["faq_id"].tolist()
    == expected_final_ids
)

assert check_df["faq_id"].is_unique

assert not check_df[
    "question"
].duplicated().any()

check_normalized = (
    check_df["question"]
    .map(normalize_question)
)

assert not check_normalized.duplicated().any()

# ============================================================
# 17. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("🏆 MERGE RESULT")
print("=" * 100)

print("""
🟢 BATCH 07 MERGED SUCCESSFULLY

Previous dataset : 416
Added questions  : 32
Final dataset    : 448

IDs:
FAQ0001 → FAQ0448

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ All required fields complete
✅ Final dataset reloaded successfully
""")

print("🔒 Backup:")
print(backup_path)

print("\n" + "=" * 100)
print("🎉 MERGE BATCH 07 COMPLETE")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - MERGE BATCH 07
====================================================================================================
Current dataset : 416
Batch 07        : 32
✅ All 13 columns exist.
✅ Column order is correct.

💾 Backup created:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch07_20260821_160530.csv

====================================================================================================
🆔 BATCH ID VALIDATION
====================================================================================================
✅ Batch IDs: FAQ0417 → FAQ0448
✅ No duplicate batch IDs.
✅ No FAQ ID overlap.
✅ No question overlap.
✅ No duplicate questions inside Batch 07.

====================================================================================================
📊 MERGE VALIDATION
====================================================================================================
✅ Final row count: 448
✅ IDs continuous: FAQ0001 → FAQ0448
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ All required fields complete

====================================================================================================
💾 FINAL DATASET UPDATED
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

====================================================================================================
🏆 MERGE RESULT
====================================================================================================

🟢 BATCH 07 MERGED SUCCESSFULLY

Previous dataset : 416
Added questions  : 32
Final dataset    : 448

IDs:
FAQ0001 → FAQ0448

✅ Backup created
✅ 32 questions added
✅ No duplicate IDs
✅ No duplicate questions
✅ No normalized duplicates
✅ IDs continuous
✅ All required fields complete
✅ Final dataset reloaded successfully

🔒 Backup:
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/backups/hotel_faq_before_batch07_20260821_160530.csv

====================================================================================================
🎉 MERGE BATCH 07 COMPLETE
====================================================================================================

In [78]:
# ============================================================
# 🏨 HOTEL AI - COMPLETE 448 DATASET AUDIT
# FULL QUALITY + DUPLICATE + SIMILARITY
# READ-ONLY
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher
import pandas as pd
import re
import unicodedata
import numpy as np

print("=" * 100)
print("🏨 HOTEL AI - COMPLETE 448 DATASET AUDIT")
print("=" * 100)

# ============================================================
# 1. CONFIG
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 448

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

SIMILARITY_THRESHOLD = 0.85

# ============================================================
# 2. LOAD
# ============================================================

assert PROJECT_ROOT.exists(), "❌ Project root not found."
assert DATASET_PATH.exists(), "❌ Dataset not found."

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n📂 PROJECT")
print("=" * 100)
print(PROJECT_ROOT)

print("\n📄 DATASET")
print("=" * 100)
print(DATASET_PATH)

print("\n📊 DATASET INFORMATION")
print("=" * 100)
print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")

checks = {}

# ============================================================
# 3. COLUMNS
# ============================================================

columns_ok = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

checks["13 columns"] = columns_ok

print("\n🧪 COLUMN VALIDATION")
print("=" * 100)

print(
    "✅ All 13 required columns exist."
    if columns_ok
    else "❌ Column validation failed."
)

if columns_ok:
    print("✅ Column order is correct.")

# ============================================================
# 4. ROW COUNT
# ============================================================

row_count_ok = len(df) == EXPECTED_ROWS

checks["448 questions"] = row_count_ok

print("\n📦 ROW COUNT")
print("=" * 100)
print(f"Total questions: {len(df)}")

print(
    "✅ Exactly 448 questions."
    if row_count_ok
    else "❌ Expected 448 questions."
)

# ============================================================
# 5. REQUIRED FIELDS
# ============================================================

required_ok = True

print("\n🧪 REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in EXPECTED_COLUMNS:

    missing = int(df[col].isna().sum())

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    ok = (
        missing == 0
        and empty == 0
    )

    print(
        f"{'✅' if ok else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<3}"
        f"Empty: {empty:<3}"
    )

    if not ok:
        required_ok = False

checks["Required fields"] = required_ok

# ============================================================
# 6. FAQ IDs
# ============================================================

print("\n🆔 FAQ ID VALIDATION")
print("=" * 100)

valid_id_format = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

duplicate_ids = df[
    df["faq_id"].duplicated(keep=False)
]

numeric_ids = pd.to_numeric(
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0],
    errors="coerce"
)

expected_numeric_ids = np.arange(
    1,
    EXPECTED_ROWS + 1
)

continuous_ids = (
    numeric_ids.notna().all()
    and numeric_ids.astype(int).tolist()
    == expected_numeric_ids.tolist()
)

checks["Valid FAQ IDs"] = bool(valid_id_format)
checks["No duplicate IDs"] = duplicate_ids.empty
checks["Continuous IDs"] = bool(continuous_ids)

print(
    "✅ All FAQ IDs have valid format."
    if valid_id_format
    else "❌ Invalid FAQ ID format."
)

print(
    "✅ No duplicate FAQ IDs."
    if duplicate_ids.empty
    else f"❌ Duplicate IDs found: {len(duplicate_ids)}"
)

print(
    "✅ IDs continuous: FAQ0001 → FAQ0448"
    if continuous_ids
    else "❌ IDs are not continuous."
)

# ============================================================
# 7. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)

# ============================================================
# 8. EXACT DUPLICATES
# ============================================================

exact_duplicates = df[
    df["question"].duplicated(keep=False)
]

checks["No exact duplicates"] = (
    exact_duplicates.empty
)

print("\n📝 EXACT DUPLICATE CHECK")
print("=" * 100)

if exact_duplicates.empty:
    print("✅ No exact duplicate questions.")
else:
    print(
        exact_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 9. NORMALIZED DUPLICATES
# ============================================================

normalized_duplicates = df[
    df["_normalized_question"].duplicated(
        keep=False
    )
]

checks["No normalized duplicates"] = (
    normalized_duplicates.empty
)

print("\n🔎 NORMALIZED DUPLICATE CHECK")
print("=" * 100)

if normalized_duplicates.empty:
    print("✅ No normalized duplicate questions.")
else:
    print(
        normalized_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 10. SAME-INTENT DUPLICATES
# ============================================================

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized_question"
        ],
        keep=False
    )
]

checks["No same-intent duplicates"] = (
    same_intent_duplicates.empty
)

print("\n🔍 DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

if same_intent_duplicates.empty:
    print("✅ No normalized duplicates inside the same intent.")
else:
    print(
        same_intent_duplicates[
            ["faq_id", "intent_id", "language", "question"]
        ].to_string(index=False)
    )

# ============================================================
# 11. INTENT MAPPING
# ============================================================

intent_mapping_ok = True

print("\n🔗 INTENT ID ↔ INTENT NAME")
print("=" * 100)

for intent_id, intent_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    actual_names = set(
        subset["intent_name"].astype(str)
    )

    ok = (
        len(subset) == 56
        and actual_names == {intent_name}
    )

    if not ok:
        intent_mapping_ok = False

    print(
        f"{'✅' if ok else '❌'} "
        f"{intent_id} → {intent_name} "
        f"| rows={len(subset)}"
    )

checks["Intent mappings"] = intent_mapping_ok

# ============================================================
# 12. LANGUAGE DISTRIBUTION
# ============================================================

language_counts = (
    df["language"]
    .value_counts()
)

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and all(
        language_counts.get(
            language,
            0
        ) == 112
        for language in EXPECTED_LANGUAGES
    )
)

checks["Language balance"] = language_balance_ok

print("\n🌍 LANGUAGE DISTRIBUTION")
print("=" * 100)
print(language_counts.to_string())

print(
    "✅ 112 questions × 4 languages."
    if language_balance_ok
    else "❌ Language balance failed."
)

# ============================================================
# 13. INTENT DISTRIBUTION
# ============================================================

intent_counts = (
    df["intent_id"]
    .value_counts()
)

intent_balance_ok = all(
    int(
        intent_counts.get(
            intent_id,
            0
        )
    ) == 56
    for intent_id in EXPECTED_INTENTS
)

checks["Intent balance"] = intent_balance_ok

print("\n🎯 INTENT DISTRIBUTION")
print("=" * 100)

print(
    df.groupby(
        ["intent_id", "intent_name"]
    )
    .size()
    .rename("questions")
    .reset_index()
    .to_string(index=False)
)

print(
    "✅ 56 questions × 8 intents."
    if intent_balance_ok
    else "❌ Intent balance failed."
)

# ============================================================
# 14. LANGUAGE × INTENT
# ============================================================

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

language_intent_ok = True

for intent_id in EXPECTED_INTENTS:

    for language in EXPECTED_LANGUAGES:

        count = int(
            language_intent.loc[
                intent_id,
                language
            ]
        )

        if count != 14:
            language_intent_ok = False

checks["Language × Intent"] = language_intent_ok

print("\n📊 LANGUAGE × INTENT MATRIX")
print("=" * 100)
print(language_intent.to_string())

print(
    "✅ Every intent has 14 questions per language."
    if language_intent_ok
    else "❌ Language × Intent balance failed."
)

# ============================================================
# 15. QUESTION TYPES
# ============================================================

question_type_counts = (
    df["question_type"]
    .value_counts()
)

unexpected_types = (
    set(df["question_type"])
    - VALID_TYPES
)

question_types_ok = not unexpected_types

checks["Question types"] = question_types_ok

print("\n📝 QUESTION TYPE DISTRIBUTION")
print("=" * 100)
print(question_type_counts.to_string())

print(
    "✅ All question types are valid."
    if question_types_ok
    else f"❌ Invalid question types: {unexpected_types}"
)

# ============================================================
# 16. STATUS
# ============================================================

status_counts = (
    df["status"]
    .value_counts()
)

unexpected_status = (
    set(df["status"])
    - VALID_STATUS
)

status_ok = not unexpected_status

checks["Status"] = status_ok

print("\n📌 STATUS DISTRIBUTION")
print("=" * 100)
print(status_counts.to_string())

print(
    "✅ Status values are valid."
    if status_ok
    else f"❌ Invalid statuses: {unexpected_status}"
)

# ============================================================
# 17. DIFFICULTY
# ============================================================

difficulty_counts = (
    df["difficulty"]
    .value_counts()
)

unexpected_difficulty = (
    set(df["difficulty"])
    - VALID_DIFFICULTY
)

difficulty_ok = not unexpected_difficulty

checks["Difficulty"] = difficulty_ok

print("\n📌 DIFFICULTY DISTRIBUTION")
print("=" * 100)
print(difficulty_counts.to_string())

print(
    "✅ Difficulty values are valid."
    if difficulty_ok
    else f"❌ Invalid difficulty: {unexpected_difficulty}"
)

# ============================================================
# 18. GROUND TRUTH / ANSWERS
# ============================================================

ground_truth_ok = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answers_ok = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

checks["Ground truth"] = bool(ground_truth_ok)
checks["Answers"] = bool(answers_ok)

print("\n🎯 GROUND TRUTH / ANSWER")
print("=" * 100)

print(
    "✅ Ground truth complete."
    if ground_truth_ok
    else "❌ Ground truth incomplete."
)

print(
    "✅ Answers complete."
    if answers_ok
    else "❌ Answers incomplete."
)

# ============================================================
# 19. GROUND TRUTH / ANSWER WORDING
# ============================================================

gt_norm = df["ground_truth"].map(normalize_text)
answer_norm = df["answer"].map(normalize_text)

wording_difference = (
    gt_norm != answer_norm
)

print("\n🔗 GROUND TRUTH ↔ ANSWER")
print("=" * 100)

print(
    "Rows with different wording:",
    int(wording_difference.sum())
)

print(
    "ℹ️ Different wording alone is not treated as a failure."
)

# ============================================================
# 20. ATTEMPTS
# ============================================================

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

attempts_ok = (
    attempts_numeric.notna().all()
    and (attempts_numeric >= 0).all()
)

checks["Attempts"] = attempts_ok

print("\n🔢 ATTEMPTS VALIDATION")
print("=" * 100)

print(
    "✅ Attempts are numeric and non-negative."
    if attempts_ok
    else "❌ Invalid attempts values."
)

print(f"Min    : {attempts_numeric.min()}")
print(f"Max    : {attempts_numeric.max()}")
print(f"Average: {attempts_numeric.mean():.2f}")

# ============================================================
# 21. QUESTION LENGTH
# ============================================================

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

very_short = df[
    question_lengths < 10
]

question_length_ok = very_short.empty

checks["Question length"] = question_length_ok

print("\n📏 QUESTION LENGTH")
print("=" * 100)

print(f"Shortest : {question_lengths.min()}")
print(f"Longest  : {question_lengths.max()}")
print(f"Average  : {question_lengths.mean():.2f}")

print(
    "✅ No suspiciously short questions."
    if question_length_ok
    else "⚠️ Suspiciously short questions found."
)

# ============================================================
# 22. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n🔍 FULL QUESTION SIMILARITY")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= 0.80:

        similarity_pairs.append({
            "similarity": round(score, 3),
            "faq_id_1": df.iloc[i]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "language_1": df.iloc[i]["language"],
            "question_1": questions[i],
            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "language_2": df.iloc[j]["language"],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(
    similarity_pairs
)

# ============================================================
# 23. THRESHOLD SUMMARY
# ============================================================

print("\n📊 SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [
    0.80,
    0.85,
    0.90,
    0.95
]:

    if similarity_df.empty:
        count = 0
    else:
        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )

# ============================================================
# 24. SAME / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

print("\n🎯 SAME-INTENT SIMILARITY")
print("=" * 100)
print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

print("\n⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)
print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)

# ============================================================
# 25. TOP SIMILAR
# ============================================================

print("\n📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:

    print("None.")

else:

    print(
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 26. HIGH SIMILARITY
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"]
        >= SIMILARITY_THRESHOLD
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

checks["Similarity < 0.85"] = (
    high_similarity.empty
)

print("\n🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print("✅ No similarity >= 0.85.")

else:

    print(
        f"❌ {len(high_similarity)} pairs >= 0.85"
    )

    print(
        high_similarity
        .sort_values(
            "similarity",
            ascending=False
        )
        .to_string(index=False)
    )

# ============================================================
# 27. FINAL SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed = sum(checks.values())
total = len(checks)

score = (
    passed / total * 100
)

print("-" * 100)

print(
    f"Passed checks      : {passed}/{total}"
)

print(
    f"Validation Score   : {score:.1f}%"
)

if score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )

# ============================================================
# 28. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 FINAL SUMMARY")
print("=" * 100)

print(f"Questions : {len(df)}")

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    intent_counts.to_string()
)

print("\nLanguage × Intent:")
print(
    language_intent.to_string()
)

print("\nQuestion Types:")
print(
    question_type_counts.to_string()
)

print("\nStatus:")
print(
    status_counts.to_string()
)

print("\nDifficulty:")
print(
    difficulty_counts.to_string()
)

print(
    f"\nSimilarity >= 0.85: "
    f"{len(high_similarity)}"
)

# ============================================================
# 29. READ-ONLY
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print("✅ hotel_faq_final.csv was NOT modified.")
print("✅ No rows added.")
print("✅ No rows deleted.")
print("✅ No values changed.")

# ============================================================
# 30. CLEAN MEMORY ONLY
# ============================================================

df.drop(
    columns=["_normalized_question"],
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 100)
print("🎉 COMPLETE 448-QUESTION AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - COMPLETE 448 DATASET AUDIT
====================================================================================================

📂 PROJECT
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent

📄 DATASET
====================================================================================================
/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv

📊 DATASET INFORMATION
====================================================================================================
Rows    : 448
Columns : 13

🧪 COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

📦 ROW COUNT
====================================================================================================
Total questions: 448
✅ Exactly 448 questions.

🧪 REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0  Empty: 0
✅ intent_id      Missing: 0  Empty: 0
✅ language       Missing: 0  Empty: 0
✅ question_type  Missing: 0  Empty: 0
✅ question       Missing: 0  Empty: 0
✅ status         Missing: 0  Empty: 0
✅ intent_name    Missing: 0  Empty: 0
✅ ground_truth   Missing: 0  Empty: 0
✅ category       Missing: 0  Empty: 0
✅ source         Missing: 0  Empty: 0
✅ attempts       Missing: 0  Empty: 0
✅ difficulty     Missing: 0  Empty: 0
✅ answer         Missing: 0  Empty: 0

🆔 FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ IDs continuous: FAQ0001 → FAQ0448

📝 EXACT DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

🔎 NORMALIZED DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

🔍 DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

🔗 INTENT ID ↔ INTENT NAME
====================================================================================================
✅ INT001 → hotel_location | rows=56
✅ INT002 → hotel_category | rows=56
✅ INT003 → reception_availability | rows=56
✅ INT004 → check_in_time | rows=56
✅ INT005 → check_out_time | rows=56
✅ INT006 → early_check_in | rows=56
✅ INT007 → late_check_out | rows=56
✅ INT008 → identification_required | rows=56

🌍 LANGUAGE DISTRIBUTION
====================================================================================================
language
English    112
Arabic     112
French     112
Russian    112
✅ 112 questions × 4 languages.

🎯 INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         56
   INT002          hotel_category         56
   INT003  reception_availability         56
   INT004           check_in_time         56
   INT005          check_out_time         56
   INT006          early_check_in         56
   INT007          late_check_out         56
   INT008 identification_required         56
✅ 56 questions × 8 intents.

📊 LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         14       14      14       14
INT002         14       14      14       14
INT003         14       14      14       14
INT004         14       14      14       14
INT005         14       14      14       14
INT006         14       14      14       14
INT007         14       14      14       14
INT008         14       14      14       14
✅ Every intent has 14 questions per language.

📝 QUESTION TYPE DISTRIBUTION
====================================================================================================
question_type
Paraphrased    180
Direct         148
Scenario       120
✅ All question types are valid.

📌 STATUS DISTRIBUTION
====================================================================================================
status
valid        224
generated    224
✅ Status values are valid.

📌 DIFFICULTY DISTRIBUTION
====================================================================================================
difficulty
Easy    448
✅ Difficulty values are valid.

🎯 GROUND TRUTH / ANSWER
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

🔗 GROUND TRUTH ↔ ANSWER
====================================================================================================
Rows with different wording: 407
ℹ️ Different wording alone is not treated as a failure.

🔢 ATTEMPTS VALIDATION
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 6
Average: 0.30

📏 QUESTION LENGTH
====================================================================================================
Shortest : 31
Longest  : 186
Average  : 75.50
✅ No suspiciously short questions.

🔍 FULL QUESTION SIMILARITY
====================================================================================================
Comparing 100,128 question pairs...

📊 SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 33 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 33

⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

📋 TOP 30 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1 language_1                                                                                                          question_1 faq_id_2 intent_2 language_2                                                                                                                                 question_2
      0.843  FAQ0065   INT003    English                                                 What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                 What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                            هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                         هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                    В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                          Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.836  FAQ0008   INT001    English                                     For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?  FAQ0386   INT001    English                                                                                 In which part of Cairo should I look for Nile Pearl Hotel?
      0.829  FAQ0004   INT001    English                                                                      In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                     Where can I find the Nile Pearl Hotel?
      0.828  FAQ0121   INT004    Russian                                                                          Когда можно заселиться в Nile Pearl Hotel?  FAQ0125   INT004    Russian                                                                                Когда стандартно можно заселиться в отель Nile Pearl Hotel?
      0.827  FAQ0235   INT008     Arabic                                              هل يجب علي تقديم إثبات هوية ساري عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0237   INT008     Arabic                                                         هل يحتاج الضيوف إلى تقديم وثائق إثبات الهوية عند تسجيل الوصول في Nile Pearl Hotel?
      0.824  FAQ0066   INT003    English                                         What are the hours of operation for the reception desk at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.821  FAQ0098   INT004    English                                                         What time does check-in normally begin at Nile Pearl Hotel?  FAQ0100   INT004    English                                                                               What time is check-in usually available at Nile Pearl Hotel?
      0.818  FAQ0017   INT001     French                                                                              Où se trouve l'hôtel Nile Pearl Hotel?  FAQ0019   INT001     French                                                                                      Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.818  FAQ0223   INT007    Russian Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?  FAQ0224   INT007    Russian Могу ли я получить поздний выезд из Nile Pearl Hotel, и если это возможно, под какие условия и будут ли какие-либо дополнительные расходы?
      0.816  FAQ0025   INT001    Russian                                                                  По какому адресу находится отель Nile Pearl Hotel?  FAQ0260   INT001    Russian                                                                                    В каком районе города находится отель Nile Pearl Hotel?
      0.816  FAQ0027   INT001    Russian                                                                              Где расположен отель Nile Pearl Hotel?  FAQ0388   INT001    Russian                                                                                                   Где в Каире расположен Nile Pearl Hotel?
      0.816  FAQ0252   INT008    Russian                                                    Какое удостоверение личности принимается от гостя при заселении?  FAQ0416   INT008    Russian                                                                            Какой вид удостоверения личности требуется гостю при заселении?
      0.814  FAQ0233   INT008     Arabic                                        ما نوع مستند إثبات الهوية المقبول عند تسجيل الوصول في فندق Nile Pearl Hotel؟  FAQ0234   INT008     Arabic                                                                    ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?
      0.814  FAQ0053   INT002     French                                                            Quelle est la categorisation étoile du Nile Pearl Hotel?  FAQ0423   INT002     French                                                                               Quelle est la classification hôtelière du Nile Pearl Hotel ?
      0.814  FAQ0222   INT007    Russian                      Могу ли я получить поздний выезд из Nile Pearl Hotel, и какие возможны дополнительные расходы?  FAQ0223   INT007    Russian                        Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?
      0.812  FAQ0044   INT002     Arabic                                                               كم عدد النجوم التي يُصنَّف بها فندق Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                             كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.811  FAQ0274   INT005    English                                                         By what time do guests normally need to vacate their rooms?  FAQ0434   INT005    English                                                                                     By what time are guests expected to vacate their room?
      0.811  FAQ0001   INT001    English                                                                                  Where is Nile Pearl Hotel located?  FAQ0003   INT001    English                                                                                                 In which city is Nile Pearl Hotel located?
      0.810  FAQ0312   INT006    Russian                                          Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?  FAQ0376   INT006    Russian                                                        Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?
      0.809  FAQ0003   INT001    English                                                                          In which city is Nile Pearl Hotel located?  FAQ0258   INT001    English                                                                                     Which part of the city is Nile Pearl Hotel located in?
      0.807  FAQ0098   INT004    English                                                         What time does check-in normally begin at Nile Pearl Hotel?  FAQ0102   INT004    English                                                                                  At what time can I normally check in at Nile Pearl Hotel?
      0.805  FAQ0204   INT007     Arabic                       هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وما العوامل التي تحدد إمكانية ذلك؟  FAQ0205   INT007     Arabic                                                           هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وهل توجد رسوم إضافية؟
      0.804  FAQ0251   INT008    Russian          Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0253   INT008    Russian                              Требуется ли гостям предъявлять документ, удостоверяющий личность, при регистрации заезда в Nile Pearl Hotel?
      0.804  FAQ0045   INT002     Arabic                                                                    ما فئة النجوم التي ينتمي إليها Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                             كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.804  FAQ0036   INT002    English                                                                What is the star classification of Nile Pearl Hotel?  FAQ0038   INT002    English                                                                                  What star classification is assigned to Nile Pearl Hotel?
      0.802  FAQ0217   INT007    Russian                               Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, что мне нужно знать?  FAQ0218   INT007    Russian                                                    Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?
      0.800  FAQ0137   INT005     Arabic                                                  متى يجب على النزيل إتمام إجراءات تسجيل الخروج من Nile Pearl Hotel؟  FAQ0139   INT005     Arabic                                                                    متى يجب على الضيوف إتمام تسجيل الخروج المعتاد من فندق Nile Pearl Hotel؟

🚨 HIGH-SIMILARITY REVIEW
====================================================================================================
✅ No similarity >= 0.85.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 13 columns
✅ 448 questions
✅ Required fields
✅ Valid FAQ IDs
✅ No duplicate IDs
✅ Continuous IDs
✅ No exact duplicates
✅ No normalized duplicates
✅ No same-intent duplicates
✅ Intent mappings
✅ Language balance
✅ Intent balance
✅ Language × Intent
✅ Question types
✅ Status
✅ Difficulty
✅ Ground truth
✅ Answers
✅ Attempts
✅ Question length
✅ Similarity < 0.85
----------------------------------------------------------------------------------------------------
Passed checks      : 21/21
Validation Score   : 100.0%
🟢 DATASET IS FULLY VALIDATED

====================================================================================================
📊 FINAL SUMMARY
====================================================================================================
Questions : 448

Languages:
language
English    112
Arabic     112
French     112
Russian    112

Intents:
intent_id
INT001    56
INT002    56
INT003    56
INT004    56
INT005    56
INT006    56
INT007    56
INT008    56

Language × Intent:
language   Arabic  English  French  Russian
intent_id
INT001         14       14      14       14
INT002         14       14      14       14
INT003         14       14      14       14
INT004         14       14      14       14
INT005         14       14      14       14
INT006         14       14      14       14
INT007         14       14      14       14
INT008         14       14      14       14

Question Types:
question_type
Paraphrased    180
Direct         148
Scenario       120

Status:
status
valid        224
generated    224

Difficulty:
difficulty
Easy    448

Similarity >= 0.85: 0

====================================================================================================
🔒 READ-ONLY CONFIRMATION
====================================================================================================
✅ hotel_faq_final.csv was NOT modified.
✅ No rows added.
✅ No rows deleted.
✅ No values changed.

====================================================================================================
🎉 COMPLETE 448-QUESTION AUDIT FINISHED
====================================================================================================

In [79]:
# ============================================================
# 🏨 HOTEL AI - ULTRA COMPLETE 448 DATASET AUDIT
# FULL STRUCTURAL + DATA QUALITY + DUPLICATE + SIMILARITY
# READ-ONLY - NO DATA MODIFICATION
# ============================================================

from pathlib import Path
from itertools import combinations
from difflib import SequenceMatcher

import pandas as pd
import numpy as np
import re
import unicodedata


# ============================================================
# 1. CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(
    "/Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent"
)

DATASET_PATH = (
    PROJECT_ROOT
    / "03_Structured_Data"
    / "CSV"
    / "final"
    / "hotel_faq_final.csv"
)

EXPECTED_ROWS = 448

EXPECTED_COLUMNS = [
    "faq_id",
    "intent_id",
    "language",
    "question_type",
    "question",
    "status",
    "intent_name",
    "ground_truth",
    "category",
    "source",
    "attempts",
    "difficulty",
    "answer",
]

EXPECTED_INTENTS = {
    "INT001": "hotel_location",
    "INT002": "hotel_category",
    "INT003": "reception_availability",
    "INT004": "check_in_time",
    "INT005": "check_out_time",
    "INT006": "early_check_in",
    "INT007": "late_check_out",
    "INT008": "identification_required",
}

EXPECTED_LANGUAGES = {
    "Arabic",
    "English",
    "French",
    "Russian",
}

VALID_QUESTION_TYPES = {
    "Direct",
    "Paraphrased",
    "Scenario",
}

VALID_STATUS = {
    "valid",
    "generated",
}

VALID_DIFFICULTY = {
    "Easy",
}

# Similarity review thresholds
SIMILARITY_REVIEW = 0.80
SIMILARITY_HIGH = 0.85
SIMILARITY_VERY_HIGH = 0.90
SIMILARITY_EXTREME = 0.95


# ============================================================
# 2. HEADER
# ============================================================

print("=" * 100)
print("🏨 HOTEL AI - ULTRA COMPLETE 448 DATASET AUDIT")
print("=" * 100)


# ============================================================
# 3. LOAD DATASET
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"❌ Project root not found:\n{PROJECT_ROOT}"
)

assert DATASET_PATH.exists(), (
    f"❌ Dataset not found:\n{DATASET_PATH}"
)

df = pd.read_csv(
    DATASET_PATH,
    encoding="utf-8-sig"
)

print("\n" + "=" * 100)
print("📂 PROJECT / DATASET")
print("=" * 100)

print(f"Project : {PROJECT_ROOT}")
print(f"Dataset : {DATASET_PATH}")
print(f"Rows    : {len(df)}")
print(f"Columns : {len(df.columns)}")


# ============================================================
# 4. CHECK REGISTRY
# ============================================================

checks = {}


# ============================================================
# 5. COLUMN CHECK
# ============================================================

columns_ok = (
    len(df.columns) == 13
    and df.columns.tolist() == EXPECTED_COLUMNS
)

checks["13 columns"] = columns_ok

print("\n" + "=" * 100)
print("🧪 1. COLUMN VALIDATION")
print("=" * 100)

if columns_ok:
    print("✅ All 13 required columns exist.")
    print("✅ Column order is correct.")
else:
    print("❌ Column validation failed.")


# ============================================================
# 6. ROW COUNT
# ============================================================

rows_ok = len(df) == EXPECTED_ROWS

checks["448 questions"] = rows_ok

print("\n" + "=" * 100)
print("📦 2. ROW COUNT")
print("=" * 100)

print(f"Total questions: {len(df)}")

if rows_ok:
    print("✅ Exactly 448 questions.")
else:
    print("❌ Dataset does not contain exactly 448 questions.")


# ============================================================
# 7. REQUIRED FIELD VALIDATION
# ============================================================

required_fields_ok = True

print("\n" + "=" * 100)
print("🧪 3. REQUIRED FIELD VALIDATION")
print("=" * 100)

for col in EXPECTED_COLUMNS:

    missing = int(
        df[col].isna().sum()
    )

    empty = int(
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    ok = (
        missing == 0
        and empty == 0
    )

    print(
        f"{'✅' if ok else '❌'} "
        f"{col:<15}"
        f"Missing: {missing:<4}"
        f"Empty: {empty:<4}"
    )

    if not ok:
        required_fields_ok = False

checks["Required fields complete"] = required_fields_ok


# ============================================================
# 8. NORMALIZATION FUNCTION
# ============================================================

def normalize_text(text):

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    )

    text = text.casefold()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# ============================================================
# 9. FAQ ID FORMAT
# ============================================================

print("\n" + "=" * 100)
print("🆔 4. FAQ ID VALIDATION")
print("=" * 100)

valid_id_format = (
    df["faq_id"]
    .astype(str)
    .str.fullmatch(r"FAQ\d{4}")
    .all()
)

duplicate_id_rows = df[
    df["faq_id"].duplicated(
        keep=False
    )
]

numeric_ids = pd.to_numeric(
    df["faq_id"]
    .astype(str)
    .str.extract(r"FAQ(\d{4})")[0],
    errors="coerce"
)

expected_ids = np.arange(
    1,
    EXPECTED_ROWS + 1
)

continuous_ids = (
    numeric_ids.notna().all()
    and
    numeric_ids.astype(int).tolist()
    == expected_ids.tolist()
)

checks["Valid FAQ ID format"] = bool(
    valid_id_format
)

checks["No duplicate FAQ IDs"] = (
    duplicate_id_rows.empty
)

checks["Continuous FAQ IDs"] = bool(
    continuous_ids
)

print(
    "✅ All FAQ IDs have valid format."
    if valid_id_format
    else "❌ Invalid FAQ IDs found."
)

print(
    "✅ No duplicate FAQ IDs."
    if duplicate_id_rows.empty
    else "❌ Duplicate FAQ IDs found."
)

print(
    "✅ IDs continuous: FAQ0001 → FAQ0448"
    if continuous_ids
    else "❌ IDs are not continuous."
)


# ============================================================
# 10. PREPARE NORMALIZED QUESTIONS
# ============================================================

df["_normalized_question"] = (
    df["question"]
    .map(normalize_text)
)


# ============================================================
# 11. EXACT DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("📝 5. EXACT QUESTION DUPLICATE CHECK")
print("=" * 100)

exact_duplicates = df[
    df["question"].duplicated(
        keep=False
    )
]

checks["No exact question duplicates"] = (
    exact_duplicates.empty
)

if exact_duplicates.empty:

    print("✅ No exact duplicate questions.")

else:

    print(
        exact_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )


# ============================================================
# 12. NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔎 6. NORMALIZED QUESTION DUPLICATE CHECK")
print("=" * 100)

normalized_duplicates = df[
    df["_normalized_question"].duplicated(
        keep=False
    )
]

checks["No normalized duplicates"] = (
    normalized_duplicates.empty
)

if normalized_duplicates.empty:

    print("✅ No normalized duplicate questions.")

else:

    print(
        normalized_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )


# ============================================================
# 13. SAME-INTENT NORMALIZED DUPLICATES
# ============================================================

print("\n" + "=" * 100)
print("🔍 7. DUPLICATES INSIDE SAME INTENT")
print("=" * 100)

same_intent_duplicates = df[
    df.duplicated(
        subset=[
            "intent_id",
            "_normalized_question",
        ],
        keep=False
    )
]

checks["No same-intent normalized duplicates"] = (
    same_intent_duplicates.empty
)

if same_intent_duplicates.empty:

    print(
        "✅ No normalized duplicates inside the same intent."
    )

else:

    print(
        same_intent_duplicates[
            [
                "faq_id",
                "intent_id",
                "language",
                "question",
            ]
        ].to_string(index=False)
    )


# ============================================================
# 14. INTENT ID ↔ NAME
# ============================================================

print("\n" + "=" * 100)
print("🔗 8. INTENT ID ↔ INTENT NAME")
print("=" * 100)

intent_mapping_ok = True

for intent_id, expected_name in EXPECTED_INTENTS.items():

    subset = df[
        df["intent_id"] == intent_id
    ]

    actual_names = set(
        subset["intent_name"]
        .astype(str)
    )

    ok = (
        len(subset) == 56
        and actual_names == {
            expected_name
        }
    )

    if not ok:
        intent_mapping_ok = False

    print(
        f"{'✅' if ok else '❌'} "
        f"{intent_id} → {expected_name}"
        f" | rows={len(subset)}"
    )

checks["Intent ID ↔ Name mappings"] = (
    intent_mapping_ok
)


# ============================================================
# 15. LANGUAGE DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🌍 9. LANGUAGE DISTRIBUTION")
print("=" * 100)

language_counts = (
    df["language"]
    .value_counts()
)

language_balance_ok = (
    set(language_counts.index)
    == EXPECTED_LANGUAGES
    and
    all(
        int(
            language_counts.get(
                language,
                0
            )
        ) == 112
        for language in EXPECTED_LANGUAGES
    )
)

checks["Language balance"] = (
    language_balance_ok
)

print(
    language_counts.to_string()
)

print(
    "✅ 112 × 4 languages."
    if language_balance_ok
    else "❌ Language balance failed."
)


# ============================================================
# 16. INTENT DISTRIBUTION
# ============================================================

print("\n" + "=" * 100)
print("🎯 10. INTENT DISTRIBUTION")
print("=" * 100)

intent_counts = (
    df["intent_id"]
    .value_counts()
)

intent_balance_ok = all(
    int(
        intent_counts.get(
            intent_id,
            0
        )
    ) == 56
    for intent_id in EXPECTED_INTENTS
)

checks["Intent balance"] = (
    intent_balance_ok
)

print(
    df.groupby(
        [
            "intent_id",
            "intent_name",
        ]
    )
    .size()
    .rename("questions")
    .reset_index()
    .to_string(index=False)
)

print(
    "✅ 56 × 8 intents."
    if intent_balance_ok
    else "❌ Intent balance failed."
)


# ============================================================
# 17. LANGUAGE × INTENT
# ============================================================

print("\n" + "=" * 100)
print("📊 11. LANGUAGE × INTENT MATRIX")
print("=" * 100)

language_intent = pd.crosstab(
    df["intent_id"],
    df["language"]
)

language_intent_ok = True

for intent_id in EXPECTED_INTENTS:

    for language in EXPECTED_LANGUAGES:

        value = int(
            language_intent.loc[
                intent_id,
                language
            ]
        )

        if value != 14:
            language_intent_ok = False

print(
    language_intent.to_string()
)

print(
    "✅ Every intent has 14 questions per language."
    if language_intent_ok
    else "❌ Language × Intent is not balanced."
)

checks["Language × Intent balance"] = (
    language_intent_ok
)


# ============================================================
# 18. QUESTION TYPES
# ============================================================

print("\n" + "=" * 100)
print("📝 12. QUESTION TYPE VALIDATION")
print("=" * 100)

question_type_counts = (
    df["question_type"]
    .value_counts()
)

invalid_question_types = (
    set(df["question_type"])
    - VALID_QUESTION_TYPES
)

question_types_ok = (
    not invalid_question_types
)

checks["Question types valid"] = (
    question_types_ok
)

print(
    question_type_counts.to_string()
)

print(
    "✅ All question types are valid."
    if question_types_ok
    else
    f"❌ Invalid question types: {invalid_question_types}"
)


# ============================================================
# 19. STATUS
# ============================================================

print("\n" + "=" * 100)
print("📌 13. STATUS VALIDATION")
print("=" * 100)

status_counts = (
    df["status"]
    .value_counts()
)

invalid_statuses = (
    set(df["status"])
    - VALID_STATUS
)

status_ok = (
    not invalid_statuses
)

checks["Status valid"] = (
    status_ok
)

print(
    status_counts.to_string()
)

print(
    "✅ Status values are valid."
    if status_ok
    else
    f"❌ Invalid status values: {invalid_statuses}"
)


# ============================================================
# 20. DIFFICULTY
# ============================================================

print("\n" + "=" * 100)
print("📌 14. DIFFICULTY VALIDATION")
print("=" * 100)

difficulty_counts = (
    df["difficulty"]
    .value_counts()
)

invalid_difficulties = (
    set(df["difficulty"])
    - VALID_DIFFICULTY
)

difficulty_ok = (
    not invalid_difficulties
)

checks["Difficulty valid"] = (
    difficulty_ok
)

print(
    difficulty_counts.to_string()
)

print(
    "✅ Difficulty values are valid."
    if difficulty_ok
    else
    f"❌ Invalid difficulty values: {invalid_difficulties}"
)


# ============================================================
# 21. GROUND TRUTH
# ============================================================

print("\n" + "=" * 100)
print("🎯 15. GROUND TRUTH / ANSWER COMPLETENESS")
print("=" * 100)

ground_truth_ok = (
    df["ground_truth"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

answer_ok = (
    df["answer"]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)

checks["Ground truth complete"] = (
    bool(ground_truth_ok)
)

checks["Answers complete"] = (
    bool(answer_ok)
)

print(
    "✅ Ground truth complete."
    if ground_truth_ok
    else "❌ Ground truth incomplete."
)

print(
    "✅ Answers complete."
    if answer_ok
    else "❌ Answers incomplete."
)


# ============================================================
# 22. GROUND TRUTH / ANSWER CONSISTENCY
# ============================================================

print("\n" + "=" * 100)
print("🔗 16. GROUND TRUTH ↔ ANSWER")
print("=" * 100)

gt_normalized = (
    df["ground_truth"]
    .map(normalize_text)
)

answer_normalized = (
    df["answer"]
    .map(normalize_text)
)

different_wording = (
    gt_normalized
    !=
    answer_normalized
)

same_exact_content = (
    gt_normalized
    ==
    answer_normalized
)

print(
    f"Rows with different normalized wording: "
    f"{int(different_wording.sum())}"
)

print(
    f"Rows with matching normalized wording : "
    f"{int(same_exact_content.sum())}"
)

print(
    "ℹ️ Different wording is informational only."
)


# ============================================================
# 23. ATTEMPTS
# ============================================================

print("\n" + "=" * 100)
print("🔢 17. ATTEMPTS VALIDATION")
print("=" * 100)

attempts_numeric = pd.to_numeric(
    df["attempts"],
    errors="coerce"
)

attempts_ok = (
    attempts_numeric.notna().all()
    and
    (attempts_numeric >= 0).all()
)

checks["Attempts valid"] = (
    bool(attempts_ok)
)

print(
    "✅ Attempts are numeric and non-negative."
    if attempts_ok
    else "❌ Invalid Attempts values."
)

print(
    f"Min    : {attempts_numeric.min()}"
)

print(
    f"Max    : {attempts_numeric.max()}"
)

print(
    f"Average: {attempts_numeric.mean():.2f}"
)


# ============================================================
# 24. QUESTION LENGTH
# ============================================================

print("\n" + "=" * 100)
print("📏 18. QUESTION LENGTH VALIDATION")
print("=" * 100)

question_lengths = (
    df["question"]
    .astype(str)
    .str.len()
)

very_short_questions = df[
    question_lengths < 10
]

question_length_ok = (
    very_short_questions.empty
)

checks["Question length valid"] = (
    question_length_ok
)

print(
    f"Shortest : {question_lengths.min()}"
)

print(
    f"Longest  : {question_lengths.max()}"
)

print(
    f"Average  : {question_lengths.mean():.2f}"
)

print(
    "✅ No suspiciously short questions."
    if question_length_ok
    else "⚠️ Suspiciously short questions found."
)


# ============================================================
# 25. WHITESPACE CHECK
# ============================================================

print("\n" + "=" * 100)
print("🧹 19. WHITESPACE / TEXT CLEANLINESS")
print("=" * 100)

leading_trailing = (
    df["question"]
    .astype(str)
    .map(
        lambda x: x != x.strip()
    )
)

double_spaces = (
    df["question"]
    .astype(str)
    .str.contains(
        r"\s{2,}",
        regex=True,
        na=False
    )
)

whitespace_ok = not (
    leading_trailing.any()
    or
    double_spaces.any()
)

checks["Whitespace cleanliness"] = (
    whitespace_ok
)

print(
    "✅ No obvious leading/trailing whitespace."
    if not leading_trailing.any()
    else
    f"⚠️ Leading/trailing whitespace rows: "
    f"{int(leading_trailing.sum())}"
)

print(
    "✅ No obvious repeated spaces."
    if not double_spaces.any()
    else
    f"⚠️ Repeated-space rows: "
    f"{int(double_spaces.sum())}"
)


# ============================================================
# 26. FULL PAIRWISE SIMILARITY
# ============================================================

print("\n" + "=" * 100)
print("🔍 20. FULL QUESTION SIMILARITY")
print("=" * 100)

questions = (
    df["question"]
    .astype(str)
    .tolist()
)

total_pairs = (
    EXPECTED_ROWS
    * (EXPECTED_ROWS - 1)
    // 2
)

print(
    f"Comparing {total_pairs:,} question pairs..."
)

similarity_pairs = []

for i, j in combinations(
    range(EXPECTED_ROWS),
    2
):

    score = SequenceMatcher(
        None,
        normalize_text(questions[i]),
        normalize_text(questions[j])
    ).ratio()

    if score >= SIMILARITY_REVIEW:

        similarity_pairs.append({
            "similarity": round(score, 3),

            "faq_id_1": df.iloc[i]["faq_id"],
            "intent_1": df.iloc[i]["intent_id"],
            "language_1": df.iloc[i]["language"],
            "question_1": questions[i],

            "faq_id_2": df.iloc[j]["faq_id"],
            "intent_2": df.iloc[j]["intent_id"],
            "language_2": df.iloc[j]["language"],
            "question_2": questions[j],
        })

similarity_df = pd.DataFrame(
    similarity_pairs
)


# ============================================================
# 27. THRESHOLDS
# ============================================================

print("\n" + "=" * 100)
print("📊 21. SIMILARITY THRESHOLD SUMMARY")
print("=" * 100)

for threshold in [
    SIMILARITY_REVIEW,
    SIMILARITY_HIGH,
    SIMILARITY_VERY_HIGH,
    SIMILARITY_EXTREME,
]:

    if similarity_df.empty:

        count = 0

    else:

        count = int(
            (
                similarity_df["similarity"]
                >= threshold
            ).sum()
        )

    print(
        f"{threshold:.2f}+ : {count} pairs"
    )


# ============================================================
# 28. SAME INTENT / CROSS INTENT
# ============================================================

if similarity_df.empty:

    same_intent = pd.DataFrame()
    cross_intent = pd.DataFrame()

else:

    same_intent = similarity_df[
        similarity_df["intent_1"]
        ==
        similarity_df["intent_2"]
    ]

    cross_intent = similarity_df[
        similarity_df["intent_1"]
        !=
        similarity_df["intent_2"]
    ]

print("\n" + "=" * 100)
print("🎯 SAME-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(same_intent)}"
)

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT SIMILARITY")
print("=" * 100)

print(
    f"Pairs >= 0.80: {len(cross_intent)}"
)


# ============================================================
# 29. TOP SIMILAR QUESTIONS
# ============================================================

print("\n" + "=" * 100)
print("📋 TOP 30 MOST SIMILAR QUESTIONS")
print("=" * 100)

if similarity_df.empty:

    print("None.")

else:

    print(
        similarity_df
        .sort_values(
            "similarity",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )


# ============================================================
# 30. HIGH SIMILARITY CHECK
# ============================================================

high_similarity = (
    similarity_df[
        similarity_df["similarity"]
        >= SIMILARITY_HIGH
    ]
    if not similarity_df.empty
    else pd.DataFrame()
)

checks["Similarity < 0.85"] = (
    high_similarity.empty
)

print("\n" + "=" * 100)
print("🚨 HIGH-SIMILARITY REVIEW")
print("=" * 100)

if high_similarity.empty:

    print(
        "✅ No similarity >= 0.85."
    )

else:

    print(
        f"❌ {len(high_similarity)} pairs "
        f"have similarity >= 0.85."
    )

    print(
        high_similarity
        .sort_values(
            "similarity",
            ascending=False
        )
        .to_string(index=False)
    )


# ============================================================
# 31. CROSS-INTENT HIGH SIMILARITY
# ============================================================

cross_intent_high = (
    cross_intent[
        cross_intent["similarity"]
        >= SIMILARITY_REVIEW
    ]
    if not cross_intent.empty
    else pd.DataFrame()
)

cross_intent_ok = (
    cross_intent_high.empty
)

checks["No cross-intent >= 0.80"] = (
    cross_intent_ok
)

print("\n" + "=" * 100)
print("⚠️ CROSS-INTENT REVIEW")
print("=" * 100)

if cross_intent_high.empty:

    print(
        "✅ No cross-intent similarity >= 0.80."
    )

else:

    print(
        f"❌ {len(cross_intent_high)} "
        f"cross-intent pairs >= 0.80."
    )

    print(
        cross_intent_high
        .sort_values(
            "similarity",
            ascending=False
        )
        .to_string(index=False)
    )


# ============================================================
# 32. FINAL SCORE
# ============================================================

print("\n" + "=" * 100)
print("🏆 FINAL VALIDATION SCORE")
print("=" * 100)

for name, result in checks.items():

    print(
        f"{'✅' if result else '❌'} {name}"
    )

passed_checks = sum(
    bool(value)
    for value in checks.values()
)

total_checks = len(checks)

validation_score = (
    passed_checks
    / total_checks
    * 100
)

print("-" * 100)

print(
    f"Passed checks      : "
    f"{passed_checks}/{total_checks}"
)

print(
    f"Validation Score   : "
    f"{validation_score:.1f}%"
)

if validation_score == 100:

    print(
        "🟢 DATASET IS FULLY VALIDATED"
    )

else:

    print(
        "🟡 DATASET NEEDS REVIEW"
    )


# ============================================================
# 33. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("📊 FINAL DATASET SUMMARY")
print("=" * 100)

print(
    f"Questions : {len(df)}"
)

print("\nLanguages:")
print(
    language_counts.to_string()
)

print("\nIntents:")
print(
    intent_counts.to_string()
)

print("\nLanguage × Intent:")
print(
    language_intent.to_string()
)

print("\nQuestion Types:")
print(
    question_type_counts.to_string()
)

print("\nStatus:")
print(
    status_counts.to_string()
)

print("\nDifficulty:")
print(
    difficulty_counts.to_string()
)

print(
    f"\nSimilarity >= 0.85 : "
    f"{len(high_similarity)}"
)

print(
    f"Cross-intent >= 0.80 : "
    f"{len(cross_intent_high)}"
)


# ============================================================
# 34. READ-ONLY CONFIRMATION
# ============================================================

print("\n" + "=" * 100)
print("🔒 READ-ONLY CONFIRMATION")
print("=" * 100)

print(
    "✅ hotel_faq_final.csv was NOT modified."
)

print(
    "✅ No rows were added."
)

print(
    "✅ No rows were deleted."
)

print(
    "✅ No values were changed."
)


# ============================================================
# 35. CLEAN TEMP COLUMN
# ============================================================

df.drop(
    columns=[
        "_normalized_question"
    ],
    inplace=True,
    errors="ignore"
)


print("\n" + "=" * 100)
print("🎉 COMPLETE 448-QUESTION ULTRA AUDIT FINISHED")
print("=" * 100)

====================================================================================================
🏨 HOTEL AI - ULTRA COMPLETE 448 DATASET AUDIT
====================================================================================================

====================================================================================================
📂 PROJECT / DATASET
====================================================================================================
Project : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent
Dataset : /Users/sondosahmed/Desktop/HotelAI-Intelligent-Agent/03_Structured_Data/CSV/final/hotel_faq_final.csv
Rows    : 448
Columns : 13

====================================================================================================
🧪 1. COLUMN VALIDATION
====================================================================================================
✅ All 13 required columns exist.
✅ Column order is correct.

====================================================================================================
📦 2. ROW COUNT
====================================================================================================
Total questions: 448
✅ Exactly 448 questions.

====================================================================================================
🧪 3. REQUIRED FIELD VALIDATION
====================================================================================================
✅ faq_id         Missing: 0   Empty: 0
✅ intent_id      Missing: 0   Empty: 0
✅ language       Missing: 0   Empty: 0
✅ question_type  Missing: 0   Empty: 0
✅ question       Missing: 0   Empty: 0
✅ status         Missing: 0   Empty: 0
✅ intent_name    Missing: 0   Empty: 0
✅ ground_truth   Missing: 0   Empty: 0
✅ category       Missing: 0   Empty: 0
✅ source         Missing: 0   Empty: 0
✅ attempts       Missing: 0   Empty: 0
✅ difficulty     Missing: 0   Empty: 0
✅ answer         Missing: 0   Empty: 0

====================================================================================================
🆔 4. FAQ ID VALIDATION
====================================================================================================
✅ All FAQ IDs have valid format.
✅ No duplicate FAQ IDs.
✅ IDs continuous: FAQ0001 → FAQ0448

====================================================================================================
📝 5. EXACT QUESTION DUPLICATE CHECK
====================================================================================================
✅ No exact duplicate questions.

====================================================================================================
🔎 6. NORMALIZED QUESTION DUPLICATE CHECK
====================================================================================================
✅ No normalized duplicate questions.

====================================================================================================
🔍 7. DUPLICATES INSIDE SAME INTENT
====================================================================================================
✅ No normalized duplicates inside the same intent.

====================================================================================================
🔗 8. INTENT ID ↔ INTENT NAME
====================================================================================================
✅ INT001 → hotel_location | rows=56
✅ INT002 → hotel_category | rows=56
✅ INT003 → reception_availability | rows=56
✅ INT004 → check_in_time | rows=56
✅ INT005 → check_out_time | rows=56
✅ INT006 → early_check_in | rows=56
✅ INT007 → late_check_out | rows=56
✅ INT008 → identification_required | rows=56

====================================================================================================
🌍 9. LANGUAGE DISTRIBUTION
====================================================================================================
language
English    112
Arabic     112
French     112
Russian    112
✅ 112 × 4 languages.

====================================================================================================
🎯 10. INTENT DISTRIBUTION
====================================================================================================
intent_id             intent_name  questions
   INT001          hotel_location         56
   INT002          hotel_category         56
   INT003  reception_availability         56
   INT004           check_in_time         56
   INT005          check_out_time         56
   INT006          early_check_in         56
   INT007          late_check_out         56
   INT008 identification_required         56
✅ 56 × 8 intents.

====================================================================================================
📊 11. LANGUAGE × INTENT MATRIX
====================================================================================================
language   Arabic  English  French  Russian
intent_id
INT001         14       14      14       14
INT002         14       14      14       14
INT003         14       14      14       14
INT004         14       14      14       14
INT005         14       14      14       14
INT006         14       14      14       14
INT007         14       14      14       14
INT008         14       14      14       14
✅ Every intent has 14 questions per language.

====================================================================================================
📝 12. QUESTION TYPE VALIDATION
====================================================================================================
question_type
Paraphrased    180
Direct         148
Scenario       120
✅ All question types are valid.

====================================================================================================
📌 13. STATUS VALIDATION
====================================================================================================
status
valid        224
generated    224
✅ Status values are valid.

====================================================================================================
📌 14. DIFFICULTY VALIDATION
====================================================================================================
difficulty
Easy    448
✅ Difficulty values are valid.

====================================================================================================
🎯 15. GROUND TRUTH / ANSWER COMPLETENESS
====================================================================================================
✅ Ground truth complete.
✅ Answers complete.

====================================================================================================
🔗 16. GROUND TRUTH ↔ ANSWER
====================================================================================================
Rows with different normalized wording: 407
Rows with matching normalized wording : 41
ℹ️ Different wording is informational only.

====================================================================================================
🔢 17. ATTEMPTS VALIDATION
====================================================================================================
✅ Attempts are numeric and non-negative.
Min    : 0
Max    : 6
Average: 0.30

====================================================================================================
📏 18. QUESTION LENGTH VALIDATION
====================================================================================================
Shortest : 31
Longest  : 186
Average  : 75.50
✅ No suspiciously short questions.

====================================================================================================
🧹 19. WHITESPACE / TEXT CLEANLINESS
====================================================================================================
✅ No obvious leading/trailing whitespace.
✅ No obvious repeated spaces.

====================================================================================================
🔍 20. FULL QUESTION SIMILARITY
====================================================================================================
Comparing 100,128 question pairs...

====================================================================================================
📊 21. SIMILARITY THRESHOLD SUMMARY
====================================================================================================
0.80+ : 33 pairs
0.85+ : 0 pairs
0.90+ : 0 pairs
0.95+ : 0 pairs

====================================================================================================
🎯 SAME-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 33

====================================================================================================
⚠️ CROSS-INTENT SIMILARITY
====================================================================================================
Pairs >= 0.80: 0

====================================================================================================
📋 TOP 30 MOST SIMILAR QUESTIONS
====================================================================================================
 similarity faq_id_1 intent_1 language_1                                                                                                          question_1 faq_id_2 intent_2 language_2                                                                                                                                 question_2
      0.843  FAQ0065   INT003    English                                                 What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0066   INT003    English                                                                What are the hours of operation for the reception desk at Nile Pearl Hotel?
      0.843  FAQ0065   INT003    English                                                 What are the operating hours for the reception at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.840  FAQ0202   INT007     Arabic                                            هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الشروط المطلوبة؟  FAQ0206   INT007     Arabic                                                         هل يمكنني طلب تسجيل خروج متأخر في Nile Pearl Hotel، وما الظروف التي يجب أن تتوافر؟
      0.839  FAQ0059   INT002    Russian                                                                    В каком классе отеля находится Nile Pearl Hotel?  FAQ0062   INT002    Russian                                                                                          Какой класс отеля принадлежит «Nile Pearl Hotel»?
      0.836  FAQ0008   INT001    English                                     For a trip to Egypt, which part of Cairo should I look for Nile Pearl Hotel in?  FAQ0386   INT001    English                                                                                 In which part of Cairo should I look for Nile Pearl Hotel?
      0.829  FAQ0004   INT001    English                                                                      In which city can I find the Nile Pearl Hotel?  FAQ0005   INT001    English                                                                                                     Where can I find the Nile Pearl Hotel?
      0.828  FAQ0121   INT004    Russian                                                                          Когда можно заселиться в Nile Pearl Hotel?  FAQ0125   INT004    Russian                                                                                Когда стандартно можно заселиться в отель Nile Pearl Hotel?
      0.827  FAQ0235   INT008     Arabic                                              هل يجب علي تقديم إثبات هوية ساري عند تسجيل الوصول في Nile Pearl Hotel?  FAQ0237   INT008     Arabic                                                         هل يحتاج الضيوف إلى تقديم وثائق إثبات الهوية عند تسجيل الوصول في Nile Pearl Hotel?
      0.824  FAQ0066   INT003    English                                         What are the hours of operation for the reception desk at Nile Pearl Hotel?  FAQ0067   INT003    English                                                                What are the availability hours for the reception desk at Nile Pearl Hotel?
      0.821  FAQ0098   INT004    English                                                         What time does check-in normally begin at Nile Pearl Hotel?  FAQ0100   INT004    English                                                                               What time is check-in usually available at Nile Pearl Hotel?
      0.818  FAQ0017   INT001     French                                                                              Où se trouve l'hôtel Nile Pearl Hotel?  FAQ0019   INT001     French                                                                                      Dans quelle zone se trouve l'hôtel Nile Pearl Hotel ?
      0.818  FAQ0223   INT007    Russian Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?  FAQ0224   INT007    Russian Могу ли я получить поздний выезд из Nile Pearl Hotel, и если это возможно, под какие условия и будут ли какие-либо дополнительные расходы?
      0.816  FAQ0025   INT001    Russian                                                                  По какому адресу находится отель Nile Pearl Hotel?  FAQ0260   INT001    Russian                                                                                    В каком районе города находится отель Nile Pearl Hotel?
      0.816  FAQ0027   INT001    Russian                                                                              Где расположен отель Nile Pearl Hotel?  FAQ0388   INT001    Russian                                                                                                   Где в Каире расположен Nile Pearl Hotel?
      0.816  FAQ0252   INT008    Russian                                                    Какое удостоверение личности принимается от гостя при заселении?  FAQ0416   INT008    Russian                                                                            Какой вид удостоверения личности требуется гостю при заселении?
      0.814  FAQ0233   INT008     Arabic                                        ما نوع مستند إثبات الهوية المقبول عند تسجيل الوصول في فندق Nile Pearl Hotel؟  FAQ0234   INT008     Arabic                                                                    ما هي وثائق إثبات الهوية المطلوبة عند تسجيل الوصول في Nile Pearl Hotel?
      0.814  FAQ0053   INT002     French                                                            Quelle est la categorisation étoile du Nile Pearl Hotel?  FAQ0423   INT002     French                                                                               Quelle est la classification hôtelière du Nile Pearl Hotel ?
      0.814  FAQ0222   INT007    Russian                      Могу ли я получить поздний выезд из Nile Pearl Hotel, и какие возможны дополнительные расходы?  FAQ0223   INT007    Russian                        Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, как это сделать и будут ли дополнительные расходы?
      0.812  FAQ0044   INT002     Arabic                                                               كم عدد النجوم التي يُصنَّف بها فندق Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                             كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.811  FAQ0274   INT005    English                                                         By what time do guests normally need to vacate their rooms?  FAQ0434   INT005    English                                                                                     By what time are guests expected to vacate their room?
      0.811  FAQ0001   INT001    English                                                                                  Where is Nile Pearl Hotel located?  FAQ0003   INT001    English                                                                                                 In which city is Nile Pearl Hotel located?
      0.810  FAQ0312   INT006    Russian                                          Я приеду раньше времени регистрации; смогу ли я заселиться в номер раньше?  FAQ0376   INT006    Russian                                                        Если я приеду раньше времени заезда, могу ли я попросить заселиться в номер раньше?
      0.809  FAQ0003   INT001    English                                                                          In which city is Nile Pearl Hotel located?  FAQ0258   INT001    English                                                                                     Which part of the city is Nile Pearl Hotel located in?
      0.807  FAQ0098   INT004    English                                                         What time does check-in normally begin at Nile Pearl Hotel?  FAQ0102   INT004    English                                                                                  At what time can I normally check in at Nile Pearl Hotel?
      0.805  FAQ0204   INT007     Arabic                       هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وما العوامل التي تحدد إمكانية ذلك؟  FAQ0205   INT007     Arabic                                                           هل يمكنني الحصول على تسجيل خروج متأخر في Nile Pearl Hotel، وهل توجد رسوم إضافية؟
      0.804  FAQ0251   INT008    Russian          Нужно ли предъявлять действительный документ, удостоверяющий личность, при регистрации в Nile Pearl Hotel?  FAQ0253   INT008    Russian                              Требуется ли гостям предъявлять документ, удостоверяющий личность, при регистрации заезда в Nile Pearl Hotel?
      0.804  FAQ0045   INT002     Arabic                                                                    ما فئة النجوم التي ينتمي إليها Nile Pearl Hotel؟  FAQ0261   INT002     Arabic                                                                                             كم عدد النجوم التي حصل عليها Nile Pearl Hotel؟
      0.804  FAQ0036   INT002    English                                                                What is the star classification of Nile Pearl Hotel?  FAQ0038   INT002    English                                                                                  What star classification is assigned to Nile Pearl Hotel?
      0.802  FAQ0217   INT007    Russian                               Могу ли я получить поздний выезд из Nile Pearl Hotel, и если да, что мне нужно знать?  FAQ0218   INT007    Russian                                                    Могу ли я получить поздний выезд из Nile Pearl Hotel, и под какие условия это возможно?
      0.800  FAQ0137   INT005     Arabic                                                  متى يجب على النزيل إتمام إجراءات تسجيل الخروج من Nile Pearl Hotel؟  FAQ0139   INT005     Arabic                                                                    متى يجب على الضيوف إتمام تسجيل الخروج المعتاد من فندق Nile Pearl Hotel؟

====================================================================================================
🚨 HIGH-SIMILARITY REVIEW
====================================================================================================
✅ No similarity >= 0.85.

====================================================================================================
⚠️ CROSS-INTENT REVIEW
====================================================================================================
✅ No cross-intent similarity >= 0.80.

====================================================================================================
🏆 FINAL VALIDATION SCORE
====================================================================================================
✅ 13 columns
✅ 448 questions
✅ Required fields complete